import json

# Load dictionary_1000.json
with open('app/src/main/assets/dictionary_1000.json', 'r', encoding='utf-8') as f:
    dict_data = json.load(f)

existing_words_set = set(x['word'].strip().lower() for x in dict_data)
print(f"Starting word count: {len(dict_data)}")

# Comprehensive list of authentic high-frequency exam words (BCS, Bank, Varsity Admission, GRE, IELTS)
batch3_raw = [
    # 1 - 50
    ("Aberration", "Noun", "/ˌæb.əˈreɪ.ʃən/ (অ্যাবারেশন)", "স্বাভাবিক পথ বা আচরণ থেকে বিচ্যুতি", ["Anomaly", "Deviation", "Divergence"], ["Normality", "Conformity"], "The sudden drop in scores was an aberration for the top student.", "শীর্ষ শিক্ষার্থীর জন্য স্কোরের হঠাৎ পতনটি ছিল একটি বিচ্যুতি।", "GRE & BCS"),
    ("Abscond", "Verb", "/əbˈskɒnd/ (আবসকন্ড)", "গোপনে পালিয়ে যাওয়া বা আত্মগোপন করা", ["Flee", "Escape", "Decamp"], ["Remain", "Stay", "Appear"], "The accountant tried to abscond with the company funds.", "হিসাবরক্ষণ কোম্পানি তহবিল নিয়ে গোপনে পালিয়ে যাওয়ার চেষ্টা করেছিল।", "Bank & BCS"),
    ("Abstemious", "Adjective", "/æbˈstiː.mi.əs/ (অ্যাবস্টিমিয়াস)", "আহার ও পানীয় গ্রহণে সংযমী", ["Temperate", "Moderate", "Ascetic"], ["Gluttonous", "Intemperate"], "Monks lead an abstemious life focused on spiritual growth.", "সন্ন্যাসীরা আধ্যাত্মিক উন্নতির দিকে মনোনিবেশ করে সংযমী জীবনযাপন করেন।", "GRE & BCS"),
    ("Acumen", "Noun", "/ˈæk.jə.mən/ (অ্যাকিউমেন)", "সূক্ষ্ম বিচারবুদ্ধি বা দ্রুত সিদ্ধান্ত নেওয়ার বিচক্ষণতা", ["Astuteness", "Shrewdness", "Insight"], ["Ignorance", "Obtuseness"], "Her commercial acumen turned the struggling business into a market leader.", "তাঁর বাণিজ্যিক বিচক্ষণতা মন্দাক্রান্ত ব্যবসাটিকে বাজার নেতায় পরিণত করেছে।", "Bank & Corporate"),
    ("Admonish", "Verb", "/ədˈmɒn.ɪʃ/ (এডমনিশ)", "মৃদু তিরস্কার করা বা সতর্ক করে দেওয়া", ["Reprimand", "Chide", "Warn"], ["Praise", "Applaud"], "The supervisor had to admonish the worker for arriving late.", "দেরিতে আসার জন্য সুপারভাইজারকে কর্মীকে মৃদু তিরস্কার করতে হয়েছিল।", "BCS & Bank"),
    ("Aggrandize", "Verb", "/əˈɡræn.daɪz/ (অ্যাগ্র্যান্ডাইজ)", "ক্ষমতা, পদমর্যাদা বা সম্পদ বৃদ্ধি করা", ["Exalt", "Elevate", "Enlarge"], ["Belittle", "Degrade"], "The ruler sought to aggrandize his empire through military conquest.", "শাসক সামরিক বিজয়ের মাধ্যমে তাঁর সাম্রাজ্য সম্প্রসারিত করতে চেয়েছিলেন।", "GRE & BCS"),
    ("Alacrity", "Noun", "/əˈlæk.rə.ti/ (অ্যালাক্রিটি)", "তৎপরতা বা উল্লাসভরা আগ্রহ", ["Eagerness", "Promptness", "Readiness"], ["Apathy", "Reluctance"], "The team responded to the client's request with remarkable alacrity.", "দলটি ক্লায়েন্টের অনুরোধে অসাধারণ তৎপরতার সাথে সাড়া দিয়েছিল।", "IELTS & GRE"),
    ("Anachronism", "Noun", "/əˈnæk.rə.nɪz.əm/ (অ্যানাক্রোনিজম)", "কালবৈষম্য বা বর্তমান সময়ের সাথে অপ্রাসঙ্গিক কিছু", ["Misplacement", "Solecism", "Incongruity"], ["Synchronism", "Timeliness"], "Using a dial-up modem today is a complete anachronism.", "আজ ডায়াল-আপ মডেম ব্যবহার করা একটি সম্পূর্ণ কালবৈষম্য।", "GRE & Admission"),
    ("Antipathy", "Noun", "/ænˈtɪp.ə.θi/ (অ্যান্টিপ্যাথি)", "তীব্র শত্রুভাব বা ঘৃণা", ["Hostility", "Aversion", "Animosity"], ["Sympathy", "Affinity"], "There is a deep-seated antipathy between the rival factions.", "প্রতিদ্বন্দ্বী দলগুলোর মধ্যে তীব্র শত্রুভাব রয়েছে।", "BCS & Bank"),
    ("Apathy", "Noun", "/ˈæp.ə.θi/ (অ্যাপাথি)", "উদাসীনতা বা কোনো বিষয়ে আগ্রহের অভাব", ["Indifference", "Unconcern", "Lethargy"], ["Enthusiasm", "Concern"], "Public apathy regarding local elections led to low voter turnout.", "স্থানীয় নির্বাচন নিয়ে জনগণের উদাসীনতা কম ভোটার উপস্থিতির কারণ হয়েছিল।", "BCS & Bank"),
    ("Arduous", "Adjective", "/ˈɑː.dʒu.əs/ (আর্ডুয়াস)", "কঠিন ও অতিরিক্ত শ্রমসাধ্য", ["Onerous", "Strenuous", "Grueling"], ["Easy", "Effortless"], "Building the mountain highway was an arduous task.", "পাহাড়ি মহাসড়ক নির্মাণ একটি অতিরিক্ত শ্রমসাধ্য কাজ ছিল।", "IELTS & GRE"),
    ("Ascetic", "Adjective", "/əˈset.ɪk/ (অ্যাসেটিক)", "কঠোর আত্মসংযমী বা কৃচ্ছ্রসাধনকারী", ["Austere", "Abstemious", "Puritanical"], ["Hedonistic", "Self-indulgent"], "He chose an ascetic lifestyle in a secluded monastery.", "তিনি একটি নির্জন আশ্রমে কৃচ্ছ্রসাধনকারী জীবনধারা বেছে নিয়েছিলেন।", "GRE & Admission"),
    ("Assiduous", "Adjective", "/əˈsɪd.ju.əs/ (অ্যাসিডুয়াস)", "অধ্যবসায়ী বা অত্যন্ত মনোযোগী", ["Diligent", "Meticulous", "Sedulous"], ["Lazy", "Negligent"], "Through assiduous practice, she became a master pianist.", "অধ্যবসায়ী অনুশীলনের মাধ্যমে তিনি একজন ওস্তাদ পিয়ানোবাদক হয়ে উঠেছিলেন।", "BCS & GRE"),
    ("Audacious", "Adjective", "/ɔːˈdeɪ.ʃəs/ (অডেশাস)", "দুঃসাহসী বা স্পর্ধাপূর্ণ", ["Bold", "Daring", "Intrepid"], ["Timid", "Cowardly"], "The young general executed an audacious surprise attack.", "তরুণ জেনারেল একটি দুঃসাহসী বিস্ময়কর আক্রমণ পরিচালনা করেছিলেন।", "BCS & GRE"),
    ("Austere", "Adjective", "/ɔːˈstɪər/ (অস্টিয়ার)", "কঠোর, অনালঙ্কার বা কৃচ্ছ্রতাপূর্ণ", ["Severe", "Stern", "Unadorned"], ["Lavish", "Ornate"], "The church was built in a plain, austere style.", "গির্জাটি একটি সাদামাটা, অনালঙ্কার শৈলীতে নির্মিত হয়েছিল।", "IELTS & BCS"),
    ("Banal", "Adjective", "/bəˈnɑːl/ (ব্যানাল)", "বস্তাপচা বা গতানুগতিক", ["Trite", "Hackneyed", "Commonplace"], ["Original", "Fresh"], "The novel received poor reviews for its banal plot line.", "এর বস্তাপচা কাহিনীর জন্য উপন্যাসটি বাজে পর্যালোচনা পেয়েছিল।", "GRE & BCS"),
    ("Belligerent", "Adjective", "/bəˈlɪdʒ.ər.ənt/ (বেলিজারেন্ট)", "যুদ্ধংদেহী বা আক্রমণাত্মক", ["Aggressive", "Combative", "Pugnacious"], ["Peaceful", "Conciliatory"], "The belligerent customer argued loudly with the store manager.", "যুদ্ধংদেহী গ্রাহকটি দোকান ব্যবস্থাপকের সাথে উচ্চস্বরে তর্ক করেছিল।", "BCS & Bank"),
    ("Benevolent", "Adjective", "/bəˈnev.əl.ənt/ (বেনেভোলেন্ট)", "দয়ালু বা পরোপকারী", ["Charitable", "Altruistic", "Philanthropic"], ["Malevolent", "Spiteful"], "The benevolent benefactor funded several local schools.", "দয়ালু দানবীর বেশ কয়েকটি স্থানীয় স্কুলে অর্থায়ন করেছিলেন।", "Admission & Bank"),
    ("Bolster", "Verb", "/ˈbəʊl.stər/ (বোলস্টার)", "শক্তিশালী করা বা চাঙ্গা করা", ["Strengthen", "Reinforce", "Fortify"], ["Undermine", "Weaken"], "The good news helped bolster investor confidence.", "ভালো খবরটি বিনিয়োগকারীদের আত্মবিশ্বাস চাঙ্গা করতে সাহায্য করেছিল।", "GRE & IELTS"),
    ("Bombastic", "Adjective", "/bɒmˈbæs.tɪk/ (বম্বাস্টিক)", "আড়ম্বরপূর্ণ শব্দবহুল কিন্তু সারবস্তুহীন", ["Pompous", "Grandiloquent", "Pretentious"], ["Restrained", "Simple"], "His bombastic rhetoric failed to impress the educated audience.", "তাঁর আড়ম্বরপূর্ণ ফাঁপা বক্তব্য শিক্ষিত দর্শকদের প্রভাবিত করতে ব্যর্থ হয়েছিল।", "GRE & Admission"),
    ("Candid", "Adjective", "/ˈkæn.dɪd/ (ক্যান্ডিড)", "স্পষ্টভাষী বা অমায়িক", ["Frank", "Outspoken", "Direct"], ["Evasive", "Guarded"], "She gave a candid answer during the live interview.", "সরাসরি সাক্ষাৎকারের সময় তিনি একটি স্পষ্টভাষী উত্তর দিয়েছিলেন।", "BCS & Bank"),
    ("Capricious", "Adjective", "/kəˈprɪʃ.əs/ (ক্যাপ্রিশাস)", "খামখেয়ালী বা পরিবর্তনশীল", ["Fickle", "Erratic", "Impulsive"], ["Predictable", "Stable"], "Market demand in the fashion industry can be highly capricious.", "ফ্যাশন শিল্পে বাজারের চাহিদা অত্যন্ত খামখেয়ালী হতে পারে।", "GRE & Admission"),
    ("Castigate", "Verb", "/ˈkæs.tɪ.ɡeɪt/ (ক্যাস্টিগেট)", "তীব্রভাবে সমালোচনা করা", ["Chastise", "Censure", "Reprimand"], ["Praise", "Extol"], "The news column castigated the administration for inaction.", "সংবাদপত্রের কলামটি নিষ্ক্রিয়তার জন্য প্রশাসনের তীব্র সমালোচনা করেছিল।", "GRE & BCS"),
    ("Caustic", "Adjective", "/ˈkɔː.stɪk/ (কস্টিক)", "কটূক্তিপূর্ণ বা কষাঘাতপূর্ণ", ["Sarcastic", "Acerbic", "Biting"], ["Gentle", "Mild"], "His caustic humor made some colleagues feel uncomfortable.", "তাঁর কটূক্তিপূর্ণ রসবোধ কিছু সহকর্মীকে অস্বস্তিতে ফেলেছিল।", "BCS & Bank"),
    ("Chicanery", "Noun", "/ʃɪˈkeɪ.nər.i/ (শিকেনারী)", "প্রতারণা বা চাতুরী", ["Trickery", "Deception", "Duplicity"], ["Honesty", "Truthfulness"], "Political chicanery undermined public trust in government.", "রাজনৈতিক চাতুরী সরকারের ওপর জনগণের বিশ্বাস ক্ষুণ্ন করেছিল।", "GRE & Bank"),
    ("Clandestine", "Adjective", "/klænˈdes.tɪn/ (ক্ল্যান্ডেস্টিন)", "গোপন বা অলক্ষ্যে সম্পাদিত", ["Secret", "Covert", "Surreptitious"], ["Overt", "Public"], "They carried out a clandestine operation under cover of night.", "তারা রাতের আঁধারে একটি গোপন অভিযান পরিচালনা করেছিল।", "BCS & IELTS"),
    ("Cogent", "Adjective", "/ˈkəʊ.dʒənt/ (কোজেন্ট)", "জোরালো ও যুক্তিযুক্ত", ["Compelling", "Persuasive", "Convincing"], ["Weak", "Unconvincing"], "The scientist presented cogent evidence supporting the theory.", "বিজ্ঞানী তত্ত্বটির সমর্থনে জোরালো প্রমাণ উপস্থাপন করেছিলেন।", "GRE & BCS"),
    ("Commensurate", "Adjective", "/kəˈmen.sjər.ət/ (কমেনশুরেট)", "সমানুপাতিক বা উপযুক্ত সামঞ্জস্যপূর্ণ", ["Proportional", "Equivalent"], ["Disproportionate"], "Benefits are commensurate with the responsibility of the post.", "সুযোগ-সুবিধা পদের দায়িত্বের সাথে সামঞ্জস্যপূর্ণ।", "Bank & Corporate"),
    ("Compendium", "Noun", "/kəmˈpen.di.əm/ (কমপেন্ডিয়াম)", "সারসংক্ষেপ বা সংকলন", ["Summary", "Digest", "Compilation"], ["Expansion"], "This volume is a handy compendium of civil engineering formulas.", "এই খণ্ডটি সিভিল ইঞ্জিনিয়ারিং সূত্রের একটি সুবিধাজনক সংকলন।", "GRE & Admission"),
    ("Complaisant", "Adjective", "/kəmˈpleɪ.zənt/ (কমপ্লেজেন্ট)", "পরের সন্তুষ্টিবিধানে ইচ্ছুক", ["Obliging", "Polite", "Submissive"], ["Refractory", "Uncooperative"], "Her complaisant nature made her popular among her peers.", "তাঁর বাধ্য স্বভাব তাঁকে সহকর্মীদের মাঝে জনপ্রিয় করে তুলেছিল।", "GRE & BCS"),
    ("Conciliatory", "Adjective", "/kənˈsɪl.i.ə.tər.i/ (কনসিলিয়েটরি)", "শান্তিদায়ক বা মীমাংসাকারী", ["Pacifying", "Appeasing", "Placatory"], ["Aggressive", "Provocative"], "He made a conciliatory gesture to end the longstanding rivalry.", "দীর্ঘদিনের প্রতিদ্বন্দ্বিতা দূর করতে তিনি এক শান্তিদায়ক পদক্ষেপ নিয়েছিলেন।", "BCS & Bank"),
    ("Condone", "Verb", "/kənˈdəʊn/ (কনডোন)", "উপেক্ষা করা বা ক্ষমা চোখে দেখা", ["Overlook", "Pardon", "Forgive"], ["Condemn", "Punish"], "Parents should not condone disrespectful behavior in children.", "বাবা-মায়ের উচিত নয় শিশুদের অমার্জিত আচরণ প্রশ্রয় দেওয়া।", "BCS & IELTS"),
    ("Confound", "Verb", "/kənˈfaʊnd/ (কনফাউন্ড)", "কিংকর্তব্যবিমূঢ় বা হতবুদ্ধি করা", ["Confuse", "Baffle", "Perplex"], ["Clarify", "Explain"], "The sudden policy change confounded political analysts.", "হঠাৎ নীতি পরিবর্তন রাজনৈতিক বিশ্লেষকদের হতবুদ্ধি করেছিল।", "GRE & Admission"),
    ("Connoisseur", "Noun", "/ˌkɒn.əˈsɜːr/ (কনয়সার)", "শিল্প বা রসবোধের সমঝদার", ["Expert", "Authority", "Judge"], ["Novice", "Amateur"], "She is a connoisseur of classical European architecture.", "তিনি ধ্রুপদী ইউরোপীয় স্থাপত্যের একজন সমঝদার।", "BCS & Bank"),
    ("Conundrum", "Noun", "/kəˈnʌn.drəm/ (কনানড্রাম)", "জটিল সমস্যা বা ধাঁধা", ["Puzzle", "Enigma", "Riddle"], ["Solution", "Resolution"], "Resolving the budget deficit is a complex financial conundrum.", "বাজেট ঘাটতি সমাধান করা একটি জটিল আর্থিক ধাঁধা।", "GRE & IELTS"),
    ("Copious", "Adjective", "/ˈkəʊ.pi.əs/ (কোপিয়াস)", "প্রচুর বা অঢেল", ["Abundant", "Plentiful", "Ample"], ["Meager", "Scanty"], "The garden yielded a copious harvest of fresh vegetables.", "বাগানটিতে তাজা শাকসবজির প্রচুর ফলন হয়েছিল।", "BCS & Bank"),
    ("Corroborate", "Verb", "/kəˈrɒb.ə.reɪt/ (করোবোরেট)", "সত্যতা সমর্থন বা সত্যায়ন করা", ["Confirm", "Verify", "Substantiate"], ["Refute", "Contradict"], "Witness accounts corroborated the driver's statement.", "সাক্ষীদের বিবরণ চালকের বক্তব্যকে সমর্থন করেছিল।", "GRE & Bank"),
    ("Credulous", "Adjective", "/ˈkred.jə.ləs/ (ক্রেডিউলাস)", "সহজ বিশ্বাসী", ["Gullible", "Naïve", "Trusting"], ["Skeptical", "Suspicious"], "Credulous investors fell victim to the fraudulent scheme.", "সহজ বিশ্বাসী বিনিয়োগকারীরা প্রতারণামূলক স্কিমের শিকার হয়েছিলেন।", "BCS & Admission"),
    ("Culpable", "Adjective", "/ˈkʌl.pə.bəl/ (কালপেবল)", "দণ্ডনীয় বা দায়ী", ["Blameworthy", "Guilty", "Liable"], ["Innocent", "Blameless"], "The driver was deemed culpable for causing the accident.", "দুর্ঘটনা ঘটানোর জন্য চালককে দায়ী বলে গণ্য করা হয়েছিল।", "BCS & Law"),
    ("Cursory", "Adjective", "/ˈkɜː.sər.i/ (কার্সরি)", "দ্রুত ও উপরভাসা", ["Hasty", "Superficial", "Casual"], ["Thorough", "Detailed"], "A cursory inspection revealed several minor defects.", "একটি উপরভাসা পরিদর্শন বেশ কয়েকটি ছোটখাটো ত্রুটি প্রকাশ করেছিল।", "BCS & Bank"),
    ("Dearth", "Noun", "/dɜːθ/ (ডার্থ)", "অভাব বা অপ্রতুলতা", ["Scarcity", "Lack", "Shortage"], ["Abundance", "Surfeit"], "There was a dearth of evidence to secure a conviction.", "দণ্ড নিশ্চিত করার মতো প্রমাণের অভাব ছিল।", "GRE & BCS"),
    ("Debacle", "Noun", "/deɪˈbɑː.kəl/ (ডেবাকল)", "বিপর্যয় বা সম্পূর্ণ ব্যর্থতা", ["Fiasco", "Disaster", "Collapse"], ["Success", "Triumph"], "The musical performance turned into an unmitigated debacle.", "সঙ্গীত পরিবেশনাটি একটি সম্পূর্ণ বিপর্যয়ে রূপ নিয়েছিল।", "GRE & Bank"),
    ("Decorum", "Noun", "/dɪˈkɔː.rəm/ (ডেকোরাম)", "শিষ্টাচার ও শোভনতা", ["Propriety", "Etiquette", "Dignity"], ["Impropriety", "Rudeness"], "Members must observe proper decorum during parliamentary debate.", "পার্লামেন্ট বিতর্কের সময় সদস্যদের সঠিক শিষ্টাচার বজায় রাখতে হবে।", "BCS & Bank"),
    ("Deference", "Noun", "/ˈdef.ər.əns/ (ডেফারেন্স)", "গুরুজনের প্রতি শ্রদ্ধা ও নতি স্বীকার", ["Respect", "Reverence", "Esteem"], ["Disrespect", "Defiance"], "He bowed his head in deference to the elder statesman.", "বয়োজ্যেষ্ঠ রাষ্ট্রনায়কের প্রতি শ্রদ্ধায় তিনি মাথা নোয়ালেন।", "BCS & IELTS"),
    ("Deleterious", "Adjective", "/ˌdel.ɪˈtɪə.ri.əs/ (ডেলিটেরিয়াস)", "ক্ষতিকর বা হানিকর", ["Harmful", "Detrimental", "Injurious"], ["Beneficial", "Salubrious"], "Pollution has a deleterious effect on urban wildlife.", "দূষণ নগর বন্যপ্রাণীর ওপর ক্ষতিকর প্রভাব ফেলে।", "GRE & BCS"),
    ("Demur", "Verb", "/dɪˈmɜːr/ (ডিমার)", "আপত্তি জানানো বা দ্বিধা করা", ["Object", "Protest", "Hesitate"], ["Agree", "Accept"], "She demurred when asked to sign the unverified contract.", "যাচাইহীন চুক্তিতে স্বাক্ষর করতে বলা হলে তিনি আপত্তি জানিয়েছিলেন।", "GRE & BCS"),
    ("Deride", "Verb", "/dɪˈraɪd/ (ডিরাইড)", "বিদ্রূপ বা উপহাস করা", ["Mock", "Ridicule", "Scorn"], ["Praise", "Applaud"], "Opponents derided his proposal as unrealistic dreamer fantasy.", "প্রতিপক্ষ তাঁর প্রস্তাবটিকে অবাস্তব কল্পনা বলে উপহাস করেছিল।", "GRE & Admission"),
    ("Desiccate", "Verb", "/ˈdes.ɪ.keɪt/ (ডেসেকেট)", "শুকিয়ে শুষ্ক করা", ["Dehydrate", "Dry out", "Parch"], ["Moisten", "Hydrate"], "The scorching sun will desiccate crops if rain does not fall.", "বৃষ্টি না হলে প্রখর সূর্য ফসল শুকিয়ে ফেলবে।", "GRE & Science"),
    ("Desultory", "Adjective", "/ˈdes.əl.tər.i/ (ডেসাল্টরি)", "এলোমেলো বা লক্ষ্যহীন", ["Aimless", "Haphazard", "Random"], ["Methodical", "Focused"], "He turned the pages in a desultory manner without reading.", "তিনি না পড়ে এলোমেলোভাবে বইয়ের পৃষ্ঠা উল্টাতে লাগলেন।", "GRE & BCS"),
    ("Diatribe", "Noun", "/ˈdaɪ.ə.traɪb/ (ডায়াট্রাইব)", "আক্রমণাত্মক বক্তব্য বা ভর্ৎসনা", ["Harangue", "Tirade", "Invective"], ["Praise", "Tribute"], "The article was a harsh diatribe against modern materialism.", "প্রবন্ধটি আধুনিক বস্তুবাদিতার বিরুদ্ধে একটি কড়া ভর্ৎসনা ছিল।", "GRE & BCS")
]

print(f"Loaded batch 3 sample list length: {len(batch3_raw)}")
