# coding=utf-8

BATCH9_EXTRA3 = [
    ('Absquatulate', 'Verb', '/æbˈskwɒt.jʊ.leɪt/ (আবস্কোয়াটিউলেট)', 'চম্পট দেওয়া বা দ্রুত কেটে পড়া', ['Abscond', 'Decamp', 'Flee'], ['Stay', 'Remain'], 'The thief absquatulate with the cash box before police arrived.', 'পুলিশ আসার আগেই চোর ক্যাশ বাক্স নিয়ে চম্পট দিয়েছিল।'),
    ('Aerolith', 'Noun', '/ˈeə.rə.lɪθ/ (এরোলিথ)', 'উল্কাপাতপ্রসূত পাথর, আকাশ থেকে পৃথিবীতে পতিত উল্কাখণ্ড', ['Meteorite', 'Shooting star stone'], ['Terrestrial rock'], 'The museum displayed a rare iron aerolith found in the desert.', 'জাদুঘরটি মরুভূমিতে পাওয়া একটি বিরল লোহার উল্কাপাতপ্রসূত পাথর প্রদর্শন করেছিল।'),
    ('Alimony', 'Noun', '/ˈæl.ɪ.mə.ni/ (অ্যালিমনি)', 'খোরপোষ বা জীবনধারণ ভাতা, বিচ্ছেদের পর প্রাপ্ত আইনি আর্থিক সহায়তা', ['Maintenance', 'Support', 'Spousal allowance'], ['Deprivation'], 'The court ordered him to pay monthly alimony to his former spouse.', 'আদালত তাকে তার সাবেক স্ত্রীকে মাসিক খোরপোষ বা জীবনধারণ ভাতা দেওয়ার নির্দেশ দিয়েছে।'),
    ('Alliterative', 'Adjective', '/əˈlɪt.ər.ə.tɪv/ (অ্যালিটারেটিভ)', 'অনুপ্রাসময়, একই ব্যঞ্জনবর্ণের ঘনঘন উচ্চারণে তৈরি সাহিত্যিক রূপ', ['Repetitive-sound', 'Poetic'], ['Unrhymed'], 'The poem used alliterative phrases to create a musical rhythm.', 'কবিতাটি একটি সুরময় ছন্দ তৈরি করতে অনুপ্রাসময় বাক্যাংশ ব্যবহার করেছিল।'),
    ('Altimetry', 'Noun', '/ælˈtɪm.ə.tri/ (অলটিমেট্রি)', 'উচ্চতা পরিমাপবিদ্যা, সমুদ্রপৃষ্ঠ থেকে উচ্চতা মাপার বিজ্ঞান', ['Altitude measurement', 'Elevation science'], ['Depth measurement'], 'Satellite altimetry accurately measures global sea level rise.', 'স্যাটেলাইট উচ্চতা পরিমাপবিদ্যা বিশ্বব্যাপী সমুদ্রের উচ্চতা বৃদ্ধি নির্ভুলভাবে পরিমাপ করে।'),
    ('Alveolar', 'Adjective', '/ælˈviː.ə.lər/ (অ্যালভিওলার)', 'দন্তমূলীয়, দন্তমূল ব্যবহার করে উচ্চারিত ধ্বনি বা ফুসফুসের বায়ুথলি সংক্রান্ত', ['Dental-root', 'Pulmonary'], ['Nasal'], "Sounds like 't' and 'd' are classified as alveolar consonants.", "'টি' এবং 'ডি' এর মতো শব্দগুলোকে দন্তমূলীয় ব্যঞ্জনবর্ণ হিসেবে শ্রেণীবদ্ধ করা হয়।"),
    ('Amanuensis', 'Noun', '/əˌmæn.juˈen.sɪs/ (অ্যামানিউয়েনসিস)', 'শ্রুতলেখক, অন্য ব্যক্তির মুখে বলা কথা দেখে দেখে লেখালোক', ['Scribe', 'Secretary', 'Transcriber'], ['Author'], 'The blind poet dictated his epic verses to his loyal amanuensis.', 'অন্ধ কবি তার বিশ্বস্ত শ্রুতলেখক এর কাছে তার মহাকাব্যিক শ্লোকগুলো নির্দেশ করেছিলেন।'),
    ('Amphitheater', 'Noun', '/ˈæm.fɪˌθɪə.tər/ (অ্যামফিথিয়েটার)', 'গ্যালারিযুক্ত খোলা নাট্যশালা, বৃত্তাকার মুক্তমঞ্চ', ['Auditorium', 'Arena', 'Colosseum'], ['Closed room'], 'The band performed an acoustic concert in the ancient Greek amphitheater.', 'ব্যান্ডটি প্রাচীন গ্রীক গ্যালারিযুক্ত খোলা নাট্যশালা এ একটি শব্দময় কনসার্ট উপস্থাপন করেছিল।'),
    ('Anthropocentric', 'Adjective', '/ˌæn.θrə.pəʊˈsen.trɪk/ (অ্যানথ্রোপোসেন্ট্রিক)', 'মানবকেন্দ্রিক দৃষ্টিভঙ্গি, মানুষকে বিশ্বজগতের কেন্দ্রে বিবেচনা করা', ['Human-centered', 'Egoistic'], ['Biocentric'], 'An anthropocentric view places human needs above environmental health.', 'একটি মানবকেন্দ্রিক দৃষ্টিভঙ্গি পরিবেশগত স্বাস্থ্যের ওপরে মানুষের চাহিদাকে স্থান দেয়।'),
]
