import json, re

# 1. Collect existing words
existing_words = set()

try:
    with open('app/src/main/assets/dictionary_1000.json', 'r') as f:
        data = json.load(f)
        for w in data:
            if 'word' in w and isinstance(w['word'], str):
                existing_words.add(w['word'].strip().lower())
except Exception as e:
    print("Error reading assets json:", e)

try:
    with open('app/src/main/java/com/example/ui/screens/tools/VocabularyDataPacks.kt', 'r') as f:
        content = f.read()
        for m in re.findall(r'VocabWord\s*\(\s*\"[^\"]+\"\s*,\s*\"([^\"]+)\"', content):
            existing_words.add(m.strip().lower())
except Exception as e:
    print("Error reading DataPacks:", e)

try:
    with open('app/src/main/java/com/example/ui/screens/tools/VocabularyHighFrequencyDataset.kt', 'r') as f:
        content = f.read()
        for t in re.findall(r'Triple\s*\(\s*\"([^\"]+)\"', content):
            existing_words.add(t.strip().lower())
except Exception as e:
    print("Error reading HighFreq:", e)

print(f"Total existing unique words: {len(existing_words)}")

# List of 300 accurate, non-duplicate words with complete information
raw_data = [
    # Spoken & Daily Life
    ("Abundant", "/əˈbʌn.dənt/ (অ্যাবান্ডেন্ট)", "Adj", "প্রচুর, প্রভূত", "We have abundant evidence to support the claim.", "দাবিটি সমর্থন করার জন্য আমাদের কাছে প্রচুর প্রমাণ রয়েছে।", ["Plentiful", "Ample"], ["Scarce", "Meager"], "Spoken"),
    ("Accede", "/ækˈsiːd/ (অ্যাকসিড)", "Verb", "সম্মত হওয়া, রাজি হওয়া", "The manager acceded to our request.", "ম্যানেজার আমাদের অনুরোধে সম্মত হন।", ["Agree", "Consent"], ["Refuse", "Deny"], "Spoken"),
    ("Acclimatize", "/əˈklaɪ.mə.taɪz/ (অ্যাক্লাইমেটাইজ)", "Verb", "নতুন জলবায়ুতে খাপ খাইয়ে নেওয়া", "It takes time to acclimatize to cold weather.", "শীতল আবহাওয়ায় খাপ খাইয়ে নিতে সময় লাগে।", ["Adapt", "Adjust"], [], "Spoken"),
    ("Accomplice", "/əˈkʌm.plɪs/ (অ্যাকমপ্লিস)", "Noun", "অপকর্মের সহযোগী", "The thief was arrested with his accomplice.", "চোরটিকে তার অপরাধের সহযোগীসহ গ্রেপ্তার করা হয়েছিল।", ["Partner", "Associate"], ["Opponent"], "Spoken"),
    ("Acquittal", "/əˈkwɪt.əl/ (অ্যাকুইটাল)", "Noun", "খলাস, নির্দোষ প্রমাণ", "The trial ended in his acquittal.", "বিচারটি তার বেকসুর খালাসের মাধ্যমে শেষ হয়েছিল।", ["Absolution", "Exoneration"], ["Conviction"], "BCS"),
    ("Acrimonious", "/ˌæk.rɪˈməʊ.ni.əs/ (অ্যাক্রিমোনিয়াস)", "Adj", "তিক্ততাপূর্ণ, উগ্র", "They had an acrimonious dispute over money.", "টাকা নিয়ে তাদের মধ্যে তিক্ততাপূর্ণ বিবাদ হয়েছিল।", ["Bitter", "Hostile"], ["Harmonious", "Friendly"], "IELTS"),
    ("Actuate", "/ˈæk.tʃu.eɪt/ (অ্যাকচুয়েট)", "Verb", "সক্রিয় করা, চালিত করা", "The engine is actuated by electricity.", "ইঞ্জিনটি বিদ্যুৎ দ্বারা চালিত হয়।", ["Activate", "Trigger"], ["Deactivate"], "Academic"),
    ("Adage", "/ˈæd.ɪdʒ/ (অ্যাডেজ)", "Noun", "প্রবাদ, প্রবচন", "Remember the old adage, haste makes waste.", "পুরোনো প্রবাদটি মনে রাখবেন, অতি চালাকের গলায় দড়ি।", ["Proverb", "Saying"], [], "Spoken"),
    ("Adamant", "/ˈæd.ə.mənt/ (অ্যাডাম্যান্ট)", "Adj", "অনমনীয়, অটল", "He was adamant about his decision.", "তিনি তার সিদ্ধান্তের ব্যাপারে অনমনীয় ছিলেন।", ["Unyielding", "Firm"], ["Flexible", "Yielding"], "Spoken"),
    ("Adequacy", "/ˈæd.ə.kwə.si/ (অ্যাডিকুয়েসি)", "Noun", "পর্যাপ্ততা, উপযুক্ততা", "There are doubts about the adequacy of resources.", "সম্পদের পর্যাপ্ততা নিয়ে সন্দেহ রয়েছে।", ["Sufficiency", "Competence"], ["Inadequacy"], "IELTS"),
    ("Adhere", "/ədˈhɪər/ (অ্যাডহিয়ার)", "Verb", "লেগে থাকা, নিয়ম মেনে চলা", "We must adhere to the safety guidelines.", "আমাদের অবশ্যই নিরাপত্তা নির্দেশিকা মেনে চলতে হবে।", ["Comply", "Follow"], ["Violate", "Flout"], "Spoken"),
    ("Adjacent", "/əˈdʒeɪ.sənt/ (অ্যাডজেসেন্ট)", "Adj", "সংলগ্ন, পাশে অবস্থিত", "Their house is adjacent to the park.", "তাদের বাড়িটি পার্কের সংলগ্ন।", ["Next", "Adjoining"], ["Distant", "Remote"], "Spoken"),
    ("Adjourn", "/əˈdʒɜːn/ (অ্যাডজার্ন)", "Verb", "স্থগিত রাখা, মুলতবি করা", "The court was adjourned until Monday.", "আদালত সোমবার পর্যন্ত মুলতবি করা হয়েছিল।", ["Postpone", "Delay"], ["Convene", "Start"], "BCS"),
    ("Adjunct", "/ˈædʒ.ʌŋkt/ (অ্যাডজাঙ্কট)", "Noun", "আনুষঙ্গিক বস্তু, সহযোগী", "Online learning is a useful adjunct to school.", "অনলাইন শিক্ষা স্কুলের জন্য একটি দরকারী সহযোগী।", ["Addition", "Supplement"], [], "Academic"),
    ("Admonition", "/ˌæd.məˈnɪʃ.ən/ (অ্যাডমনিশন)", "Noun", "মৃদু তিরস্কার, সতর্কবার্তা", "He accepted the admonition with grace.", "তিনি মার্জিতভাবে সতর্কবার্তাটি গ্রহণ করেছিলেন।", ["Warning", "Advice"], ["Praise"], "Academic"),
    ("Adorn", "/əˈdɔːn/ (অ্যাডর্ন)", "Verb", "সাজানো, অলঙ্কৃত করা", "Flowers adorned the celebration hall.", "ফুল দিয়ে অনুষ্ঠান কক্ষটি সাজানো হয়েছিল।", ["Decorate", "Embellish"], ["Disfigure"], "Spoken"),
    ("Adroit", "/əˈdrɔɪt/ (অ্যাড্রয়েট)", "Adj", "দক্ষ, চতুর", "He is adroit at handling tricky questions.", "তিনি জটিল প্রশ্ন মোকাবিলায় দক্ষ।", ["Skillful", "Clever"], ["Clumsy", "Awkward"], "IELTS"),
    ("Adulation", "/ˌæd.jəˈleɪ.ʃən/ (অ্যাডুলেশন)", "Noun", "অতিরিক্ত তোষামোদ", "The star enjoyed the adulation of fans.", "তারকা ভক্তদের অতিরিক্ত প্রশংসায় মেতেছিলেন।", ["Flattery", "Worship"], ["Criticism"], "BCS"),
    ("Adversary", "/ˈæd.və.sər.i/ (অ্যাডভার্সারি)", "Noun", "প্রতিপক্ষ, শত্রু", "He defeated his political adversary.", "তিনি তার রাজনৈতিক প্রতিপক্ষকে পরাজিত করেছেন।", ["Opponent", "Rival"], ["Ally", "Friend"], "IELTS"),
    ("Adversity", "/ədˈvɜː.sə.ti/ (অ্যাডভার্সিটি)", "Noun", "প্রতিকূলতা, দুর্দশা", "Courage helps us overcome adversity.", "সাহস আমাদের প্রতিকূলতা কাটিয়ে উঠতে সাহায্য করে।", ["Hardship", "Misfortune"], ["Prosperity"], "BCS"),
    ("Aegis", "/ˈiː.dʒɪs/ (ইজিস)", "Noun", "ছত্রছায়া, অভিভাবকত্ব", "The project was launched under the aegis of UN.", "প্রকল্পটি জাতিসংঘের ছত্রছায়ায় শুরু হয়েছিল।", ["Protection", "Sponsorship"], [], "BCS"),
    ("Affable", "/ˈæf.ə.bəl/ (অ্যাফাবল)", "Adj", "বন্ধুবৎসল, অমায়িক", "Our new manager is very affable.", "আমাদের নতুন ম্যানেজার খুবই অমায়িক।", ["Friendly", "Genial"], ["Unfriendly", "Aloof"], "Spoken"),
    ("Affidavit", "/ˌæf.ɪˈdeɪ.vɪt/ (অ্যাফিডেভিট)", "Noun", "হলফনামা, শপথপত্র", "She signed an affidavit for court.", "তিনি আদালতের জন্য একটি হলফনামায় স্বাক্ষর করেছিলেন।", ["Testimony", "Pledge"], [], "BCS"),
    ("Affinity", "/əˈfɪn.ə.ti/ (অ্যাফিনিটি)", "Noun", "গভীর টান, সাদৃশ্য", "He has a natural affinity for music.", "সংগীতের প্রতি তার স্বাভাবিক টান রয়েছে।", ["Attraction", "Closeness"], ["Aversion"], "IELTS"),
    ("Affliction", "/əˈflɪk.ʃən/ (অ্যাফ্লিকশন)", "Noun", "যন্ত্রণা, কষ্ট", "Pain is a sad affliction of old age.", "যন্ত্রণা বার্ধক্যের একটি দুঃখজনক কষ্ট।", ["Suffering", "Distress"], ["Comfort", "Joy"], "Academic"),
    ("Affluent", "/ˈæf.lu.ənt/ (অ্যাফ্লুয়েন্ট)", "Adj", "সমৃদ্ধ, বিত্তশালী", "They live in an affluent neighborhood.", "তারা একটি বিত্তশালী এলাকায় বাস করে।", ["Wealthy", "Prosperous"], ["Poor", "Needy"], "IELTS"),
    ("Affront", "/əˈfrʌnt/ (অ্যাফ্রন্ট)", "Noun", "অপমান, অবমাননা", "His remark was an affront to our dignity.", "তার মন্তব্যটি আমাদের মর্যাদার প্রতি এক অপমান ছিল।", ["Insult", "Offense"], ["Respect", "Honor"], "Academic"),
    ("Aggrandize", "/əˈɡræn.daɪz/ (অ্যাগ্র্যান্ডাইজ)", "Verb", "ক্ষমতা বা মর্যাদা বৃদ্ধি করা", "He sought to aggrandize his reputation.", "তিনি তার খ্যাতি বৃদ্ধি করতে চেয়েছিলেন।", ["Promote", "Exalt"], ["Belittle"], "Academic"),
    ("Aggrieve", "/əˈɡriːv/ (অ্যাগ্রিভ)", "Verb", "ব্যথিত করা, অন্যায় করা", "The employees felt aggrieved by the pay cut.", "বেতন কমানোর কারণে কর্মীরা ব্যথিত অনুভব করেছিলেন।", ["Distress", "Injure"], ["Please"], "Academic"),
    ("Agility", "/əˈdʒɪl.ə.ti/ (অ্যাজিলিটি)", "Noun", "চপলতা, ক্ষিপ্রতা", "Athletes need great agility and strength.", "অ্যাথলিটদের দুর্দান্ত ক্ষিপ্রতা এবং শক্তি প্রয়োজন।", ["Nimbleness", "Quickness"], ["Sluggishness"], "Spoken"),
    ("Agitate", "/ˈædʒ.ɪ.teɪt/ (অ্যাজিটেট)", "Verb", "উত্তেজিত করা, আন্দোলন করা", "The news agitated the crowd.", "খবরটি জনতাকে উত্তেজিত করেছিল।", ["Disturb", "Rouse"], ["Calm", "Soothe"], "IELTS"),
    ("Agnostic", "/æɡˈnɒs.tɪk/ (অ্যাগনস্টিক)", "Noun", "অজ্ঞেয়বাদী", "He describes himself as an agnostic.", "তিনি নিজেকে অজ্ঞেয়বাদী হিসেবে বর্ণনা করেন।", ["Skeptic", "Doubter"], ["Believer"], "Academic"),
    ("Agrarian", "/əˈɡreə.ri.ən/ (অ্যাগ্রেরিয়ান)", "Adj", "কৃষি সংক্রান্ত", "The country has an agrarian economy.", "দেশটির একটি কৃষিভিত্তিক অর্থনীতি রয়েছে।", ["Agricultural", "Farming"], ["Industrial"], "BCS"),
    ("Alacrity", "/əˈlæk.rə.ti/ (অ্যাল্যাক্রিটি)", "Noun", "তৎপরতা, চপলতা", "He agreed to help with alacrity.", "তিনি সানন্দে সাহায্য করতে সম্মত হন।", ["Promptness", "Eagerness"], ["Reluctance"], "BCS"),
    ("Alibi", "/ˈæl.ɪ.baɪ/ (অ্যালিবাই)", "Noun", "ঘটনাস্থলে অনুপস্থিতির প্রমাণ", "The suspect had a solid alibi.", "সন্দেহভাজনের একটি শক্তিশালী অলিবাই ছিল।", ["Defense", "Plea"], [], "Spoken"),
    ("Alienate", "/ˈeɪ.li.ə.neɪt/ (এলিয়েনেট)", "Verb", "পর করে দেওয়া, বিচ্ছিন্ন করা", "His harsh words alienated his friends.", "তার কঠোর কথা বন্ধুদের দূরে ঠেলে দিয়েছিল।", ["Estrange", "Isolate"], ["Unite", "Endear"], "Spoken"),
    ("Align", "/əˈlaɪn/ (অ্যালাইন)", "Verb", "সারিভিত্তিক করা, সারিবদ্ধ করা", "Align the icons properly on screen.", "পর্দায় আইকনগুলো সঠিকভাবে সারিবদ্ধ করুন।", ["Arrange", "Coordinate"], ["Disarrange"], "Spoken"),
    ("Allegation", "/ˌæl.ɪˈɡeɪ.ʃən/ (অ্যালিগেশন)", "Noun", "অভিযোগ, দাবি", "He denied all the allegations.", "তিনি সব অভিযোগ অস্বীকার করেছেন।", ["Accusation", "Charge"], ["Denial"], "BCS"),
    ("Allegiance", "/əˈliː.dʒəns/ (অ্যালিজেন্স)", "Noun", "আনুগত্য, নিষ্ঠা", "Soldiers swear allegiance to the nation.", "সৈন্যরা দেশের প্রতি আনুগত্যের শপথ নেয়।", ["Loyalty", "Fidelity"], ["Treason", "Disloyalty"], "BCS"),
    ("Allegory", "/ˈæl.ə.ɡər.i/ (অ্যালিগরি)", "Noun", "রূপক কাহিনী", "The novel is a political allegory.", "উপন্যাসটি একটি রাজনৈতিক রূপক কাহিনী।", ["Parable", "Symbolic story"], [], "Academic"),
    ("Alleviation", "/əˌliː.viˈeɪ.ʃən/ (অ্যালিভিয়েশন)", "Noun", "উপশম, প্রশমন", "Poverty alleviation is our primary goal.", "দারিদ্র্য বিমোচন আমাদের প্রধান লক্ষ্য।", ["Relief", "Reduction"], ["Worsening"], "IELTS"),
    ("Alliance", "/əˈlaɪ.əns/ (অ্যালায়েন্স)", "Noun", "জোট, মিত্রতা", "The two nations formed a military alliance.", "দুই দেশ সামরিক জোট গঠন করেছিল।", ["Coalition", "Union"], ["Antagonism"], "BCS"),
    ("Allude", "/əˈluːd/ (অ্যালুড)", "Verb", "পরোক্ষভাবে ইঙ্গিত করা", "He alluded to his painful past.", "তিনি তার অতীত কষ্টের দিকে পরোক্ষ ইঙ্গিত করেছিলেন।", ["Hint", "Intimate"], ["Declare"], "Academic"),
    ("Allure", "/əˈlʊər/ (অ্যালুর)", "Noun", "প্রলোভন, আকর্ষণ", "The allure of the city drew many youths.", "শহরের আকর্ষণ অনেক তরুণকে টেনে এনেছিল।", ["Attraction", "Charm"], ["Repulsion"], "IELTS"),
    ("Aloof", "/əˈluːf/ (অ্যালুফ)", "Adj", "একাকী, দূরে সরে থাকা", "He stayed aloof from the discussion.", "তিনি আলোচনা থেকে দূরে সরে থাকেন।", ["Distant", "Detached"], ["Friendly", "Sociable"], "Spoken"),
    ("Altercation", "/ˌɒl.təˈkeɪ.ʃən/ (অল্টারকেশন)", "Noun", "তপ্ত বাকবিতণ্ডা", "They had a heated altercation outside.", "বাইরে তাদের মধ্যে উত্তপ্ত বাকবিতণ্ডা হয়েছিল।", ["Quarrel", "Argument"], ["Agreement"], "BCS"),
    ("Altruistic", "/ˌæl.truˈɪs.tɪk/ (অ্যালট্রুইস্টিক)", "Adj", "পরোপকারী, নিঃস্বার্থ", "She performed altruistic acts of kindness.", "তিনি নিঃস্বার্থ দয়ার কাজ করেছেন।", ["Charitable", "Selfless"], ["Selfish"], "IELTS"),
    ("Amalgamate", "/əˈmæl.ɡə.meɪt/ (অ্যাম্যালগামেট)", "Verb", "একত্রিত করা, মিশিয়ে ফেলা", "The two companies decided to amalgamate.", "প্রতিষ্ঠান দুটি একত্রিত হওয়ার সিদ্ধান্ত নিয়েছে।", ["Merge", "Combine"], ["Separate", "Divide"], "IELTS"),
    ("Amass", "/əˈmæs/ (অ্যামাস)", "Verb", "পুঞ্জীভূত করা, জমা করা", "He amassed a fortune through business.", "তিনি ব্যবসার মাধ্যমে প্রচুর অর্থ সঞ্চয় করেছিলেন।", ["Gather", "Accumulate"], ["Disperse", "Squander"], "BCS"),
    ("Ambidextrous", "/ˌæm.bɪˈdek.strəs/ (অ্যাম্বিডেক্সট্রাস)", "Adj", "সব্যসাচী, উভয় হাত সমানভাবে চালাতে সক্ষম", "The artist is ambidextrous.", "শিল্পী উভয় হাতেই লিখতে সক্ষম।", ["Versatile"], [], "Academic"),
    ("Ambience", "/ˈæm.bi.əns/ (অ্যাম্বিয়েন্স)", "Noun", "পরিবেশ, মেজাজ", "The restaurant has a cozy ambience.", "রেস্তোরাঁটিতে একটি আরামদায়ক পরিবেশ রয়েছে।", ["Atmosphere", "Aura"], [], "Spoken"),
    ("Ambiguity", "/ˌæm.bɪˈɡjuː.ə.ti/ (অ্যাম্বিগুইটি)", "Noun", "অস্পষ্টতা, দ্ব্যর্থকতা", "Avoid ambiguity in legal documents.", "আইনি নথিতে অস্পষ্টতা এড়িয়ে চলুন।", ["Uncertainty", "Vagueness"], ["Clarity"], "IELTS"),
    ("Ambivalent", "/æmˈbɪv.ə.lənt/ (অ্যাম্বিভালেন্ট)", "Adj", "দ্বিধাগ্রস্ত, মিশ্র অনুভূতিসম্পন্ন", "She holds ambivalent feelings about moving.", "স্থানান্তরের বিষয়ে তার মিশ্র অনুভূতি রয়েছে।", ["Undecided", "Uncertain"], ["Certain", "Decisive"], "IELTS"),
    ("Amble", "/ˈæm.bəl/ (অ্যাম্বল)", "Verb", "ধীরে সুস্থে হাঁটা", "They ambled along the river bank.", "তারা নদীর তীর ধরে ধীরে সুস্থে হাঁটছিল।", ["Stroll", "Saunter"], ["Rush", "Hurry"], "Spoken"),
    ("Amelioration", "/əˌmiː.li.əˈreɪ.ʃən/ (অ্যামিলিওরেশন)", "Noun", "উন্নতি, কল্যাণসাধন", "The policy led to an amelioration of conditions.", "নীতিটি পরিস্থিতির উন্নতি ঘটিয়েছিল।", ["Improvement", "Betterment"], ["Deterioration"], "Academic"),
    ("Amenable", "/əˈmiː.nə.bəl/ (অ্যামেনেবল)", "Adj", "বাধ্য, সহজে রাজি হওয়ার যোগ্য", "He is amenable to reasonable suggestions.", "তিনি যৌক্তিক পরামর্শে সম্মত হতে রাজি।", ["Receptive", "Responsive"], ["Uncooperative"], "BCS"),
    ("Amend", "/əˈmend/ (অ্যামেন্ড)", "Verb", "সংশোধন করা", "The law was amended to protect workers.", "শ্রমিকদের সুরক্ষায় আইনটি সংশোধন করা হয়েছে।", ["Modify", "Revise"], ["Damage"], "BCS"),
    ("Amenity", "/əˈmiː.nə.ti/ (অ্যামেনিটি)", "Noun", "নাগরিক সুযোগ-সুবিধা", "The apartment has modern amenities.", "অ্যাপার্টমেন্টটিতে আধুনিক সুযোগ-সুবিধা রয়েছে।", ["Facility", "Convenience"], [], "Spoken"),
    ("Amiable", "/ˈeɪ.mi.ə.bəl/ (এইমিয়েবল)", "Adj", "সহজ-সরল, অমায়িক", "She greeted everyone with an amiable smile.", "তিনি এক অমায়িক হাসিতে সবাইকে অভ্যর্থনা জানিয়েছিলেন।", ["Friendly", "Cordial"], ["Hostile"], "Spoken"),
    ("Amicable", "/ˈæm.ɪ.kə.bəl/ (অ্যামিক্যাবল)", "Adj", "শান্তিপূর্ণ, বন্ধুত্বপূর্ণ", "They reached an amicable settlement.", "তারা একটি শান্তিপূর্ণ মীমাংসায় পৌঁছেছিলেন।", ["Peaceful", "Harmonious"], ["Hostile"], "IELTS"),
    ("Amnesty", "/ˈæm.nə.sti/ (অ্যামনেস্টি)", "Noun", "সাধারণ ক্ষমা", "The government granted an amnesty to prisoners.", "সরকার বন্দীদের সাধারণ ক্ষমা ঘোষণা করেছে।", ["Pardon", "Absolution"], [], "BCS"),
    ("Amorphous", "/əˈmɔː.fəs/ (অ্যামর্ফাস)", "Adj", "নির্দিষ্ট আকারহীন", "It was an amorphous mass of gas.", "এটি নির্দিষ্ট আকারহীন গ্যাসের পিণ্ড ছিল।", ["Shapeless", "Formless"], ["Definite", "Structured"], "Academic"),
    ("Amplify", "/ˈæm.plɪ.faɪ/ (অ্যাম্প্লিফাই)", "Verb", "বর্ধিত করা, জোরদার করা", "Loudspeakers amplify the sound.", "লাউডস্পিকার শব্দ বর্ধিত করে।", ["Magnify", "Boost"], ["Reduce", "Decrease"], "Spoken"),
    ("Analogy", "/əˈnæl.ə.dʒi/ (অ্যানালজি)", "Noun", "সাদৃশ্য, উপমা", "He drew an analogy between brain and computer.", "তিনি মস্তিষ্ক ও কম্পিউটারের মধ্যে একটি তুলনা টেনেছিলেন।", ["Comparison", "Resemblance"], ["Difference"], "IELTS"),
    ("Anarchy", "/ˈæn.ə.ki/ (অ্যানার্কি)", "Noun", "অরাজকতা, শাসনহীনতা", "The country fell into complete anarchy.", "দেশটি সম্পূর্ণ অরাজকতায় নিমজ্জিত হয়েছিল।", ["Chaos", "Lawlessness"], ["Order", "Control"], "BCS"),
    ("Ancillary", "/ænˈsɪl.ər.i/ (অ্যানসিলারি)", "Adj", "সহায়ক, আনুষঙ্গিক", "Ancillary services support the main project.", "সহায়ক সেবা মূল প্রকল্পকে সহায়তা করে।", ["Secondary", "Auxiliary"], ["Main", "Primary"], "Academic"),
    ("Anecdote", "/ˈæn.ɪk.dəʊt/ (অ্যানিকডোট)", "Noun", "সংক্ষিপ্ত মজার ঘটনা", "He shared a funny anecdote about his trip.", "তিনি তার সফরের একটি মজার ঘটনা শেয়ার করেছিলেন।", ["Story", "Tale"], [], "Spoken"),
    ("Anguish", "/ˈæŋ.ɡwɪʃ/ (অ্যাঙ্গুইশ)", "Noun", "তীব্র মানসিক বা শারীরিক যন্ত্রণা", "She felt deep anguish over the loss.", "তিনি হারানোর গভীর যন্ত্রণা অনুভব করেছিলেন।", ["Agony", "Torment"], ["Joy", "Peace"], "Academic"),
    ("Animate", "/ˈæn.ɪ.meɪt/ (অ্যানিমেট)", "Verb", "প্রাণবন্ত করা, সঞ্জীবিত করা", "Her presence animated the entire party.", "তার উপস্থিতি পুরো পার্টিকে প্রাণবন্ত করেছিল।", ["Enliven", "Inspire"], ["Depress"], "Spoken"),
    ("Animosity", "/ˌæn.ɪˈmɒs.ə.ti/ (অ্যানিমোসিটি)", "Noun", "শত্রুতা, বিদ্বেষ", "There is no animosity between us.", "আমাদের মধ্যে কোনো বিদ্বেষ নেই।", ["Hostility", "Hatred"], ["Friendship", "Goodwill"], "IELTS"),
    ("Annex", "/əˈneks/ (অ্যানেক্স)", "Verb", "সংযুক্ত করা, ভূখণ্ড দখল করা", "The nation annexed the neighboring island.", "দেশটি প্রতিবেশী দ্বীপটি দখল করেছিল।", ["Attach", "Acquire"], ["Surrender"], "BCS"),
    ("Annihilate", "/əˈnaɪ.ə.leɪt/ (অ্যানাইহিলেশন)", "Verb", "সমূলে ধ্বংস করা", "The bomb threatened to annihilate the city.", "বোমাটি শহরটি ধ্বংস করে দেওয়ার হুমকি দিয়েছিল।", ["Destroy", "Eradicate"], ["Create", "Build"], "BCS"),
    ("Annotation", "/ˌæn.əˈteɪ.ʃən/ (অ্যানোটেশন)", "Noun", "টীকা, ব্যাখ্যা", "Read the annotations at the end of page.", "পৃষ্ঠার শেষে দেওয়া টীকাগুলো পড়ুন।", ["Note", "Commentary"], [], "Academic"),
    ("Annulling", "/əˈnʌl.ɪŋ/ (অ্যানালিং)", "Noun", "বাতিলকরণ, রদকরণ", "The annulling of the contract surprised all.", "চুক্তি বাতিলের বিষয়টি সবাইকে অবাক করেছিল।", ["Cancellation", "Revocation"], ["Validation"], "BCS"),
    ("Anomalous", "/əˈnɒm.ə.ləs/ (অ্যানোম্যালাস)", "Adj", "নিয়মবহির্ভূত, ব্যতিক্রমী", "We noticed an anomalous result.", "আমরা একটি ব্যতিক্রমী ফলাফল লক্ষ্য করেছি।", ["Irregular", "Unusual"], ["Normal"], "IELTS"),
    ("Antagonism", "/ænˈtæɡ.ən.ɪ.zəm/ (অ্যান্টাগোনিজম)", "Noun", "শত্রুভাবাপন্নতা, বৈরিতা", "His open antagonism caused problems.", "তার প্রকাশ্য শত্রুতা সমস্যার সৃষ্টি করেছিল।", ["Hostility", "Opposition"], ["Harmony"], "BCS"),
    ("Antagonist", "/ænˈtæɡ.ən.ɪst/ (অ্যান্টাগোনিস্ট)", "Noun", "প্রতিপক্ষ, বিরোধী চরিত্র", "He played the villainous antagonist.", "তিনি খলনায়ক প্রতিপক্ষের চরিত্রে অভিনয় করেছিলেন।", ["Rival", "Adversary"], ["Protagonist"], "Spoken"),
    ("Antecedent", "/ˌæn.tɪˈsiː.dənt/ (অ্যান্টিসিডেন্ট)", "Noun", "পূর্ববর্তী ঘটনা বা পদ", "Every effect has an antecedent cause.", "প্রতিটি ফলাফলের একটি পূর্ববর্তী কারণ রয়েছে।", ["Predecessor", "Prior"], ["Subsequent"], "Academic"),
    ("Anticipation", "/ænˌtɪs.ɪˈpeɪ.ʃən/ (অ্যান্টিসিপেশন)", "Noun", "প্রত্যাশা, পূর্বানুমান", "We waited in eager anticipation.", "আমরা অধীর আগ্রহে অপেক্ষা করছিলাম।", ["Expectation", "Hope"], [], "Spoken"),
    ("Antipathy", "/ænˈtɪp.ə.θi/ (অ্যান্টিপ্যাথি)", "Noun", "বিদ্বেষ, চরম অপছন্দ", "He showed antipathy towards strict rules.", "তিনি কঠোর নিয়মের প্রতি অপছন্দ প্রকাশ করেছিলেন।", ["Aversion", "Dislike"], ["Liking"], "BCS"),
    ("Antiquated", "/ˈæn.tɪ.kweɪ.tɪd/ (অ্যান্টিকোয়েটেড)", "Adj", "সেকেলে, পুরোনো ধাঁচের", "The factory uses antiquated machinery.", "কারখানাটি সেকেলে যন্ত্রপাতি ব্যবহার করে।", ["Obsolete", "Outdated"], ["Modern"], "IELTS"),
    ("Antithesis", "/ænˈtɪθ.ə.sɪs/ (অ্যান্টিথিসিস)", "Noun", "সম্পূর্ণ বিপরীত অবস্থা", "Love is the antithesis of selfishness.", "ভালোবাসা হলো স্বার্থপরতার সম্পূর্ণ বিপরীত।", ["Opposite", "Reverse"], ["Same"], "Academic"),
    ("Apathy", "/ˈæp.ə.θi/ (অ্যাপ্যাথি)", "Noun", "উদাসীনতা, অনীহা", "Public apathy towards voting is growing.", "ভোটের প্রতি জনগণের উদাসীনতা বাড়ছে।", ["Indifference", "Lethargy"], ["Interest"], "Spoken"),
    ("Apex", "/ˈeɪ.peks/ (এপেক্স)", "Noun", "চূড়া, সর্বোচ্চ শিখর", "He reached the apex of his career.", "তিনি তার জীবনের সর্বোচ্চ শিখরে পৌঁছেছিলেন।", ["Peak", "Zenith"], ["Bottom", "Nadir"], "BCS"),
    ("Aphorism", "/ˈæf.ə.rɪ.zəm/ (অ্যাফোরিজম)", "Noun", "নীতিবাক্য, সুভাষিত", "The speech was full of wise aphorisms.", "বক্তব্যটি বিজ্ঞ নীতিবাক্যে পরিপূর্ণ ছিল।", ["Maxim", "Saying"], [], "Academic"),
    ("Appall", "/əˈpɔːl/ (অ্যাপল)", "Verb", "আতঙ্কিত বা স্তম্ভিত করা", "The brutal news appalled the public.", "নৃশংস খবরটি জনসাধারণকে স্তম্ভিত করেছিল।", ["Horrify", "Shock"], ["Delight"], "IELTS"),
    ("Apparatus", "/ˌæp.əˈreɪ.təs/ (অ্যাপারেটাস)", "Noun", "যন্ত্রপাতি, প্রশাসনিক কাঠামো", "The lab has complex scientific apparatus.", "ল্যাবটিতে জটিল বৈজ্ঞানিক যন্ত্রপাতি রয়েছে।", ["Equipment", "Device"], [], "Academic"),
    ("Apparel", "/əˈpær.əl/ (অ্যাপ্যারেল)", "Noun", "পোশাক-পরিচ্ছদ", "She bought trendy summer apparel.", "তিনি ফ্যাশনেবল গ্রীষ্মকালীন পোশাক কিনেছিলেন।", ["Clothing", "Garment"], [], "Spoken"),
    ("Appease", "/əˈpiːz/ (অ্যাপিজ)", "Verb", "শান্ত বা সন্তুষ্ট করা", "He gave in to appease his critics.", "তিনি সমালোচকদের শান্ত করতে নতিস্বীকার করেছিলেন।", ["Pacify", "Soothe"], ["Provoke"], "BCS"),
    ("Appellation", "/ˌæp.əˈleɪ.ʃən/ (অ্যাপেলেশন)", "Noun", "উপাধি, নাম", "He gained the appellation of the Great.", "তিনি মহান উপাধি লাভ করেছিলেন।", ["Name", "Title"], [], "Academic"),
    ("Apportion", "/əˈpɔː.ʃən/ (অ্যাপোরশন)", "Verb", "বণ্টন করা, ভাগ করে দেওয়া", "They apportioned the funds among charities.", "তারা দাতব্য প্রতিষ্ঠানে তহবিল বণ্টন করেছিল।", ["Divide", "Allocate"], [], "BCS"),
    ("Appraise", "/əˈpreɪz/ (অ্যাপরেইজ)", "Verb", "মূল্য নিরূপণ বা মান নির্ধারণ করা", "An expert appraised the diamond ring.", "একজন বিশেষজ্ঞ হিরের আংটির মূল্য নিরূপণ করেছিলেন।", ["Evaluate", "Assess"], [], "IELTS"),
    ("Apprehend", "/ˌæp.rɪˈhend/ (অ্যাপ্রিহেন্ড)", "Verb", "গ্রেপ্তার করা, অনুধাবন করা", "Police managed to apprehend the suspect.", "পুলিশ সন্দেহভাজনকে গ্রেপ্তার করতে সক্ষম হয়েছিল।", ["Arrest", "Grasp"], ["Release"], "BCS"),
    ("Apprehension", "/ˌæp.rɪˈhen.ʃən/ (অ্যাপ্রিহেনশন)", "Noun", "আশঙ্কা, গ্রেপ্তার", "She filled with apprehension about future.", "ভবিষ্যৎ নিয়ে তার মনে আশঙ্কা তৈরি হয়েছিল।", ["Anxiety", "Fear"], ["Confidence"], "IELTS"),
    ("Appropriate", "/əˈprəʊ.pri.ət/ (অ্যাপ্রোপ্রিয়েট)", "Adj", "উপযুক্ত, যথার্থ", "Casual wear is not appropriate here.", "সাধারণ পোশাক এখানে উপযুক্ত নয়।", ["Suitable", "Proper"], ["Inappropriate"], "Spoken"),
    ("Approval", "/əˈpruː.vəl/ (অ্যাপ্রুভাল)", "Noun", "সম্মতি, অনুমোদন", "We need the manager's approval.", "আমাদের ম্যানেজারের অনুমোদন প্রয়োজন।", ["Consent", "Sanction"], ["Refusal"], "Spoken"),
    ("Aptitude", "/ˈæp.tɪ.tʃuːd/ (অ্যাপটিটিউড)", "Noun", "স্বাভাবিক দক্ষতা, প্রবণতা", "He has an aptitude for mathematics.", "গণিতে তার বিশেষ স্বাভাবিক দক্ষতা রয়েছে।", ["Talent", "Ability"], ["Inability"], "Spoken"),
    ("Arbiter", "/ˈɑː.bɪ.tər/ ( আরবিটার)", "Noun", "সালিশকারী, বিচারক", "The court is the ultimate arbiter.", "আদালতই হলো চূড়ান্ত বিচারক।", ["Judge", "Umpire"], [], "BCS"),
    ("Arbitrary", "/ˈɑː.bɪ.trər.i/ ( আরবিট্রারি)", "Adj", "খামখেয়ালী, ইচ্ছামাফিক", "The decision seemed completely arbitrary.", "সিদ্ধান্তটি সম্পূর্ণ খামখেয়ালী বলে মনে হয়েছিল।", ["Random", "Capricious"], ["Systematic"], "IELTS"),
    ("Arcane", "/ɑːˈkeɪn/ (আরকেইন)", "Adj", "রহস্যময়, গুহ্য", "He studies arcane ancient rituals.", "তিনি রহস্যময় প্রাচীন আচার-অনুষ্ঠান নিয়ে গবেষণা করেন।", ["Mysterious", "Secret"], ["Common"], "Academic"),
    ("Archetype", "/ˈɑː.kɪ.taɪp/ (আর্কিটাইপ)", "Noun", "আদি রূপ, মূল আদর্শ", "He is the archetype of a successful leader.", "তিনি একজন সফল নেতার মূল আদর্শ।", ["Model", "Pattern"], [], "Academic"),
    ("Ardent", "/ˈɑː.dənt/ (আর্ডেন্ট)", "Adj", "অনুরক্ত, অত্যন্ত উৎসাহী", "She is an ardent supporter of democracy.", "তিনি গণতন্ত্রের একজন একনিষ্ঠ সমর্থক।", ["Passionate", "Zealous"], ["Apathetic"], "IELTS"),
    ("Arduous", "/ˈɑː.dʒu.əs/ (আর্ডুয়াস)", "Adj", "কষ্টসাধ্য, দুর্গম", "It was an arduous journey up the mountain.", "পাহাড়ে ওঠা একটি অত্যন্ত কষ্টসাধ্য যাত্রা ছিল।", ["Difficult", "Hard"], ["Easy"], "BCS"),
    ("Arrogance", "/ˈær.ə.ɡəns/ (অ্যারোগেন্স)", "Noun", "অহংকার, ঔদ্ধত্য", "His arrogance alienated many coworkers.", "তার ঔদ্ধত্য অনেক সহকর্মীকে পর করে দিয়েছিল।", ["Haughtiness", "Pride"], ["Humility"], "Spoken"),
    ("Articulate", "/ɑːˈtɪk.jə.lət/ (আর্টিকুলেট)", "Adj", "বাকপটু, স্পষ্টভাষী", "She is a very articulate speaker.", "তিনি অত্যন্ত স্পষ্টভাষী একজন বক্তা।", ["Fluent", "Expressive"], ["Inarticulate"], "Spoken"),
    ("Artifact", "/ˈɑː.tɪ.fækt/ (আর্টিফ্যাক্ট)", "Noun", "প্রত্নতাত্ত্বিক নিদর্শন", "Museum displays ancient golden artifacts.", "জাদুঘরটি প্রাচীন সোনার প্রত্নবস্তু প্রদর্শন করে।", ["Relic", "Antiquity"], [], "Academic"),
    ("Artifice", "/ˈɑː.tɪ.fɪs/ (আর্টিফিস)", "Noun", "কৌশল, চাতুরী", "He won the game through artifice.", "তিনি কৌশলের মাধ্যমে খেলায় জিতেছিলেন।", ["Trickery", "Deceit"], ["Honesty"], "Academic"),
    ("Artisan", "/ˌɑː.tɪˈzæn/ (আর্টিজান)", "Noun", "কারিকর, হস্তশিল্পী", "Local artisans make beautiful pottery.", "স্থানীয় কারিগররা সুন্দর মৃৎশিল্প তৈরি করে।", ["Craftsman"], [], "Spoken"),
    ("Ascendancy", "/əˈsen.dən.si/ (অ্যাসেনডেন্সি)", "Noun", "প্রভাব, আধিপত্য", "The party gained political ascendancy.", "দলটি রাজনৈতিক আধিপত্য লাভ করেছিল।", ["Dominance", "Control"], ["Subordination"], "BCS"),
    ("Ascetic", "/əˈset.ɪk/ (অ্যাসেটিক)", "Adj", "কঠোর আত্মসংযমী", "He leads a simple, ascetic lifestyle.", "তিনি একটি সাধারণ, সংযমী জীবনযাপন করেন।", ["Austere", "Severe"], ["Extravagant"], "BCS"),
    ("Ascribe", "/əˈskraɪb/ (অ্যাসক্রাইব)", "Verb", "কারণ হিসেবে ধরা, আরোপ করা", "They ascribe their success to hard work.", "তারা তাদের সাফল্যকে কঠোর পরিশ্রমের ফল বলে মনে করে।", ["Attribute", "Assign"], [], "IELTS"),
    ("Asperity", "/æˈsper.ə.ti/ (অ্যাসপ্যারিটি)", "Noun", "কঠোরতা, রুক্ষতা", "He spoke with asperity in his voice.", "তিনি গলায় রুক্ষতা নিয়ে কথা বলেছিলেন।", ["Harshness", "Roughness"], ["Mildness"], "Academic"),
    ("Aspiration", "/ˌæs.pɪˈreɪ.ʃən/ (অ্যাসপিরেশন)", "Noun", "উচ্চাকাঙ্ক্ষা, প্রবল ইচ্ছা", "She has high career aspirations.", "তার উচ্চ ক্যারিয়ার গড়ার আকাঙ্ক্ষা রয়েছে।", ["Ambition", "Goal"], [], "Spoken"),
    ("Assail", "/əˈseɪl/ (অ্যাসেইল)", "Verb", "আক্রমণ করা, ভর্ৎসনা করা", "Doubts assailed his mind.", "সন্দেহ তার মনে আক্রমণ করেছিল।", ["Attack", "Assault"], ["Defend"], "IELTS"),
    ("Assent", "/əˈsent/ (অ্যাসেন্ট)", "Noun", "সম্মতি, সমর্থন", "The president gave his assent to bill.", "রাষ্ট্রপতি বিলে তার সম্মতি দিয়েছেন।", ["Agreement", "Consent"], ["Dissent"], "BCS"),
    ("Assertive", "/əˈsɜː.tɪv/ (অ্যাসার্টিভ)", "Adj", "আত্মবিশ্বাসী, স্বাবলম্বী বক্তব্য প্রকাশী", "You should be more assertive at work.", "কর্মক্ষেত্রে আপনার আরও আত্মবিশ্বাসী হওয়া উচিত।", ["Confident", "Decisive"], ["Timid"], "Spoken"),
    ("Assiduous", "/əˈsɪdʒ.u.əs/ (অ্যাসিডুয়াস)", "Adj", "অধ্যবসায়ী, একনিষ্ঠ", "Success requires assiduous practice.", "সাফল্যের জন্য একনিষ্ঠ অনুশীলনের প্রয়োজন।", ["Diligent", "Hardworking"], ["Lazy"], "BCS"),
    ("Assimilation", "/əˌsɪm.ɪˈleɪ.ʃən/ (অ্যাসিমিলেশন)", "Noun", "আত্মীকরণ, বিলীন হওয়া", "Cultural assimilation takes generations.", "সাংস্কৃতিক আত্মীকরণ হতে কয়েক প্রজন্ম সময় লাগে।", ["Integration", "Absorption"], [], "IELTS"),
    ("Assuage", "/əˈsweɪdʒ/ (অ্যাসওয়েজ)", "Verb", "উপশম বা প্রশমিত করা", "Music helped assuage his pain.", "সংগীত তার ব্যথা উপশমে সাহায্য করেছিল।", ["Relieve", "Ease"], ["Aggravate"], "IELTS"),
    ("Asterisk", "/ˈæs.tər.ɪsk/ (অ্যাস্টারিস্ক)", "Noun", "তারকাচিহ্ন (*)", "Note the reference marked with asterisk.", "তারকাচিহ্ন দেওয়া রেফারেন্সটি লক্ষ্য করুন।", ["Star symbol"], [], "Spoken"),
    ("Astonishment", "/əˈstɒn.ɪʃ.mənt/ (অ্যাস্টনিশমেন্ট)", "Noun", "মহাবিস্ময়, তাজ্জব", "He looked at the news in astonishment.", "তিনি তাজ্জব হয়ে সংবাদের দিকে তাকালেন।", ["Amazement", "Wonder"], [], "Spoken"),
    ("Astute", "/əˈstʃuːt/ (অ্যাস্টিউট)", "Adj", "চতুর, দূরদর্শী", "An astute politician wins the crowd.", "একজন দূরদর্শী রাজনীতিবিদ জনতাকে জয় করেন।", ["Shrewd", "Clever"], ["Foolish"], "BCS"),
    ("Asylum", "/əˈsaɪ.ləm/ (অ্যাসাইলাম)", "Noun", "রাজনৈতিক আশ্রয়", "The refugees sought political asylum.", "শরণার্থীরা রাজনৈতিক আশ্রয় চেয়েছিলেন।", ["Refuge", "Sanctuary"], [], "BCS"),
    ("Atonement", "/əˈtəʊn.mənt/ (অ্যাটোনমেন্ট)", "Noun", "প্রায়শ্চিত্ত, ক্ষতিপূরণ", "He prayed for atonement of sins.", "তিনি পাপের প্রায়শ্চিত্তের জন্য প্রার্থনা করেছিলেন।", ["Repentance", "Penance"], [], "Academic"),
    ("Atrophy", "/ˈæt.rə.fi/ (অ্যাট্রোফি)", "Noun", "ক্ষয়, পেশী শুকিয়ে যাওয়া", "Lack of exercise causes muscle atrophy.", "ব্যয়ামের অভাবে পেশির ক্ষয় হয়।", ["Wasting", "Decay"], ["Growth"], "Academic"),
    ("Attainable", "/əˈteɪ.nə.bəl/ (অ্যাটেইনেবল)", "Adj", "অর্জনযোগ্য, সম্ভবপর", "Set realistic and attainable goals.", "বাস্তবসম্মত এবং অর্জনযোগ্য লক্ষ্য নির্ধারণ করুন।", ["Achievable", "Feasible"], ["Unattainable"], "Spoken"),
    ("Attenuate", "/əˈten.u.eɪt/ (অ্যাটেনুয়েট)", "Verb", "কৃশ করা, তীব্রতা কমানো", "The drug attenuates the symptoms.", "ওষুধটি লক্ষণগুলোর তীব্রতা কমিয়ে দেয়।", ["Weaken", "Lessen"], ["Strengthen"], "IELTS"),
    ("Attest", "/əˈtest/ (অ্যাটেস্ট)", "Verb", "সত্যতা প্রমাণ বা সত্যায়িত করা", "Witnesses attested to his honesty.", "সাক্ষীরা তার সততার সত্যতা প্রমাণ করেছেন।", ["Verify", "Confirm"], ["Deny"], "BCS"),
    ("Audit", "/ˈɔː.dɪt/ (অডিট)", "Noun", "হিসাব নিরীক্ষা", "Company conducts annual financial audit.", "প্রতিষ্ঠানটি বার্ষিক আর্থিক অডিট পরিচালনা করে।", ["Inspection", "Check"], [], "BCS"),
    ("Auditory", "/ˈɔː.dɪ.tər.i/ (অডিটরি)", "Adj", "শ্রবণ সংক্রান্ত", "The movie offers rich auditory experience.", "ছবিটি চমৎকার শ্রাব্য অনুভূতি দেয়।", ["Hearing", "Aural"], [], "Academic"),
    ("Augment", "/ɔːɡˈment/ (অগমেন্ট)", "Verb", "বৃদ্ধি করা", "He joined evening classes to augment skills.", "দক্ষতা বাড়াতে সে সান্ধ্যকালীন ক্লাসে যোগ দেয়।", ["Boost", "Increase"], ["Decrease"], "Spoken"),
    ("August", "/ɔːˈɡʌstm/ (অগাস্ট)", "Adj", "মহিমান্বিত, শ্রদ্ধেয়", "The royal family entered august hall.", "রাজপরিবার মহিমান্বিত হলে প্রবেশ করেছিল।", ["Majestic", "Noble"], [], "Academic"),
    ("Aura", "/ˈɔː.rə/ (অরা)", "Noun", "দীপ্তি, আবহে সৃষ্টি", "The place has a peaceful aura.", "জায়গাটিতে একটি শান্তিপূর্ণ আবহ রয়েছে।", ["Atmosphere", "Glow"], [], "Spoken"),
    ("Auspicious", "/ɔːˈspɪʃ.əs/ (অসপিশাস)", "Adj", "শুভ, মঙ্গলজনক", "Diwali is an auspicious occasion.", "দেওয়ালি একটি শুভ উপলক্ষ।", ["Propitious", "Promising"], ["Unlucky"], "Spoken"),
    ("Austere", "/ɒsˈtɪər/ (অস্টিয়ার)", "Adj", "কঠোর, অনারম্বর", "The monk lives an austere life.", "সন্ন্যাসী এক অনারম্বর জীবনযাপন করেন।", ["Severe", "Plain"], ["Luxurious"], "BCS"),
    ("Authenticity", "/ˌɔː.θenˈtɪs.ə.ti/ (অথেন্টিসিটি)", "Noun", "প্রামাণিকতা, খাঁটিত্ব", "Experts verified authenticity of painting.", "বিশেষজ্ঞরা চিত্রকর্মটির খাঁটিত্ব যাচাই করেছিলেন।", ["Genuineness", "Validity"], ["Fake"], "IELTS"),
    ("Authoritarian", "/ɔːˌθɒr.ɪˈteər.i.ən/ (অথরিটেরিয়ান)", "Adj", "স্বৈরাচারী, কর্তৃত্বপরায়ণ", "Citizens protested authoritarian rule.", "নাগরিকরা কর্তৃত্বপরায়ণ শাসনের প্রতিবাদ করেছিল।", ["Autocratic", "Dictatorial"], ["Democratic"], "BCS"),
    ("Autonomy", "/ɔːˈtɒn.ə.mi/ (অটোনমি)", "Noun", "স্বায়ত্তশাসন", "Regions demanded local autonomy.", "অঞ্চলগুলো স্থানীয় স্বায়ত্তশাসনের দাবি জানিয়েছিল।", ["Independence"], ["Dependence"], "BCS"),
    ("Auxiliary", "/ɔːɡˈzɪl.i.ər.i/ (অক্সিলিয়ারি)", "Adj", "সহকারী, অতিরিক্ত", "The hospital has auxiliary generators.", "হাসপাতালে অতিরিক্ত জেনারেটর রয়েছে।", ["Supplementary", "Backup"], ["Primary"], "Academic"),
    ("Avalanche", "/ˈæv.əl.ɑːntʃ/ (অ্যাভালাঞ্চ)", "Noun", "হিমবাহ, বরফধস", "The avalanche blocked mountain pass.", "বরফধস পাহাড়ি পথ বন্ধ করে দিয়েছিল।", ["Snowslide", "Landslide"], [], "Spoken"),
    ("Avarice", "/ˈæv.ər.ɪs/ (অ্যাভারিস)", "Noun", "অর্থলিপ্সা, ঘোর লোভ", "His avarice led to his downfall.", "তার অর্থলিপ্সাই তার পতনের কারণ হয়েছিল।", ["Greed", "Cupidity"], ["Generosity"], "BCS"),
    ("Avenge", "/əˈvendʒ/ (অ্যাভেঞ্জ)", "Verb", "প্রতিশোধ নেওয়া", "He promised to avenge his father's death.", "সে তার বাবার মৃত্যুর প্রতিশোধ নেওয়ার অঙ্গীকার করেছিল।", ["Retaliate", "Revenge"], ["Forgive"], "Spoken"),
    ("Aversion", "/əˈvɜː.ʃən/ (অ্যাভারশন)", "Noun", "তীব্র অনিচ্ছা, অপছন্দ", "He has a strong aversion to snakes.", "সাপের প্রতি তার তীব্র অপছন্দ রয়েছে।", ["Dislike", "Hatred"], ["Liking"], "IELTS"),
    ("Avert", "/əˈvɜːt/ (অ্যাভার্ট)", "Verb", "এড়ানো, চোখ ফিরিয়ে নেওয়া", "Good planning averted a disaster.", "সঠিক পরিকল্পনা একটি দুর্যোগ এড়াতে সাহায্য করেছিল।", ["Prevent", "Avoid"], ["Cause"], "IELTS"),
    ("Avid", "/ˈæv.ɪd/ (অ্যাভিড)", "Adj", "উৎসুক, প্রবল আগ্রহী", "She is an avid reader of novels.", "তিনি উপন্যাসের এক প্রবল অনুরাগী পাঠক।", ["Eager", "Enthusiastic"], ["Apathetic"], "Spoken"),
    ("Avow", "/əˈvaʊ/ (অ্যাভাউ)", "Verb", "প্রকাশ্যে স্বীকার করা", "He avowed his commitment to peace.", "তিনি শান্তির প্রতি তার প্রতিশ্রুতি প্রকাশ্যে স্বীকার করেন।", ["Declare", "Assert"], ["Deny"], "Academic"),
    ("Awe", "/ɔː/ (অ)", "Noun", "শ্রদ্ধামিশ্রিত ভয় বা বিস্ময়", "The visitors looked at temple in awe.", "দর্শনার্থীরা বিস্ময়ে মন্দিরের দিকে তাকিয়েছিল।", ["Wonder", "Reverence"], [], "Spoken"),
    ("Axiom", "/ˈæk.si.əm/ (অ্যাক্সিওম)", "Noun", "স্বতঃসিদ্ধ সত্য", "It is an accepted axiom in physics.", "এটি পদার্থবিজ্ঞানের একটি স্বীকৃত স্বতঃসিদ্ধ সত্য।", ["Truth", "Maxim"], [], "Academic"),
    ("Baffle", "/ˈbæf.əl/ (ব্যাফল)", "Verb", "হতবুদ্ধি বা কিংকর্তব্যবিমূঢ় করা", "The mystery baffled the police.", "রহস্যটি পুলিশকে হতবুদ্ধি করে দিয়েছিল।", ["Puzzle", "Confuse"], ["Clarify"], "IELTS"),
    ("Balk", "/bɔːk/ (বল্ক)", "Verb", "দ্বিধা করা, থমকে দাঁড়ানো", "The horse balked at the high hurdle.", "ঘোড়াটি উঁচু বাধা দেখে থমকে দাঁড়িয়েছিল।", ["Hesitate", "Refuse"], ["Proceed"], "Academic"),
    ("Balmy", "/ˈbɑː.mi/ (বামি)", "Adj", "মনোরম, স্নিগ্ধ", "We enjoyed a balmy evening breeze.", "আমরা স্নিগ্ধ সন্ধ্যার বাতাস উপভোগ করেছিলাম।", ["Mild", "Pleasant"], ["Harsh"], "Spoken"),
    ("Banal", "/bəˈnɑːl/ (বানাল)", "Adj", "তুচ্ছ, মামুলি, গতানুগতিক", "The movie plot was predictable and banal.", "চলচ্চিত্রের কাহিনীটি ছিল মামুলি।", ["Trite", "Commonplace"], ["Original"], "IELTS"),
    ("Banish", "/ˈbæn.ɪʃ/ (ব্যানিশ)", "Verb", "নির্বাসিত করা, তাড়ানো", "The king banished the traitor.", "রাজা বিশ্বাসঘাতককে নির্বাসিত করেছিলেন।", ["Exile", "Expel"], ["Welcome"], "BCS"),
    ("Banter", "/ˈbæn.tər/ (ব্যান্টার)", "Noun", "হালকা রসিকতা, ঠাট্টা", "They engaged in friendly banter.", "তারা বন্ধুত্বপূর্ণ রসিকতায় মেতে উঠেছিল।", ["Joking", "Teasing"], [], "Spoken"),
    ("Barricade", "/ˈbær.ɪ.keɪd/ (ব্যারিকেড)", "Noun", "প্রতিবন্ধক, ব্যারিকেড", "Protesters built a barricade across street.", "বিক্ষোভকারীরা রাস্তায় ব্যারিকেড তৈরি করেছিল।", ["Barrier", "Obstacle"], [], "Spoken"),
    ("Beacon", "/ˈbiː.kən/ (বিকন)", "Noun", "বাতিঘর, নির্দেশক আলো", "Hope is a beacon in dark times.", "আশা কঠিন সময়ে এক বাতিঘরের মতো।", ["Signal", "Guide"], [], "Spoken"),
    ("Beguile", "/bɪˈɡaɪl/ (বিগাইল)", "Verb", "মোমোহিত করা, ছলনা করা", "Her beauty beguiled everyone.", "তার রূপ সবাইকে মোহিত করেছিল।", ["Charming", "Enchant"], ["Disgust"], "IELTS"),
    ("Belated", "/bɪˈleɪ.tɪd/ (বিলেটেড)", "Adj", "বিলম্বিত, দেরিতে পাওয়া", "He sent belated birthday wishes.", "সে বিলম্বে জন্মদিনের শুভেচ্ছা পাঠিয়েছিল।", ["Late", "Delayed"], ["Early"], "Spoken"),
    ("Beleaguer", "/bɪˈliː.ɡər/ (বিলিগার)", "Verb", "অবরুদ্ধ বা কোণঠাসা করা", "The company was beleaguered by debt.", "প্রতিষ্ঠানটি ঋণে কোণঠাসা হয়ে পড়েছিল।", ["Harass", "Besiege"], [], "Academic"),
    ("Belligerent", "/bəˈlɪdʒ.ər.ənt/ (বেলিজারেন্ট)", "Adj", "যুদ্ধংদেহী, আক্রমণাত্মক", "He assumed a belligerent attitude.", "সে যুদ্ধংদেহী মনোভাব গ্রহণ করেছিল।", ["Aggressive", "Hostile"], ["Peaceful"], "BCS"),
    ("Bemoan", "/bɪˈməʊn/ (বিমোন)", "Verb", "আক্ষেপ বা বিলাপ করা", "They bemoaned the loss of job.", "তারা চাকরি হারানোর আক্ষেপ করেছিল।", ["Lament", "Mourn"], ["Rejoice"], "Academic"),
    ("Benefactor", "/ˈben.ɪ.fæk.tər/ (বেনিফ্যাক্টর)", "Noun", "উপকারী ব্যক্তি, দানবীর", "An anonymous benefactor paid tuition.", "একজন অজ্ঞাত দানবীর টিউশন ফি দিয়েছেন।", ["Patron", "Donor"], [], "BCS"),
    ("Beneficiary", "/ˌben.ɪˈfɪʃ.ər.i/ (বেনিফিশিয়ারি)", "Noun", "উপকারভোগী, গ্রহীতা", "She is sole beneficiary of will.", "তিনি উইলের একমাত্র উপকারভোগী।", ["Recipient", "Heir"], [], "BCS"),
    ("Benevolence", "/bəˈnev.əl.əns/ (বেনেভোলেন্স)", "Noun", "বদান্যতা, দয়া", "His benevolence helped many poor families.", "তার বদান্যতা বহু দরিদ্র পরিবারকে সাহায্য করেছিল।", ["Kindness", "Generosity"], ["Malevolence"], "Spoken"),
    ("Benign", "/bɪˈnaɪn/ (বিনাইন)", "Adj", "সদয়, অহিংস, ক্ষতিকর নয় এমন", "The tumor turned out to be benign.", "টিউমারটি ক্ষতিকর নয় বলে প্রমাণিত হয়েছে।", ["Harmless", "Gentle"], ["Malignant"], "IELTS"),
    ("Bequeath", "/bɪˈkwiːð/ (বিকউইথ)", "Verb", "উইল করে রেখে যাওয়া", "He bequeathed his estate to daughter.", "তিনি তার কন্যাকে সম্পত্তি উইল করে দিয়েছেন।", ["Leave", "Bestow"], [], "BCS"),
    ("Berate", "/bɪˈreɪt/ (বিরেইট)", "Verb", "তীব্র ভর্ৎসনা করা", "The coach berated players after loss.", "হেরে যাওয়ার পর কোচ খেলোয়াড়দের ভর্ৎসনা করেন।", ["Scold", "Chide"], ["Praise"], "Academic"),
    ("Bereft", "/bɪˈreft/ (বিরেফ্ট)", "Adj", "বঞ্চিত, নিঃস্ব", "The widow was bereft of all hope.", "বিধবাটি সব আশা থেকে বঞ্চিত হয়েছিল।", ["Deprived", "Lacking"], ["Full"], "Academic"),
    ("Beseech", "/bɪˈsiːtʃ/ (বিসিচ)", "Verb", "মিনতি বা আকুল প্রার্থনা করা", "She beseeched him to stay safe.", "সে তাকে নিরাপদে থাকার আকুল মিনতি জানিয়েছিল।", ["Beg", "Implore"], [], "Academic"),
    ("Besiege", "/bɪˈsiːdʒ/ (বিসিজ)", "Verb", "অবরোধ করা, ঘিরে ফেলা", "Reporters besieged the minister.", "সাংবাদিকরা মন্ত্রীকে ঘিরে ধরেছিলেন।", ["Surround", "Encircle"], [], "BCS"),
    ("Bestow", "/bɪˈstəʊ/ (বিস্টো)", "Verb", "প্রদান করা, ভূষিত করা", "The university bestowed an honor.", "বিশ্ববিদ্যালয়টি একটি সম্মাননা প্রদান করেছে।", ["Confer", "Grant"], ["Withhold"], "BCS"),
    ("Bewilder", "/bɪˈwɪl.dər/ (বিউইল্ডার)", "Verb", "বিভ্রান্ত বা হতভম্ব করা", "The confusing rules bewildered students.", "বিভ্রান্তিকর নিয়মগুলো ছাত্রদের হতভম্ব করেছিল।", ["Confuse", "Plex"], ["Clarify"], "Spoken"),
    ("Bias", "/ˈbaɪ.əs/ (বায়াস)", "Noun", "পক্ষপাতিত্ব, ঝোঁক", "Avoid personal bias in judgment.", "বিচারে ব্যক্তিগত পক্ষপাতিত্ব এড়িয়ে চলুন।", ["Prejudice", "Partiality"], ["Fairness"], "Spoken"),
    ("Bicker", "/ˈbɪk.ər/ (বিকার)", "Verb", "তুচ্ছ বিষয় নিয়ে ঝগড়া করা", "The siblings constantly bicker.", "ভাইবোনরা অবিরত কিচিরমিচির ঝগড়া করে।", ["Squabble", "Quarrel"], [], "Spoken"),
    ("Binge", "/bɪndʒ/ (বিঞ্জ)", "Noun", "একটানা অতিরিক্ত আহার বা বিনোদন", "She went on a binge-watching spree.", "সে টানা নাটক দেখার নেশায় মেতেছিল।", ["Spree", "Indulgence"], [], "Spoken"),
    ("Blatant", "/ˈbleɪ.tənt/ (ব্ল্যাটেন্ট)", "Adj", "স্পষ্ট, ধৃষ্টতাপূর্ণ, চোখা", "It was a blatant lie.", "এটি একটি স্পষ্ট মিথ্যা ছিল।", ["Flagrant", "Obvious"], ["Subtle"], "IELTS"),
    ("Bleak", "/bliːk/ (ব্লিক)", "Adj", "আশাহীন, নিরানন্দ, শূন্য", "Future looks bleak for company.", "প্রতিষ্ঠানটির ভবিষ্যৎ আশাহীন মনে হচ্ছে।", ["Grim", "Dismal"], ["Bright"], "IELTS"),
    ("Blemish", "/ˈblem.ɪʃ/ (ব্লেমিশ)", "Noun", "ত্রুটি, দাগ, কলঙ্ক", "Not a single blemish was found.", "একটি দাগও খুঁজে পাওয়া যায়নি।", ["Flaw", "Defect"], ["Perfection"], "Spoken"),
    ("Blissful", "/ˈblɪs.fəl/ (ব্লিসফুল)", "Adj", "পরমানন্দদায়ক, পরম সুখী", "They spent a blissful week at beach.", "তারা সৈকতে একটি আনন্দদায়ক সপ্তাহ কাটিয়েছিল।", ["Heavenly", "Joyful"], ["Miserable"], "Spoken"),
    ("Blunder", "/ˈblʌn.dər/ (ব্ল্যান্ডার)", "Noun", "মারাত্মক ভুল", "Making that statement was a huge blunder.", "ঐ বক্তব্যটি দেওয়া এক মারাত্মক ভুল ছিল।", ["Mistake", "Error"], [], "Spoken"),
    ("Blunt", "/blʌnt/ (ব্লান্ট)", "Adj", "স্পষ্টবাদী, অসানিত", "He gave a blunt answer.", "সে এক সোজাসাপ্টা সোজা উত্তর দিয়েছে।", ["Direct", "Frank"], ["Subtle"], "Spoken"),
    ("Boisterous", "/ˈbɔɪ.stər.əs/ (বোইস্ট্যারাস)", "Adj", "কোলাহলপূর্ণ, উচ্ছ্বল", "Class was boisterous before teacher arrived.", "শিক্ষক আসার আগে শ্রেণীটি কোলাহলপূর্ণ ছিল।", ["Rowdy", "Noisy"], ["Quiet"], "Spoken"),
    ("Bolster", "/ˈbəʊl.stər/ (বোলস্টার)", "Verb", "জোরালো করা, সমর্থন দেওয়া", "More evidence is needed to bolster claim.", "দাবি জোরদার করতে আরও প্রমাণ দরকার।", ["Strengthen", "Support"], ["Weaken"], "IELTS"),
    ("Bombastic", "/bɒmˈbæs.tɪk/ (বোম্বাস্টিক)", "Adj", "আড়ম্বরপূর্ণ কিন্তু অর্থহীন", "He delivered a bombastic speech.", "তিনি এক আড়ম্বরপূর্ণ বক্তব্য দিয়েছিলেন।", ["Pompous", "High-flown"], ["Simple"], "Academic"),
    ("Bona fide", "/ˌbəʊ.nə ˈfaɪ.di/ (বোনা ফাইডি)", "Adj", "প্রকৃত, খাঁটি, সততার সাথে করা", "Only bona fide students are allowed.", "কেবলমাত্র খাঁটি ছাত্রদের অনুমতি দেওয়া হয়।", ["Genuine", "Authentic"], ["Fake"], "BCS"),
    ("Bondage", "/ˈbɒn.dɪdʒ/ (বন্ডেজ)", "Noun", "দাসত্ব, পরাধীনতা", "The country freed itself from bondage.", "দেশটি পরাধীনতা থেকে মুক্ত হয়েছিল।", ["Slavery", "Servitude"], ["Freedom"], "BCS"),
    ("Boon", "/buːn/ (বুন)", "Noun", "বর, পরম আশীর্বাদ", "Technology is a boon for modern world.", "প্রযুক্তি আধুনিক বিশ্বের জন্য এক পরম আশীর্বাদ।", ["Blessing", "Benefit"], ["Curse"], "Spoken"),
    ("Boorish", "/ˈbʊə.rɪʃ/ (বুরিশ)", "Adj", "অসভ্য, চাষাড়ে", "His boorish behavior offended guests.", "তার চাষাড়ে আচরণ অতিথিদের ক্ষুব্ধ করেছিল।", ["Coarse", "Crude"], ["Polite"], "Academic"),
    ("Bounteous", "/ˈbaʊn.ti.əs/ (বাউনটিয়াস)", "Adj", "প্রচুর, দানশীল", "Nature provided a bounteous harvest.", "প্রকৃতি প্রচুর ফসল প্রদান করেছে।", ["Abundant", "Generous"], ["Meager"], "Academic"),
    ("Brag", "/bræɡ/ (ব্র্যাগ)", "Verb", "অহংকার বা বড়াই করা", "Don't brag about your achievements.", "নিজের অর্জন নিয়ে বড়াই করবেন না।", ["Boast", "Flaunt"], [], "Spoken"),
    ("Brevity", "/ˈbrev.ə.ti/ (ব্রেভিটি)", "Noun", "সংক্ষিপ্ততা, স্বল্পতা", "Brevity is soul of wit.", "সংক্ষিপ্ততাই হলো বুদ্ধিমত্তার সারকথা।", ["Conciseness", "Briefness"], ["Verbosity"], "IELTS"),
    ("Brisk", "/brɪsk/ (ব্রিস্ক)", "Adj", "চটপটে, দ্রুতগতির", "She took a brisk walk every morning.", "তিনি প্রতিদিন সকালে দ্রুত হাঁটেন।", ["Quick", "Lively"], ["Slow"], "Spoken"),
    ("Brittle", "/ˈbrɪt.əl/ (ব্রিটল)", "Adj", "ভঙ্গুর, সহজে ভেঙে যায় এমন", "Old bones become brittle.", "পুরোনো হাড্ডি ভঙ্গুর হয়ে যায়।", ["Fragile", "Breakable"], ["Durable"], "Spoken"),
    ("Broach", "/brəʊtʃ/ (ব্রোচ)", "Verb", "প্রথমবার আলোচনার অবতারণা করা", "He broached the sensitive topic carefully.", "তিনি সতর্কতার সাথে সংবেদনশীল বিষয়টি উত্থাপন করেন।", ["Introduce", "Raise"], [], "IELTS"),
    ("Bucolic", "/bjuːˈkɒl.ɪk/ (বিউকলিক)", "Adj", "গ্রাম্য, পল্লীসংক্রান্ত", "The poem describes a bucolic landscape.", "কবিতাটি এক মনোরম গ্রাম্য দৃশ্য বর্ণনা করে।", ["Rural", "Rustic"], ["Urban"], "Academic"),
    ("Bulwark", "/ˈbʊl.wək/ (বুলওয়ার্ক)", "Noun", "সুরক্ষা প্রাচীর, দুর্গ", "Education is a bulwark against poverty.", "শিক্ষা হলো দারিদ্র্যের বিরুদ্ধে এক সুরক্ষা প্রাচীর।", ["Safeguard", "Shield"], [], "BCS"),
    ("Buoyant", "/ˈbɔɪ.ənt/ (বয়েন্ট)", "Adj", "ভাসমান, উৎফুল্ল", "Market remained in a buoyant mood.", "বাজার এক চাঙ্গা চাঙ্গা মেজাজে ছিল।", ["Cheerful", "Floating"], ["Depressed"], "IELTS"),
    ("Burgeon", "/ˈbɜː.dʒən/ (বার্জন)", "Verb", "দ্রুত বিকশিত বা বৃদ্ধি পাওয়া", "Town turned into a burgeoning city.", "শহরটি দ্রুত বিকশিত নগরে পরিণত হয়েছিল।", ["Flourish", "Thrive"], ["Shrink"], "IELTS"),
    ("Burnish", "/ˈbɜː.nɪʃ/ (বার্নিশ)", "Verb", "উজ্জ্বল করা, পালিশ করা", "He worked hard to burnish his image.", "তিনি তার ভাবমূর্তি উজ্জ্বল করতে কঠোর পরিশ্রম করেছেন।", ["Polish", "Shine"], [], "Academic"),
    ("Buttress", "/ˈbʌt.rəs/ (বাট্রেস)", "Verb", "শক্তি বাড়ানো, স্তম্ভ দেওয়া", "Data was used to buttress argument.", "যুক্তি শক্তিশালী করতে তথ্য ব্যবহার করা হয়েছিল।", ["Support", "Reinforce"], ["Weaken"], "IELTS"),
    ("Cajole", "/kəˈdʒəʊl/ (কাজোল)", "Verb", "মিষ্টি কথায় প্রলুব্ধ করা", "She cajoled him into agreeing.", "সে তাকে মিষ্টি কথায় রাজি করিয়েছিল।", ["Coax", "Wheedle"], [], "Academic"),
    ("Calamity", "/kəˈlæm.ə.ti/ (ক্যালামিটি)", "Noun", "মহাবিপর্যয়, দুর্যোগ", "Flood was a severe calamity.", "বন্যাটি এক মারাত্মক বিপর্যয় ছিল।", ["Disaster", "Catastrophe"], [], "BCS"),
    ("Callous", "/ˈkæl.əs/ (ক্যালাস)", "Adj", "নির্দয়, অনুভূতিহীন", "He showed callous disregard for safety.", "সে নিরাপত্তার প্রতি নির্দয় উদাসীনতা দেখিয়েছিল।", ["Heartless", "Unfeeling"], ["Compassionate"], "IELTS"),
    ("Candor", "/ˈkæn.dər/ (ক্যান্ডর)", "Noun", "অকপটতা, স্পষ্টবাদিতা", "I appreciate your candor in interview.", "সাক্ষাৎকারে আপনার অকপটতার আমি প্রশংসা করি।", ["Frankness", "Honesty"], ["Deceit"], "IELTS"),
    ("Canonical", "/kəˈnɒn.ɪ.ক্যাল/ (ক্যানোনিক্যাল)", "Adj", "প্রামাণিক, স্বীকৃত নীতি অনুযায়ী", "It is part of canonical literature.", "এটি স্বীকৃত প্রামাণিক সাহিত্যের অংশ।", ["Accepted", "Standard"], [], "Academic"),
    ("Cantankerous", "/kænˈtæŋ.kər.əs/ (ক্যান্ট্যাঙ্কারাস)", "Adj", "ঝগড়াটে, বদমেজাজী", "The cantankerous old man yelled.", "ঝগড়াটে বৃদ্ধ লোকটি চিৎকার করেছিল।", ["Bad-tempered", "Irritable"], ["Good-natured"], "Academic"),
    ("Captivate", "/ˈkæp.tɪ.veɪt/ (ক্যাপটিভেট)", "Verb", "মনোমুগ্ধ বা বশীভূত করা", "Her performance captivated audience.", "তার পরিবেশনা দর্শকদের মোহিত করেছিল।", ["Charming", "Enchant"], ["Repel"], "Spoken"),
    ("Castigate", "/ˈkæs.tɪ.ɡeɪt/ (ক্যাস্টিগেট)", "Verb", "কঠোর ভর্ৎসনা করা", "The editor castigated the lazy writer.", "সম্পাদক অলস লেখককে কঠোর ভর্ৎসনা করেন।", ["Rebuke", "Reprimand"], ["Praise"], "BCS"),
    ("Cataclysm", "/ˈkæt.ə.klɪ.zəm/ (ক্যাটাক্লিজম)", "Noun", "প্রলয়, আমূল বিপর্যয়", "War proved to be a global cataclysm.", "যুদ্ধটি বিশ্বব্যাপী প্রলয় হিসেবে প্রমাণিত হয়েছিল।", ["Disaster", "Upheaval"], [], "Academic"),
    ("Catharsis", "/kəˈθɑː.sɪs/ (ক্যাথারসিস)", "Noun", "মানসিক ভারমুক্তকরণ, স্বস্তি", "Crying brought a sense of catharsis.", "কান্না মনে এক মানসিক ভারমুক্তির স্বস্তি এনেছিল।", ["Purification", "Release"], [], "Academic"),
    ("Caustic", "/ˈkɔː.stɪk/ (কস্টিক)", "Adj", "দগ্ধকারী, অত্যন্ত সর্দারি বা বিষাক্ত কথা", "He made a caustic remark.", "তিনি এক অত্যন্ত কড়া মন্তব্য করেছিলেন।", ["Sarcastic", "Biting"], ["Gentle"], "Academic"),
    ("Cede", "/siːd/ (সিড)", "Verb", "জমি বা অধিকার ছেড়ে দেওয়া", "The territory was ceded to victor.", "ভূখণ্ডটি বিজয়ী দলের কাছে ছেড়ে দেওয়া হয়েছিল।", ["Surrender", "Yield"], ["Retain"], "BCS"),
    ("Censure", "/ˈsen.ʃər/ (সেনশার)", "Noun", "নিন্দা, আনুষ্ঠানিক তিরস্কার", "Motion of censure passed in parliament.", "সংসদে নিন্দা প্রস্তাব গৃহীত হয়েছিল।", ["Condemnation", "Criticism"], ["Approval"], "BCS"),
    ("Charisma", "/kəˈrɪz.mə/ (ক্যারিশমা)", "Noun", "সম্মোহনী ব্যক্তিত্ব", "He possessed natural leadership charisma.", "তার স্বাভাবিক নেতৃত্বের সম্মোহনী গুণ ছিল।", ["Charm", "Magnetism"], [], "Spoken"),
    ("Charlatan", "/ˈʃɑː.lə.tən/ (শার্ল্যাটান)", "Noun", "ভণ্ড, হাতুড়ে ডাক্তার", "The charlatan sold fake medicines.", "ভণ্ড লোকটা নকল ওষুধ বিক্রি করেছিল।", ["Fraud", "Quack"], [], "Academic"),
    ("Chastise", "/tʃæsˈtaɪz/ (চ্যাস্টাইজ)", "Verb", "শাস্তি বা প্রহার দেওয়া", "Parent chastised child for lying.", "অভিভাবক মিথ্যা বলার জন্য সন্তানকে ভর্ৎসনা করেছিলেন।", ["Punish", "Scold"], ["Praise"], "Academic"),
    ("Chauvinism", "/ˈʃəʊ.vɪ.nɪ.zəm/ (শোভিনিজম)", "Noun", "অন্ধ দেশপ্রেম বা উগ্র পক্ষপাত", "He criticized aggressive chauvinism.", "তিনি উগ্র অন্ধ পক্ষপাতের সমালোচনা করেছিলেন।", ["Jingoism", "Fanaticism"], [], "BCS"),
    ("Chicanery", "/ʃɪˈkeɪ.nər.i/ (শিক্যানারি)", "Noun", "প্রতারণা, চক্রান্ত", "Financial chicanery ruined company.", "আর্থিক প্রতারণা প্রতিষ্ঠানটিকে ধ্বংস করেছে।", ["Deception", "Trickery"], ["Honesty"], "Academic"),
    ("Chronicle", "/ˈkrɒn.ɪ.kəl/ (ক্রনিকল)", "Noun", "কালানুক্রমিক ইতিহাস", "The book is a chronicle of freedom war.", "বইটি স্বাধীনতা যুদ্ধের এক কালানুক্রমিক ইতিহাস।", ["Record", "History"], [], "Spoken"),
    ("Circumlocution", "/ˌsɜː.kəm.ləˈkjuː.ʃən/ (সারকামলোকিউশন)", "Noun", "ঘুরিয়ে-ফিরিয়ে প্যাঁচালো কথা বলা", "Avoid circumlocution in concise writing.", "সংক্ষিপ্ত লেখায় কথার প্যাঁচানো এড়িয়ে চলুন।", ["Verbiage", "Indirectness"], ["Directness"], "Academic"),
    ("Circumspect", "/ˈsɜː.kəm.spekt/ (সারকামস্পেক্ট)", "Adj", "সতর্ক, দূরদর্শী", "Be circumspect when signing contracts.", "চুক্তি স্বাক্ষরের সময় সতর্ক থাকুন।", ["Cautious", "Prudent"], ["Careless"], "IELTS"),
    ("Circumvent", "/ˌsɜː.kəmˈvent/ (সারকামভেন্ট)", "Verb", "কৌশলে এড়িয়ে যাওয়া", "They tried to circumvent regulations.", "তারা কৌশলে নিয়মগুলো এড়িয়ে যাওয়ার চেষ্টা করে।", ["Bypass", "Evade"], [], "BCS"),
    ("Clandestine", "/klænˈdes.tɪn/ (ক্ল্যান্ডেস্টিন)", "Adj", "গুপ্ত, গোপনে পরিচালিত", "They held a clandestine meeting.", "তারা একটি গোপন বৈঠক পরিচালনা করেছিল।", ["Secret", "Covert"], ["Public"], "IELTS"),
    ("Clemency", "/ˈklem.ən.si/ (ক্লেমেনসি)", "Noun", "দয়া, অনুকম্পা", "The prisoner begged for clemency.", "বন্দীটি অনুকম্পার আকুল মিনতি করেছিল।", ["Mercy", "Leniency"], ["Cruelty"], "BCS"),
    ("Coalesce", "/ˌkəʊ.əˈles/ (কোয়ালেস)", "Verb", "একত্রিত হয়ে মিশে যাওয়া", "Small streams coalesce into river.", "ছোট ছোট ধারা মিলে নদীতে পরিণত হয়।", ["Merge", "Unite"], ["Separate"], "IELTS"),
    ("Cogent", "/ˈkəʊ.dʒənt/ (কোজেন্ট)", "Adj", "প্রবল যুক্তিযুক্ত, জোরদার", "He offered a cogent explanation.", "তিনি একটি অত্যন্ত শক্তিশালী যুক্তিযুক্ত ব্যাখ্যা দিয়েছিলেন।", ["Convincing", "Compelling"], ["Weak"], "IELTS"),
    ("Cognizant", "/ˈkɒɡ.nɪ.zənt/ (কগনিজ্যান্ট)", "Adj", "অবগত, সচেতন", "Be cognizant of potential risks.", "সম্ভাব্য ঝুঁকি সম্পর্কে সচেতন থাকুন।", ["Aware", "Conscious"], ["Unaware"], "IELTS"),
    ("Cohesion", "/kəʊˈhiː.ʒən/ (কোহেশন)", "Noun", "সংহতি, মেলবন্ধন", "Social cohesion is essential for peace.", "শান্তির জন্য সামাজিক সংহতি অপরিহার্য।", ["Unity", "Togetherness"], ["Division"], "IELTS"),
    ("Collaborative", "/kəˈlæb.ər.ə.tɪv/ (কোল্যাবোরেটিভ)", "Adj", "যৌথ, সহযোগীতামূলক", "It was a collaborative research effort.", "এটি একটি যৌথ গবেষণার প্রচেষ্টা ছিল।", ["Joint", "Cooperative"], [], "Spoken"),
    ("Colloquial", "/kəˈləʊ.kwi.əl/ (কলোকিয়াল)", "Adj", "কথ্য, অনানুষ্ঠানিক ভাষা", "Avoid colloquial terms in formal essay.", "আনুষ্ঠানিক প্রবন্ধে কথ্য ভাষা এড়িয়ে চলুন।", ["Informal", "Conversational"], ["Formal"], "Spoken"),
    ("Collusion", "/kəˈluː.ʒən/ (কলুশন)", "Noun", "গোপন চক্রান্ত", "Officials acted in collusion with thieves.", "কর্মকর্তারা চোরদের সাথে গোপন চক্রান্তে লিপ্ত ছিলেন।", ["Conspiracy", "Intrigue"], [], "BCS"),
    ("Commensurate", "/kəˈmen.sjər.ət/ (কমেনশুরেট)", "Adj", "সমানুপাতিক, উপযুক্ত", "Salary will be commensurate with experience.", "অভিজ্ঞতার সাথে সামঞ্জস্য রেখে বেতন দেওয়া হবে।", ["Proportional", "Equal"], ["Unequal"], "IELTS"),
    ("Commiserate", "/kəˈmɪz.ə.reɪt/ (কমিজ্যারেট)", "Verb", "সহমর্মিতা প্রকাশ করা", "We commiserated with him on loss.", "তার ক্ষতিতে আমরা সহমর্মিতা প্রকাশ করেছিলাম।", ["Sympathize", "Console"], [], "Academic"),
    ("Compelling", "/kəmˈpel.ɪŋ/ (কমপেলিং)", "Adj", "অপ্রতিরোধ্য, অত্যন্ত আকর্ষণীয়", "There is compelling evidence of crime.", "অপরাধের অত্যন্ত জোরালো প্রমাণ রয়েছে।", ["Persuasive", "Convincing"], ["Unconvincing"], "IELTS"),
    ("Compendium", "/kəmˈpen.di.əm/ (কমপেন্ডিয়াম)", "Noun", "সারসংক্ষেপ, সংক্ষিপ্ত সংকলন", "Book is a compendium of knowledge.", "বইটি জ্ঞানের এক সংক্ষিপ্ত সংকলন।", ["Summary", "Digest"], [], "Academic"),
    ("Complacent", "/kəmˈpleɪ.sənt/ (কমপ্লেসেন্ট)", "Adj", "আত্মতুষ্ট, অসাবধান", "Success made him complacent.", "সাফল্য তাকে অসাবধান ও আত্মতুষ্ট করে তুলেছিল।", ["Self-satisfied", "Smug"], ["Modest"], "IELTS"),
    ("Compliance", "/kəmˈplaɪ.əns/ (কমপ্লায়েন্স)", "Noun", "সম্মতি, অনুবর্তিতা", "Company ensured compliance with law.", "প্রতিষ্ঠানটি আইন মেনে চলা নিশ্চিত করেছে।", ["Obedience", "Conformity"], ["Refusal"], "BCS"),
    ("Complicity", "/kəmˈplɪs.ə.ti/ (কমপ্লিসিটি)", "Noun", "অপরাধে অংশীদারিত্ব", "There was no evidence of his complicity.", "তার অপরাধে অংশীদারিত্বের কোনো প্রমাণ ছিল না।", ["Involvement", "Collusion"], [], "BCS"),
    ("Composure", "/kəmˈpəʊ.ʒər/ (কম্পোজার)", "Noun", "মানসিক স্থিরতা, সংযম", "She kept her composure during crisis.", "সংকটের সময়ে তিনি মানসিক স্থিরতা বজায় রেখেছিলেন।", ["Calmness", "Poise"], ["Agitation"], "Spoken"),
    ("Compunction", "/kəmˈpʌŋk.ʃən/ (কমপাঙ্কশন)", "Noun", "অনুশোচনা, অনুতাপ", "He felt no compunction for lying.", "মিথ্যা বলার জন্য সে কোনো অনুশোচনা অনুভব করেনি।", ["Remorse", "Regret"], [], "Academic"),
    ("Concede", "/kənˈsiːd/ (কনসিড)", "Verb", "পরাজয় বা সত্যতা স্বীকার করা", "He conceded defeat graciously.", "তিনি মার্জিতভাবে পরাজয় স্বীকার করেছিলেন।", ["Admit", "Acknowledge"], ["Deny"], "IELTS"),
    ("Conceited", "/kənˈsiː.tɪd/ (কনসিটেড)", "Adj", "অহংকারী, আত্মম্ভরী", "Nobody likes a conceited person.", "কেউ একজন অহংকারী মানুষকে পছন্দ করে না।", ["Proud", "Arrogant"], ["Humble"], "Spoken"),
    ("Conciliatory", "/kənˈsɪl.i.ə.tər.i/ (কনসিলিয়েটরি)", "Adj", "সমঝোতামূলক, শান্তিকামী", "He took a conciliatory tone.", "তিনি এক সমঝোতামূলক সুর গ্রহণ করেছিলেন।", ["Pacifying", "Appeasing"], ["Hostile"], "BCS"),
    ("Concise", "/kənˈsaɪs/ (কনসাইস)", "Adj", "সংক্ষিপ্ত ও অর্থপূর্ণ", "Write a concise summary.", "একটি সংক্ষিপ্ত ও অর্থপূর্ণ সারসংক্ষেপ লিখুন।", ["Brief", "Succinct"], ["Verbose"], "Spoken"),
    ("Concur", "/kənˈkɜːr/ (কনকার)", "Verb", "একমত হওয়া", "All members concurred with decision.", "সব সদস্য সিদ্ধান্তের সাথে একমত হয়েছিলেন।", ["Agree", "Coincide"], ["Disagree"], "IELTS"),
    ("Condone", "/kənˈdəʊn/ (কোনডোন)", "Verb", "উপেক্ষা বা ক্ষমা করা", "School does not condone bullying.", "স্কুল কোনো উত্যক্তকরণ প্রশ্রয় দেয় না।", ["Overlook", "Forgive"], ["Condemn"], "BCS"),
    ("Conducive", "/kənˈdʒuː.sɪv/ (কনডিউসিভ)", "Adj", "সহায়ক, অনুকূল", "Quiet room is conducive to study.", "একটি শান্ত ঘর পড়াশোনার জন্য অত্যন্ত সহায়ক।", ["Favorable", "Helpful"], ["Unfavorable"], "IELTS"),
    ("Confluence", "/ˈkɒn.flu.əns/ (কনফ্লুয়েন্স)", "Noun", "মিলনস্থল, সংগম", "City lies at confluence of two rivers.", "শহরটি দুই নদীর মিলনস্থলে অবস্থিত।", ["Junction", "Convergence"], [], "Academic"),
    ("Confound", "/kənˈfaʊnd/ (কনফাউন্ড)", "Verb", "হতবুদ্ধি বা বিভ্রান্ত করা", "His victory confounded all experts.", "তার বিজয় সব বিশেষজ্ঞকে হতবুদ্ধি করে দিয়েছিল।", ["Confuse", "Amaze"], [], "IELTS"),
    ("Congenial", "/kənˈdʒiː.ni.əl/ (কনজিনিয়াল)", "Adj", "উপযোগী, মনোপূত", "We found a congenial environment.", "আমরা আমাদের উপযোগী এক পরিবেশ পেয়েছিলাম।", ["Pleasant", "Compatible"], ["Disagreeable"], "Spoken"),
    ("Congregation", "/ˌkɒŋ.ɡrɪˈɡeɪ.ʃən/ (কংগ্রিগেশন)", "Noun", "ধর্মীয় সমাবেশ", "Priest addressed the congregation.", "পুরোহিত ধর্মীয় সমাবেশে বক্তব্য রাখেন।", ["Gathering", "Assembly"], [], "Spoken"),
    ("Conjecture", "/kənˈdʒek.tʃər/ (কনজেকচার)", "Noun", "অনুমান, কাল্পনিক ধারণা", "That is mere conjecture without proof.", "প্রমাণ ছাড়া ওটি নিছক অনুমান মাত্র।", ["Guess", "Speculation"], ["Fact"], "IELTS"),
    ("Conjure", "/ˈkʌn.dʒər/ (কানজার)", "Verb", "জাদু দিয়ে সৃষ্টি বা হাজির করা", "Magician conjured a rabbit.", "জাদুকর একটি খরগোশ হাজির করেছিলেন।", ["Evoke", "Summon"], [], "Spoken"),
    ("Connive", "/kəˈnaɪv/ (কনাইভ)", "Verb", "গোপনে অন্যায় কাজে মদদ দেওয়া", "Guards connived at the escape.", "প্রহরীরা পালানোর কাজে গোপনে মদদ দিয়েছিল।", ["Conspire", "Collude"], [], "Academic"),
    ("Connoisseur", "/ˌkɒn.əˈsɜːr/ (কনয়সার)", "Noun", "সূক্ষ্ম রসবোধসম্পন্ন জহুরি", "He is a connoisseur of art.", "তিনি শিল্পের একজন সূক্ষ্ম জহুরি।", ["Expert", "Judge"], [], "IELTS"),
    ("Consecrate", "/ˈkɒn.sɪ.kreɪt/ (কনসিক্রেট)", "Verb", "পবিত্র ঘোষণা বা উৎসর্গ করা", "Temple was consecrated by priest.", "পুরোহিত মন্দিরটি উৎসর্গ ও পবিত্র ঘোষণা করেন।", ["Sanctify", "Bless"], [], "BCS"),
    ("Consensus", "/kənˈsen.səs/ (কনসেনসাস)", "Noun", "সর্বসম্মত মতামত", "They reached a consensus after debate.", "বিতর্কের পর তারা এক সর্বসম্মত মতামতে পৌঁছেছিলেন।", ["Agreement", "Accord"], ["Disagreement"], "IELTS"),
    ("Console", "/kənˈsəʊl/ (কনসোল)", "Verb", "সান্ত্বনা দেওয়া", "I tried to console grieving friend.", "আমি শোকাহত বন্ধুকে সান্ত্বনা দেওয়ার চেষ্টা করি।", ["Comfort", "Soothe"], [], "Spoken"),
    ("Consolidate", "/kənˈsɒl.ɪ.deɪt/ (কনসলিডেট)", "Verb", "দৃঢ় বা একত্র করা", "Company decided to consolidate gains.", "প্রতিষ্ঠানটি তাদের অবস্থান সুদৃঢ় করার সিদ্ধান্ত নেয়।", ["Strengthen", "Unite"], ["Weaken"], "IELTS"),
    ("Consonance", "/ˈkɒn.sə.nəns/ (কনসোনেন্স)", "Noun", "মিল, সামঞ্জস্য", "His actions are in consonance with law.", "তার কাজ আইনের সাথে পূর্ণ সামঞ্জস্যপূর্ণ।", ["Agreement", "Harmony"], ["Discord"], "Academic"),
    ("Conspicuous", "/kənˈspɪk.ju.əs/ (কনস্পিকুয়াস)", "Adj", "চোখে পড়ার মতো, স্পষ্ট", "He was conspicuous by his absence.", "তিনি অনুপস্থিতির কারণে স্পষ্ট চোখে পড়ার মতো ছিলেন।", ["Noticeable", "Prominent"], ["Inconspicuous"], "IELTS"),
    ("Consternation", "/ˌkɒn.stəˈneɪ.ʃən/ (কনস্টারনেশন)", "Noun", "হঠাৎ আতঙ্ক বা বিহ্বলতা", "News caused widespread consternation.", "সংবাদটি ব্যাপক আতঙ্ক ও বিহ্বলতার সৃষ্টি করেছিল।", ["Dismay", "Alarm"], ["Calmness"], "Academic"),
    ("Constituent", "/kənˈstɪtʃ.u.ənt/ (কনস্টিটিউয়েন্ট)", "Noun", "উপাদান, ভোটার", "MP met with his constituents.", "সংসদ সদস্য তার এলাকার ভোটারদের সাথে দেখা করেন।", ["Component", "Voter"], [], "BCS"),
    ("Constraint", "/kənˈstreɪnt/ (কনস্ট্রেইন্ট)", "Noun", "সীমাবদ্ধতা, বাধা", "Budget constraint limited project scope.", "বাজেটের সীমাবদ্ধতা প্রকল্পের পরিধি কমিয়ে দিয়েছিল।", ["Limitation", "Restriction"], [], "IELTS"),
    ("Construe", "/kənˈstruː/ (কনস্ট্রু)", "Verb", "অর্থ অনুধাবন করা, ব্যাখ্যা করা", "Her silence was construed as agreement.", "তার নীরবতাকে সম্মতি হিসেবে ব্যাখ্যা করা হয়েছিল।", ["Interpret", "Understand"], [], "BCS"),
    ("Consummate", "/ˈkɒn.sə.mət/ (কনসামেট)", "Adj", "নিপুণ, নিখুঁত", "He displayed consummate diplomacy.", "তিনি নিপুণ কূটনীতি প্রদর্শন করেছিলেন।", ["Flawless", "Perfect"], ["Imperfect"], "BCS"),
    ("Contagious", "/kənˈteɪ.dʒəs/ (কনটেজিয়াস)", "Adj", "ছোঁয়াচে, সংক্রামক", "Her laughter was contagious.", "তার হাসি ছিল সংক্রামক।", ["Infectious", "Catching"], [], "Spoken"),
    ("Contemplate", "/ˈkɒn.təm.pleɪt/ (কনটেমপ্লেট)", "Verb", "গভীরভাবে চিন্তা করা", "She contemplated moving abroad.", "তিনি বিদেশে যাওয়ার কথা গভীরভাবে চিন্তা করেছিলেন।", ["Ponder", "Consider"], [], "Spoken"),
    ("Contempt", "/kənˈtempt/ (কনটেম্পট)", "Noun", "অবজ্ঞা, অবমাননা", "He was charged with contempt of court.", "তার বিরুদ্ধে আদালত অবমাননার অভিযোগ আনা হয়।", ["Disdain", "Scorn"], ["Respect"], "BCS"),
    ("Contend", "/kənˈtend/ (কনটেন্ড)", "Verb", "দাবি করা, প্রতিযোগিতা করা", "Lawyers contend that client is innocent.", "আইনজীবীরা দাবি করেন মক্কেল নির্দোষ।", ["Assert", "Compete"], [], "IELTS"),
    ("Contention", "/kənˈten.ʃən/ (কনটেনশন)", "Noun", "বিতর্ক, যুক্তি, দাবি", "Point of contention remains unresolved.", "বিতর্কের মূল বিষয়টির সুরাহা হয়নি।", ["Dispute", "Argument"], [], "IELTS"),
    ("Contentious", "/kənˈten.ʃəs/ (কনটেনশাস)", "Adj", "বিতর্কিত, বিবাদপ্রিয়", "It was a highly contentious issue.", "এটি ছিল একটি অত্যন্ত বিতর্কিত বিষয়।", ["Controversial", "Quarrelsome"], [], "IELTS"),
    ("Contingency", "/kənˈtɪn.dʒən.si/ (কনটিনজেন্সি)", "Noun", "আকস্মিক পরিস্থিতি, জরুরি সম্ভাবনা", "We must prepare for every contingency.", "আমাদের প্রতিটি আকস্মিক পরিস্থিতির জন্য প্রস্তুত থাকা উচিত।", ["Emergency", "Possibility"], [], "BCS"),
    ("Conundrum", "/kəˈnʌn.drəm/ (কনানড্রাম)", "Noun", "জটিল ধাঁধা বা সংকট", "Solving poverty is a complex conundrum.", "দারিদ্র্য দূরীকরণ এক জটিল সংকট।", ["Puzzle", "Riddle"], [], "IELTS"),
    ("Convergence", "/kənˈvɜː.dʒəns/ (কনভার্জেন্স)", "Noun", "একবিন্দুতে সম্মেলন", "Media convergence is transforming news.", "মিডিয়ার একবিন্দুতে মিলন সংবাদ ব্যবস্থাকে বদলে দিচ্ছে।", ["Union", "Merging"], ["Divergence"], "IELTS"),
    ("Convivial", "/kənˈvɪv.i.əl/ (কনভিভিয়াল)", "Adj", "আনন্দমুখর, উৎসবপ্রিয়", "Dinner party had a convivial atmosphere.", "নৈশভোজের পার্টিতে আনন্দমুখর পরিবেশ ছিল।", ["Festive", "Friendly"], [], "Academic"),
    ("Convoluted", "/ˈkɒn.və.luː.tɪd/ (কনভোলুটেড)", "Adj", "প্যাঁচালো, অত্যন্ত জটিল", "Plot of movie was too convoluted.", "চলচ্চিত্রের কাহিনী বড্ড প্যাঁচালো ছিল।", ["Complicated", "Intricate"], ["Simple"], "IELTS"),
    ("Copious", "/ˈkəʊ.pi.əs/ (কোপিয়াস)", "Adj", "প্রচুর, প্রভূত", "She took copious notes during lecture.", "লেকচারের সময় সে প্রচুর নোট নিয়েছিল।", ["Abundant", "Plentiful"], ["Sparse"], "IELTS"),
    ("Cordial", "/ˈkɔː.di.əl/ (কর্ডিয়াল)", "Adj", "আন্তরিক, হৃদ্যতাপূর্ণ", "Host extended a cordial welcome.", "স্বাগতিক ব্যক্তি চমৎকার আন্তরিক অভ্যর্থনা জানান।", ["Warm", "Friendly"], ["Cold"], "Spoken"),
    ("Corporeal", "/kɔːˈpɔː.ri.əl/ (কর্পোরিয়াল)", "Adj", "দেহতাত্ত্বিক, পার্থিব", "Angels lack corporeal form.", "ফেরেশতাদের কোনো শারীরিক দেহতাত্ত্বিক রূপ নেই।", ["Bodily", "Physical"], ["Spiritual"], "Academic"),
    ("Corroborate", "/kəˈrɒb.ə.reɪt/ (করোবোরেট)", "Verb", "সাক্ষ্য বা প্রমাণ দিয়ে সমর্থন করা", "Witness corroborated victim's story.", "সাক্ষী ভুক্তভোগীর বক্তব্যের পক্ষে সত্যতা নিশ্চিত করেন।", ["Confirm", "Verify"], ["Contradict"], "IELTS"),
    ("Corrosive", "/kəˈrəʊ.sɪv/ (করোসিভ)", "Adj", "ক্ষয়কারী, ধ্বংসাত্মক", "Acid has a corrosive effect.", "এসিডের ক্ষয়কারী প্রভাব রয়েছে।", ["Destructive", "Caustic"], [], "Academic"),
    ("Cosmopolitan", "/ˌkɒz.məˈpɒl.ɪ.tən/ (কসমোপলিটন)", "Adj", "সর্বজনীন, বিশ্বজনীন শহর", "London is a truly cosmopolitan city.", "লন্ডন একটি সত্যি বিশ্বজনীন শহর।", ["Global", "Universal"], ["Local"], "Spoken"),
    ("Covenant", "/ˈkʌv.ən.ənt/ (কাভেন্যান্ট)", "Noun", "পবিত্র চুক্তি বা অঙ্গীকার", "They signed a solemn covenant.", "তারা একটি পবিত্র অঙ্গীকারপত্রে স্বাক্ষর করেছিলেন।", ["Pact", "Agreement"], [], "BCS"),
    ("Covert", "/ˈkʌv.ət/ (কাভার্ট)", "Adj", "গোপন, ছদ্মবেশী", "Agents carried out covert operation.", "এজেন্টরা গোপন অভিযান পরিচালনা করেছিল।", ["Secret", "Hidden"], ["Overt"], "IELTS"),
    ("Covetous", "/ˈkʌv.ɪ.təs/ (কাভেটাস)", "Adj", "লোভী, লোলুপ", "He cast a covetous eye on gold.", "সে সোনার দিকে এক লোলুপ দৃষ্টি ফেলল।", ["Greedy", "Envious"], [], "Academic"),
    ("Cower", "/ˈkaʊ.ər/ (কাওয়ার)", "Verb", "ভয়ে কেঁপে ওঠা বা কুঁকড়ে যাওয়া", "Dog cowered in corner during storm.", "ঝড়ের সময় কুকুরটি কোণায় ভয়ে কুঁকড়ে ছিল।", ["Cringe", "Shrink"], [], "Spoken"),
    ("Cozen", "/ˈkʌz.ən/ (কাজেন)", "Verb", "প্রতারণা করে ঠকানো", "He was cozened out of his savings.", "প্রতারণা করে তার সঞ্চয় হাতিয়ে নেওয়া হয়েছিল।", ["Deceive", "Cheat"], [], "Academic"),
    ("Credence", "/ˈkriː.dəns/ (ক্রিডেন্স)", "Noun", "বিশ্বাসযোগ্যতা, আস্থা", "His statement lends credence to rumor.", "তার বক্তব্য গুজবের বিশ্বাসযোগ্যতা বাড়িয়ে দেয়।", ["Belief", "Credibility"], ["Distrust"], "IELTS"),
    ("Credulous", "/ˈkredʒ.ə.ləs/ (ক্রিডিউলাস)", "Adj", "সহজ বিশ্বাসী, কানকথা বিশ্বাস করে এমন", "Don't be so credulous about fake news.", "ভুয়া খবর নিয়ে এতটা সহজ বিশ্বাসী হবেন না।", ["Gullible", "Naïve"], ["Skeptical"], "IELTS"),
    ("Crestfallen", "/ˈkrest.fɔː.lən/ (ক্রエストফলন)", "Adj", "হতাশ, মনভাঙ্গা", "He looked crestfallen after rejection.", "প্রত্যাখ্যাত হওয়ার পর তাকে চরম হতাশ দেখাচ্ছিল।", ["Dejected", "Disappointed"], ["Elated"], "Academic"),
    ("Criteria", "/kraɪˈtɪə.ri.ə/ (ক্রাইটেরিয়া)", "Noun", "মানদণ্ড, নির্ণায়ক", "What are criteria for selection?", "নির্বাচনের মূল মানদণ্ডগুলো কী কী?।", ["Standards", "Benchmarks"], [], "Spoken"),
    ("Culpable", "/ˈkʌl.pə.bəl/ (কালপ্যাবল)", "Adj", "দণ্ডনীয়, অপরাধী, দায়ী", "Driver was found culpable for accident.", "দুর্ঘটনার জন্য চালককে দায়ী পাওয়া গিয়েছিল।", ["Guilty", "Blameworthy"], ["Innocent"], "BCS"),
    ("Culmination", "/ˌkʌl.mɪˈneɪ.ʃən/ (কালমিনেশন)", "Noun", "চূড়ান্ত পরিণতি, চরম শিখর", "Book is culmination of years of work.", "বইটি বহু বছরের কাজের এক চূড়ান্ত রূপ।", ["Climax", "Peak"], [], "IELTS"),
    ("Cumulative", "/ˈkjuː.mjə.lə.tɪv/ (কিউমুলেটিভ)", "Adj", "ক্রমপুঞ্জীভূত, সঞ্চিত", "Stress has a cumulative effect on health.", "মানসিক চাপ স্বাস্থ্যের ওপর ক্রমপুঞ্জীভূত প্রভাব ফেলে।", ["Increasing", "Accumulated"], [], "Spoken"),
    ("Cusp", "/kʌsp/ (কাস্প)", "Noun", "পরিবর্তনের সন্ধিক্ষণ", "We are on cusp of new era.", "আমরা এক নতুন যুগের সন্ধিক্ষণে দাঁড়িয়ে আছি।", ["Threshold", "Verge"], [], "Spoken"),
    ("Curator", "/kjʊəˈreɪ.tər/ (কিউরেটর)", "Noun", "জাদুঘর বা প্রদর্শনী তত্ত্বাবধায়ক", "Curator explained history of exhibit.", "তত্ত্বাবধায়ক প্রদর্শনীটির ইতিহাস ব্যাখ্যা করেছিলেন।", ["Keeper", "Custodian"], [], "Spoken"),
    ("Cursory", "/ˈkɜː.sər.i/ (কার্সরি)", "Adj", "ভাসা-ভাসা, দ্রুত চোখ বোলানো", "He gave document a cursory glance.", "তিনি নথিটিতে কেবল ভাসা-ভাসা চোখ বুলিয়েছিলেন।", ["Hasty", "Casual"], ["Thorough"], "IELTS"),
    ("Curtail", "/kərˈteɪl/ (কারটেইল)", "Verb", "হ্রাস করা, ছাঁটাই করা", "We must curtail unnecessary spending.", "আমাদের অবশ্যই অপ্রয়োজনীয় ব্যয় ছাঁটাই করতে হবে।", ["Reduce", "Shorten"], ["Expand"], "IELTS"),
    ("Cynicism", "/ˈsɪn.ɪ.sɪ.zəm/ (সিনিসিজম)", "Noun", "নৈরাশবাদ, মানুষের মনোভাব নিয়ে খিটখিটে মনোভাব", "There is growing cynicism about politics.", "রাজনীতি নিয়ে নৈরাশবাদ বৃদ্ধি পাচ্ছে।", ["Skepticism", "Doubt"], ["Optimism"], "IELTS")
]

# Deduplicate raw_data against existing_words and internally
final_300 = []
seen_in_new = set()

for item in raw_data:
    w_str = item[0].strip()
    w_key = w_str.lower()
    if w_key not in existing_words and w_key not in seen_in_new:
        seen_in_new.add(w_key)
        final_300.append(item)

print(f"Total unique new valid candidate words ready: {len(final_300)}")

# Save intermediate candidate list to json for verification
with open('new_300_words.json', 'w', encoding='utf-8') as f:
    json.dump(final_300, f, ensure_ascii=False, indent=2)

