# coding=utf-8

words_p5 = [
  {
    "word": "Abate",
    "phonetic": "/əˈbeɪt/ (অ্যাবেইট)",
    "partOfSpeech": "Verb",
    "meaningBn": "হ্রাস পাওয়া, তীব্রতা কমা",
    "exampleEn": "The storm began to abate after midnight.",
    "exampleBn": "মধ্যরাতের পর ঝড়ের তীব্রতা কমতে শুরু করে।",
    "synonyms": ["subside", "decrease", "dwindle"],
    "antonyms": ["increase", "intensify"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 201
  },
  {
    "word": "Brevity",
    "phonetic": "/ˈbrevəti/ (ব্রেভিটি)",
    "partOfSpeech": "Noun",
    "meaningBn": "সংক্ষিপ্ততা, স্বল্পতা",
    "exampleEn": "The brevity of his speech was appreciated by everyone.",
    "exampleBn": "তার বক্তব্যের সংক্ষিপ্ততা সবার কাছে প্রশংসিত হয়েছিল।",
    "synonyms": ["conciseness", "shortness", "succinctness"],
    "antonyms": ["verbosity", "lengthiness"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 202
  },
  {
    "word": "Culpable",
    "phonetic": "/ˈkʌlpəbl/ (কালপাবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "দণ্ডনীয়, অপরাধী, দোষী",
    "exampleEn": "He was held culpable for the negligence that led to the accident.",
    "exampleBn": "দুর্ঘটনার কারণ হওয়া অবহেলার জন্য তাকে দোষী সাব্যস্ত করা হয়েছিল।",
    "synonyms": ["blameworthy", "guilty", "answerable"],
    "antonyms": ["blameless", "innocent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 203
  },
  {
    "word": "Detrimental",
    "phonetic": "/ˌdetrɪˈmentl/ (ডেট্রিমেন্টাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "ক্ষতিকর, ক্ষতিকর প্রভাব ফেলে এমন",
    "exampleEn": "Smoking is detrimental to health.",
    "exampleBn": "ধূমপান স্বাস্থ্যের জন্য ক্ষতিকর।",
    "synonyms": ["harmful", "damaging", "injurious"],
    "antonyms": ["beneficial", "helpful"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 204
  },
  {
    "word": "Eloquent",
    "phonetic": "/ˈeləkwənt/ (ইলোকুয়েন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বাকপটু, সাবলীল বক্তা",
    "exampleEn": "She delivered an eloquent speech on human rights.",
    "exampleBn": "তিনি মানবাধিকারের ওপর একটি সাবলীল ও বাকপটু ভাষণ দিয়েছিলেন।",
    "synonyms": ["articulate", "fluent", "expressive"],
    "antonyms": ["inarticulate", "hesitant"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 205
  },
  {
    "word": "Feasible",
    "phonetic": "/ˈfiːzəbl/ (ফিজিবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সম্ভব, বাস্তবায়নযোগ্য",
    "exampleEn": "It is not feasible to finish this project in two days.",
    "exampleBn": "দুই দিনে এই কাজটি শেষ করা সম্ভব বা বাস্তবায়নযোগ্য নয়।",
    "synonyms": ["viable", "practicable", "workable"],
    "antonyms": ["unfeasible", "impossible"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 206
  },
  {
    "word": "Gregarious",
    "phonetic": "/ɡrɪˈɡeəriəs/ (গ্রিগ্যারিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "মিশুক, সংঘপ্রিয়",
    "exampleEn": "He is a gregarious person who enjoys attending social gatherings.",
    "exampleBn": "তিনি একজন মিশুক মানুষ যিনি সামাজিক অনুষ্ঠানে যোগ দিতে পছন্দ করেন।",
    "synonyms": ["sociable", "outgoing", "friendly"],
    "antonyms": ["introverted", "reserved"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 207
  },
  {
    "word": "Hinder",
    "phonetic": "/ˈhɪndər/ (হিন্ডার)",
    "partOfSpeech": "Verb",
    "meaningBn": "বাধা দেওয়া, অগ্রগতি ব্যাহত করা",
    "exampleEn": "Bad weather hindered the rescue operation.",
    "exampleBn": "খারাপ আবহাওয়া উদ্ধারকাজে বাধা সৃষ্টি করেছিল।",
    "synonyms": ["impede", "obstruct", "hamper"],
    "antonyms": ["facilitate", "encourage"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 208
  },
  {
    "word": "Impartial",
    "phonetic": "/ɪmˈpɑːʃl/ (ইম্পার্শাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "নিরপেক্ষ, পক্ষপাতহীন",
    "exampleEn": "A judge must remain impartial during the trial.",
    "exampleBn": "বিচার চলাকালীন একজন বিচারককে অবশ্যই নিরপেক্ষ থাকতে হবে।",
    "synonyms": ["unbiased", "neutral", "fair"],
    "antonyms": ["biased", "partial"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 209
  },
  {
    "word": "Judicious",
    "phonetic": "/dʒuːˈdɪʃəs/ (জুডিশাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বিচক্ষণ, সুবিবেচক",
    "exampleEn": "A judicious use of resources can save a lot of money.",
    "exampleBn": "সম্পদের বিচক্ষণ ব্যবহার প্রচুর অর্থ বাঁচাতে পারে।",
    "synonyms": ["wise", "prudent", "sensible"],
    "antonyms": ["foolish", "unwise"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 210
  },
  {
    "word": "Keen",
    "phonetic": "/kiːn/ (কীন)",
    "partOfSpeech": "Adjective",
    "meaningBn": "আগ্রহী, প্রখর বা তীব্র",
    "exampleEn": "He has a keen interest in learning new programming languages.",
    "exampleBn": "নতুন প্রোগ্রামিং ভাষা শেখার প্রতি তার প্রখর আগ্রহ রয়েছে।",
    "synonyms": ["eager", "sharp", "enthusiastic"],
    "antonyms": ["indifferent", "apathetic"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 211
  },
  {
    "word": "Lethargic",
    "phonetic": "/ləˈθɑːdʒɪk/ (লেথারজিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অলস, অলস প্রকৃতির, ঝিমানো",
    "exampleEn": "Feeling lethargic after lunch is quite common.",
    "exampleBn": "দুপুরের খাবারের পর অলস বা ঝিমুনি অনুভব করা বেশ স্বাভাবিক।",
    "synonyms": ["sluggish", "inactive", "lazy"],
    "antonyms": ["energetic", "active"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 212
  },
  {
    "word": "Mitigate",
    "phonetic": "/ˈmɪtɪɡeɪt/ (মিটিগেইট)",
    "partOfSpeech": "Verb",
    "meaningBn": "প্রশমিত করা, তীব্রতা কমানো",
    "exampleEn": "Steps were taken to mitigate the effects of the flood.",
    "exampleBn": "বন্যার ক্ষয়ক্ষতি প্রশমিত করার জন্য পদক্ষেপ নেওয়া হয়েছিল।",
    "synonyms": ["alleviate", "reduce", "ease"],
    "antonyms": ["aggravate", "worsen"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 213
  },
  {
    "word": "Notorious",
    "phonetic": "/nəʊˈtɔːriəs/ (নোটোরিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "কুখ্যাত, খারাপ কাজে পরিচিত",
    "exampleEn": "The criminal was notorious for bank robberies.",
    "exampleBn": "অপরাধীটি ব্যাংক ডাকাতির জন্য কুখ্যাত ছিল।",
    "synonyms": ["infamous", "disreputable"],
    "antonyms": ["famous", "reputable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 214
  },
  {
    "word": "Obsolete",
    "phonetic": "/ˈɒbsəliːt/ (অবসলিট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সেকেলে, অপ্রচলিত",
    "exampleEn": "Floppy disks have become obsolete in modern computing.",
    "exampleBn": "আধুনিক কম্পিউটিংয়ে ফ্লপি ডিস্ক অপ্রচলিত হয়ে পড়েছে।",
    "synonyms": ["outdated", "archaic", "outmoded"],
    "antonyms": ["modern", "current"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 215
  },
  {
    "word": "Pragmatic",
    "phonetic": "/præɡˈmætɪk/ (প্র্যাগম্যাটিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বাস্তবসম্মত, প্রয়োগমুখী",
    "exampleEn": "We need a pragmatic approach to solve this issue.",
    "exampleBn": "এই সমস্যা সমাধানের জন্য আমাদের একটি বাস্তবসম্মত দৃষ্টিভঙ্গি দরকার।",
    "synonyms": ["practical", "realistic", "sensible"],
    "antonyms": ["idealistic", "impractical"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 216
  },
  {
    "word": "Quandary",
    "phonetic": "/ˈkwɒndəri/ (কোয়ান্ডারি)",
    "partOfSpeech": "Noun",
    "meaningBn": "উভয়সংকট, দ্বিধাদ্বন্দ্ব",
    "exampleEn": "He was in a quandary about whether to accept the job offer.",
    "exampleBn": "চাকরির প্রস্তাবটি গ্রহণ করবেন কি না তা নিয়ে তিনি উভয়সংকটে পড়েছিলেন।",
    "synonyms": ["dilemma", "predicament", "plight"],
    "antonyms": [],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 217
  },
  {
    "word": "Redundant",
    "phonetic": "/rɪˈdʌndənt/ (রিডানড্যান্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অতিরিক্ত, অপ্রয়োজনীয়",
    "exampleEn": "The edit removed several redundant words from the article.",
    "exampleBn": "সম্পাদনার মাধ্যমে নিবন্ধটি থেকে বেশ কিছু অপ্রয়োজনীয় শব্দ বাদ দেওয়া হয়েছে।",
    "synonyms": ["superfluous", "unnecessary", "excess"],
    "antonyms": ["essential", "necessary"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 218
  },
  {
    "word": "Subtle",
    "phonetic": "/ˈsʌtl/ (সাটল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সূক্ষ্ম, যা সহজে চোখে পড়ে না",
    "exampleEn": "There is a subtle difference between the two concepts.",
    "exampleBn": "ধারণা দুটির মধ্যে একটি সূক্ষ্ম পার্থক্য রয়েছে।",
    "synonyms": ["delicate", "fine", "understated"],
    "antonyms": ["obvious", "blatant"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 219
  },
  {
    "word": "Tantamount",
    "phonetic": "/ˈtæntəmaʊnt/ (ট্যান্টামাউন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সমপরিমাণ, সমতুল্য",
    "exampleEn": "Refusing to answer is tantamount to an admission of guilt.",
    "exampleBn": "উত্তর দিতে অস্বীকার করা দোষ স্বীকার করার সমতুল্য।",
    "synonyms": ["equivalent", "equal", "commensurate"],
    "antonyms": ["different", "opposite"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 220
  },
  {
    "word": "Ubiquitous",
    "phonetic": "/juːˈbɪkwɪtəs/ (ইউবিকুইটাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সর্বব্যাপী, যা সব জায়গায় বিদ্যমান",
    "exampleEn": "Smartphones have become ubiquitous in daily life.",
    "exampleBn": "স্মার্টফোন দৈনন্দিন জীবনে সর্বব্যাপী হয়ে উঠেছে।",
    "synonyms": ["omnipresent", "pervasive", "universal"],
    "antonyms": ["rare", "scarce"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 221
  },
  {
    "word": "Venerate",
    "phonetic": "/ˈvenəreɪt/ (ভেনারেট)",
    "partOfSpeech": "Verb",
    "meaningBn": "গভীর শ্রদ্ধা করা, পূজা বা মান্য করা",
    "exampleEn": "Many cultures venerate their elders for their wisdom.",
    "exampleBn": "অনেক সংস্কৃতিতে তাদের বয়োজ্যেষ্ঠদের জ্ঞানের জন্য গভীরভাবে শ্রদ্ধা করা হয়।",
    "synonyms": ["revere", "respect", "honor"],
    "antonyms": ["despise", "scorn"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 222
  },
  {
    "word": "Whimsical",
    "phonetic": "/ˈwɪmzɪkl/ (উইমজিক্যাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "খেয়ালি, কল্পনাপ্রসূত, অদ্ভুত",
    "exampleEn": "The book is full of whimsical stories and illustrations.",
    "exampleBn": "বইটি অদ্ভুত ও কল্পনাপ্রসূত গল্প এবং চিত্রে ভরা।",
    "synonyms": ["fanciful", "playful", "capricious"],
    "antonyms": ["serious", "sensible"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 223
  },
  {
    "word": "Xenophobia",
    "phonetic": "/ˌzenəˈfəʊbiə/ (জেনোফোবিয়া)",
    "partOfSpeech": "Noun",
    "meaningBn": "বিদেশি বা বহিরাগতদের প্রতি অযৌক্তিক ভয় বা বিদ্বেষ",
    "exampleEn": "Education is essential to combat racism and xenophobia.",
    "exampleBn": "বর্ণবাদ এবং বিদেশি-বিদ্বেষ মোকাবিলার জন্য শিক্ষা অপরিহার্য।",
    "synonyms": ["chauvinism", "prejudice", "intolerance"],
    "antonyms": ["tolerance", "acceptance"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 224
  },
  {
    "word": "Yield",
    "phonetic": "/jiːld/ (যিল্ড)",
    "partOfSpeech": "Verb / Noun",
    "meaningBn": "উৎপাদন করা, নতি স্বীকার করা; ফলন",
    "exampleEn": "This farmland yields a rich harvest every year.",
    "exampleBn": "এই ফসলি জমি প্রতি বছর প্রচুর ফলন দেয়।",
    "synonyms": ["produce", "generate", "surrender"],
    "antonyms": ["resist", "withstand"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 225
  },
  {
    "word": "Zealous",
    "phonetic": "/ˈzeləs/ (জেলাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "প্রবল উৎসাহী, সংকল্পবদ্ধ",
    "exampleEn": "The zealous volunteers worked day and night.",
    "exampleBn": "প্রবল উৎসাহী স্বেচ্ছাসেবকরা দিনরাত কাজ করেছিলেন।",
    "synonyms": ["enthusiastic", "passionate", "ardent"],
    "antonyms": ["apathetic", "indifferent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 226
  },
  {
    "word": "Apathy",
    "phonetic": "/ˈæpəθi/ (অ্যাপাথি)",
    "partOfSpeech": "Noun",
    "meaningBn": "উদাসীনতা, আগ্রহহীনতা",
    "exampleEn": "Voter apathy is a concern for democratic countries.",
    "exampleBn": "ভোটারদের উদাসীনতা গণতান্ত্রিক দেশগুলোর জন্য একটি উদ্বেগের বিষয়।",
    "synonyms": ["indifference", "unconcern", "passivity"],
    "antonyms": ["enthusiasm", "concern"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 227
  },
  {
    "word": "Benevolence",
    "phonetic": "/bəˈnevələns/ (বেনেভোলেন্স)",
    "partOfSpeech": "Noun",
    "meaningBn": "দয়ালুতা, পরোপকারিতা",
    "exampleEn": "His benevolence won the hearts of the poor people.",
    "exampleBn": "তাঁর দয়ালুতা দরিদ্র মানুষের মন জয় করেছিল।",
    "synonyms": ["kindness", "generosity", "altruism"],
    "antonyms": ["malevolence", "cruelty"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 228
  },
  {
    "word": "Complacent",
    "phonetic": "/kəmˈpleɪsnt/ (কমপ্লেসেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "আত্মসন্তুষ্ট, অতিরিক্ত নিশ্চিন্ত",
    "exampleEn": "We cannot afford to become complacent about safety.",
    "exampleBn": "নিরাপত্তার বিষয়ে আমাদের অতিরিক্ত নিশ্চিন্ত বা আত্মসন্তুষ্ট হওয়া চলবে না।",
    "synonyms": ["self-satisfied", "content", "smug"],
    "antonyms": ["dissatisfied", "concerned"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 229
  },
  {
    "word": "Disparate",
    "phonetic": "/ˈdɪspərət/ (ডিসপ্যারেট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সম্পূর্ণ ভিন্ন, অসদৃশ",
    "exampleEn": "The team members brought disparate skills to the project.",
    "exampleBn": "টিমের সদস্যরা প্রকল্পে সম্পূর্ণ ভিন্ন ভিন্ন দক্ষতা নিয়ে এসেছিল।",
    "synonyms": ["dissimilar", "diverse", "distinct"],
    "antonyms": ["similar", "homogeneous"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 230
  },
  {
    "word": "Exacerbate",
    "phonetic": "/ɪɡˈzæsəbeɪt/ (ইগজাসারবেইট)",
    "partOfSpeech": "Verb",
    "meaningBn": "পরিস্থিতি আরও খারাপ করা, তীব্রতর করা",
    "exampleEn": "His harsh words only served to exacerbate the situation.",
    "exampleBn": "তার কঠোর বাক্যগুলো পরিস্থিতিকে আরও খারাপ করার কাজই করেছিল।",
    "synonyms": ["worsen", "aggravate", "intensify"],
    "antonyms": ["alleviate", "soothe"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 231
  },
  {
    "word": "Flamboyant",
    "phonetic": "/flæmˈbɔɪənt/ (ফ্ল্যামবয়্যান্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "ঝাঁকজমকপূর্ণ, জাঁকালো",
    "exampleEn": "The performer was known for his flamboyant costumes.",
    "exampleBn": "শিল্পী তাঁর জাঁকালো পোশাকের জন্য সুপরিচিত ছিলেন।",
    "synonyms": ["showy", "ostentatious", "vibrant"],
    "antonyms": ["modest", "restrained"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 232
  },
  {
    "word": "Gregariousness",
    "phonetic": "/ɡrɪˈɡeəriəsnəs/ (গ্রিগ্যারিয়াসনেস)",
    "partOfSpeech": "Noun",
    "meaningBn": "সংঘপ্রিয়তা, সামাজিকতা",
    "exampleEn": "Her gregariousness made her popular in college.",
    "exampleBn": "তাঁর সামাজিকতা বা মিশুক স্বভাব তাঁকে কলেজে জনপ্রিয় করে তুলেছিল।",
    "synonyms": ["sociability", "friendliness"],
    "antonyms": ["introversion", "solitude"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 233
  },
  {
    "word": "Hypocrisy",
    "phonetic": "/hɪˈpɒkrəsi/ (হিপোক্রিসি)",
    "partOfSpeech": "Noun",
    "meaningBn": "ভণ্ডামি, কাপট্য",
    "exampleEn": "He expressed disgust at the hypocrisy of political leaders.",
    "exampleBn": "তিনি রাজনৈতিক নেতাদের ভণ্ডামির প্রতি ঘৃণা প্রকাশ করেছিলেন।",
    "synonyms": ["insincerity", "deceit", "duplicity"],
    "antonyms": ["sincerity", "honesty"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 234
  },
  {
    "word": "Inevitable",
    "phonetic": "/ɪnˈevɪtəbl/ (ইনএভিটেবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অনিবার্য, যা এড়ানো অসম্ভব",
    "exampleEn": "Change is an inevitable part of life.",
    "exampleBn": "পরিবর্তন জীবনের একটি অনিবার্য অংশ।",
    "synonyms": ["unavoidable", "certain", "inescapable"],
    "antonyms": ["avoidable", "uncertain"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 235
  },
  {
    "word": "Jeopardize",
    "phonetic": "/ˈdʒepədaɪz/ (জেপারডাইজ)",
    "partOfSpeech": "Verb",
    "meaningBn": "বিপন্ন করা, ঝুঁকির মুখে ফেলা",
    "exampleEn": "Do not jeopardize your health for quick financial gain.",
    "exampleBn": "দ্রুত আর্থিক লাভের জন্য আপনার স্বাস্থ্যকে ঝুঁকির মুখে ফেলবেন না।",
    "synonyms": ["endanger", "imperil", "risk"],
    "antonyms": ["protect", "safeguard"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 236
  },
  {
    "word": "Latent",
    "phonetic": "/ˈleɪtnt/ (লেইটেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সুপ্ত, লুকায়িত",
    "exampleEn": "The test revealed his latent mathematical abilities.",
    "exampleBn": "পরীক্ষায় তার সুপ্ত গাণিতিক ক্ষমতা প্রকাশ পেয়েছে।",
    "synonyms": ["hidden", "dormant", "concealed"],
    "antonyms": ["active", "manifest"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 237
  },
  {
    "word": "Meticulous",
    "phonetic": "/məˈtɪkjələs/ (মেটিকিউলাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "খুঁতখুঁতে, অত্যন্ত সতর্ক ও নিখুঁত",
    "exampleEn": "She paid meticulous attention to every detail of the plan.",
    "exampleBn": "তিনি পরিকল্পনার প্রতিটি খুঁটিনাটি বিষয়ে অত্যন্ত সতর্ক নজর দিয়েছিলেন।",
    "synonyms": ["scrupulous", "painstaking", "thorough"],
    "antonyms": ["careless", "sloppy"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 238
  },
  {
    "word": "Nonchalant",
    "phonetic": "/ˌnɒnʃələnt/ (ননশাল্যান্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "উদাসীন, নির্ভাবনাপ্রবণ",
    "exampleEn": "He gave a nonchalant shrug when asked about the delay.",
    "exampleBn": "দেরির কারণ জিজ্ঞাসা করা হলে তিনি নির্ভাবনায় কাঁধ ঝাঁকিয়েছিলেন।",
    "synonyms": ["casual", "indifferent", "unconcerned"],
    "antonyms": ["anxious", "concerned"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 239
  },
  {
    "word": "Obstinate",
    "phonetic": "/ˈɒbstɪnət/ (অবস্টিনেট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "একগুঁয়ে, জেদি",
    "exampleEn": "He was too obstinate to admit his mistake.",
    "exampleBn": "নিজের ভুল স্বীকার করার পক্ষে তিনি অতিরিক্ত একগুঁয়ে ছিলেন।",
    "synonyms": ["stubborn", "headstrong", "unyielding"],
    "antonyms": ["flexible", "pliant"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 240
  },
  {
    "word": "Perseverance",
    "phonetic": "/ˌpɜːsɪˈvɪərəns/ (পারসিভিয়ারেন্স)",
    "partOfSpeech": "Noun",
    "meaningBn": "অধ্যবসায়, সুদৃঢ় চেষ্টা",
    "exampleEn": "Success requires hard work and perseverance.",
    "exampleBn": "সাফল্যের জন্য কঠোর পরিশ্রম ও অধ্যবসায় প্রয়োজন।",
    "synonyms": ["persistence", "tenacity", "dedication"],
    "antonyms": ["apathy", "giving up"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 241
  },
  {
    "word": "Quench",
    "phonetic": "/kwentʃ/ (কোয়েন্চ)",
    "partOfSpeech": "Verb",
    "meaningBn": "তৃষ্ণা নিবারণ করা, নিভানো",
    "exampleEn": "Cold water is best to quench your thirst.",
    "exampleBn": "তৃষ্ণা নিবারণের জন্য ঠান্ডা পানি সবচেয়ে ভালো।",
    "synonyms": ["satisfy", "extinguish", "slake"],
    "antonyms": ["ignite", "intensify"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 242
  },
  {
    "word": "Reluctant",
    "phonetic": "/rɪˈlʌktənt/ (রিলাকট্যান্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "अनिচ্ছুক, বিমুখ",
    "exampleEn": "He was reluctant to leave his hometown.",
    "exampleBn": "তিনি নিজের শহর ছেড়ে যেতে অনিচ্ছুক ছিলেন।",
    "synonyms": ["unwilling", "hesitant", "loath"],
    "antonyms": ["eager", "willing"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 243
  },
  {
    "word": "Scrutinize",
    "phonetic": "/ˈskruːtənaɪz/ (স্ক্রুটিনাইজ)",
    "partOfSpeech": "Verb",
    "meaningBn": "খুঁটিয়ে পরীক্ষা করা",
    "exampleEn": "The auditors will scrutinize all financial documents.",
    "exampleBn": "নিরীক্ষকেরা সব আর্থিক নথি গভীরভাবে বা খুঁটিয়ে পরীক্ষা করবেন।",
    "synonyms": ["inspect", "examine", "analyze"],
    "antonyms": ["ignore", "overlook"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 244
  },
  {
    "word": "Trepidation",
    "phonetic": "/ˌtrepɪˈdeɪʃn/ (ট্রেপিডেশন)",
    "partOfSpeech": "Noun",
    "meaningBn": "ভীতি, কম্পন বা উদ্বেগ",
    "exampleEn": "She entered the interview room with great trepidation.",
    "exampleBn": "তিনি তীব্র ভীতি ও উদ্বেগ নিয়ে ভাইভা কক্ষে প্রবেশ করেছিলেন।",
    "synonyms": ["apprehension", "fear", "dread"],
    "antonyms": ["calmness", "confidence"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 245
  },
  {
    "word": "Unprecedented",
    "phonetic": "/ʌnˈpresɪdentɪd/ (আনপ্রিসিডেন্টেড)",
    "partOfSpeech": "Adjective",
    "meaningBn": "নজিরবিহীন, অভূতপূর্ব",
    "exampleEn": "The city experienced an unprecedented rainfall this year.",
    "exampleBn": "শহরটি এ বছর নজিরবিহীন বৃষ্টির সম্মুখীন হয়েছে।",
    "synonyms": ["unmatched", "unparalleled", "extraordinary"],
    "antonyms": ["common", "usual"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 246
  },
  {
    "word": "Vindicate",
    "phonetic": "/ˈvɪndɪkeɪt/ (ভিনডিকেইট)",
    "partOfSpeech": "Verb",
    "meaningBn": "নির্দোষ প্রমাণ করা, সত্যতা প্রমাণ করা",
    "exampleEn": "The new evidence helped to vindicate the accused man.",
    "exampleBn": "নতুন প্রমাণগুলো অভিযুক্ত ব্যক্তিকে নির্দোষ প্রমাণ করতে সাহায্য করেছিল।",
    "synonyms": ["exonerate", "absolve", "justify"],
    "antonyms": ["condemn", "convict"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 247
  },
  {
    "word": "Waver",
    "phonetic": "/ˈweɪvər/ (ওয়েভার)",
    "partOfSpeech": "Verb",
    "meaningBn": "দ্বিধাগ্রস্ত হওয়া, টলমল করা",
    "exampleEn": "His commitment to the cause never wavered.",
    "exampleBn": "উদ্দেশ্যের প্রতি তার প্রতিশ্রুতি কখনোই টলমল করেনি।",
    "synonyms": ["hesitate", "falter", "fluctuate"],
    "antonyms": ["remain firm", "stay steadfast"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 248
  },
  {
    "word": "Yieldingness",
    "phonetic": "/ˈjiːldɪŋnəs/ (যিল্ডিংনেস)",
    "partOfSpeech": "Noun",
    "meaningBn": "নমনীয়তা, বাধ্যতা",
    "exampleEn": "Her yieldingness made her easy to work with.",
    "exampleBn": "তাঁর নমনীয়তা তাঁর সাথে কাজ করা সহজ করে তুলেছিল।",
    "synonyms": ["compliance", "submission", "flexibility"],
    "antonyms": ["stubbornness", "rigidity"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 249
  },
  {
    "word": "Zeal",
    "phonetic": "/ziːl/ (জীল)",
    "partOfSpeech": "Noun",
    "meaningBn": "প্রবল আগ্রহ, তীব্র উৎসাহ",
    "exampleEn": "She approached her new role with great zeal.",
    "exampleBn": "তিনি দারুণ উৎসাহ নিয়ে তার নতুন দায়িত্ব পালন শুরু করেছিলেন।",
    "synonyms": ["passion", "enthusiasm", "ardor"],
    "antonyms": ["apathy", "indifference"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_5",
    "frequencyRank": 250
  },
  {
    "word": "Adversity",
    "phonetic": "/ədˈvɜːsəti/ (এডভার্সিটি)",
    "partOfSpeech": "Noun",
    "meaningBn": "দুর্দশা, প্রতিকূলতা, বিপত্তি",
    "exampleEn": "A true friend stands by you in times of adversity.",
    "exampleBn": "প্রতিকূলতার সময়ে প্রকৃত বন্ধু পাশে দাঁড়ায়।",
    "synonyms": ["hardship", "misfortune", "distress"],
    "antonyms": ["prosperity", "good fortune"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 251
  },
  {
    "word": "Belligerent",
    "phonetic": "/bəˈlɪdʒərənt/ (বেলিজারেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "যুদ্ধংদেহী, ঝগড়াটে",
    "exampleEn": "His belligerent attitude made it difficult to negotiate.",
    "exampleBn": "তার যুদ্ধংদেহী মনোভাবের কারণে আলোচনা করা কঠিন হয়ে পড়েছিল।",
    "synonyms": ["hostile", "aggressive", "combative"],
    "antonyms": ["peaceful", "friendly"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 252
  },
  {
    "word": "Coalesce",
    "phonetic": "/ˌkəʊəˈles/ (কোয়ালেস)",
    "partOfSpeech": "Verb",
    "meaningBn": "একত্রিত হওয়া, মিলেমিশে এক হওয়া",
    "exampleEn": "The small groups coalesced to form a strong political party.",
    "exampleBn": "ছোট ছোট দলগুলো একত্রিত হয়ে একটি শক্তিশালী রাজনৈতিক দল গঠন করেছিল।",
    "synonyms": ["merge", "unite", "fuse"],
    "antonyms": ["separate", "divide"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 253
  },
  {
    "word": "Deterrent",
    "phonetic": "/dɪˈterənt/ (ডিটেরেন্ট)",
    "partOfSpeech": "Noun / Adjective",
    "meaningBn": "প্রতিবন্ধক, নিবারক (যা অপরাধ প্রতিরোধ করে)",
    "exampleEn": "Strict punishment serves as a deterrent to crime.",
    "exampleBn": "কঠোর শাস্তি অপরাধের বিরুদ্ধে একটি নিবারক বা প্রতিবন্ধক হিসেবে কাজ করে।",
    "synonyms": ["discouragement", "obstacle", "check"],
    "antonyms": ["encouragement", "incentive"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 254
  },
  {
    "word": "Ephemeral",
    "phonetic": "/ɪˈfemərəl/ (ইফেমারাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "ক্ষণস্থায়ী, স্বল্পস্থায়ী",
    "exampleEn": "Fame in the digital age is often ephemeral.",
    "exampleBn": "ডিজিটাল যুগে খ্যাতি প্রায়শই ক্ষণস্থায়ী হয়।",
    "synonyms": ["transient", "fleeting", "short-lived"],
    "antonyms": ["permanent", "eternal"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 255
  },
  {
    "word": "Fostering",
    "phonetic": "/ˈfɒstərɪŋ/ (ফস্টারিং)",
    "partOfSpeech": "Noun / Verb",
    "meaningBn": "লালন-পালন করা, উৎসাহিত করা বা লালন করা",
    "exampleEn": "The organization is dedicated to fostering innovation.",
    "exampleBn": "প্রতিষ্ঠানটি উদ্ভাবনকে উৎসাহিত করতে বা লালন করতে নিবেদিত।",
    "synonyms": ["nurturing", "encouraging", "promoting"],
    "antonyms": ["suppressing", "discouraging"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 256
  },
  {
    "word": "Gratuitous",
    "phonetic": "/ɡrəˈtjuːɪtəs/ (গ্র্যাচুইটাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অহেতুক, বিনামূল্যে বা অকারণ",
    "exampleEn": "The movie was criticized for its gratuitous violence.",
    "exampleBn": "ছবিটি অহেতুক সহিংসতার কারণে সমালোচিত হয়েছিল।",
    "synonyms": ["unwarranted", "unnecessary", "free"],
    "antonyms": ["justified", "necessary"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 257
  },
  {
    "word": "Harmonious",
    "phonetic": "/hɑːˈməʊniəs/ (হারমোনিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সামঞ্জস্যপূর্ণ, সুসংগত, শান্তিপূর্ণ",
    "exampleEn": "They worked together in a harmonious atmosphere.",
    "exampleBn": "তারা একটি সামঞ্জস্যপূর্ণ বা শান্তিপূর্ণ পরিবেশে একসাথে কাজ করেছিল।",
    "synonyms": ["congruous", "peaceful", "cordial"],
    "antonyms": ["discordant", "hostile"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 258
  },
  {
    "word": "Impede",
    "phonetic": "/ɪmˈpiːd/ (ইম্পীড)",
    "partOfSpeech": "Verb",
    "meaningBn": "বাধা সৃষ্টি করা, শ্লথ করা",
    "exampleEn": "Heavy traffic can impede the progress of ambulances.",
    "exampleBn": "ভারী ট্রাফিক অ্যাম্বুলেন্সের চলাচলে বাধা সৃষ্টি করতে পারে।",
    "synonyms": ["hinder", "obstruct", "hamper"],
    "antonyms": ["facilitate", "assist"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 259
  },
  {
    "word": "Jeopardy",
    "phonetic": "/ˈdʒepədi/ (জেপারডি)",
    "partOfSpeech": "Noun",
    "meaningBn": "ঝুঁকি, বিপদ",
    "exampleEn": "His rash decision put the entire operation in jeopardy.",
    "exampleBn": "তার ফুসকুড়ি সিদ্ধান্ত পুরো অপারেশনকে ঝুঁকির মুখে ফেলে দিয়েছিল।",
    "synonyms": ["danger", "peril", "risk"],
    "antonyms": ["safety", "security"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 260
  },
  {
    "word": "Kindle",
    "phonetic": "/ˈkɪndl/ (কিন্ডল)",
    "partOfSpeech": "Verb",
    "meaningBn": "প্রজ্জ্বলিত করা, উৎসাহ বা উদ্দীপনা জাগানো",
    "exampleEn": "The teacher managed to kindle a love for reading in her students.",
    "exampleBn": "শিক্ষক তার ছাত্রদের মনে পড়ার প্রতি ভালোবাসা জাগিয়ে তুলতে পেরেছিলেন।",
    "synonyms": ["ignite", "arouse", "spark"],
    "antonyms": ["extinguish", "dampen"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 261
  },
  {
    "word": "Laudable",
    "phonetic": "/ˈlɔːdəbl/ (লডেবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "প্রশংসনীয়, প্রশংসার যোগ্য",
    "exampleEn": "His efforts to help the poor are truly laudable.",
    "exampleBn": "দরিদ্রদের সাহায্য করার জন্য তার প্রচেষ্টা সত্যিই প্রশংসনীয়।",
    "synonyms": ["praiseworthy", "commendable", "admirable"],
    "antonyms": ["blameworthy", "despicable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 262
  },
  {
    "word": "Munificent",
    "phonetic": "/mjuːˈnɪfɪsnt/ (মিউনিফিসেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অত্যন্ত উদার, দানশীল",
    "exampleEn": "The museum received a munificent donation from an anonymous donor.",
    "exampleBn": "জাদুঘরটি একজন অজ্ঞাত দাতার কাছ থেকে একটি অত্যন্ত উদার অনুদান পেয়েছে।",
    "synonyms": ["generous", "bountiful", "magnanimous"],
    "antonyms": ["stingy", "miserly"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 263
  },
  {
    "word": "Negligent",
    "phonetic": "/ˈneɡlɪdʒənt/ (নেগলিজেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অসাবধান, দায়িত্বজ্ঞানহীন, গাফিলতিপূর্ণ",
    "exampleEn": "The company was found negligent in maintaining safety standards.",
    "exampleBn": "নিরাপত্তা মান বজায় রাখতে কোম্পানিটি গাফিলতিপূর্ণ প্রমাণিত হয়েছে।",
    "synonyms": ["careless", "remiss", "heedless"],
    "antonyms": ["careful", "attentive"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 264
  },
  {
    "word": "Ostentatious",
    "phonetic": "/ˌɒstenˈteɪʃəs/ (ওস্টেনটেশাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "আড়ম্বরপূর্ণ, লোকদেখানো",
    "exampleEn": "They avoid ostentatious displays of wealth.",
    "exampleBn": "তারা সম্পদের লোকদেখানো প্রদর্শন এড়িয়ে চলে।",
    "synonyms": ["showy", "flamboyant", "pretentious"],
    "antonyms": ["modest", "unpretentious"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 265
  },
  {
    "word": "Plausible",
    "phonetic": "/ˈplɔːzəbl/ (প্লজিবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বিশ্বাসযোগ্য, যুক্তিযুক্ত মনে হয় এমন",
    "exampleEn": "She provided a plausible explanation for her absence.",
    "exampleBn": "তিনি তার অনুপস্থিতির একটি বিশ্বাসযোগ্য ব্যাখ্যা দিয়েছিলেন।",
    "synonyms": ["credible", "believable", "reasonable"],
    "antonyms": ["implausible", "unbelievable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 266
  },
  {
    "word": "Quell",
    "phonetic": "/kwel/ (কুয়েল)",
    "partOfSpeech": "Verb",
    "meaningBn": "দমন করা, শান্ত করা",
    "exampleEn": "Police were called to quell the protest.",
    "exampleBn": "বিক্ষোভ দমন করতে পুলিশকে ডাকা হয়েছিল।",
    "synonyms": ["suppress", "extinguish", "calm"],
    "antonyms": ["incite", "provoke"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 267
  },
  {
    "word": "Resilient",
    "phonetic": "/rɪˈzɪliənt/ (রিজিলিয়েন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সহজে কাটিয়ে উঠতে সক্ষম, স্থিতিস্থাপক",
    "exampleEn": "Local communities proved to be resilient after the earthquake.",
    "exampleBn": "ভূমিকম্পের পর স্থানীয় সম্প্রদায়গুলো বেশ স্থিতিস্থাপক বা ঘুরে দাঁড়াতে সক্ষম বলে প্রমাণিত হয়েছিল।",
    "synonyms": ["tough", "adaptable", "flexible"],
    "antonyms": ["fragile", "vulnerable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 268
  },
  {
    "word": "Spurious",
    "phonetic": "/ˈspjʊəriəs/ (স্পিউরিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "ভুয়া, নকল, কৃত্রিম",
    "exampleEn": "The politician made spurious claims about his opponent.",
    "exampleBn": "রাজনীতিবিদ তার বিরোধীর বিরুদ্ধে ভূয়া বা মিথ্যা দাবি করেছিলেন।",
    "synonyms": ["fake", "false", "counterfeit"],
    "antonyms": ["genuine", "authentic"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 269
  },
  {
    "word": "Transient",
    "phonetic": "/ˈtrænziənt/ (ট্রানজিয়েন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অস্থায়ী, ক্ষণস্থায়ী",
    "exampleEn": "The rain was transient, and the sun soon returned.",
    "exampleBn": "বৃষ্টি ক্ষণস্থায়ী ছিল এবং শীঘ্রই সূর্য আবার দেখা দিয়েছিল।",
    "synonyms": ["temporary", "ephemeral", "fleeting"],
    "antonyms": ["permanent", "lasting"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 270
  },
  {
    "word": "Unanimous",
    "phonetic": "/juːˈnænɪমəs/ (ইউন্যানিমাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সর্বসম্মত, একমত",
    "exampleEn": "The committee reached a unanimous decision.",
    "exampleBn": "কমিটি একটি সর্বসম্মত সিদ্ধান্তে পৌঁছেছিল।",
    "synonyms": ["agreed", "united", "in accord"],
    "antonyms": ["divided", "split"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 271
  },
  {
    "word": "Vehement",
    "phonetic": "/ˈviːəmənt/ (ভিহিমেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "প্রবল, তীব্র, আবেগপূর্ণ",
    "exampleEn": "There was vehement opposition to the proposed law.",
    "exampleBn": "প্রস্তাবিত আইনের বিরুদ্ধে তীব্র বিরোধিতা ছিল।",
    "synonyms": ["passionate", "intense", "forceful"],
    "antonyms": ["mild", "apathetic"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 272
  },
  {
    "word": "Withhold",
    "phonetic": "/wɪðˈhəʊld/ (উইথহোল্ড)",
    "partOfSpeech": "Verb",
    "meaningBn": "আটকে রাখা, দিতে অস্বীকৃতি জানানো",
    "exampleEn": "The government chose to withhold critical information.",
    "exampleBn": "সরকার গুরুত্বপূর্ণ তথ্য আটকে রাখার সিদ্ধান্ত নিয়েছিল।",
    "synonyms": ["retain", "reserve", "suppress"],
    "antonyms": ["release", "grant"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 273
  },
  {
    "word": "Xenophobic",
    "phonetic": "/ˌzenəˈfəʊbɪk/ (জেনোফোবিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বিদেশি বা বহিরাগতদের প্রতি বিদ্বেষপূর্ণ",
    "exampleEn": "He condemned the xenophobic remarks made during the debate.",
    "exampleBn": "বিতর্কের সময় করা বিদেশি-বিদ্বেষপূর্ণ মন্তব্যের তিনি নিন্দা করেছিলেন।",
    "synonyms": ["prejudiced", "intolerant", "chauvinistic"],
    "antonyms": ["welcoming", "accepting"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 274
  },
  {
    "word": "Yielded",
    "phonetic": "/ˈjiːldɪd/ (যিল্ডেড)",
    "partOfSpeech": "Verb (Past)",
    "meaningBn": "উৎপাদন করেছিল, নতি স্বীকার করেছিল",
    "exampleEn": "The investigation yielded crucial new evidence.",
    "exampleBn": "তদন্তে গুরুত্বপূর্ণ নতুন প্রমাণ পাওয়া গিয়েছিল।",
    "synonyms": ["produced", "generated", "surrendered"],
    "antonyms": ["resisted", "withstood"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 275
  },
  {
    "word": "Zealotry",
    "phonetic": "/ˈzelətri/ (জে্লট্রি)",
    "partOfSpeech": "Noun",
    "meaningBn": "উগ্র অন্ধবিশ্বাস, কট্টরপন্থা",
    "exampleEn": "Religious zealotry can lead to social conflicts.",
    "exampleBn": "ধর্মীয় কট্টরপন্থা সামাজিক সংঘাতের দিকে নিয়ে যেতে পারে।",
    "synonyms": ["fanaticism", "extremism", "bigotry"],
    "antonyms": ["moderation", "tolerance"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 276
  },
  {
    "word": "Acquiesce",
    "phonetic": "/ˌækwiˈes/ (অ্যাকুয়েস)",
    "partOfSpeech": "Verb",
    "meaningBn": "মেনে নেওয়া, বিনা প্রতিবাদে সম্মতি দেওয়া",
    "exampleEn": "He decided to acquiesce to his parents' demands.",
    "exampleBn": "তিনি তার মা-বাবার দাবিতে বিনা প্রতিবাদে সম্মতি দেওয়ার সিদ্ধান্ত নিয়েছিলেন।",
    "synonyms": ["comply", "concede", "assent"],
    "antonyms": ["resist", "forbid"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 277
  },
  {
    "word": "Banal",
    "phonetic": "/bəˈnɑːl/ (বানাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "তুচ্ছ, অতিসাধারণ, সাধারণ ও আকর্ষণহীন",
    "exampleEn": "He made a few banal remarks about the weather.",
    "exampleBn": "তিনি আবহাওয়া নিয়ে কয়েকটি সাধারণ ও তুচ্ছ মন্তব্য করেছিলেন।",
    "synonyms": ["trite", "commonplace", "hackneyed"],
    "antonyms": ["original", "fresh"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 278
  },
  {
    "word": "Capricious",
    "phonetic": "/kəˈprɪʃəs/ (ক্যাপ্রিশাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "খেয়ালি, পরিবর্তনশীল",
    "exampleEn": "The weather in spring can be very capricious.",
    "exampleBn": "বসন্তের আবহাওয়া খুবই পরিবর্তনশীল হতে পারে।",
    "synonyms": ["unpredictable", "fickle", "whimsical"],
    "antonyms": ["predictable", "stable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 279
  },
  {
    "word": "Disseminate",
    "phonetic": "/dɪˈsemɪneɪt/ (ডিসেমিনেট)",
    "partOfSpeech": "Verb",
    "meaningBn": "ছড়িয়ে দেওয়া, প্রচার করা",
    "exampleEn": "The internet is used to disseminate information quickly.",
    "exampleBn": "দ্রুত তথ্য প্রচার করার জন্য ইন্টারনেট ব্যবহার করা হয়।",
    "synonyms": ["broadcast", "spread", "distribute"],
    "antonyms": ["suppress", "gather"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 280
  },
  {
    "word": "Equivocal",
    "phonetic": "/ɪˈkwɪvəkl/ (ইকুইভোক্যাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "দ্ব্যর্থবোধক, সন্দেহজনক, অস্পষ্ট",
    "exampleEn": "His answer was equivocal, leaving us confused.",
    "exampleBn": "তার উত্তরটি অস্পষ্ট ছিল, যা আমাদের বিভ্রান্ত করে রেখেছিল।",
    "synonyms": ["ambiguous", "unclear", "doubtful"],
    "antonyms": ["clear", "unequivocal"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 281
  },
  {
    "word": "Formidable",
    "phonetic": "/ˈfɔːmɪdəbl/ (ফরমিডেবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "দুর্ধর্ষ, ভীতিপ্রদ, কঠিন",
    "exampleEn": "The team faces a formidable opponent in the final.",
    "exampleBn": "ফাইনালে দলটি এক দুর্ধর্ষ প্রতিপক্ষের মুখোমুখি হচ্ছে।",
    "synonyms": ["intimidating", "daunting", "impressive"],
    "antonyms": ["weak", "easy"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 282
  },
  {
    "word": "Garrulous",
    "phonetic": "/ˈɡærələs/ (গ্যারুলাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বাচাল, বাচাল প্রকৃতির, বেশি কথা বলা",
    "exampleEn": "The garrulous old man talked for hours.",
    "exampleBn": "বাচাল বৃদ্ধ লোকটি ঘণ্টার পর ঘণ্টা কথা বলেছিলেন।",
    "synonyms": ["talkative", "loquacious", "chatty"],
    "antonyms": ["taciturn", "silent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 283
  },
  {
    "word": "Haughty",
    "phonetic": "/ˈhɔːti/ (হটি)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অহংকারী, দাম্ভিক",
    "exampleEn": "Her haughty behavior alienated her colleagues.",
    "exampleBn": "তার অহংকারী আচরণ তার সহকর্মীদের দূরে ঠেলে দিয়েছিল।",
    "synonyms": ["arrogant", "proud", "conceited"],
    "antonyms": ["humble", "modest"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 284
  },
  {
    "word": "Indefatigable",
    "phonetic": "/ˌɪndɪˈfætɪɡəbl/ (ইনডিফ্যাটিগেবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অশ্রান্ত, অক্লান্ত",
    "exampleEn": "She is an indefatigable campaigner for social justice.",
    "exampleBn": "তিনি সামাজিক বিচারের জন্য একজন অক্লান্ত আন্দোলনকারী।",
    "synonyms": ["untiring", "tireless", "relentless"],
    "antonyms": ["weary", "easily tired"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 285
  },
  {
    "word": "Jovial",
    "phonetic": "/ˈdʒəʊviəl/ (জোভিয়াল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "হাসিখুশি, প্রফুল্ল",
    "exampleEn": "He was in a jovial mood throughout the party.",
    "exampleBn": "পুরো পার্টি জুড়েই তিনি প্রফুল্ল বা হাসিখুশি মেজাজে ছিলেন।",
    "synonyms": ["cheerful", "jolly", "mirthful"],
    "antonyms": ["gloomy", "miserable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 286
  },
  {
    "word": "Keenness",
    "phonetic": "/ˈkiːnnəs/ (কীননেস)",
    "partOfSpeech": "Noun",
    "meaningBn": "তীব্রতা, প্রখরতা, আগ্রহ",
    "exampleEn": "His keenness to learn impressed the interviewer.",
    "exampleBn": "শেখার প্রতি তার তীব্র আগ্রহ সাক্ষাৎকার গ্রহণকারীকে প্রভাবিত করেছিল।",
    "synonyms": ["eagerness", "sharpness", "enthusiasm"],
    "antonyms": ["apathy", "indifference"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 287
  },
  {
    "word": "Loquacious",
    "phonetic": "/ləˈkweɪʃəs/ (লোকুয়েশাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বাচাল, মুখর",
    "exampleEn": "The loquacious host kept the audience entertained.",
    "exampleBn": "মুখর বা বাচাল উপস্থাপক দর্শকদের আনন্দে রেখেছিলেন।",
    "synonyms": ["talkative", "garrulous", "voluble"],
    "antonyms": ["quiet", "reserved"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 288
  },
  {
    "word": "Magnanimous",
    "phonetic": "/mæɡˈnænɪməs/ (ম্যাগন্যানিমাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "মহানুভাব, মহৎ হৃদয়",
    "exampleEn": "He was magnanimous in victory and praised his opponents.",
    "exampleBn": "তিনি বিজয়ে মহানুভাব ছিলেন এবং তার বিরোধীদের প্রশংসা করেছিলেন।",
    "synonyms": ["generous", "noble", "forgiving"],
    "antonyms": ["petty", "mean"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 289
  },
  {
    "word": "Nefarious",
    "phonetic": "/nɪˈfeəriəs/ (নেফেয়ারিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "কুখ্যাত, দুষ্কৃতকারী, অত্যন্ত অসৎ",
    "exampleEn": "The police uncovered a nefarious scheme to steal money.",
    "exampleBn": "পুলিশ টাকা চুরির একটি কুখ্যাত ষড়যন্ত্র উন্মোচন করেছিল।",
    "synonyms": ["wicked", "evil", "villainous"],
    "antonyms": ["noble", "virtuous"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 290
  },
  {
    "word": "Ominous",
    "phonetic": "/ˈɒmɪnəs/ (ওমিনাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অশুভ, অমঙ্গলসূচক",
    "exampleEn": "There were ominous dark clouds in the sky.",
    "exampleBn": "আকাশে অশুভ কালো মেঘ ছেয়ে ছিল।",
    "synonyms": ["threatening", "foreboding", "inauspicious"],
    "antonyms": ["promising", "auspicious"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 291
  },
  {
    "word": "Precocious",
    "phonetic": "/prɪˈkəʊʃəs/ (প্রিকেশাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অকালপক্ব, বয়সের তুলনায় বেশি বুদ্ধিমান",
    "exampleEn": "She was a precocious child who learned to read at age three.",
    "exampleBn": "তিনি একজন অকালপক্ব শিশু ছিলেন যিনি তিন বছর বয়সে পড়তে শিখেছিলেন।",
    "synonyms": ["advanced", "gifted", "talented"],
    "antonyms": ["backward", "slow-developing"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 292
  },
  {
    "word": "Quotidian",
    "phonetic": "/kwəˈtɪdiən/ (কোয়াটিডিয়ান)",
    "partOfSpeech": "Adjective",
    "meaningBn": "দৈনন্দিন, নিত্যদিনের, মামুলি",
    "exampleEn": "He enjoys writing about the quotidian events of life.",
    "exampleBn": "তিনি জীবনের দৈনন্দিন ঘটনাগুলো নিয়ে লিখতে পছন্দ করেন।",
    "synonyms": ["daily", "ordinary", "routine"],
    "antonyms": ["unusual", "extraordinary"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 293
  },
  {
    "word": "Reticent",
    "phonetic": "/ˈretɪsnt/ (রেটিসেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "স্বল্পভাষী, চুপচাপ",
    "exampleEn": "She was reticent about discussing her private life.",
    "exampleBn": "তিনি তার ব্যক্তিগত জীবন নিয়ে আলোচনা করার ক্ষেত্রে স্বল্পভাষী ছিলেন।",
    "synonyms": ["reserved", "uncommunicative", "quiet"],
    "antonyms": ["talkative", "garrulous"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 294
  },
  {
    "word": "Surreptitious",
    "phonetic": "/ˌsʌrəpˈtɪʃəs/ (সারেপটিশাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "গুপ্ত, গোপনে করা",
    "exampleEn": "She took a surreptitious glance at her watch.",
    "exampleBn": "তিনি গোপনে তার ঘড়ির দিকে এক নজর তাকিয়েছিলেন।",
    "synonyms": ["secretive", "stealthy", "clandestine"],
    "antonyms": ["open", "overt"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 295
  },
  {
    "word": "Taciturn",
    "phonetic": "/ˈtæsɪtɜːn/ (ট্যাসিটার্ন)",
    "partOfSpeech": "Adjective",
    "meaningBn": "স্বল্পভাষী, গম্ভীর বা কম কথা বলে এমন",
    "exampleEn": "He was a taciturn man who rarely spoke unless spoken to.",
    "exampleBn": "তিনি একজন স্বল্পভাষী মানুষ ছিলেন যিনি কথা না বললে খুব কমই কথা বলতেন।",
    "synonyms": ["reserved", "uncommunicative", "silent"],
    "antonyms": ["garrulous", "loquacious"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 296
  },
  {
    "word": "Unassailable",
    "phonetic": "/ˌʌnəˈseɪləbl/ (আনঅ্যাসেইলেবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অভেদ্য, যা খণ্ডন করা যায় না",
    "exampleEn": "Their legal team built an unassailable case.",
    "exampleBn": "তাদের আইনি দল একটি খণ্ডনঅযোগ্য বা অভেদ্য মামলা তৈরি করেছিল।",
    "synonyms": ["indisputable", "invulnerable", "unbeatable"],
    "antonyms": ["vulnerable", "defenseless"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 297
  },
  {
    "word": "Vociferous",
    "phonetic": "/vəˈsɪfərəs/ (ভোসিফারাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "কোলাহলপূর্ণ, সোচ্চার",
    "exampleEn": "He was a vociferous critic of the new economic policy.",
    "exampleBn": "তিনি নতুন অর্থনৈতিক নীতির একজন সোচ্চার সমালোচক ছিলেন।",
    "synonyms": ["vehement", "loud", "outspoken"],
    "antonyms": ["quiet", "silent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 298
  },
  {
    "word": "Whimsically",
    "phonetic": "/ˈwɪmzɪkli/ (উইমজিক্যালি)",
    "partOfSpeech": "Adverb",
    "meaningBn": "খেয়ালিভাবে, অদ্ভুত ভঙ্গিতে",
    "exampleEn": "The room was whimsically decorated with bright colors.",
    "exampleBn": "ঘরটি উজ্জ্বল রং দিয়ে অদ্ভুত ও দারুণ ভঙ্গিতে সাজানো হয়েছিল।",
    "synonyms": ["fancifully", "playfully"],
    "antonyms": ["seriously", "solemnly"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 299
  },
  {
    "word": "Zenithal",
    "phonetic": "/ˈzenɪθəl/ (জেনিথাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "শীর্ষবিন্দু সংক্রান্ত, সর্বোচ্চ চূড়ার",
    "exampleEn": "The sun reached its zenithal position at noon.",
    "exampleBn": "দুপুরে সূর্য তার সর্বোচ্চ শীর্ষবিন্দুতে পৌঁছেছিল।",
    "synonyms": ["highest", "peak", "climactic"],
    "antonyms": ["lowest", "bottom"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_6",
    "frequencyRank": 300
  }
]
