# coding=utf-8

words_p1 = [
  {
    "word": "Pragmatic",
    "phonetic": "/præɡˈmætɪk/ (প্র্যাগম্যাটিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বাস্তবসম্মত বা প্রয়োগমুখী",
    "exampleEn": "We need a pragmatic solution to solve this issue quickly.",
    "exampleBn": "এই সমস্যাটি দ্রুত সমাধান করার জন্য আমাদের একটি বাস্তবসম্মত সমাধান দরকার।",
    "synonyms": ["practical", "realistic", "sensible"],
    "antonyms": ["impractical", "idealistic"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 1
  },
  {
    "word": "Meticulous",
    "phonetic": "/məˈtɪkjələs/ (মেটিকিউলাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "খুঁটিনাটি বিষয়ে অত্যন্ত সতর্ক বা নিখুঁত",
    "exampleEn": "The research required meticulous attention to detail.",
    "exampleBn": "গবেষণাটিতে প্রতিটি খুঁটিনাটি বিষয়ে অত্যন্ত সতর্ক নজর দেওয়ার প্রয়োজন ছিল।",
    "synonyms": ["precise", "thorough", "scrupulous"],
    "antonyms": ["careless", "negligent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 2
  },
  {
    "word": "Candor",
    "phonetic": "/ˈkændər/ (ক্যান্ডর)",
    "partOfSpeech": "Noun",
    "meaningBn": "স্পষ্টবাদিতা, কাপট্যহীনতা বা সততা",
    "exampleEn": "The official spoke with great candor about the project's failure.",
    "exampleBn": "কর্মকর্তা প্রকল্পের ব্যর্থতা নিয়ে অত্যন্ত স্পষ্টবাদিতার সাথে কথা বলেছেন।",
    "synonyms": ["honesty", "frankness", "openness"],
    "antonyms": ["deceit", "insincerity"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 3
  },
  {
    "word": "Mitigate",
    "phonetic": "/ˈmɪtɪɡeɪt/ (মিটিগেট)",
    "partOfSpeech": "Verb",
    "meaningBn": "কমানো, তীব্রতা বা ক্ষয়ক্ষতি হ্রাস করা",
    "exampleEn": "Steps were taken to mitigate the damage caused by the flood.",
    "exampleBn": "বন্যার ক্ষয়ক্ষতি হ্রাস করার জন্য নানা পদক্ষেপ নেওয়া হয়েছিল।",
    "synonyms": ["alleviate", "reduce", "diminish"],
    "antonyms": ["aggravate", "intensify"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 4
  },
  {
    "word": "Resilient",
    "phonetic": "/rɪˈzɪliənt/ (রেজিলিয়েন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "স্থিতিস্থাপক, দ্রুত প্রতিকূলতা থেকে ঘুরে দাঁড়াতে সক্ষম",
    "exampleEn": "The community remained resilient despite facing multiple disasters.",
    "exampleBn": "একাধিক দুর্যোগের মুখোমুখি হওয়া সত্ত্বেও সম্প্রদায়টি দ্রুত ঘুরে দাঁড়াতে সক্ষম ছিল।",
    "synonyms": ["adaptable", "tough", "robust"],
    "antonyms": ["vulnerable", "fragile"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 5
  },
  {
    "word": "Ambiguous",
    "phonetic": "/æmˈbɪɡjuəs/ (অ্যামবিগুয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "দ্ব্যর্থবোধক, অস্পষ্ট বা যার একাধিক অর্থ হতে পারে",
    "exampleEn": "The contract contained several ambiguous clauses.",
    "exampleBn": "চুক্তিটিতে কয়েকটি অস্পষ্ট ধারা ছিল।",
    "synonyms": ["vague", "unclear", "equivocal"],
    "antonyms": ["clear", "explicit"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 6
  },
  {
    "word": "Benevolent",
    "phonetic": "/bəˈnevələnt/ (বেনেভোলেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "দয়ালু, পরোপকারী বা হিতৈষী",
    "exampleEn": "A benevolent donor funded the building of the new hospital.",
    "exampleBn": "একজন পরোপকারী দাতা নতুন হাসপাতাল নির্মাণের অর্থায়ন করেছেন।",
    "synonyms": ["charitable", "kind", "generous"],
    "antonyms": ["malevolent", "cruel"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 7
  },
  {
    "word": "Ephemeral",
    "phonetic": "/ɪˈfemərəl/ (ইফেমেরাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "ক্ষণস্থায়ী, অল্প সময় টিকে থাকে এমন",
    "exampleEn": "Fame in the digital age is often ephemeral.",
    "exampleBn": "ডিজিটাল যুগে খ্যাতি প্রায়ই ক্ষণস্থায়ী হয়।",
    "synonyms": ["transitory", "short-lived", "fleeting"],
    "antonyms": ["permanent", "eternal"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 8
  },
  {
    "word": "Fastidious",
    "phonetic": "/fæˈstɪdiəs/ (ফাস্টিডিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "খুঁতখুঁতে, সহজে যাকে সন্তুষ্ট করা যায় না",
    "exampleEn": "He is fastidious about his personal hygiene.",
    "exampleBn": "তিনি তাঁর ব্যক্তিগত পরিচ্ছন্নতার বিষয়ে অত্যন্ত খুঁতখুঁতে।",
    "synonyms": ["fussy", "demanding", "particular"],
    "antonyms": ["easygoing", "careless"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 9
  },
  {
    "word": "Gregarious",
    "phonetic": "/ɡrɪˈɡeəriəs/ (গ্রিগেরিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "মিশুক, সংঘপ্রিয় বা দলবদ্ধ হয়ে থাকতে পছন্দ করে এমন",
    "exampleEn": "She is a gregarious person who enjoys hosting large parties.",
    "exampleBn": "তিনি একজন মিশুক মানুষ যিনি বড় পার্টির আয়োজন করতে পছন্দ করেন।",
    "synonyms": ["sociable", "outgoing", "friendly"],
    "antonyms": ["introverted", "solitary"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 10
  },
  {
    "word": "Impeccable",
    "phonetic": "/ɪmˈpekəbl/ (ইমপেকেবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "ত্রুটিহীন, নিখুঁত বা নিষ্পাপ",
    "exampleEn": "Her English pronunciation is impeccable.",
    "exampleBn": "তাঁর ইংরেজি উচ্চারণ একদম ত্রুটিহীন।",
    "synonyms": ["flawless", "faultless", "perfect"],
    "antonyms": ["flawed", "defective"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 11
  },
  {
    "word": "Lethargic",
    "phonetic": "/ləˈθɑːdʒɪk/ (লেথারজিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "আলস, নিস্তেজ বা উদ্যমহীন",
    "exampleEn": "Hot weather always makes me feel lethargic.",
    "exampleBn": "গরম আবহাওয়া আমাকে সবসময় নিস্তেজ অনুভব করায়।",
    "synonyms": ["sluggish", "apathetic", "lazy"],
    "antonyms": ["energetic", "active"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 12
  },
  {
    "word": "Nostalgia",
    "phonetic": "/nɒˈstældʒə/ (নস্টালজিয়া)",
    "partOfSpeech": "Noun",
    "meaningBn": "গৃহকাতরতা, অতীতের স্মৃতিবেদনা",
    "exampleEn": "Old photographs always evoke a sense of nostalgia.",
    "exampleBn": "পুরোনো ছবিগুলো সবসময় অতীতের স্মৃতিবেদনাকে জাগিয়ে তোলে।",
    "synonyms": ["reminiscence", "longing", "wistfulness"],
    "antonyms": ["indifference"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 13
  },
  {
    "word": "Ominous",
    "phonetic": "/ˈɒmɪnəs/ (ওমিনাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অশুভ, অমঙ্গলসূচক",
    "exampleEn": "The dark clouds in the sky looked ominous.",
    "exampleBn": "আকাশের কালো মেঘগুলো অশুভ দেখাচ্ছিল।",
    "synonyms": ["threatening", "menacing", "foreboding"],
    "antonyms": ["promising", "auspicious"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 14
  },
  {
    "word": "Plausible",
    "phonetic": "/ˈplɔːzəbl/ (প্লজিবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বিশ্বাসযোগ্য, আপাতদৃষ্টিতে সত্য মনে হয় এমন",
    "exampleEn": "She provided a plausible explanation for her absence.",
    "exampleBn": "সে তার অনুপস্থিতির একটি বিশ্বাসযোগ্য ব্যাখ্যা দিয়েছিল।",
    "synonyms": ["credible", "believable", "reasonable"],
    "antonyms": ["implausible", "unbelievable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 15
  },
  {
    "word": "Redundant",
    "phonetic": "/rɪˈdʌndənt/ (রিডানড্যান্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অতিরিক্ত, অপ্রয়োজনীয় বা উদ্বৃত্ত",
    "exampleEn": "The last paragraph of the essay is redundant.",
    "exampleBn": "প্রবন্ধের শেষ প্যারাগ্রাফটি অপ্রয়োজনীয়।",
    "synonyms": ["superfluous", "unnecessary", "excess"],
    "antonyms": ["essential", "necessary"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 16
  },
  {
    "word": "Scrutinize",
    "phonetic": "/ˈskruːtənaɪz/ (স্ক্রুটিনাইজ)",
    "partOfSpeech": "Verb",
    "meaningBn": "সূক্ষ্মভাবে পরীক্ষা করা বা খুঁটিয়ে দেখা",
    "exampleEn": "The committee will scrutinize all the documents carefully.",
    "exampleBn": "কমিটি সব নথি সতর্কতার সাথে সূক্ষ্মভাবে পরীক্ষা করবে।",
    "synonyms": ["inspect", "examine", "analyze"],
    "antonyms": ["ignore", "overlook"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 17
  },
  {
    "word": "Treacherous",
    "phonetic": "/ˈtretʃərəs/ (ট্রেচারাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বিশ্বাসঘাতক বা বিপজ্জনক",
    "exampleEn": "The mountain pass was icy and treacherous.",
    "exampleBn": "পাহাড়ি পথটি বরফাবৃত এবং বিপজ্জনক ছিল।",
    "synonyms": ["perilous", "hazardous", "disloyal"],
    "antonyms": ["safe", "loyal"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 18
  },
  {
    "word": "Ubiquitous",
    "phonetic": "/juːˈbɪkwɪtəs/ (ইউবিকুইটাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সর্বব্যাপী, যা সব জায়গায় একযোগে উপস্থিত",
    "exampleEn": "Smartphones have become ubiquitous in modern society.",
    "exampleBn": "আধুনিক সমাজে স্মার্টফোন সর্বব্যাপী হয়ে উঠেছে।",
    "synonyms": ["omnipresent", "pervasive", "universal"],
    "antonyms": ["rare", "scarce"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 19
  },
  {
    "word": "Vindicate",
    "phonetic": "/ˈvɪndɪkeɪt/ (ভিনডিকেট)",
    "partOfSpeech": "Verb",
    "meaningBn": "দোষমুক্ত করা, সত্যতা বা নির্দোষিতা প্রমাণ করা",
    "exampleEn": "New evidence emerged to vindicate the accused man.",
    "exampleBn": "অভিযুক্ত ব্যক্তিকে দোষমুক্ত করার জন্য নতুন প্রমাণ সামনে এসেছে।",
    "synonyms": ["exonerate", "acquit", "justify"],
    "antonyms": ["condemn", "blame"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 20
  },
  {
    "word": "Adversity",
    "phonetic": "/ədˈvɜːsəti/ (এডভারসিটি)",
    "partOfSpeech": "Noun",
    "meaningBn": "প্রতিকূলতা, দুর্বিপাক বা দুর্ভাগ্য",
    "exampleEn": "He showed great courage in the face of adversity.",
    "exampleBn": "প্রতিকূলতার মুখে তিনি দারুণ সাহস দেখিয়েছিলেন।",
    "synonyms": ["hardship", "misfortune", "distress"],
    "antonyms": ["prosperity", "fortune"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 21
  },
  {
    "word": "Bolster",
    "phonetic": "/ˈbəʊlstər/ (বোলস্টার)",
    "partOfSpeech": "Verb",
    "meaningBn": "শক্তিশালী করা, সমর্থন বা জোরদার করা",
    "exampleEn": "The extra training helped bolster his confidence.",
    "exampleBn": "অতিরিক্ত প্রশিক্ষণ তার আত্মবিশ্বাসকে জোরদার করতে সাহায্য করেছে।",
    "synonyms": ["strengthen", "reinforce", "boost"],
    "antonyms": ["weaken", "undermine"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 22
  },
  {
    "word": "Coercion",
    "phonetic": "/kəʊˈɜːʃn/ (কোয়ারশন)",
    "partOfSpeech": "Noun",
    "meaningBn": "জোরজুলুম, বলপ্রয়োগ বা বাধ্যকরণ",
    "exampleEn": "He signed the confession under coercion.",
    "exampleBn": "তিনি বলপ্রয়োগের মুখে স্বীকারোক্তিতে স্বাক্ষর করেছিলেন।",
    "synonyms": ["compulsion", "force", "duress"],
    "antonyms": ["persuasion", "freewill"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 23
  },
  {
    "word": "Diligent",
    "phonetic": "/ˈdɪlɪdʒənt/ (ডিলিজেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "পরিশ্রমী, অধ্যবসায়ী",
    "exampleEn": "She is a diligent student who always completes her work on time.",
    "exampleBn": "তিনি একজন পরিশ্রমী ছাত্রী যিনি সবসময় সময়মতো তার কাজ শেষ করেন।",
    "synonyms": ["hardworking", "industrious", "assiduous"],
    "antonyms": ["lazy", "negligent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 24
  },
  {
    "word": "Elusive",
    "phonetic": "/ɪˈluːsɪv/ (ইলুসিভ)",
    "partOfSpeech": "Adjective",
    "meaningBn": "ধরাছোঁয়ার বাইরে, যা সহজে পাওয়া বা বোঝা যায় না",
    "exampleEn": "Success remained elusive despite his best efforts.",
    "exampleBn": "তার সর্বোচ্চ চেষ্টা সত্ত্বেও সাফল্য অধরাই থেকে গেছে।",
    "synonyms": ["evasive", "slippery", "indefinable"],
    "antonyms": ["accessible", "attainable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 25
  },
  {
    "word": "Frugal",
    "phonetic": "/ˈfruːɡl/ (ফ্রুগাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "মিতব্যয়ী, হিসেবি",
    "exampleEn": "They lived a frugal life to save money for higher education.",
    "exampleBn": "উচ্চশিক্ষার জন্য টাকা বাঁচাতে তারা মিতব্যয়ী জীবনযাপন করত।",
    "synonyms": ["thrifty", "economical", "sparing"],
    "antonyms": ["extravagant", "wasteful"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 26
  },
  {
    "word": "Gullible",
    "phonetic": "/ˈɡʌləbl/ (গালিবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অতিসহজবিশ্বাসী, যাকে সহজে প্রতারিত করা যায়",
    "exampleEn": "He is so gullible that he believes almost anything you tell him.",
    "exampleBn": "সে এতটাই অতিসহজবিশ্বাসী যে তাকে আপনি যাই বলুন না কেন সে তা বিশ্বাস করে।",
    "synonyms": ["naive", "credulous", "trusting"],
    "antonyms": ["skeptical", "suspicious"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 27
  },
  {
    "word": "Hypocrisy",
    "phonetic": "/hɪˈpɒkrəsi/ (হিপোক্রিসি)",
    "partOfSpeech": "Noun",
    "meaningBn": "ভণ্ডামি, কপটতা",
    "exampleEn": "His advice was criticized as sheer hypocrisy.",
    "exampleBn": "তার উপদেশকে খাঁটি ভণ্ডামি বলে সমালোচনা করা হয়েছিল।",
    "synonyms": ["insincerity", "duplicity", "deceit"],
    "antonyms": ["sincerity", "honesty"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 28
  },
  {
    "word": "Implicit",
    "phonetic": "/ɪmˈplɪsɪt/ (ইমপ্লিসিট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অন্তর্নিহিত, পরোক্ষ বা না বলেই বুঝিয়ে দেওয়া হয় এমন",
    "exampleEn": "There was an implicit agreement between the two nations.",
    "exampleBn": "দুই দেশের মধ্যে একটি পরোক্ষ চুক্তি ছিল।",
    "synonyms": ["tacit", "implied", "unspoken"],
    "antonyms": ["explicit", "direct"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 29
  },
  {
    "word": "Juxtapose",
    "phonetic": "/ˌdʒʌkstəˈpəʊz/ (জাক্সটাপোজ)",
    "partOfSpeech": "Verb",
    "meaningBn": "তুলনা করার জন্য পাশাপাশি রাখা",
    "exampleEn": "The museum juxtaposed modern art with classical sculptures.",
    "exampleBn": "জাদুঘরটি আধুনিক শিল্পকে ক্লাসিক্যাল ভাস্কর্যের পাশে রেখে তুলনা করেছিল।",
    "synonyms": ["collocate", "compare", "side-by-side"],
    "antonyms": ["separate", "isolate"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 30
  },
  {
    "word": "Kinetic",
    "phonetic": "/kɪˈnetɪk/ (কাইনেটিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "গতিশীল, গতির সাথে সম্পর্কিত",
    "exampleEn": "Wind energy is converted into kinetic energy to generate electricity.",
    "exampleBn": "বিদ্যুৎ উৎপাদনের জন্য বায়ু শক্তিকে গতিশক্তিতে রূপান্তর করা হয়।",
    "synonyms": ["active", "dynamic", "moving"],
    "antonyms": ["static", "motionless"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 31
  },
  {
    "word": "Lucid",
    "phonetic": "/ˈluːsɪd/ (লুসিড)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সহজবোধ্য, স্পষ্ট বা পরিষ্কার",
    "exampleEn": "The professor gave a lucid explanation of a complex topic.",
    "exampleBn": "অধ্যাপক একটি জটিল বিষয়ের সহজবোধ্য ব্যাখ্যা দিয়েছেন।",
    "synonyms": ["clear", "comprehensible", "transparent"],
    "antonyms": ["confusing", "obscure"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 32
  },
  {
    "word": "Mandatory",
    "phonetic": "/ˈmændətəri/ (ম্যান্ডেটরি)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বাধ্যতামূলক, আইনত আবশ্যক",
    "exampleEn": "Wearing a helmet is mandatory for motorbikers.",
    "exampleBn": "মোটরবাইক চালকদের জন্য হেলমেট পরা বাধ্যতামূলক।",
    "synonyms": ["compulsory", "obligatory", "required"],
    "antonyms": ["optional", "voluntary"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 33
  },
  {
    "word": "Notorious",
    "phonetic": "/nəʊˈtɔːriəs/ (নটোরিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "কুখ্যাত, খারাপ কাজে পরিচিত",
    "exampleEn": "The river is notorious for its dangerous currents.",
    "exampleBn": "নদীটি বিপজ্জনক স্রোতের জন্য কুখ্যাত।",
    "synonyms": ["infamous", "disreputable"],
    "antonyms": ["famous", "reputable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 34
  },
  {
    "word": "Oblivious",
    "phonetic": "/əˈblɪviəs/ (অব্লিভিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অসচেতন, খেয়াল রাখে না এমন",
    "exampleEn": "He absorbed himself in the book, oblivious to his surroundings.",
    "exampleBn": "তিনি নিজের চারপাশ সম্পর্কে অসচেতন হয়ে বইয়ে মগ্ন ছিলেন।",
    "synonyms": ["unaware", "unmindful", "ignorant"],
    "antonyms": ["aware", "conscious"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 35
  },
  {
    "word": "Paradox",
    "phonetic": "/ˈpærədɒks/ (প্যারাডক্স)",
    "partOfSpeech": "Noun",
    "meaningBn": "আপাতবিরোধী কথা, যা সত্য হলেও দেখতে বিপরীত মনে হয়",
    "exampleEn": "It is a paradox that exercising gives you more energy.",
    "exampleBn": "এটি একটি আপাতবিরোধী কথা যে ব্যায়াম করলে আপনার শক্তি আরও বাড়ে।",
    "synonyms": ["contradiction", "anomaly", "puzzle"],
    "antonyms": ["norm", "certainty"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 36
  },
  {
    "word": "Quench",
    "phonetic": "/kwentʃ/ (কোয়েন্চ)",
    "partOfSpeech": "Verb",
    "meaningBn": "পিপাসা মেটানো, আগুন নেভানো",
    "exampleEn": "A glass of cold water quenched his thirst.",
    "exampleBn": "এক গ্লাস ঠান্ডা পানি তার তৃষ্ণা মিটিয়েছিল।",
    "synonyms": ["satisfy", "extinguish", "slake"],
    "antonyms": ["ignite", "intensify"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 37
  },
  {
    "word": "Reluctant",
    "phonetic": "/rɪˈlʌktənt/ (রিল্যাকট্যান্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অনিচ্ছুক, নারাজ",
    "exampleEn": "He was reluctant to share his personal information.",
    "exampleBn": "তিনি তাঁর ব্যক্তিগত তথ্য শেয়ার করতে অনিচ্ছুক ছিলেন।",
    "synonyms": ["unwilling", "hesitant", "loath"],
    "antonyms": ["eager", "willing"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 38
  },
  {
    "word": "Subtle",
    "phonetic": "/ˈsʌtl/ (সাবটল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সূক্ষ্ম, যা সহজে চোখে পড়ে না বা বোঝা যায় না",
    "exampleEn": "There is a subtle difference between the two colors.",
    "exampleBn": "দুটি রঙের মধ্যে একটি সূক্ষ্ম পার্থক্য রয়েছে।",
    "synonyms": ["delicate", "understated", "nuanced"],
    "antonyms": ["obvious", "harsh"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 39
  },
  {
    "word": "Tactful",
    "phonetic": "/ˈtæktfl/ (ট্যাক্টফুল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "কৌশলী, বিচক্ষণ বা রুচিশীল",
    "exampleEn": "She gave a tactful answer to avoid offending anyone.",
    "exampleBn": "কাউকে আঘাত না করার জন্য সে একটি কৌশলী উত্তর দিয়েছিল।",
    "synonyms": ["diplomatic", "discreet", "considerate"],
    "antonyms": ["tactless", "rude"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 40
  },
  {
    "word": "Unprecedented",
    "phonetic": "/ʌnˈpresɪdentɪd/ (আনপ্রেসিডেন্টেড)",
    "partOfSpeech": "Adjective",
    "meaningBn": "নজিরবিহীন, অতীতে কখনো ঘটেনি এমন",
    "exampleEn": "The country is facing an unprecedented economic crisis.",
    "exampleBn": "দেশটি একটি নজিরবিহীন অর্থনৈতিক সংকটের মুখোমুখি।",
    "synonyms": ["unmatched", "unparalleled", "extraordinary"],
    "antonyms": ["precedented", "common"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 41
  },
  {
    "word": "Versatile",
    "phonetic": "/ˈvɜːsətaɪl/ (ভার্সাটাইল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বহুমুখী প্রতিভাধর বা নানা কাজে ব্যবহারযোগ্য",
    "exampleEn": "He is a versatile actor who can play any role.",
    "exampleBn": "তিনি একজন বহুমুখী অভিনেতা যিনি যেকোনো চরিত্রে অভিনয় করতে পারেন।",
    "synonyms": ["adaptable", "flexible", "all-round"],
    "antonyms": ["inflexible", "limited"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 42
  },
  {
    "word": "Wary",
    "phonetic": "/ˈweəri/ (ওয়ারি)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সতর্ক, হুশিয়ার",
    "exampleEn": "Be wary of strangers asking for money online.",
    "exampleBn": "অনলাইনে টাকা চাওয়া অপরিচিতদের বিষয়ে সতর্ক থাকুন।",
    "synonyms": ["cautious", "alert", "prudent"],
    "antonyms": ["careless", "trusting"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 43
  },
  {
    "word": "Yield",
    "phonetic": "/jiːld/ (হিল্ড)",
    "partOfSpeech": "Verb",
    "meaningBn": "উৎপাদন করা, নতি স্বীকার করা বা মেনে নেওয়া",
    "exampleEn": "The farm yields a high quality of wheat every year.",
    "exampleBn": "খামারটি প্রতি বছর উচ্চমানের গম উৎপাদন করে।",
    "synonyms": ["produce", "surrender", "generate"],
    "antonyms": ["resist", "withstand"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 44
  },
  {
    "word": "Zealous",
    "phonetic": "/ˈzeləs/ (জেলাছ)",
    "partOfSpeech": "Adjective",
    "meaningBn": "প্রবল আগ্রহান্বিত, অতি-উৎসাহী",
    "exampleEn": "He is a zealous supporter of environmental protection.",
    "exampleBn": "তিনি পরিবেশ সুরক্ষার একজন প্রবল উৎসাহী সমর্থক।",
    "synonyms": ["enthusiastic", "passionate", "ardent"],
    "antonyms": ["apathetic", "indifferent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 45
  },
  {
    "word": "Apathy",
    "phonetic": "/ˈæpəθi/ (অ্যাপাথি)",
    "partOfSpeech": "Noun",
    "meaningBn": "অনিচ্ছা, উদাসীনতা",
    "exampleEn": "Voter apathy is a serious concern for modern democracies.",
    "exampleBn": "ভোটারদের উদাসীনতা আধুনিক গণতন্ত্রের জন্য একটি গুরুতর উদ্বেগের বিষয়।",
    "synonyms": ["indifference", "unconcern", "lethargy"],
    "antonyms": ["enthusiasm", "passion"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 46
  },
  {
    "word": "Candid",
    "phonetic": "/ˈkændɪd/ (ক্যান্ডিড)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অকপট, সরল বা সোজা কথা বলে এমন",
    "exampleEn": "He gave a candid response to the interviewer's question.",
    "exampleBn": "তিনি সাক্ষাৎকারগ্রহীতার প্রশ্নের একটি অকপট উত্তর দিয়েছেন।",
    "synonyms": ["honest", "direct", "straightforward"],
    "antonyms": ["secretive", "guarded"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 47
  },
  {
    "word": "Deviate",
    "phonetic": "/ˈdiːvieɪt/ (ডিভিয়েট)",
    "partOfSpeech": "Verb",
    "meaningBn": "পথচ্যুত হওয়া, মূল বিষয় থেকে সরে যাওয়া",
    "exampleEn": "Do not deviate from the original plan.",
    "exampleBn": "মূল পরিকল্পনা থেকে সরে যাবেন না।",
    "synonyms": ["diverge", "stray", "veer"],
    "antonyms": ["conform", "continue"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 48
  },
  {
    "word": "Enhance",
    "phonetic": "/ɪnˈhɑːns/ (এনহ্যান্স)",
    "partOfSpeech": "Verb",
    "meaningBn": "বৃদ্ধি করা, মান উন্নত করা",
    "exampleEn": "Regular exercise can enhance your quality of life.",
    "exampleBn": "নিয়মিত ব্যায়াম আপনার জীবনযাত্রার মান উন্নত করতে পারে।",
    "synonyms": ["improve", "boost", "augment"],
    "antonyms": ["degrade", "diminish"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 49
  },
  {
    "word": "Feasible",
    "phonetic": "/ˈfiːzəbl/ (ফিজিবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বাস্তবায়নযোগ্য, সম্ভবপর",
    "exampleEn": "The manager asked for a feasible business plan.",
    "exampleBn": "ম্যানেজার একটি বাস্তবায়নযোগ্য ব্যবসায়িক পরিকল্পনা চেয়েছিলেন।",
    "synonyms": ["practicable", "viable", "achievable"],
    "antonyms": ["impossible", "unfeasible"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_1",
    "frequencyRank": 50
  }
]
