# coding=utf-8

words_p3 = [
 {
    "word": "Plausible",
    "phonetic": "/ˈplɔːzəbl/ (প্লজিবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বিশ্বাসযোগ্য, যুক্তিযুক্ত",
    "exampleEn": "His explanation sounds plausible enough to be true.",
    "exampleBn": "তার ব্যাখ্যাটি সত্যি হওয়ার মতো যথেষ্ট বিশ্বাসযোগ্য মনে হচ্ছে।",
    "synonyms": ["credible", "believable", "reasonable"],
    "antonyms": ["implausible", "unbelievable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 101
  },
  {
    "word": "Quantitative",
    "phonetic": "/ˈkwɒntɪtətɪv/ (কোয়ান্টিটেটিভ)",
    "partOfSpeech": "Adjective",
    "meaningBn": "পরিমাণগত, সংখ্যাসূচক",
    "exampleEn": "The report includes both qualitative and quantitative data.",
    "exampleBn": "প্রতিবেদনটিতে গুণগত এবং পরিমাণগত উভয় ডেটাই অন্তর্ভুক্ত রয়েছে।",
    "synonyms": ["measurable", "numerical"],
    "antonyms": ["qualitative"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 102
  },
  {
    "word": "Redundant",
    "phonetic": "/rɪˈdʌndənt/ (রিডানড্যান্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অতিরিক্ত, অপ্রয়োজনীয় বা উদ্বৃত্ত",
    "exampleEn": "Using those extra words makes the sentence redundant.",
    "exampleBn": "ঐ অতিরিক্ত শব্দগুলো ব্যবহার করায় বাক্যটি অপ্রয়োজনীয় হয়ে পড়েছে।",
    "synonyms": ["superfluous", "unnecessary", "surplus"],
    "antonyms": ["essential", "necessary"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 103
  },
  {
    "word": "Substantial",
    "phonetic": "/səbˈstænʃl/ (সাবস্ট্যানশাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "উল্লেখযোগ্য, প্রচুর বা সুদৃঢ়",
    "exampleEn": "They made a substantial profit this fiscal year.",
    "exampleBn": "তারা এই অর্থবছরে একটি উল্লেখযোগ্য পরিমাণ মুনাফা করেছে।",
    "synonyms": ["considerable", "significant", "sizable"],
    "antonyms": ["slight", "insignificant"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 104
  },
  {
    "word": "Treacherous",
    "phonetic": "/ˈtretʃərəs/ (ট্রেচারাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বিশ্বাসঘাতকতামূলক, বিপজ্জনক",
    "exampleEn": "The mountain roads become treacherous during heavy rain.",
    "exampleBn": "ভারী বৃষ্টির সময় পাহাড়ি রাস্তাগুলো বিপজ্জনক হয়ে ওঠে।",
    "synonyms": ["perilous", "hazardous", "deceitful"],
    "antonyms": ["safe", "loyal"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 105
  },
  {
    "word": "Unprecedented",
    "phonetic": "/ʌnˈpresɪdentɪd/ (আনপ্রেসিডেন্টেড)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অভূতপূর্ব, যা আগে কখনো ঘটেনি",
    "exampleEn": "The economy is facing unprecedented challenges.",
    "exampleBn": "অর্থনীতি অভূতপূর্ব চ্যালেঞ্জের সম্মুখীন হচ্ছে।",
    "synonyms": ["unmatched", "unparalleled", "novel"],
    "antonyms": ["precedented", "familiar"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 106
  },
  {
    "word": "Versatile",
    "phonetic": "/ˈvɜːsətaɪl/ (ভার্সাটাইল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বহুমুখী, নানা কাজে পারদর্শী",
    "exampleEn": "He is a versatile actor who can play any role easily.",
    "exampleBn": "তিনি একজন বহুমুখী অভিনেতা যিনি যেকোনো চরিত্রে সহজেই অভিনয় করতে পারেন।",
    "synonyms": ["adaptable", "flexible", "resourceful"],
    "antonyms": ["inflexible", "limited"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 107
  },
  {
    "word": "Widespread",
    "phonetic": "/ˈwaɪdspred/ (ওয়াইডস্প্রেড)",
    "partOfSpeech": "Adjective",
    "meaningBn": "ব্যাপক, সর্বত্র বিস্তৃত",
    "exampleEn": "The news caused widespread alarm among citizens.",
    "exampleBn": "খবরটি নাগরিকদের মধ্যে ব্যাপক উদ্বেগের সৃষ্টি করেছে।",
    "synonyms": ["extensive", "pervasive", "common"],
    "antonyms": ["limited", "rare"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 108
  },
  {
    "word": "Affluent",
    "phonetic": "/ˈæfluənt/ (এফ্লুয়েন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "ধনী, বিত্তশালী বা সমৃদ্ধ",
    "exampleEn": "They live in an affluent neighborhood in the city.",
    "exampleBn": "তারা শহরের একটি বিত্তশালী এলাকায় বসবাস করে।",
    "synonyms": ["wealthy", "prosperous", "rich"],
    "antonyms": ["poor", "impoverished"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 109
  },
  {
    "word": "Benchmark",
    "phonetic": "/ˈbentʃmɑːk/ (বেঞ্চমার্ক)",
    "partOfSpeech": "Noun",
    "meaningBn": "মানদণ্ড, মাপকাঠি",
    "exampleEn": "This result sets a new benchmark for quality.",
    "exampleBn": "এই ফলাফলটি মান বা গুণগত মানের জন্য একটি নতুন মানদণ্ড তৈরি করেছে।",
    "synonyms": ["standard", "criterion", "gauge"],
    "antonyms": [],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 110
  },
  {
    "word": "Consolidate",
    "phonetic": "/kənˈsɒlɪdeɪt/ (কনসোলিডেট)",
    "partOfSpeech": "Verb",
    "meaningBn": "একত্রিত করা, সুদৃঢ় করা",
    "exampleEn": "The company plans to consolidate its smaller offices.",
    "exampleBn": "কোম্পানিটি তার ছোট অফিসগুলোকে একত্রিত করার পরিকল্পনা করছে।",
    "synonyms": ["combine", "strengthen", "merge"],
    "antonyms": ["separate", "weaken"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 111
  },
  {
    "word": "Diverse",
    "phonetic": "/daɪˈvɜːs/ (ডাইভার্স)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বৈচিত্র্যময়, নানা ধরনের",
    "exampleEn": "The country has a culturally diverse population.",
    "exampleBn": "দেশটিতে সামাজিকভাবে বা সাংস্কৃতিকভাবে বৈচিত্র্যময় জনগোষ্ঠী রয়েছে।",
    "synonyms": ["varied", "miscellaneous", "assorted"],
    "antonyms": ["similar", "uniform"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 112
  },
  {
    "word": "Enhance",
    "phonetic": "/ɪnˈhɑːns/ (ইনহ্যান্স)",
    "partOfSpeech": "Verb",
    "meaningBn": "বৃদ্ধি করা, মান উন্নত করা",
    "exampleEn": "Regular exercise can enhance your physical endurance.",
    "exampleBn": "নিয়মিত ব্যায়াম আপনার শারীরিক সহনশীলতা বৃদ্ধি করতে পারে।",
    "synonyms": ["improve", "boost", "augment"],
    "antonyms": ["reduce", "impair"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 113
  },
  {
    "word": "Fostering",
    "phonetic": "/ˈfɒstərɪŋ/ (ফস্টারিং)",
    "partOfSpeech": "Noun / Verb",
    "meaningBn": "উৎসাহিত করা, লালন-পালন করা",
    "exampleEn": "Fostering creativity is important in early education.",
    "exampleBn": "প্রাথমিক শিক্ষায় সৃজনশীলতাকে উৎসাহিত করা খুবই গুরুত্বপূর্ণ।",
    "synonyms": ["encouraging", "nurturing", "promoting"],
    "antonyms": ["discouraging", "stifling"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 114
  },
  {
    "word": "Gregarious",
    "phonetic": "/ɡrɪˈɡeəriəs/ (গ্রিগ্যারিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "মিশুক, সামাজিক",
    "exampleEn": "She is a gregarious person who loves making new friends.",
    "exampleBn": "তিনি একজন মিশুক মানুষ যিনি নতুন বন্ধু তৈরি করতে ভালোবাসেন।",
    "synonyms": ["sociable", "extroverted", "out-going"],
    "antonyms": ["reclusive", "introverted"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 115
  },
  {
    "word": "Humble",
    "phonetic": "/ˈhʌmbl/ (হাম্বল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বিনয়ী, নম্র",
    "exampleEn": "Despite his huge success, he remained humble.",
    "exampleBn": "প্রচুর সাফল্য সত্ত্বেও তিনি সবসময় বিনয়ী ছিলেন।",
    "synonyms": ["modest", "meek", "polite"],
    "antonyms": ["arrogant", "proud"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 116
  },
  {
    "word": "Implausible",
    "phonetic": "/ɪmˈplɔːzəbl/ (ইমপ্লজিবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অবিশ্বাস্য, যুক্তিহীন",
    "exampleEn": "Her excuse for being late was highly implausible.",
    "exampleBn": "দেরি করার পেছনে তার অজুহাতটি অত্যন্ত অবিশ্বাস্য ছিল।",
    "synonyms": ["unbelievable", "improbable", "doubtful"],
    "antonyms": ["plausible", "credible"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 117
  },
  {
    "word": "Juvenile",
    "phonetic": "/ˈdʒuːvənaɪl/ (জুভেনাইল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "কিশোর, অপ্রাপ্তবয়স্ক",
    "exampleEn": "The government launched new centers for juvenile rehabilitation.",
    "exampleBn": "সরকার কিশোর পুনর্বাসনের জন্য নতুন কেন্দ্র চালু করেছে।",
    "synonyms": ["youthful", "adolescent", "young"],
    "antonyms": ["adult", "mature"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 118
  },
  {
    "word": "Keen",
    "phonetic": "/kiːn/ (কীন)",
    "partOfSpeech": "Adjective",
    "meaningBn": "আগ্রহী, প্রখর বা তীব্র",
    "exampleEn": "He has a keen eye for detail.",
    "exampleBn": "খুঁটিনাটি বিষয় খেয়াল করার ক্ষেত্রে তার প্রখর দৃষ্টি রয়েছে।",
    "synonyms": ["eager", "sharp", "astute"],
    "antonyms": ["dull", "indifferent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 119
  },
  {
    "word": "Lethargic",
    "phonetic": "/lɪˈθɑːdʒɪk/ (লেথারজিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "কুঁড়ে, নিস্তেজ বা অলস",
    "exampleEn": "The hot weather made everyone feel lethargic.",
    "exampleBn": "গরম আবহাওয়া সবাইকে নিস্তেজ বা অলস করে তুলেছিল।",
    "synonyms": ["sluggish", "lazy", "inactive"],
    "antonyms": ["energetic", "active"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 120
  },
  {
    "word": "Mitigate",
    "phonetic": "/ˈmɪtɪɡeɪt/ (মিটিগেট)",
    "partOfSpeech": "Verb",
    "meaningBn": "প্রশমিত করা, তীব্রতা কমানো",
    "exampleEn": "Tree planting helps mitigate the impacts of climate change.",
    "exampleBn": "বৃক্ষরোপণ জলবায়ু পরিবর্তনের প্রভাব প্রশমিত করতে সাহায্য করে।",
    "synonyms": ["alleviate", "reduce", "lessen"],
    "antonyms": ["aggravate", "intensify"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 121
  },
  {
    "word": "Nostalgic",
    "phonetic": "/nɒˈstældʒɪk/ (নস্টালজিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "স্মৃতিবেদনাতুর, অতীতের স্মৃতির প্রতি অনুরাগী",
    "exampleEn": "Listening to old songs made him feel nostalgic.",
    "exampleBn": "পুরোনো গান শোনা তাকে স্মৃতিবেদনাতুর করে তুলেছিল।",
    "synonyms": ["wistful", "sentimental", "reminiscent"],
    "antonyms": ["indifferent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 122
  },
  {
    "word": "Oblivious",
    "phonetic": "/əˈblɪviəs/ (অবলিভিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অসচেতন, বেখবর",
    "exampleEn": "He remained oblivious to the danger around him.",
    "exampleBn": "তিনি নিজের চারপাশের বিপদ সম্পর্কে অসচেতন ছিলেন।",
    "synonyms": ["unaware", "unmindful", "ignorant"],
    "antonyms": ["aware", "conscious"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 123
  },
  {
    "word": "Pragmatic",
    "phonetic": "/præɡˈmætɪk/ (প্র্যাগম্যাটিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বাস্তবসম্মত, প্রয়োগমুখী",
    "exampleEn": "We need a pragmatic approach to solve this issue.",
    "exampleBn": "এই সমস্যা সমাধানের জন্য আমাদের একটি বাস্তবসম্মত পদ্ধতি দরকার।",
    "synonyms": ["practical", "realistic", "sensible"],
    "antonyms": ["idealistic", "impractical"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 124
  },
  {
    "word": "Quench",
    "phonetic": "/kwentʃ/ (কোয়েন্চ)",
    "partOfSpeech": "Verb",
    "meaningBn": "মিটানো (তৃষ্ণা), নেভানো (আগুন)",
    "exampleEn": "A glass of cold water helped quench his thirst.",
    "exampleBn": "এক গ্লাস ঠান্ডা পানি তার তৃষ্ণা মিটাতে সাহায্য করেছিল।",
    "synonyms": ["satisfy", "extinguish", "slake"],
    "antonyms": ["ignite"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 125
  },
  {
    "word": "Resilient",
    "phonetic": "/rɪˈzɪliənt/ (রিজিলিয়েন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "স্থিতিস্থাপক, দুর্যোগ কাটিয়ে উঠতে সক্ষম",
    "exampleEn": "The community proved to be remarkably resilient after the storm.",
    "exampleBn": "ঝড়ের পর স্থানীয় সমাজটি দারুণভাবে ঘুরে দাঁড়াতে সক্ষম প্রমাণিত হয়েছিল।",
    "synonyms": ["tough", "adaptable", "flexible"],
    "antonyms": ["fragile", "vulnerable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 126
  },
  {
    "word": "Scrutinize",
    "phonetic": "/ˈskruːtənaɪz/ (স্ক্রুটিনাইজ)",
    "partOfSpeech": "Verb",
    "meaningBn": "খুঁটিয়ে পরীক্ষা করা, নিবিড়ভাবে পর্যবেক্ষণ করা",
    "exampleEn": "Auditors will scrutinize the company's financial records.",
    "exampleBn": "নিরীক্ষকেরা কোম্পানির আর্থিক রেকর্ডগুলো খুঁটিয়ে পরীক্ষা করবেন।",
    "synonyms": ["examine", "inspect", "analyze"],
    "antonyms": ["ignore", "overlook"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 127
  },
  {
    "word": "Transient",
    "phonetic": "/ˈtrænziənt/ (ট্রানজিয়েন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "ক্ষণস্থায়ী, অস্থায়ী",
    "exampleEn": "The relief provided by the drug was only transient.",
    "exampleBn": "ওষুধটির মাধ্যমে প্রাপ্ত উপশমটি কেবল ক্ষণস্থায়ী ছিল।",
    "synonyms": ["temporary", "fleeting", "ephemeral"],
    "antonyms": ["permanent", "lasting"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 128
  },
  {
    "word": "Unbiased",
    "phonetic": "/ʌnˈbaɪəst/ (আনবায়াসড)",
    "partOfSpeech": "Adjective",
    "meaningBn": "নিরপেক্ষ, পক্ষপাতহীন",
    "exampleEn": "Journalists should try to give an unbiased account of events.",
    "exampleBn": "সাংবাদিকদের উচিত ঘটনাগুলোর একটি নিরপেক্ষ বিবরণ দেওয়ার চেষ্টা করা।",
    "synonyms": ["impartial", "fair", "neutral"],
    "antonyms": ["biased", "prejudiced"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 129
  },
  {
    "word": "Vindicate",
    "phonetic": "/ˈvɪndɪkeɪt/ (ভিন্ডিকেট)",
    "partOfSpeech": "Verb",
    "meaningBn": "দোষমুক্ত করা, নির্দোষ প্রমাণ করা",
    "exampleEn": "The new evidence will vindicate him of all charges.",
    "exampleBn": "নতুন প্রমাণগুলো তাকে সমস্ত অভিযোগ থেকে নির্দোষ প্রমাণ করবে।",
    "synonyms": ["exonerate", "acquit", "justify"],
    "antonyms": ["condemn", "convict"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 130
  },
  {
    "word": "Yield",
    "phonetic": "/jiːld/ (যিল্ড)",
    "partOfSpeech": "Verb / Noun",
    "meaningBn": "উৎপাদন করা, নতিস্বীকার করা; ফলন",
    "exampleEn": "The new farming techniques produced a higher yield.",
    "exampleBn": "নতুন কৃষি পদ্ধতিটি অধিক ফলন দিয়েছে।",
    "synonyms": ["produce", "surrender", "generate"],
    "antonyms": ["resist", "withstand"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 131
  },
  {
    "word": "Zealous",
    "phonetic": "/ˈzeləs/ (জেলাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "উৎসুক, প্রবল উৎসাহী",
    "exampleEn": "The zealous volunteers worked day and night to help others.",
    "exampleBn": "প্রবল উৎসাহী সোসেবকরা অন্যদের সাহায্য করতে দিনরাত কাজ করেছিলেন।",
    "synonyms": ["enthusiastic", "passionate", "eager"],
    "antonyms": ["apathetic", "indifferent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 132
  },
  {
    "word": "Advocate",
    "phonetic": "/ˈædvəkeɪt/ (এডভোকেট)",
    "partOfSpeech": "Verb / Noun",
    "meaningBn": "পরামর্শ দেওয়া, সমর্থন করা; সমর্থক",
    "exampleEn": "Many experts advocate for a healthier lifestyle.",
    "exampleBn": "অনেক বিশেষজ্ঞ আরও স্বাস্থ্যকর জীবনধারার সমর্থন করেন।",
    "synonyms": ["support", "champion", "encourage"],
    "antonyms": ["oppose", "discourage"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 133
  },
  {
    "word": "Brevity",
    "phonetic": "/ˈbrevəti/ (ব্রেভিটি)",
    "partOfSpeech": "Noun",
    "meaningBn": "সংক্ষিপ্ততা, স্বল্পতা",
    "exampleEn": "The brevity of his speech impressed the audience.",
    "exampleBn": "তার বক্তব্যের সংক্ষিপ্ততা দর্শকদের মুগ্ধ করেছিল।",
    "synonyms": ["conciseness", "shortness", "succinctness"],
    "antonyms": ["verbosity", "lengthiness"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 134
  },
  {
    "word": "Complacent",
    "phonetic": "/kəmˈpleɪsnt/ (কমপ্লেসেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "আত্মসন্তুষ্ট, অতি-আত্মবিশ্বাসী",
    "exampleEn": "We cannot afford to become complacent about safety.",
    "exampleBn": "নিরাপত্তার বিষয়ে আমাদের আত্মসন্তুষ্ট হওয়া চলবে না।",
    "synonyms": ["self-satisfied", "smug", "contented"],
    "antonyms": ["concerned", "dissatisfied"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 135
  },
  {
    "word": "Deference",
    "phonetic": "/ˈdefərəns/ (ডেফারেন্স)",
    "partOfSpeech": "Noun",
    "meaningBn": "শ্রদ্ধা, সম্মান প্রদর্শন",
    "exampleEn": "He showed deference to his elders by listening quietly.",
    "exampleBn": "তিনি শান্তভাবে শুনে তাঁর মুরুব্বিদের প্রতি শ্রদ্ধা প্রদর্শন করেছেন।",
    "synonyms": ["respect", "reverence", "esteem"],
    "antonyms": ["disrespect", "defiance"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 136
  },
  {
    "word": "Elaborate",
    "phonetic": "/ɪˈlæbərət/ (ইলাবোরেট)",
    "partOfSpeech": "Adjective / Verb",
    "meaningBn": "বিস্তৃত, বিশদভাবে ব্যাখ্যা করা",
    "exampleEn": "Please elaborate on your plans for the new project.",
    "exampleBn": "নতুন প্রকল্পের জন্য আপনার পরিকল্পনাগুলো দয়া করে বিশদভাবে ব্যাখ্যা করুন।",
    "synonyms": ["detailed", "expand", "explain"],
    "antonyms": ["simple", "simplify"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 137
  },
  {
    "word": "Fundamental",
    "phonetic": "/ˌfʌndəˈmentl/ (ফান্ডামেন্টাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "মৌলিক, আবশ্যকীয়",
    "exampleEn": "Education is a fundamental human right.",
    "exampleBn": "শিক্ষা হলো একটি মৌলিক মানবাধিকার।",
    "synonyms": ["basic", "essential", "primary"],
    "antonyms": ["secondary", "minor"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 138
  },
  {
    "word": "Garner",
    "phonetic": "/ˈɡɑːnər/ (গার্নার)",
    "partOfSpeech": "Verb",
    "meaningBn": "সংগ্রহ করা, অর্জন করা",
    "exampleEn": "The proposal managed to garner strong public support.",
    "exampleBn": "প্রস্তাবটি জনগণের জোরালো সমর্থন সংগ্রহ করতে সক্ষম হয়েছিল।",
    "synonyms": ["gather", "collect", "accumulate"],
    "antonyms": ["disperse", "scatter"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 139
  },
  {
    "word": "Hostile",
    "phonetic": "/ˈhɒstaɪl/ (হস্টাইল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "শত্রুভাবাপন্ন, বিরোধী",
    "exampleEn": "The harsh climate creates a hostile environment for plants.",
    "exampleBn": "প্রতিকূল আবহাওয়া উদ্ভিদের জন্য একটি বিরোধী পরিবেশ তৈরি করে।",
    "synonyms": ["unfriendly", "antagonistic", "opposed"],
    "antonyms": ["friendly", "hospitable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 140
  },
  {
    "word": "Imperative",
    "phonetic": "/ɪmˈperətɪv/ (ইম্পারেটিভ)",
    "partOfSpeech": "Adjective",
    "meaningBn": "জরুরি, অত্যন্ত গুরুত্বপূর্ণ",
    "exampleEn": "It is imperative that action be taken immediately.",
    "exampleBn": "অবিলম্বে ব্যবস্থা নেওয়া অত্যন্ত জরুরি।",
    "synonyms": ["vital", "crucial", "essential"],
    "antonyms": ["optional", "unnecessary"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 141
  },
  {
    "word": "Laudable",
    "phonetic": "/ˈlɔːdəbl/ (লডেবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "প্রশংসনীয়, প্রশংসার যোগ্য",
    "exampleEn": "His charity work is truly laudable.",
    "exampleBn": "তার দাতব্য কাজ সত্যিই প্রশংসনীয়।",
    "synonyms": ["praiseworthy", "commendable", "admirable"],
    "antonyms": ["blameworthy", "deplorable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 142
  },
  {
    "word": "Meticulous",
    "phonetic": "/məˈtɪkjələs/ (মেটিকিউলাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "খুঁতখুঁতে, অত্যন্ত সতর্ক ও নিখুঁত",
    "exampleEn": "He paid meticulous attention to every single detail.",
    "exampleBn": "তিনি প্রতিটি ক্ষুদ্রাতিক্ষুদ্র বিষয়ে অত্যন্ত সতর্ক মনোযোগ দিয়েছিলেন।",
    "synonyms": ["thorough", "precise", "careful"],
    "antonyms": ["careless", "sloppy"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 143
  },
  {
    "word": "Naïve",
    "phonetic": "/naɪˈiːv/ (নাইভ)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সরল, অতি-বিশ্বাসী বা অভিজ্ঞতাশূন্য",
    "exampleEn": "It would be naïve to think the problem will solve itself.",
    "exampleBn": "সমস্যাটি নিজে থেকেই সমাধান হয়ে যাবে—এমনটা ভাবা হবে সরলতা বা বোকামি।",
    "synonyms": ["gullible", "innocent", "inexperienced"],
    "antonyms": ["shrewd", "sophisticated"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 144
  },
  {
    "word": "Optimize",
    "phonetic": "/ˈɒptɪmaɪz/ (অপটিমাইজ)",
    "partOfSpeech": "Verb",
    "meaningBn": "সর্বোত্তম ব্যবহার করা, সর্বোচ্চ কার্যকর করা",
    "exampleEn": "We must optimize our resources to increase efficiency.",
    "exampleBn": "দক্ষতা বাড়াতে আমাদের সম্পদের সর্বোত্তম ব্যবহার করতে হবে।",
    "synonyms": ["maximize", "enhance", "perfect"],
    "antonyms": ["impair", "worsen"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 145
  },
  {
    "word": "Pivotal",
    "phonetic": "/ˈpɪvətl/ (পিভোটাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "কেন্দ্রীয়, অত্যন্ত গুরুত্বপূর্ণ",
    "exampleEn": "Education plays a pivotal role in national development.",
    "exampleBn": "জাতীয় উন্নয়নে শিক্ষা একটি অত্যন্ত গুরুত্বপূর্ণ বা কেন্দ্রীয় ভূমিকা পালন করে।",
    "synonyms": ["crucial", "central", "vital"],
    "antonyms": ["minor", "unimportant"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 146
  },
  {
    "word": "Refurbish",
    "phonetic": "/ˌriːˈfɜːbɪʃ/ (রিফার্বিশ)",
    "partOfSpeech": "Verb",
    "meaningBn": "পুনর্নবীকরণ করা, মেরামত করে নতুন করা",
    "exampleEn": "The company decided to refurbish its old building.",
    "exampleBn": "কোম্পানিটি তার পুরোনো ভবনটি পুনর্নবীকরণ করার সিদ্ধান্ত নিয়েছে।",
    "synonyms": ["renovate", "restore", "revamp"],
    "antonyms": ["demolish", "destroy"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 147
  },
  {
    "word": "Subtle",
    "phonetic": "/ˈsʌtl/ (সাবটল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সূক্ষ্ম, যা সহজে ধরা পড়ে না",
    "exampleEn": "There is a subtle difference between the two colors.",
    "exampleBn": "রং দুটির মধ্যে একটি সূক্ষ্ম পার্থক্য রয়েছে।",
    "synonyms": ["delicate", "understated", "fine"],
    "antonyms": ["obvious", "harsh"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 148
  },
  {
    "word": "Tangential",
    "phonetic": "/tænˈdʒenʃl/ (ট্যানজেনশিয়াল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "আংশিক প্রাসঙ্গিক, মূল বিষয় থেকে সরে যাওয়া",
    "exampleEn": "His comment was only tangential to the main topic.",
    "exampleBn": "তার মন্তব্যটি মূল বিষয়ের সাথে কেবল আংশিক প্রাসঙ্গিক ছিল।",
    "synonyms": ["peripheral", "divergent", "digressive"],
    "antonyms": ["central", "relevant"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 149
  },
  {
    "word": "Unravel",
    "phonetic": "/ʌnˈrævl/ (আনর্যাভেল)",
    "partOfSpeech": "Verb",
    "meaningBn": "জট খোলা, রহস্য উন্মোচন করা",
    "exampleEn": "Investigators are trying to unravel the details of the incident.",
    "exampleBn": "তদন্তকারীরা ঘটনাটির পেছনের বিস্তারিত রহস্য উন্মোচন করার চেষ্টা করছেন।",
    "synonyms": ["untangle", "solve", "disentangle"],
    "antonyms": ["entangle", "complicate"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_3",
    "frequencyRank": 150
  }
]
