# coding=utf-8

words_p2 = [
  {
    "word": "Fluctuate",
    "phonetic": "/ˈflʌktʃueɪt/ (ফ্লাকচুয়েট)",
    "partOfSpeech": "Verb",
    "meaningBn": "উঠানামা করা, অস্থির থাকা",
    "exampleEn": "Prices tend to fluctuate according to supply and demand.",
    "exampleBn": "জোগান ও চাহিদার ওপর ভিত্তি করে দাম উঠানামা করে।",
    "synonyms": ["vary", "oscillate", "waver"],
    "antonyms": ["stabilize", "remain"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 51
  },
  {
    "word": "Formidable",
    "phonetic": "/ˈfɔːmɪdəbl/ (ফরমিডেবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "দুর্ধর্ষ, অত্যন্ত শক্তিশালী বা ভীতিপ্রদ",
    "exampleEn": "The team faces a formidable opponent in the finals.",
    "exampleBn": "ফাইনালে দলটি এক দুর্ধর্ষ প্রতিযোগীর মুখোমুখি হচ্ছে।",
    "synonyms": ["intimidating", "daunting", "mighty"],
    "antonyms": ["weak", "harmless"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 52
  },
  {
    "word": "Hinder",
    "phonetic": "/ˈhɪndər/ (হিন্ডার)",
    "partOfSpeech": "Verb",
    "meaningBn": "বাঁধা দেওয়া, অগ্রগতি ব্যাহত করা",
    "exampleEn": "Bad weather could hinder the rescue operations.",
    "exampleBn": "খারাপ আবহাওয়া উদ্ধারকাজ ব্যাহত করতে পারে।",
    "synonyms": ["obstruct", "impede", "hamper"],
    "antonyms": ["facilitate", "help"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 53
  },
  {
    "word": "Imminent",
    "phonetic": "/ˈɪmɪnənt/ (ইমিনেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "আসন্ন, যা খুব শিগগিরই ঘটতে যাচ্ছে",
    "exampleEn": "The dark clouds indicate that rain is imminent.",
    "exampleBn": "কালো মেঘ ইঙ্গিত দিচ্ছে যে বৃষ্টি আসন্ন।",
    "synonyms": ["impending", "approaching", "looming"],
    "antonyms": ["distant", "remote"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 54
  },
  {
    "word": "Inevitably",
    "phonetic": "/ɪnˈevɪtəbli/ (ইনেভিটেবলি)",
    "partOfSpeech": "Adverb",
    "meaningBn": "অপরিহার্যভাবে, যা এড়ানো অসম্ভব",
    "exampleEn": "Technological advancement will inevitably change how we work.",
    "exampleBn": "প্রযুক্তির অগ্রগতি অপরিহার্যভাবে আমাদের কাজের ধরন বদলে দেবে।",
    "synonyms": ["unavoidably", "certainly", "necessarily"],
    "antonyms": ["avoidably", "uncertainly"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 55
  },
  {
    "word": "Jeopardize",
    "phonetic": "/ˈdʒepədaɪz/ (জেপারডাইজ)",
    "partOfSpeech": "Verb",
    "meaningBn": "ঝুঁকির মুখে ফেলা, বিপন্ন করা",
    "exampleEn": "Careless mistakes could jeopardize the whole project.",
    "exampleBn": "অসাবধানতাবশত করা ভুল পুরো প্রকল্পটিকে ঝুঁকির মুখে ফেলতে পারে।",
    "synonyms": ["endanger", "risk", "imperil"],
    "antonyms": ["protect", "safeguard"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 56
  },
  {
    "word": "Lament",
    "phonetic": "/ləˈment/ (লামেন্ট)",
    "partOfSpeech": "Verb",
    "meaningBn": "শোক প্রকাশ করা, বিলাপ করা",
    "exampleEn": "The city lamented the loss of its historical heritage.",
    "exampleBn": "শহরটি তার ঐতিহাসিক ঐতিহ্য হারানোর জন্য শোক প্রকাশ করেছে।",
    "synonyms": ["mourn", "grieve", "deplore"],
    "antonyms": ["rejoice", "celebrate"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 57
  },
  {
    "word": "Magnitude",
    "phonetic": "/ˈmæɡnɪtjuːd/ (ম্যাগনিটিউড)",
    "partOfSpeech": "Noun",
    "meaningBn": "পরিমাণ, বিশালতা বা গুরুত্ব",
    "exampleEn": "They did not realize the magnitude of the problem at first.",
    "exampleBn": "তারা প্রথমে সমস্যাটির গুরুত্ব বা বিশালতা উপলব্ধি করতে পারেনি।",
    "synonyms": ["scale", "size", "immensity"],
    "antonyms": ["smallness", "insignificance"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 58
  },
  {
    "word": "Negligible",
    "phonetic": "/ˈneɡlɪdʒəbl/ (নেগলিজিবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "নগণ্য, তুচ্ছ বা উপেক্ষণীয়",
    "exampleEn": "The cost difference between the two options is negligible.",
    "exampleBn": "দুটি বিকল্পের মধ্যে খরচের পার্থক্য খুবই নগণ্য।",
    "synonyms": ["insignificant", "trivial", "minor"],
    "antonyms": ["significant", "substantial"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 59
  },
  {
    "word": "Obsolete",
    "phonetic": "/ˈɒbsəliːt/ (অবসোলিট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সেকেলে, অপ্রচলিত",
    "exampleEn": "Floppy disks have become obsolete in the digital era.",
    "exampleBn": "ডিজিটাল যুগে ফ্লপি ডিস্ক অপ্রচলিত হয়ে পড়েছে।",
    "synonyms": ["outdated", "archaic", "disused"],
    "antonyms": ["modern", "current"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 60
  },
  {
    "word": "Persevere",
    "phonetic": "/ˌpɜːsɪˈvɪər/ (পারসিভিয়ার)",
    "partOfSpeech": "Verb",
    "meaningBn": "অধ্যবসায় করা, একনাগাড়ে চেষ্টা করে যাওয়া",
    "exampleEn": "If you persevere, you will eventually achieve your goal.",
    "exampleBn": "আপনি যদি একনাগাড়ে চেষ্টা করে যান, তবে অবশেষে লক্ষ্য অর্জনে সফল হবেন।",
    "synonyms": ["persist", "endure", "continue"],
    "antonyms": ["quit", "surrender"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 61
  },
  {
    "word": "Relinquish",
    "phonetic": "/rɪˈlɪŋkwɪʃ/ (রিলিংকুইশ)",
    "partOfSpeech": "Verb",
    "meaningBn": "ত্যাগ করা, দাবি ছেড়ে দেওয়া",
    "exampleEn": "He was forced to relinquish his position as chairman.",
    "exampleBn": "তিনি চেয়ারম্যান পদ ত্যাগ করতে বাধ্য হয়েছিলেন।",
    "synonyms": ["surrender", "abandon", "yield"],
    "antonyms": ["retain", "keep"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 62
  },
  {
    "word": "Spontaneous",
    "phonetic": "/spɒnˈteɪniəs/ (স্পন্টেনিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "স্বতঃস্ফূর্ত, আপনা-আপনি ঘটে এমন",
    "exampleEn": "The audience broke into spontaneous applause.",
    "exampleBn": "শ্রোতারা স্বতঃস্ফূর্ত করতালিতে ফেটে পড়েছিলেন।",
    "synonyms": ["unplanned", "impromptu", "natural"],
    "antonyms": ["planned", "deliberate"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 63
  },
  {
    "word": "Tolerant",
    "phonetic": "/ˈtɒlərənt/ (টলারেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সহনশীল, সহিষ্ণু",
    "exampleEn": "A peaceful society requires people to be tolerant of different views.",
    "exampleBn": "একটি শান্তিময় সমাজের জন্য মানুষকে ভিন্ন মতের প্রতি সহনশীল হতে হয়।",
    "synonyms": ["patient", "broad-minded", "lenient"],
    "antonyms": ["intolerant", "prejudiced"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 64
  },
  {
    "word": "Unanimous",
    "phonetic": "/juːˈnænɪməs/ (ইউন্যানিমাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সর্বসম্মত, একমত",
    "exampleEn": "The committee reached a unanimous decision on the project.",
    "exampleBn": "কমিটি প্রকল্পটির বিষয়ে একটি সর্বসম্মত সিদ্ধান্তে পৌঁছেছিল।",
    "synonyms": ["united", "agreed", "undivided"],
    "antonyms": ["divided", "conflicting"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 65
  },
  {
    "word": "Vulnerable",
    "phonetic": "/ˈvʌlnərəbl/ (ভালনারেবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "ঝুঁকিপূর্ণ, সহজে আঘাতপ্রাপ্ত হতে পারে এমন",
    "exampleEn": "Elderly people are more vulnerable to severe illness.",
    "exampleBn": "বয়স্ক ব্যক্তিরা গুরুতর অসুস্থতার ক্ষেত্রে বেশি ঝুঁকিপূর্ণ।",
    "synonyms": ["exposed", "susceptible", "defenseless"],
    "antonyms": ["secure", "protected"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 66
  },
  {
    "word": "Wholesome",
    "phonetic": "/ˈhəʊlsəm/ (হোলসাম)",
    "partOfSpeech": "Adjective",
    "meaningBn": "স্বাস্থ্যকর, পুষ্টিকর বা কল্যাণকর",
    "exampleEn": "Eating wholesome food contributes to good health.",
    "exampleBn": "স্বাস্থ্যকর খাবার খাওয়া ভালো স্বাস্থ্যের ক্ষেত্রে ভূমিকা রাখে।",
    "synonyms": ["healthy", "nutritious", "beneficial"],
    "antonyms": ["unhealthy", "harmful"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 67
  },
  {
    "word": "Acquire",
    "phonetic": "/əˈkwaɪər/ (একোয়ার)",
    "partOfSpeech": "Verb",
    "meaningBn": "অর্জন করা, লাভ করা",
    "exampleEn": "Students need time to acquire new technical skills.",
    "exampleBn": "শিক্ষার্থীদের নতুন কারিগরি দক্ষতা অর্জন করতে সময় প্রয়োজন।",
    "synonyms": ["obtain", "gain", "attain"],
    "antonyms": ["lose", "forfeit"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 68
  },
  {
    "word": "Brief",
    "phonetic": "/briːf/ (ব্রিফ)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সংক্ষিপ্ত, অল্প সময়স্থায়ী",
    "exampleEn": "He gave a brief summary of the proposal.",
    "exampleBn": "তিনি প্রস্তাবনাটির একটি সংক্ষিপ্ত সারসংক্ষেপ দিয়েছেন।",
    "synonyms": ["concise", "short", "succinct"],
    "antonyms": ["lengthy", "verbose"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 69
  },
  {
    "word": "Cognitive",
    "phonetic": "/ˈkɒɡnətɪv/ (কগনিটিভ)",
    "partOfSpeech": "Adjective",
    "meaningBn": "জ্ঞানীয়, বুদ্ধি বা উপলব্ধিসংক্রান্ত",
    "exampleEn": "Puzzles are great for improving cognitive development.",
    "exampleBn": "পাজল জ্ঞানীয় বিকাশ বাড়ানোর জন্য খুব ভালো।",
    "synonyms": ["mental", "intellectual", "perceptual"],
    "antonyms": ["physical"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 70
  },
  {
    "word": "Deteriorate",
    "phonetic": "/dɪˈtɪəriəreɪt/ (ডিটেরিওরেট)",
    "partOfSpeech": "Verb",
    "meaningBn": "অবনোিত হওয়া, খারাপের দিকে যাওয়া",
    "exampleEn": "The patient's condition began to deteriorate rapidly.",
    "exampleBn": "রোগীর অবস্থার দ্রুত অবনতি হতে শুরু করেছে।",
    "synonyms": ["worsen", "decline", "degrade"],
    "antonyms": ["improve", "recover"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 71
  },
  {
    "word": "Exemplary",
    "phonetic": "/ɪɡˈzempləri/ (ইগজেমপ্লারি)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অনুকরণীয়, দৃষ্টান্তমূলক",
    "exampleEn": "The officer was rewarded for his exemplary service.",
    "exampleBn": "কর্মকর্তাটিকে তাঁর অনুকরণীয় সেবার জন্য পুরস্কৃত করা হয়েছিল।",
    "synonyms": ["model", "praiseworthy", "commendable"],
    "antonyms": ["deplorable", "unworthy"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 72
  },
  {
    "word": "Futile",
    "phonetic": "/ˈfjuːtaɪl/ (ফিউটাইল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "পণ্ড, নিরর্থক বা ব্যর্থ",
    "exampleEn": "Their attempts to restart the engine were futile.",
    "exampleBn": "ইঞ্জিনটি পুনরায় চালু করার তাদের প্রচেষ্টাগুলো ব্যর্থ হয়েছিল।",
    "synonyms": ["useless", "pointless", "vain"],
    "antonyms": ["fruitful", "effective"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 73
  },
  {
    "word": "Grasp",
    "phonetic": "/ɡrɑːsp/ (গ্রাস্প)",
    "partOfSpeech": "Verb",
    "meaningBn": "আঁকড়ে ধরা, সঠিকভাবে অনুধাবন করা",
    "exampleEn": "It took him some time to grasp the basic concepts.",
    "exampleBn": "মৌলিক বিষয়গুলো সঠিকভাবে অনুধাবন করতে তার কিছুটা সময় লেগেছিল।",
    "synonyms": ["comprehend", "understand", "clutch"],
    "antonyms": ["misunderstand", "release"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 74
  },
  {
    "word": "Harmony",
    "phonetic": "/ˈhɑːməni/ (হারমোনি)",
    "partOfSpeech": "Noun",
    "meaningBn": "সামঞ্জস্য, মেলবন্ধন বা সম্প্রীতি",
    "exampleEn": "The different communities live together in peace and harmony.",
    "exampleBn": "বিভিন্ন সম্প্রদায় শান্তি ও সম্প্রীতির সাথে একসাথে বসবাস করে।",
    "synonyms": ["concord", "unity", "agreement"],
    "antonyms": ["conflict", "discord"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 75
  },
  {
    "word": "Incredible",
    "phonetic": "/ɪnˈkredəbl/ (ইনক্রেডিবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অবিশ্বাস্য, অসাধারণ",
    "exampleEn": "The team achieved incredible success in a short time.",
    "exampleBn": "দলটি অল্প সময়ের মধ্যে অবিশ্বাস্য সাফল্য অর্জন করেছে।",
    "synonyms": ["extraordinary", "unbelievable", "amazing"],
    "antonyms": ["ordinary", "plausible"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 76
  },
  {
    "word": "Judicious",
    "phonetic": "/dʒuːˈdɪʃəs/ (জুডিশাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বিচক্ষণ, সুবিবেচক",
    "exampleEn": "We must make a judicious use of our limited resources.",
    "exampleBn": "আমাদের সীমিত সম্পদের বিচক্ষণ ব্যবহার করতে হবে।",
    "synonyms": ["wise", "prudent", "sensible"],
    "antonyms": ["foolish", "imprudent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 77
  },
  {
    "word": "Legitimate",
    "phonetic": "/lɪˈdʒɪtɪmət/ (লেজিটিমেট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বৈধ, যুক্তিযুক্ত",
    "exampleEn": "He raised a legitimate concern during the meeting.",
    "exampleBn": "তিনি মিটিংয়ের সময়ে একটি যুক্তিযুক্ত উদ্বেগ তুলে ধরেছিলেন।",
    "synonyms": ["lawful", "valid", "genuine"],
    "antonyms": ["illegal", "invalid"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 78
  },
  {
    "word": "Monumental",
    "phonetic": "/ˌmɒnjuˈmentl/ (মনুমেন্টাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বিশাল, স্মরণীয় বা যুগান্তকারী",
    "exampleEn": "Constructing the bridge was a monumental task.",
    "exampleBn": "সেতুটি নির্মাণ করা একটি বিশাল বা যুগান্তকারী কাজ ছিল।",
    "synonyms": ["massive", "historic", "gigantic"],
    "antonyms": ["tiny", "insignificant"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 79
  },
  {
    "word": "Nurture",
    "phonetic": "/ˈnɜːtʃər/ (নারচার)",
    "partOfSpeech": "Verb",
    "meaningBn": "লালন-পালন করা, লালন করা বা বিকাশ ঘটানো",
    "exampleEn": "Parents work hard to nurture their children's talents.",
    "exampleBn": "বাবা-মা তাঁদের সন্তানদের মেধার বিকাশ ঘটাতে কঠোর পরিশ্রম করেন।",
    "synonyms": ["foster", "cherish", "encourage"],
    "antonyms": ["neglect", "discourage"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 80
  },
  {
    "word": "Origin",
    "phonetic": "/ˈɒrɪdʒɪn/ (অরিজিন)",
    "partOfSpeech": "Noun",
    "meaningBn": "উৎপত্তি, উৎস",
    "exampleEn": "Scientists are researching the origin of the universe.",
    "exampleBn": "বিজ্ঞানীগণ মহাবিশ্বের উৎপত্তি নিয়ে গবেষণা করছেন।",
    "synonyms": ["source", "beginning", "root"],
    "antonyms": ["end", "outcome"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 81
  },
  {
    "word": "Prominent",
    "phonetic": "/ˈprɒmɪnənt/ (প্রমিনেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বিশিষ্ট, প্রখ্যাত বা দৃষ্টিগোচর",
    "exampleEn": "He is a prominent figure in local politics.",
    "exampleBn": "তিনি স্থানীয় রাজনীতির একজন বিশিষ্ট ব্যক্তিত্ব।",
    "synonyms": ["distinguished", "conspicuous", "famous"],
    "antonyms": ["obscure", "unknown"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 82
  },
  {
    "word": "Rational",
    "phonetic": "/ˈræʃnəl/ (রেশনাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "যুক্তিসঙ্গত, বিবেকবান",
    "exampleEn": "Try to make a rational decision instead of acting emotionally.",
    "exampleBn": "আবেগ দিয়ে কাজ না করে একটি যুক্তিসঙ্গত সিদ্ধান্ত নেওয়ার চেষ্টা করুন।",
    "synonyms": ["logical", "sensible", "reasonable"],
    "antonyms": ["irrational", "illogical"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 83
  },
  {
    "word": "Scarce",
    "phonetic": "/skeəs/ (স্কার্স)",
    "partOfSpeech": "Adjective",
    "meaningBn": "দুষ্প্রাপ্য, দুর্লভ বা অপর্যাপ্ত",
    "exampleEn": "Fresh water becomes scarce during the summer months.",
    "exampleBn": "গ্রীষ্মের মাসগুলোতে বিশুদ্ধ পানি দুষ্প্রাপ্য হয়ে পড়ে।",
    "synonyms": ["rare", "insufficient", "limited"],
    "antonyms": ["abundant", "plentiful"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 84
  },
  {
    "word": "Tangible",
    "phonetic": "/ˈtændʒəbl/ (ট্যানজিবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "স্পর্শযোগ্য, বাস্তব বা সুনির্দিষ্ট",
    "exampleEn": "The government has shown tangible progress in reducing inflation.",
    "exampleBn": "মুদ্রাস্ফীতি কমাতে সরকার বাস্তব অগ্রগতি দেখিয়েছে।",
    "synonyms": ["concrete", "palpable", "real"],
    "antonyms": ["intangible", "abstract"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 85
  },
  {
    "word": "Ultimate",
    "phonetic": "/ˈʌltɪmət/ (আল্টিমেট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "চরম, চূড়ান্ত",
    "exampleEn": "Our ultimate goal is to reach complete customer satisfaction.",
    "exampleBn": "আমাদের চূড়ান্ত লক্ষ্য হলো সম্পূর্ণ গ্রাহক সন্তুষ্টি অর্জন করা।",
    "synonyms": ["final", "concluding", "supreme"],
    "antonyms": ["initial", "first"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 86
  },
  {
    "word": "Vague",
    "phonetic": "/veɪɡ/ (ভেগ)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অস্পষ্ট, অনির্দিষ্ট",
    "exampleEn": "He gave a vague response when asked about his future plans.",
    "exampleBn": "ভবিষ্যৎ পরিকল্পনার কথা জিজ্ঞাসা করা হলে তিনি একটি অস্পষ্ট প্রতিক্রিয়া জানান।",
    "synonyms": ["indistinct", "ambiguous", "unclear"],
    "antonyms": ["precise", "clear"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 87
  },
  {
    "word": "Withstand",
    "phonetic": "/wɪðˈstænd/ (উইথস্ট্যান্ড)",
    "partOfSpeech": "Verb",
    "meaningBn": "প্রতিরোধ করা, সহ্য করা বা টিকে থাকা",
    "exampleEn": "The new building is designed to withstand strong earthquakes.",
    "exampleBn": "নতুন ভবনটি শক্তিশালী ভূমিকম্প সহ্য করার উপযোগী করে ডিজাইন করা হয়েছে।",
    "synonyms": ["resist", "endure", "bear"],
    "antonyms": ["succumb", "yield"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 88
  },
  {
    "word": "Abundant",
    "phonetic": "/əˈbʌndənt/ (এবানড্যান্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "প্রচুর, প্রভূত বা পর্যাপ্ত",
    "exampleEn": "The region is rich with abundant natural resources.",
    "exampleBn": "অঞ্চলটি প্রচুর প্রাকৃতিক সম্পদে সমৃদ্ধ।",
    "synonyms": ["plentiful", "copious", "ample"],
    "antonyms": ["scarce", "meager"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 89
  },
  {
    "word": "Briefly",
    "phonetic": "/ˈbriːfli/ (ব্রিফলি)",
    "partOfSpeech": "Adverb",
    "meaningBn": "সংক্ষেপে, অল্প সময়ের জন্য",
    "exampleEn": "She spoke briefly about the main findings of the report.",
    "exampleBn": "তিনি রিপোর্টের প্রধান ফলাফল সম্পর্কে সংক্ষেপে কথা বলেছিলেন।",
    "synonyms": ["concisely", "shortly", "fleetingly"],
    "antonyms": ["at length", "thoroughly"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 90
  },
  {
    "word": "Comprehend",
    "phonetic": "/ˌkɒmprɪˈhend/ (কমপ্রিহেন্ড)",
    "partOfSpeech": "Verb",
    "meaningBn": "উপলব্ধি করা, বুঝতে পারা",
    "exampleEn": "It was difficult to comprehend the reason behind his decision.",
    "exampleBn": "তার সিদ্ধান্তের পেছনের কারণ বোঝা কঠিন ছিল।",
    "synonyms": ["understand", "grasp", "fathom"],
    "antonyms": ["misunderstand", "miss"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 91
  },
  {
    "word": "Drastic",
    "phonetic": "/ˈdræstɪk/ (ড্রাস্টিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "চরম, কঠোর বা আমূল",
    "exampleEn": "The company had to take drastic measures to avoid bankruptcy.",
    "exampleBn": "দেউলিয়া হওয়া এড়াতে কোম্পানিটিকে কঠোর ব্যবস্থা নিতে হয়েছিল।",
    "synonyms": ["extreme", "severe", "radical"],
    "antonyms": ["mild", "moderate"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 92
  },
  {
    "word": "Empower",
    "phonetic": "/ɪmˈpaʊər/ (ইম্পাওয়ার)",
    "partOfSpeech": "Verb",
    "meaningBn": "ক্ষমতায়িত করা, সামর্থ্য প্রদান করা",
    "exampleEn": "Education is the key tool to empower rural youth.",
    "exampleBn": "গ্রামীণ যুবসমাজকে ক্ষমতায়িত করার মূল চাবিকাঠি হলো শিক্ষা।",
    "synonyms": ["authorize", "enable", "strengthen"],
    "antonyms": ["disempower", "disable"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 93
  },
  {
    "word": "Flourish",
    "phonetic": "/ˈflʌrɪʃ/ (ফ্লারিশ)",
    "partOfSpeech": "Verb",
    "meaningBn": "সমৃদ্ধ হওয়া, উন্নতি লাভ করা",
    "exampleEn": "Small businesses tend to flourish in a stable economy.",
    "exampleBn": "একটি স্থিতিশীল অর্থনীতিতে ক্ষুদ্র ব্যবসাগুলো সমৃদ্ধ লাভ করে।",
    "synonyms": ["thrive", "prosper", "bloom"],
    "antonyms": ["wither", "decline"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 94
  },
  {
    "word": "Genuine",
    "phonetic": "/ˈdʒenjuɪn/ (জেনুইন)",
    "partOfSpeech": "Adjective",
    "meaningBn": "আসল, খাঁটি বা আন্তরিক",
    "exampleEn": "He showed a genuine interest in learning new things.",
    "exampleBn": "নতুন জিনিস শেখার প্রতি তিনি এক আন্তরিক আগ্রহ দেখিয়েছেন।",
    "synonyms": ["authentic", "real", "sincere"],
    "antonyms": ["fake", "insincere"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 95
  },
  {
    "word": "Hypothesis",
    "phonetic": "/haɪˈpɒθəsɪs/ (হাইপোথেসিস)",
    "partOfSpeech": "Noun",
    "meaningBn": "অনুমান, প্রকল্প বা ধারণা",
    "exampleEn": "Scientists will test the hypothesis through various experiments.",
    "exampleBn": "বিজ্ঞানীগণ বিভিন্ন পরীক্ষার মাধ্যমে ধারণাটি পরীক্ষা করবেন।",
    "synonyms": ["theory", "assumption", "premise"],
    "antonyms": ["fact", "proof"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 96
  },
  {
    "word": "Impartial",
    "phonetic": "/ɪmˈpɑːʃl/ (ইম্পার্শাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "নিরপেক্ষ, পক্ষপাতহীন",
    "exampleEn": "A judge must remain completely impartial during a trial.",
    "exampleBn": "বিচার চলাকালীন একজন বিচারককে সম্পূর্ণ নিরপেক্ষ থাকতে হবে।",
    "synonyms": ["unbiased", "neutral", "fair"],
    "antonyms": ["biased", "partial"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 97
  },
  {
    "word": "Lucrative",
    "phonetic": "/ˈluːkrətɪv/ (লুকরেটিভ)",
    "partOfSpeech": "Adjective",
    "meaningBn": "লাভজনক, লাভজনক বা লাভদায়ক",
    "exampleEn": "He left his old job for a more lucrative offer.",
    "exampleBn": "তিনি আরও একটি লাভজনক অফারের জন্য তাঁর পুরোনো চাকরিটি ছেড়েছেন।",
    "synonyms": ["profitable", "remunerative", "rewarding"],
    "antonyms": ["unprofitable", "unrewarding"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 98
  },
  {
    "word": "Novice",
    "phonetic": "/ˈnɒvɪs/ (নভিস)",
    "partOfSpeech": "Noun",
    "meaningBn": "শিক্ষানবিস, নবীন",
    "exampleEn": "Even a novice can learn to use this app quickly.",
    "exampleBn": "এমনকি একজন শিক্ষানবিসও দ্রুত এই অ্যাপটি ব্যবহার করতে শিখতে পারে।",
    "synonyms": ["beginner", "neophyte", "learner"],
    "antonyms": ["expert", "veteran"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 99
  },
  {
    "word": "Outcome",
    "phonetic": "/ˈaʊtkʌm/ (আউটকাম)",
    "partOfSpeech": "Noun",
    "meaningBn": "ফলাফল, পরিণতি",
    "exampleEn": "We are still waiting for the final outcome of the negotiation.",
    "exampleBn": "আমরা এখনো আলোচনার চূড়ান্ত ফলাফলের জন্য অপেক্ষা করছি।",
    "synonyms": ["result", "consequence", "effect"],
    "antonyms": ["cause", "origin"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_2",
    "frequencyRank": 100
  }
]
