# coding=utf-8

words_p4 = [
 {
    "word": "Valid",
    "phonetic": "/ˈvælɪd/ (ভ্যালিড)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বৈধ, যুক্তিযুক্ত বা গ্রহণযোগ্য",
    "exampleEn": "You need a valid passport to travel abroad.",
    "exampleBn": "বিদেশে ভ্রমণের জন্য আপনার একটি বৈধ পাসপোর্ট প্রয়োজন।",
    "synonyms": ["legitimate", "authentic", "sound"],
    "antonyms": ["invalid", "void"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 151
  },
  {
    "word": "Waive",
    "phonetic": "/weɪv/ (ওয়েভ)",
    "partOfSpeech": "Verb",
    "meaningBn": "মওকুফ করা, দাবি বা অধিকার ত্যাগ করা",
    "exampleEn": "The university decided to waive the application fee.",
    "exampleBn": "বিশ্ববিদ্যালয়টি আবেদন ফি মওকুফ করার সিদ্ধান্ত নিয়েছে।",
    "synonyms": ["relinquish", "forgo", "remit"],
    "antonyms": ["enforce", "claim"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 152
  },
  {
    "word": "Zenith",
    "phonetic": "/ˈzenɪθ/ (জেনিথ)",
    "partOfSpeech": "Noun",
    "meaningBn": "শীর্ষবিন্দু, সাফল্যের সর্বোচ্চ চূড়া",
    "exampleEn": "His career reached its zenith in the late nineties.",
    "exampleBn": "নব্বইয়ের দশকের শেষের দিকে তাঁর ক্যারিয়ার সাফল্যের সর্বোচ্চ চূড়ায় পৌঁছেছিল।",
    "synonyms": ["peak", "pinnacle", "summit"],
    "antonyms": ["nadir", "bottom"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 153
  },
  {
    "word": "Ambiguous",
    "phonetic": "/æmˈbɪɡjuəs/ (অ্যামবিগুয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "দ্ব্যর্থবোধক, অস্পষ্ট",
    "exampleEn": "The contract contains several ambiguous terms.",
    "exampleBn": "চুক্তিটিতে বেশ কিছু অস্পষ্ট বা দ্ব্যর্থবোধক শর্ত রয়েছে।",
    "synonyms": ["unclear", "vague", "equivocal"],
    "antonyms": ["clear", "explicit"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 154
  },
  {
    "word": "Benevolent",
    "phonetic": "/bəˈnevələnt/ (বেনেভোলেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "দয়ালু, পরোপকারী",
    "exampleEn": "A benevolent leader always cares for his people.",
    "exampleBn": "একজন পরোপকারী নেতা সর্বদা তাঁর জনগণের যত্ন নেন।",
    "synonyms": ["charitable", "kind", "generous"],
    "antonyms": ["malevolent", "unkind"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 155
  },
  {
    "word": "Coerce",
    "phonetic": "/kəʊˈɜːs/ (কোয়ার্স)",
    "partOfSpeech": "Verb",
    "meaningBn": "বলপ্রয়োগ করা, বাধ্য করা",
    "exampleEn": "No one should be coerced into signing a agreement.",
    "exampleBn": "কাউকে কোনো চুক্তিতে স্বাক্ষর করতে বাধ্য করা উচিত নয়।",
    "synonyms": ["force", "compel", "pressurize"],
    "antonyms": ["persuade", "allow"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 156
  },
  {
    "word": "Diligent",
    "phonetic": "/ˈdɪlɪdʒənt/ (ডিলিজেন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "পরিশ্রমী, অধ্যবসায়ী",
    "exampleEn": "He is a diligent worker who finishes tasks on time.",
    "exampleBn": "তিনি একজন পরিশ্রমী কর্মী যিনি সময়মতো কাজ শেষ করেন।",
    "synonyms": ["hardworking", "industrious", "assiduous"],
    "antonyms": ["lazy", "negligent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 157
  },
  {
    "word": "Empirical",
    "phonetic": "/ɪmˈpɪrɪkl/ (এমপিরিক্যাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অভিজ্ঞতালব্ধ, পর্যবেক্ষণমূলক",
    "exampleEn": "The research is based on empirical evidence.",
    "exampleBn": "গবেষণাটি অভিজ্ঞতালব্ধ বা পর্যবেক্ষণমূলক প্রমাণের ওপর ভিত্তি করে তৈরি।",
    "synonyms": ["observational", "experimental", "practical"],
    "antonyms": ["theoretical", "hypothetical"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 158
  },
  {
    "word": "Frugal",
    "phonetic": "/ˈfruːɡl/ (ফ্রুগল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "মিতব্যয়ী, হিসাব করে খরচ করে এমন",
    "exampleEn": "He leads a frugal lifestyle to save money for the future.",
    "exampleBn": "ভবিষ্যতের জন্য টাকা বাঁচাতে তিনি মিতব্যয়ী জীবনযাপন করেন।",
    "synonyms": ["economical", "thrifty", "sparing"],
    "antonyms": ["extravagant", "wasteful"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 159
  },
  {
    "word": "Gullible",
    "phonetic": "/ˈɡʌləbl/ (গালিবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সহজ বিশ্বাসী, যাকে সহজে প্রতারিত করা যায়",
    "exampleEn": "Scammers often target gullible individuals.",
    "exampleBn": "প্রতারকেরা প্রায়শই সহজ বিশ্বাসী ব্যক্তিদের লক্ষ্য বানায়।",
    "synonyms": ["credulous", "naïve", "trusting"],
    "antonyms": ["skeptical", "suspicious"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 160
  },
  {
    "word": "Hierarchy",
    "phonetic": "/ˈhaɪərɑːki/ (হায়ারার্কি)",
    "partOfSpeech": "Noun",
    "meaningBn": "ক্রমোচ্চ শ্রেণিবিভাগ, পদমর্যাদাক্রম",
    "exampleEn": "There is a strict corporate hierarchy in this company.",
    "exampleBn": "এই কোম্পানিতে একটি কঠোর প্রাতিষ্ঠানিক পদমর্যাদাক্রম রয়েছে।",
    "synonyms": ["ranking", "pecking order", "grading"],
    "antonyms": [],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 161
  },
  {
    "word": "Innate",
    "phonetic": "/ɪˈneɪt/ (ইনেট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সহজাত, জন্মগত",
    "exampleEn": "She has an innate talent for music.",
    "exampleBn": "সংগীতের প্রতি তাঁর একটি সহজাত বা জন্মগত প্রতিভা রয়েছে।",
    "synonyms": ["inborn", "inherent", "natural"],
    "antonyms": ["acquired", "learned"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 162
  },
  {
    "word": "Juxtapose",
    "phonetic": "/ˌdʒʌkstəˈpəʊz/ (জাক্সটাপোজ)",
    "partOfSpeech": "Verb",
    "meaningBn": "তুলনার জন্য পাশাপাশি স্থাপন করা",
    "exampleEn": "The artist juxtaposed bright and dark colors in the painting.",
    "exampleBn": "শিল্পী চিত্রকর্মটিতে উজ্জ্বল ও গাঢ় রং তুলনার জন্য পাশাপাশি স্থাপন করেছেন।",
    "synonyms": ["collocate", "compare", "side-by-side"],
    "antonyms": ["separate", "isolate"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 163
  },
  {
    "word": "Kinship",
    "phonetic": "/ˈkɪnʃɪp/ (কিনশিপ)",
    "partOfSpeech": "Noun",
    "meaningBn": "রক্তের সম্পর্ক, আত্মীয়তা বা ঘনিষ্ঠতা",
    "exampleEn": "They felt a strong sense of kinship with their neighbors.",
    "exampleBn": "তারা তাদের প্রতিবেশীদের সাথে আত্মীয়তার একটি গভীর অনুভূতি অনুভব করেছিল।",
    "synonyms": ["affinity", "family tie", "connection"],
    "antonyms": ["alienation", "strangement"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 164
  },
  {
    "word": "Lucid",
    "phonetic": "/ˈluːsɪd/ (লুসিড)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সহজবোধ্য, স্পষ্ট",
    "exampleEn": "He gave a lucid presentation on complex financial policies.",
    "exampleBn": "তিনি জটিল আর্থিক নীতির ওপর একটি সহজবোধ্য ও স্পষ্ট প্রেজেন্টেশন দিয়েছেন।",
    "synonyms": ["clear", "comprehensible", "transparent"],
    "antonyms": ["confusing", "unclear"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 165
  },
  {
    "word": "Manifest",
    "phonetic": "/ˈmænɪfest/ (ম্যানিফেস্ট)",
    "partOfSpeech": "Verb / Adjective",
    "meaningBn": "প্রকাশ করা, সুস্পষ্ট করা; স্পষ্ট",
    "exampleEn": "His anxiety began to manifest through physical symptoms.",
    "exampleBn": "তার উদ্বেগ শারীরিক লক্ষণের মাধ্যমে প্রকাশ পেতে শুরু করে।",
    "synonyms": ["demonstrate", "display", "evident"],
    "antonyms": ["conceal", "hide"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 166
  },
  {
    "word": "Nadir",
    "phonetic": "/ˈneɪdɪər/ (নেডিয়ার)",
    "partOfSpeech": "Noun",
    "meaningBn": "সর্বনিম্ন বিন্দু, অবনতির চরম সীমা",
    "exampleEn": "The company's stock value reached its nadir last month.",
    "exampleBn": "গত মাসে কোম্পানির শেয়ারের দাম সর্বনিম্ন বিন্দুতে পৌঁছেছিল।",
    "synonyms": ["lowest point", "bottom", "rock-bottom"],
    "antonyms": ["zenith", "peak"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 167
  },
  {
    "word": "Opaque",
    "phonetic": "/əʊˈpeɪk/ (ওপেক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অস্বচ্ছ, যার মধ্য দিয়ে আলো চলাচল করতে পারে না",
    "exampleEn": "The window was covered with opaque glass.",
    "exampleBn": "জানালাটি অস্বচ্ছ কাচ দিয়ে ঢাকা ছিল।",
    "synonyms": ["non-transparent", "cloudy", "obscure"],
    "antonyms": ["transparent", "clear"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 168
  },
  {
    "word": "Paradox",
    "phonetic": "/ˈpærədɒks/ (প্যারাডক্স)",
    "partOfSpeech": "Noun",
    "meaningBn": "আপাতবিরোধী কথা বা সত্যভাস",
    "exampleEn": "It is a paradox that technology connects us but also makes us feel isolated.",
    "exampleBn": "এটি একটি আপাতবিরোধী বিষয় যে প্রযুক্তি আমাদের যুক্ত করে, আবার একাকীও করে তোলে।",
    "synonyms": ["contradiction", "anomaly", "puzzle"],
    "antonyms": [],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 169
  },
  {
    "word": "Quaint",
    "phonetic": "/kweɪnt/ (কোয়েন্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "মনোরম প্রাচীন ধাঁচের, অদ্ভুত সুন্দর",
    "exampleEn": "They visited a quaint little village in the countryside.",
    "exampleBn": "তারা গ্রামাঞ্চলের একটি মনোরম প্রাচীন ধাঁচের ছোট গ্রাম পরিদর্শন করেছিল।",
    "synonyms": ["picturesque", "charming", "old-fashioned"],
    "antonyms": ["modern", "ordinary"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 170
  },
  {
    "word": "Reconcile",
    "phonetic": "/ˈrekənsaɪl/ (রেকনসাইল)",
    "partOfSpeech": "Verb",
    "meaningBn": "মীমাংসা করা, পুনর্মিলন করা",
    "exampleEn": "They managed to reconcile their differences after a long discussion.",
    "exampleBn": "দীর্ঘ আলোচনার পর তারা তাদের মতভেদগুলোর মীমাংসা করতে সক্ষম হয়েছিল।",
    "synonyms": ["resolve", "harmonize", "settle"],
    "antonyms": ["estrange", "alienate"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 171
  },
  {
    "word": "Skeptical",
    "phonetic": "/ˈskeptɪkl/ (স্কেপটিক্যাল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সন্দেহপ্রবণ, সংশয়ী",
    "exampleEn": "Many people are skeptical about the new policy's success.",
    "exampleBn": "অনেক মানুষই নতুন নীতির সাফল্য নিয়ে সন্দেহপ্রবণ।",
    "synonyms": ["doubtful", "dubious", "distrustful"],
    "antonyms": ["convinced", "certain"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 172
  },
  {
    "word": "Tenacious",
    "phonetic": "/təˈneɪʃəs/ (টেনেশাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "একগুঁয়ে, নাছোড়বান্দা বা সুদৃঢ়",
    "exampleEn": "Her tenacious effort led her to overcome all obstacles.",
    "exampleBn": "তার নাছোড়বান্দা চেষ্টা তাকে সমস্ত বাধা অতিক্রম করতে সাহায্য করেছিল।",
    "synonyms": ["persistent", "determined", "stubborn"],
    "antonyms": ["irresolute", "weak"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 173
  },
  {
    "word": "Uncanny",
    "phonetic": "/ʌnˈkæni/ (আনক্যানি)",
    "partOfSpeech": "Adjective",
    "meaningBn": "অদ্ভুত, অলৌকিক বা রহস্যময়",
    "exampleEn": "He has an uncanny ability to predict the future.",
    "exampleBn": "ভবিষ্যদ্বাণী করার ক্ষেত্রে তার একটি অদ্ভুত বা রহস্যময় ক্ষমতা রয়েছে।",
    "synonyms": ["weird", "mysterious", "eerie"],
    "antonyms": ["ordinary", "normal"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 174
  },
  {
    "word": "Vicarious",
    "phonetic": "/vɪˈkeəriəs/ (ভিক্যারিয়াস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "পরোক্ষ, অন্যের অভিজ্ঞতার মাধ্যমে অর্জিত",
    "exampleEn": "Parents often feel a vicarious thrill in their children's success.",
    "exampleBn": "বাবা-মায়েরা প্রায়শই সন্তানদের সাফল্যে একটি পরোক্ষ আনন্দ অনুভব করেন।",
    "synonyms": ["indirect", "secondhand", "substitute"],
    "antonyms": ["direct", "firsthand"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 175
  },
  {
    "word": "Wary",
    "phonetic": "/ˈweəri/ (ওয়েয়ারি)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সতর্ক, হুশিয়ার",
    "exampleEn": "Be wary of online scams asking for personal information.",
    "exampleBn": "ব্যক্তিগত তথ্য চাওয়া অনলাইন স্ক্যাম বা প্রতারণা সম্পর্কে সতর্ক থাকুন।",
    "synonyms": ["cautious", "alert", "watchful"],
    "antonyms": ["careless", "unwary"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 176
  },
  {
    "word": "Yielding",
    "phonetic": "/ˈjiːldɪŋ/ (যিল্ডিং)",
    "partOfSpeech": "Adjective",
    "meaningBn": "নমনীয়, আদেশ বা নির্দেশ মেনে চলে এমন",
    "exampleEn": "A yielding material was used to absorb the impact.",
    "exampleBn": "আঘাত বা ধাক্কা শোষণের জন্য একটি নমনীয় উপাদান ব্যবহার করা হয়েছিল।",
    "synonyms": ["compliant", "flexible", "submissive"],
    "antonyms": ["rigid", "stubborn"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 177
  },
  {
    "word": "Aesthetic",
    "phonetic": "/iːsˈθetɪk/ (এসথেটিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "সৌন্দর্যবোধ সংক্রান্ত, নান্দনিক",
    "exampleEn": "The interior design has a high aesthetic value.",
    "exampleBn": "ইন্টেরিয়র ডিজাইনের একটি উচ্চ নান্দনিক মান রয়েছে।",
    "synonyms": ["artistic", "tasteful", "beautiful"],
    "antonyms": ["unsightly", "unattractive"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 178
  },
  {
    "word": "Bolster",
    "phonetic": "/ˈbəʊlstər/ (বোলস্টার)",
    "partOfSpeech": "Verb",
    "meaningBn": "জোরালো করা, সমর্থন করা বা শক্তিশালী করা",
    "exampleEn": "The new evidence helped bolster his argument.",
    "exampleBn": "নতুন প্রমাণগুলো তার যুক্তিকে আরও জোরালো বা শক্তিশালী করতে সাহায্য করেছিল।",
    "synonyms": ["strengthen", "reinforce", "support"],
    "antonyms": ["weaken", "undermine"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 179
  },
  {
    "word": "Candid",
    "phonetic": "/ˈkændɪd/ (ক্যান্ডিড)",
    "partOfSpeech": "Adjective",
    "meaningBn": "কপটতাহীন, স্পষ্টবাদী বা অমায়িক",
    "exampleEn": "She gave a candid response during the interview.",
    "exampleBn": "সাক্ষাৎকারের সময় তিনি একটি অমায়িক বা কাপটতাহীন প্রতিক্রিয়া দিয়েছিলেন।",
    "synonyms": ["frank", "honest", "straightforward"],
    "antonyms": ["evasive", "deceitful"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 180
  },
  {
    "word": "Deficit",
    "phonetic": "/ˈdefɪsɪt/ (ডেফিসিট)",
    "partOfSpeech": "Noun",
    "meaningBn": "ঘাটতি, অভাব",
    "exampleEn": "The government is trying to reduce the trade deficit.",
    "exampleBn": "সরকার বাণিজ্য ঘাটতি কমানোর চেষ্টা করছে।",
    "synonyms": ["shortage", "shortfall", "loss"],
    "antonyms": ["surplus", "excess"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 181
  },
  {
    "word": "Eccentric",
    "phonetic": "/ɪkˈsentrɪk/ (ইকসেন্ট্রিক)",
    "partOfSpeech": "Adjective",
    "meaningBn": "খেয়ালি, অদ্ভুত স্বভাবের",
    "exampleEn": "The old professor was known for his eccentric behavior.",
    "exampleBn": "বৃদ্ধ অধ্যাপক তাঁর খেয়ালি আচরণের জন্য পরিচিত ছিলেন।",
    "synonyms": ["unconventional", "peculiar", "odd"],
    "antonyms": ["normal", "conventional"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 182
  },
  {
    "word": "Ferocious",
    "phonetic": "/fəˈrəʊʃəs/ (ফেরোশাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "হিংস্র, ভয়ানক",
    "exampleEn": "The lion is a ferocious predator in the wild.",
    "exampleBn": "সিংহ বনাঞ্চলের একটি অত্যন্ত হিংস্র শিকারী প্রাণী।",
    "synonyms": ["fierce", "savage", "wild"],
    "antonyms": ["gentle", "tame"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 183
  },
  {
    "word": "Genre",
    "phonetic": "/ˈʒɒ̃rə/ (জনরা)",
    "partOfSpeech": "Noun",
    "meaningBn": "শিল্প বা সাহিত্যের ধারা বা ধরন",
    "exampleEn": "Science fiction is a popular genre among teenagers.",
    "exampleBn": "সাইন্স ফিকশন বা বিজ্ঞান কল্পকাহিনী কিশোর-কিশোরীদের মধ্যে একটি জনপ্রিয় ধারা।",
    "synonyms": ["category", "style", "type"],
    "antonyms": [],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 184
  },
  {
    "word": "Heinous",
    "phonetic": "/ˈheɪnəs/ (হেইনাস)",
    "partOfSpeech": "Adjective",
    "meaningBn": "জঘন্য, নৃশংস",
    "exampleEn": "The criminal was sentenced to life imprisonment for his heinous crime.",
    "exampleBn": "জঘন্য অপরাধের জন্য অপরাধীকে যাবজ্জীবন কারাদণ্ড দেওয়া হয়েছে।",
    "synonyms": ["atrocious", "monstrous", "abominable"],
    "antonyms": ["admirable", "noble"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 185
  },
  {
    "word": "Illuminate",
    "phonetic": "/ɪˈluːmɪneɪt/ (ইলিউমিনেট)",
    "partOfSpeech": "Verb",
    "meaningBn": "আলোকিত করা, স্পষ্ট করে ব্যাখ্যা করা",
    "exampleEn": "Streetlights were turned on to illuminate the dark road.",
    "exampleBn": "অন্ধকার রাস্তাটি আলোকিত করতে রাস্তার বাতি জ্বালানো হয়েছিল।",
    "synonyms": ["light up", "clarify", "enlighten"],
    "antonyms": ["darken", "obscure"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 186
  },
  {
    "word": "Jubilant",
    "phonetic": "/ˈdʒuːbɪlənt/ (জু্বিল্যান্ট)",
    "partOfSpeech": "Adjective",
    "meaningBn": "আনন্দিত, উল্লসিত",
    "exampleEn": "The crowd was jubilant after their team won the match.",
    "exampleBn": "দলটি ম্যাচে জয়লাভ করার পর জনতা উল্লসিত হয়েছিল।",
    "synonyms": ["ecstatic", "overjoyed", "elated"],
    "antonyms": ["depressed", "sorrowful"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 187
  },
  {
    "word": "Looming",
    "phonetic": "/ˈluːmɪŋ/ (লুমিং)",
    "partOfSpeech": "Adjective",
    "meaningBn": "আসন্ন (যা ভীতিজনক বা উদ্বেগজনক)",
    "exampleEn": "The company prepared itself for the looming economic crisis.",
    "exampleBn": "কোম্পানিটি আসন্ন অর্থনৈতিক সংকটের জন্য নিজেকে প্রস্তুত করেছিল।",
    "synonyms": ["impending", "approaching", "threatening"],
    "antonyms": ["distant", "receding"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 188
  },
  {
    "word": "Malleable",
    "phonetic": "/ˈmæliəbl/ (ম্যালিঅ্যাবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "নমনীয়, পিটিয়ে রূপ পরিবর্তনযোগ্য",
    "exampleEn": "Gold is a highly malleable metal.",
    "exampleBn": "সোনা একটি অত্যন্ত নমনীয় ধাতু।",
    "synonyms": ["pliant", "flexible", "adaptable"],
    "antonyms": ["rigid", "brittle"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 189
  },
  {
    "word": "Nurturing",
    "phonetic": "/ˈnɜːtʃərɪŋ/ (নারচারিং)",
    "partOfSpeech": "Noun / Adjective",
    "meaningBn": "লালন-পালনকারী, বিকাশ সাধনকারী",
    "exampleEn": "A nurturing environment helps children grow with confidence.",
    "exampleBn": "একটি বিকাশ সাধনকারী পরিবেশ শিশুদের আত্মবিশ্বাসের সাথে বেড়ে উঠতে সাহায্য করে।",
    "synonyms": ["fostering", "caring", "supportive"],
    "antonyms": ["neglectful", "harmful"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 190
  },
  {
    "word": "Outspoken",
    "phonetic": "/aʊtˈspəʊkən/ (আউটস্পোকেন)",
    "partOfSpeech": "Adjective",
    "meaningBn": "স্পষ্টভাষী, নির্ভীক বক্তা",
    "exampleEn": "She is an outspoken critic of corruption.",
    "exampleBn": "তিনি দুর্নীতির একজন নির্ভীক ও স্পষ্টভাষী সমালোচক।",
    "synonyms": ["candid", "vocal", "forthright"],
    "antonyms": ["reserved", "reticent"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 191
  },
  {
    "word": "Plausibility",
    "phonetic": "/ˌplɔːzəˈbɪləti/ (প্লজিবিলিটি)",
    "partOfSpeech": "Noun",
    "meaningBn": "বিশ্বাসযোগ্যতা, সম্ভাব্যতা",
    "exampleEn": "The police questioned the plausibility of his story.",
    "exampleBn": "পুলিশ তার গল্পের বিশ্বাসযোগ্যতা নিয়ে প্রশ্ন তুলেছিল।",
    "synonyms": ["credibility", "likelihood", "feasibility"],
    "antonyms": ["improbability", "implausibility"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 192
  },
  {
    "word": "Reiterate",
    "phonetic": "/riˈɪtəreɪt/ (রিইটারেট)",
    "partOfSpeech": "Verb",
    "meaningBn": "পুনরাবৃত্তি করা, বারবার বলা",
    "exampleEn": "Let me reiterate the importance of following safety rules.",
    "exampleBn": "আমাকে নিরাপত্তা নিয়ম মেনে চলার গুরুত্বটি আবারও মনে করিয়ে বা পুনরাবৃত্তি করতে দিন।",
    "synonyms": ["repeat", "restate", "reaffirm"],
    "antonyms": [],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 193
  },
  {
    "word": "Synchronize",
    "phonetic": "/ˈsɪŋkrənaɪz/ (সিংক্রোনাইজ)",
    "partOfSpeech": "Verb",
    "meaningBn": "একই সময়ে ঘটানো, যুগপৎ করা",
    "exampleEn": "Please synchronize your watches before starting the mission.",
    "exampleBn": "মিশন শুরু করার আগে অনুগ্রহ করে আপনাদের ঘড়িগুলোর সময় মিলিয়ে বা একই সময়ে সেট করে নিন।",
    "synonyms": ["coordinate", "align", "match"],
    "antonyms": [],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 194
  },
  {
    "word": "Threshold",
    "phonetic": "/ˈθreʃhəʊld/ (থ্রেশহোল্ড)",
    "partOfSpeech": "Noun",
    "meaningBn": "প্রবেশদ্বার, সূচনা বা সর্বনিম্ন সীমা",
    "exampleEn": "He stood on the threshold of a promising career.",
    "exampleBn": "তিনি একটি সম্ভাবনাময় ক্যারিয়ারের সূচনালগ্নে দাঁড়িয়ে ছিলেন।",
    "synonyms": ["doorway", "entrance", "beginning"],
    "antonyms": ["end", "conclusion"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 195
  },
  {
    "word": "Unanimously",
    "phonetic": "/juːˈnænɪməsli/ (ইউন্যানিমাসলি)",
    "partOfSpeech": "Adverb",
    "meaningBn": "সর্বসম্মতভাবে, সর্বসম্মতিক্রমে",
    "exampleEn": "The bill was unanimously passed in parliament.",
    "exampleBn": "বিলটি সংসদে সর্বসম্মতভাবে পাস হয়েছিল।",
    "synonyms": ["unitedly", "without opposition"],
    "antonyms": ["differently", "disagreeing"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 196
  },
  {
    "word": "Viable",
    "phonetic": "/ˈvaɪəbl/ (ভায়াবল)",
    "partOfSpeech": "Adjective",
    "meaningBn": "বাস্তবায়নযোগ্য, টিকে থাকতে সক্ষম",
    "exampleEn": "We need to find a commercially viable solution.",
    "exampleBn": "আমাদের একটি বাণিজ্যিকভাবে বাস্তবায়নযোগ্য সমাধান খুঁজে বের করতে হবে।",
    "synonyms": ["feasible", "workable", "practical"],
    "antonyms": ["unviable", "impractical"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 197
  },
  {
    "word": "Withholding",
    "phonetic": "/wɪðˈhəʊldɪŋ/ (উইথহোল্ডিং)",
    "partOfSpeech": "Noun / Verb",
    "meaningBn": "আটকে রাখা, প্রকাশ না করা",
    "exampleEn": "Withholding crucial evidence is a punishable offense.",
    "exampleBn": "গুরুত্বপূর্ণ প্রমাণ আটকে রাখা বা গোপন করা একটি দণ্ডনীয় অপরাধ।",
    "synonyms": ["retaining", "suppressing", "concealing"],
    "antonyms": ["releasing", "disclosing"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 198
  },
  {
    "word": "Yearning",
    "phonetic": "/ˈjɜːnɪŋ/ (য়ার্নিং)",
    "partOfSpeech": "Noun",
    "meaningBn": "আকুল আকাঙ্ক্ষা, তীব্র ইচ্ছা",
    "exampleEn": "She felt a deep yearning to return to her homeland.",
    "exampleBn": "তিনি নিজের জন্মভূমিতে ফিরে যাওয়ার এক আকুল আকাঙ্ক্ষা অনুভব করেছিলেন।",
    "synonyms": ["longing", "desire", "craving"],
    "antonyms": ["apathy", "indifference"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 199
  },
  {
    "word": "Zealot",
    "phonetic": "/ˈzelət/ (জে্লট)",
    "partOfSpeech": "Noun",
    "meaningBn": "ধর্মান্ধ, কট্টর সমর্থক",
    "exampleEn": "The political zealot refused to listen to reason.",
    "exampleBn": "সেই কট্টর সমর্থক বা অন্ধ অনুসারী কোনো যুক্তি শুনতেই অস্বীকার করেছিল।",
    "synonyms": ["fanatic", "extremist", "radical"],
    "antonyms": ["moderate"],
    "category": "BCS & Govt Jobs High-Frequency",
    "packId": "vocab_pack_4",
    "frequencyRank": 200
  }
]
