# -*- coding: utf-8 -*-
import json

batch2_sub1 = [
    {
        "word": "Conchology",
        "pos": "Noun",
        "phonetic": "/kɒŋˈkɒl.ə.dʒi/ (কঙ্কোলজি)",
        "meaningBn": "শামুক ও ঝিনুকের শক্ত বহিরাবরণী বা খোলসসংক্রান্ত বিজ্ঞান",
        "synonyms": ["Shell collecting", "Study of mollusk shells"],
        "antonyms": ["Malacology (broader study)"],
        "exampleEn": "Her childhood hobby of beachcombing evolved into a distinguished career in conchology.",
        "exampleBn": "সমুদ্রসৈকতে শামুকের খোলস কুড়ানোর শৈশবের শখটি কালক্রমে তাঁর কঙ্কোলজি বা খোলসবিজ্ঞানের পেশায় রূপ নেয়।",
        "category": "Science & Environment"
    },
    {
        "word": "Carcinology",
        "pos": "Noun",
        "phonetic": "/ˌkɑːr.sɪˈnɒl.ə.dʒi/ (কার্সিনোলজি)",
        "meaningBn": "কাঁকড়া, চিংড়ি ও ক্রাস্টাশিয়ান প্রাণীসংক্রান্ত বিজ্ঞান",
        "synonyms": ["Crustaceology", "Study of crustaceans"],
        "antonyms": ["Entomology"],
        "exampleEn": "The marine laboratory conducts research in carcinology, focusing on deep-sea hermit crabs.",
        "exampleBn": "সামুদ্রিক ল্যাবরেটরিটি গভীর সমুদ্রের সন্ন্যাসী কাঁকড়ার ওপর আলোকপাত করে ক্রাস্টাশিয়ান বিজ্ঞান গবেষণা পরিচালনা করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Myrmecology",
        "pos": "Noun",
        "phonetic": "/ˌmɜːr.mɪˈkɒl.ə.dʒi/ (মার্মিকোলজি)",
        "meaningBn": "পিপীলিকা বা পিঁপড়াসংক্রান্ত বৈজ্ঞানিক পাঠ",
        "synonyms": ["Study of ants", "Ant science"],
        "antonyms": ["Apiology"],
        "exampleEn": "E.O. Wilson was the world's foremost authority on myrmecology and social insect behavior.",
        "exampleBn": "ই.ও. উইলসন ছিলেন পিঁপড়াবিদ্যা এবং সামাজিক পতঙ্গের আচরণের ক্ষেত্রে বিশ্বের শীর্ষস্থানীয় বিশেষজ্ঞ।",
        "category": "Science & Environment"
    },
    {
        "word": "Lepidopterology",
        "pos": "Noun",
        "phonetic": "/ˌlɛp.ɪˌdɒp.təˈrɒl.ə.dʒi/ (লেপিডপ্টেরোলজি)",
        "meaningBn": "প্রজাপতি ও মথসংক্রান্ত বৈজ্ঞানিক পাঠ",
        "synonyms": ["Study of butterflies and moths"],
        "antonyms": ["Coleopterology"],
        "exampleEn": "Vladimir Nabokov was deeply committed to lepidopterology alongside his literary writing.",
        "exampleBn": "ভ্লাদিমির নাবোকভ তাঁর সাহিত্যচর্চার পাশাপাশি প্রজাপতিবিদ্যার প্রতিও গভীরভাবে নিবেদিত ছিলেন।",
        "category": "Science & Environment"
    },
    {
        "word": "Coleopterology",
        "pos": "Noun",
        "phonetic": "/ˌkoʊ.li.ɒp.təˈrɒl.ə.dʒi/ (কোলিওপটেরোলজি)",
        "meaningBn": "গুবরে পোকা ও বিটল (beetle) সংক্রান্ত বিজ্ঞান",
        "synonyms": ["Study of beetles"],
        "antonyms": ["Lepidopterology"],
        "exampleEn": "Coleopterology covers the largest order of insects, encompassing over 400,000 species of beetles.",
        "exampleBn": "গুবরে পোকা বিজ্ঞান পতঙ্গজগতের বৃহত্তম বর্গ নিয়ে কাজ করে, যার মধ্যে চার লক্ষাধিক বিটল প্রজাতি অন্তর্ভুক্ত।",
        "category": "Science & Environment"
    },
    {
        "word": "Melittology",
        "pos": "Noun",
        "phonetic": "/ˌmɛl.ɪˈtɒl.ə.dʒi/ (মেলিটোলজি)",
        "meaningBn": "মৌমাছিসংক্রান্ত বৈজ্ঞানিক পাঠ (Apiology)",
        "synonyms": ["Apiology", "Study of bees"],
        "antonyms": ["Myrmecology"],
        "exampleEn": "Melittology is critical today to understand global pollinator decline and colony collapse disorder.",
        "exampleBn": "বিশ্বব্যাপী পরাগায়নকারী পতঙ্গের হ্রাস ও মৌমাছির ঝাঁক বিলুপ্তি বুঝতে মেলিটোলজি অত্যন্ত জরুরি।",
        "category": "Science & Environment"
    },
    {
        "word": "Arachnology",
        "pos": "Noun",
        "phonetic": "/ˌær.əkˈnɒl.ə.dʒi/ (অ্যারাকনোলজি)",
        "meaningBn": "মাকড়সা, বিচ্ছু ও আটপেয়ে সন্ধিপদী প্রাণীসংক্রান্ত বিজ্ঞান",
        "synonyms": ["Study of spiders and scorpions"],
        "antonyms": ["Entomology"],
        "exampleEn": "Research in arachnology has uncovered extraordinary biomedical properties in spider venom peptides.",
        "exampleBn": "মাকড়সাবিদ্যার গবেষণা মাকড়সার বিষের পেপটাইডে অসাধারণ প্রাণ-চিকিৎসাগত গুণাবলি উন্মোচন করেছে।",
        "category": "Science & Environment"
    },
    {
        "word": "Acarology",
        "pos": "Noun",
        "phonetic": "/ˌæk.əˈrɒl.ə.dʒi/ (অ্যাকারোলজি)",
        "meaningBn": "আটুল ও মাইট (টিক ও মাইট) সংক্রান্ত বিজ্ঞান",
        "synonyms": ["Study of mites and ticks"],
        "antonyms": ["Nematology"],
        "exampleEn": "Medical acarology investigates the transmission of Lyme disease by blacklegged deer ticks.",
        "exampleBn": "চিকিৎসা মাইটবিজ্ঞান হরিণের শরীরে থাকা আটুলের মাধ্যমে লাইম রোগ সংক্রমণের উপায় অনুসন্ধান করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Helminthology",
        "pos": "Noun",
        "phonetic": "/ˌhɛl.mɪnˈθɒl.ə.dʒi/ (হেলমিন্থোলজি)",
        "meaningBn": "পরজীবী কৃমি ও ক্রিমিঘটিত রোগসংক্রান্ত বিজ্ঞান",
        "synonyms": ["Study of parasitic worms"],
        "antonyms": ["Protozoology"],
        "exampleEn": "Public health initiatives in the tropics rely heavily on field research in helminthology.",
        "exampleBn": "গ্রীষ্মমণ্ডলীয় অঞ্চলে জনস্বাস্থ্য কর্মসূচি পরজীবী কৃমিবিজ্ঞান গবেষণার ওপর গভীরভাবে নির্ভর করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Nematology",
        "pos": "Noun",
        "phonetic": "/ˌnɛm.əˈtɒl.ə.dʒi/ (নেমাটোলজি)",
        "meaningBn": "সুত্রকৃমি বা গোলকৃমি (nematode) সংক্রান্ত বিজ্ঞান",
        "synonyms": ["Study of roundworms"],
        "antonyms": ["Helminthology (general)"],
        "exampleEn": "Agricultural nematology studies how soil nematodes damage vegetable root systems.",
        "exampleBn": "কৃষি সূত্রকৃমিবিজ্ঞান পর্যালোচনা করে কীভাবে মাটির গোলকৃমি শাকসবজির মূল বা শিকড় ক্ষতিগ্রস্ত করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Protozoology",
        "pos": "Noun",
        "phonetic": "/ˌproʊ.toʊ.zoʊˈɒl.ə.dʒi/ (প্রোটোজুওলজি)",
        "meaningBn": "এককোষী আদ্যপ্রাণী বা প্রোটোজোয়াসংক্রান্ত বিজ্ঞান",
        "synonyms": ["Study of protozoa", "Protistology"],
        "antonyms": ["Bacteriology"],
        "exampleEn": "Protozoology was revolutionized by the early microscopical observations of Antonie van Leeuwenhoek.",
        "exampleBn": "অ্যান্টনি ভন লিউয়েনহুকের প্রাথমিক অণুবীক্ষণ পর্যবেক্ষণের মাধ্যমে আদ্যপ্রাণীবিজ্ঞানে বিপ্লব ঘটেছিল।",
        "category": "Science & Environment"
    },
    {
        "word": "Posology",
        "pos": "Noun",
        "phonetic": "/poʊˈzɒl.ə.dʒi/ (পোসোলজি)",
        "meaningBn": "ওষুধের মাত্রা বা ডোজ নির্ধারণসংক্রান্ত চিকিৎসাশাস্ত্র",
        "synonyms": ["Science of dosages", "Dose calculation"],
        "antonyms": ["Toxicology (overdose focus)"],
        "exampleEn": "Accurate posology is vital in pediatrics to ensure medicine is both safe and therapeutically effective.",
        "exampleBn": "ওষুধ যেন নিরাপদ এবং কার্যকর হয় তা নিশ্চিত করতে শিশুরোগ চিকিৎসায় নির্ভুল মাত্রাবিজ্ঞান অত্যাবশ্যক।",
        "category": "Medical & Health"
    },
    {
        "word": "Nosology",
        "pos": "Noun",
        "phonetic": "/noʊˈzɒl.ə.dʒi/ (নোসোলজি)",
        "meaningBn": "রোগের নিয়মতান্ত্রিক শ্রেণিবিন্যাস ও নামকরণবিদ্যা",
        "synonyms": ["Disease classification", "Systematic pathology"],
        "antonyms": ["Symptom description"],
        "exampleEn": "The World Health Organization periodically revises its international nosology of diseases.",
        "exampleBn": "বিশ্ব স্বাস্থ্য সংস্থা পর্যায়ক্রমে রোগের আন্তর্জাতিক শ্রেণিবিন্যাস ও নামকরণ তালিকা সংস্কার করে থাকে।",
        "category": "Medical & Health"
    },
    {
        "word": "Symptomatology",
        "pos": "Noun",
        "phonetic": "/ˌsɪmp.tə.məˈtɒl.ə.dʒi/ (সিম্পটোম্যাটোলজি)",
        "meaningBn": "রোগের লক্ষণ ও উপসর্গসংক্রান্ত আলোচনা বা উপসর্গসমূহ",
        "synonyms": ["Clinical signs", "Symptom complex", "Semiotics"],
        "antonyms": ["Etiology (cause)"],
        "exampleEn": "The typical symptomatology of the viral illness includes high fever, fatigue, and dry cough.",
        "exampleBn": "ভাইরাসজনিত অসুস্থতার সাধারণ লক্ষণসমূহের মধ্যে রয়েছে তীব্র জ্বর, অবসাদ ও শুষ্ক কাশি।",
        "category": "Medical & Health"
    },
    {
        "word": "Syndromic",
        "pos": "Adjective",
        "phonetic": "/sɪnˈdrɒm.ɪk/ (সিন্ড্রোমিক)",
        "meaningBn": "রোগের সমলক্ষণযুক্ত বা নির্দিষ্ট সিন্ড্রোম সংশ্লিষ্ট",
        "synonyms": ["Characteristic of a syndrome", "Multi-symptom"],
        "antonyms": ["Isolated", "Asymptomatic"],
        "exampleEn": "Hospitals implement syndromic surveillance to detect sudden infectious outbreaks before lab tests confirm them.",
        "exampleBn": "ল্যাব টেস্ট নিশ্চিত করার আগেই সংক্রামক রোগের প্রাদুর্ভাব ধরতে হাসপাতালগুলো সমলক্ষণভিত্তিক নজরদারি চালায়।",
        "category": "Medical & Health"
    },
    {
        "word": "Pathophysiology",
        "pos": "Noun",
        "phonetic": "/ˌpæθ.oʊˌfɪz.iˈɒl.ə.dʒi/ (প্যাথোফিজিওলজি)",
        "meaningBn": "রোগের ফলে শরীরের স্বাভাবিক শারীরবৃত্তীয় প্রক্রিয়ায় সৃষ্ট অস্বাভাবিকতা",
        "synonyms": ["Physiopathology", "Disease mechanism"],
        "antonyms": ["Normal physiology"],
        "exampleEn": "Understanding the pathophysiology of diabetes is necessary to design targeted therapies.",
        "exampleBn": "ডায়াবেটিসের অসুস্থ শারীরবৃত্তীয় প্রক্রিয়া বোঝা লক্ষ্যভিত্তিক চিকিৎসা উদ্ভাবনের জন্য অপরিহার্য।",
        "category": "Medical & Health"
    },
    {
        "word": "Cytopathology",
        "pos": "Noun",
        "phonetic": "/ˌsaɪ.toʊ.pəˈθɒl.ə.dʒi/ (সাইটোপ্যাথোলজি)",
        "meaningBn": "কোষের গঠন ও বিকৃতি পরীক্ষার মাধ্যমে রোগনির্ণয়বিদ্যা",
        "synonyms": ["Cellular pathology", "Cytodiagnosis"],
        "antonyms": ["Histopathology (tissue focus)"],
        "exampleEn": "A Pap smear is a classic routine procedure in diagnostic cytopathology.",
        "exampleBn": "প্যাপ স্মিয়ার হলো রোগনির্ণয়ী কোষবিকৃতি পরীক্ষার একটি চিরায়ত নিয়মিত পদ্ধতি।",
        "category": "Medical & Health"
    },
    {
        "word": "Histopathology",
        "pos": "Noun",
        "phonetic": "/ˌhɪs.toʊ.pəˈθɒl.ə.dʒi/ (হিস্টোপ্যাথোলজি)",
        "meaningBn": "অণুবীক্ষণযন্ত্রের নিচে জৈবিক টিস্যু পরীক্ষা করে রোগনির্ণয়ের বিজ্ঞান",
        "synonyms": ["Tissue pathology", "Microscopic biopsy examination"],
        "antonyms": ["Gross anatomy"],
        "exampleEn": "The surgeon waited anxiously for the histopathology report to determine if the tumor was malignant.",
        "exampleBn": "টিউমারটি ক্ষতিকর কি না তা জানতে সার্জন উদ্বেগের সাথে টিস্যু পরীক্ষার রিপোর্টের অপেক্ষায় ছিলেন।",
        "category": "Medical & Health"
    },
    {
        "word": "Neonatology",
        "pos": "Noun",
        "phonetic": "/ˌniː.oʊ.neɪˈtɒl.ə.dʒi/ (নিওন্যাটোলজি)",
        "meaningBn": "নবজাতক শিশু ও প্রসবপরবর্তী জটিলতাবিষয়ক বিশেষ চিকিৎসাশাস্ত্র",
        "synonyms": ["Newborn pediatrics", "Infant intensive care"],
        "antonyms": ["Geriatrics"],
        "exampleEn": "Thanks to breakthroughs in neonatology, premature infants born at 24 weeks can now survive and thrive.",
        "exampleBn": "নবজাতক চিকিৎসাশাস্ত্রের অগ্রগতির কারণে ২৪ সপ্তাহে জন্ম নেওয়া অপরিণত শিশুরাও এখন বেঁচে থাকতে পারছে।",
        "category": "Medical & Health"
    },
    {
        "word": "Jurisprudence",
        "pos": "Noun",
        "phonetic": "/ˌdʒʊər.ɪsˈpruː.dəns/ (জুরিসপ্রুডেন্স)",
        "meaningBn": "আইনশাস্ত্র; আইনের দর্শন ও মৌলিক নীতিসমূহ",
        "synonyms": ["Legal theory", "Philosophy of law", "Legal system"],
        "antonyms": ["Lawlessness", "Anarchy"],
        "exampleEn": "Constitutional jurisprudence safeguards individual liberties against executive overreach.",
        "exampleBn": "সাংবিধানিক আইনশাস্ত্র নির্বাহী বিভাগের বাড়াবাড়ির বিরুদ্ধে ব্যক্তি স্বাধীনতা রক্ষা করে।",
        "category": "Law & Justice"
    },
    {
        "word": "Mandamus",
        "pos": "Noun",
        "phonetic": "/mænˈdeɪ.məs/ (ম্যান্ডামাস)",
        "meaningBn": "পরমাদেশ; সরকারি কর্মকর্তা বা সংস্থাকে আইনগত দায়িত্ব পালনে উচ্চ আদালতের নির্দেশ",
        "synonyms": ["Writ of mandate", "Judicial order", "Command"],
        "antonyms": ["Prohibition writ", "Injunction"],
        "exampleEn": "The Supreme Court issued a writ of mandamus directing the municipal authority to clean the river.",
        "exampleBn": "সুপ্রিম কোর্ট নদী পরিষ্কার করার নির্দেশ দিয়ে পৌর কর্তৃপক্ষের প্রতি পরমাদেশ বা ম্যান্ডামাস জারি করে।",
        "category": "Law & Justice"
    },
    {
        "word": "Certiorari",
        "pos": "Noun",
        "phonetic": "/ˌsɜːr.ʃi.əˈrɑː.raɪ/ (সার্সিওরারাই)",
        "meaningBn": "উৎপ্রেষণ রিট; অধস্তন আদালতের নথিপত্র পুনর্বিবেচনার জন্য তলব করার আদেশ",
        "synonyms": ["Writ of review", "Judicial review order"],
        "antonyms": ["Remand order"],
        "exampleEn": "The appellate court granted certiorari to resolve an unsettled question of statutory interpretation.",
        "exampleBn": "সংবিধিবদ্ধ ব্যাখ্যার অমীমাংসিত প্রশ্ন নিষ্পত্তির জন্য আপিল আদালত উৎপ্রেষণ রিট মঞ্জুর করে।",
        "category": "Law & Justice"
    },
    {
        "word": "Res judicata",
        "pos": "Noun",
        "phonetic": "/ˌreɪz dʒuː.dɪˈkɑː.tə/ (রেস জুডিকাটা)",
        "meaningBn": "চূড়ান্তভাবে নিষ্পত্তিপ্রাপ্ত মোকদ্দমা যা পুনরায় আদালতে উত্থাপন নিষিদ্ধ",
        "synonyms": ["Adjudicated matter", "Settled issue", "Final decision"],
        "antonyms": ["Pending litigation", "Sub judice matter"],
        "exampleEn": "The lawsuit was dismissed under the doctrine of res judicata because the matter had already been ruled upon.",
        "exampleBn": "মামলাটি নিষ্পত্তিপ্রাপ্ত মোকদ্দমা নীতির অধীনে খারিজ হয়েছিল কারণ বিষয়টি আগেই আদালতে নিষ্পত্তি হয়েছিল।",
        "category": "Law & Justice"
    },
    {
        "word": "Subpoena",
        "pos": "Noun",
        "phonetic": "/səˈpiː.nə/ (সাবপিনা)",
        "meaningBn": "আদালতে সাক্ষ্য দেওয়ার বা দলিল দাখিলের জন্য জারি করা তলবনামা বা সমন",
        "synonyms": ["Court summons", "Writ", "Judicial subpoena"],
        "antonyms": ["Release from witness", "Exemption"],
        "exampleEn": "The bank manager received a federal subpoena demanding all financial transaction records.",
        "exampleBn": "ব্যাংক ব্যবস্থাপক সমস্ত আর্থিক লেনদেনের রেকর্ড চেয়ে একটি রাষ্ট্রীয় আদালতের সমন পেয়েছিলেন।",
        "category": "Law & Justice"
    },
    {
        "word": "Affidavit",
        "pos": "Noun",
        "phonetic": "/ˌæf.ɪˈdeɪ.vɪt/ (অ্যাফিডেভিট)",
        "meaningBn": "হলফনামা; শপথপূর্বক দেওয়া লিখিত সাক্ষ্য বা বিবৃতি",
        "synonyms": ["Sworn statement", "Deposition", "Attested pledge"],
        "antonyms": ["Unsworn declaration", "Hearsay"],
        "exampleEn": "The witness signed an affidavit confirming that she saw the defendant at the crime scene.",
        "exampleBn": "সাক্ষী অপরাধস্থলে আসামিকে দেখতে পাওয়ার বিষয়ে শপথপূর্বক একটি হলফনামা স্বাক্ষর করেছিলেন।",
        "category": "Law & Justice"
    },
    {
        "word": "Amicus curiae",
        "pos": "Noun",
        "phonetic": "/əˈmiː.kəs ˈkjʊər.i.aɪ/ (অ্যামিকাস কিউরি)",
        "meaningBn": "আদালতের বন্ধু; নিরপেক্ষ আইনি মতামত প্রদানের জন্য নিয়োজিত ব্যক্তি",
        "synonyms": ["Friend of the court", "Impartial adviser"],
        "antonyms": ["Adversary party", "Litigant"],
        "exampleEn": "The prominent civil liberties group submitted an amicus curiae brief on free speech protections.",
        "exampleBn": "বিশিষ্ট নাগরিক অধিকার সংস্থাটি বাকস্বাধীনতা সুরক্ষায় আদালতের বন্ধু হিসেবে অভিমত জমা দিয়েছিল।",
        "category": "Law & Justice"
    },
    {
        "word": "De jure",
        "pos": "Adverb",
        "phonetic": "/deɪ ˈdʒʊər.eɪ/ (দে জুরে)",
        "meaningBn": "আইনগতভাবে; বিধিসম্মত অধিকারবলে",
        "synonyms": ["By legal right", "Lawful", "Legitimate"],
        "antonyms": ["De facto", "Illegitimate"],
        "exampleEn": "Although he was de jure the sovereign monarch, real power was wielded entirely by military officers.",
        "exampleBn": "যদিও তিনি আইনত সার্বভৌম সম্রাট ছিলেন, প্রকৃত ক্ষমতা সম্পূর্ণভাবে সামরিক কর্মকর্তাদের হাতে ছিল।",
        "category": "Law & Justice"
    },
    {
        "word": "De facto",
        "pos": "Adverb",
        "phonetic": "/deɪ ˈfæk.toʊ/ (দে ফ্যাক্টো)",
        "meaningBn": "বাস্তবে বা কার্যত; আইনি স্বীকৃতি না থাকলেও কার্যকর থাকা",
        "synonyms": ["In reality", "In practice", "Actual"],
        "antonyms": ["De jure", "Nominal"],
        "exampleEn": "After the coup, the general became the de facto head of government.",
        "exampleBn": "অভ্যুত্থানের পর জেনারেল বাস্তবে সরকারের কার্যত প্রধান হয়ে ওঠেন।",
        "category": "Law & Justice"
    },
    {
        "word": "Ex post facto",
        "pos": "Adjective",
        "phonetic": "/ˌɛks poʊst ˈfæk.toʊ/ (এক্স পোস্ট ফ্যাক্টো)",
        "meaningBn": "অতীতকাল থেকে কার্যকর; ভূতাপেক্ষ আইনি ব্যবস্থা",
        "synonyms": ["Retroactive", "Retrospective law"],
        "antonyms": ["Prospective", "Future-binding"],
        "exampleEn": "The constitution explicitly forbids ex post facto criminal laws punishing deeds done before legislation.",
        "exampleBn": "আইন পাসের পূর্বের কর্মকাণ্ডকে শাস্তি দিতে ভূতাপেক্ষ ফৌজদারি আইন প্রণয়ন সংবিধান সুস্পষ্টভাবে নিষিদ্ধ করে।",
        "category": "Law & Justice"
    },
    {
        "word": "Bona fide",
        "pos": "Adjective",
        "phonetic": "/ˌboʊ.nə ˈfaɪ.di/ (বোনা ফাইডি)",
        "meaningBn": "সরল বিশ্বাসে কৃত; খাঁটি, প্রকৃত ও প্রবঞ্চনাহীন",
        "synonyms": ["Genuine", "Authentic", "In good faith", "Honest"],
        "antonyms": ["Mala fide", "Fraudulent", "Bogus"],
        "exampleEn": "Only bona fide registered students are eligible to vote in university council elections.",
        "exampleBn": "কেবল প্রকৃত নিবন্ধিত শিক্ষার্থীরাই বিশ্ববিদ্যালয় পরিষদ নির্বাচনে ভোট দেওয়ার যোগ্য।",
        "category": "Law & Justice"
    },
    {
        "word": "Mens rea",
        "pos": "Noun",
        "phonetic": "/ˌmɛnz ˈreɪ.ə/ (মেনস রিয়া)",
        "meaningBn": "অপরাধমূলক অসৎ মানসিক ইচ্ছা বা অপরাধের অভিপ্রায়",
        "synonyms": ["Guilty mind", "Criminal intent"],
        "antonyms": ["Innocent mind", "Lack of intent"],
        "exampleEn": "To convict for murder, the prosecutor must prove both the physical act and the requisite mens rea.",
        "exampleBn": "খুনের অপরাধে দণ্ডিত করতে হলে কৌঁসুলিকে শারীরিক অপরাধকর্ম ও অপরাধমূলক ইচ্ছা উভয়েই প্রমাণ করতে হয়।",
        "category": "Law & Justice"
    },
    {
        "word": "Actus reus",
        "pos": "Noun",
        "phonetic": "/ˌæk.təs ˈreɪ.əs/ (অ্যাক্টাস রিয়াস)",
        "meaningBn": "অপরাধমূলক প্রত্যক্ষ শারীরিক কর্মকাণ্ড বা অপরাধ সংঘটন",
        "synonyms": ["Criminal act", "Guilty deed", "Overt act"],
        "antonyms": ["Inaction", "Mental thought alone"],
        "exampleEn": "A guilty mind alone cannot be punished without proof of an unlawful actus reus.",
        "exampleBn": "বেআইনি অপরাধকর্মের প্রমাণ ছাড়া কেবল অসৎ চিন্তার কারণে কাউকে শাস্তি দেওয়া যায় না।",
        "category": "Law & Justice"
    },
    {
        "word": "Nolo contendere",
        "pos": "Noun",
        "phonetic": "/ˌnoʊ.loʊ kənˈtɛn.də.ri/ (নোলো কনটেনডারি)",
        "meaningBn": "দোষ স্বীকার না করে বিচারিক দণ্ড মেনে নেওয়া সংক্রান্ত আইনি আবেদন",
        "synonyms": ["No contest plea", "Tacit acceptance"],
        "antonyms": ["Plea of not guilty", "Vigorous defense"],
        "exampleEn": "The corporate executive entered a plea of nolo contendere to avoid civil litigation liabilities.",
        "exampleBn": "দেওয়ানি মামলার দায় এড়াতে করপোরেট নির্বাহী দোষ স্বীকার না করে দণ্ড মেনে নেওয়ার আবেদন করেছিলেন।",
        "category": "Law & Justice"
    },
    {
        "word": "Caveat emptor",
        "pos": "Noun",
        "phonetic": "/ˌkæv.i.æt ˈɛmp.tɔːr/ (ক্যাভিয়েট এম্পটর)",
        "meaningBn": "ক্রেতা সাবধান নীতি; পণ্য ক্রয়ের পূর্বে ক্রেতাকেই যাচাই করতে হবে",
        "synonyms": ["Buyer beware", "Purchaser responsibility"],
        "antonyms": ["Seller warranty", "Consumer protection"],
        "exampleEn": "When purchasing antique goods at an auction, the traditional rule of caveat emptor applies.",
        "exampleBn": "নিলামে পুরোনো পণ্য কেনার সময় ক্রেতা সাবধানের সনাতন নীতিটি প্রযোজ্য হয়।",
        "category": "Law & Justice"
    },
    {
        "word": "Prima facie",
        "pos": "Adverb",
        "phonetic": "/ˌpraɪ.mə ˈfeɪ.ʃi/ (প্রাইমা ফ্যাসি)",
        "meaningBn": "প্রথম দর্শনে বা আপাতদৃষ্টিতে সত্য প্রতীয়মান",
        "synonyms": ["At first sight", "On the face of it", "Self-evident"],
        "antonyms": ["Rebutted", "Disproven after scrutiny"],
        "exampleEn": "The forged signature constituted prima facie evidence of extensive bank fraud.",
        "exampleBn": "জাল স্বাক্ষরটি প্রথম দর্শনেই ব্যাপক ব্যাংক জালিয়াতির স্পষ্ট সাক্ষ্য প্রমাণ করেছিল।",
        "category": "Law & Justice"
    },
    {
        "word": "Non sequitur",
        "pos": "Noun",
        "phonetic": "/ˌnɒn ˈsɛk.wɪ.tər/ (নন সিকুইটার)",
        "meaningBn": "অসঙ্গত মন্তব্য বা সিদ্ধান্ত যা পূর্বের কথার সাথে কোনো মিল রাখে না",
        "synonyms": ["Illogical conclusion", "Incongruity", "Disconnection"],
        "antonyms": ["Logical inference", "Sound deduction"],
        "exampleEn": "Claiming that wealth equals moral purity is a flagrant non sequitur.",
        "exampleBn": "ধনসম্পদ থাকা মানেই নৈতিক পবিত্রতা—এমন দাবি করা এক চরম অসঙ্গত কুযুক্তি।",
        "category": "Philosophy & Ethics"
    },
    {
        "word": "Ipso facto",
        "pos": "Adverb",
        "phonetic": "/ˌɪp.soʊ ˈfæk.toʊ/ (ইপসো ফ্যাক্টো)",
        "meaningBn": "সেই ঘটনার ফলেই; বাস্তবিক কার্যকারণেই",
        "synonyms": ["By the very fact itself", "Thereby", "Inevitably"],
        "antonyms": ["Indirectly", "By subsequent process"],
        "exampleEn": "Violating your sworn professional code makes you ipso facto ineligible for the board.",
        "exampleBn": "শপথ নেওয়া পেশাগত নিয়ম ভঙ্গ করার ঘটনা নিজেই আপনাকে কার্যত বোর্ডের অযোগ্য করে তোলে।",
        "category": "Law & Justice"
    },
    {
        "word": "Modus operandi",
        "pos": "Noun",
        "phonetic": "/ˌmoʊ.dəs ˌɒp.ərˈæn.daɪ/ (মোডাস অপারেন্ডি)",
        "meaningBn": "কাজের বা অপরাধ সংগঠনের বিশেষ কার্যপ্রণালী",
        "synonyms": ["Method of operation", "M.O.", "Technique", "Procedure"],
        "antonyms": ["Random behavior", "Unsystematic approach"],
        "exampleEn": "Detectives recognized the burglar's signature modus operandi of disabling security cameras first.",
        "exampleBn": "গোয়েন্দারা প্রথমে সিসিটিভি ক্যামেরা নিষ্ক্রিয় করার মধ্য দিয়ে চোরের চেনা কার্যপ্রণালী ধরে ফেলেছিলেন।",
        "category": "Law & Justice"
    },
    {
        "word": "Modus vivendi",
        "pos": "Noun",
        "phonetic": "/ˌmoʊ.dəs vɪˈvɛn.di/ (মোডাস ভিভেন্ডি)",
        "meaningBn": "বিরোধমান দুই পক্ষের মধ্যে সহাবস্থানের সাময়িক কার্যকর সমঝোতা",
        "synonyms": ["Way of living together", "Practical truce", "Compromise"],
        "antonyms": ["Open warfare", "Unresolved hostility"],
        "exampleEn": "The two feuding neighbors reached a peaceful modus vivendi regarding the shared driveway.",
        "exampleBn": "বিবাদমান দুই প্রতিবেশী যৌথ ড্রাইভওয়ের ব্যবহার নিয়ে একটি শান্তিপূর্ণ কার্যকর সহাবস্থান সমঝোতায় পৌঁছায়।",
        "category": "Law & Justice"
    },
    {
        "word": "Sine qua non",
        "pos": "Noun",
        "phonetic": "/ˌsɪn.eɪ kwɑː ˈnoʊn/ (সিনে কুয়া নন)",
        "meaningBn": "অপরিহার্য পূর্বশর্ত; যা ছাড়া কোনো কিছুই সম্ভব নয়",
        "synonyms": ["Essential condition", "Prerequisite", "Must-have"],
        "antonyms": ["Dispensable detail", "Superfluity"],
        "exampleEn": "Integrity is the absolute sine qua non of a trustworthy judge.",
        "exampleBn": "সততা হলো একজন বিশ্বাসযোগ্য বিচারকের একমাত্র অপরিহার্য পূর্বশর্ত।",
        "category": "BCS & Bank"
    },
    {
        "word": "Ultra vires",
        "pos": "Adjective",
        "phonetic": "/ˌʌl.trə ˈvaɪ.riːz/ (আলট্রা ভায়ারিজ)",
        "meaningBn": "আইনি কর্তৃত্ব বা এখতিয়ারের বাইরে কৃত পদক্ষেপ",
        "synonyms": ["Beyond legal power", "Unauthorized", "Illegitimate"],
        "antonyms": ["Intra vires", "Authorized", "Within powers"],
        "exampleEn": "The Supreme Court declared the minister's unilateral executive order to be ultra vires.",
        "exampleBn": "সুপ্রিম কোর্ট মন্ত্রীর একতরফা নির্বাহী আদেশকে এখতিয়ারবহির্ভূত ও অবৈধ বলে ঘোষণা করে।",
        "category": "Law & Justice"
    },
    {
        "word": "Inter alia",
        "pos": "Adverb",
        "phonetic": "/ˌɪn.tər ˈeɪ.li.ə/ (ইন্টার আলিয়া)",
        "meaningBn": "অন্যান্য বিষয়ের মধ্যে; বিশেষ করে",
        "synonyms": ["Among other things", "Along with others"],
        "antonyms": ["Exclusively", "Solely"],
        "exampleEn": "The committee's annual report highlighted, inter alia, the urgent need for judicial digitisation.",
        "exampleBn": "কমিটির বার্ষিক প্রতিবেদনে অন্যান্য বিষয়ের মধ্যে বিচার বিভাগীয় ডিজিটালাইজেশনের প্রয়োজনীয়তার ওপর জোর দেওয়া হয়েছিল।",
        "category": "Law & Justice"
    },
    {
        "word": "Mutatis mutandis",
        "pos": "Adverb",
        "phonetic": "/mjuːˈtɑː.tɪs mjuːˈtæn.dɪs/ (মুটাটিস মুটানডিস)",
        "meaningBn": "প্রয়োজনীয় পরিবর্তন সাপেক্ষে হুবহু প্রযোজ্য",
        "synonyms": ["With appropriate alterations", "Having changed what needs changing"],
        "antonyms": ["Inapplicable", "Irreconcilable"],
        "exampleEn": "The rules governing the senior tournament apply mutatis mutandis to the junior league.",
        "exampleBn": "সিনিয়র টুর্নামেন্টের নিয়মগুলো প্রয়োজনীয় পরিবর্তন সাপেক্ষে জুনিয়র লিগেও হুবহু প্রযোজ্য হবে।",
        "category": "Law & Justice"
    },
    {
        "word": "Stare decisis",
        "pos": "Noun",
        "phonetic": "/ˈsteɪ.ri dɪˈsaɪ.sɪs/ (স্টেয়ার ডেসিসিস)",
        "meaningBn": "পূর্বনজির অনুসরণের নীতি; অতীতের বিচারিক রায়ের প্রতি আনুগত্য",
        "synonyms": ["Doctrine of precedent", "Following precedent"],
        "antonyms": ["Overruling precedent", "Judicial activism"],
        "exampleEn": "Adhering to stare decisis provides legal predictability and stability across generations.",
        "exampleBn": "পূর্বনজির অনুসরণের নীতি বজায় রাখা প্রজন্মান্তরে আইনি স্থিতিশীলতা ও নিশ্চয়তা দেয়।",
        "category": "Law & Justice"
    },
    {
        "word": "In loco parentis",
        "pos": "Adverb",
        "phonetic": "/ɪn ˈloʊ.koʊ pəˈrɛn.tɪs/ (ইন লোকো প্যারেন্টিস)",
        "meaningBn": "মা-বাবার স্থানে বা অভিভাবকের দায়িত্বে",
        "synonyms": ["In place of a parent", "Acting guardian"],
        "antonyms": ["Independent adult", "Emancipated minor"],
        "exampleEn": "During school field trips, teachers stand in loco parentis regarding pupil safety.",
        "exampleBn": "বিদ্যালয়ের শিক্ষা সফরে শিক্ষার্থীদের নিরাপত্তার ক্ষেত্রে শিক্ষকরা অভিভাবকের দায়িত্বে অবস্থান করেন।",
        "category": "Law & Justice"
    },
    {
        "word": "Force majeure",
        "pos": "Noun",
        "phonetic": "/ˌfɔːrs mæˈʒɜːr/ (ফোর্স মেজার)",
        "meaningBn": "অপ্রতিরোধ্য প্রাকৃতিক বা আকস্মিক ঘটনা যা চুক্তি পালনে বাধা দেয়",
        "synonyms": ["Act of God", "Unforeseeable disaster", "Superior force"],
        "antonyms": ["Foreseeable breach", "Willful default"],
        "exampleEn": "The airline cancelled flights citing a force majeure clause after volcanic ash grounded all planes.",
        "exampleBn": "আগ্নেয়গিরির ছাইয়ে আকাশ ঢেকে যাওয়ার পর বিমান সংস্থা অপ্রতিরোধ্য বাধার ধারা উল্লেখ করে ফ্লাইট বাতিল করে।",
        "category": "Law & Justice"
    },
    {
        "word": "Locus standi",
        "pos": "Noun",
        "phonetic": "/ˌloʊ.kəs ˈstæn.daɪ/ (লোকাস স্ট্যান্ডাই)",
        "meaningBn": "আদালতে মামলা বা আবেদন করার আইনি অধিকার ও সংক্ষুব্ধতা",
        "synonyms": ["Right to bring action", "Legal standing"],
        "antonyms": ["Lack of standing"],
        "exampleEn": "The judge dismissed the petition because the plaintiff lacked locus standi in the land dispute.",
        "exampleBn": "জমি বিরোধে বাদীর কোনো আইনি মামলা করার অধিকার না থাকায় বিচারক আবেদনটি খারিজ করেন।",
        "category": "Law & Justice"
    },
    {
        "word": "Sub judice",
        "pos": "Adjective",
        "phonetic": "/sʌb ˈdʒuː.dɪ.si/ (সাব জুডিসি)",
        "meaningBn": "আদালতে বিচারাধীন বিষয় যার ওপর প্রকাশ্য মন্তব্য করা বারণ",
        "synonyms": ["Under judicial consideration", "Pending trial"],
        "antonyms": ["Adjudicated", "Public domain debate"],
        "exampleEn": "The minister declined to answer reporters, noting that the corruption trial was sub judice.",
        "exampleBn": "দুর্নীতির বিচারটি আদালতে বিচারাধীন থাকায় মন্ত্রী সাংবাদিকদের প্রশ্নের উত্তর দিতে অস্বীকৃতি জানান।",
        "category": "Law & Justice"
    },
    {
        "word": "Obiter dictum",
        "pos": "Noun",
        "phonetic": "/ˌoʊ.bɪ.tər ˈdɪk.təm/ (ওবিটার ডিকটাম)",
        "meaningBn": "রায়ের মূল কারণ নয় এমন বিচারকের প্রাসঙ্গিক মন্তব্য",
        "synonyms": ["Incidental remark", "Judicial passing comment"],
        "antonyms": ["Ratio decidendi", "Binding holding"],
        "exampleEn": "While insightful, the judge's observation was merely obiter dictum and not binding precedent.",
        "exampleBn": "বিচারকের পর্যবেক্ষণটি গভীর হলেও তা ছিল কেবল সহপ্রাসঙ্গিক মন্তব্য, কোনো বাধ্যবাধকতামূলক নজির নয়।",
        "category": "Law & Justice"
    },
    {
        "word": "Ratio decidendi",
        "pos": "Noun",
        "phonetic": "/ˌreɪ.ʃi.oʊ ˌdɛs.ɪˈdɛn.daɪ/ (রেশিও ডেসিডেনডাই)",
        "meaningBn": "আদালতের রায়ের মূল ভিত্তি ও আইনগত সিদ্ধান্ত",
        "synonyms": ["Reason for decision", "Core legal principle", "Binding ruling"],
        "antonyms": ["Obiter dictum"],
        "exampleEn": "Law students must parse the full judgment to identify the binding ratio decidendi.",
        "exampleBn": "বাধ্যবাধকতামূলক মূল আইনি সিদ্ধান্ত চিহ্নিত করতে আইনের শিক্ষার্থীদের সম্পূর্ণ রায়টি বিশ্লেষণ করতে হয়।",
        "category": "Law & Justice"
    }
]

with open('next_part2_sub1.json', 'w', encoding='utf-8') as f:
    json.dump(batch2_sub1, f, ensure_ascii=False, indent=2)
print("Part 2 sub 1 written:", len(batch2_sub1))
