# -*- coding: utf-8 -*-
import json

batch3_sub1 = [
    {
        "word": "Orographic",
        "pos": "Adjective",
        "phonetic": "/ˌɔːr.əˈɡræf.ɪk/ (অরোগ্রাফিক)",
        "meaningBn": "পাহাড় বা পর্বতের অবস্থানজনিত (যেমন শৈলোৎক্ষেপ বৃষ্টিপাত)",
        "synonyms": ["Mountain-induced", "Relief-related"],
        "antonyms": ["Lowland", "Plains-related"],
        "exampleEn": "Orographic precipitation occurs when moist winds are forced upward by steep mountain ranges.",
        "exampleBn": "আর্দ্র বাতাস খাড়া পর্বতমালা দ্বারা বাধা পেয়ে উপরে উঠলে শৈলোৎক্ষেপ বৃষ্টিপাত সৃষ্টি হয়।",
        "category": "Science & Environment"
    },
    {
        "word": "Riparian",
        "pos": "Adjective",
        "phonetic": "/raɪˈpɛər.i.ən/ (রাইপ্যারিয়ান)",
        "meaningBn": "নদী বা প্রাকৃতিক জলাশয়ের তীরবর্তী অঞ্চলসংক্রান্ত",
        "synonyms": ["Riverbank", "Riverside", "Fluvial border"],
        "antonyms": ["Arid", "Inland", "Desert"],
        "exampleEn": "Protecting riparian vegetation prevents riverbank soil erosion and sustains freshwater fish.",
        "exampleBn": "নদীতীরবর্তী বনভূমি সংরক্ষণ নদীর পাড়ের মাটিক্ষয় রোধ করে এবং মিঠা পানির মাছের জীবন রক্ষা করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Littoral",
        "pos": "Adjective",
        "phonetic": "/ˈlɪt.ər.əl/ (লিটোরাল)",
        "meaningBn": "সমুদ্র বা হ্রদের উপকূলীয় অগভীর জলজ এলাকা সংশ্লিষ্ট",
        "synonyms": ["Coastal", "Seashore", "Intertidal"],
        "antonyms": ["Pelagic", "Abyssal", "Inland"],
        "exampleEn": "The littoral zone teems with biodiversity, including crabs, sea anemones, and algae.",
        "exampleBn": "উপকূলীয় অঞ্চলে কাঁকড়া, সাগর কুসুম ও শৈবালসহ প্রচুর জীববৈচিত্র্য দেখতে পাওয়া যায়।",
        "category": "Science & Environment"
    },
    {
        "word": "Estuarine",
        "pos": "Adjective",
        "phonetic": "/ˌɛs.tʃuˈær.aɪn/ (এসচুয়ারাইন)",
        "meaningBn": "নদীমুখ বা মোহনার নোনা ও মিষ্টি পানির মিলনস্থলসংক্রান্ত",
        "synonyms": ["Brackish water", "Estuary-related", "Tidal mouth"],
        "antonyms": ["Upstream", "Pure freshwater"],
        "exampleEn": "Mangrove ecosystems thrive specifically in protected, nutrient-rich estuarine environments.",
        "exampleBn": "ম্যানগ্রোভ বাস্তুতন্ত্র মূলত সুরক্ষিত ও পুষ্টিসমৃদ্ধ নদীমোহনার মোহনাময় পরিবেশে সমৃদ্ধি লাভ করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Brackish",
        "pos": "Adjective",
        "phonetic": "/ˈbræk.ɪʃ/ (ব্র্যাকিশ)",
        "meaningBn": "ঈষৎ লবণাক্ত; মিষ্টি পানির চেয়ে বেশি কিন্তু সমুদ্রের চেয়ে কম লবণযুক্ত",
        "synonyms": ["Slightly salty", "Saline", "Briny"],
        "antonyms": ["Freshwater", "Pure potable"],
        "exampleEn": "The Sundarbans mangrove forest is sustained by vast networks of brackish tidal channels.",
        "exampleBn": "সুন্দরবনের ম্যানগ্রোভ বন ঈষৎ লবণাক্ত জোয়ার-ভাটার খালের বিশাল জালে টিকে রয়েছে।",
        "category": "Science & Environment"
    },
    {
        "word": "Pelagic",
        "pos": "Adjective",
        "phonetic": "/pəˈlædʒ.ɪk/ (পেলাজিক)",
        "meaningBn": "তীর বা সমুদ্রের তলদেশ থেকে দূরে উন্মুক্ত গভীর সমুদ্রসংক্রান্ত",
        "synonyms": ["Open-ocean", "Oceanic", "Offshore"],
        "antonyms": ["Benthic", "Littoral", "Coastal"],
        "exampleEn": "Tuna and blue sharks are agile pelagic predators adapted for high-speed open-sea swimming.",
        "exampleBn": "টুনা এবং নীল হাঙর হলো উন্মুক্ত সাগরে দ্রুত সাঁতারে সক্ষম চটপটে গভীর সমুদ্রের শিকারী।",
        "category": "Science & Environment"
    },
    {
        "word": "Benthic",
        "pos": "Adjective",
        "phonetic": "/ˈbɛn.θɪk/ (বেন্থিক)",
        "meaningBn": "সাগর বা জলাশয়ের তলদেশসংক্রান্ত; পাতালদেশীয়",
        "synonyms": ["Seabed-dwelling", "Bottom-dwelling", "Deep floor"],
        "antonyms": ["Pelagic", "Surface"],
        "exampleEn": "Benthic organisms like sea cucumbers feed on organic debris that drifts down to the ocean floor.",
        "exampleBn": "সমুদ্র শশার মতো তলদেশীয় প্রাণীরা সাগরের তলদেশে ভেসে আসা জৈব অবশেষ খেয়ে জীবনধারণ করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Abyssal",
        "pos": "Adjective",
        "phonetic": "/əˈbɪs.əl/ (অ্যাবাইসাল)",
        "meaningBn": "গভীরতম অতল সাগরের আলোহীন নিম্নাঞ্চলসংক্রান্ত (২,০০০ থেকে ৬,০০০ মিটার গভীরে)",
        "synonyms": ["Deep-sea", "Bottomless ocean", "Profound depths"],
        "antonyms": ["Surface", "Sunlit shallow"],
        "exampleEn": "Creatures of the abyssal zone survive under freezing temperatures and crushing water pressure.",
        "exampleBn": "অতল সমুদ্র অঞ্চলের প্রাণীরা শূন্য ডিগ্রি তাপমাত্রা এবং তীব্র পানির চাপের মধ্যে টিকে থাকে।",
        "category": "Science & Environment"
    },
    {
        "word": "Hadal",
        "pos": "Adjective",
        "phonetic": "/ˈheɪ.dəl/ (হেডাল)",
        "meaningBn": "সমুদ্রের গভীরতম খাতসমূহের অতল অন্ধকার এলাকা (৬,০০০ মিটারের অধিক গভীর)",
        "synonyms": ["Trench zone", "Ultra-deep ocean"],
        "antonyms": ["Shallow", "Littoral"],
        "exampleEn": "The Mariana Trench reaches the mysterious hadal zone, the deepest frontier on Earth.",
        "exampleBn": "মারিয়ানা খাত পৃথিবীর গভীরতম প্রান্তসীমা রহস্যময় হেডাল অঞ্চলে গিয়ে পৌঁছেছে।",
        "category": "Science & Environment"
    },
    {
        "word": "Neritic",
        "pos": "Adjective",
        "phonetic": "/nəˈrɪt.ɪk/ (নেরিটিক)",
        "meaningBn": "মহীসোপানের ওপর অবস্থিত অগভীর সমুদ্রাঞ্চলসংক্রান্ত (২০০ মিটার পর্যন্ত)",
        "synonyms": ["Continental shelf waters", "Shallow marine"],
        "antonyms": ["Oceanic", "Pelagic deep"],
        "exampleEn": "The neritic zone supports the vast majority of commercial fishing worldwide.",
        "exampleBn": "মহীসোপানস্থ অগভীর সমুদ্রাঞ্চল বিশ্বজুড়ে সিংহভাগ বাণিজ্যিক মাছ শিকারের যোগান দেয়।",
        "category": "Science & Environment"
    },
    {
        "word": "Planktonic",
        "pos": "Adjective",
        "phonetic": "/plæŋkˈtɒn.ɪk/ (প্ল্যাঙ্কটনিক)",
        "meaningBn": "পানিতে নিজের শক্তিতে নয় বরং স্রোতের সাথে ভেসে চলা অণুজীবাণু সংক্রান্ত",
        "synonyms": ["Drifting", "Floating microscopic"],
        "antonyms": ["Nektonic (free-swimming)", "Benthic"],
        "exampleEn": "Planktonic algae produce roughly half of the oxygen in the Earth's atmosphere.",
        "exampleBn": "স্রোতে ভেসে থাকা শৈবাল প্ল্যাঙ্কটন পৃথিবীর বায়ুমণ্ডলের প্রায় অর্ধেক অক্সিজেন তৈরি করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Nektonic",
        "pos": "Adjective",
        "phonetic": "/nɛkˈtɒn.ɪk/ (নেকটনিক)",
        "meaningBn": "স্রোতের বিপরীতে স্বাধীনভাবে সাঁতার কাটতে সক্ষম জলজ প্রাণীসংক্রান্ত",
        "synonyms": ["Free-swimming", "Active aquatic"],
        "antonyms": ["Planktonic", "Sessile"],
        "exampleEn": "Unlike drifting plankton, nektonic animals like squid and salmon actively propel themselves.",
        "exampleBn": "ভাসমান প্ল্যাঙ্কটনের বিপরীতে স্কুইড এবং স্যামনের মতো সাঁতারু প্রাণীরা সক্রিয়ভাবে চলাচল করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Epiphytic",
        "pos": "Adjective",
        "phonetic": "/ˌɛp.ɪˈfɪt.ɪk/ (এপিফিটিক)",
        "meaningBn": "অন্য গাছের ওপর জন্মায় কিন্তু পরজীবী নয় এমন বায়বীয় পরশ্রয়ী উদ্ভিদসংক্রান্ত",
        "synonyms": ["Air-plant", "Non-parasitic perching"],
        "antonyms": ["Parasitic", "Terrestrial root-bound"],
        "exampleEn": "Orchids and Spanish moss are famous epiphytic plants absorbing moisture from ambient air.",
        "exampleBn": "অর্কিড ও স্প্যানিশ মস হলো বিখ্যাত বায়বীয় উদ্ভিদ যা বাতাস থেকে আর্দ্রতা শোষণ করে বাঁচে।",
        "category": "Science & Environment"
    },
    {
        "word": "Saprophytic",
        "pos": "Adjective",
        "phonetic": "/ˌsæp.roʊˈfɪt.ɪk/ (স্যাপ্রোফিটিক)",
        "meaningBn": "মৃত ও পচা জৈববস্তুর ওপর জন্মায় এমন মৃতজীবী সংক্রান্ত",
        "synonyms": ["Decaying-matter feeding", "Decomposing"],
        "antonyms": ["Autotrophic", "Parasitic"],
        "exampleEn": "Saprophytic fungi break down dead logs on the forest floor, recycling vital nutrients.",
        "exampleBn": "মৃতজীবী ছত্রাক বনের মেঝেতে পড়ে থাকা পচা কাঠ পচিয়ে পুষ্টি উপাদান মাটিতে ফিরিয়ে দেয়।",
        "category": "Science & Environment"
    },
    {
        "word": "Xerophytic",
        "pos": "Adjective",
        "phonetic": "/ˌzɪər.əˈfɪt.ɪk/ (জিরোফিটিক)",
        "meaningBn": "মরুভূমি বা অত্যন্ত শুষ্ক অঞ্চলে বেঁচে থাকতে সক্ষম উদ্ভিদসংক্রান্ত",
        "synonyms": ["Drought-adapted", "Desert-dwelling"],
        "antonyms": ["Hydrophytic", "Mesophytic"],
        "exampleEn": "Cacti possess thick waxy skins and spines as xerophytic adaptations to minimize water loss.",
        "exampleBn": "ক্যাকটাসের পুরু মোমযুক্ত আবরণ এবং কাঁটা হলো পানিক্ষয় কমানোর মরু-অভিযোজন।",
        "category": "Science & Environment"
    },
    {
        "word": "Hydrophytic",
        "pos": "Adjective",
        "phonetic": "/ˌhaɪ.drəˈfɪt.ɪk/ (হাইড্রোফিটিক)",
        "meaningBn": "পানিতে বা অত্যন্ত আর্দ্র কাদায় জন্মানো জলজ উদ্ভিদসংক্রান্ত",
        "synonyms": ["Aquatic plant", "Water-adapted"],
        "antonyms": ["Xerophytic", "Arid"],
        "exampleEn": "Water lilies feature specialized hydrophytic aerenchyma tissues that enable their leaves to float.",
        "exampleBn": "পদ্মফুলের বিশেষ জলজ টিস্যু থাকে যা পাতার পানিতে ভেসে থাকতে সাহায্য করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Halophytic",
        "pos": "Adjective",
        "phonetic": "/ˌhæl.əˈfɪt.ɪk/ (হ্যালোফিটিক)",
        "meaningBn": "লবণাক্ত মাটিতে বা নোনা পানির পরিবেশে টিকে থাকা উদ্ভিদসংক্রান্ত",
        "synonyms": ["Salt-tolerant", "Saline-adapted"],
        "antonyms": ["Glycophytic", "Salt-intolerant"],
        "exampleEn": "Mangrove trees display extraordinary halophytic mechanisms to excrete excess salt through their foliage.",
        "exampleBn": "ম্যানগ্রোভ গাছে পাতার মাধ্যমে অতিরিক্ত লবণ বের করে দেওয়ার মতো অসাধারণ লবণসহিষ্ণু ক্ষমতা রয়েছে।",
        "category": "Science & Environment"
    },
    {
        "word": "Mesophytic",
        "pos": "Adjective",
        "phonetic": "/ˌmɛs.əˈfɪt.ɪk/ (মেসোফিটিক)",
        "meaningBn": "মাঝারি পরিমিত পানি ও আর্দ্রতাপূর্ণ পরিবেশে স্বাভাবিকভাবে জন্মায় এমন উদ্ভিদসংক্রান্ত",
        "synonyms": ["Moderate-moisture adapted"],
        "antonyms": ["Xerophytic", "Hydrophytic"],
        "exampleEn": "Most agricultural crops, such as wheat and corn, are mesophytic plants requiring moderate rainfall.",
        "exampleBn": "গম ও ভুট্টার মতো অধিকাংশ কৃষিজ ফসল হলো পরিমিত আর্দ্রতাপ্রেমী উদ্ভিদ।",
        "category": "Science & Environment"
    },
    {
        "word": "Coniferous",
        "pos": "Adjective",
        "phonetic": "/koʊˈnɪf.ər.əs/ (কোনিফেরাস)",
        "meaningBn": "মোচাকৃতির ফল ও সুচালো পাতাবিশিষ্ট সরলবর্গীয় চিরহরিৎ বৃক্ষসংক্রান্ত",
        "synonyms": ["Cone-bearing", "Needle-leaved", "Evergreen pine"],
        "antonyms": ["Deciduous", "Broad-leaved"],
        "exampleEn": "Dense coniferous forests of pine and spruce dominate the subarctic taiga biome.",
        "exampleBn": "পাইন ও স্প্রুসের মতো ঘন সরলবর্গীয় বনাঞ্চল উপ-সুমেরু তৈগা অঞ্চল জুড়ে বিস্তৃত।",
        "category": "Science & Environment"
    },
    {
        "word": "Arboreal",
        "pos": "Adjective",
        "phonetic": "/ɑːrˈbɔːr.i.əl/ (আর্বোরিয়াল)",
        "meaningBn": "গাছে বসবাসকারী বা গাছে চলাফেরায় অভ্যস্ত প্রাণীসংক্রান্ত",
        "synonyms": ["Tree-dwelling", "Tree-climbing"],
        "antonyms": ["Terrestrial", "Fossorial", "Aquatic"],
        "exampleEn": "Monkeys and tree frogs are classic examples of arboreal creatures adapted with prehensile grips.",
        "exampleBn": "বানর ও গেছো ব্যাঙ হলো শক্ত মুঠোযুক্ত গাছে বসবাসকারী বৃক্ষচর প্রাণীর চিরায়ত উদাহরণ।",
        "category": "Science & Environment"
    },
    {
        "word": "Fossorial",
        "pos": "Adjective",
        "phonetic": "/fɒˈsɔːr.i.əl/ (ফসোরাল)",
        "meaningBn": "মাটি খুঁড়ে গর্তে বসবাসকারী বা খননে পারদর্শী প্রাণীসংক্রান্ত",
        "synonyms": ["Burrowing", "Subterranean digger"],
        "antonyms": ["Cursorial", "Arboreal", "Volant"],
        "exampleEn": "Moles have powerful, spade-like forepaws adapted for a fossorial lifestyle beneath the lawn.",
        "exampleBn": "লনের নিচে গর্ত খুঁড়ে বসবাসের জন্য মোলের সামনের পা বেলচার মতো শক্তিশালী হয়ে থাকে।",
        "category": "Science & Environment"
    },
    {
        "word": "Cursorial",
        "pos": "Adjective",
        "phonetic": "/kɜːrˈsɔːr.i.əl/ (কারসোরিয়াল)",
        "meaningBn": "দ্রুত দৌড়াতে বা স্থলভাগে দ্রুত ছুটতে অভ্যস্ত প্রাণীসংক্রান্ত",
        "synonyms": ["Adapted for running", "Fast-running terrestrial"],
        "antonyms": ["Fossorial", "Sessile", "Arboreal"],
        "exampleEn": "Cheetahs and ostriches possess specialized cursorial limb structures designed for blazing speed.",
        "exampleBn": "চিতাবাঘ ও উটপাখির অঙ্গপ্রত্যঙ্গ তীব্র গতিতে দৌড়ানোর উপযোগী দৌড়বাজ গঠন দ্বারা নির্মিত।",
        "category": "Science & Environment"
    },
    {
        "word": "Volant",
        "pos": "Adjective",
        "phonetic": "/ˈvoʊ.lənt/ (ভোল্যান্ট)",
        "meaningBn": "উড়তে সক্ষম; ডানার সাহায্যে আকাশে উড়ন্ত",
        "synonyms": ["Capable of flight", "Flying", "Airborne"],
        "antonyms": ["Flightless", "Ground-dwelling"],
        "exampleEn": "Bats are the only mammals endowed with true powered volant locomotion.",
        "exampleBn": "বাদুড় হলো একমাত্র স্তন্যপায়ী প্রাণী যাদের সত্যি সত্যি ওড়ার ডানাবিশিষ্ট সক্ষমতা রয়েছে।",
        "category": "Science & Environment"
    },
    {
        "word": "Saltatorial",
        "pos": "Adjective",
        "phonetic": "/ˌsæl.təˈtɔːr.i.əl/ (সালটাটোরিয়াল)",
        "meaningBn": "লাফাতে বা লম্ফ দিয়ে চলতে অভ্যস্ত প্রাণীসংক্রান্ত",
        "synonyms": ["Hopping-adapted", "Leaping", "Saltatory"],
        "antonyms": ["Crawling", "Cursorial"],
        "exampleEn": "Grasshoppers and kangaroos display saltatorial hind legs capable of explosive jumps.",
        "exampleBn": "ঘাসফড়িং এবং ক্যাঙ্গারুর পেছনের পাগুলো তীব্র লম্ফ দেওয়ার জন্য লাফানো উপযোগী হয়।",
        "category": "Science & Environment"
    },
    {
        "word": "Natatorial",
        "pos": "Adjective",
        "phonetic": "/ˌneɪ.təˈtɔːr.i.əl/ (ন্যাটাটোরিয়াল)",
        "meaningBn": "সাঁতার কাটতে পারদর্শী বা জলজ সাঁতারবান্ধব অঙ্গযুক্ত",
        "synonyms": ["Swimming-adapted", "Webbed aquatic"],
        "antonyms": ["Cursorial", "Terrestrial"],
        "exampleEn": "Ducks possess webbed feet that serve as efficient natatorial paddles.",
        "exampleBn": "হাঁসের লিপ্তপদী পা সাঁতার কাটার চমৎকার দাঁড় হিসেবে কাজ করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Estivation",
        "pos": "Noun",
        "phonetic": "/ˌɛs.tɪˈveɪ.ʃən/ (এসটিভেশন)",
        "meaningBn": "গ্রীষ্মনিদ্রা; প্রচণ্ড গরম ও খরার সময় প্রাণীদের দীর্ঘকালীন নিষ্ক্রিয় বিশ্রাম",
        "synonyms": ["Summer dormancy", "Aestivation"],
        "antonyms": ["Hibernation", "Active wakefulness"],
        "exampleEn": "Desert snails enter estivation inside their shells during the scorching summer months.",
        "exampleBn": "মরুভূমির শামুকেরা প্রখর গ্রীষ্মের মাসগুলোতে খোলসের ভেতরে গ্রীষ্মনিদ্রায় চলে যায়।",
        "category": "Science & Environment"
    },
    {
        "word": "Brumation",
        "pos": "Noun",
        "phonetic": "/bruːˈmeɪ.ʃən/ (ব্রুমেশন)",
        "meaningBn": "শীতকালে সরীসৃপ প্রাণীদের বিপাকীয় নিষ্ক্রিয়তা বা শীতকালীন বিশ্রাম",
        "synonyms": ["Reptilian dormancy", "Cold-blooded hibernation"],
        "antonyms": ["Active thermoregulation"],
        "exampleEn": "Turtles undergo brumation submerged beneath the mud of frozen ponds until spring.",
        "exampleBn": "কচ্ছপেরা বসন্ত না আসা পর্যন্ত জমে যাওয়া পুকুরের কাদার নিচে শীতকালীন বিশ্রামে কাটায়।",
        "category": "Science & Environment"
    },
    {
        "word": "Torpor",
        "pos": "Noun",
        "phonetic": "/ˈtɔːr.pər/ (টরপর)",
        "meaningBn": "অলস স্থবিরতা; শক্তি বাঁচাতে প্রাণীর সাময়িক নিষ্ক্রিয় শারীরবৃত্তীয় অবস্থা",
        "synonyms": ["Lethargy", "Sluggishness", "Suspended animation", "Stupor"],
        "antonyms": ["Vigor", "Animation", "Liveliness"],
        "exampleEn": "Hummingbirds drop into overnight torpor to conserve crucial metabolic energy.",
        "exampleBn": "হামিংবার্ডরা জরুরি বিপাকীয় শক্তি সঞ্চয় করতে রাতের বেলা সাময়িক শারীরিক স্থবিরতায় চলে যায়।",
        "category": "Science & Environment"
    },
    {
        "word": "Cryptobiosis",
        "pos": "Noun",
        "phonetic": "/ˌkrɪp.toʊ.baɪˈoʊ.sɪs/ (ক্রিপ্টোবায়োসিস)",
        "meaningBn": "প্রতিকূল পরিবেশে প্রাণীর জীবনের সকল বাহ্যিক লক্ষণ সাময়িক স্তব্ধ রেখে টিকে থাকার ক্ষমতা",
        "synonyms": ["Suspended life", "Anabiosis", "Extreme dormancy"],
        "antonyms": ["Active metabolism", "Death"],
        "exampleEn": "Tardigrades can withstand outer space radiation by entering deep cryptobiosis.",
        "exampleBn": "টারডিগ্রেড চরম শারীরিক নিষ্ক্রিয়তায় গিয়ে মহাকাশের বিপজ্জনক তেজস্ক্রিয়তার মধ্যেও টিকে থাকতে পারে।",
        "category": "Science & Environment"
    },
    {
        "word": "Diapause",
        "pos": "Noun",
        "phonetic": "/ˈdaɪ.əˌpɔːz/ (ডায়াপজ)",
        "meaningBn": "পতঙ্গের ভ্রূণ বা লার্ভার বৃদ্ধি ও বিকাশের সাময়িক স্থগিতাবস্থা",
        "synonyms": ["Developmental delay", "Insect latency"],
        "antonyms": ["Active metamorphosis"],
        "exampleEn": "Silkworm eggs remain in diapause through harsh winters before hatching in spring.",
        "exampleBn": "রেশমকীটের ডিম তীব্র শীতে বৃদ্ধি স্থগিত রেখে বসন্তকালে ফুটে বের হয়।",
        "category": "Science & Environment"
    },
    {
        "word": "Phenology",
        "pos": "Noun",
        "phonetic": "/fɪˈnɒl.ə.dʒi/ (ফেনোলজি)",
        "meaningBn": "ঋতু পরিবর্তনের সাথে সাথে উদ্ভিদ ও প্রাণীর জীবনচক্রের সময়কালসংক্রান্ত বিজ্ঞান",
        "synonyms": ["Seasonal biology", "Periodic natural events study"],
        "antonyms": ["Static morphology"],
        "exampleEn": "Botanists track tree flowering dates through phenology to measure the impact of global warming.",
        "exampleBn": "বিশ্ব উষ্ণায়নের প্রভাব মাপতে উদ্ভিদবিদরা গাছে ফুল ফোটার সময়কাল ঋতুবিজ্ঞানের মাধ্যমে পর্যবেক্ষণ করেন।",
        "category": "Science & Environment"
    },
    {
        "word": "Taxidermy",
        "pos": "Noun",
        "phonetic": "/ˈtæk.sɪˌdɜːr.mi/ (ট্যাক্সিডার্মি)",
        "meaningBn": "মৃত পশুপাখির চামড়া ছাড়িয়ে অবিকল জীবন্ত রূপ দিয়ে সাজিয়ে রাখার শিল্প",
        "synonyms": ["Animal preservation", "Mounting of skins"],
        "antonyms": ["Cremation", "Skeleton articulation"],
        "exampleEn": "The natural history museum exhibits masterful taxidermy specimens of extinct birds.",
        "exampleBn": "প্রাকৃতিক ইতিহাস জাদুঘরটিতে বিলুপ্ত পাখিদের নিখুঁতভাবে সংরক্ষিত জীবন্ত মডেল প্রদর্শিত আছে।",
        "category": "Literature & Arts"
    },
    {
        "word": "Phylogeny",
        "pos": "Noun",
        "phonetic": "/faɪˈlɒdʒ.ə.ni/ (ফাইলোজেনি)",
        "meaningBn": "জীব প্রজাতির বিবর্তনমূলক ইতিহাস ও বংশগতির উৎসরেখা",
        "synonyms": ["Evolutionary genealogy", "Ancestral lineage"],
        "antonyms": ["Ontogeny (individual development)"],
        "exampleEn": "DNA sequencing has clarified the complex phylogeny of early mammalian ancestors.",
        "exampleBn": "ডিএনএ সিকোয়েন্সিং আদিম স্তন্যপায়ী পূর্বপুরুষদের জটিল বিবর্তনমূলক ইতিহাস স্পষ্ট করেছে।",
        "category": "Science & Environment"
    },
    {
        "word": "Ontogeny",
        "pos": "Noun",
        "phonetic": "/ɒnˈtɒdʒ.ə.ni/ (অনটোজেনি)",
        "meaningBn": "নিষেক থেকে পূর্ণাঙ্গ রূপ পর্যন্ত একক জীবের বৃদ্ধি ও বিকাশের ইতিহাস",
        "synonyms": ["Individual development", "Organismal life history"],
        "antonyms": ["Phylogeny (species evolution)"],
        "exampleEn": "Embryologists study the ontogeny of the brain from initial neural tube formation.",
        "exampleBn": "ভ্রূণতত্ত্ববিদরা প্রাথমিক নিউরাল টিউব গঠন থেকে মস্তিষ্কের একক শারীরিক বিকাশের ইতিহাস পর্যালোচনা করেন।",
        "category": "Science & Environment"
    },
    {
        "word": "Speciation",
        "pos": "Noun",
        "phonetic": "/ˌspiː.ʃiˈeɪ.ʃən/ (স্পিসিয়েশন)",
        "meaningBn": "বিবর্তন প্রক্রিয়ায় এক প্রজাতি থেকে সম্পূর্ণ নতুন প্রজাতির উৎপত্তি",
        "synonyms": ["Species formation", "Evolutionary divergence"],
        "antonyms": ["Extinction", "Convergence"],
        "exampleEn": "Geographic separation on Darwin's finches fostered rapid adaptive speciation.",
        "exampleBn": "ভৌগোলিক বিচ্ছিন্নতা ডারউইনের ফিঞ্চ পাখিদের মধ্যে দ্রুত নতুন প্রজাতির জন্ম দিয়েছিল।",
        "category": "Science & Environment"
    },
    {
        "word": "Sympatric",
        "pos": "Adjective",
        "phonetic": "/sɪmˈpæt.rɪk/ (সিমপ্যাট্রিক)",
        "meaningBn": "ভৌগোলিক বিচ্ছিন্নতা ছাড়াই একই অঞ্চলে বসবাসরত প্রজাতির বিবর্তনসংক্রান্ত",
        "synonyms": ["Same-area speciation", "Overlapping habitat"],
        "antonyms": ["Allopatric"],
        "exampleEn": "Cichlid fishes in the crater lake underwent sympatric speciation despite sharing the exact same waters.",
        "exampleBn": "একই হ্রদের পানিতে বাস করা সত্ত্বেও সিচলিড মাছেরা একই এলাকায় থেকেই নতুন প্রজাতিতে বিভক্ত হয়েছিল।",
        "category": "Science & Environment"
    },
    {
        "word": "Allopatric",
        "pos": "Adjective",
        "phonetic": "/ˌæl.əˈpæt.rɪk/ (অ্যালোপ্যাট্রিক)",
        "meaningBn": "পাহাড় বা নদীর মতো ভৌগোলিক বাধার কারণে বিচ্ছিন্ন হয়ে নতুন প্রজাতি গঠনসংক্রান্ত",
        "synonyms": ["Geographically isolated", "Separated habitat"],
        "antonyms": ["Sympatric"],
        "exampleEn": "The formation of the Grand Canyon led to allopatric divergence between two squirrel populations.",
        "exampleBn": "গ্র্যান্ড ক্যানিয়ন সৃষ্টি হওয়ার ফলে দুই পাড়ের কাঠবিড়ালি ভৌগোলিক বিচ্ছিন্নতায় ভিন্ন প্রজাতিতে পরিণত হয়।",
        "category": "Science & Environment"
    },
    {
        "word": "Endemism",
        "pos": "Noun",
        "phonetic": "/ˈɛn.dəˌmɪz.əm/ (এনডেমিজম)",
        "meaningBn": "কোনো জীবপ্রজাতির নির্দিষ্ট একটি ভৌগোলিক এলাকার বাইরে অন্য কোথাও না পাওয়ার অনন্যতা",
        "synonyms": ["Native exclusivity", "Ecological restriction"],
        "antonyms": ["Cosmopolitan distribution", "Ubiquity"],
        "exampleEn": "Madagascar boasts astonishing levels of endemism, with 90 percent of its wildlife found nowhere else.",
        "exampleBn": "মাদাগাস্কারের ৯০ শতাংশ প্রাণী পৃথিবীর আর কোথাও না পাওয়া অঞ্চল-নির্দিষ্ট অনন্যতার দাবিদার।",
        "category": "Science & Environment"
    },
    {
        "word": "Bioluminescence",
        "pos": "Noun",
        "phonetic": "/ˌbaɪ.oʊˌluː.mɪˈnɛs.əns/ (বায়োলুমিনেসেন্স)",
        "meaningBn": "জৈবরাসায়নিক বিক্রিয়ার মাধ্যমে জীবদেহে আলো উৎপাদনের ক্ষমতা (যেমন জোনাকির আলো)",
        "synonyms": ["Living light", "Biological light emission"],
        "antonyms": ["Darkness", "Inorganic phosphorescence"],
        "exampleEn": "Deep-sea anglerfish use bioluminescence to lure prey into their jaws in complete darkness.",
        "exampleBn": "গভীর সমুদ্রের মাছেরা ঘুটঘুটে অন্ধকারে শিকারকে আকৃষ্ট করতে দেহ নিঃসৃত আলো ব্যবহার করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Bioaccumulation",
        "pos": "Noun",
        "phonetic": "/ˌbaɪ.oʊ.əˌkjuː.mjəˈleɪ.ʃən/ (বায়োঅ্যাকিউমুলেশন)",
        "meaningBn": "জীবদেহে সময়ের সাথে ক্ষতিকর বিষাক্ত পদার্থ বা রাসায়নিক জমা হওয়ার প্রক্রিয়া",
        "synonyms": ["Toxin buildup", "Chemical accumulation"],
        "antonyms": ["Bio-elimination", "Detoxification"],
        "exampleEn": "Bioaccumulation of methylmercury in predatory tuna poses serious health risks for consumers.",
        "exampleBn": "শিকারি টুনা মাছের শরীরে মিথাইলমার্কারির বিষাক্ত জমাট বাঁধা ভক্ষণকারীদের জন্য মারাত্মক স্বাস্থ্যঝুঁকি তৈরি করে।",
        "category": "Science & Environment"
    },
    {
        "word": "Biomagnification",
        "pos": "Noun",
        "phonetic": "/ˌbaɪ.oʊˌmæɡ.nɪ.fɪˈkeɪ.ʃən/ (বায়োম্যাগনিফিকেশন)",
        "meaningBn": "খাদ্যশৃঙ্খলের এক ধাপ থেকে পরবর্তী উচ্চতর ধাপে ক্ষতিকর বিষাক্ত পদার্থের ঘনত্ব বৃদ্ধি",
        "synonyms": ["Food-chain concentration", "Biological amplification"],
        "antonyms": ["Biodilution"],
        "exampleEn": "Due to biomagnification, apex predators like bald eagles had eggshells thinned by pesticides.",
        "exampleBn": "খাদ্যশৃঙ্খলে বিষের ঘনত্ব বৃদ্ধির ফলে ঈগলের মতো শীর্ষ শিকারী পাখির ডিমের খোসা কীটনাশকে পাতলা হয়ে গিয়েছিল।",
        "category": "Science & Environment"
    },
    {
        "word": "Eutrophication",
        "pos": "Noun",
        "phonetic": "/juːˌtrɒf.ɪˈkeɪ.ʃən/ (ইউট্রোফিকেশন)",
        "meaningBn": "অতিরিক্ত সার বা পুষ্টির ফলে জলাশয়ে শৈবালের অতিরিক্ত বৃদ্ধি ও অক্সিজেনের মারাত্মক ঘাটতি",
        "synonyms": ["Nutrient enrichment", "Algal bloom depletion"],
        "antonyms": ["Oligotrophication"],
        "exampleEn": "Fertilizer runoff caused severe eutrophication in the estuary, creating a dead zone devoid of fish.",
        "exampleBn": "সারের অতিরিক্ত পানির প্রবাহ মোহনায় মারাত্মক পুষ্টি-বিস্ফোরণ ঘটিয়ে মাছশূন্য নিথর এলাকা তৈরি করেছিল।",
        "category": "Science & Environment"
    },
    {
        "word": "Bioremediation",
        "pos": "Noun",
        "phonetic": "/ˌbaɪ.oʊ.rɪˌmiː.diˈeɪ.ʃən/ (বায়োরিমেডিয়েশন)",
        "meaningBn": "দূষিত মাটি বা পানি পরিষ্কারে ব্যাকটেরিয়া ও অণুজীবের ব্যবহার",
        "synonyms": ["Biological cleanup", "Microbial pollutant breakdown"],
        "antonyms": ["Chemical pollution", "Contamination"],
        "exampleEn": "Engineers employed bioremediation to break down petroleum spills on the rocky shoreline.",
        "exampleBn": "পাথুরে উপকূলে তেলের দাগ ভেঙে পরিষ্কার করতে প্রকৌশলীরা অণুজীবভিত্তিক প্রতিকার পদ্ধতি ব্যবহার করেছিলেন।",
        "category": "Science & Environment"
    },
    {
        "word": "Amensalism",
        "pos": "Noun",
        "phonetic": "/eɪˈmɛn.səl.ɪz.əm/ (অ্যামেনসালিজম)",
        "meaningBn": "এমন এক জৈব সম্পর্ক যেখানে এক পক্ষ ক্ষতিগ্রস্ত হয় কিন্তু অন্য পক্ষের কোনো লাভ বা ক্ষতি হয় না",
        "synonyms": ["Asymmetrical inhibition", "One-sided harm"],
        "antonyms": ["Mutualism", "Symbiosis"],
        "exampleEn": "The black walnut tree exhibits amensalism by secreting juglone that stunts neighboring crops without benefiting the tree directly.",
        "exampleBn": "আখরোট গাছ এমন রস নিঃসরণ করে যা পাশের গাছের ক্ষতি করে অথচ আখরোটের কোনো অতিরিক্ত লাভ হয় না—এটি অ্যামেনসালিজম।",
        "category": "Science & Environment"
    },
    {
        "word": "Teleology",
        "pos": "Noun",
        "phonetic": "/ˌtiː.liˈɒl.ə.dʒi/ (টেলিওলজি)",
        "meaningBn": "জগৎ বা কোনো বিষয়ের চূড়ান্ত উদ্দেশ্য বা পরিণাম সংক্রান্ত দার্শনিক তত্ত্ব",
        "synonyms": ["Doctrine of final purpose", "Final causes study"],
        "antonyms": ["Mechanism", "Dysteleology", "Random chance"],
        "exampleEn": "Aristotelian physics relied heavily on teleology, asserting that acorns naturally aim to become oak trees.",
        "exampleBn": "অ্যারিস্টটলের পদার্থবিদ্যা চূড়ান্ত উদ্দেশ্যের তত্ত্বে বিশ্বাসী ছিল যে ওক ফলের জন্ম ওক গাছ হওয়াই চূড়ান্ত লক্ষ্য।",
        "category": "Philosophy & Ethics"
    },
    {
        "word": "Axiology",
        "pos": "Noun",
        "phonetic": "/ˌæk.siˈɒl.ə.dʒi/ (অ্যাক্সিওলজি)",
        "meaningBn": "মূল্যবোধ, নৈতিকতা ও সৌন্দর্যের প্রকৃতিসংক্রান্ত দর্শনশাস্ত্র (মূল্যতত্ত্ব)",
        "synonyms": ["Theory of value", "Value philosophy"],
        "antonyms": ["Ontology (being focus)", "Epistemology"],
        "exampleEn": "Axiology encompasses both moral ethics and aesthetics to analyze what humans truly treasure.",
        "exampleBn": "মূল্যতত্ত্ব মানুষ কিসের প্রকৃত কদর করে তা বিশ্লেষণ করতে নীতিশাস্ত্র এবং নন্দনতত্ত্ব উভয়কেই ধারণ করে।",
        "category": "Philosophy & Ethics"
    },
    {
        "word": "Deontology",
        "pos": "Noun",
        "phonetic": "/ˌdiː.ɒnˈtɒl.ə.dʒi/ (ডিওন্টোলজি)",
        "meaningBn": "ফলাফলের তোয়াক্কা না করে অলঙ্ঘনীয় কর্তব্য ও নিয়ম পালনের ওপর প্রতিষ্ঠিত নীতিশাস্ত্র",
        "synonyms": ["Duty-based ethics", "Kantian ethics", "Moral obligation"],
        "antonyms": ["Consequentialism", "Utilitarianism"],
        "exampleEn": "In Kantian deontology, lying is strictly impermissible even if telling a lie produces a beneficial outcome.",
        "exampleBn": "কান্টীয় কর্তব্যভিত্তিক নীতিশাস্ত্রে মিথ্যা বলা কঠোরভাবে নিষিদ্ধ, এমনকি মিথ্যা কোনো ভালো ফল আনলেও।",
        "category": "Philosophy & Ethics"
    },
    {
        "word": "Consequentialism",
        "pos": "Noun",
        "phonetic": "/ˌkɒn.sɪˈkwɛn.ʃəl.ɪz.əm/ (কনসিকোয়েনশিয়ালিজম)",
        "meaningBn": "কাজের ভালো-মন্দ কেবল তার ফলাফলের ওপর নির্ভর করে—এই নৈতিক মতবাদ",
        "synonyms": ["Result-oriented ethics", "Teleological ethics", "Utilitarianism"],
        "antonyms": ["Deontology", "Absolutism"],
        "exampleEn": "Consequentialism judges actions solely by the overall happiness or suffering they produce.",
        "exampleBn": "ফলাফলবাদী নীতিশাস্ত্র কোনো কাজকে কেবল তা কতটুকু সামগ্রিক সুখ বা দুঃখ বয়ে এনেছে তার ভিত্তিতে বিচার করে।",
        "category": "Philosophy & Ethics"
    },
    {
        "word": "Individuation",
        "pos": "Noun",
        "phonetic": "/ˌɪn.dɪˌvɪdʒ.uˈeɪ.ʃən/ (ইনডিভিজুয়েশন)",
        "meaningBn": "অজ্ঞান ও সচেতন মনের মেলবন্ধনে একজন পরিপূর্ণ স্বতন্ত্র মানুষে রূপান্তরের মনস্তাত্ত্বিক প্রক্রিয়া",
        "synonyms": ["Self-realization", "Psychological wholeness", "Integration"],
        "antonyms": ["Dissociation", "Alienation"],
        "exampleEn": "Carl Jung viewed individuation as the central lifelong journey of discovering one's authentic self.",
        "exampleBn": "কার্ল ইয়ুং ব্যক্তিকরণ বা আত্মিক পূর্ণতাকে নিজের আসল সত্তা আবিষ্কারের আজীবন সাধনা হিসেবে গণ্য করেছেন।",
        "category": "Philosophy & Ethics"
    },
    {
        "word": "Synchronicity",
        "pos": "Noun",
        "phonetic": "/ˌsɪŋ.krəˈnɪs.ə.ti/ (সিনক্রোনিসিটি)",
        "meaningBn": "কার্যকারণ সম্পর্কহীন কিন্তু অর্থপূর্ণ তাৎপর্যপূর্ণ সমাপতন",
        "synonyms": ["Meaningful coincidence", "Acausal connection"],
        "antonyms": ["Pure randomness", "Cause-and-effect"],
        "exampleEn": "Meeting her childhood mentor on a remote foreign mountain seemed an uncanny act of synchronicity.",
        "exampleBn": "একটি দুর্গম বিদেশি পাহাড়ে শৈশবের শিক্ষকের সাথে দেখা হয়ে যাওয়াকে অর্থপূর্ণ সমাপতন বলে মনে হয়েছিল।",
        "category": "Philosophy & Ethics"
    }
]

with open('next_part3_sub1.json', 'w', encoding='utf-8') as f:
    json.dump(batch3_sub1, f, ensure_ascii=False, indent=2)
print("Part 3 sub 1 written:", len(batch3_sub1))
