# -*- coding: utf-8 -*-
import json

batch1_words = [
    {
        "word": "Catachresis",
        "pos": "Noun",
        "phonetic": "/ˌkæt.əˈkriː.sɪs/ (ক্যাটাক্রিসিস)",
        "meaningBn": "শব্দের ভুল বা অসঙ্গত অলঙ্কারিক প্রয়োগ; অপপ্রয়োগ",
        "synonyms": ["Misapplication", "Abuse of words", "Solecism"],
        "antonyms": ["Proper usage", "Correct diction"],
        "exampleEn": "The poet was criticized for catachresis when he described sound as being visually blinding.",
        "exampleBn": "শব্দকে দৃষ্টিহীন করে দেওয়ার মতো অলঙ্কারিক অপপ্রয়োগের জন্য কবির সমালোচনা করা হয়েছিল।",
        "category": "Literature & Arts"
    },
    {
        "word": "Anacoluthon",
        "pos": "Noun",
        "phonetic": "/ˌæn.ə.kəˈluː.θɒn/ (অ্যানাকোলুথন)",
        "meaningBn": "বাক্য গঠনের মাঝপথে ব্যাকরণগত ধারাবাহিকতার আকস্মিক পরিবর্তন",
        "synonyms": ["Grammatical shift", "Syntactic discontinuity"],
        "antonyms": ["Syntactic coherence", "Smooth continuity"],
        "exampleEn": "Spoken conversation often contains anacoluthon because thoughts change mid-sentence.",
        "exampleBn": "কথোপকথনে প্রায়ই বাক্যরীতির আকস্মিক পরিবর্তন ঘটে কারণ কথা বলতে বলতে ভাবনা বদলে যায়।",
        "category": "Literature & Arts"
    },
    {
        "word": "Aposiopesis",
        "pos": "Noun",
        "phonetic": "/ˌæp.əˌsaɪ.əˈpiː.sɪs/ (অ্যাপোসায়োপিসিস)",
        "meaningBn": "আবেগে বা ইচ্ছাকৃতভাবে বাক্যের অসমাপ্ত ইতি টানা",
        "synonyms": ["Sudden breaking off", "Speech pause"],
        "antonyms": ["Complete utterance", "Conclusion"],
        "exampleEn": "Overcome with sudden rage, he ended his warning with an aposiopesis: 'If you dare step foot here again...!'",
        "exampleBn": "তীব্র ক্রোধের বশবর্তী হয়ে সে অসমাপ্ত বাক্যেই হুমকি দিল: 'যদি আর কখনো এখানে পা রাখো...!'",
        "category": "Literature & Arts"
    },
    {
        "word": "Zeugma",
        "pos": "Noun",
        "phonetic": "/ˈzjuːɡ.mə/ (জিউগমা)",
        "meaningBn": "একই ক্রিয়াপদ দিয়ে দুই ভিন্ন অর্থের পদের সংযোগ স্থাপনকারী অলঙ্কার",
        "synonyms": ["Syllepsis", "Yoking figure"],
        "antonyms": ["Repetitive syntax"],
        "exampleEn": "The diplomat broke the silence and the treaty in a brilliant zeugma.",
        "exampleBn": "কূটনীতিক নীরবতা এবং চুক্তি উভয়েই ভঙ্গ করলেন—যা একটি চমৎকার জিউগমা অলঙ্কার।",
        "category": "Literature & Arts"
    },
    {
        "word": "Chiasmus",
        "pos": "Noun",
        "phonetic": "/kaɪˈæz.məs/ (কায়াজমাস)",
        "meaningBn": "বাক্যাংশের বিপরীতমুখী রূপান্তরযুক্ত অলঙ্কার",
        "synonyms": ["Inverted parallelism", "Criss-cross structure"],
        "antonyms": ["Direct parallelism"],
        "exampleEn": "'Never let a Fool Kiss You or a Kiss Fool You' is a classic chiasmus.",
        "exampleBn": "'কখনও কোনো নির্বোধকে তোমাকে চুম্বন করতে দিও না, কিংবা চুম্বনকে তোমার বুদ্ধিভ্রষ্ট করতে দিও না' একটি চিরায়ত কায়াজমাস।",
        "category": "Literature & Arts"
    },
    {
        "word": "Asyndeton",
        "pos": "Noun",
        "phonetic": "/əˈsɪn.də.tɒn/ (অ্যাসিন্ডেটন)",
        "meaningBn": "বাক্যে সংযোজক অব্যয় (conjunction) বর্জন করার রীতি",
        "synonyms": ["Omission of conjunctions", "Concise listing"],
        "antonyms": ["Polysyndeton"],
        "exampleEn": "Julius Caesar's famous phrase 'I came, I saw, I conquered' is an example of asyndeton.",
        "exampleBn": "জুলিয়াস সিজারের বিখ্যাত উক্তি 'এলাম, দেখলাম, জয় করলাম' হলো অব্যয়হীন বাক্যরীতির উদাহরণ।",
        "category": "Literature & Arts"
    },
    {
        "word": "Polysyndeton",
        "pos": "Noun",
        "phonetic": "/ˌpɒl.iˈsɪn.də.tɒn/ (পলিসিন্ডেটন)",
        "meaningBn": "বাক্যে ঘন ঘন সংযোজক অব্যয়ের পুনরাবৃত্তি",
        "synonyms": ["Conjunction repetition"],
        "antonyms": ["Asyndeton"],
        "exampleEn": "The child spoke with polysyndeton: 'We ran and laughed and ate candy and fell asleep.'",
        "exampleBn": "শিশুটির কথায় অব্যয়ের পুনরাবৃত্তি ছিল: 'আমরা দৌড়ালাম এবং হাসলাম এবং মিষ্টি খেলাম এবং ঘুমিয়ে পড়লাম।'",
        "category": "Literature & Arts"
    },
    {
        "word": "Epistrophe",
        "pos": "Noun",
        "phonetic": "/ɪˈpɪs.trə.fi/ (এপিস্ট্রোফি)",
        "meaningBn": "একাধিক বাক্যাংশ বা বাক্যের শেষে একই শব্দের পুনরাবৃত্তি",
        "synonyms": ["Epiphora", "Terminal repetition"],
        "antonyms": ["Anaphora"],
        "exampleEn": "'Government of the people, by the people, for the people' employs epistrophe.",
        "exampleBn": "'জনগণের সরকার, জনগণের দ্বারা সরকার, জনগণের জন্য সরকার' উক্তিতে শেষাংশের পুনরাবৃত্তি ব্যবহৃত হয়েছে।",
        "category": "Literature & Arts"
    },
    {
        "word": "Paraprosdokian",
        "pos": "Noun",
        "phonetic": "/ˌpær.ə.prɒzˈdoʊ.ki.ən/ (প্যারাপ্রসডোকিয়ান)",
        "meaningBn": "বাক্যের শেষে অপ্রত্যাশিত বা চমকপ্রদ সমাপ্তি যা পূর্বের ভাবকে আমূল বদলে দেয়",
        "synonyms": ["Surprise ending", "Punchline twist"],
        "antonyms": ["Predictable ending", "Expected finish"],
        "exampleEn": "'I've had a wonderful evening, but this wasn't it' is an amusing paraprosdokian.",
        "exampleBn": "'আমার সন্ধ্যাটি দারুণ কেটেছে, তবে এই সন্ধ্যাটি নয়' একটি মজাদার অপ্রত্যাশিত সমাপ্তিযুক্ত বাক্য।",
        "category": "Literature & Arts"
    },
    {
        "word": "Hypallage",
        "pos": "Noun",
        "phonetic": "/haɪˈpæl.ə.dʒi/ (হাইপ্যালাজি)",
        "meaningBn": "বিশেষণের স্থান পরিবর্তনজনিত অলঙ্কার (transferred epithet)",
        "synonyms": ["Transferred epithet", "Syntactic displacement"],
        "antonyms": ["Literal modifier"],
        "exampleEn": "The phrase 'sleepless night' is a hypallage, as the person was sleepless, not the night.",
        "exampleBn": "'নির্ঘুম রাত' পদবন্ধটি একটি স্থানান্তরিত বিশেষণের উদাহরণ, কারণ রাত নয় মানুষটি নির্ঘুম ছিল।",
        "category": "Literature & Arts"
    },
    {
        "word": "Tmesis",
        "pos": "Noun",
        "phonetic": "/təˈmiː.sɪs/ (টিমেসিস)",
        "meaningBn": "যৌগিক শব্দের মাঝে অন্য কোনো শব্দ গুঁজে দেওয়ার রীতি",
        "synonyms": ["Word intercalation", "Infixation"],
        "antonyms": ["Compounding"],
        "exampleEn": "Informal expressions like 'abso-bloody-lutely' are everyday examples of tmesis.",
        "exampleBn": "শব্দের মাঝে অতিরিক্ত শব্দ ঢুকিয়ে জোর দেওয়ার ঘটনা হলো টিমেসিস।",
        "category": "Literature & Arts"
    },
    {
        "word": "Anastrophe",
        "pos": "Noun",
        "phonetic": "/əˈnæs.trə.fi/ (অ্যানাস্ট্রোফি)",
        "meaningBn": "শব্দ বা পদের স্বাভাবিক ব্যাকরণিক ক্রমের উল্টাপাল্টা বিন্যাস",
        "synonyms": ["Inversion", "Syntactic reversal"],
        "antonyms": ["Standard syntax", "Direct order"],
        "exampleEn": "Yoda's famous dialect is full of anastrophe, such as 'Told you I did.'",
        "exampleBn": "স্বাভাবিক পদের ক্রম উল্টে দিয়ে কথা বলা অ্যানাস্ট্রোফির সুস্পষ্ট রূপ।",
        "category": "Literature & Arts"
    },
    {
        "word": "Antiphrasis",
        "pos": "Noun",
        "phonetic": "/ænˈtɪf.rə.sɪs/ (অ্যান্টিফ্রাসিস)",
        "meaningBn": "ব্যঙ্গার্থে শব্দের বিপরীত অর্থে প্রয়োগ",
        "synonyms": ["Ironical usage", "Opposite meaning"],
        "antonyms": ["Literal speech"],
        "exampleEn": "Calling a towering two-meter giant 'Tiny' is an example of antiphrasis.",
        "exampleBn": "দুই মিটার লম্বা কাউকে রসিকতা করে 'খুদে' বলা বিপরীতার্থক শ্লেষ বা অ্যান্টিফ্রাসিস।",
        "category": "Literature & Arts"
    },
    {
        "word": "Hendiadys",
        "pos": "Noun",
        "phonetic": "/hɛnˈdaɪ.ə.dɪs/ (হেন্ডায়াডিস)",
        "meaningBn": "বিশেষণ ও বিশেষ্যের পরিবর্তে দুটি বিশেষ্যকে 'and' দিয়ে যুক্ত করার রীতি",
        "synonyms": ["Coordinate expression", "Dual phrasing"],
        "antonyms": ["Adjectival phrasing"],
        "exampleEn": "'Sound and fury' instead of 'furious sound' is a celebrated hendiadys.",
        "exampleBn": "'উগ্র কোলাহল' না বলে 'শব্দ ও ক্রোধ' বলা একটি বিখ্যাত হেন্ডায়াদিস রূপ।",
        "category": "Literature & Arts"
    },
    {
        "word": "Syllepsis",
        "pos": "Noun",
        "phonetic": "/sɪˈlɛp.sɪs/ (সিলেপসিস)",
        "meaningBn": "একই শব্দের শাব্দিক ও রূপক দ্বৈত প্রয়োগ",
        "synonyms": ["Dual application", "Semantic pun"],
        "antonyms": ["Literal agreement"],
        "exampleEn": "She dropped her phone and her guard at the very same moment.",
        "exampleBn": "সে একই মুহূর্তে তার ফোন এবং মনের সতর্কতা উভয়েই ফেলে দিল।",
        "category": "Literature & Arts"
    },
    {
        "word": "Paronomasia",
        "pos": "Noun",
        "phonetic": "/ˌpær.ə.noʊˈmeɪ.ʒə/ (প্যারোনোমেজিয়া)",
        "meaningBn": "শব্দশ্লেষ বা ধ্বনিসাম্যের ওপর ভিত্তি করে কৌতুকপূর্ণ বাক্যপ্রয়োগ (Pun)",
        "synonyms": ["Wordplay", "Pun", "Quip"],
        "antonyms": ["Literalism", "Direct assertion"],
        "exampleEn": "Shakespeare was renowned for his rapid-fire paronomasia and witty puns.",
        "exampleBn": "শেক্সপিয়র তাঁর চতুর শব্দশ্লেষ ও কৌতুকপূর্ণ বাক্যপ্রয়োগের জন্য সুবিখ্যাত ছিলেন।",
        "category": "Literature & Arts"
    },
    {
        "word": "Anthimeria",
        "pos": "Noun",
        "phonetic": "/ˌæn.θɪˈmɪər.i.ə/ (অ্যান্থিমেরিয়া)",
        "meaningBn": "এক পদের শব্দকে অন্য পদ হিসেবে ব্যবহার (যেমন বিশেষ্যকে ক্রিয়া বানানো)",
        "synonyms": ["Functional shift", "Conversion"],
        "antonyms": ["Fixed part of speech"],
        "exampleEn": "Saying 'Let me Google that' is a modern example of anthimeria turning a noun into a verb.",
        "exampleBn": "'আমাকে গুগল করতে দিন' বলা একটি আধুনিক রূপান্তর যাতে বিশেষ্যকে ক্রিয়া করা হয়েছে।",
        "category": "Literature & Arts"
    },
    {
        "word": "Parataxis",
        "pos": "Noun",
        "phonetic": "/ˌpær.əˈtæk.sɪs/ (প্যারাট্যাক্সিস)",
        "meaningBn": "অধীন বাক্যাংশ ছাড়া কেবল সমান্তরাল প্রধান বাক্য জোড়া লাগানোর শৈলী",
        "synonyms": ["Coordinate style", "Side-by-side phrasing"],
        "antonyms": ["Hypotaxis"],
        "exampleEn": "Ernest Hemingway was celebrated for his minimalist, direct parataxis in prose.",
        "exampleBn": "আর্নেস্ট হেমিংওয়ে তাঁর গদ্যে সমান্তরাল ও অলঙ্কারহীন সরল বাক্যরীতির জন্য সমাদৃত ছিলেন।",
        "category": "Literature & Arts"
    },
    {
        "word": "Hypotaxis",
        "pos": "Noun",
        "phonetic": "/ˌhaɪ.poʊˈtæk.sɪs/ (হাইপোট্যাক্সিস)",
        "meaningBn": "অধীন ও প্রধান বাক্যাংশের সমন্বয়ে গঠিত জটিল ও প্রলম্বিত বাক্যশৈলী",
        "synonyms": ["Subordinate clause structure", "Complex syntax"],
        "antonyms": ["Parataxis"],
        "exampleEn": "The Victorian essayist favored rich hypotaxis with nested relative clauses.",
        "exampleBn": "ভিক্টোরিয়ান প্রাবন্ধিক অধীন বাক্যাংশখচিত জটিল ও সমৃদ্ধ বাক্যশৈলী পছন্দ করতেন।",
        "category": "Literature & Arts"
    },
    {
        "word": "Epanalepsis",
        "pos": "Noun",
        "phonetic": "/ˌɛp.ə.nəˈlɛp.sɪs/ (এপ্যানালেপসিস)",
        "meaningBn": "বাক্যের শুরুতে যে শব্দ ব্যবহৃত হয় শেষভাগেও সেই একই শব্দের পুনরাবৃত্তি",
        "synonyms": ["Initial-terminal repetition", "Framing reprise"],
        "antonyms": ["Linear prose"],
        "exampleEn": "'The king is dead, long live the king' is an enduring epanalepsis.",
        "exampleBn": "'রাজা মৃত, রাজা দীর্ঘজীবী হোন' শুরুতে ও শেষে একই শব্দের প্রভাবশালী পুনরাবৃত্তির চমৎকার নজির।",
        "category": "Literature & Arts"
    },
    {
        "word": "Anadiplosis",
        "pos": "Noun",
        "phonetic": "/ˌæn.ə.dɪˈploʊ.sɪs/ (অ্যানাডিপ্লোসিস)",
        "meaningBn": "পূর্ববর্তী বাক্যের শেষ শব্দ দিয়ে পরবর্তী বাক্য শুরু করার অলঙ্কার",
        "synonyms": ["Duplicative repetition", "Chained recurrence"],
        "antonyms": ["Discontinuous syntax"],
        "exampleEn": "'Fear leads to anger. Anger leads to hate' features anadiplosis.",
        "exampleBn": "'ভয় থেকে জন্মায় ক্রোধ, ক্রোধ ডেকে আনে ঘৃণা' বাক্যে শেষ শব্দের পুনরাবৃত্তি দিয়ে নতুন বাক্য গড়ার অলঙ্কার রয়েছে।",
        "category": "Literature & Arts"
    },
    {
        "word": "Polyptoton",
        "pos": "Noun",
        "phonetic": "/pɒˈlɪp.tə.tɒn/ (পলিপটোটন)",
        "meaningBn": "একই মূল ধাতুর শব্দের ভিন্ন রূপের পুনরাবৃত্তিযুক্ত অলঙ্কার",
        "synonyms": ["Root-word variation", "Cognate repetition"],
        "antonyms": ["Synonymous replacement"],
        "exampleEn": "'With eager feeding food doth choke the feeder' illustrates polyptoton.",
        "exampleBn": "একই ধাতুর ভিন্ন পদ পাশাপাশি বসিয়ে বাক্যের সৌন্দর্য বৃদ্ধি করাই হলো পলিপটোটন।",
        "category": "Literature & Arts"
    },
    {
        "word": "Antimetabole",
        "pos": "Noun",
        "phonetic": "/ˌæn.ti.mɪˈtæb.ə.li/ (অ্যান্টিমেটাবোলি)",
        "meaningBn": "পরবর্তী বাক্যাংশে শব্দগুলোর বিপরীত বিন্যাসে পুনরাবৃত্তি",
        "synonyms": ["Chiasmic repetition", "Inverted wordplay"],
        "antonyms": ["Sequential repetition"],
        "exampleEn": "'Ask not what your country can do for you; ask what you can do for your country.'",
        "exampleBn": "'দেশ তোমার জন্য কী করতে পারে তা জানতে চেয়ো না; জানো তুমি দেশের জন্য কী করতে পারো।'—এটি অ্যান্টিমেটাবোলির উদাহরণ।",
        "category": "Literature & Arts"
    },
    {
        "word": "Epizeuxis",
        "pos": "Noun",
        "phonetic": "/ˌɛp.ɪˈzjuːk.sɪs/ (এপিজিউকসিস)",
        "meaningBn": "তীব্র জোর দেওয়ার জন্য কোনো শব্দের বিরতিহীন অবিচ্ছিন্ন পুনরাবৃত্তি",
        "synonyms": ["Emphatic repetition", "Palilogia"],
        "antonyms": ["Single mention"],
        "exampleEn": "The general shouted: 'Attack! Attack! Attack!' in dramatic epizeuxis.",
        "exampleBn": "সেনাপতি তীব্র আবেগে 'আক্রমণ! আক্রমণ! আক্রমণ!' বলে অবিচ্ছিন্ন পুনরাবৃত্তি ঘটালেন।",
        "category": "Literature & Arts"
    },
    {
        "word": "Isocolon",
        "pos": "Noun",
        "phonetic": "/ˌaɪ.soʊˈkoʊ.lən/ (আইসোকোলন)",
        "meaningBn": "সমান দৈর্ঘ্য ও একই গঠনবিশিষ্ট সমান্তরাল বাক্যাংশ",
        "synonyms": ["Balanced structure", "Parallel phrasing"],
        "antonyms": ["Unbalanced syntax"],
        "exampleEn": "'Veni, vidi, vici' is a flawless tricolon and isocolon of equal rhythmic weight.",
        "exampleBn": "সমান দৈর্ঘ্য ও তালবিশিষ্ট তিনটি বাক্যাংশের সুষম গাঁথুনিই হলো আইসোকোলন।",
        "category": "Literature & Arts"
    },
    {
        "word": "Tricolon",
        "pos": "Noun",
        "phonetic": "/ˈtraɪˌkoʊ.lən/ (ট্রাইকোলন)",
        "meaningBn": "তিনটি সুষম সমান্তরাল বাক্যাংশ বা শব্দের সমাবেশ",
        "synonyms": ["Rule of three", "Triad"],
        "antonyms": ["Monocolon"],
        "exampleEn": "The motto 'Liberty, Equality, Fraternity' is the ultimate political tricolon.",
        "exampleBn": "'স্বাধীনতা, সাম্য, ভ্রাতৃত্ব' স্লোগানটি তিনটি সমান্তরাল পদের সেরা রাজনৈতিক ট্রাইকোলন।",
        "category": "Literature & Arts"
    },
    {
        "word": "Kenning",
        "pos": "Noun",
        "phonetic": "/ˈkɛn.ɪŋ/ (কেনিং)",
        "meaningBn": "পুরোনো নর্ডিক বা অ্যাংলো-স্যাক্সন রূপক যৌগিক শব্দ (যেমন সমুদ্রকে 'তিমির পথ' বলা)",
        "synonyms": ["Metaphorical compound", "Periphrastic figure"],
        "antonyms": ["Literal noun"],
        "exampleEn": "Old English bards referred to the sea using the kenning 'whale-road'.",
        "exampleBn": "পুরোনো ইংরেজি চারণ কবিরা রূপক যৌগিক শব্দ ব্যবহার করে সমুদ্রকে 'তিমির সড়ক' বলতেন।",
        "category": "Literature & Arts"
    },
    {
        "word": "Meiosis",
        "pos": "Noun",
        "phonetic": "/maɪˈoʊ.sɪs/ (মায়োসিস)",
        "meaningBn": "কোনো বিষয়ের গুরুত্ব ইচ্ছাকৃতভাবে ছোট করে দেখানোর অলঙ্কার",
        "synonyms": ["Understatement", "Belittlement"],
        "antonyms": ["Hyperbole", "Overstatement"],
        "exampleEn": "Calling a catastrophic hurricane 'a bit of breezy weather' is dramatic meiosis.",
        "exampleBn": "ভয়ানক ঘূর্ণিঝড়কে 'একটু দমকা বাতাস' বলা হলো গুরুত্ব কমিয়ে প্রকাশ করার আলঙ্কারিক চাতুর্য।",
        "category": "Literature & Arts"
    },
    {
        "word": "Synesthesia",
        "pos": "Noun",
        "phonetic": "/ˌsɪn.əsˈθiː.ʒə/ (সিনেসথেসিয়া)",
        "meaningBn": "এক ইন্দ্রিয়ের অনুভূতিকে অন্য ইন্দ্রিয় দিয়ে প্রকাশ করার আলঙ্কারিক বা মনস্তাত্ত্বিক অনুভূতি",
        "synonyms": ["Cross-sensory perception", "Sensory blend"],
        "antonyms": ["Sensory segregation"],
        "exampleEn": "Describing a trumpet sound as 'bright golden and sweet' is poetic synesthesia.",
        "exampleBn": "তূরীর ধ্বনিকে 'উজ্জ্বল সোনালী ও মিষ্টি' হিসেবে প্রকাশ করা অনুভূতির সংমিশ্রণ বা সিনেসথেসিয়া।",
        "category": "Literature & Arts"
    },
    {
        "word": "Dysphemism",
        "pos": "Noun",
        "phonetic": "/ˈdɪs.fəˌmɪz.əm/ (ডিসফেমিজম)",
        "meaningBn": "কোনো সাধারণ শব্দের বদলে কঠোর, কুৎসিত বা অবমাননাকর শব্দের প্রয়োগ",
        "synonyms": ["Pejorative term", "Derogatory expression"],
        "antonyms": ["Euphemism"],
        "exampleEn": "Calling an old car a 'rust bucket' is a common dysphemism.",
        "exampleBn": "একটি পুরোনো গাড়িকে তাচ্ছিল্যভরে 'লৌহখণ্ডের স্তূপ' বলা ডিসফেমিজমের দৃষ্টান্ত।",
        "category": "Literature & Arts"
    },
    {
        "word": "Poltroon",
        "pos": "Noun",
        "phonetic": "/pɒlˈtruːn/ (পলট্রুন)",
        "meaningBn": "চরম কাপুরুষ; ভীরু ও মেরুদণ্ডহীন ব্যক্তি",
        "synonyms": ["Craven", "Coward", "Dastard"],
        "antonyms": ["Hero", "Valiant warrior", "Stalwart"],
        "exampleEn": "The poltroon abandoned his post and fled the moment the first shot was fired.",
        "exampleBn": "প্রথম গুলির শব্দ শোনা মাত্রই ভীরু কাপুরুষটি নিজের দায়িত্ব ছেড়ে পালিয়ে গেল।",
        "category": "One Word Substitution"
    },
    {
        "word": "Braggadocio",
        "pos": "Noun",
        "phonetic": "/ˌbræɡ.əˈdoʊ.tʃi.oʊ/ (ব্রাগাডোসিও)",
        "meaningBn": "অসার আস্ফালন; দাম্ভিক অহমিকা প্রদর্শন",
        "synonyms": ["Boastfulness", "Bluster", "Vain swagger"],
        "antonyms": ["Modesty", "Humility", "Diffidence"],
        "exampleEn": "Despite all his empty braggadocio, he produced no tangible results on the project.",
        "exampleBn": "তার সকল অন্তঃসারশূন্য আস্ফালন সত্ত্বেও সে প্রকল্পে বাস্তব কোনো ফলাফল দেখাতে পারেনি।",
        "category": "BCS & Bank"
    },
    {
        "word": "Rodomont",
        "pos": "Noun",
        "phonetic": "/ˈrɒd.ə.mɒnt/ (রোডোমন্ট)",
        "meaningBn": "অহংকারী গালভরা বচন দেওয়া ব্যক্তি; আস্ফালনকারী",
        "synonyms": ["Braggart", "Boaster", "Vaunter"],
        "antonyms": ["Quiet achiever", "Modest person"],
        "exampleEn": "He gained a reputation as a tireless rodomont whose stories were entirely fabricated.",
        "exampleBn": "তার পরিচিতি ছিল এক ফাঁকা বুলি আওড়ানো আস্ফালনকারী হিসেবে যার গল্পগুলো ছিল নিছক বানোয়াট।",
        "category": "One Word Substitution"
    },
    {
        "word": "Scaramouch",
        "pos": "Noun",
        "phonetic": "/ˈskær.ə.muːtʃ/ (স্কারামাউচ)",
        "meaningBn": "বাচাল অথচ ভীতু ভাঁড় চরিত্র; ভণ্ড ও কাপুরুষ ব্যক্তি",
        "synonyms": ["Buffoon", "Poltroon", "Clown"],
        "antonyms": ["Noble leader", "Dignified person"],
        "exampleEn": "The satirical play depicted the corrupt mayor as a ridiculous scaramouch.",
        "exampleBn": "ব্যঙ্গাত্মক নাটকটিতে দুর্নীতিগ্রস্ত মেয়রকে এক হাস্যকর ভাঁড় ও ভণ্ড হিসেবে উপস্থাপন করা হয়েছিল।",
        "category": "One Word Substitution"
    },
    {
        "word": "Pantaloon",
        "pos": "Noun",
        "phonetic": "/ˌpæn.təˈluːn/ (প্যান্টালুন)",
        "meaningBn": "প্রহসনের বৃদ্ধ, নির্বোধ ও উপহাসের পাত্র চরিত্র",
        "synonyms": ["Foolish elder", "Dotard", "Buffoon"],
        "antonyms": ["Wise elder", "Patriarch"],
        "exampleEn": "In the comedic opera, the greedy guardian was portrayed as a bumbling pantaloon.",
        "exampleBn": "হাস্যরসাত্মক অপেরায় লোভী অভিভাবকটিকে এক হাবাগোবা নির্বোধ বৃদ্ধ হিসেবে ফুটিয়ে তোলা হয়েছিল।",
        "category": "Literature & Arts"
    },
    {
        "word": "Saltimbanco",
        "pos": "Noun",
        "phonetic": "/ˌsæl.tɪmˈbæŋ.koʊ/ (সালটিমব্যাঙ্কো)",
        "meaningBn": "রাস্তার ভ্রাম্যমাণ ভোজবাজিকর ও হাতুড়ে ওষুধ বিক্রেতা",
        "synonyms": ["Mountebank", "Quack", "Charlatan"],
        "antonyms": ["Legitimate physician", "Licensed doctor"],
        "exampleEn": "The medieval saltimbanco stood on a bench selling useless tonics to naive villagers.",
        "exampleBn": "মধ্যযুগীয় হাতুড়ে বিক্রেতাটি বেঞ্চের ওপর দাঁড়িয়ে সরল গ্রামবাসীদের কাছে অকার্যকর টনিক বিক্রি করত।",
        "category": "One Word Substitution"
    },
    {
        "word": "Quacksalver",
        "pos": "Noun",
        "phonetic": "/ˈkwækˌsæl.vər/ (কোয়াকস্যালভার)",
        "meaningBn": "অকার্যকর সালসা বা ওষুধ ফেরি করা হাতুড়ে চিকিৎসক",
        "synonyms": ["Quack doctor", "Charlatan", "Medicaster"],
        "antonyms": ["Certified physician", "Authentic doctor"],
        "exampleEn": "Before medical regulation, many a quacksalver profited by peddling toxic mercury mixtures.",
        "exampleBn": "চিকিৎসা নিয়ন্ত্রণ আইন হওয়ার পূর্বে অনেক হাতুড়ে কবিরাজ পারদের ক্ষতিকর মিশ্রণ বিক্রি করে লাভবান হতো।",
        "category": "One Word Substitution"
    },
    {
        "word": "Medicaster",
        "pos": "Noun",
        "phonetic": "/ˈmɛd.ɪˌkæs.tər/ (মেডিক্যাস্টার)",
        "meaningBn": "অল্পবিদ্যাভয়ংকর হাতুড়ে চিকিৎসক",
        "synonyms": ["Incompetent doctor", "Quack", "Pretender"],
        "antonyms": ["Expert physician", "Specialist"],
        "exampleEn": "The patient suffered grievous harm under the care of an uncredentialed medicaster.",
        "exampleBn": "ডিগ্রিবিহীন হাতুড়ে চিকিৎসকের কবলে পড়ে রোগীটি মারাত্মক শারীরিক ক্ষতির শিকার হয়েছিল।",
        "category": "One Word Substitution"
    },
    {
        "word": "Poetaster",
        "pos": "Noun",
        "phonetic": "/ˌpoʊ.ɪˈtæs.tər/ (পোয়েট্যাস্টার)",
        "meaningBn": "অযোগ্য ও নিকৃষ্টমানের কবি; পদ্যলেখক",
        "synonyms": ["Rhymester", "Dabbler in verse", "Verse-monger"],
        "antonyms": ["Poet laureate", "Master poet", "Bard"],
        "exampleEn": "Every royal court had its share of obsequious poetasters seeking royal favors.",
        "exampleBn": "প্রতিটি রাজদরবারেই অনুগ্রহপ্রার্থী কিছু চাটুকার অযোগ্য পদ্যলেখক থাকত।",
        "category": "One Word Substitution"
    },
    {
        "word": "Criticaster",
        "pos": "Noun",
        "phonetic": "/ˈkrɪt.ɪˌkæs.tər/ (ক্রিটিক্যাস্টার)",
        "meaningBn": "অযোগ্য, অগভীর ও খুতখুঁতে সমালোচক",
        "synonyms": ["Petty critic", "Superficial reviewer", "Caviler"],
        "antonyms": ["Master critic", "Astute scholar"],
        "exampleEn": "The visionary novelist ignored the snide remarks of every petty criticaster.",
        "exampleBn": "দূরদর্শী ঔপন্যাসিক কোনো অগভীর অযোগ্য সমালোচকের কটূক্তির তোয়াক্কা করতেন না।",
        "category": "One Word Substitution"
    },
    {
        "word": "Grammaticaster",
        "pos": "Noun",
        "phonetic": "/ɡrəˌmæt.ɪˈkæs.tər/ (গ্রামাটিক্যাস্টার)",
        "meaningBn": "ক্ষুদ্রাতিক্ষুদ্র তুচ্ছ নিয়ম নিয়ে বাড়াবাড়ি করা পণ্ডিতম্মন্য ব্যাকরণবিদ",
        "synonyms": ["Pedantic grammarian", "Petty pedant"],
        "antonyms": ["Linguist", "Progressive grammarian"],
        "exampleEn": "The grammaticaster was more obsessed with ending sentences with prepositions than conveying ideas.",
        "exampleBn": "ক্ষুদ্র নিয়মান্ধ ব্যাকরণবিদটি মূল ভাব প্রকাশের চেয়ে বাক্যশেষে প্রিপোজিশন বসা নিয়ে বেশি চিন্তিত ছিলেন।",
        "category": "One Word Substitution"
    },
    {
        "word": "Sciolist",
        "pos": "Noun",
        "phonetic": "/ˈsaɪ.ə.lɪst/ (সায়োলিস্ট)",
        "meaningBn": "অল্পবিদ্যাভয়ংকর ভণ্ড পণ্ডিত; অগভীর জ্ঞানের অধিকারী",
        "synonyms": ["Superficial pretender", "Dilettante", "Smatterer"],
        "antonyms": ["Polymath", "Scholar", "Erudite expert"],
        "exampleEn": "He sounded knowledgeable at first, but deeper probing revealed him to be a mere sciolist.",
        "exampleBn": "প্রথমে তাকে বিজ্ঞ মনে হলেও গভীরভাবে প্রশ্ন করায় ধরা পড়ল সে নিছক এক অগভীর ভণ্ড পণ্ডিত।",
        "category": "One Word Substitution"
    },
    {
        "word": "Opsimath",
        "pos": "Noun",
        "phonetic": "/ˈɒp.sɪ.mæθ/ (অপসিমাথ)",
        "meaningBn": "দেরিতে বা পরিণত বয়সে বিদ্যালাভ শুরু করা ব্যক্তি",
        "synonyms": ["Late learner", "Adult student"],
        "antonyms": ["Child prodigy", "Early scholar"],
        "exampleEn": "Proving that it is never too late, the proud opsimath earned her university degree at age seventy.",
        "exampleBn": "শেখার কোনো বয়স নেই তা প্রমাণ করে সেই পরিণত বয়সের শিক্ষার্থী সত্তর বছর বয়সে ডিগ্রি অর্জন করলেন।",
        "category": "One Word Substitution"
    },
    {
        "word": "Plutocrat",
        "pos": "Noun",
        "phonetic": "/ˈpluː.tə.kræt/ (প্লুটোক্র্যাট)",
        "meaningBn": "ধনকুবের শাসক; প্রভূত সম্পদের শক্তিতে প্রভাব বিস্তারকারী ব্যক্তি",
        "synonyms": ["Magnate", "Tycoon", "Wealthy oligarch"],
        "antonyms": ["Proletarian", "Pauper"],
        "exampleEn": "Critics argued that policy decisions were dictated by plutocrats rather than ordinary citizens.",
        "exampleBn": "সমালোচকরা অভিযোগ করেন নীতিগত সিদ্ধান্তগুলো সাধারণ নাগরিকের বদলে ধনকুবের শাসকরাই নির্ধারণ করছিল।",
        "category": "BCS & Bank"
    },
    {
        "word": "Kleptocrat",
        "pos": "Noun",
        "phonetic": "/ˈklɛp.tə.kræt/ (ক্লেপ্টোক্র্যাট)",
        "meaningBn": "রাষ্ট্রীয় অর্থ আত্মসাৎকারী চোর শাসক",
        "synonyms": ["Thieving ruler", "Corrupt despot"],
        "antonyms": ["Honest statesman", "Incorruptible leader"],
        "exampleEn": "The fallen kleptocrat had siphoned billions into secret offshore accounts.",
        "exampleBn": "ক্ষমতাচ্যুত চোর শাসকটি বিলিয়ন বিলিয়ন অর্থ বিদেশি বেনামি অ্যাকাউন্টে পাচার করেছিল।",
        "category": "BCS & Bank"
    },
    {
        "word": "Ochlocrat",
        "pos": "Noun",
        "phonetic": "/ˈɒk.lə.kræt/ (অকলোক্র্যাট)",
        "meaningBn": "উচ্ছৃঙ্খল জনতা বা উগ্র মবের শাসন সমর্থক",
        "synonyms": ["Mob rule advocate", "Rabble-rouser"],
        "antonyms": ["Constitutionalist", "Rule-of-law advocate"],
        "exampleEn": "The orator warned that reckless populism would turn the republic over to violent ochlocrats.",
        "exampleBn": "বক্তা সতর্ক করে দিলেন যে দায়িত্বহীন গণতুষ্টিবাদ প্রজাতন্ত্রকে উগ্র জনতার শাসনে পরিণত করবে।",
        "category": "BCS & Bank"
    },
    {
        "word": "Kakistocrat",
        "pos": "Noun",
        "phonetic": "/kæˌkɪsˈtɒk.ræt/ (ক্যাকিস্টোক্র্যাট)",
        "meaningBn": "সবচেয়ে অযোগ্য ও নীতিহীন শাসকশ্রেণির ব্যক্তি",
        "synonyms": ["Worst ruler", "Incompetent leader"],
        "antonyms": ["Aristocrat", "Meritocrat", "Statesman"],
        "exampleEn": "Under the reign of kakistocrats, public institutions crumbled due to sheer incompetence.",
        "exampleBn": "চরম অযোগ্য নীতিহীন শাসকদের আমলে চূড়ান্ত অদক্ষতার কারণে সরকারি প্রতিষ্ঠানগুলো ভেঙে পড়েছিল।",
        "category": "BCS & Bank"
    },
    {
        "word": "Gerontocrat",
        "pos": "Noun",
        "phonetic": "/ˌdʒɛr.ənˈtɒk.ræt/ (জেরন্টাক্র্যাট)",
        "meaningBn": "বৃদ্ধ বয়সের শাসক; প্রবীণতন্ত্রের সদস্য",
        "synonyms": ["Elderly ruler", "Aged leader"],
        "antonyms": ["Youth leader", "Juvenile official"],
        "exampleEn": "The aging committee of gerontocrats struggled to understand modern digital privacy.",
        "exampleBn": "প্রবীণ শাসকদের কমিটি আধুনিক ডিজিটাল গোপনীয়তার গুরুত্ব উপলব্ধি করতে হিমশিম খাচ্ছিল।",
        "category": "BCS & Bank"
    },
    {
        "word": "Theocrat",
        "pos": "Noun",
        "phonetic": "/ˈθiː.ə.kræt/ (থিওক্র্যাট)",
        "meaningBn": "ধর্মযাজক বা ধর্মাশ্রিত শাসক",
        "synonyms": ["Religious ruler", "Clerical governor"],
        "antonyms": ["Secular ruler"],
        "exampleEn": "The medieval state was strictly governed by dogmatic theocrats.",
        "exampleBn": "মধ্যযুগীয় রাষ্ট্রটি কট্টর ধর্মাশ্রিত ধর্মযাজক শাসকদের দ্বারা পরিচালিত হতো।",
        "category": "BCS & Bank"
    },
    {
        "word": "Misocapnic",
        "pos": "Adjective",
        "phonetic": "/ˌmɪs.oʊˈkæp.nɪk/ (মিসোক্যাপনিক)",
        "meaningBn": "তামাকের ধোঁয়া বা ধূমপান ঘোর অপছন্দকারী",
        "synonyms": ["Smoke-hating", "Anti-smoking"],
        "antonyms": ["Tobacco-loving", "Pro-smoking"],
        "exampleEn": "As a deeply misocapnic individual, she immediately left any room where people smoked.",
        "exampleBn": "ধূমপানের ধোঁয়া ঘোর অপছন্দকারী হিসেবে কেউ সিগারেট ধরালেই সে তাৎক্ষণিক কক্ষ ত্যাগ করত।",
        "category": "One Word Substitution"
    }
]

with open('next_part1_sub1.json', 'w', encoding='utf-8') as f:
    json.dump(batch1_words, f, ensure_ascii=False, indent=2)
print("Part 1 sub 1 written:", len(batch1_words))
