import json, re

# 1. Collect all existing words
existing_words = set()

try:
    with open('app/src/main/assets/dictionary_1000.json', 'r') as f:
        data = json.load(f)
        for w in data:
            if 'word' in w and isinstance(w['word'], str):
                existing_words.add(w['word'].strip().lower())
except Exception as e:
    print("Error reading assets json:", e)

try:
    with open('app/src/main/java/com/example/ui/screens/tools/VocabularyDataPacks.kt', 'r') as f:
        content = f.read()
        for m in re.findall(r'VocabWord\s*\(\s*\"[^\"]+\"\s*,\s*\"([^\"]+)\"', content):
            existing_words.add(m.strip().lower())
except Exception as e:
    print("Error reading DataPacks:", e)

try:
    with open('app/src/main/java/com/example/ui/screens/tools/VocabularyHighFrequencyDataset.kt', 'r') as f:
        content = f.read()
        for t in re.findall(r'Triple\s*\(\s*\"([^\"]+)\"', content):
            existing_words.add(t.strip().lower())
except Exception as e:
    print("Error reading HighFreq:", e)

print(f"Total existing unique words: {len(existing_words)}")

# Curated bank of English words with Bengali translations
word_bank = [
    # (Word, Phonetic, POS, MeaningBn, ExampleEn, ExampleBn, Synonyms, Antonyms, Category)
    ("Abridge", "/əˈbrɪdʒ/", "Verb", "সংক্ষিপ্ত করা, ছেঁটে ছোট করা", "The publisher decided to abridge the long novel.", "প্রকাশক দীর্ঘ উপন্যাসটি সংক্ষিপ্ত করার সিদ্ধান্ত নেন।", ["Shorten", "Truncate"], ["Expand", "Extend"], "IELTS"),
    ("Absolve", "/əbˈzɒlv/", "Verb", "পাপ বা অপরাধ থেকে মুক্তি দেওয়া", "The priest absolved him of his sins.", "পুরোহিত তাকে তার পাপ থেকে মুক্তি দেন।", ["Pardon", "Exonerate"], ["Blame", "Condemn"], "BCS"),
    ("Abstain", "/əbˈsteɪn/", "Verb", "বিরত থাকা, সংযত হওয়া", "Doctors advised him to abstain from smoking.", "ডাক্তাররা তাকে ধূমপান থেকে বিরত থাকার পরামর্শ দিয়েছেন।", ["Refrain", "Avoid"], ["Indulge"], "Spoken"),
    ("Abstemious", "/æbˈstiː.mi.əs/", "Adj", "পরিমিতাহারী, সংযমী", "He leads an abstemious lifestyle.", "তিনি এক পরিমিত ও সংযমী জীবনযাপন করেন।", ["Temperate", "Moderate"], ["Gluttonous"], "Academic"),
    ("Abstracted", "/æbˈstræk.tɪd/", "Adj", "অন্যমনস্ক, উদাসীন", "He had an abstracted look on his face.", "তার মুখে এক অন্যমনস্ক ভাব ছিল।", ["Preoccupied", "Absent-minded"], ["Attentive"], "Spoken"),
    ("Abstruse", "/æbˈstruːs/", "Adj", "গূঢ়, জটিল, দুর্বোধ্য", "The lecture was full of abstruse theories.", "বক্তৃতাটি দুর্বোধ্য তত্ত্বে পরিপূর্ণ ছিল।", ["Obscure", "Recondite"], ["Clear", "Simple"], "Academic"),
    ("Abut", "/əˈbʌt/", "Verb", "সীমান্তে সংলগ্ন হওয়া", "His property abuts on the public park.", "তার সম্পত্তিটি পাবলিক পার্কের সংলগ্ন।", ["Adjoin", "Border"], [], "Academic"),
    ("Abysmal", "/əˈbɪz.məl/", "Adj", "অতল, অত্যন্ত বাজে", "The quality of work was abysmal.", "কাজের মান ছিল অত্যন্ত বাজে।", ["Dreadful", "Appalling"], ["Excellent"], "IELTS"),
    ("Accelerate", "/əkˈsel.ə.reɪt/", "Verb", "গতি বৃদ্ধি করা, ত্বরান্বিত করা", "The driver accelerated the car to overtake.", "চালক ওভারটেক করার জন্য গাড়ির গতি বাড়িয়েছিল।", ["Speed up", "Hasten"], ["Decelerate", "Slow down"], "Spoken"),
    ("Accentuating", "/əkˈsen.tʃu.eɪ.tɪŋ/", "Noun", "জোর প্রদান, গুরুত্বারোপ", "The highlighting helps in accentuating key points.", "হাইলাইট করা অংশগুলো মূল পয়েন্টে জোর দিতে সাহায্য করে।", ["Emphasizing", "Highlighting"], [], "IELTS"),
    ("Acclimation", "/ˌæk.lɪˈmeɪ.ʃən/", "Noun", "নতুন আবহাওয়া বা পরিবেশে মানিয়ে নেওয়া", "Acclimation to high altitude takes time.", "উঁচু স্থানের আবহাওয়ায় মানিয়ে নিতে সময় লাগে।", ["Adaptation", "Adjustment"], [], "Academic"),
    ("Accolade", "/ˈæk.ə.leɪd/", "Noun", "সংবর্ধনা, বিশেষ সম্মাননা", "She received the highest accolade for bravery.", "তিনি সাহসিকতার জন্য সর্বোচ্চ সম্মাননা পেয়েছিলেন।", ["Honor", "Award", "Tribute"], [], "BCS"),
    ("Accountability", "/əˌkaʊn.təˈbɪl.ə.ti/", "Noun", "জবাবদিহিতা, দায়বদ্ধতা", "Public officers must maintain accountability.", "সরকারি কর্মকর্তাদের অবশ্যই জবাবদিহিতা বজায় রাখতে হবে।", ["Responsibility", "Answerability"], [], "BCS"),
    ("Accrete", "/əˈkriːt/", "Verb", "একত্রিত হয়ে বড় হওয়া", "Dust particles accrete to form planets.", "ধূলিকণা একত্রিত হয়ে গ্রহ গঠন করে।", ["Grow", "Accumulate"], [], "Academic"),
    ("Acerbic", "/əˈsɜː.bɪk/", "Adj", "কটু, তিক্ত, তীক্ষ্ণভাষী", "He made an acerbic comment about the food.", "খাবার নিয়ে সে এক কটু মন্তব্য করেছিল।", ["Caustic", "Biting"], ["Mild", "Sweet"], "IELTS"),
    ("Acquiescence", "/ˌæk.wiˈes.əns/", "Noun", "নীরব সম্মতি", "Her acquiescence signaled approval.", "তার নীরব সম্মতি অনুমোদনের ইঙ্গিত দিয়েছিল।", ["Consent", "Compliance"], ["Refusal"], "BCS"),
    ("Acquisitive", "/əˈkwɪz.ə.tɪv/", "Adj", "অর্জনপ্রবণ, ধনলিপ্সু", "We live in an acquisitive society.", "আমরা এক ধনলিপ্সু সমাজে বাস করি।", ["Greedy", "Grasping"], ["Generous"], "Academic"),
    ("Acrimony", "/ˈæk.rɪ.mə.ni/", "Noun", "তিক্ততা, উগ্রতা", "The dispute ended in acrimony.", "বিবাদটি তিক্ততার মাধ্যমে শেষ হয়েছিল।", ["Bitterness", "Rancor"], ["Harmony"], "IELTS"),
    ("Acumen", "/ˈæk.jə.mən/", "Noun", "তীক্ষ্ণ বুদ্ধি, বিচক্ষণতা", "Her financial acumen saved the company.", "তার আর্থিক বিচক্ষণতা কোম্পানিটিকে বাঁচিয়েছিল।", ["Shrewdness", "Insight"], ["Stupidity"], "BCS"),
    ("Adage", "/ˈæd.ɪdʒ/", "Noun", "প্রবাদ বাক্য", "An old adage says honesty is best policy.", "একটি পুরোনো প্রবাদ বলে সততাই সর্বোৎকৃষ্ট পন্থা।", ["Maxim", "Motto"], [], "Spoken"),
    ("Adamant", "/ˈæd.ə.mənt/", "Adj", "অনমনীয়, অনড়", "The union remained adamant on their demands.", "ইউনিয়ন তাদের দাবির ব্যাপারে অনড় ছিল।", ["Unyielding", "Firm"], ["Flexible"], "Spoken"),
    ("Adaptability", "/əˌdæp.təˈbɪl.ə.ti/", "Noun", "অভিযোজনক্ষমতা, মানিয়ে নেওয়ার যোগ্যতা", "Adaptability is essential for career success.", "ক্যারিয়ারের সাফল্যের জন্য মানিয়ে নেওয়ার ক্ষমতা অপরিহার্য।", ["Flexibility", "Versatility"], [], "Spoken"),
    ("Addendum", "/əˈden.dəm/", "Noun", "সংযোজনী, পরিশিষ্ট", "An addendum was attached to the contract.", "চুক্তিতে একটি পরিশিষ্ট সংযুক্ত করা হয়েছিল।", ["Supplement", "Appendix"], [], "Academic"),
    ("Adduce", "/əˈdʒuːs/", "Verb", "প্রমাণ হিসেবে উত্থাপন করা", "He adduced several facts to support his view.", "তিনি তার বক্তব্য সমর্থনে বেশ কিছু তথ্য উত্থাপন করেন।", ["Cite", "Present"], [], "BCS"),
    ("Adroit", "/əˈdrɔɪt/", "Adj", "চতুর, ক্ষিপ্রহস্ত", "She is adroit at handling crisis.", "তিনি সংকট মোকাবিলায় অত্যন্ত চতুর।", ["Skillful", "Adept"], ["Clumsy"], "IELTS"),
    ("Adulation", "/ˌæd.jəˈleɪ.ʃən/", "Noun", "অতিরিক্ত স্তুতি বা তোষামোদ", "The actor enjoyed the adulation of crowd.", "অভিনেতা জনতার তোষামোদ উপভোগ করছিলেন।", ["Flattery", "Worship"], ["Criticism"], "BCS"),
    ("Adulterate", "/əˈdʌl.tə.reɪt/", "Verb", "ভেজাল মেশানো", "It is illegal to adulterate milk with water.", "দুধে পানি মেশানো বেআইনি।", ["Contaminate", "Debase"], ["Purify"], "BCS"),
    ("Adumbrate", "/ˈæd.əm.breɪt/", "Verb", "আভাস দেওয়া, অস্পষ্ট রূপরেখা দেওয়া", "The report adumbrates future changes.", "প্রতিবেদনটি ভবিষ্যতের পরিবর্তনের আভাস দেয়।", ["Outline", "Foreshadow"], [], "Academic"),
    ("Adversary", "/ˈæd.və.sər.i/", "Noun", "শত্রু, প্রতিপক্ষ", "He defeated his formidable adversary.", "তিনি তার প্রবল প্রতিপক্ষকে পরাজিত করেছিলেন।", ["Opponent", "Rival"], ["Ally"], "IELTS"),
    ("Adversity", "/ədˈvɜː.sə.ti/", "Noun", "দুর্ভাগ্য, প্রতিকূলতা", "He showed great courage in adversity.", "তিনি প্রতিকূলতায় দুর্দান্ত সাহস দেখিয়েছিলেন।", ["Hardship", "Misfortune"], ["Prosperity"], "BCS"),
    ("Advocacy", "/ˈæd.və.kə.si/", "Noun", "সমর্থন, ওকালতি", "She is known for her advocacy of human rights.", "তিনি মানবাধিকার সমর্থনের জন্য পরিচিত।", ["Support", "Promotion"], [], "BCS"),
    ("Aegis", "/ˈiː.dʒɪs/", "Noun", "ছত্রছায়া, অভিভাবকত্ব", "The summit took place under aegis of UN.", "জাতিসংঘের ছত্রছায়ায় শীর্ষ সম্মেলনটি অনুষ্ঠিত হয়েছিল।", ["Protection", "Sponsorship"], [], "BCS"),
    ("Aesthetic", "/esˈθet.ɪk/", "Adj", "নান্দনিক, সৌন্দর্যবোধসম্পন্ন", "The building has high aesthetic value.", "ভবনটির উচ্চ নান্দনিক মান রয়েছে।", ["Artistic", "Beautiful"], ["Ugly"], "IELTS"),
    ("Affable", "/ˈæf.ə.bəl/", "Adj", "অমায়িক, বন্ধুবৎসল", "He was an affable host.", "তিনি ছিলেন এক অমায়িক স্বাগতিক।", ["Friendly", "Cordial"], ["Aloof"], "Spoken"),
    ("Affectionate", "/əˈfek.ʃən.ət/", "Adj", "স্নেহশীল, অনুরাগী", "She gave her son an affectionate hug.", "তিনি তার ছেলেকে এক স্নেহশীল কোলাকুলি দিয়েছিলেন।", ["Loving", "Caring"], ["Cold"], "Spoken"),
    ("Affidavit", "/ˌæf.ɪˈdeɪ.vɪt/", "Noun", "হলফনামা, লিখিত শপথপত্র", "Submit an affidavit along with application.", "আবেদনের সাথে একটি হলফনামা জমা দিন।", ["Testimony", "Declaration"], [], "BCS"),
    ("Affiliate", "/əˈfɪl.i.eɪt/", "Verb", "শাখা হিসেবে যুক্ত করা", "The college is affiliated with university.", "কলেজটি বিশ্ববিদ্যালয়ের সাথে অনুমোদিত।", ["Associate", "Connect"], [], "Spoken"),
    ("Affinity", "/əˈfɪn.ə.ti/", "Noun", "আকর্ষণ, নিবিড় অনুভূতি", "She feels an affinity for nature.", "তিনি প্রকৃতির প্রতি এক নিবিড় টান অনুভব করেন।", ["Attraction", "Liking"], ["Aversion"], "IELTS"),
    ("Affliction", "/əˈflɪk.ʃən/", "Noun", "কষ্ট, মানসিক যন্ত্রণা", "He bore his affliction with patience.", "তিনি ধৈর্যের সাথে তার কষ্ট সহ্য করেছিলেন।", ["Suffering", "Pain"], ["Relief"], "Academic"),
    ("Affluence", "/ˈæf.lu.əns/", "Noun", "প্রাচুর্য, সমৃদ্ধি", "The family achieved affluence through trade.", "পরিবারটি ব্যবসার মাধ্যমে সমৃদ্ধি অর্জন করেছিল।", ["Wealth", "Prosperity"], ["Poverty"], "IELTS"),
    ("Affront", "/əˈfrʌnt/", "Noun", "প্রকাশ্য অপমান", "His harsh remarks were an affront to dignity.", "তার কঠোর মন্তব্য মর্যাদার প্রতি এক অপমান ছিল।", ["Insult", "Offense"], ["Honor"], "Academic"),
    ("Aforementioned", "/əˈfɔːˌmen.ʃənd/", "Adj", "পূর্বোল্লিখিত, আগেই বলা হয়েছে এমন", "The aforementioned rules apply to all.", "পূর্বোল্লিখিত নিয়মগুলো সবার ক্ষেত্রে প্রযোজ্য।", ["Aforesaid", "Previous"], [], "Academic"),
    ("Aghast", "/əˈɡɑːst/", "Adj", "ভয়ে স্তম্ভিত, হতভম্ব", "She stood aghast at the tragic news.", "দুঃখজনক সংবাদে সে ভয়ে স্তম্ভিত হয়ে দাঁড়িয়েছিল।", ["Horrified", "Shocked"], [], "Spoken"),
    ("Agility", "/əˈdʒɪl.ə.ti/", "Noun", "ক্ষিপ্রতা, তৎপরতা", "Mental agility is needed in chess.", "দাবায় মানসিক ক্ষিপ্রতার প্রয়োজন।", ["Nimbleness", "Quickness"], ["Sluggishness"], "Spoken"),
    ("Agitate", "/ˈædʒ.ɪ.teɪt/", "Verb", "উত্তেজিত করা, আন্দোলন করা", "Protesters gathered to agitate for reform.", "সংস্কারের আন্দোলনে বিক্ষোভকারীরা জড়ো হয়েছিল।", ["Disturb", "Stir"], ["Calm"], "IELTS"),
    ("Agnostic", "/æɡˈnɒs.tɪk/", "Noun", "অজ্ঞেয়বাদী", "He remains agnostic about afterlife.", "পরকাল নিয়ে তিনি অজ্ঞেয়বাদী রয়ে গেছেন।", ["Skeptic", "Doubter"], [], "Academic"),
    ("Agrarian", "/əˈɡreə.ri.ən/", "Adj", "কৃষিভিত্তিক, কৃষিসংক্রান্ত", "Most villagers lead an agrarian life.", "অধিকাংশ গ্রামবাসী একটি কৃষিভিত্তিক জীবনযাপন করেন।", ["Agricultural", "Farming"], ["Industrial"], "BCS"),
    ("Alacrity", "/əˈlæk.rə.ti/", "Noun", "তৎপরতা, চঞ্চলতা", "He agreed with surprising alacrity.", "তিনি আশ্চর্যজনক তৎপরতার সাথে সম্মত হলেন।", ["Eagerness", "Readiness"], ["Reluctance"], "BCS"),
    ("Albeit", "/ɔːlˈbiː.ɪt/", "Conjunction", "যদিও, সত্ত্বেও", "He accepted the job, albeit reluctantly.", "তিনি কাজটি গ্রহণ করেছিলেন, যদিও অনিচ্ছাসত্ত্বেও।", ["Although", "Even though"], [], "IELTS"),
    ("Alienate", "/ˈeɪ.li.ə.neɪt/", "Verb", "পর করে দেওয়া, দূরে ঠেলে দেওয়া", "His arrogance alienates his friends.", "তার অহংকার তার বন্ধুদের দূরে ঠেলে দেয়।", ["Estrange", "Isolate"], ["Unite"], "Spoken"),
    ("Align", "/əˈlaɪn/", "Verb", "সারিবদ্ধ করা, একলাইনে আনা", "Align the text properly on left margin.", "বাম মার্জিনে লেখাগুলো সঠিকভাবে সাজান।", ["Coordinate", "Adjust"], [], "Spoken"),
    ("Allay", "/əˈleɪ/", "Verb", "ভয় বা উদ্বেগ প্রশমিত করা", "The doctor allayed her fears.", "ডাক্তার তার ভয় প্রশমিত করেছিলেন।", ["Soothe", "Relieve"], ["Intensify"], "IELTS"),
    ("Allegation", "/ˌæl.ɪˈɡeɪ.ʃən/", "Noun", "অভিযোগ, অকাট্য দাবি", "He rejected the false allegation.", "তিনি মিথ্যা অভিযোগটি প্রত্যাখ্যান করেছিলেন।", ["Accusation", "Charge"], [], "BCS"),
    ("Allegiance", "/əˈliː.dʒəns/", "Noun", "আনুগত্য, একনিষ্ঠতা", "Citizens pledge allegiance to flag.", "নাগরিকরা পতাকার প্রতি আনুগত্যের শপথ নেয়।", ["Loyalty", "Fidelity"], ["Disloyalty"], "BCS"),
    ("Allegory", "/ˈæl.ə.ɡər.i/", "Noun", "রূপক কাহিনী", "The story is an allegory of freedom struggle.", "গল্পটি স্বাধীনতা সংগ্রামের এক রূপক আখ্যান।", ["Parable", "Fable"], [], "Academic"),
    ("Alliterate", "/əˈlɪt.ə.reɪt/", "Verb", "অনুপ্রাস সৃষ্টি করা", "Poets often alliterate in verse.", "কফিরা কবিতায় প্রায়শই অনুপ্রাস ব্যবহার করেন।", [], [], "Academic"),
    ("Allocate", "/ˈæl.ə.keɪt/", "Verb", "বরাদ্দ করা", "Government will allocate funds for education.", "সরকার শিক্ষার জন্য তহবিল বরাদ্দ করবে।", ["Assign", "Distribute"], [], "IELTS"),
    ("Allude", "/əˈluːd/", "Verb", "পরোক্ষভাবে উল্লেখ করা", "The article alludes to secret deals.", "প্রবন্ধটি গোপন চুক্তির দিকে পরোক্ষ ইঙ্গিত করে।", ["Hint", "Suggest"], ["Declare"], "IELTS"),
    ("Allure", "/əˈlʊər/", "Noun", "প্রলোভন, মোহিত করার শক্তি", "The allure of big city life attracts youth.", "বড় শহরের জীবনের আকর্ষণ তরুণদের টানে।", ["Attraction", "Charm"], ["Repulsion"], "IELTS"),
    ("Aloof", "/əˈluːf/", "Adj", "একাকী, পৃথক থাকা", "He stayed aloof during debate.", "বিতর্কের সময় তিনি নিরপেক্ষ ও পৃথক ছিলেন।", ["Distant", "Detached"], ["Friendly"], "Spoken"),
    ("Altercation", "/ˌɒl.təˈkeɪ.ʃən/", "Noun", "উত্তপ্ত বাকবিতণ্ডা", "The drivers had a noisy altercation.", "চালকদের মধ্যে এক কোলাহলপূর্ণ বাকবিতণ্ডা হয়েছিল।", ["Quarrel", "Dispute"], ["Agreement"], "BCS"),
    ("Altruism", "/ˈæl.tru.ɪ.zəm/", "Noun", "পরোপকারিতা, নিঃস্বার্থ মনোভাব", "His altruism earned him great respect.", "তার পরোপকারিতা তাকে অগাধ শ্রদ্ধা এনে দিয়েছিল।", ["Selflessness", "Benevolence"], ["Selfishness"], "IELTS"),
    ("Amalgamate", "/əˈmæl.ɡə.meɪt/", "Verb", "একত্রিত হয়ে সংমিশ্রিত হওয়া", "The two banks plan to amalgamate.", "ব্যাংক দুটি একত্রিত হওয়ার পরিকল্পনা করছে।", ["Merge", "Combine"], ["Separate"], "IELTS"),
    ("Amass", "/əˈmæs/", "Verb", "সঞ্চয় করা, পুঞ্জীভূত করা", "He managed to amass vast fortune.", "তিনি বিশাল সম্পত্তি সঞ্চয় করতে সক্ষম হয়েছিলেন।", ["Accumulate", "Gather"], ["Squander"], "BCS"),
    ("Ambience", "/ˈæm.bi.əns/", "Noun", "চারপাশের পরিবেশ ও মেজাজ", "The restaurant offers a romantic ambience.", "রেস্তোরাঁটি এক চমৎকার রোমান্টিক পরিবেশ দেয়।", ["Atmosphere", "Aura"], [], "Spoken"),
    ("Ambiguity", "/ˌæm.bɪˈɡjuː.ə.ti/", "Noun", "দ্ব্যর্থকতা, দ্ব্যর্থবোধক অস্পষ্টতা", "Clear language eliminates ambiguity.", "স্পষ্ট ভাষা অস্পষ্টতা দূর করে।", ["Vagueness", "Uncertainty"], ["Clarity"], "IELTS"),
    ("Ambivalent", "/æmˈbɪv.ə.lənt/", "Adj", "দ্বিধাগ্রস্ত, দুইমুখী অনুভূতিসম্পন্ন", "He feels ambivalent about job offer.", "চাকরির প্রস্তাব নিয়ে সে দ্বিধাগ্রস্ত অনুভব করছে।", ["Undecided", "Uncertain"], ["Decisive"], "IELTS"),
    ("Amble", "/ˈæm.bəl/", "Verb", "ধীরে সুস্থে ঘুরে বেড়ানো", "They ambled through garden after tea.", "চায়ের পর তারা বাগানে ধীরে সুস্থে হাঁটছিলেন।", ["Stroll", "Saunter"], ["Rush"], "Spoken"),
    ("Ameliorate", "/əˈmiː.li.ə.reɪt/", "Verb", "পরিস্থিতির উন্নতি ঘটানো", "New medicine helps ameliorate pain.", "নতুন ওষুধটি ব্যথা কমাতে ও দূর করতে সাহায্য করে।", ["Improve", "Enhance"], ["Worsen"], "BCS"),
    ("Amenable", "/əˈmiː.nə.bəl/", "Adj", "সহজে রাজি হওয়া, বাধ্য", "She is amenable to new ideas.", "তিনি নতুন ধারণার প্রতি ইতিবাচক ও বাধ্য।", ["Receptive", "Flexible"], ["Uncooperative"], "BCS"),
    ("Amendment", "/əˈmend.mənt/", "Noun", "আইনি সংশোধনী", "The bill was passed with amendment.", "বিলিটি সংশোধনীর মাধ্যমে পাস হয়েছিল।", ["Revision", "Modification"], [], "BCS"),
    ("Amenity", "/əˈmiː.nə.ti/", "Noun", "সুযোগ-সুবিধা", "The hotel features modern amenities.", "হোটেলটিতে আধুনিক সুযোগ-সুবিধা রয়েছে।", ["Facility", "Convenience"], [], "Spoken"),
    ("Amiable", "/ˈeɪ.mi.ə.bəl/", "Adj", "সহজ-সরল ও অমায়িক", "She is known for her amiable personality.", "তিনি তার অমায়িক ব্যক্তিত্বের জন্য পরিচিত।", ["Friendly", "Pleasant"], ["Hostile"], "Spoken"),
    ("Amicable", "/ˈæm.ɪ.kə.bəl/", "Adj", "শান্তিপূর্ণ ও বন্ধুত্বপূর্ণ", "They reached an amicable agreement.", "তারা এক শান্তিপূর্ণ চুক্তিতে পৌঁছেছিলেন।", ["Peaceful", "Harmonious"], ["Hostile"], "IELTS"),
    ("Amnesty", "/ˈæm.nə.sti/", "Noun", "সাধারণ ক্ষমাঘোষণা", "The government declared amnesty for rebels.", "সরকার বিদ্রোহীদের জন্য সাধারণ ক্ষমা ঘোষণা করে।", ["Pardon", "Forgiveness"], [], "BCS"),
    ("Amorphous", "/əˈmɔː.fəs/", "Adj", "নির্দিষ্ট আকারবিহীন", "A cloud is an amorphous mass of vapor.", "মেঘ হলো নির্দিষ্ট আকারবিহীন জলীয় বাষ্পের স্তূপ।", ["Shapeless", "Formless"], ["Definite"], "Academic"),
    ("Amplify", "/ˈæm.plɪ.faɪ/", "Verb", "বর্ধিত বা জোরালো করা", "Use a microphone to amplify your voice.", "আপনার কণ্ঠস্বর জোরালো করতে মাইক ব্যবহার করুন।", ["Boost", "Magnify"], ["Reduce"], "Spoken"),
    ("Anachronism", "/əˈnæk.rə.nɪ.zəm/", "Noun", "কালবৈষম্য, যুগে বেমানান বস্তু", "A typewriter today is an anachronism.", "আজকের দিনে টাইপরাইটার একটি কালবৈষম্য।", ["Chronological error"], [], "Academic"),
    ("Analogy", "/əˈnæl.ə.dʒi/", "Noun", "উপমা, সাদৃশ্যপূর্ণ তুলনা", "He explained the law using an analogy.", "তিনি একটি উপমার সাহায্যে নিয়মটি ব্যাখ্যা করেন।", ["Comparison", "Parallel"], [], "IELTS"),
    ("Anarchy", "/ˈæn.ə.ki/", "Noun", "অরাজকতা, শাসনহীন অবস্থা", "Protests dissolved into total anarchy.", "বিক্ষোভগুলো সম্পূর্ণ অরাজকতায় রূপ নিয়েছিল।", ["Chaos", "Lawlessness"], ["Order"], "BCS"),
    ("Ancillary", "/ænˈsɪl.ər.i/", "Adj", "সহায়ক, আনুসঙ্গিক", "Ancillary staff keep hospital running.", "সহায়ক কর্মীরা হাসপাতাল সচল রাখেন।", ["Secondary", "Auxiliary"], ["Main"], "Academic"),
    ("Anecdote", "/ˈæn.ɪk.dəʊt/", "Noun", "সংক্ষিপ্ত জীবনকাহিনি বা আখ্যান", "He told a humorous anecdote about school.", "তিনি স্কুল নিয়ে একটি রসাত্মক গল্প বলেছিলেন।", ["Story", "Tale"], [], "Spoken"),
    ("Anguish", "/ˈæŋ.ɡwɪʃ/", "Noun", "তীব্র মানসিক যন্ত্রণা", "He cried out in deep anguish.", "তিনি চরম তীব্র যন্ত্রণায় কেঁদে উঠেছিলেন।", ["Agony", "Torment"], ["Joy"], "Academic"),
    ("Animate", "/ˈæn.ɪ.meɪt/", "Verb", "সঞ্জীবিত ও প্রাণবন্ত করা", "His smile animated his face.", "তার হাসি তার মুখকে সজীব করে তুলেছিল।", ["Enliven", "Inspire"], [], "Spoken"),
    ("Animosity", "/ˌæn.ɪˈmɒs.ə.ti/", "Noun", "শত্রুভাব, বিদ্বেষ", "They put aside personal animosity.", "তারা ব্যক্তিগত বিদ্বেষ দূরে সরিয়ে রেখেছিলেন।", ["Hostility", "Hatred"], ["Goodwill"], "IELTS"),
    ("Annexation", "/ˌæn.ekˈseɪ.ʃən/", "Noun", "ভূখণ্ড সংযোজন বা দখল", "The annexation of territory provoked war.", "ভূখণ্ড দখল যুদ্ধ উস্কে দিয়েছিল।", ["Acquisition", "Seizure"], [], "BCS"),
    ("Annihilate", "/əˈnaɪ.ə.leɪt/", "Verb", "সমূলে ধ্বংস করে দেওয়া", "The explosion annihilated the house.", "বিস্ফোরণটি বাড়িটি সমূলে ধ্বংস করেছিল।", ["Destroy", "Eradicate"], ["Create"], "BCS"),
    ("Annotation", "/ˌæn.əˈteɪ.ʃən/", "Noun", "টীকা, ব্যখ্যাসূচক নোট", "Add annotations to your diagram.", "আপনার চিত্রটিতে ব্যাখ্যাসূচক টীকা যুক্ত করুন।", ["Note", "Comment"], [], "Academic"),
    ("Anomalous", "/əˈnɒm.ə.ləs/", "Adj", "ব্যতিক্রমী, স্বাভাবিক বহির্ভূত", "Scientists detected an anomalous signal.", "বিজ্ঞানীরা একটি ব্যতিক্রমী সংকেত পেয়েছিলেন।", ["Irregular", "Abnormal"], ["Normal"], "IELTS"),
    ("Antagonism", "/ænˈtæɡ.ən.ɪ.zəm/", "Noun", "শত্রুতা, বৈরিতা", "There was strong antagonism between factions.", "উভয় গোষ্ঠীর মধ্যে তীব্র বৈরিতা ছিল।", ["Hostility", "Opposition"], ["Friendship"], "BCS"),
    ("Antecedent", "/ˌæn.tɪˈsiː.dənt/", "Noun", "পূর্ববর্তী ঘটনা বা পূর্বপুরুষ", "Look at the antecedent events.", "পূর্ববর্তী ঘটনাগুলোর দিকে তাকান।", ["Predecessor", "Prior"], ["Successor"], "Academic"),
    ("Anticipate", "/ænˈtɪs.ɪ.peɪt/", "Verb", "পূর্বানুমান করা, প্রত্যাশা করা", "We anticipate a surge in demand.", "আমরা চাহিদার এক উল্লম্ফন প্রত্যাশা করছি।", ["Expect", "Foresee"], [], "Spoken"),
    ("Antipathy", "/ænˈtɪp.ə.θi/", "Noun", "তীব্র অপছন্দ বা বিদ্বেষ", "She felt antipathy towards injustice.", "তিনি অবিচারের প্রতি তীব্র বিদ্বেষ অনুভব করেছিলেন।", ["Aversion", "Dislike"], ["Liking"], "BCS"),
    ("Antiquated", "/ˈæn.tɪ.kweɪ.tɪd/", "Adj", "সেকেলে, অপ্রচলিত", "The system relies on antiquated software.", "সিস্টেমটি সেকেলে সফটওয়্যারের ওপর নির্ভরশীল।", ["Obsolete", "Outdated"], ["Modern"], "IELTS"),
    ("Antithesis", "/ænˈtɪθ.ə.sɪs/", "Noun", "সম্পূর্ণ বিপরীত অবস্থা", "Poverty is the antithesis of wealth.", "দারিদ্র্য হলো প্রাচুর্যের সম্পূর্ণ বিপরীত।", ["Opposite", "Contrast"], [], "Academic"),
    ("Apathy", "/ˈæp.ə.θi/", "Noun", "উদাসীনতা, অনীহা", "Voter apathy concerns election board.", "ভোটারদের উদাসীনতা নির্বাচন কমিশনকে চিন্তিত করে।", ["Indifference", "Lethargy"], ["Enthusiasm"], "Spoken"),
    ("Apex", "/ˈeɪ.peks/", "Noun", "চূড়া, সর্বোচ্চ শিখর", "He reached the apex of power.", "তিনি ক্ষমতার সর্বোচ্চ শিখরে পৌঁছেছিলেন।", ["Peak", "Summit"], ["Nadir"], "BCS"),
    ("Aphorism", "/ˈæf.ə.rɪ.zəm/", "Noun", "নীতিবাক্য, সুবচন", "His talk featured a witty aphorism.", "তার বক্তব্যে একটি বুদ্ধিমত্তাপূর্ণ নীতিবাক্য ছিল।", ["Maxim", "Saying"], [], "Academic"),
    ("Appall", "/əˈpɔːl/", "Verb", "আতঙ্কিত করা, স্তম্ভিত করা", "The violence appalled peace-loving citizens.", "সহিংসতা শান্তিকামী নাগরিকদের স্তম্ভিত করেছিল।", ["Horrify", "Shock"], [], "IELTS"),
    ("Apparatus", "/ˌæp.əˈreɪ.təs/", "Noun", "যন্ত্রপাতি, প্রশাসনিক ব্যবস্থা", "The scientific apparatus worked well.", "বৈজ্ঞানিক যন্ত্রপাতিগুলো চমৎকার কাজ করেছিল।", ["Equipment", "Device"], [], "Academic"),
    ("Apparel", "/əˈpær.əl/", "Noun", "পোশাক-পরিচ্ছদ", "Store sells high-end winter apparel.", "দোকানটি মানসম্মত শীতকালীন পোশাক বিক্রি করে।", ["Clothing", "Garment"], [], "Spoken"),
    ("Appease", "/əˈpiːz/", "Verb", "সন্তুষ্ট করা, শান্ত করা", "Nothing could appease the angry crowd.", "কোনো কিছুই ক্রুদ্ধ জনতাকে শান্ত করতে পারেনি।", ["Pacify", "Soothe"], ["Provoke"], "BCS"),
    ("Appellation", "/ˌæp.əˈleɪ.ʃən/", "Noun", "উপাধি বা নাম", "City holds the appellation of City of Lights.", "শহরটি 'আলোর শহর' উপাধি ধারণ করে।", ["Name", "Title"], [], "Academic"),
    ("Appraise", "/əˈpreɪz/", "Verb", "মূল্যায়ন বা মান নিরূপণ করা", "An expert came to appraise property.", "একজন বিশেষজ্ঞ সম্পত্তি মূল্যায়ন করতে এসেছিলেন।", ["Evaluate", "Assess"], [], "IELTS"),
    ("Apprehend", "/ˌæp.rɪˈhend/", "Verb", "গ্রেপ্তার করা, হৃদয়ঙ্গম করা", "Police failed to apprehend thief.", "পুলিশ চোরকে গ্রেপ্তার করতে ব্যর্থ হয়েছিল।", ["Arrest", "Catch"], ["Release"], "BCS"),
    ("Apprehension", "/ˌæp.rɪˈhen.ʃən/", "Noun", "ভীতি, গ্রেফতার, আশঙ্কা", "She faced exam with apprehension.", "তিনি আশঙ্কার সাথে পরীক্ষার মুখোমুখি হয়েছিলেন।", ["Anxiety", "Dread"], ["Confidence"], "IELTS"),
    ("Approbation", "/ˌæp.rəˈbeɪ.ʃən/", "Noun", "অনুমোদন, প্রশংসা", "Proposal met with general approbation.", "প্রস্তাবটি সাধারণ প্রশংসা পেয়েছিল।", ["Approval", "Praise"], ["Disapproval"], "Academic"),
    ("Appropriate", "/əˈprəʊ.pri.eɪt/", "Verb", "বাজেয়াপ্ত বা নিজের করে নেওয়া", "Government may appropriate land for road.", "রাস্তার জন্য সরকার জমি বাজেয়াপ্ত করতে পারে।", ["Seize", "Take"], [], "BCS"),
    ("Aptitude", "/ˈæp.tɪ.tʃuːd/", "Noun", "স্বাভাবিক দক্ষতা", "She showed an aptitude for learning languages.", "তিনি ভাষা শেখার স্বাভাবিক দক্ষতা দেখিয়েছিলেন।", ["Talent", "Gift"], [], "Spoken"),
    ("Arbiter", "/ˈɑː.bɪ.tər/", "Noun", "সালিশকারী, বিচারক", "Court acts as final arbiter.", "আদালত চূড়ান্ত বিচারক হিসেবে কাজ করে।", ["Judge", "Refree"], [], "BCS"),
    ("Arbitrary", "/ˈɑː.bɪ.trər.i/", "Adj", "যথেচ্ছ, খামখেয়ালী", "Rule was completely arbitrary.", "নিয়মটি সম্পূর্ণ খামখেয়ালী ছিল।", ["Random", "Capricious"], ["Systematic"], "IELTS"),
    ("Arcane", "/ɑːˈkeɪn/", "Adj", "রহস্যময়, গুহ্য", "He explained arcane points of law.", "তিনি আইনের গুহ্য বিষয়গুলো ব্যাখ্যা করেছিলেন।", ["Mysterious", "Secret"], ["Common"], "Academic"),
    ("Archetype", "/ˈɑː.kɪ.taɪp/", "Noun", "মূল আদর্শ রূপ", "She is the archetype of dedicated teacher.", "তিনি একজন নিবেদিতপ্রাণ শিক্ষকের মূল আদর্শ।", ["Model", "Prototype"], [], "Academic"),
    ("Ardent", "/ˈɑː.dənt/", "Adj", "অনুরক্ত, পরম উৎসাহী", "He is an ardent fan of cricket.", "তিনি ক্রিকেটের এক পরম অনুরাগী ভক্ত।", ["Passionate", "Eager"], ["Apathetic"], "IELTS"),
    ("Arduous", "/ˈɑː.dʒu.əs/", "Adj", "কষ্টসাধ্য, দুর্গম", "Climbing mountain was arduous task.", "পাহাড় চড়া ছিল এক কষ্টসাধ্য কাজ।", ["Strenuous", "Difficult"], ["Easy"], "BCS"),
    ("Arrogance", "/ˈær.ə.ɡəns/", "Noun", "অহংকার, দম্ভ", "His arrogance ruined his career.", "তার দম্ভ তার ক্যারিয়ার ধ্বংস করেছিল।", ["Pride", "Haughtiness"], ["Humility"], "Spoken"),
    ("Articulate", "/ɑːˈtɪk.jə.leɪt/", "Verb", "স্পষ্টভাবে উচ্চারণ বা ব্যক্ত করা", "He struggled to articulate his feelings.", "সে তার অনুভূতি ব্যক্ত করতে হিমশিম খাচ্ছিল।", ["Express", "Utter"], [], "Spoken"),
    ("Artifact", "/ˈɑː.tɪ.fækt/", "Noun", "প্রাচীন প্রত্নবস্তু", "Museum displays ancient artifacts.", "জাদুঘরটি প্রাচীন প্রত্নবস্তু প্রদর্শন করে।", ["Relic", "Antiquity"], [], "Academic"),
    ("Artifice", "/ˈɑː.tɪ.fɪs/", "Noun", "চতুর কৌশল, প্রতারণা", "Political artifice misled voters.", "রাজনৈতিক কৌশল ভোটারদের বিভ্রান্ত করেছিল।", ["Trickery", "Deception"], ["Sincerity"], "Academic"),
    ("Artisan", "/ˌɑː.tɪˈzæn/", "Noun", "হস্তশিল্পী, কারিগর", "Local artisans sell handcrafted goods.", "স্থানীয় কারিগররা হস্তশিল্প বিক্রি করেন।", ["Craftsman"], [], "Spoken"),
    ("Ascendancy", "/əˈsen.dən.si/", "Noun", "আধিপত্য, প্রবল প্রভাব", "Company holds market ascendancy.", "কোম্পানিটি বাজারে আধিপত্য ধরে রেখেছে।", ["Dominance", "Supremacy"], [], "BCS"),
    ("Ascetic", "/əˈset.ɪk/", "Noun", "সন্ন্যাসী, কঠোর সংযমী", "The ascetic lives in mountain cave.", "সন্ন্যাসী পাহাড়ি গুহায় বাস করেন।", ["Hermit", "Monk"], [], "BCS"),
    ("Ascribe", "/əˈskraɪb/", "Verb", "কারণ বলে ধরা, আরোপ করা", "They ascribe failure to bad weather.", "তারা ব্যর্থতাকে খারাপ আবহাওয়ার ফল বলে ধরে নেন।", ["Attribute", "Assign"], [], "IELTS"),
    ("Asperity", "/æˈsper.ə.ti/", "Noun", "গলার রুক্ষতা, মেজাজের তিক্ততা", "He spoke with sharp asperity.", "তিনি তীব্র রুক্ষতার সাথে কথা বলেছিলেন।", ["Harshness", "Roughness"], ["Mildness"], "Academic"),
    ("Aspiration", "/ˌæs.pɪˈreɪ.ʃən/", "Noun", "উচ্চাকাঙ্ক্ষা, বড় লক্ষ্য", "She has aspirations to become doctor.", "তার ডাক্তার হওয়ার উচ্চাকাঙ্ক্ষা রয়েছে।", ["Ambition", "Goal"], [], "Spoken"),
    ("Assail", "/əˈseɪl/", "Verb", "আক্রমণ করা", "Critics assailed new policy.", "সমালোচকরা নতুন নীতি আক্রমণ করেছিলেন।", ["Attack", "Assault"], ["Defend"], "IELTS"),
    ("Assent", "/əˈsent/", "Verb", "সম্মতি দেওয়া", "King assented to new law.", "রাজা নতুন আইনে সম্মতি প্রকাশ করেন।", ["Agree", "Consent"], ["Refuse"], "BCS"),
    ("Assertive", "/əˈsɜː.tɪv/", "Adj", "আত্মবিশ্বাসী, স্বকীয় বক্তব্য প্রকাশী", "Be assertive in expressing opinion.", "মতামত প্রকাশের ক্ষেত্রে আত্মবিশ্বাসী হন।", ["Confident", "Decisive"], ["Timid"], "Spoken"),
    ("Assiduous", "/əˈsɪdʒ.u.əs/", "Adj", "অধ্যবসায়ী, পরিশ্রমী", "Success demands assiduous effort.", "সাফল্য একনিষ্ঠ পরিশ্রম দাবি করে।", ["Diligent", "Hardworking"], ["Lazy"], "BCS"),
    ("Assimilation", "/ˌæs.ɪ.mɪˈleɪ.ʃən/", "Noun", "আত্মীকরণ", "Assimilation of knowledge takes time.", "জ্ঞান আত্মীকরণ হতে সময় লাগে।", ["Absorption", "Integration"], [], "IELTS"),
    ("Assuage", "/əˈsweɪdʒ/", "Verb", "প্রশমিত করা, তীব্রতা কমানো", "Medicine assuaged his suffering.", "ওষুধটি তার কষ্ট প্রশমিত করেছিল।", ["Relieve", "Ease"], ["Worsen"], "IELTS"),
    ("Astonishment", "/əˈstɒn.ɪʃ.mənt/", "Noun", "বিস্ময়, হতবাক হওয়ার ভাব", "To my astonishment, he won race.", "আমার বিস্ময় জাগিয়ে সে দৌড়ে জিতেছিল।", ["Amazement", "Surprise"], [], "Spoken"),
    ("Astute", "/əˈstʃuːt/", "Adj", "দূরদর্শী, বিচক্ষণ", "She is an astute businesswoman.", "তিনি একজন অত্যন্ত দূরদর্শী ব্যবসায়ী নারী।", ["Shrewd", "Clever"], ["Foolish"], "BCS"),
    ("Asylum", "/əˈsaɪ.ləm/", "Noun", "আশ্রয়স্থল", "Refugees found asylum in neighbor country.", "শরণার্থীরা প্রতিবেশী দেশে আশ্রয় পেয়েছিল।", ["Sanctuary", "Refuge"], [], "BCS"),
    ("Atonement", "/əˈtəʊn.mənt/", "Noun", "পাপের প্রায়শ্চিত্ত", "He fasted in atonement for mistake.", "ভুলের প্রায়শ্চিত্ত হিসেবে সে রোজা রেখেছিল।", ["Repentance", "Penance"], [], "Academic"),
    ("Atrophy", "/ˈæt.rə.fi/", "Verb", "ক্ষয় হওয়া, শুকিয়ে যাওয়া", "Muscles atrophy if unused.", "ব্যবহার না করলে পেশি শুকিয়ে যায়।", ["Wither", "Decay"], ["Grow"], "Academic"),
    ("Attainable", "/əˈteɪ.nə.bəl/", "Adj", "অর্জনযোগ্য", "Set clear and attainable goals.", "স্পষ্ট ও অর্জনযোগ্য লক্ষ্য নির্ধারণ করুন।", ["Achievable", "Feasible"], ["Unattainable"], "Spoken"),
    ("Attenuate", "/əˈten.u.eɪt/", "Verb", "তীব্রতা হ্রাস করা", "Walls attenuate sound from outside.", "দেওয়ালগুলো বাইরের শব্দের তীব্রতা হ্রাস করে।", ["Weaken", "Reduce"], ["Strengthen"], "IELTS"),
    ("Attest", "/əˈtest/", "Verb", "সত্যতা দেওয়া, সত্যায়িত করা", "Documents attest to his honesty.", "নথিগুলো তার সততার প্রামাণিকতা দেয়।", ["Verify", "Confirm"], ["Deny"], "BCS"),
    ("Auditory", "/ˈɔː.dɪ.tər.i/", "Adj", "শ্রবণ সংক্রান্ত", "The hall has good auditory properties.", "হলটির শ্রবণ গুণাবলি চমৎকার।", ["Aural", "Hearing"], [], "Academic"),
    ("Augment", "/ɔːɡˈment/", "Verb", "বৃদ্ধি করা", "He takes tuition to augment income.", "আয় বাড়াতে সে টিউশনি করে।", ["Increase", "Boost"], ["Decrease"], "Spoken"),
    ("August", "/ɔːˈɡʌst/", "Adj", "মহিমান্বিত, সম্ভ্রান্ত", "We stood before august assembly.", "আমরা সম্ভ্রান্ত সমাবেশের সামনে দাঁড়িয়েছিলাম।", ["Majestic", "Noble"], [], "Academic"),
    ("Aura", "/ˈɔː.rə/", "Noun", "আবহের বলয়, বিশেষ অনুভূতি", "She has a radiant aura.", "তার এক উজ্জ্বল আকর্ষণীয় ব্যক্তিত্বের বলয় রয়েছে।", ["Atmosphere", "Glow"], [], "Spoken"),
    ("Auspicious", "/ɔːˈspɪʃ.əs/", "Adj", "শুভ, মঙ্গলজনক", "New year started on auspicious note.", "নতুন বছর এক শুভ সূচনায় শুরু হয়েছিল।", ["Promising", "Favorable"], ["Inauspicious"], "Spoken"),
    ("Austere", "/ɒsˈtɪər/", "Adj", "কঠোর, অনারম্বর", "The building has an austere style.", "ভবনটির এক অনারম্বর ধাঁচ রয়েছে।", ["Plain", "Severe"], ["Luxurious"], "BCS"),
    ("Authenticity", "/ˌɔː.θenˈtɪs.ə.ti/", "Noun", "খাঁটিত্ব, সততা", "We verified authenticity of document.", "আমরা দলিলের প্রামাণিকতা যাচাই করেছিলাম।", ["Genuineness", "Validity"], ["Falsity"], "IELTS"),
    ("Authoritarian", "/ɔːˌθɒr.ɪˈteər.i.ən/", "Adj", "স্বৈরাচারী, কর্তৃত্বপরায়ণ", "Country was under authoritarian rule.", "দেশটি স্বৈরাচারী শাসনের অধীনে ছিল।", ["Autocratic", "Dictatorial"], ["Democratic"], "BCS"),
    ("Autonomy", "/ɔːˈtɒn.ə.mi/", "Noun", "স্বায়ত্তশাসন", "University enjoys academic autonomy.", "বিশ্ববিদ্যালয়টি একাডেমিক স্বায়ত্তশাসন উপভোগ করে।", ["Independence", "Self-rule"], ["Dependence"], "BCS"),
    ("Auxiliary", "/ɔːɡˈzɪl.i.ər.i/", "Adj", "সহকারী", "An auxiliary engine was turned on.", "একটি সহকারী ইঞ্জিন চালু করা হয়েছিল।", ["Secondary", "Backup"], ["Primary"], "Academic"),
    ("Avalanche", "/ˈæv.əl.ɑːntʃ/", "Noun", "বরফধস, বিপুল পরিমাণ আগমন", "Office received avalanche of applications.", "অফিসে বিপুল আবেদনের বরফধস নেমেছিল।", ["Flood", "Torrent"], [], "Spoken"),
    ("Avarice", "/ˈæv.ər.ɪs/", "Noun", "অর্থলিপ্সা, ঘোর লোভ", "Avarice drives corruption.", "অর্থলিপ্সা দুর্নীতিকে পরিচালিত করে।", ["Greed", "Cupidity"], ["Generosity"], "BCS"),
    ("Avenge", "/əˈvendʒ/", "Verb", "প্রতিশোধ নেওয়া", "He swore to avenge the wrong.", "সে অন্যায়ের প্রতিশোধ নেওয়ার শপথ করেছিল।", ["Retaliate", "Revenge"], ["Forgive"], "Spoken"),
    ("Aversion", "/əˈvɜː.ʃən/", "Noun", "তীব্র অনিচ্ছা বা অপছন্দ", "He has aversion to risk.", "ঝুঁকির প্রতি তার তীব্র অনিচ্ছা রয়েছে।", ["Dislike", "Hatred"], ["Liking"], "IELTS"),
    ("Avert", "/əˈvɜːt/", "Verb", "এড়ানো, চোখ সরিয়ে নেওয়া", "A disaster was narrowly averted.", "একটি বিপর্যয় অল্পের জন্য এড়ানো গিয়েছিল।", ["Prevent", "Avoid"], [], "IELTS"),
    ("Avid", "/ˈæv.ɪd/", "Adj", "প্রবল অনুরাগী", "She is an avid reader.", "তিনি একজন প্রবল অনুরাগী পাঠক।", ["Eager", "Enthusiastic"], ["Apathetic"], "Spoken"),
    ("Avow", "/əˈvaʊ/", "Verb", "প্রকাশ্যে স্বীকার করা", "He avowed his innocence.", "তিনি প্রকাশ্যে নিজের নির্দোষিতা দাবি করেন।", ["Declare", "Assert"], ["Deny"], "Academic"),
    ("Axiom", "/ˈæk.si.əm/", "Noun", "স্বতঃসিদ্ধ সত্য", "It is an axiom that time is money.", "সময়ই অর্থ এটি এক স্বতঃসিদ্ধ সত্য।", ["Truth", "Maxim"], [], "Academic"),
    ("Baffle", "/ˈbæf.əl/", "Verb", "হতবুদ্ধি করা", "His bizarre behavior baffled all.", "তার অদ্ভুত আচরণ সবাইকে হতবুদ্ধি করেছিল।", ["Puzzle", "Confuse"], ["Clarify"], "IELTS"),
    ("Balk", "/bɔːk/", "Verb", "দ্বিধা করা, পিছিয়ে যাওয়া", "He balked at high price tag.", "উঁচু দাম দেখে সে পিছিয়ে গিয়েছিল।", ["Hesitate", "Refuse"], [], "Academic"),
    ("Banal", "/bəˈnɑːl/", "Adj", "মামুলি, সস্তা, গতানুগতিক", "Song had banal lyrics.", "গানটির কথা ছিল একবারে গতানুগতিক।", ["Trite", "Commonplace"], ["Original"], "IELTS"),
    ("Banish", "/ˈbæn.ɪʃ/", "Verb", "নির্বাসিত করা, দূর করা", "Banish fear from your mind.", "মন থেকে ভয় দূর করে দাও।", ["Exile", "Dismiss"], [], "BCS"),
    ("Banter", "/ˈbæn.tər/", "Noun", "ঠাট্টা-রসিকতা", "Friendly banter lightened mood.", "বান্ধব ঠাট্টা-রসিকতা পরিবেশ হালকা করেছিল।", ["Joking", "Teasing"], [], "Spoken"),
    ("Barricade", "/ˈbær.ɪ.keɪd/", "Noun", "প্রতিবন্ধক", "Police erected barricades around venue.", "পুলিশ অনুষ্ঠানস্থলের চারপাশে ব্যারিকেড দিয়েছিল।", ["Barrier", "Obstacle"], [], "Spoken"),
    ("Beacon", "/ˈbiː.kən/", "Noun", "বাতিঘর", "Light served as beacon for ships.", "আলোটি জাহাজের জন্য বাতিঘর হিসেবে কাজ করেছিল।", ["Signal", "Guide"], [], "Spoken"),
    ("Beguile", "/bɪˈɡaɪl/", "Verb", "মোহিত বা প্রতারিত করা", "He was beguiled by her smile.", "সে তার হাসিতে মোহিত হয়েছিল।", ["Charming", "Enchant"], [], "IELTS"),
    ("Belated", "/bɪˈleɪ.tɪd/", "Adj", "বিলম্বিত", "Accept my belated congratulations.", "আমার বিলম্বিত অভিনন্দন গ্রহণ করুন।", ["Late", "Delayed"], ["Early"], "Spoken"),
    ("Beleaguer", "/bɪˈliː.ɡər/", "Verb", "কোণঠাসা বা বিপন্ন করা", "Troops beleagured the town.", "সেনাদল শহরটিকে কোণঠাসা করেছিল।", ["Harass", "Besiege"], [], "Academic"),
    ("Belligerent", "/bəˈlɪdʒ.ər.ənt/", "Adj", "আক্রমণাত্মক, যুদ্ধংদেহী", "He took a belligerent stance.", "সে এক আক্রমণাত্মক অবস্থান নিয়েছিল।", ["Aggressive", "Hostile"], ["Peaceful"], "BCS"),
    ("Bemoan", "/bɪˈməʊn/", "Verb", "আক্ষেপ করা", "They bemoan lack of funds.", "তারা তহবিলের অভাব নিয়ে আক্ষেপ করে।", ["Lament", "Mourn"], [], "Academic"),
    ("Benefactor", "/ˈben.ɪ.fæk.tər/", "Noun", "দানবীর, উপকারী ব্যক্তি", "A generous benefactor funded school.", "একজন উদার দানবীর স্কুলে অর্থায়ন করেছিলেন।", ["Patron", "Donor"], [], "BCS"),
    ("Beneficiary", "/ˌben.ɪˈfɪʃ.ər.i/", "Noun", "উপকারভোগী", "Who is beneficiary of policy?", "পলিসির প্রধান উপকারভোগী কে?।", ["Recipient", "Heir"], [], "BCS"),
    ("Benevolence", "/bəˈnev.əl.əns/", "Noun", "দয়া, বদান্যতা", "Her benevolence touched hearts.", "তার বদান্যতা মানুষের হৃদয় স্পর্শ করেছিল।", ["Kindness", "Generosity"], ["Malevolence"], "Spoken"),
    ("Benign", "/bɪˈnaɪn/", "Adj", "ক্ষতিকর নয় এমন, সদয়", "Doctor confirmed tumor was benign.", "ডাক্তার নিশ্চিত করেন টিউমারটি ক্ষতিকর ছিল না।", ["Harmless", "Gentle"], ["Malignant"], "IELTS"),
    ("Bequeath", "/bɪˈkwiːð/", "Verb", "উইল করা", "Grandfather bequeathed house to him.", "দাদা তাকে বাড়িটি উইল করে দিয়েছিলেন।", ["Leave", "Bestow"], [], "BCS"),
    ("Berate", "/bɪˈreɪt/", "Verb", "ভর্ৎসনা করা", "Don't berate child in public.", "প্রকাশ্যে সন্তানকে ভর্ৎসনা করবেন না।", ["Scold", "Chide"], ["Praise"], "Academic"),
    ("Bereft", "/bɪˈreft/", "Adj", "বঞ্চিত", "Speech left us bereft of words.", "বক্তব্য আমাদের বাকরুদ্ধ করে দিয়েছিল।", ["Deprived", "Lacking"], [], "Academic"),
    ("Beseech", "/bɪˈsiːtʃ/", "Verb", "মিনতি করা", "I beseech you to reconsider.", "আমি আপনাকে পুনর্বিবেচনার আকুল মিনতি জানাচ্ছি।", ["Beg", "Implore"], [], "Academic"),
    ("Besiege", "/bɪˈsiːdʒ/", "Verb", "ঘিরে ফেলা, অবরোধ করা", "Fans besieged hotel entrance.", "ভক্তরা হোটেলের প্রবেশপথ ঘিরে ফেলেছিল।", ["Surround", "Encircle"], [], "BCS"),
    ("Bestow", "/bɪˈstəʊ/", "Verb", "উপাধি বা সম্মান প্রদান করা", "Medal was bestowed upon hero.", "বীরকে পদক প্রদান করা হয়েছিল।", ["Confer", "Grant"], [], "BCS"),
    ("Bewilder", "/bɪˈwɪl.dər/", "Verb", "হতভম্ব করা", "Directions bewildered driver.", "দিকনির্দেশনাগুলো চালককে হতভম্ব করেছিল।", ["Confuse", "Plex"], ["Clarify"], "Spoken"),
    ("Bias", "/ˈbaɪ.əs/", "Noun", "পক্ষপাতিত্ব", "Judge showed no bias.", "বিচারক কোনো পক্ষপাতিত্ব দেখাননি।", ["Prejudice", "Partiality"], ["Fairness"], "Spoken"),
    ("Bicker", "/ˈbɪk.ər/", "Verb", "ঝগড়া করা", "Children bicker over toys.", "শিশুরা খেলনা নিয়ে ঝগড়া করে।", ["Squabble", "Quarrel"], [], "Spoken"),
    ("Blatant", "/ˈbleɪ.tənt/", "Adj", "স্পষ্ট, ধৃষ্টতাপূর্ণ", "It was a blatant disregard of law.", "এটি ছিল আইনের স্পষ্ট অবমাননা।", ["Flagrant", "Obvious"], ["Subtle"], "IELTS"),
    ("Bleak", "/bliːk/", "Adj", "আশাহীন, নিরানন্দ", "Outlook remains bleak.", "পরিস্থিতি আশাহীন রয়ে গেছে।", ["Grim", "Dismal"], ["Bright"], "IELTS"),
    ("Blemish", "/ˈblem.ɪʃ/", "Noun", "ত্রুটি, দাগ", "His record is without a blemish.", "তার রেকর্ডে কোনো ত্রুটি বা দাগ নেই।", ["Flaw", "Defect"], [], "Spoken"),
    ("Blissful", "/ˈblɪs.fəl/", "Adj", "পরমানন্দদায়ক", "They spent blissful afternoon together.", "তারা একসাথে আনন্দদায়ক বিকেল কাটিয়েছিল।", ["Joyful", "Heavenly"], ["Miserable"], "Spoken"),
    ("Blunder", "/ˈblʌn.dər/", "Noun", "মারাত্মক ভুল", "Tactical blunder cost game.", "কৌশলগত মারাত্মক ভুল খেলায় হার দিয়েছিল।", ["Mistake", "Error"], [], "Spoken"),
    ("Blunt", "/blʌnt/", "Adj", "সোজা কথা বলা, ধারহীন", "She gave blunt response.", "সে সোজা সোজাসাপ্টা জবাব দিয়েছিল।", ["Direct", "Frank"], ["Subtle"], "Spoken"),
    ("Boisterous", "/ˈbɔɪ.stər.əs/", "Adj", "কোলাহলপূর্ণ", "Group was boisterous and lively.", "দলটি কোলাহলপূর্ণ ও সজীব ছিল।", ["Rowdy", "Noisy"], ["Quiet"], "Spoken"),
    ("Bolster", "/ˈbəʊl.stər/", "Verb", "শক্তিশালী করা", "News bolstered public confidence.", "সংবাদটি জনগণের আত্মবিশ্বাস বাড়িয়েছিল।", ["Strengthen", "Support"], ["Weaken"], "IELTS"),
    ("Bombastic", "/bɒmˈbæs.tɪk/", "Adj", "আড়ম্বরপূর্ণ", "His bombastic style turned audience off.", "তার আড়ম্বরপূর্ণ ভঙ্গি শ্রোতাদের বিরক্ত করেছিল।", ["Pompous", "High-sounding"], [], "Academic"),
    ("Boon", "/buːn/", "Noun", "আশীর্বাদ, বর", "Rain was a boon for farmers.", "বৃষ্টি কৃষকদের জন্য এক আশীর্বাদ ছিল।", ["Blessing", "Benefit"], ["Curse"], "Spoken"),
    ("Boorish", "/ˈbʊə.rɪʃ/", "Adj", "অসভ্য", "Apologize for boorish behavior.", "অসভ্য আচরণের জন্য ক্ষমা চান।", ["Coarse", "Crude"], ["Polite"], "Academic"),
    ("Bounteous", "/ˈbaʊn.ti.əs/", "Adj", "দানশীল, প্রচুর", "Earth yields bounteous harvest.", "পৃথিবী প্রচুর শস্য উপহার দেয়।", ["Abundant", "Generous"], [], "Academic"),
    ("Brevity", "/ˈbrev.ə.ti/", "Noun", "সংক্ষিপ্ততা", "Speaker valued brevity.", "বক্তা সংক্ষিপ্ততার কদর করতেন।", ["Conciseness", "Briefness"], [], "IELTS"),
    ("Brisk", "/brɪsk/", "Adj", "দ্রুত, চটপটে", "Walk at brisk pace.", "দ্রুত গতিতে হাঁটুন।", ["Quick", "Lively"], ["Slow"], "Spoken"),
    ("Brittle", "/ˈbrɪt.əl/", "Adj", "ভঙ্গুর", "Glass is very brittle.", "কাঁচ খুব ভঙ্গুর।", ["Fragile", "Breakable"], ["Durable"], "Spoken"),
    ("Broach", "/brəʊtʃ/", "Verb", "উত্থাপন করা", "She broached subject of salary raise.", "সে বেতন বাড়ানোর বিষয়টি উত্থাপন করেছিল।", ["Introduce", "Raise"], [], "IELTS"),
    ("Bucolic", "/bjuːˈkɒl.ɪk/", "Adj", "গ্রাম্য, মনোরম", "Region is famous for bucolic scenery.", "অঞ্চলটি চমৎকার গ্রাম্য দৃশ্যের জন্য বিখ্যাত।", ["Rural", "Rustic"], ["Urban"], "Academic"),
    ("Bulwark", "/ˈbʊl.wək/", "Noun", "সুরক্ষা প্রাচীর", "Law is bulwark of democracy.", "আইন হলো গণতন্ত্রের সুরক্ষা প্রাচীর।", ["Safeguard", "Shield"], [], "BCS"),
    ("Buoyant", "/ˈbɔɪ.ənt/", "Adj", "উৎফুল্ল, চাঙ্গা", "Investors are in buoyant mood.", "বিনিয়োগকারীরা উৎফুল্ল মেজাজে রয়েছেন।", ["Cheerful", "Upbeat"], [], "IELTS"),
    ("Burgeon", "/ˈbɜː.dʒən/", "Verb", "দ্রুত বিকশিত হওয়া", "Tech sector continues to burgeon.", "প্রযুক্তি খাত দ্রুত বিকশিত হচ্ছে।", ["Flourish", "Thrive"], [], "IELTS"),
    ("Burnish", "/ˈbɜː.nɪʃ/", "Verb", "উজ্জ্বল করা", "He sought to burnish reputation.", "তিনি তার সুনাম উজ্জ্বল করতে চেয়েছিলেন।", ["Polish", "Shine"], [], "Academic"),
    ("Buttress", "/ˈbʌt.rəs/", "Verb", "সমর্থন দেওয়া", "Use facts to buttress claim.", "দাবি সমর্থনে তথ্য ব্যবহার করুন।", ["Support", "Reinforce"], [], "IELTS"),
    ("Cajole", "/kəˈdʒəʊl/", "Verb", "মিষ্টি কথায় রাজি করানো", "He cajoled child into eating.", "সে শিশুকে মিষ্টি কথায় খাবার খাইয়েছিল।", ["Coax", "Wheedle"], [], "Academic"),
    ("Calamity", "/kəˈlæm.ə.ti/", "Noun", "মহাবিপর্যয়", "Earthquake was worst calamity.", "ভূমিকম্পটি ছিল ভয়ংকর মহাবিপর্যয়।", ["Disaster", "Catastrophe"], [], "BCS"),
    ("Callous", "/ˈkæl.əs/", "Adj", "অনুভূতিহীন, নির্দয়", "His callous attitude hurt all.", "তার নির্দয় মনোভাব সবাইকে কষ্ট দিয়েছিল।", ["Heartless", "Unfeeling"], ["Compassionate"], "IELTS"),
    ("Candor", "/ˈkæn.dər/", "Noun", "অকপটতা", "He spoke with complete candor.", "তিনি পূর্ণ অকপটতার সাথে কথা বলেছিলেন।", ["Frankness", "Honesty"], [], "IELTS"),
    ("Canonical", "/kəˈnɒn.ɪ.kəl/", "Adj", "স্বীকৃত প্রামাণিক", "Work is now canonical text.", "লেখাটি এখন স্বীকৃত প্রামাণিক টেক্সট।", ["Accepted", "Standard"], [], "Academic"),
    ("Cantankerous", "/kænˈtæŋ.kər.əs/", "Adj", "বদমেজাজী", "He became cantankerous in old age.", "বার্ধক্যে সে বদমেজাজী হয়ে উঠেছিল।", ["Irritable", "Bad-tempered"], [], "Academic"),
    ("Captivate", "/ˈkæp.tɪ.veɪt/", "Verb", "মোহিত করা", "Show captivated audience.", "শো দর্শকদের মোহিত করেছিল।", ["Enchant", "Charm"], [], "Spoken"),
    ("Castigate", "/ˈkæs.tɪ.ɡeɪt/", "Verb", "কঠোর ভর্ৎসনা করা", "Manager castigated team for errors.", "ম্যানেজার ভুলের জন্য টিমকে ভর্ৎসনা করেন।", ["Rebuke", "Scold"], [], "BCS"),
    ("Cataclysm", "/ˈkæt.ə.klɪ.zəm/", "Noun", "প্রলয়, ধ্বংস", "War brought economic cataclysm.", "যুদ্ধ অর্থনৈতিক বিপর্যয় এনেছিল।", ["Disaster", "Upheaval"], [], "Academic"),
    ("Catharsis", "/kəˈθɑː.sɪs/", "Noun", "মানসিক ভারমুক্তি", "Art provided emotional catharsis.", "শিল্পকলা আবেগীয় স্বস্তি দিয়েছিল।", ["Release", "Purification"], [], "Academic"),
    ("Caustic", "/ˈkɔː.stɪk/", "Adj", "কড়া, তিক্তভাষী", "He made caustic remarks.", "তিনি তিক্ত কড়া মন্তব্য করেছিলেন।", ["Sarcastic", "Biting"], [], "Academic"),
    ("Cede", "/siːd/", "Verb", "ছেড়ে দেওয়া", "Nations ceded land in treaty.", "চুক্তিতে দেশগুলো জমি ছেড়ে দিয়েছিল।", ["Surrender", "Yield"], [], "BCS"),
    ("Censure", "/ˈsen.ʃər/", "Noun", "আনুষ্ঠানিক নিন্দা", "Officer faced severe censure.", "কর্মকর্তা তীব্র নিন্দার মুখে পড়েছিলেন।", ["Condemnation", "Criticism"], [], "BCS"),
    ("Charisma", "/kəˈrɪz.mə/", "Noun", "সম্মোহনী শক্তি", "Leader has undeniable charisma.", "নেতার অস্বীকার্য সম্মোহনী ক্ষমতা রয়েছে।", ["Charm", "Magnetism"], [], "Spoken"),
    ("Charlatan", "/ˈʃɑː.lə.tən/", "Noun", "ভণ্ড ব্যক্তি", "He was exposed as a charlatan.", "সে ভণ্ড হিসেবে উন্মোচিত হয়েছিল।", ["Fraud", "Fake"], [], "Academic"),
    ("Chastise", "/tʃæsˈtaɪz/", "Verb", "শাস্তি দেওয়া", "Teacher chastised student.", "শিক্ষক ছাত্রকে শাস্তি দিয়েছিলেন।", ["Punish", "Scold"], [], "Academic"),
    ("Chauvinism", "/ˈʃəʊ.vɪ.nɪ.zəm/", "Noun", "উগ্র পক্ষপাত", "Reject male chauvinism.", "পুরুষালী উগ্র মনোভাব প্রত্যাখ্যান করুন।", ["Jingoism", "Bias"], [], "BCS"),
    ("Chicanery", "/ʃɪˈkeɪ.nər.i/", "Noun", "প্রতারণা", "Lawyer exposed legal chicanery.", "আইনজীবী আইনি চক্রান্ত ফাঁস করেছিলেন।", ["Deception", "Trickery"], [], "Academic"),
    ("Chronicle", "/ˈkrɒn.ɪ.kəl/", "Noun", "ইতিহাসের বিবরণ", "Read chronicle of war.", "যুদ্ধের ইতিহাসের বিবরণ পড়ুন।", ["Record", "History"], [], "Spoken"),
    ("Circumlocution", "/ˌsɜː.kəm.ləˈkjuː.ʃən/", "Noun", "ঘুরিয়ে কথা বলা", "Avoid useless circumlocution.", "অপ্রয়োজনীয় ঘুরিয়ে কথা বলা বাদ দিন।", ["Verbiage", "Indirectness"], [], "Academic"),
    ("Circumspect", "/ˈsɜː.kəm.spekt/", "Adj", "সতর্ক", "Be circumspect in investment.", "বিনিয়োগের ক্ষেত্রে সতর্ক থাকুন।", ["Cautious", "Prudent"], [], "IELTS"),
    ("Circumvent", "/ˌsɜː.kəmˈvent/", "Verb", "এড়িয়ে যাওয়া", "They circumvented security rules.", "তারা নিরাপত্তা নিয়ম এড়িয়ে গিয়েছিল।", ["Bypass", "Evade"], [], "BCS"),
    ("Clandestine", "/klænˈdes.tɪn/", "Adj", "গোপন", "They held clandestine talks.", "তারা গোপন কথা বলেছিল।", ["Secret", "Covert"], [], "IELTS"),
    ("Clemency", "/ˈklem.ən.si/", "Noun", "অনুকম্পা", "Judge showed clemency.", "বিচারক অনুকম্পা দেখিয়েছিলেন।", ["Mercy", "Leniency"], [], "BCS"),
    ("Coalesce", "/ˌkəʊ.əˈles/", "Verb", "মিশে যাওয়া", "Ideas coalesced into plan.", "ধারণাগুলো এক পরিকল্পনায় রূপ নেয়।", ["Merge", "Unite"], [], "IELTS"),
    ("Cogent", "/ˈkəʊ.dʒənt/", "Adj", "জোরালো যুক্তিযুক্ত", "Present a cogent argument.", "এক জোরালো যুক্তি উপস্থাপন করুন।", ["Convincing", "Compelling"], [], "IELTS"),
    ("Cognizant", "/ˈkɒɡ.nɪ.zənt/", "Adj", "অবগত", "Stay cognizant of facts.", "তথ্যগুলো সম্পর্কে সজাগ থাকুন।", ["Aware", "Conscious"], [], "IELTS"),
    ("Cohesion", "/kəʊˈhiː.ʒən/", "Noun", "একতা, সংহতি", "Group showed great cohesion.", "দলটি চমৎকার একতা দেখিয়েছিল।", ["Unity", "Togetherness"], [], "IELTS"),
    ("Collaborative", "/kəˈlæb.ər.ə.tɪv/", "Adj", "যৌথ", "It was collaborative effort.", "এটি একটি যৌথ প্রচেষ্টা ছিল।", ["Joint", "Cooperative"], [], "Spoken"),
    ("Colloquial", "/kəˈləʊ.kwi.əl/", "Adj", "কথ্য ভাষা", "Use colloquial expressions.", "কথ্য প্রকাশভঙ্গি ব্যবহার করুন।", ["Informal", "Casual"], [], "Spoken"),
    ("Collusion", "/kəˈluː.ʒən/", "Noun", "গোপন চক্রান্ত", "Acted in collusion.", "গোপন চক্রান্তে কাজ করা হয়েছিল।", ["Conspiracy", "Intrigue"], [], "BCS"),
    ("Commensurate", "/kəˈmen.sjər.ət/", "Adj", "সমানুপাতিক", "Pay commensurate with skill.", "দক্ষতার সাথে সামঞ্জস্য রেখে বেতন।", ["Proportional", "Equal"], [], "IELTS"),
    ("Commiserate", "/kəˈmɪz.a.reɪt/", "Verb", "সহমর্মিতা প্রকাশ", "Commiserate with friends.", "বন্ধুদের সাথে সহমর্মিতা প্রকাশ করুন।", ["Sympathize", "Console"], [], "Academic"),
    ("Compelling", "/kəmˈpel.ɪŋ/", "Adj", "অত্যন্ত আকর্ষণীয়", "Compelling reason to act.", "কাজ করার জোরালো কারণ।", ["Persuasive", "Convincing"], [], "IELTS"),
    ("Compendium", "/kəmˈpen.di.əm/", "Noun", "সংক্ষিপ্ত সংকলন", "A compendium of essays.", "প্রবন্ধের একটি সংকলন।", ["Summary", "Digest"], [], "Academic"),
    ("Complacent", "/kəmˈpleɪ.sənt/", "Adj", "আত্মতুষ্ট", "Don't become complacent.", "আত্মতুষ্ট হবেন না।", ["Self-satisfied", "Smug"], [], "IELTS"),
    ("Compliance", "/kəmˈplaɪ.əns/", "Noun", "অনুবর্তিতা", "Ensure full compliance.", "পূর্ণ অনুবর্তিতা নিশ্চিত করুন।", ["Obedience", "Conformity"], [], "BCS"),
    ("Complicity", "/kəmˈplɪs.ə.ti/", "Noun", "অপরাধের অংশীদারিত্ব", "Suspected of complicity.", "অপরাধের অংশীদারিত্বের সন্দেহ।", ["Involvement", "Collusion"], [], "BCS"),
    ("Composure", "/kəmˈpəʊ.ʒər/", "Noun", "মানসিক স্থিরতা", "Keep your composure.", "আপনার স্থিরতা বজায় রাখুন।", ["Calmness", "Poise"], [], "Spoken"),
    ("Compunction", "/kəmˈpʌŋk.ʃən/", "Noun", "অনুশোচনা", "Showed no compunction.", "কোনো অনুশোচনা দেখায়নি।", ["Remorse", "Regret"], [], "Academic"),
    ("Concede", "/kənˈsiːd/", "Verb", "স্বীকার করা", "Conceded the point.", "বিষয়টি স্বীকার করেছেন।", ["Admit", "Acknowledge"], [], "IELTS"),
    ("Conceited", "/kənˈsiː.tɪd/", "Adj", "অহংকারী", "He is very conceited.", "সে খুব অহংকারী।", ["Proud", "Arrogant"], [], "Spoken"),
    ("Conciliatory", "/kənˈsɪl.i.ə.tər.i/", "Adj", "সমঝোতামূলক", "A conciliatory gesture.", "একটি সমঝোতামূলক অঙ্গভঙ্গি।", ["Pacifying", "Appeasing"], [], "BCS"),
    ("Concise", "/kənˈsaɪs/", "Adj", "সংক্ষিপ্ত", "Keep it concise.", "এটি সংক্ষিপ্ত রাখুন।", ["Brief", "Succinct"], [], "Spoken"),
    ("Concur", "/kənˈkɜːr/", "Verb", "একমত হওয়া", "I concur with you.", "আমি আপনার সাথে একমত।", ["Agree", "Coincide"], [], "IELTS"),
    ("Condone", "/kənˈdəʊn/", "Verb", "ক্ষমা করা", "Cannot condone violence.", "সহিংসতা মেনে নেওয়া যায় না।", ["Overlook", "Forgive"], [], "BCS"),
    ("Conducive", "/kənˈdʒuː.sɪv/", "Adj", "অনুকূল", "Conducive to health.", "স্বাস্থ্যের জন্য অনুকূল।", ["Favorable", "Helpful"], [], "IELTS"),
    ("Confluence", "/ˈkɒn.flu.əns/", "Noun", "মিলনস্থল", "Confluence of ideas.", "ভাবনার মিলনস্থল।", ["Junction", "Convergence"], [], "Academic"),
    ("Confound", "/kənˈfaʊnd/", "Verb", "বিভ্রান্ত করা", "Confound the enemies.", "শত্রুদের বিভ্রান্ত করে দেওয়া।", ["Confuse", "Amaze"], [], "IELTS"),
    ("Congenial", "/kənˈdʒiː.ni.əl/", "Adj", "উপযোগী", "Congenial atmosphere.", "উপযোগী পরিবেশ।", ["Pleasant", "Compatible"], [], "Spoken"),
    ("Congregation", "/ˌkɒŋ.ɡrɪˈɡeɪ.ʃən/", "Noun", "সমাবেশ", "Large congregation.", "বিশাল সমাবেশ।", ["Gathering", "Assembly"], [], "Spoken"),
    ("Conjecture", "/kənˈdʒek.tʃər/", "Noun", "অনুমান", "Pure conjecture.", "বিশুদ্ধ অনুমান।", ["Guess", "Speculation"], [], "IELTS"),
    ("Conjure", "/ˈkʌn.dʒər/", "Verb", "হাজির করা", "Conjure up memories.", "স্মৃতি জাগিয়ে তোলা।", ["Evoke", "Summon"], [], "Spoken"),
    ("Connive", "/kəˈnaɪv/", "Verb", "মদদ দেওয়া", "Connived at crime.", "অপরাধে মদদ দিয়েছিল।", ["Conspire", "Collude"], [], "Academic"),
    ("Connoisseur", "/ˌkɒn.əˈsɜːr/", "Noun", "জহুরি", "Food connoisseur.", "খাবারের সূক্ষ্ম জহুরি।", ["Expert", "Judge"], [], "IELTS"),
    ("Consecrate", "/ˈkɒn.sɪ.kreɪt/", "Verb", "পবিত্র করা", "Consecrate the ground.", "জায়গাটি পবিত্র করা।", ["Sanctify", "Bless"], [], "BCS"),
    ("Consensus", "/kənˈsen.səs/", "Noun", "সর্বসম্মত মত", "Reach a consensus.", "একমতে পৌঁছান।", ["Agreement", "Accord"], [], "IELTS"),
    ("Console", "/kənˈsəʊl/", "Verb", "সান্ত্বনা দেওয়া", "Console the grieving.", "শোকাহতকে সান্ত্বনা দিন।", ["Comfort", "Soothe"], [], "Spoken"),
    ("Consolidate", "/kənˈsɒl.ɪ.deɪt/", "Verb", "একত্রিত করা", "Consolidate power.", "ক্ষমতা সুসংহত করা।", ["Strengthen", "Unite"], [], "IELTS"),
    ("Consonance", "/ˈkɒn.sə.nəns/", "Noun", "মিল", "In consonance with.", "এর সাথে মিল রেখে।", ["Agreement", "Harmony"], [], "Academic"),
    ("Conspicuous", "/kənˈspɪk.ju.əs/", "Adj", "স্পষ্ট", "Conspicuous success.", "চোখে পড়ার মতো সাফল্য।", ["Noticeable", "Prominent"], [], "IELTS"),
    ("Consternation", "/ˌkɒn.stəˈneɪ.ʃən/", "Noun", "আতঙ্ক", "Cause consternation.", "আতঙ্কের সৃষ্টি করা।", ["Dismay", "Alarm"], [], "Academic"),
    ("Constituent", "/kənˈstɪtʃ.u.ənt/", "Noun", "উপাদান", "Key constituent.", "প্রধান উপাদান।", ["Component", "Voter"], [], "BCS"),
    ("Constraint", "/kənˈstreɪnt/", "Noun", "সীমাবদ্ধতা", "Financial constraint.", "আর্থিক সীমাবদ্ধতা।", ["Limitation", "Restriction"], [], "IELTS"),
    ("Construe", "/kənˈstruː/", "Verb", "ব্যাখ্যা করা", "Construe correctly.", "সঠিকভাবে ব্যাখ্যা করুন।", ["Interpret", "Understand"], [], "BCS"),
    ("Consummate", "/ˈkɒn.sə.mət/", "Adj", "নিপুণ", "Consummate skill.", "নিপুণ দক্ষতা।", ["Flawless", "Perfect"], [], "BCS"),
    ("Contagious", "/kənˈteɪ.dʒəs/", "Adj", "সংক্রামক", "Contagious illness.", "সংক্রামক ব্যাধি।", ["Infectious", "Catching"], [], "Spoken"),
    ("Contemplate", "/ˈkɒn.təm.pleɪt/", "Verb", "চিন্তা করা", "Contemplate options.", "বিকল্পগুলো ভেবে দেখা।", ["Ponder", "Consider"], [], "Spoken"),
    ("Contempt", "/kənˈtempt/", "Noun", "অবজ্ঞা", "Show contempt.", "অবজ্ঞা প্রদর্শন করা।", ["Disdain", "Scorn"], [], "BCS"),
    ("Contend", "/kənˈtend/", "Verb", "দাবি করা", "Contend strongly.", "দৃঢ়ভাবে দাবি করা।", ["Assert", "Compete"], [], "IELTS"),
    ("Contention", "/kənˈten.ʃən/", "Noun", "বিতর্ক", "Bone of contention.", "বিতর্কের প্রধান বিষয়।", ["Dispute", "Argument"], [], "IELTS"),
    ("Contentious", "/kənˈten.ʃəs/", "Adj", "বিতর্কিত", "Contentious topic.", "বিতর্কিত বিষয়টি।", ["Controversial", "Quarrelsome"], [], "IELTS"),
    ("Contingency", "/kənˈtɪn.dʒən.si/", "Noun", "জরুরি সম্ভাবনা", "Contingency plan.", "জরুরি পরিকল্পনা।", ["Emergency", "Possibility"], [], "BCS"),
    ("Conundrum", "/kəˈnʌn.drəm/", "Noun", "জটিল ধাঁধা", "Economic conundrum.", "অর্থনৈতিক জটিল প্রশ্ন।", ["Puzzle", "Riddle"], [], "IELTS"),
    ("Convergence", "/kənˈvɜː.dʒəns/", "Noun", "মিলন", "Convergence of paths.", "পথের মিলন।", ["Union", "Merging"], [], "IELTS"),
    ("Convivial", "/kənˈvɪv.i.əl/", "Adj", "আনন্দমুখর", "Convivial gathering.", "আনন্দমুখর সমাবেশ।", ["Festive", "Friendly"], [], "Academic"),
    ("Convoluted", "/ˈkɒn.və.luː.tɪd/", "Adj", "প্যাঁচালো", "Convoluted story.", "প্যাঁচালো গল্প।", ["Complicated", "Intricate"], [], "IELTS"),
    ("Copious", "/ˈkəʊ.pi.əs/", "Adj", "প্রচুর", "Copious notes.", "প্রচুর নোট।", ["Abundant", "Plentiful"], [], "IELTS"),
    ("Cordial", "/ˈkɔː.di.əl/", "Adj", "আন্তরিক", "Cordial welcome.", "আন্তরিক অভ্যর্থনা।", ["Warm", "Friendly"], [], "Spoken"),
    ("Corporeal", "/kɔːˈpɔː.ri.əl/", "Adj", "শারীরিক", "Corporeal existence.", "শারীরিক অস্তিত্ব।", ["Bodily", "Physical"], [], "Academic"),
    ("Corroborate", "/kəˈrɒb.ə.reɪt/", "Verb", "প্রমাণ করা", "Corroborate evidence.", "প্রমাণ দিয়ে জোর দেওয়া।", ["Confirm", "Verify"], [], "IELTS"),
    ("Corrosive", "/kəˈrəʊ.sɪv/", "Adj", "ক্ষয়কারী", "Corrosive liquid.", "ক্ষয়কারী তরল।", ["Destructive", "Caustic"], [], "Academic"),
    ("Cosmopolitan", "/ˌkɒz.məˈpɒl.ɪ.tən/", "Adj", "বিশ্বজনীন", "Cosmopolitan city.", "বিশ্বজনীন শহর।", ["Global", "Universal"], [], "Spoken"),
    ("Covenant", "/ˈkʌv.ən.ənt/", "Noun", "পবিত্র চুক্তি", "Sacred covenant.", "পবিত্র অঙ্গীকার।", ["Pact", "Agreement"], [], "BCS"),
    ("Covert", "/ˈkʌv.ət/", "Adj", "গোপন", "Covert mission.", "গোপন অভিযান।", ["Secret", "Hidden"], [], "IELTS"),
    ("Covetous", "/ˈkʌv.ɪ.təs/", "Adj", "লোভী", "Covetous eyes.", "লোভী চোখ।", ["Greedy", "Envious"], [], "Academic"),
    ("Cower", "/ˈkaʊ.ər/", "Verb", "ভয়ে কুঁকড়ে যাওয়া", "Cower in fear.", "ভয়ে কুঁকড়ে যাওয়া।", ["Cringe", "Shrink"], [], "Spoken"),
    ("Cozen", "/ˈkʌz.ən/", "Verb", "ঠকানো", "Cozened out of money.", "টাকা ঠকিয়ে নেওয়া।", ["Deceive", "Cheat"], [], "Academic"),
    ("Credence", "/ˈkriː.dəns/", "Noun", "বিশ্বাসযোগ্যতা", "Give credence to.", "বিশ্বাস দেওয়া।", ["Belief", "Credibility"], [], "IELTS"),
    ("Credulous", "/ˈkredʒ.ə.ləs/", "Adj", "সহজ বিশ্বাসী", "Credulous nature.", "সহজ বিশ্বাসী স্বভাব।", ["Gullible", "Naïve"], [], "IELTS"),
    ("Crestfallen", "/ˈkrest.fɔː.lən/", "Adj", "মনভাঙ্গা", "Look crestfallen.", "মনভাঙ্গা দেখাচ্ছিল।", ["Dejected", "Disappointed"], [], "Academic"),
    ("Criteria", "/kraɪˈtɪə.ri.ə/", "Noun", "মানদণ্ড", "Selection criteria.", "নির্বাচনের মানদণ্ড।", ["Standards", "Benchmarks"], [], "Spoken"),
    ("Culpable", "/ˈkʌl.pə.bəl/", "Adj", "দণ্ডনীয়", "Culpable negligence.", "দণ্ডনীয় অবহেলা।", ["Guilty", "Blameworthy"], [], "BCS"),
    ("Culmination", "/ˌkʌl.mɪˈneɪ.ʃən/", "Noun", "চূড়ান্ত পরিণাম", "Culmination of effort.", "প্রচেষ্টার চরম শিখর।", ["Climax", "Peak"], [], "IELTS"),
    ("Cumulative", "/ˈkjuː.mjə.lə.tɪv/", "Adj", "ক্রমপুঞ্জীভূত", "Cumulative effect.", "ক্রমপুঞ্জীভূত প্রভাব।", ["Increasing", "Accumulated"], [], "Spoken"),
    ("Cusp", "/kʌsp/", "Noun", "সন্ধিক্ষণ", "On the cusp of change.", "পরিবর্তনের সন্ধিক্ষণে।", ["Threshold", "Verge"], [], "Spoken"),
    ("Curator", "/kjʊəˈreɪ.tər/", "Noun", "তত্ত্বাবধায়ক", "Museum curator.", "জাদুঘরের তত্ত্বাবধায়ক।", ["Keeper", "Custodian"], [], "Spoken"),
    ("Cursory", "/ˈkɜː.sər.i/", "Adj", "ভাসা-ভাসা", "Cursory glance.", "এক ভাসা-ভাসা দৃষ্টি।", ["Hasty", "Casual"], [], "IELTS"),
    ("Curtail", "/kərˈteɪl/", "Verb", "হ্রাস করা", "Curtail spending.", "খরচ হ্রাস করা।", ["Reduce", "Shorten"], [], "IELTS"),
    ("Cynicism", "/ˈsɪn.ɪ.sɪ.zəm/", "Noun", "নৈরাশবাদ", "Public cynicism.", "জনসাধারণের নৈরাশবাদ।", ["Skepticism", "Doubt"], [], "IELTS")
]

selected_300 = []
seen = set()

for item in word_bank:
    w = item[0].strip()
    key = w.lower()
    if key not in existing_words and key not in seen:
        seen.add(key)
        selected_300.append(item)
        if len(selected_300) >= 300:
            break

print(f"Total non-duplicate words collected: {len(selected_300)}")
