# -*- coding: utf-8 -*-
import json

with open('app/src/main/assets/dictionary_1000.json') as f:
    d = json.load(f)
existing = set(w['word'].strip().lower() for w in d)

law_data = [
    ("Jurisconsult", "Noun", "/ˌdʒʊə.rɪsˈkɒn.sʌlt/ (জুরিসকনসাল্ট)", "আইন বিশারদ বা অভিজ্ঞ আইনি উপদেষ্টা",
     ["Legal scholar", "Jurist"], [],
     "The constitutional committee consulted an eminent jurisconsult on electoral reforms.",
     "নির্বাচনী সংস্কার বিষয়ে সাংবিধানিক কমিটি একজন প্রখ্যাত আইন বিশারদের পরামর্শ গ্রহণ করেছে।", "Law & Governance"),
    ("Inculpatory", "Adjective", "/ɪnˈkʌl.pə.tər.i/ (ইনকালপেটরি)", "দোষ বা অপরাধ নির্দেশক প্রমাণাদি",
     ["Incriminating", "Damning"], ["Exculpatory"],
     "Prosecutors produced inculpatory surveillance footage linking the suspect to the theft.",
     "প্রসিকিউটররা সন্দেহভাজন ব্যক্তিকে চুরির সাথে যুক্ত করে এমন অপরাধ নির্দেশক ফুটেজ উপস্থাপন করেন।", "Law & Governance"),
    ("Exculpatory", "Adjective", "/ekˈskʌl.pə.tər.i/ (এক্সকালপেটরি)", "দোষমুক্তকারী বা নিরপরাধ প্রমাণকারী প্রমাণ",
     ["Vindicating", "Clearing"], ["Inculpatory"],
     "New biometric records provided crucial exculpatory evidence for the wrongly accused clerk.",
     "নতুন বায়োমেট্রিক রেকর্ড ভুলভাবে অভিযুক্ত কেরানির পক্ষে গুরুত্বপূর্ণ নির্দোষতার প্রমাণ দেয়।", "Law & Governance"),
    ("Remand", "Noun", "/rɪˈmɑːnd/ (রিমান্ড)", "জিজ্ঞাসাবাদের জন্য আসামিকে পুলিশ বা আদালতের হেফাজতে প্রেরণ",
     ["Custodial detention"], ["Bail"],
     "The magistrate granted a three-day police remand for intensive questioning.",
     "ম্যাজিস্ট্রেট নিবিড় জিজ্ঞাসাবাদের জন্য তিন দিনের পুলিশ রিমান্ড মঞ্জুর করেছেন।", "Law & Governance"),
    ("Subornation", "Noun", "/ˌsʌb.ɔːˈneɪ.ʃən/ (সাবর্নেশন)", "কাউকে প্ররোচিত করে আদালতে মিথ্যা সাক্ষ্য দেওয়ানো",
     ["Perjury inducement"], [],
     "The defense lawyer was disbarred after being convicted of witness subornation.",
     "সাক্ষীকে মিথ্যা সাক্ষ্যে প্ররোচিত করার অপরাধে বিবাদী পক্ষের আইনজীবীর সনদ বাতিল করা হয়।", "Law & Governance"),
    ("Misprision", "Noun", "/mɪsˈprɪʒ.ən/ (মিসপ্রিশন)", "গুরুতর অপরাধ জেনেও তা গোপন রাখা বা দায়িত্বে অবহেলা",
     ["Concealment of treason", "Official neglect"], [],
     "Failing to report financial embezzlement constitutes criminal misprision of felony.",
     "আর্থিক আত্মসাতের তথ্য জেনেও গোপন রাখা ফৌজদারি অপরাধের শামিল।", "Law & Governance"),
    ("Regicide", "Noun", "/ˈredʒ.ɪ.saɪd/ (রেজিসাইড)", "রাজহত্যা বা রাজার হত্যাকারী",
     ["Monarch killing"], [],
     "Conspirators plotted royal regicide to dismantle the dynastic empire.",
     "ষড়যন্ত্রকারীরা রাজবংশীয় সাম্রাজ্য ধ্বংসের লক্ষ্যে রাজহত্যার ষড়যন্ত্র করেছিল।", "History & Governance"),
    ("Patricide", "Noun", "/ˈpæt.rɪ.saɪd/ (প্যাট্রিসাইড)", "পিতৃহত্যা বা পিতার হত্যাকারী",
     ["Father killing"], [],
     "Ancient drama often explored tragic family hubris resulting in patricide.",
     "প্রাচীন নাটকে প্রায়শই পিতৃহত্যার মর্মান্তিক পারিবারিক ট্র্যাজেডি তুলে ধরা হতো।", "Literature & Arts"),
    ("Fratricide", "Noun", "/ˈfræt.rɪ.saɪd/ (ফ্র্যাট্রিসাইড)", "ভ্রাতৃহত্যা বা ভাইয়ের হত্যাকারী",
     ["Brother killing"], [],
     "The ruthless battle for the imperial crown ended in tragic fratricide.",
     "রাজমুকুটের নির্মম লড়াই শেষ পর্যন্ত এক মর্মান্তিক ভ্রাতৃহত্যায় রূপ নিয়েছিল।", "History & Governance"),
    ("Sororicide", "Noun", "/səˈrɒr.ɪ.saɪd/ (সোরোরিসাইড)", "ভগিনীহত্যা বা বোনের হত্যাকারী",
     ["Sister killing"], [],
     "Mythological folklore contains rare cautionary fables addressing sororicide.",
     "পৌরাণিক রূপকথায় ভগিনীহত্যার মতো অপরাধের বিষয়ে বিরল সতর্কতামূলক গল্প দেখা যায়।", "Literature & Arts"),
    ("Infanticide", "Noun", "/ɪnˈfæn.tɪ.saɪd/ (ইনফ্যান্টিসাইড)", "শিশুহত্যা বা নবজাতকের হত্যা",
     ["Child killing"], [],
     "Stringent child welfare laws strictly penalize any form of infanticide.",
     "কঠোর শিশু কল্যাণ আইন নবজাতক বা শিশুহত্যার যে কোনো রূপকে কঠোরভাবে শাস্তিযোগ্য করে।", "Law & Governance"),
    ("Homicide", "Noun", "/ˈhɒm.ɪ.saɪd/ (হোমিসাইড)", "মানবহত্যা বা কাউকে হত্যা করার অপরাধ",
     ["Manslaughter", "Murder"], [],
     "Forensic pathologists established that the unnatural death was a culpable homicide.",
     "ফরেনসিক চিকিৎসকরা নিশ্চিত করেছেন যে অস্বাভাবিক মৃত্যুটি ছিল একটি অপরাধমূলক মানবহত্যা।", "Law & Governance"),
    ("Suzerain", "Noun", "/ˈsuː.zə.reɪn/ (সুজেরেইন)", "অধীনস্ত রাষ্ট্রের ওপর আধিপত্য বিস্তারকারী পরাক্রমশালী রাজা",
     ["Feudal overlord"], ["Vassal"],
     "The small principality paid annual maritime tributes to its imperial suzerain.",
     "ক্ষুদ্র রাজ্যটি তার সাম্রাজ্যবাদী অভিভাবক রাষ্ট্রের প্রতি বার্ষিক কর প্রদান করত।", "History & Governance"),
    ("Vassal", "Noun", "/ˈvæs.əl/ (ভ্যাসাল)", "সামন্তপ্রভুর অধীনস্থ সামন্ত বা আজ্ঞাবহ রাজ্য",
     ["Feudal subject", "Subordinate state"], ["Suzerain"],
     "The conquered territory was reduced to a compliant vassal of the foreign crown.",
     "পরাজিত ভূখণ্ডটিকে বিদেশি রাজমুকুটের অধীনস্থ একটি অনুগত সামন্ত রাজ্যে পরিণত করা হয়েছিল।", "History & Governance"),
    ("Hegemon", "Noun", "/ˈhedʒ.ɪ.mɒn/ (হেজেমন)", "আঞ্চলিক বা বৈশ্বিক প্রধান আধিপত্য বিস্তারকারী পরাশক্তি",
     ["Dominant power", "Superpower"], [],
     "Smaller developing states formed a security coalition to counter the regional hegemon.",
     "আঞ্চলিক পরাশক্তির প্রভাব মোকাবিলা করতে ক্ষুদ্র উন্নয়নশীল রাষ্ট্রগুলো একটি নিরাপত্তা জোট গঠন করে।", "International Relations"),
    ("Demesne", "Noun", "/dɪˈmeɪn/ (ডিমিইন)", "সামন্তপ্রভুর নিজস্ব প্রত্যক্ষ খাসজমি",
     ["Manorial estate", "Private domain"], [],
     "The medieval manor retained extensive agricultural fields as the lord private demesne.",
     "মধ্যযুগীয় জমিদারির বিস্তীর্ণ কৃষিজমি সামন্তপ্রভুর নিজস্ব খাসজমি হিসেবে সংরক্ষিত ছিল।", "History & Governance"),
    ("Chattel", "Noun", "/ˈtʃæt.əl/ (চ্যাটেল)", "স্থাবর সম্পত্তি ছাড়া যেকোনো অস্থাবর ব্যক্তিগত সম্পদ",
     ["Movable property"], ["Real property"],
     "Commercial mortgage covenants explicitly distinguish between landed real estate and movable chattel.",
     "বাণিজ্যিক বন্ধকী চুক্তিতে স্থাবর জমি এবং অস্থাবর ব্যক্তিগত সম্পত্তির মধ্যে স্পষ্ট পার্থক্য করা হয়।", "Law & Governance"),
    ("Manumission", "Noun", "/ˌmæn.jəˈmɪʃ.ən/ (ম্যানিউমিশন)", "আইনিভাবে দাসত্ব বা পরাধীনতা থেকে মুক্তিদান",
     ["Emancipation", "Enfranchisement"], ["Enslavement"],
     "Historical records document the philanthropic manumission of indentured plantation laborers.",
     "ঐতিহাসিক নথিপত্র চুক্তিবদ্ধ বাগান শ্রমিকদের আইনি দাসত্বমুক্তির প্রমাণ বহন করে।", "History & Governance"),
    ("Plebeian", "Noun", "/plɪˈbiː.ən/ (প্লিবেয়ান)", "প্রাচীন রোমের সাধারণ বা নিম্নবর্গীয় নাগরিক",
     ["Commoner", "Proletarian"], ["Patrician"],
     "Ancient Roman tribunes were elected to champion the constitutional interests of the plebeian.",
     "সাধারণ নিম্নবর্গীয় নাগরিকদের সাংবিধানিক অধিকার রক্ষার জন্য প্রাচীন রোমে ট্রাইবিউন নির্বাচিত হতেন।", "History & Governance"),
    ("Patrician", "Noun", "/pəˈtrɪʃ.ən/ (প্যাট্রিশিয়ান)", "অভিজাত বংশীয় ব্যক্তি বা সমাজের উচ্চশ্রেণী",
     ["Aristocrat", "Nobleman"], ["Plebeian"],
     "The senate was predominantly dominated by conservative patrician landowners.",
     "সিনেট মূলত রক্ষণশীল অভিজাত ভূম্যধিকারীদের দ্বারা নিয়ন্ত্রিত ছিল।", "History & Governance"),
    ("Proletariat", "Noun", "/ˌprəʊ.lɪˈteə.ri.ət/ (প্রলেতারিয়েত)", "শ্রমজীবী সর্বহারা শ্রেণী",
     ["Working class", "Wage earners"], ["Bourgeoisie"],
     "Industrialization mobilized the urban industrial proletariat into organized labor trade unions.",
     "শিল্পায়ন শহরের শ্রমজীবী সর্বহারা শ্রেণীকে সংগঠিত শ্রমিক ইউনিয়নে রূপান্তর করেছিল।", "Economics"),
    ("Bourgeoisie", "Noun", "/ˌbʊəʒ.wɑːˈziː/ (বুর্জোয়া)", "পুঁজিবাদী মধ্যবিত্ত বা পুঁজিপতি শ্রেণী",
     ["Middle class", "Capitalist class"], ["Proletariat"],
     "Marxian economic theory analyzes class conflict between the proletariat and the bourgeoisie.",
     "মার্কসীয় অর্থনীতি সর্বহারা ও পুঁজিপতি বুর্জোয়া শ্রেণীর মধ্যকার দ্বন্দ্ব বিশ্লেষণ করে।", "Economics"),
    ("Demagoguery", "Noun", "/ˌdem.əˈɡɒɡ.ər.i/ (ডেম্যাগোগারি)", "আবেগ ও অন্ধ সংস্কার উসকে দিয়ে জনসমর্থন আদায়ের অপকৌশল",
     ["Rabble-rousing", "Populist agitation"], [],
     "Responsible journalism exposes political demagoguery aimed at dividing minority communities.",
     "দায়িত্বশীল সাংবাদিকতা সংখ্যালঘু সম্প্রদায়কে বিভক্ত করার রাজনৈতিক অপকৌশল উন্মোচিত করে।", "Law & Governance"),
    ("Plutocrat", "Noun", "/ˈpluː.tə.kræt/ (প্লুটোক্র্যাট)", "বিপুল সম্পদের জোরে রাজনীতি নিয়ন্ত্রণকারী ধনিক ব্যক্তি",
     ["Wealthy tycoon"], [],
     "Campaign finance limits prevent wealthy plutocrats from purchasing legislative elections.",
     "নির্বাচনী প্রচারণার ব্যয়সীমা ধনী পুঁজিপতিদের সংসদ নির্বাচন প্রভাবিত করার সুযোগ হ্রাস করে।", "Law & Governance"),
    ("Kleptocrat", "Noun", "/ˈklep.tə.kræt/ (ক্লেপ্টোক্র্যাট)", "রাষ্ট্রীয় কোষাগার লুণ্ঠনকারী দুর্নীতিবাজ শাসক",
     ["Corrupt ruler", "Thief administrator"], [],
     "International asset recovery agencies froze foreign luxury villas belonging to the kleptocrat.",
     "আন্তর্জাতিক সম্পদ পুনরুদ্ধার সংস্থা দুর্নীতিবাজ শাসকের বিদেশি বিলাসবহুল বাড়ি জব্দ করেছে।", "Law & Governance"),
    ("Gerontocracy", "Noun", "/ˌdʒer.ənˈtɒk.rə.si/ (জেরন্টোক্র্যাসি)", "বয়োবৃদ্ধ ব্যক্তিদের দ্বারা পরিচালিত শাসনব্যবস্থা",
     ["Rule by elderly"], [],
     "Youth activists demanded political term limits to reform the aging bureaucratic gerontocracy.",
     "তরুণ সমাজকর্মীরা প্রবীণ আমলাতান্ত্রিক শাসনব্যবস্থা সংস্কারে মেয়াদসীমা নির্ধারণের দাবি জানান।", "Law & Governance"),
    ("Meritocracy", "Noun", "/ˌmer.ɪˈtɒk.rə.si/ (মেরিটোক্র্যাসি)", "মেধা ও যোগ্যতার ভিত্তিতে পদায়ন ও সমাজব্যবস্থা",
     ["Talent-based system"], ["Nepotism", "Cronyism"],
     "Civil service examinations establish an impartial meritocracy for recruitment.",
     "সরকারি চাকুরির উন্মুক্ত পরীক্ষা যোগ্যতার ভিত্তিতে নিয়োগের এক নিরপেক্ষ ব্যবস্থা নিশ্চিত করে।", "BCS & Bank"),
    ("Technocracy", "Noun", "/tekˈnɒk.rə.si/ (টেকনোক্র্যাসি)", "বিশেষজ্ঞ ও প্রযুক্তিবিদদের দ্বারা পরিচালিত সরকার",
     ["Rule by technical experts"], [],
     "During economic crises, interim technocracy administrations formulate fiscal stabilizations.",
     "অর্থনৈতিক সংকটের সময় বিশেষজ্ঞ প্রযুক্তিবিদদের সমন্বয়ে গঠিত সরকার রাজস্ব সংস্কার প্রণয়ন করে।", "Economics"),
    ("Kakistocracy", "Noun", "/ˌkæk.ɪˈstɒk.rə.si/ (ক্যাকিস্টোক্র্যাসি)", "সবচেয়ে অযোগ্য ও নীতিহীন ব্যক্তিদের দ্বারা পরিচালিত নিকৃষ্ট সরকার",
     ["Government by worst"], ["Meritocracy"],
     "Citizens voiced deep anger against administrative corruption, warning of sliding into kakistocracy.",
     "প্রশাসনিক দুর্নীতিতে ক্ষুব্ধ নাগরিকরা সবচেয়ে অযোগ্যদের শাসনের বিপদের ব্যাপারে সতর্ক করেছিলেন।", "Law & Governance"),
    ("Ochlocracy", "Noun", "/ɒkˈlɒk.rə.si/ (অক্লোক্র্যাসি)", "উচ্ছৃঙ্খল জনতার শাসন বা মব রুল",
     ["Mob rule", "Mobocracy"], ["Rule of law"],
     "Constitutional judiciaries safeguard human dignity from degenerating into lawless ochlocracy.",
     "সাংবিধানিক বিচারব্যবস্থা নাগরিক মর্যাদাকে আইনহীন উচ্ছৃঙ্খল জনতার শাসনে রূপ নেওয়া থেকে রক্ষা করে।", "Law & Governance"),
    ("Viceroy", "Noun", "/ˈvaɪs.rɔɪ/ (ভাইসরয়)", "রাজার প্রতিনিধি হিসেবে কোনো উপনিবেশ শাসনকারী শাসক",
     ["Governor-general", "Colonial deputy"], [],
     "The historical palace served as the official administrative seat of the colonial viceroy.",
     "ঐতিহাসিক প্রাসাদটি ঔপনিবেশিক রাজপ্রতিনিধির সরকারি প্রশাসনিক কার্যালয় হিসেবে ব্যবহৃত হতো।", "History & Governance"),
    ("Attache", "Noun", "/əˈtæʃ.eɪ/ (অ্যাটাশে)", "দূতাবাসে নির্দিষ্ট বিষয়ের বিশেষজ্ঞ কূটনৈতিক সহকারী",
     ["Diplomatic specialist", "Liaison officer"], [],
     "The military attache coordinated joint peacekeeping exercises with defense officials.",
     "সামরিক কূটনৈতিক কর্মকর্তা প্রতিরক্ষা কর্মকর্তাদের সাথে যৌথ শান্তিরক্ষা মহড়া সমন্বয় করেন।", "International Relations"),
    ("Parley", "Noun", "/ˈpɑː.li/ (পার্লি)", "যুদ্ধরত দুই পক্ষের মধ্যে সমঝোতার উদ্দেশ্যে আনুষ্ঠানিক আলোচনা",
     ["Peace conference", "Truce talks"], [],
     "Opposing field commanders called an urgent parley to evacuate wounded soldiers safely.",
     "বিপরীতমুখী সেনাপতিরা আহত সৈন্যদের নিরাপদে সরাতে একটি জরুরি সাময়িক আলোচনার আহ্বান জানান।", "International Relations"),
    ("Capitulation", "Noun", "/kəˌpɪtʃ.əˈleɪ.ʃən/ (ক্যাপিচুলেশন)", "শর্তাধীনে আত্মসমর্পণ বা বশ্যতা স্বীকার",
     ["Surrender", "Yielding"], ["Resistance"],
     "Surrounded on all flanks, the besieged garrison signed a formal terms of capitulation.",
     "চারিদিক থেকে অবরুদ্ধ সামরিক ঘাঁটি শর্ত সাপেক্ষে আনুষ্ঠানিক আত্মসমর্পণে স্বাক্ষর করে।", "History & Governance"),
    ("Irredentism", "Noun", "/ˌɪr.ɪˈden.tɪ.zəm/ (ইরেডেন্টিজম)", "ঐতিহাসিক কারণে প্রতিবেশীর ভূখণ্ড নিজ দেশের বলে দাবি করার নীতি",
     ["Territorial revanchism"], [],
     "Aggressive cross-border irredentism ignited protracted diplomatic frictions in the region.",
     "সীমান্তবর্তী অঞ্চলে অন্যের ভূখণ্ড দাবির আগ্রাসী নীতি অঞ্চলে দীর্ঘমেয়াদী কূটনৈতিক দ্বন্দ্ব তৈরি করেছিল।", "International Relations"),
    ("Enclave", "Noun", "/ˈen.kleɪv/ (এনক্লেভ)", "অন্য দেশের ভূখণ্ড দ্বারা চারদিকে সম্পূর্ণ বেষ্টিত ছিটমহল",
     ["Pocket territory"], ["Exclave"],
     "The bilateral boundary accord successfully exchanged dozens of landlocked border enclaves.",
     "দ্বিপাক্ষিক সীমান্ত চুক্তি সফলভাবে কয়েক ডজন চারদিকে বেষ্টিত ছিটমহল বিনিময় সম্পন্ন করেছিল।", "International Relations"),
    ("Exclave", "Noun", "/ˈek.skleɪv/ (এক্সক্লেভ)", "মূল ভূখণ্ড থেকে বিচ্ছিন্ন কিন্তু নিজস্ব সার্বভৌম অংশ",
     ["Detached territory"], ["Enclave"],
     "Access to the coastal exclave required transit visas across the intervening nation.",
     "মূল ভূখণ্ড থেকে বিচ্ছিন্ন ছিটমহলে যেতে মধ্যবর্তী দেশের মধ্য দিয়ে ট্রানজিট ভিসার প্রয়োজন হতো।", "International Relations"),
    ("Delimitation", "Noun", "/diːˌlɪm.ɪˈteɪ.ʃən/ (ডিলিমিটেশন)", "মানচিত্রে বা চুক্তিতে জাতীয় সীমানা নির্ধারণ",
     ["Border fixing"], [],
     "Maritime boundary delimitation secured sovereign rights over vast undersea petroleum blocks.",
     "সামুদ্রিক সীমানা সুনির্দিষ্টকরণ সমুদ্রের বিপুল খনিজ তেল ব্লকের ওপর সার্বভৌম অধিকার নিশ্চিত করেছে।", "International Relations"),
    ("Blockade", "Noun", "/blɒkˈeɪd/ (ব্লকেড)", "শত্রুর বন্দর বা নগরীতে পণ্য ও যাতায়াত অবরুদ্ধকরণ",
     ["Naval siege", "Barricade"], [],
     "The naval blockade prevented fuel tankers from unloading contraband oil supplies.",
     "নৌ অবরোধ তেলবাহী জাহাজগুলোকে নিষিদ্ধ তেল সরবরাহ খালাস করতে বাধা দিয়েছিল।", "International Relations"),
    ("Boycott", "Noun", "/ˈbɔɪ.kɒt/ (বয়কট)", "প্রতিবাদ হিসেবে পণ্য বা সেবা বর্জন",
     ["Embargo", "Ban"], ["Patronage"],
     "Consumers organized a nationwide commercial boycott against companies utilizing child labor.",
     "শিশুশ্রম ব্যবহারকারী প্রতিষ্ঠানগুলোর বিরুদ্ধে ক্রেতারা দেশব্যাপী বাণিজ্যিক বর্জনের ডাক দেন।", "Economics"),
    ("Reparations", "Noun", "/ˌrep.əˈreɪ.ʃənz/ (রেপারেশনস)", "যুদ্ধের পর বিজিত দেশকে বিজয়ী পক্ষের প্রদত্ত ক্ষতিপূরণ",
     ["War compensation"], [],
     "The international tribunal ordered the aggressor state to pay substantial war reparations.",
     "আন্তর্জাতিক আদালত আগ্রাসী রাষ্ট্রকে যুদ্ধের ক্ষয়ক্ষতির বিপুল ক্ষতিপূরণ প্রদানের নির্দেশ দেয়।", "International Relations"),
    ("Rescript", "Noun", "/ˈriː.skrɪpt/ (রিস্ক্রিপ্ট)", "রাষ্ট্রপ্রধান বা সম্রাটের আনুষ্ঠানিক লিখিত সরকারি আদেশ",
     ["Imperial edict", "Official mandate"], [],
     "The historical royal rescript granted religious autonomy to linguistic minorities.",
     "ঐতিহাসিক রাজকীয় লিখিত আদেশটি ভাষাগত সংখ্যালঘুদের ধর্মীয় স্বায়ত্তশাসন প্রদান করেছিল।", "History & Governance"),
    ("Hustings", "Noun", "/ˈhʌs.tɪŋz/ (হাস্টিংস)", "নির্বাচনী প্রচারণার জনসভা বা প্রচারমঞ্চ",
     ["Campaign platform", "Election rallies"], [],
     "Candidates crossed the nation on the hustings outlining employment generation agendas.",
     "প্রার্থীরা কর্মসংস্থান সৃষ্টির প্রতিশ্রুতি তুলে ধরতে নির্বাচনী প্রচারমঞ্চে দেশ চষে বেড়ান।", "Law & Governance"),
    ("Bipartisan", "Adjective", "/baɪˌpɑː.tɪˈzæn/ (বাইপার্টিজান)", "উভয় প্রধান রাজনৈতিক দলের ঐক্যমত্যভিত্তিক",
     ["Two-party", "Cross-party"], ["Partisan"],
     "The climate resilience bill passed with rare bipartisan legislative support.",
     "জলবায়ু অভিযোজন বিলটি দুই প্রধান রাজনৈতিক দলের বিরল ঐক্যমত্যে সংসদে পাস হয়েছিল।", "Law & Governance"),
    ("Nonpartisan", "Adjective", "/nɒnˈpɑː.tɪ.zæn/ (ননপার্টিজান)", "কোনো রাজনৈতিক দলের সাথে যুক্ত নয় বা নিরপেক্ষ",
     ["Neutral", "Independent", "Objective"], ["Partisan"],
     "Election monitoring requires an internationally certified nonpartisan oversight body.",
     "নির্বাচন পর্যবেক্ষণে আন্তর্জাতিকভাবে স্বীকৃত নিরপেক্ষ তদারকি সংস্থার প্রয়োজন হয়।", "Law & Governance"),
    ("Suborn", "Verb", "/səˈbɔːn/ (সাবর্ন)", "ঘুষ বা প্রলোভন দিয়ে কাউকে অসৎ কাজে রাজি করানো",
     ["Bribe", "Corrupt"], [],
     "Investigators uncovered an underworld attempt to suborn customs border guards.",
     "তদন্তকারীরা সীমান্ত শুল্করক্ষীদের ঘুষ দিয়ে হাত করার একটি অপরাধী চক্রের অপচেষ্টা উন্মোচন করেন।", "Law & Governance"),
    ("Replevin", "Noun", "/rɪˈplev.ɪn/ (রিপ্লেভিন)", "অবৈধভাবে আটকে রাখা সম্পত্তি আদালতের আদেশে পুনরুদ্ধার মামলা",
     ["Recovery of goods"], [],
     "The equipment owner filed a writ of replevin to reclaim leased factory generators.",
     "যন্ত্রপাতির মালিক ইজারা দেওয়া জেনারেটর ফেরত পেতে আদালতে একটি পুনরুদ্ধার মামলা দায়ের করেন।", "Law & Governance"),
    ("Interpleader", "Noun", "/ˌɪn.təˈpliː.dər/ (ইন্টারপ্লিডার)", "তৃতীয় পক্ষের মাধ্যমে দুই দাবীদারের মধ্যে প্রকৃত মালিক নির্ধারণের বিচারিক প্রক্রিয়া",
     ["Dispute stakeholders litigation"], [],
     "The insurance agency initiated an interpleader suit to determine lawful beneficiaries.",
     "প্রকৃত উত্তরাধিকারী নির্ধারণের জন্য বীমা প্রতিষ্ঠানটি আদালতে একটি ইন্টারপ্লিডার মামলা দায়ের করে।", "Law & Governance"),
    ("Champerty", "Noun", "/ˈtʃæm.pə.ti/ (চ্যাম্পার্টি)", "মামলার জয়ের অংশের আশায় অন্যের মামলায় আর্থিক সহায়তা দানের অবৈধ চুক্তি",
     ["Illegal litigation financing"], [],
     "Common law traditions prohibit speculative champerty to prevent commercial lawsuit abuse.",
     "সাধারণ আইন ব্যবস্থা মামলার অপব্যবহার রোধে মামলার লভ্যাংশভিত্তিক বেআইনি অর্থায়ন নিষিদ্ধ করে।", "Law & Governance"),
    ("Barratry", "Noun", "/ˈbær.ə.tri/ (ব্যারাট্রি)", "লাভের উদ্দেশ্যে বারবার অযথা মামলা দায়েরের অপরাধ",
     ["Frivolous vexatious litigation"], [],
     "The vexatious attorney was formally reprimanded by the bar council for habitual barratry.",
     "অযৌক্তিকভাবে বারবার ভুয়া মামলা দায়েরের অপরাধে আইনজীবী সমিতিতে আইনজীবীকে ভর্ৎসনা করা হয়।", "Law & Governance"),
    ("Embracery", "Noun", "/ɪmˈbreɪ.sər.i/ (এমব্রেসারি)", "ঘুষ বা ভয় দেখিয়ে বিচারক বা জুরিদের প্রভাবিত করার ফৌজদারি অপরাধ",
     ["Jury tampering"], [],
     "Bribing court officials constitutes a severe penal felony categorized as embracery.",
     "আদালতের কর্মকর্তাদের ঘুষ দিয়ে রায় প্রভাবিত করার অপচেষ্টা বিচার প্রভাবিত করার অপরাধ হিসেবে গণ্য।", "Law & Governance"),
    ("Misfeasance", "Noun", "/mɪsˈfiː.zəns/ (মিসফিজ্যান্স)", "আইনসম্মত কাজ ত্রুটিপূর্ণ বা ক্ষতিকরভাবে সম্পাদন",
     ["Improper performance of legal duty"], [],
     "Contractors were held liable for civic misfeasance due to defective road paving.",
     "ত্রুটিপূর্ণভাবে রাস্তা নির্মাণের কারণে ঠিকাদারদের ওপর ক্ষতিকর দায়িত্ব পালনের দায় চাপানো হয়।", "Law & Governance"),
    ("Nonfeasance", "Noun", "/nɒnˈfiː.zəns/ (ননফিজ্যান্স)", "আইনগত দায়িত্ব পালন থেকে সম্পূর্ণরূপে বিরত থাকা বা ব্যর্থতা",
     ["Failure to act", "Omission"], [],
     "The civic supervisor was dismissed for nonfeasance after ignoring public flood warnings.",
     "বন্যার বারবার সতর্কতা উপেক্ষা করে দায়িত্বে নিষ্ক্রিয় থাকার অপরাধে সুপারভাইজারকে বরখাস্ত করা হয়।", "Law & Governance"),
    ("Defalcator", "Noun", "/ˈdiː.fælˌkeɪ.tər/ (ডিফ্যালকেটর)", "সরকারি বা করপোরেট তহবিল তছরুপকারী অপরাধী",
     ["Embezzler", "Financial misappropriator"], [],
     "Police tracked the fugitive bank defalcator attempting to flee to an offshore haven.",
     "পুলিশ ব্যাংক তহবিল তছরুপকারী পলাতক অপরাধীকে বিদেশি আশ্রয়ে পালানোর সময় আটক করে।", "Banking & Finance"),
    ("Embezzler", "Noun", "/ɪmˈbez.lər/ (এমবেজলার)", "দায়িত্বে থাকা অর্থ আত্মসাৎকারী ব্যক্তি",
     ["Peculator", "Thief"], [],
     "Auditors gathered clear financial records convicting the corporate accounts embezzler.",
     "নিরীক্ষকেরা করপোরেট হিসাব বিভাগের অর্থ আত্মসাৎকারীকে দোষী সাব্যস্ত করতে স্পষ্ট প্রমাণ সংগ্রহ করেন।", "Banking & Finance"),
    ("Prevaricator", "Noun", "/prɪˈvær.ɪ.keɪ.tər/ (প্রিভ্যারিকেটর)", "সত্যকে চতুরভাবে ঘুরিয়ে মিথ্যা বা বিভ্রান্তি সৃষ্টিকারী",
     ["Equivocator", "Liar"], ["Truth teller"],
     "The cross-examining attorney trapped the prevaricator in a web of contradictory answers.",
     "জেরা চলাকালীন আইনজীবী চতুর মিথ্যাবাদীকে তার নিজের পরস্পরবিরোধী বক্তব্যের জালে আটকে ফেলেন।", "Law & Governance"),
    ("Perjurer", "Noun", "/ˈpɜː.dʒər.ər/ (পারজারার)", "আদালতে শপথপূর্বক মিথ্যা সাক্ষ্য প্রদানকারী ব্যক্তি",
     ["False witness"], [],
     "The court sentenced the convicted perjurer to rigorous administrative detention.",
     "আদালত মিথ্যা সাক্ষ্যদানকারী অপরাধীকে সশ্রম প্রশাসনিক কারাদণ্ডে দণ্ডিত করেছে।", "Law & Governance"),
    ("Inquisitor", "Noun", "/ɪnˈkwɪz.ɪ.tər/ (ইনকুইজিটর)", "কঠোর ও আক্রমণাত্মক প্রশ্নকর্তা বা তদন্তকারী",
     ["Interrogator", "Investigator"], [],
     "The parliamentary inquisitor pressed the minister for specific dates regarding contract awards.",
     "সংসদীয় তদন্তকারী কর্মকর্তা চুক্তি বরাদ্দের সুনির্দিষ্ট তারিখ জানতে মন্ত্রীর ওপর চাপ সৃষ্টি করেন।", "Law & Governance"),
    ("Magistracy", "Noun", "/ˈmædʒ.ɪ.strə.si/ (ম্যাজিস্ট্রেসি)", "বিচারিক ম্যাজিস্ট্রেটের পদ, পদমর্যাদা বা সামগ্রিক বিচারিক স্তর",
     ["Judicial bench", "Judiciary office"], [],
     "The executive civil service separation strengthened the autonomy of the judicial magistracy.",
     "প্রশাসন থেকে বিচার বিভাগ পৃথকীকরণ বিচারিক ম্যাজিস্ট্রেসির স্বাধীনতাকে সুসংহত করেছে।", "Law & Governance"),
    ("Constabulary", "Noun", "/kənˈstæb.jʊ.lər.i/ (কনস্ট্যাবুলারি)", "একটি নির্দিষ্ট অঞ্চলের পুলিশ বা আইনশৃঙ্খলা রক্ষাকারী বাহিনী",
     ["Police force"], [],
     "The provincial constabulary restored civil order following intense border riots.",
     "সীমান্তে তীব্র বিশৃঙ্খলা দেখা দিলে প্রাদেশিক পুলিশ বাহিনী নাগরিক শৃঙ্খলা পুনরুদ্ধার করে।", "Law & Governance"),
    ("Custodian", "Noun", "/kʌsˈtəʊ.di.ən/ (কাস্টোডিয়ান)", "সম্পদ বা দলিলের আইনি হেফাজতকারী বা সংরক্ষক",
     ["Guardian", "Keeper"], [],
     "The heritage foundation serves as the legal custodian of rare independence war archives.",
     "ঐতিহ্য সংরক্ষণ ট্রাস্ট স্বাধীনতা যুদ্ধের দুর্লভ নথিপত্রের আইনগত হেফাজতকারী হিসেবে দায়িত্ব পালন করে।", "BCS & Bank"),
    ("Benefactor", "Noun", "/ˈben.ɪˌfæk.tər/ (বেনেফ্যাক্টর)", "জনকল্যাণে আর্থিক সাহায্য বা অনুদান প্রদানকারী হিতৈষী",
     ["Patron", "Donor"], [],
     "An anonymous benefactor donated modern robotic dialysis suites to the medical college.",
     "একজন অজ্ঞাত হিতৈষী ব্যক্তি মেডিকেল কলেজে আধুনিক রোবোটিক ডায়ালাইসিস ইউনিট দান করেছেন।", "BCS & Bank"),
    ("Testator", "Noun", "/tesˈteɪ.tər/ (টেস্টেটর)", "আইনগতভাবে উইল বা ইচ্ছাপত্র সম্পাদনকারী পুরুষ ব্যক্তি",
     ["Will maker"], [],
     "The signed will confirmed that the testator was of sound mind during execution.",
     "স্বাক্ষরিত উইলটি নিশ্চিত করেছে যে সম্পাদনকালে উইলকারী সম্পূর্ণ সুস্থ মানসিক অবস্থার অধিকারী ছিলেন।", "Law & Governance"),
    ("Testatrix", "Noun", "/tesˈteɪ.trɪks/ (টেস্টেট্রিক্স)", "আইনগতভাবে উইল বা ইচ্ছাপত্র সম্পাদনকারী নারী ব্যক্তি",
     ["Female will maker"], [],
     "The testatrix bequeathed her estate to establish a rural nursing academy.",
     "নারী উইলকারী তাঁর সমুদয় সম্পত্তি একটি গ্রামীণ নার্সিং একাডেমি প্রতিষ্ঠার জন্য দান করে যান।", "Law & Governance"),
    ("Intestate", "Adjective", "/ɪnˈtes.teɪt/ (ইনটেস্টেট)", "কোনো বৈধ উইল না রেখে মৃত্যুবরণ করা",
     ["Without a will"], ["Testate"],
     "When an individual passes intestate, ancestral properties are partitioned under statutory personal laws.",
     "কোনো ব্যক্তি উইল ছাড়া মারা গেলে পৈতৃক সম্পত্তি পারিবারিক আইন অনুযায়ী বণ্টন করা হয়।", "Law & Governance"),
    ("Executrix", "Noun", "/ɪɡˈzek.jʊ.trɪks/ (এক্সিকিউট্রিক্স)", "উইল বাস্তবায়নকারী নারী সম্পাদনকারী",
     ["Female executor"], [],
     "The court confirmed her appointment as the sole executrix of her late father estate.",
     "আদালত তাঁর প্রয়াত পিতার উইলের একমাত্র নারী সম্পাদনকারী হিসেবে তাঁর নিয়োগ নিশ্চিত করেছে।", "Law & Governance"),
    ("Appellant", "Noun", "/əˈpel.ənt/ (অ্যাপিলেল্যান্ট)", "নিম্ন আদালতের রায়ের বিরুদ্ধে উচ্চ আদালতে আপিলকারী ব্যক্তি",
     ["Appealing party", "Petitioner"], ["Appellee"],
     "The appellant argued that the magistrate court overlooked critical material eyewitness records.",
     "আপিলকারী যুক্তি দেন যে নিম্ন আদালত প্রত্যক্ষদর্শীর অত্যন্ত গুরুত্বপূর্ণ সাক্ষ্য প্রমাণ উপেক্ষা করেছে।", "Law & Governance"),
    ("Appellee", "Noun", "/ˌæp.əˈliː/ (অ্যাপেলি)", "আপিল মামলার বিবাদী বা যার বিরুদ্ধে আপিল করা হয়েছে",
     ["Respondent in appeal"], ["Appellant"],
     "Attorneys for the appellee urged the supreme court to uphold the high court verdict.",
     "আপিলের বিবাদী পক্ষের আইনজীবীরা হাইকোর্টের রায় বহাল রাখার জন্য সুপ্রিম কোর্টের কাছে আবেদন জানান।", "Law & Governance"),
    ("Petitioner", "Noun", "/pəˈtɪʃ.ən.ər/ (পিটিশনার)", "আদালতে রিট বা আনুষ্ঠানিক আবেদন দাখিলকারী পক্ষ",
     ["Complainant", "Applicant"], ["Respondent"],
     "The environmental petitioner challenged the clearance granted to the riverfront factory.",
     "পরিবেশবাদী আবেদনকারী নদীর তীরের কারখানাটিকে দেওয়া পরিবেশগত ছাড়পত্রের বৈধতা চ্যালেঞ্জ করেন।", "Law & Governance"),
    ("Respondent", "Noun", "/rɪˈspɒn.dənt/ (রেসপনডেন্ট)", "রিট বা মামলায় নোটিশপ্রাপ্ত বিবাদী পক্ষ",
     ["Defendant in writ"], ["Petitioner"],
     "The court directed the state respondent to submit a compliance report within two weeks.",
     "আদালত রাষ্ট্রপক্ষের বিবাদীকে দুই সপ্তাহের মধ্যে নির্দেশ প্রতিপালনের প্রতিবেদন দাখিলের নির্দেশ দেন।", "Law & Governance"),
    ("Deponent", "Noun", "/dɪˈpəʊ.nənt/ (ডিপোনেন্ট)", "আদালতে শপথপূর্বক লিখিত জবানবন্দি প্রদানকারী ব্যক্তি",
     ["Affidavit maker", "Witness"], [],
     "The deponent attested that the corporate accounts ledger was maintained in good faith.",
     "শপথকারী ব্যক্তি সাক্ষ্য দেন যে করপোরেট হিসাবের খাতা সৎ উদ্দেশ্যে যথাযথভাবে সংরক্ষণ করা হয়েছিল।", "Law & Governance"),
    ("Affiant", "Noun", "/əˈfaɪ.ənt/ (অ্যাফায়্যান্ট)", "হলফনামা বা শপথনামায় স্বাক্ষরকারী ব্যক্তি",
     ["Sworn declarant"], [],
     "The magistrate verified the national identification card presented by the legal affiant.",
     "ম্যাজিস্ট্রেট হলফনামা প্রদানকারী ব্যক্তির জাতীয় পরিচয়পত্রের সঠিকতা যাচাই করেন।", "Law & Governance"),
    ("Interrogatory", "Noun", "/ˌɪn.təˈrɒɡ.ə.tər.i/ (ইন্টারোগাটরি)", "শুনানির পূর্বে প্রতিপক্ষকে দেওয়া আদালতের আনুষ্ঠানিক লিখিত প্রশ্নমালা",
     ["Written discovery questions"], [],
     "Civil defense lawyers submitted a detailed interrogatory seeking asset disclosure.",
     "আইনজীবীরা সম্পত্তির তথ্য প্রকাশের দাবি জানিয়ে একটি বিশদ আনুষ্ঠানিক লিখিত প্রশ্নমালা দাখিল করেন।", "Law & Governance"),
    ("Impanel", "Verb", "/ɪmˈpæn.əl/ (ইম্প্যানেল)", "বিচার সম্পন্ন করার উদ্দেশ্যে জুরি বা বিচারক প্যানেল গঠন করা",
     ["Select jury", "Swear in court"], [],
     "The clerk took four hours to impanel an impartial jury for the homicide trial.",
     "মানবহত্যা মামলার জন্য একটি নিরপেক্ষ জুরি প্যানেল গঠন করতে আদালতের চার ঘণ্টা সময় লাগে।", "Law & Governance"),
    ("Sequester", "Verb", "/sɪˈkwes.tər/ (সিকোয়েস্টার)", "বিচারকদের বহির্বিশ্ব থেকে আলাদা রাখা বা সম্পত্তি সাময়িক বাজেয়াপ্ত করা",
     ["Isolate", "Confiscate"], [],
     "High-profile trials mandate that authorities sequester the jury to shield them from media bias.",
     "সংবেদনশীল মামলায় বিচারকদের গণমাধ্যমের প্রভাব থেকে মুক্ত রাখতে প্রশাসন তাদের সম্পূর্ণ আলাদা রাখে।", "Law & Governance"),
    ("Ex-officio", "Adjective", "/ˌeks əˈfɪʃ.i.əʊ/ (এক্স-অফিসিও)", "পদাধিকারবলে প্রাপ্ত বা পদের কারণে স্বয়ংক্রিয়ভাবে অর্পিত",
     ["By virtue of office"], [],
     "The Prime Minister serves as the ex-officio chairman of the national planning commission.",
     "প্রধানমন্ত্রী পদাধিকারবলে জাতীয় পরিকল্পনা কমিশনের চেয়ারম্যান হিসেবে দায়িত্ব পালন করেন।", "Law & Governance"),
    ("Caveat-emptor", "Noun", "/ˌkæv.i.æt ˈemp.tɔːr/ (ক্যাভিয়েট এম্পটর)", "ক্রেতা সাবধান নীতি যেখানে ক্রয়ের ঝুঁকি ক্রেতার নিজের",
     ["Buyer beware rule"], [],
     "In real estate auctions, the principle of caveat emptor applies to all bidders.",
     "স্থাবর সম্পত্তি নিলামে সকল দরদাতার জন্য ক্রেতা সাবধানের আইনি নীতিটি প্রযোজ্য হয়।", "Law & Governance"),
    ("Locus-standi", "Noun", "/ˌləʊ.kəs ˈstæn.daɪ/ (লোকাস স্ট্যান্ডাই)", "আদালতে মামলা করার বা প্রতিকার চাওয়ার আইনগত অধিকার বা এখতিয়ার",
     ["Legal standing"], [],
     "The judge dismissed the petition noting that the distant applicant lacked locus standi.",
     "আদালত আবেদনটি খারিজ করে উল্লেখ করেন যে অনাত্মীয় আবেদনকারীর কোনো মামলা করার আইনি অধিকার নেই।", "Law & Governance"),
    ("Stare-decisis", "Noun", "/ˌstɑː.reɪ dɪˈsaɪ.sɪs/ (স্টেয়ার ডেসিসিস)", "পূর্ববর্তী উচ্চ আদালতের রায়ের নজির মেনে চলার বাধ্যবাধকতা",
     ["Doctrine of precedent"], [],
     "Lower appellate courts are strictly bound under stare decisis to observe constitutional rulings.",
     "নিম্ন আপিল আদালতগুলো উচ্চ আদালতের সাংবিধানিক রায় নজির হিসেবে অনুসরণ করতে কঠোরভাবে বাধ্য।", "Law & Governance"),
    ("In-camera", "Adjective", "/ɪn ˈkæm.ər.ə/ (ইন-ক্যামেরা)", "জনসমক্ষে নয় বরং বিচারকের খাস কামরায় গোপন বিচারকার্য সম্পাদন",
     ["Behind closed doors", "Secret hearing"], ["Open court"],
     "Sensitive national espionage hearings are traditionally conducted in camera.",
     "স্পর্শকাতর রাষ্ট্রীয় গোয়েন্দা তথ্যের মামলার বিচারকাজ প্রথাগতভাবে খাস কামরায় গোপনে অনুষ্ঠিত হয়।", "Law & Governance"),
    ("Ex-parte", "Adjective", "/ˌeks ˈpɑː.ti/ (এক্স-পার্টি)", "একতরফা বা এক পক্ষের উপস্থিতিতে প্রদত্ত আদালতের আদেশ",
     ["One-sided legal decision"], ["Bilateral hearing"],
     "The judge issued an ex parte temporary restraining order preventing property demolition.",
     "সম্পত্তি ভাঙা ঠেকাতে বিচারক একতরফা শুনানির ভিত্তিতে সাময়িক স্থগিতাদেশ জারি করেছেন।", "Law & Governance"),
    ("Pro-rata", "Adverb", "/ˌprəʊ ˈrɑː.tə/ (প্রো-রাটা)", "আনুপাতিক হারে বা প্রত্যেকের প্রাপ্য অনুযায়ী বণ্টন",
     ["Proportionally"], [],
     "Insolvency funds were distributed on a pro rata basis among unsecured trade creditors.",
     "দেউলিয়া প্রতিষ্ঠানের অবশিষ্ট অর্থ পাওনাদারদের মাঝে তাদের আনুপাতিক হারের ভিত্তিতে বণ্টন করা হয়।", "Banking & Finance"),
    ("Post-mortem", "Noun", "/ˌpəʊstˈmɔː.təm/ (পোস্টমর্টেম)", "মৃত্যুর কারণ নির্ণয়ে মৃতদেহের ময়নাতদন্ত",
     ["Autopsy", "Forensic examination"], [],
     "The coroner post mortem report established drowning as the official cause of demise.",
     "ময়নাতদন্ত প্রতিবেদনে পানিতে ডুবে মৃত্যুকে আনুষ্ঠানিক কারণ হিসেবে চিহ্নিত করা হয়েছে।", "Science & Medical"),
    ("Ad-interim", "Adjective", "/ˌæd ˈɪn.tər.ɪm/ (অ্যাড-ইন্টারিম)", "স্থায়ী ব্যবস্থা না হওয়া পর্যন্ত সাময়িক বা অন্তর্বর্তীকালীন",
     ["Temporary", "Provisional"], ["Permanent"],
     "The high court granted ad interim anticipatory bail until the next regular hearing date.",
     "পরবর্তী নিয়মিত শুনানির তারিখ পর্যন্ত হাইকোর্ট অন্তর্বর্তীকালীন আগাম জামিন মঞ্জুর করেছেন।", "Law & Governance"),
    ("Ad-hoc", "Adjective", "/ˌæd ˈhɒk/ (অ্যাড-হক)", "বিশেষ কোনো নির্দিষ্ট উদ্দেশ্য সাধনে গঠিত সাময়িক ব্যবস্থা",
     ["Special purpose", "Temporary committee"], ["Permanent"],
     "Parliament established an ad hoc task force to investigate highway construction delays.",
     "মহাসড়ক নির্মাণে দীর্ঘসূত্রতার কারণ অনুসন্ধানে সংসদ একটি বিশেষ সাময়িক তদন্ত দল গঠন করেছে।", "BCS & Bank"),
    ("Sine-die", "Adverb", "/ˌsaɪ.ni ˈdaɪ.iː/ (সাইন-ডাই)", "নির্দিষ্ট কোনো ভবিষ্যৎ তারিখ উল্লেখ ছাড়া অনির্দিষ্টকালের জন্য",
     ["Indefinitely postponed"], [],
     "Disorderly chaos prompted the presiding officer to adjourn the legislative chamber sine die.",
     "উচ্ছৃঙ্খল পরিস্থিতির কারণে সভাপতি সংসদ অধিবেশন অনির্দিষ্টকালের জন্য মুলতবি করতে বাধ্য হন।", "Law & Governance"),
    ("Vice-versa", "Adverb", "/ˌvaɪs ˈvɜː.sə/ (ভাইস-ভার্সা)", "উল্টোভাবেও সত্য বা বিপরীতক্রমে একইভাবে প্রযোজ্য",
     ["Conversely"], [],
     "Monetary stability fosters commercial confidence and vice versa across all markets.",
     "আর্থিক স্থিতিশীলতা বাণিজ্যিক আস্থা বৃদ্ধি করে এবং বিপরীতক্রমে আস্থাও অর্থনীতিকে স্থিতিশীল রাখে।", "Economics"),
    ("Interlocutory", "Adjective", "/ˌɪn.təˈlɒk.jʊ.tər.i/ (ইন্টারলোকিউটরি)", "চূড়ান্ত রায় হওয়ার আগে মধ্যবর্তী অন্তর্বর্তীকালীন আদেশ",
     ["Provisional judicial decree"], ["Final verdict"],
     "The corporate litigant filed an appeal contesting the interlocutory injunction.",
     "করপোরেট বিবাদী অন্তর্বর্তীকালীন নিষেধাজ্ঞার আদেশ চ্যালেঞ্জ করে আপিল দায়ের করেছে।", "Law & Governance"),
    ("Sub-judice", "Adjective", "/sʌb ˈdʒuː.dɪ.si/ (সাব-জুডিস)", "আদালতে বিচারাধীন তাই জনসমক্ষে মন্তব্য করা নিষিদ্ধ",
     ["Under judicial consideration"], [],
     "Ministers refrained from discussing the tender irregularities since the dispute was sub judice.",
     "দরপত্র অনিয়ম সংক্রান্ত বিরোধটি আদালতে বিচারাধীন থাকায় মন্ত্রীরা মন্তব্য থেকে বিরত থাকেন।", "Law & Governance"),
    ("Suo-moto", "Noun", "/ˈsuː.oʊ ˈmoʊ.toʊ/ (সুয়ো-মোটো)", "আদালত কর্তৃক স্বপ্রণোদিতভাবে গৃহীত বিচারিক ব্যবস্থা",
     ["Spontaneous court action"], [],
     "The bench initiated suo moto proceedings demanding environmental protection for drying canals.",
     "শুকিয়ে যাওয়া খাল সংরক্ষণে হাইকোর্ট বেঞ্চ স্বতঃপ্রণোদিত হয়ে আইনি পদক্ষেপ গ্রহণ করেছে।", "Law & Governance"),
    ("Quash", "Verb", "/kwɒʃ/ (কোয়াশ)", "আদালতের রায়ে কোনো আইনি সিদ্ধান্ত বা মামলা বাতিল করা",
     ["Nullify", "Invalidate", "Annul"], ["Uphold"],
     "The high court moved to quash the politically motivated criminal charge sheet.",
     "রাজনৈতিক উদ্দেশ্যপ্রণোদিত অভিযোগপত্রটি হাইকোর্ট বাতিল ও অকার্যকর ঘোষণা করেছে।", "Law & Governance"),
    ("Jurisprudent", "Noun", "/ˌdʒʊə.rɪsˈpruː.dənt/ (জুরিসপ্রুডেন্ট)", "আইনতত্ত্বে পারদর্শী পণ্ডিত",
     ["Legal theorist", "Jurist"], [],
     "A renowned jurisprudent authored the definitive treatise on human rights constitutionalism.",
     "একজন প্রখ্যাত আইনবিজ্ঞানী মানবাধিকার ও সংবিধানবাদের ওপর ঐতিহাসিক গ্রন্থটি রচনা করেন।", "Law & Governance"),
    ("Legalese", "Noun", "/ˌliː.ɡəlˈiːz/ (লিগালিজ)", "আইনি দলিলের জটিল ও দুর্বোধ্য পারিভাষিক ভাষা",
     ["Complex legal jargon"], ["Plain English"],
     "Consumer protection bodies urge banks to replace dense legalese with simple contract terms.",
     "ভোক্তা অধিকার সংস্থাগুলো জটিল আইনি ভাষার পরিবর্তে সহজ চুক্তিনামা ব্যবহারের আহ্বান জানায়।", "Law & Governance"),
    ("Bailiff", "Noun", "/ˈbeɪ.lɪf/ (বেলিফ)", "আদালতের শৃঙ্খলা রক্ষাকারী ও সমন জারি করার কর্মকর্তা",
     ["Court officer", "Usher"], [],
     "The courtroom bailiff announced the entry of the presiding appellate judges.",
     "আদালতের কর্মকর্তা প্রধান আপিল বিচারকদের এজলাসে প্রবেশের আনুষ্ঠানিক ঘোষণা দেন।", "Law & Governance"),
    ("Juror", "Noun", "/ˈdʒʊə.rər/ (জুরর)", "মামলার রায় নির্ধারণে গঠিত জুরি বোর্ডের শপথপ্রাপ্ত সদস্য",
     ["Jury member"], [],
     "Each sworn juror must evaluate the forensic ballistic testimony impartially.",
     "প্রতিটি শপথপ্রাপ্ত জুরি সদস্যকে নিরপেক্ষভাবে ফরেনসিক ব্যালিস্টিক সাক্ষ্য মূল্যায়ন করতে হয়।", "Law & Governance"),
    ("Barrister", "Noun", "/ˈbær.ɪ.stər/ (ব্যারিস্টার)", "উচ্চ আদালতে মামলা পরিচালনায় পারদর্শী আইনজীবী",
     ["Advocate", "Counsel"], [],
     "The senior barrister presented a compelling constitutional defense before the full bench.",
     "জ্যেষ্ঠ ব্যারিস্টার পূর্ণাঙ্গ বেঞ্চের সামনে অত্যন্ত জোরালো সাংবিধানিক যুক্তি তুলে ধরেন।", "Law & Governance"),
    ("Solicitor", "Noun", "/səˈlɪs.ɪ.tər/ (সলিসিটর)", "আইনি দলিলপত্র প্রস্তুতকারী ও মক্কেলকে পরামর্শদাতা আইনজীবী",
     ["Legal adviser", "Attorney"], [],
     "Ensure that your property transfer contract is drafted by a registered solicitor.",
     "আপনার সম্পত্তি হস্তান্তর চুক্তিটি একজন নিবন্ধিত আইনি পরামর্শক দ্বারা তৈরি নিশ্চিত করুন।", "Law & Governance"),
    ("Forensics", "Noun", "/fəˈren.zɪks/ (ফরেনসিক্স)", "অপরাধ তদন্তে বিজ্ঞানের বিভিন্ন শাখার প্রয়োগ",
     ["Scientific criminal investigation"], [],
     "Modern digital forensics extracted encrypted financial logs proving cross-border fraud.",
     "আধুনিক ডিজিটাল ফরেনসিক্স আন্তঃসীমান্ত জালিয়াতি প্রমাণে এনক্রিপ্ট করা ফাইল উদ্ধার করেছে।", "BCS & Bank"),
    ("Jurisdictive", "Adjective", "/ˌdʒʊə.rɪsˈdɪk.tɪv/ (জুরিসডিক্টিভ)", "আইনি কর্তৃত্ব বা সীমানা প্রয়োগের ক্ষমতা সম্পর্কিত",
     ["Authority-exercising"], [],
     "The maritime agency exercised its full jurisdictive mandate across economic territorial waters.",
     "নৌ সংস্থাটি অর্থনৈতিক জলসীমার ওপর তার পূর্ণ আইনি কর্তৃত্ব ও এখতিয়ার প্রয়োগ করেছে।", "Law & Governance"),
    ("Statutory", "Adjective", "/ˈstætʃ.ə.tər.i/ (স্ট্যাচুটরি)", "আইনসভা কর্তৃক পাসকৃত আইনের দ্বারা বাধ্যতামূলক",
     ["Legally mandated", "Enacted"], [],
     "Every commercial bank must maintain statutory cash reserves with the central monetary body.",
     "প্রতিটি বাণিজ্যিক ব্যাংককে কেন্দ্রীয় ব্যাংকে বাধ্যতামূলক আইনসম্মত নগদ রিজার্ভ রাখতে হয়।", "Banking & Finance")
]

# Verify that all words in law_data are completely fresh against existing
fresh_law = []
seen = set()
for item in law_data:
    w = item[0].strip().lower()
    if w not in existing and w not in seen:
        fresh_law.append(item)
        seen.add(w)
    else:
        print(f"Duplicate found in law_data: {item[0]}")

print(f"Total fresh law words: {len(fresh_law)}")
assert len(fresh_law) >= 100, f"Only {len(fresh_law)}"
fresh_law = fresh_law[:100]

with open('next_part1.json', 'w', encoding='utf-8') as f:
    json.dump(fresh_law, f, ensure_ascii=False, indent=2)

print("next_part1.json saved successfully with 100 words!")
