# coding=utf-8
import json

data = json.load(open("app/src/main/assets/dictionary_1000.json"))
existing = {x["word"].strip().lower() for x in data}

# 50 more rare, high-yield words
raw_entries = [
    ("Absquatulate", "Verb", "/æbˈskwɒt.jʊ.leɪt/ (আবস্কোয়াটিউলেট)", "চম্পট দেওয়া বা দ্রুত কেটে পড়া", ["Abscond", "Decamp", "Flee"], ["Stay", "Remain"], "The thief absquatulate with the cash box before police arrived.", "পুলিশ আসার আগেই চোর ক্যাশ বাক্স নিয়ে চম্পট দিয়েছিল।"),
    ("Aerolith", "Noun", "/ˈeə.rə.lɪθ/ (এরোলিথ)", "উল্কাপাতপ্রসূত পাথর, আকাশ থেকে পৃথিবীতে পতিত উল্কাখণ্ড", ["Meteorite", "Shooting star stone"], ["Terrestrial rock"], "The museum displayed a rare iron aerolith found in the desert.", "জাদুঘরটি মরুভূমিতে পাওয়া একটি বিরল লোহার উল্কাপাতপ্রসূত পাথর প্রদর্শন করেছিল।"),
    ("Agglomeration", "Noun", "/əˌɡlɒm.əˈreɪ.ʃən/ (অ্যাগ্লোমারেশন)", "এলোমেলো জটলা বা সংগ্রহ, বিভিন্ন বস্তুর স্তূপ", ["Cluster", "Mass", "Collection"], ["Separation"], "The city is a chaotic agglomeration of ancient and modern buildings.", "শহরটি প্রাচীন এবং আধুনিক ভবনের এক বিশৃঙ্খল এলোমেলো জটলা।"),
    ("Alacrity", "Noun", "/əˈlæk.rə.ti/ (অ্যাল্যাক্রিটি)", "তৎপরতা ও উৎসাহ, সানন্দ ক্ষিপ্রতা", ["Eagerness", "Promptness", "Enthusiasm"], ["Reluctance", "Sluggishness"], "She accepted the job offer with cheerful alacrity.", "তিনি আনন্দদায়ক তৎপরতা ও উৎসাহ এর সাথে চাকরির প্রস্তাব গ্রহণ করেছিলেন।"),
    ("Alimony", "Noun", "/ˈæl.ɪ.mə.ni/ (অ্যালিমনি)", "খোরপোষ বা জীবনধারণ ভাতা, বিচ্ছেদের পর প্রাপ্ত আইনি আর্থিক সহায়তা", ["Maintenance", "Support", "Spousal allowance"], ["Deprivation"], "The court ordered him to pay monthly alimony to his former spouse.", "আদালত তাকে তার সাবেক স্ত্রীকে মাসিক খোরপোষ বা জীবনধারণ ভাতা দেওয়ার নির্দেশ দিয়েছে।"),
    ("Alliterative", "Adjective", "/əˈlɪt.ər.ə.tɪv/ (অ্যালিটারেটিভ)", "অনুপ্রাসময়, একই ব্যঞ্জনবর্ণের ঘনঘন উচ্চারণে তৈরি সাহিত্যিক রূপ", ["Repetitive-sound", "Poetic"], ["Unrhymed"], "The poem used alliterative phrases to create a musical rhythm.", "কবিতাটি একটি সুরময় ছন্দ তৈরি করতে অনুপ্রাসময় বাক্যাংশ ব্যবহার করেছিল।"),
    ("Altimetry", "Noun", "/ælˈtɪm.ə.tri/ (অলটিমেট্রি)", "উচ্চতা পরিমাপবিদ্যা, সমুদ্রপৃষ্ঠ থেকে উচ্চতা মাপার বিজ্ঞান", ["Altitude measurement", "Elevation science"], ["Depth measurement"], "Satellite altimetry accurately measures global sea level rise.", "স্যাটেলাইট উচ্চতা পরিমাপবিদ্যা বিশ্বব্যাপী সমুদ্রের উচ্চতা বৃদ্ধি নির্ভুলভাবে পরিমাপ করে।"),
    ("Altruism", "Noun", "/ˈæl.tru.ɪz.əm/ (অলট্রুইজম)", "পরোপকারিতা, নিঃস্বার্থভাবে অন্যের মঙ্গল সাধন", ["Philanthropy", "Selflessness", "Benevolence"], ["Selfishness", "Egoism"], "Her lifelong altruism led her to found free medical clinics.", "তার সারাজীবনের পরোপকারিতা তাকে বিনামূল্যে চিকিৎসা ক্লিনিক প্রতিষ্ঠা করতে পরিচালিত করেছিল।"),
    ("Alveolar", "Adjective", "/ælˈviː.ə.lər/ (অ্যালভিওলার)", "দন্তমূলীয়, দন্তমূল ব্যবহার করে উচ্চারিত ধ্বনি বা ফুসফুসের বায়ুথলি সংক্রান্ত", ["Dental-root", "Pulmonary"], ["Nasal"], "Sounds like 't' and 'd' are classified as alveolar consonants.", "'টি' এবং 'ডি' এর মতো শব্দগুলোকে দন্তমূলীয় ব্যঞ্জনবর্ণ হিসেবে শ্রেণীবদ্ধ করা হয়।"),
    ("Amanuensis", "Noun", "/əˌmæn.juˈen.sɪs/ (অ্যামানিউয়েনসিস)", "শ্রুতলেখক, অন্য ব্যক্তির মুখে বলা কথা দেখে দেখে লেখালোক", ["Scribe", "Secretary", "Transcriber"], ["Author"], "The blind poet dictated his epic verses to his loyal amanuensis.", "অন্ধ কবি তার বিশ্বস্ত শ্রুতলেখক এর কাছে তার মহাকাব্যিক শ্লোকগুলো নির্দেশ করেছিলেন।"),
    ("Ambidexterity", "Noun", "/ˌæm.bɪ.dekˈster.ə.ti/ (অ্যাম্বিডেক্সটেরিটি)", "সব্যসাচী রূপ, দুই হাত সমান দক্ষতায় ব্যবহার করার ক্ষমতা", ["Two-handed skill", "Versatility"], ["Clumsiness"], "His natural ambidexterity made him an exceptional baseball pitcher.", "তার সহজাত সব্যসাচী রূপ তাকে এক ব্যতিক্রমী বেসবল পিচার বানিয়েছিল।"),
    ("Amphibious", "Adjective", "/æmˈfɪb.i.əs/ (অ্যামফিবিয়াস)", "উভচর, জল ও স্থল উভয় স্থানে চলাচলে সক্ষম", ["Land-and-water", "Dual-habitat"], ["Terrestrial"], "Frogs are well-known amphibious creatures that live in ponds and land.", "ব্যাঙ হল সুপরিচিত উভচর প্রাণী যা পুকুর এবং ডাঙ্গায় বাস করে।"),
    ("Amphitheater", "Noun", "/ˈæm.fɪˌθɪə.tər/ (অ্যামফিথিয়েটার)", "গ্যালারিযুক্ত খোলা নাট্যশালা, বৃত্তাকার মুক্তমঞ্চ", ["Auditorium", "Arena", "Colosseum"], ["Closed room"], "The band performed an acoustic concert in the ancient Greek amphitheater.", "ব্যান্ডটি প্রাচীন গ্রীক গ্যালারিযুক্ত খোলা নাট্যশালা এ একটি শব্দময় কনসার্ট উপস্থাপন করেছিল।"),
    ("Anachronistic", "Adjective", "/əˌnæk.rəˈnɪs.tɪk/ (অ্যানাক্রোনিস্টিক)", "যুগের সাথে অমিলযুক্ত, কালবৈষম্যপূর্ণ", ["Out-of-date", "Old-fashioned"], ["Modern", "Timely"], "Using a typewriter in a modern office seems completely anachronistic.", "আধুনিক অফিসে টাইপরাইটার ব্যবহার করা সম্পূর্ণ যুগের সাথে অমিলযুক্ত মনে হয়।"),
    ("Analgesic", "Noun", "/ˌæn.əlˈdʒiː.zɪk/ (অ্যানালজেসিক)", "বেদনা উপশমকারী ওষুধ, ব্যথা দূর করার ঔষধ", ["Painkiller", "Anesthetic", "Soother"], ["Irritant"], "The doctor prescribed a mild analgesic to relieve his post-surgery pain.", "ডাক্তার তার অস্ত্রোপচার পরবর্তী ব্যথা কমাতে একটি মৃদু বেদনা উপশমকারী ওষুধ লিখেছেন।"),
    ("Animosity", "Noun", "/ˌæn.ɪˈmɒs.ə.ti/ (অ্যানিমোসিটি)", "তীব্র শত্রুতা ও বিদ্বেষ, দীর্ঘদিনের পারস্পরিক বিরোধিতা", ["Hostility", "Enmity", "Hatred"], ["Friendship", "Amity"], "There was longstanding animosity between the two competing families.", "দুটি প্রতিদ্বন্দ্বী পরিবারের মধ্যে দীর্ঘদিনের তীব্র শত্রুতা ও বিদ্বেষ ছিল।"),
    ("Anthropocentric", "Adjective", "/ˌæn.θrə.pəʊˈsen.trɪk/ (অ্যানথ্রোপোসেন্ট্রিক)", "মানবকেন্দ্রিক দৃষ্টিভঙ্গি, মানুষকে বিশ্বজগতের কেন্দ্রে বিবেচনা করা", ["Human-centered", "Egoistic"], ["Biocentric"], "An anthropocentric view places human needs above environmental health.", "একটি মানবকেন্দ্রিক দৃষ্টিভঙ্গি পরিবেশগত স্বাস্থ্যের ওপরে মানুষের চাহিদাকে স্থান দেয়।"),
    ("Antipathy", "Noun", "/ænˈtɪp.ə.θi/ (অ্যান্টিপ্যাথি)", "তীব্র বিতৃষ্ণা বা অপছন্দ, প্রাকৃতিকভাবে কাউকে অপছন্দ করা", ["Aversion", "Dislike", "Hostility"], ["Liking", "Affinity"], "She felt an instant antipathy toward the arrogant newcomer.", "তিনি অহংকারী নবাগতের প্রতি এক তাৎক্ষণিক তীব্র বিতৃষ্ণা বা অপছন্দ অনুভব করেছিলেন।"),
    ("Apotheosis", "Noun", "/əˌpɒθ.iˈəʊ.sɪs/ (অ্যাপোথিওসিস)", "পরম ঈশ্বরত্বে ভূষিতকরণ, নিখুঁততার সর্বোচ্চ চূড়া", ["Deification", "Culmination", "Elevation"], ["Degradation"], "Winning the Olympic gold medal was the apotheosis of her athletic career.", "অলিম্পিক স্বর্ণপদক জয় ছিল তার অ্যাথলেটিক ক্যারিয়ারের পরম ঈশ্বরত্বে ভূষিতকরণ বা সর্বোচ্চ চূড়া।"),
    ("Aquiline", "Adjective", "/ˈæk.wɪ.laɪn/ (অ্যাকুইলাইন)", "ঈগলের ঠোঁটের মতো বাঁকানো, রাজকীয় বাকানো নাক", ["Hooked", "Eaglenose", "Eaguelike"], ["Flat", "Straight"], "He was distinguished by his tall stature and sharp aquiline nose.", "তিনি তার লম্বা অবয়ব এবং ধারালো ঈগলের ঠোঁটের মতো বাঁকানো নাক দ্বারা চিহ্নিত ছিলেন।"),
    ("Arduousness", "Noun", "/ˈɑː.dʒu.əs.নəs/ (আর্ডুয়াসনেস)", "কঠোর সাধ্যসাধ্যতা, চরম কায়িক পরিশ্রম ও সহনশীলতার প্রয়োজন", ["Difficulty", "Strenuousness", "Laboriousness"], ["Ease", "Simplicity"], "The arduousness of the mountain climb exhausted even trained athletes.", "পাহাড়ে ওঠার কঠোর সাধ্যসাধ্যতা এমনকি প্রশিক্ষিত খেলোয়াড়দেরও ক্লান্ত করে তুলেছিল।"),
    ("Asceticism", "Noun", "/əˈset.ɪ.sɪz.əm/ (অ্যাসেটিসিজম)", "কৃচ্ছ্রসাধন বা সন্ন্যাসব্রত, জাগতিক সুখ-স্বাচ্ছন্দ্য ত্যাগ করে ত্যাগের জীবন", ["Austerity", "Self-denial", "Monasticism"], ["Hedonism", "Indulgence"], "His strict religious asceticism included fasting and long silence.", "তার কঠোর ধর্মীয় কৃচ্ছ্রসাধন এর মধ্যে রোজা রাখা এবং দীর্ঘ নীরবতা অন্তর্ভুক্ত ছিল।"),
    ("Audaciousness", "Noun", "/ɔːˈdeɪ.ʃəs.নəs/ (অডেশাসনেস)", "সাহসী দুস্পর্ধা, ভীতিহীন ও দুঃসাহসিক পদক্ষেপ", ["Boldness", "Daring", "Impudence"], ["Timidness", "Fearfulness"], "The audacity of her plan stunned the conservative board members.", "তার পরিকল্পনার সাহসী দুস্পর্ধা রক্ষণশীল বোর্ড সদস্যদের স্তব্ধ করে দিয়েছিল।"),
    ("Beguilement", "Noun", "/bɪˈɡaɪl.məন্ত/ (বিগাইলমেন্ট)", "মোহিত করার ছলাকলা, মিষ্টি কথায় ভুলিয়ে বশ করার কায়দা", ["Enchantment", "Deception", "Allure"], ["Disillusionment"], "The beguilement of the magician captivated the audience completely.", "জাদুকরের মোহিত করার ছলাকলা দর্শকদের সম্পূর্ণভাবে মুগ্ধ করেছিল।"),
    ("Benevolence", "Noun", "/bəˈnev.əl.əns/ (বেনেভোলেন্স)", "পরাণপরতা ও দয়া, অন্যের কল্যাণে আনন্দ পাওয়ার রূপ", ["Kindness", "Generosity", "Altruism"], ["Malevolence", "Cruelty"], "The elderly philanthropist was loved for her endless benevolence.", "বয়স্ক দানশীল নারী তার অশেষ পরাণপরতা ও দয়া এর জন্য ভালোবাসার পাত্রী ছিলেন।"),
    ("Cacophonous", "Adjective", "/kəˈkɒf.ə.nəs/ (ক্যাকোফোনাস)", "কর্কশ শ্রুতিকটু শব্দময়, কানফাটা বিশৃঙ্খল শব্দে ভরপুর", ["Harsh-sounding", "Discordant", "Gratings"], ["Euphonious", "Harmonious"], "The cacophonous noise of city traffic woke him up early.", "শহরের যানবাহনের কর্কশ শ্রুতিকটু শব্দময় আওয়াজ তাকে ভোরে জাগিয়ে তুলেছিল।"),
    ("Capriciousness", "Noun", "/kəˈprɪʃ.əs.নəs/ (ক্যাপ্রিশাসনেস)", "খেয়ালী অস্থিরতা, হঠাৎ ঝোঁকের মাথায় সিদ্ধান্ত বদলানো", ["Fickleness", "Whimsicality", "Variability"], ["Constancy", "Predictability"], "The capriciousness of the spring weather made planning outdoor events risky.", "বসন্তের আবহাওয়ার খেয়ালী অস্থিরতা বাইরের ইভেন্টের পরিকল্পনাকে ঝুঁকিপূর্ণ করে তুলেছিল।"),
    ("Castigation", "Noun", "/ˌkæs.tɪˈɡeɪ.ʃən/ (ক্যাস্টিগেশন)", "কঠোর তিরস্কার বা শাস্তি প্রদান, জনসম্মুখে করা তীব্র সমালোচনা", ["Severe criticism", "Chastisement", "Reprimand"], ["Praise", "Commendation"], "The manager faced severe public castigation for his mishandling of funds.", "তহবিল ব্যবস্থাপনায় ভুলের জন্য ম্যানেজার মারাত্মক জনসমক্ষে করা তীব্র সমালোচনা এর মুখোমুখি হন।"),
    ("Circumspection", "Noun", "/ˌsɜː.kəmˈspek.ʃən/ (সারকামস্পেকশন)", "সাবধানী বিবেচনা, চারপাশের ঝুঁকি ভেবেচিন্তে কাজ করা", ["Caution", "Prudence", "Discretion"], ["Recklessness", "Rashness"], "Financial investments require extreme circumspection in volatile markets.", "অস্থির বাজারে আর্থিক বিনিয়োগে চরম সাবধানী বিবেচনা প্রয়োজন।"),
    ("Cogency", "Noun", "/ˈkəʊ.dʒən.si/ (কোজেন্সি)", "যুক্তিপূর্ণ অকাট্যতা, যা শ্রোতাকে প্রভাবিত করতে বাধ্য করে", ["Persuasiveness", "Validity", "Forcefulness"], ["Weakness", "Ineffectiveness"], "The cogency of her argument convinced the entire committee.", "তার যুক্তির যুক্তিপূর্ণ অকাট্যতা পুরো কমিটিকে আশ্বস্ত করেছিল।"),
    ("Conciliatory", "Adjective", "/kənˈsɪl.i.ə.tər.i/ (কনসিলিয়েটরি)", "আপোষকামী ও শান্তিদায়ক, মনোমালিন্য দূর করতে নমনীয়", ["Placatory", "Peacemaking", "Mollifying"], ["Antagonistic", "Aggressive"], "He offered a conciliatory gesture to heal the split in the family.", "তিনি পরিবারের ফাটল মেটাতে একটি আপোষকামী ও শান্তিদায়ক অঙ্গভঙ্গি উপস্থাপন করেছিলেন।"),
    ("Conundrum", "Noun", "/kəˈnʌn.drəm/ (কনানড্রাম)", "জটিল ধাঁধা বা সমাধানহীন সমস্যা, যা বুদ্ধিকে বিভ্রান্ত করে", ["Enigma", "Puzzle", "Riddle"], ["Solution", "Explanations"], "Resolving the economic conundrum required innovative tax reform.", "অর্থনৈতিক জটিল ধাঁধা সমাধান করতে উদ্ভাবনী কর সংস্কারের প্রয়োজন ছিল।"),
    ("Conviviality", "Noun", "/kənˌvɪv.iˈæl.ə.ti/ (কনভিভিয়ালিটি)", "হাসিখুশি আড্ডাবাজ পরিবেশ, বন্ধুত্বপূর্ণ উৎসবমুখর মেজাজ", ["Sociability", "Festivity", "Geniality"], ["Gloom", "Solitude"], "The holiday dinner was filled with warmth and lively conviviality.", "ছুটির রাতের খাবারটি উষ্ণতা এবং প্রাণবন্ত হাসিখুশি আড্ডাবাজ পরিবেশ এ পূর্ণ ছিল।"),
    ("Corroboration", "Noun", "/kəˌrɒb.əˈreɪ.ʃən/ (করোবোরেশন)", "সত্যতা সমর্থন বা প্রমাণ দিয়ে জোড় দেওয়া", ["Confirmation", "Verification", "Substantiation"], ["Refutation", "Denial"], "Eyewitness testimony provided strong corroboration for the suspect's claim.", "প্রত্যক্ষদর্শীর সাক্ষ্য আসামির দাবির জন্য শক্তিশালী সত্যতা সমর্থন প্রদান করেছে।"),
    ("Deleterious", "Adjective", "/ˌdel.ɪˈtɪə.ri.əs/ (ডেলিটেরিয়াস)", "ক্ষতিকর বা অনিষ্টকারী, যা ধীরে ধীরে স্বাস্থ্যের বিনাশ ঘটায়", ["Harmful", "Damaging", "Detrimental"], ["Beneficial", "Harmless"], "Smoking has a well-documented, highly deleterious effect on lung health.", "ধূমপানের ফুসফুসের স্বাস্থ্যের ওপর একটি সুনির্দিষ্ট, অত্যন্ত ক্ষতিকর বা অনিষ্টকারী প্রভাব রয়েছে।"),
    ("Demarcation", "Noun", "/ˌdiː.mɑːˈkeɪ.ʃən/ (ডিমার্কেশন)", "সীমানা নির্ধারণ, দুটি এলাকার স্পষ্ট বর্ডার চিহ্নিত করা", ["Boundary-setting", "Delimitation", "Separation"], ["Blurring", "Union"], "Clear demarcation of roles prevented friction among team members.", "ভূমিকাগুলোর স্পষ্ট সীমানা নির্ধারণ দলের সদস্যদের মধ্যে ঘর্ষণ রোধ করেছিল।"),
    ("Denouement", "Noun", "/deɪˈnuː.mɒ̃/ (ডিনুমন্ট)", "গল্পের নাটকীয় পরিণতি, রহস্যের সমাপ্তি মোড়", ["Resolution", "Outcome", "Climax"], ["Beginning", "Introduction"], "The mystery novel reached an unexpected, thrilling denouement.", "রহস্য উপন্যাসটি একটি অপ্রত্যাশিত, রোমাঞ্চকর নাটকীয় পরিণতি এ পৌঁছেছিল।"),
    ("Diaphanous", "Adjective", "/daɪˈæf.ən.əs/ (ডায়াফ্যানাস)", "স্বচ্ছ ও সূক্ষ্ম, যার মধ্য দিয়ে আলো সহজে চলাচল করে", ["Sheer", "Translucent", "Gossamer"], ["Opaque", "Thick"], "The bride wore a delicate, diaphanous silk veil during the ceremony.", "অনুষ্ঠানের সময় কনে একটি সূক্ষ্ম, স্বচ্ছ ও সূক্ষ্ম রেশমি ঘোমটা পরেছিলেন।"),
    ("Draconian", "Adjective", "/drəˈkəʊ.ni.ən/ (ড্রাকোনিয়ান)", "কঠোর ও নির্মম, অনাবশ্যক কড়া নিয়ম বা আইন", ["Harsh", "Severe", "Strict"], ["Lenient", "Mild"], "Citizens protested against the government's new draconian censorship rules.", "নাগরিকরা সরকারের নতুন কঠোর ও নির্মম সেন্সরশিপ নিয়মের বিরুদ্ধে প্রতিবাদ করেছিল।"),
    ("Duplicity", "Noun", "/djuːˈplɪs.ə.ti/ (ডিউপ্লিসিটি)", "শঠতা ও দ্বিমুখী আচরণ, প্রতারণা করার চাতুরি", ["Deceitfulness", "Double-dealing", "Dishonesty"], ["Honesty", "Sincerity"], "His duplicity was exposed when both conflicting promises came to light.", "তার শঠতা ও দ্বিমুখী আচরণ প্রকাশ পায় যখন উভয় বিরোধী প্রতিশ্রুতি আলোর মুখ দেখে।"),
    ("Ebullient", "Adjective", "/ɪˈbʊl.i.ənt/ (ইবুলিয়েন্ট)", "উচ্ছ্বসিত ও প্রাণবন্ত, উৎসাহে টগবগ করে ফোটা", ["Exuberant", "Buoyant", "High-spirited"], ["Depressed", "Gloomy"], "The ebullient crowd cheered enthusiastically as the champion entered.", "চ্যাম্পিয়ন প্রবেশ করার সাথে সাথে উচ্ছ্বসিত ও প্রাণবন্ত জনতা উৎসাহের সাথে করতালি দিয়েছিল।"),
    ("Ecclesiastic", "Noun", "/ɪˌkliː.ziˈæs.tɪk/ (এক্লেসিয়াস্টিক)", "পুরোহিত বা ধর্মযাজক, চার্চের সেবায় নিয়োজিত ব্যক্তি", ["Clergyman", "Priest", "Minister"], ["Layman"], "The senior ecclesiastic delivered a sermon on peace and reconciliation.", "জ্যেষ্ঠ পুরোহিত বা ধর্মযাজক শান্তি ও সম্প্রীতির ওপর একটি ধর্মোপদেশ দিয়েছেন।"),
    ("Edification", "Noun", "/ˌed.ɪ.fɪˈkeɪ.ʃən/ (এডিফিকেশন)", "নৈতিক ও আত্মিক উন্নতিসাধন, মন ও জ্ঞানের ইতিবাচক বিকাশ", ["Enlightenment", "Improvement", "Education"], ["Debasement", "Corruption"], "The sermon was intended for the moral edification of the congregation.", "ধর্মোপদেশটি পুণ্যার্থীদের নৈতিক ও আত্মিক উন্নতিসাধন এর উদ্দেশ্যে তৈরি করা হয়েছিল।"),
    ("Effervescence", "Noun", "/ˌef.əˈves.əns/ (এফারভেসেন্স)", "বুদবুদ ওঠা বা ফুরফুরে চপলতা, আনন্দের স্বতঃস্ফূর্ত প্রকাশ", ["Bubbliness", "Sparkle", "Vivacity"], ["Flatness", "Dullness"], "Her natural effervescence made her the life of every social party.", "তার প্রাকৃতিক ফুরফুরে চপলতা তাকে প্রতিটি সামাজিক পার্টির প্রাণবন্ত করে তুলেছিল।"),
    ("Efficacy", "Noun", "/ˈef.ɪ.kə.si/ (এফিক্যাসি)", "কার্যকারিতা, কাঙ্ক্ষিত ফলপ্রসূতা অর্জনের ক্ষমতা", ["Effectiveness", "Productivity", "Potency"], ["Inefficacy", "Uselessness"], "Clinical trials confirmed the high medical efficacy of the new vaccine.", "ক্লিনিক্যাল ট্রায়াল নতুন ভ্যাকসিনের উচ্চ চিকিৎসা কার্যকারিতা নিশ্চিত করেছে।"),
    ("Effrontery", "Noun", "/ɪˈfrʌn.tər.i/ (ইফ্রন্টারী)", "নির্লজ্জ স্পর্ধা, বেপরোয়া ঔদ্ধত্যপূর্ণ আচরণ", ["Audacity", "Impudence", "Insolence"], ["Timidity", "Modesty"], "He had the effrontery to demand a raise right after making a huge error.", "বিশাল ভুল করার পরেই তার বেতন বৃদ্ধির দাবি করার নির্লজ্জ স্পর্ধা ছিল।")
]

added = []
for item in raw_entries:
    word, pos, pron, mean, syns, ants, ex_en, ex_bn = item
    if word.strip().lower() not in existing:
        added.append(item)

print(f"Generated {len(added)} fresh entries for batch9_extra3.py")

with open("batch9_extra3.py", "w", encoding="utf-8") as f:
    f.write("# coding=utf-8\n\nBATCH9_EXTRA3 = [\n")
    for item in added:
        f.write(f"    {repr(item)},\n")
    f.write("]\n")

print("Successfully written batch9_extra3.py!")
