import json, re

# 1. Existing words set
existing_words = set()
with open('app/src/main/assets/dictionary_1000.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    for w in data:
        if 'word' in w and isinstance(w['word'], str):
            existing_words.add(w['word'].strip().lower())

with open('app/src/main/java/com/example/ui/screens/tools/VocabularyDataPacks.kt', 'r', encoding='utf-8') as f:
    content = f.read()
    for m in re.findall(r'VocabWord\s*\(\s*\"[^\"]+\"\s*,\s*\"([^\"]+)\"', content):
        existing_words.add(m.strip().lower())

with open('app/src/main/java/com/example/ui/screens/tools/VocabularyHighFrequencyDataset.kt', 'r', encoding='utf-8') as f:
    content = f.read()
    for t in re.findall(r'Triple\s*\(\s*\"([^\"]+)\"', content):
        existing_words.add(t.strip().lower())

print(f"Loaded {len(existing_words)} existing words from database.")

# List of 300 high quality vocabulary items for batch 2
batch2_candidates = [
    # 1 - 30
    ("Axiomatic", "/ˌæk.si.əˈmæt.ɪk/", "Adj", "স্বতঃসিদ্ধ, সন্দেহাতীত", "It is axiomatic that practice improves skills.", "এটি স্বতঃসিদ্ধ যে অনুশীলনে দক্ষতা বাড়ে।", ["Self-evident", "Unquestionable"], ["Questionable", "Debatable"], "Academic"),
    ("Beguile", "/bɪˈɡaɪl/", "Verb", "ছলনা করা, মোহিত করা", "He was beguiled by her charming smile.", "সে তার মোহনীয় হাসিতে মোহিত হয়েছিল।", ["Charming", "Enchant", "Deceive"], ["Repel", "Disenchant"], "GRE"),
    ("Belligerent", "/bəˈlɪdʒ.ər.ənt/", "Adj", "যুদ্ধংদেহী, আক্রমণাত্মক", "He assumed a belligerent attitude.", "সে এক যুদ্ধংদেহী মনোভাব গ্রহণ করেছিল।", ["Aggressive", "Hostile", "Pugnacious"], ["Peaceful", "Friendly"], "IELTS"),
    ("Brevity", "/ˈbrev.ə.ti/", "Noun", "সংক্ষিপ্ততা, স্বল্পতা", "The brevity of his speech was appreciated.", "তার বক্তব্যের সংক্ষিপ্ততা সবাই পছন্দ করেছে।", ["Conciseness", "Terseness"], ["Verbosity", "Lengthiness"], "Spoken"),
    ("Bungler", "/ˈbʌŋ.ɡlər/", "Noun", "আনাড়ি ব্যক্তি, কাজে ভুল করা লোক", "The inexperienced bungler broke the vase.", "অভিজ্ঞতাহীন আনাড়ি লোকদানদানটি ভেঙে ফেলল।", ["Clumsy person", "Blunderer"], ["Expert", "Master"], "Spoken"),
    ("Cajole", "/kəˈdʒəʊl/", "Verb", "মিষ্টি কথায় প্রলুব্ধ করা", "She cajoled him into buying her a watch.", "মিষ্টি কথা বলে সে তাকে একটি ঘড়ি কিনে দিতে রাজি করাল।", ["Coax", "Wheedle", "Flatter"], ["Force", "Bully"], "Spoken"),
    ("Callous", "/ˈkæl.əs/", "Adj", "অনভূতিহীন, কঠোর হৃদয়", "He showed a callous disregard for feelings.", "অন্যের অনুভূতির প্রতি সে কঠোর উদাসীনতা দেখিয়েছে।", ["Unfeeling", "Heartless", "Insensitive"], ["Compassionate", "Kind"], "BCS"),
    ("Camouflage", "/ˈkæm.ə.flɑːʒ/", "Noun", "ছদ্মবেশ, আত্মগোপন", "Soldiers wore camouflage in the jungle.", "সৈন্যরা জঙ্গলে ছদ্মবেশ ধারণ করেছিল।", ["Disguise", "Concealment"], ["Exposure", "Revelation"], "General"),
    ("Candor", "/ˈkæn.dər/", "Noun", "অকপটতা, স্পষ্টবাদিতা", "I appreciate your candor in this matter.", "এই বিষয়ে আপনার স্পষ্টবাদিতার প্রশংসা করি।", ["Frankness", "Honesty", "Openness"], ["Deceit", "Insincerity"], "IELTS"),
    ("Capapitulate", "/kəˈpɪtʃ.ə.leɪt/", "Verb", "আত্মসমর্পণ করা", "The enemy was forced to capitulate.", "শত্রুবাহিনী আত্মসমর্পণ করতে বাধ্য হয়েছিল।", ["Surrender", "Yield", "Submit"], ["Resist", "Conquer"], "History"),
    ("Carnage", "/ˈkɑː.nɪdʒ/", "Noun", "হত্যাকাণ্ড, গণসংহার", "The war left a trail of terrible carnage.", "যুদ্ধটি এক ভয়ানক হত্যাকাণ্ডের চিহ্ন রেখে গেছে।", ["Slaughter", "Massacre", "Bloodshed"], ["Peace"], "History"),
    ("Catharsis", "/kəˈθɑː.sɪs/", "Noun", "মানসিক ভারমুক্তি, অনুভূতি পরিশোধন", "Writing music was a catharsis for him.", "গান লেখা তার জন্য এক মানসিক ভারমুক্তি এনে দিয়েছিল।", ["Purification", "Release", "Relief"], ["Suppression"], "Psychology"),
    ("Chagrin", "/ˈʃæɡ.rɪn/", "Noun", "ক্ষোভ, অনুতাপ বা হতাশা", "To his chagrin, he failed the final test.", "তার চরম হতাশায়, সে শেষ পরীক্ষায় অকৃতকার্য হলো।", ["Disappointment", "Mortification"], ["Delight", "Satisfaction"], "GRE"),
    ("Charlatan", "/ˈʃɑː.lə.tən/", "Noun", "ভণ্ড, হাতুড়ে ডাক্তার", "The charlatan sold fake medicines.", "ভণ্ড লোকটি নকল ওষুধ বিক্রি করত।", ["Quack", "Impostor", "Fake"], ["Expert", "Authority"], "General"),
    ("Chivalrous", "/ˈʃɪv.əl.rəs/", "Adj", "উদার, বীরত্বপূর্ণ ও ভদ্র", "He gave a chivalrous gesture to the lady.", "সে ভদ্রমহিলাকে সম্মানজনক অভিবাদন জানিয়েছিল।", ["Courteous", "Gallant", "Knightly"], ["Rude", "Unchivalrous"], "Literature"),
    ("Circuitous", "/sɜːˈkjuː.ɪ.təs/", "Adj", "ঘুরানো, পরোক্ষ বা আঁকাবাঁকা", "We took a circuitous route to avoid traffic.", "জট এড়াতে আমরা এক ঘুরানো পথ নিয়েছিলাম।", ["Roundabout", "Indirect", "Winding"], ["Direct", "Straight"], "IELTS"),
    ("Circumscribe", "/ˈsɜː.kəm.skraɪb/", "Verb", "সীমিত করা, সীমানা নির্ধারণ করা", "Their powers were circumscribed by law.", "আইন দ্বারা তাদের ক্ষমতা সীমিত করা হয়েছিল।", ["Restrict", "Limit", "Confine"], ["Expand", "Free"], "Legal"),
    ("Circumspect", "/ˈsɜː.kəm.spekt/", "Adj", "সতর্ক, বিচক্ষণ বা পরিপক্ক", "He was circumspect in answering questions.", "প্রশ্নের উত্তর দিতে সে বেশ সতর্ক ছিল।", ["Cautious", "Prudent", "Guarded"], ["Reckless", "Careless"], "GRE"),
    ("Clandestine", "/klænˈdes.tɪn/", "Adj", "গুপ্ত, গোপনে পরিচালিত", "They held a clandestine meeting at midnight.", "মধ্যরাতে তারা এক গোপন বৈঠক করেছিল।", ["Secret", "Covert", "Surreptitious"], ["Open", "Public"], "IELTS"),
    ("Coerce", "/kəʊˈɜːs/", "Verb", "বলপ্রয়োগ করা, বাধ্য করা", "He was coerced into signing the contract.", "তাকে চুক্তিতে সই করতে বাধ্য করা হয়েছিল।", ["Force", "Compel", "Pressurize"], ["Persuade", "Encourage"], "Legal"),
    ("Cogent", "/ˈkəʊ.dʒənt/", "Adj", "জোরালো, যুক্তিযুক্ত ও প্ররোচনামূলক", "She presented a cogent argument.", "সে একটি অত্যন্ত যুক্তিযুক্ত বক্তব্য তুলে ধরল।", ["Convincing", "Compelling", "Persuasive"], ["Unconvincing", "Weak"], "BCS"),
    ("Cohesive", "/kəʊˈhiː.sɪv/", "Adj", "সুসংবদ্ধ, একতাবদ্ধ", "They formed a cohesive working group.", "তারা এক সুসংবদ্ধ কর্মগোষ্ঠী গঠন করল।", ["United", "Integrated", "Connected"], ["Divided", "Fragmented"], "Academic"),
    ("Collusion", "/kəˈluː.ʒən/", "Noun", "গোপন চক্রান্ত, সলাপররামর্শ", "They acted in collusion with the criminals.", "তারা অপরাধীদের সাথে গোপন চক্রান্তে লিপ্ত ছিল।", ["Conspiracy", "Secret agreement"], ["Honesty", "Openness"], "Legal"),
    ("Commensurate", "/kəˈmen.sjər.ət/", "Adj", "সমানুপাতিক, সমপরিমাণ", "Salary will be commensurate with experience.", "অভিজ্ঞতার সাথে সামঞ্জস্য রেখে বেতন দেওয়া হবে।", ["Proportionate", "Equivalent", "Equal"], ["Incommensurate", "Disproportionate"], "Business"),
    ("Commendable", "/kəˈmen.də.bəl/", "Adj", "প্রশংসনীয়, ফলোপযোগী", "His brave effort was truly commendable.", "তার সাহসী প্রচেষ্টা সত্যই প্রশংসনীয় ছিল।", ["Praiseworthy", "Admirable", "Laudable"], ["Blameworthy", "Reprehensible"], "Spoken"),
    ("Complacent", "/kəmˈpleɪ.sənt/", "Adj", "আত্মতুষ্ট, অসচেতন", "We cannot afford to be complacent about safety.", "নিরাপত্তা নিয়ে আমাদের আত্মতুষ্ট হওয়া সাজে না।", ["Self-satisfied", "Smug", "Careless"], ["Anxious", "Concerned"], "IELTS"),
    ("Conciliatory", "/kənˈsɪl.i.ə.tər.i/", "Adj", "শান্তিকামী, আপসপ্রবণ", "He adopted a conciliatory tone.", "সে এক আপসপ্রবণ সুর গ্রহণ করেছিল।", ["Peacemaking", "Mollifying", "Appeasing"], ["Antagonistic", "Aggressive"], "Academic"),
    ("Condone", "/kənˈdəʊn/", "Verb", "উপেক্ষা করা, অপরাধ ক্ষমা চোখে দেখা", "We cannot condone violence in any form.", "আমরা কোনো ধরনের সহিংসতাকে প্রশ্রয় দিতে পারি না।", ["Overlook", "Pardon", "Forgive"], ["Condemn", "Punish"], "Legal"),
    ("Conflagration", "/ˌkɒn.fləˈɡreɪ.ʃən/", "Noun", "ভয়াবহ অগ্নিকাণ্ড", "The conflagration destroyed entire blocks.", "ভয়াবহ অগ্নিকাণ্ডে পুরো এলাকা ধ্বংস হয়ে গিয়েছিল।", ["Blaze", "Inferno", "Firestorm"], ["Flood", "Water"], "General"),
    ("Confound", "/kənˈfaʊnd/", "Verb", "বিভ্রান্ত করা, হতবুদ্ধি করা", "The complex puzzle confounded everyone.", "জটিল ধাঁধাটি সবাইকে বিভ্রান্ত করে দিয়েছিল।", ["Confuse", "Baffle", "Perplex"], ["Clarify", "Explain"], "GRE"),

    # 31 - 60
    ("Congenial", "/kənˈdʒiː.ni.əl/", "Adj", "মনোপূত, অনুকূল বা বন্ধুত্বপূর্ণ", "The work environment is very congenial.", "কাজের পরিবেশটি অত্যন্ত প্রীতিপ্রদ।", ["Pleasant", "Friendly", "Compatible"], ["Uncongenial", "Hostile"], "Spoken"),
    ("Conjecture", "/kənˈdʒek.tʃər/", "Noun", "অনুমান, আন্দাজ", "His theory is based on pure conjecture.", "তার তত্ত্বটি স্রেফ অনুমানের ওপর প্রতিষ্ঠিত।", ["Guess", "Surmise", "Speculation"], ["Fact", "Certainty"], "Academic"),
    ("Conspicuous", "/kənˈspɪk.ju.əs/", "Adj", "দৃষ্টিআকর্ষণকারী, স্পষ্ট দৃশ্যমান", "He felt conspicuous in his red suit.", "লাল স্যুটে সে নিজেকে বেশ স্পষ্ট দৃশ্যমান মনে করছিল।", ["Noticeable", "Prominent", "Obvious"], ["Inconspicuous", "Hidden"], "IELTS"),
    ("Consummate", "/ˈkɒn.sə.mət/", "Adj", "নিপুণ, নিখুঁত বা চরম দক্ষ", "He played with consummate skill.", "সে চরম দক্ষতার সাথে খেলেছিল।", ["Masterly", "Superb", "Complete"], ["Incomplete", "Inexpert"], "GRE"),
    ("Contemptuous", "/kənˈtemp.tʃu.əs/", "Adj", "ঘৃণাপূর্ণ, অবজ্ঞাসূচক", "He gave a contemptuous laugh.", "সে এক ঘৃণাপূর্ণ হাসি হাসল।", ["Scornful", "Disdainful", "Dismissive"], ["Respectful", "Polite"], "Literature"),
    ("Contingent", "/kənˈtɪn.dʒənt/", "Adj", "নির্ভরশীল, অনিশ্চিত ঘটনা সাপেক্ষ", "Our plans are contingent on the weather.", "আমাদের পরিকল্পনা আবহাওয়ার ওপর নির্ভরশীল।", ["Dependent", "Conditional", "Subject to"], ["Independent", "Certain"], "Business"),
    ("Contrite", "/kənˈtraɪt/", "Adj", "অনুপ্ত, লজ্জিত ও অনুশোচনাগ্রস্ত", "He made a contrite apology.", "সে এক আন্তরিক অনুশোচনা প্রকাশ করল।", ["Penitent", "Remorseful", "Sorry"], ["Unrepentant", "Defiant"], "GRE"),
    ("Conundrum", "/kəˈnʌn.drəm/", "Noun", "জটিল ধাঁধা, কঠিন সমস্যা", "Arranging housing was a real conundrum.", "থাকার ব্যবস্থা করা এক বাস্তব জটিল সমস্যা ছিল।", ["Enigma", "Puzzle", "Riddle"], ["Solution", "Answer"], "IELTS"),
    ("Copious", "/ˈkəʊ.pi.əs/", "Adj", "প্রচুর, বিপুল বা অঢেল", "She took copious notes during class.", "ক্লাসে সে প্রচুর নোট নিয়েছিল।", ["Abundant", "Plentiful", "Ample"], ["Sparse", "Meager"], "Academic"),
    ("Corroborate", "/kəˈrɒb.ə.reɪt/", "Verb", "সত্যতা জোরদার করা, নিশ্চিত করা", "Witnesses corroborated his story.", "সাক্ষীরা তার গল্পের সত্যতা নিশ্চিত করল।", ["Confirm", "Verify", "Substantiate"], ["Contradict", "Refute"], "Legal"),
    ("Cosmopolitan", "/ˌkɒz.məˈpɒl.ɪ.tən/", "Adj", "বিশ্বজনীন, বহুসংস্কৃতিপূর্ণ", "London is a truly cosmopolitan city.", "লন্ডন একটি যথার্থ বিশ্বজনীন শহর।", ["Global", "Multicultural", "Worldwide"], ["Local", "Provincial"], "IELTS"),
    ("Culpable", "/ˈkʌl.pə.bəl/", "Adj", "দণ্ডনীয়, অপরাধী বা দোষী", "He was held culpable for the accident.", "দুর্ঘটনার জন্য তাকে দোষী সাব্যস্ত করা হয়েছিল।", ["Guilty", "Blameworthy", "Liable"], ["Innocent", "Blameless"], "Legal"),
    ("Cursory", "/ˈkɜː.sər.i/", "Adj", "উপরিউক্ত, দ্রুত বা অসতর্ক দৃষ্টিপাত", "He gave the file a cursory glance.", "সে ফাইলের দিকে এক দ্রুত চোখ বুলিয়ে নিল।", ["Hasty", "Superficial", "Quick"], ["Thorough", "Detailed"], "BCS"),
    ("Curtail", "/kəˈteɪl/", "Verb", "সংক্ষিপ্ত করা, ছাঁটাই করা", "Budget cuts forced us to curtail expenses.", "বাজেট হ্রাসের কারণে আমরা খরচ ছাঁটাই করতে বাধ্য হলাম।", ["Reduce", "Shorten", "Lessen"], ["Expand", "Extend"], "Business"),
    ("Debilitate", "/dɪˈbɪl.ɪ.teɪt/", "Verb", "দুর্বল করা, শক্তি নিঃশেষ করা", "The illness severely debilitated him.", "অসুখটি তাকে চরমভাবে দুর্বল করে দিয়েছিল।", ["Weaken", "Enfeeble", "Disable"], ["Strengthen", "Invigorate"], "Medical"),
    ("Deference", "/ˈdef.ər.əns/", "Noun", "শ্রদ্ধা, মান্যকরণ বা নতিস্বীকার", "He bowed his head in deference.", "সে শ্রদ্ধার সাথে মাথা নোয়াল।", ["Respect", "Reverence", "Submission"], ["Disrespect", "Defiance"], "Literature"),
    ("Deleterious", "/ˌdel.ɪˈtɪə.ri.əs/", "Adj", "ক্ষতিকর, অনিষ্টকর", "Smoking has a deleterious effect on health.", "ধূমপানের স্বাস্থ্যের ওপর ক্ষতিকর প্রভাব রয়েছে।", ["Harmful", "Damaging", "Detrimental"], ["Beneficial", "Harmless"], "Medical"),
    ("Delineate", "/dɪˈlɪn.i.eɪt/", "Verb", "চিত্রিত করা, বর্ণনা করা", "The report delineates future priorities.", "প্রতিবেদনটিতে ভবিষ্যতের অগ্রাধিকারসমূহ বর্ণিত হয়েছে।", ["Describe", "Outline", "Depict"], ["Confuse", "Distort"], "Academic"),
    ("Demagogue", "/ˈdem.ə.ɡɒɡ/", "Noun", "উত্তেজক বক্তা, গণপ্রবঞ্চক নেতা", "The demagogue exploited public fear.", "উত্তেজক বক্তাটি জনগণের ভয়কে কাজে লাগিয়েছিল।", ["Agitator", "Firebrand"], ["Statesman", "Peacemaker"], "Politics"),
    ("Denigrate", "/ˈden.ɪ.ɡreɪt/", "Verb", "কলঙ্কিত করা, হেয় করা", "Do not denigrate the efforts of others.", "অন্যের চেষ্টাকে হেয় করবে না।", ["Belittle", "Disparage", "Defame"], ["Praise", "Extol"], "GRE"),
    ("Depict", "/dɪˈpɪkt/", "Verb", "চিত্রিত করা, ফুটিয়ে তোলা", "The novel depicts life in the 19th century.", "উপন্যাসটিতে ১৯ শতকের জীবন চিত্রিত হয়েছে।", ["Portray", "Represent", "Illustrate"], ["Conceal", "Hide"], "Literature"),
    ("Deprecate", "/ˈdep.rə.keɪt/", "Verb", "অনুমোদন না করা, নিন্দা করা", "He deprecated the use of force.", "সে শক্তিপ্রয়োগের তীব্র নিন্দা জানিয়েছিল।", ["Disapprove", "Deplore", "Condemn"], ["Approve", "Praise"], "GRE"),
    ("Deride", "/dɪˈraɪd/", "Verb", "উপহাস করা, ঠাট্টা করা", "They derided his ambitious plans.", "তারা তার উচ্চাকাঙ্ক্ষী পরিকল্পনাকে উপহাস করেছিল।", ["Mock", "Ridicule", "Taunt"], ["Praise", "Respect"], "Literature"),
    ("Desiccate", "/ˈdes.ɪ.keɪt/", "Verb", "শুষ্ক করা, পানিশূন্য করা", "The hot sun desiccated the soil.", "প্রখর সূর্য মাটি শুকিয়ে কাঠ করে দিয়েছিল।", ["Dry out", "Dehydrate"], ["Moisten", "Hydrate"], "Science"),
    ("Despondent", "/dɪˈspɒn.dənt/", "Adj", "হতাশ, বিষণ্ণ বা নিরুৎসাহী", "She grew despondent after the failure.", "ব্যর্থতার পর সে হতাশ হয়ে পড়েছিল।", ["Hopeless", "Dejected", "Glum"], ["Cheerful", "Optimistic"], "Literature"),
    ("Despot", "/ˈdes.pɒt/", "Noun", "স্বৈরাচারী শাসক, একনায়ক", "The country was ruled by a ruthless despot.", "দেশটি এক নির্দয় স্বৈরাচারী দ্বারা শাসিত হতো।", ["Tyrant", "Dictator", "Autocrat"], ["Democrat"], "Politics"),
    ("Destitute", "/ˈdes.tɪ.tʃuːt/", "Adj", "নিঃস্ব, চরম দরিদ্র", "Floods left thousands of people destitute.", "বন্যায় হাজার হাজার মানুষ নিঃস্ব হয়ে পড়েছে।", ["Impoverished", "Penniless", "Needy"], ["Wealthy", "Prosperous"], "Social"),
    ("Detrimental", "/ˌdet.rɪˈmen.təl/", "Adj", "ক্ষতিকর, অপকারী", "Stress can be detrimental to performance.", "মানসিক চাপ কর্মক্ষমতার ওপর ক্ষতিকর হতে পারে।", ["Harmful", "Damaging", "Inimical"], ["Helpful", "Favorable"], "Academic"),
    ("Devoid", "/dɪˈvɔɪd/", "Adj", "বর্জিত, শূন্য বা বিহীন", "His voice was devoid of emotion.", "তার কণ্ঠস্বর ছিল আবেগহীন।", ["Lacking", "Empty", "Bereft"], ["Full", "Abounding"], "Academic"),
    ("Dexterous", "/ˈdek.strəs/", "Adj", "হাতে-কলমে দক্ষ, চটপটে", "The surgeon had dexterous fingers.", "সার্জনের হাত দুটি ছিল অত্যন্ত চটপটে ও দক্ষ।", ["Skillful", "Adept", "Adroit"], ["Clumsy", "Awkward"], "Medical"),

    # 61 - 90
    ("Diatribe", "/ˈdaɪ.ə.traɪb/", "Noun", "তীব্র ভর্ৎসনা, কটু সমালোচনা", "He launched a diatribe against the media.", "সে মিডিয়ার বিরুদ্ধে এক তীব্র বিষোদগার ছড়ালো।", ["Harangue", "Tirade", "Denunciation"], ["Praise", "Eulogy"], "GRE"),
    ("Dictum", "/ˈdɪk.təm/", "Noun", "আপ্তবাক্য, নীতিবাক্য", "He cited the old dictum 'Honesty is best'.", "সে পুরনো নীতিবাক্য 'সততাই সেরা' উদ্ধৃত করল।", ["Maxim", "Adage", "Proverb"], [], "Literature"),
    ("Didactic", "/daɪˈdæk.tɪk/", "Adj", "উপদেশমূলক, শিক্ষা প্রদানকারী", "The story has a strong didactic message.", "গল্পটিতে এক গভীর উপদেশমূলক বার্তা রয়েছে।", ["Instructional", "Educational", "Moralizing"], [], "Academic"),
    ("Diffident", "/ˈdɪf.ɪ.dənt/", "Adj", "আত্মবিশ্বাসহীন, লাজুক", "He was diffident about expressing opinions.", "মতামত প্রকাশে সে বেশ আত্মবিশ্বাসহীন ছিল।", ["Shy", "Timid", "Unconfident"], ["Confident", "Bold"], "Psychology"),
    ("Digress", "/daɪˈɡres/", "Verb", "মূল বিষয় থেকে দূরে সরে যাওয়া", "Allow me to digress for a moment.", "আমাকে ক্ষণিকের জন্য মূল আলোচনার বাইরে যেতে দিন।", ["Deviate", "Stray", "Wander"], ["Stay on point"], "Spoken"),
    ("Diminutive", "/dɪˈmɪn.jə.tɪv/", "Adj", "ক্ষুদ্রাকৃতির, অতি ছোট", "She sat in a diminutive armchair.", "সে এক ক্ষুদ্রাকৃতির আরামদায়ক চেয়ারে বসল।", ["Tiny", "Small", "Miniature"], ["Huge", "Gigantic"], "Literature"),
    ("Discerning", "/dɪˈsɜː.nɪŋ/", "Adj", "সূক্ষ্মদর্শী, বিচক্ষণ বা পারদর্শী", "He is a discerning judge of art.", "সে শিল্পকলার এক সূক্ষ্মদর্শী জজ।", ["Perceptive", "Astute", "Insightful"], ["Undiscriminating"], "Academic"),
    ("Discomfit", "/dɪsˈkʌm.fɪt/", "Verb", "অপ্রস্তুত করা, লজ্জিত করা", "The question clearly discomfited him.", "প্রশ্নটি তাকে স্পষ্টতই অপ্রস্তুত করে দিল।", ["Embarrass", "Unsettle", "Fluster"], ["Reassure", "Calm"], "GRE"),
    ("Discordant", "/dɪsˈkɔː.dəন্ত/", "Adj", "বেসুরো, অমিল বা অসঙ্গতিপূর্ণ", "Discordant notes ruined the song.", "বেসুরো সুর গানটিকে নষ্ট করে দিয়েছিল।", ["Inharmonious", "Clashing", "Harsh"], ["Harmonious", "Melodious"], "Music"),
    ("Discretion", "/dɪˈskreʃ.ən/", "Noun", "বিচক্ষণতা, সিদ্ধান্ত নেওয়ার ক্ষমতা", "You can use your discretion in this case.", "এই ক্ষেত্রে আপনি আপনার বিচক্ষণতা প্রয়োগ করতে পারেন।", ["Prudence", "Tact", "Judgment"], ["Indiscretion", "Recklessness"], "Legal"),
    ("Disparate", "/ˈdɪs.pər.ət/", "Adj", "সম্পূর্ণ ভিন্ন, বৈষম্যমূলক", "They held disparate views on the subject.", "বিষয়টিতে তাদের সম্পূর্ণ ভিন্ন দৃষ্টিভঙ্গি ছিল।", ["Different", "Diverse", "Dissimilar"], ["Similar", "Identical"], "Academic"),
    ("Dispassionate", "/dɪsˈpæʃ.ən.ət/", "Adj", "আবেগহীন, নিরপেক্ষ বা বস্তুনিষ্ঠ", "He gave a dispassionate review of facts.", "সে তথ্যের এক নিরপেক্ষ পর্যালোচনা উপস্থাপন করল।", ["Impartial", "Objective", "Unbiased"], ["Biased", "Emotional"], "IELTS"),
    ("Dissemble", "/dɪˈsem.bəl/", "Verb", "সত্য গোপন করা, ভান করা", "He tried to dissemble his real motives.", "সে তার আসল উদ্দেশ্য গোপন করার চেষ্টা করেছিল।", ["Disguise", "Feign", "Conceal"], ["Reveal", "Disclose"], "GRE"),
    ("Dissident", "/ˈdɪs.ɪ.dənt/", "Noun", "ভিন্নমতাবলম্বী, বিদ্রোহী ব্যক্তি", "The regime suppressed political dissidents.", "শাসনব্যবস্থা রাজনৈতিক ভিন্নমতাবলম্বীদের দমন করেছিল।", ["Dissenter", "Rebel", "Nonconformist"], ["Conformist", "Loyalist"], "Politics"),
    ("Dissonance", "/ˈdɪs.ə.nəns/", "Noun", "অসঙ্গতি, সুরের অমিল", "Cognitive dissonance causes discomfort.", "জ্ঞানীয় অসঙ্গতি অস্বস্তির সৃষ্টি করে।", ["Discord", "Inconsistency", "Conflict"], ["Harmony", "Agreement"], "Psychology"),
    ("Docile", "/ˈdəʊ.saɪl/", "Adj", "সহজবশ্য, শান্ত ও অনুগত", "The horse was gentle and docile.", "ঘোড়াটি ছিল শান্ত ও অনুগত।", ["Obedient", "Submissive", "Tractable"], ["Rebellious", "Stubborn"], "General"),
    ("Dogmatic", "/dɒɡˈmæt.ɪk/", "Adj", "একগুঁয়ে, গোঁড়া বা মতান্ধ", "He is dogmatic about his political beliefs.", "সে তার রাজনৈতিক বিশ্বাসে অত্যন্ত গোঁড়া।", ["Opinionated", "Assertion", "Inflexible"], ["Open-minded", "Flexible"], "BCS"),
    ("Doleful", "/ˈdəʊl.fəl/", "Adj", "শোকাকুল, করুণ বা বিষাদময়", "A doleful expression crossed her face.", "তার মুখে এক করুণ এক্সপ্রেশন ভেসে উঠল।", ["Mournful", "Sorrowful", "Sad"], ["Joyful", "Cheerful"], "Literature"),
    ("Dubious", "/ˈdʒuː.bi.əs/", "Adj", "সন্দেহজনক, অনিশ্চিত", "The claims sound highly dubious to me.", "দাবিগুলো আমার কাছে বেশ সন্দেহজনক মনে হয়।", ["Doubtful", "Questionable", "Uncertain"], ["Certain", "Reliable"], "IELTS"),
    ("Duplicity", "/dʒuːˈplɪs.ə.ti/", "Noun", "শঠতা, কপটতা বা দ্বিমুখী আচরণ", "His duplicity was exposed eventually.", "অবশেষে তার কপটতা উন্মোচিত হয়ে গেল।", ["Deceit", "Double-dealing", "Dishonesty"], ["Honesty", "Candor"], "GRE"),
    ("Ebullient", "/ɪˈbʌl.i.ənt/", "Adj", "উচ্ছ্বসিত, প্রাণবন্ত ও উল্লসিত", "She was in an ebullient mood today.", "আজ সে এক উচ্ছ্বসিত মেজাজে ছিল।", ["Exuberant", "Enthusiastic", "Lively"], ["Depressed", "Somber"], "Spoken"),
    ("Eclectic", "/ɪˈklek.tɪk/", "Adj", "বহুমুখী, নানা উৎস থেকে সংগৃহীত", "He has an eclectic taste in music.", "সংগীতে তার এক বহুমুখী রুচি রয়েছে।", ["Diverse", "Wide-ranging", "Varied"], ["Narrow", "Uniform"], "Academic"),
    ("Efficacy", "/ˈef.ɪ.kə.si/", "Noun", "কার্যকারিতা, মোঘল ফলপ্রসূতা", "Tests proved the efficacy of the vaccine.", "পরীক্ষায় ভ্যাকসিনের কার্যকারিতা প্রমাণিত হয়েছিল।", ["Effectiveness", "Potency", "Efficiency"], ["Inefficacy", "Uselessness"], "Medical"),
    ("Effrontery", "/ɪˈfrʌn.tər.i/", "Noun", "ধৃষ্টতা, বেহায়াপনা বা আস্পর্ধা", "He had the effrontery to demand more money.", "আরও টাকা দাবি করার ধৃষ্টতা তার হয়েছিল।", ["Audacity", "Impudence", "Insolence"], ["Timidity", "Modesty"], "GRE"),
    ("Effusive", "/ɪˈfjuː.sɪv/", "Adj", "উচ্ছ্বসিত, আবেগঘন প্রশংসাভরা", "She received effusive praise for her performance.", "সে তার পারফরম্যান্সের জন্য উচ্ছ্বসিত প্রশংসা পেল।", ["Demonstrative", "Gushing", "Enthusiastic"], ["Reserved", "Restrained"], "Spoken"),
    ("Egregious", "/ɪˈɡriː.dʒəs/", "Adj", "মারাত্মক, চরম খারাপ বা জঘন্য", "It was an egregious violation of human rights.", "এটি ছিল মানবাধিকারের এক মারাত্মক লঙ্ঘন।", ["Flagrant", "Shocking", "Glaring"], ["Minor", "Inconspicuous"], "GRE"),
    ("Elicit", "/ɪˈlɪs.ɪt/", "Verb", "প্রকাশ ঘটানো, উত্তর বের করে আনা", "The question elicited a smile from her.", "প্রশ্নটি তার মুখ থেকে একটি মিষ্টি হাসি বের করে আনল।", ["Evoke", "Extract", "Draw out"], ["Suppress", "Hide"], "IELTS"),
    ("Embellish", "/ɪmˈbel.ɪʃ/", "Verb", "সজ্জিত করা, বাড়িয়ে বলা", "Don't embellish the truth with lies.", "সত্যের সাথে মিথ্যা মিশিয়ে বাড়িয়ে বোলো না।", ["Adorn", "Decorate", "Exaggerate"], ["Simplify", "Strip"], "Spoken"),
    ("Emulate", "/ˈem.jə.leɪt/", "Verb", "অনুকরণ করা, সমকক্ষ হওয়ার চেষ্টা করা", "Young scholars try to emulate his success.", "তরুণ গবেষকরা তার সাফল্য অনুকরণ করতে চান।", ["Imitate", "Copy", "Mirror"], [], "Academic"),
    ("Encomium", "/enˈkəʊ.mi.əm/", "Noun", "উচ্চ প্রশংসা, স্তুতিবাক্য", "The poem was an encomium to nature.", "কবিতাটি ছিল প্রকৃতির এক উচ্চ প্রশংসাগীতি।", ["Tribute", "Eulogy", "Praise"], ["Condemnation", "Criticism"], "Literature"),

    # 91 - 120
    ("Endemic", "/enˈdem.ɪk/", "Adj", "স্থানিক, নির্দিষ্ট অঞ্চলের সংক্রামক", "Malaria is endemic in tropical regions.", "ম্যালেরিয়া ক্রান্তীয় অঞ্চলে স্থানিক রোগ।", ["Native", "Local", "Indigenous"], ["Epidemic", "Global"], "Medical"),
    ("Enervate", "/ˈen.ə.veɪt/", "Verb", "দুর্বল করা, তেজ হরণ করা", "The heat enervated the workers.", "তাপদাহ কর্মীদের তেজ হরণ করেছিল।", ["Exhaust", "Weaken", "Fatigue"], ["Energize", "Invigorate"], "GRE"),
    ("Engender", "/ɪnˈdʒen.dər/", "Verb", "জন্ম দেওয়া, সৃষ্টি করা", "His speech engendered hope in people.", "তার ভাষণ মানুষের মনে আশার সঞ্চার করেছিল।", ["Cause", "Produce", "Generate"], ["Destroy", "Suppress"], "Academic"),
    ("Enigmatic", "/ˌen.ɪɡˈmæt.ɪk/", "Adj", "রহস্যময়, জটিল ও অস্পষ্ট", "She gave an enigmatic smile.", "সে এক রহস্যময় হাসি দিল।", ["Mysterious", "Puzzling", "Obscure"], ["Clear", "Explicit"], "Literature"),
    ("Enmity", "/ˈen.mə.ti/", "Noun", "শত্রুতা, বিদ্বেষ বা বৈরিতা", "Deep enmity existed between two families.", "দুটি পরিবারের মধ্যে গভীর বৈরিতা বিরাজ করছিল।", ["Hostility", "Animosity", "Hatred"], ["Amity", "Friendship"], "BCS"),
    ("Ephemeral", "/ɪˈfem.ər.əl/", "Adj", "ক্ষণস্থায়ী, অল্পকালস্থায়ী", "Fame in pop culture is often ephemeral.", "পপ কালচারের খ্যাতি প্রায়ই ক্ষণস্থায়ী।", ["Fleeting", "Transient", "Short-lived"], ["Permanent", "Eternal"], "IELTS"),
    ("Equivocal", "/ɪˈkwɪv.ə.kəl/", "Adj", "দ্ব্যর্থবোধক, অস্পষ্ট ও সন্দেহজনক", "His answer was vague and equivocal.", "তার উত্তরটি ছিল অস্পষ্ট ও দ্ব্যর্থবোধক।", ["Ambiguous", "Uncertain", "Evasive"], ["Clear", "Unequivocal"], "GRE"),
    ("Erudite", "/ˈer.ʊ.daɪt/", "Adj", "পণ্ডিত, প্রজ্ঞাবান ও বিদ্বান", "An erudite scholar delivered the lecture.", "এক প্রজ্ঞাবান পণ্ডিত বক্তব্য প্রদান করেছিলেন।", ["Learned", "Scholarly", "Knowledgeable"], ["Ignorant", "Uneducated"], "Academic"),
    ("Esoteric", "/ˌes.əˈter.ɪk/", "Adj", "গূঢ়, জটিল ও সীমিত লোকের বোধগম্য", "Quantum physics seems esoteric to many.", "কোয়ান্টাম পদার্থবিজ্ঞান অনেকের কাছে গূঢ় মনে হয়।", ["Obscure", "Abstruse", "Arcane"], ["Common", "Familiar"], "GRE"),
    ("Eulogy", "/ˈjuː.lə.dʒi/", "Noun", "প্রশংসাগীতি, মৃত ব্যক্তির প্রশংসাসূচক বক্তব্য", "He delivered a moving eulogy at the funeral.", "সে শেষকৃত্যে এক হৃদয়স্পর্শী প্রশংসাসূচক বক্তব্য দিয়েছিল।", ["Tribute", "Panegyric", "Praise"], ["Condemnation"], "Literature"),
    ("Exacerbate", "/ɪɡˈzæs.ə.beɪt/", "Verb", "পরিস্থিতি আরও খারাপ করা", "The rain served to exacerbate the flood.", "বৃষ্টি বন্যা পরিস্থিতিকে আরও খারাপ করেছিল।", ["Worsen", "Aggravate", "Intensify"], ["Improve", "Alleviate"], "IELTS"),
    ("Exculpate", "/ˈek.skʌl.peɪt/", "Verb", "দোষমুক্ত করা, নিষ্পাপ প্রমাণ করা", "New evidence exculpated the suspect.", "নতুন সাক্ষ্য সন্দেহভাজনকে দোষমুক্ত করল।", ["Exonerate", "Acquit", "Vindicate"], ["Convict", "Blame"], "Legal"),
    ("Exemplary", "/ɪɡˈzem.plər.i/", "Adj", "দৃষ্টান্তমূলক, অনুসরণযোগ্য", "She displayed exemplary courage.", "সে দৃষ্টান্তমূলক সাহস প্রদর্শন করেছিল।", ["Model", "Praiseworthy", "Admirable"], ["Unworthy", "Poor"], "Spoken"),
    ("Exhort", "/ɪɡˈzɔːt/", "Verb", "উপদেশ দেওয়া, উৎসাহিত করা", "The governor exhorted citizens to vote.", "গভর্নর নাগরিকদের ভোট দিতে উৎসাহিত করলেন।", ["Urge", "Encourage", "Advise"], ["Discourage", "Dissuade"], "Politics"),
    ("Exigent", "/ˈek.sɪ.dʒənt/", "Adj", "জরুরি, অবিলম্বে ব্যবস্থা গ্রহণযোগ্য", "Exigent circumstances demanded quick action.", "জরুরি পরিস্থিতি দ্রুত পদক্ষেপ দাবি করেছিল।", ["Urgent", "Pressing", "Critical"], ["Nonurgent"], "GRE"),
    ("Exonerate", "/ɪɡˈzɒn.ə.reɪt/", "Verb", "দায়মুক্তি দেওয়া, নির্দোষ ঘোষণা করা", "The audit exonerated him from fraud charges.", "অডিট তাকে জালিয়াতির অভিযোগ থেকে দায়মুক্তি দিল।", ["Absolve", "Acquit", "Clear"], ["Incriminate", "Convict"], "Legal"),
    ("Extemporaneous", "/ekˌstem.pəˈreɪ.ni.əs/", "Adj", "উপস্থিতমত প্রস্তুত, পূর্বপ্রস্তুতিহীন", "He made an extemporaneous speech.", "সে এক পূর্বপ্রস্তুতিহীন বক্তৃতা দিয়েছিল।", ["Impromptu", "Unrehearsed", "Spontaneous"], ["Planned", "Rehearsed"], "Spoken"),
    ("Extraneous", "/ɪkˈstreɪ.ni.əs/", "Adj", "অপ্রাসঙ্গিক, বহিরাগত", "Filter out all extraneous information.", "সকল অপ্রাসঙ্গিক তথ্য বাদ দিন।", ["Irrelevant", "Unrelated", "External"], ["Essential", "Relevant"], "Academic"),
    ("Extravagant", "/ɪkˈstræv.ə.ɡənt/", "Adj", "অমিতব্যয়ী, অতি অপচয়ী", "He has extravagant spending habits.", "তার অতিরিক্ত অপচয় করার অভ্যাস রয়েছে।", ["Wasteful", "Profligate", "Excessive"], ["Thrifty", "Frugal"], "Spoken"),
    ("Facetious", "/fəˈsiː.ʃəs/", "Adj", "হালকা রসাত্মক, অহেতুক তামাশাপূর্ণ", "Don't be facetious about serious matters.", "গম্ভীর বিষয়ে অহেতুক তামাশা কোরো না।", ["Flippant", "Playful", "Joking"], ["Serious", "Solemn"], "GRE"),
    ("Fallacious", "/fəˈleɪ.ʃəs/", "Adj", "ভ্রান্ত, যুক্তিহীন বা মিথ্যা", "His reasoning is totally fallacious.", "তার যুক্তি পুরোপুরি ভ্রান্ত।", ["Misleading", "False", "Erroneous"], ["Valid", "Sound"], "Academic"),
    ("Fastidious", "/fæsˈtɪd.i.əs/", "Adj", "খুঁতখুঁতে, সহজে সন্তুষ্ট হয় না এমন", "She is fastidious about cleanliness.", "পরিচ্ছন্নতার বিষয়ে সে অত্যন্ত খুঁতখুঁতে।", ["Meticulous", "Picky", "Fussy"], ["Careless", "Sloppy"], "BCS"),
    ("Fatuous", "/ˈfætʃ.u.əs/", "Adj", "বোকা, নির্বোধ বা সারহীন", "He made a fatuous comment.", "সে এক নির্বোধ মন্তব্য করেছিল।", ["Silly", "Foolish", "Inane"], ["Sensible", "Wise"], "GRE"),
    ("Fervent", "/ˈfɜː.vənt/", "Adj", "উত্তপ্ত, তীব্র বা ব্যাকুল", "He expressed a fervent desire to learn.", "সে শেখার এক ব্যাকুল ইচ্ছা প্রকাশ করেছিল।", ["Passionate", "Ardent", "Earnest"], ["Apathetic", "Cool"], "Literature"),
    ("Fiasco", "/fiˈæs.kəʊ/", "Noun", "চরম ব্যর্থতা, লজ্জাজনক পণ্ড", "The launch turned into a complete fiasco.", "উদ্বোধনটি এক চরম ব্যর্থতায় পর্যবসিত হলো।", ["Disaster", "Failure", "Catastrophe"], ["Success", "Triumph"], "General"),
    ("Fickle", "/ˈfɪk.əl/", "Adj", "চঞ্চল, পরিবর্তনশীল বা অস্থিরমনা", "Weather here can be notoriously fickle.", "এখানকার আবহাওয়া কুখ্যাতভাবে পরিবর্তনশীল হতে পারে।", ["Changeable", "Capricious", "Unstable"], ["Constant", "Steadfast"], "Spoken"),
    ("Fidelity", "/fɪˈdel.ə.ti/", "Noun", "আনুগত্য, বিশ্বাসস্ততা বা সত্যতা", "He was rewarded for his fidelity.", "তার আনুগত্যের জন্য তাকে পুরস্কৃত করা হয়েছিল।", ["Loyalty", "Faithfulness", "Devotion"], ["Treachery", "Infidelity"], "Literature"),
    ("Flagrant", "/ˈfleɪ.ɡrənt/", "Adj", "মারাত্মক, প্রকাশ্য ও জঘন্য", "It was a flagrant violation of rules.", "এটি নিয়মের এক মারাত্মক ও প্রকাশ্য লঙ্ঘন ছিল।", ["Glaring", "Blatant", "Conspicuous"], ["Subtle", "Minor"], "Legal"),
    ("Flamboyant", "/flæmˈbɔɪ.ənt/", "Adj", "জাঁকজমকপূর্ণ, চোখধাঁধানো", "He wore a flamboyant costume.", "সে এক চোখধাঁধানো পোশাক পরিধান করেছিল।", ["Showy", "Ostentatious", "Colorful"], ["Modest", "Plain"], "Fashion"),
    ("Fledgling", "/ˈfledʒ.lɪŋ/", "Noun", "নবাগত, অনভিজ্ঞ ব্যক্তি বা প্রতিষ্ঠান", "The fledgling company is growing fast.", "নতুন নবাগত কোম্পানিটি দ্রুত বৃদ্ধি পাচ্ছে।", ["Novice", "Beginner", "Startup"], ["Veteran", "Expert"], "Business"),

    # 121 - 150
    ("Flippant", "/ˈflɪp.ənt/", "Adj", "হালকা মেজাজী, অসম্মানজনক চপল", "She made a flippant remark about the crisis.", "সংকট নিয়ে সে এক হালকা মেজাজী মন্তব্য করল।", ["Frivolous", "Offhand", "Disrespectful"], ["Serious", "Respectful"], "Spoken"),
    ("Flout", "/flaʊt/", "Verb", "অবজ্ঞা করা, আইন অমান্য করা", "Drivers who flout safety rules will be fined.", "যে চালকরা নিরাপত্তা আইন অমান্য করবে তাদের জরিমানা করা হবে।", ["Defy", "Disregard", "Violate"], ["Obey", "Comply"], "Legal"),
    ("Frugal", "/ˈfruː.ɡəl/", "Adj", "মিতব্যয়ী, হিসাব করে খরচকারী", "They lead a quiet, frugal life.", "তারা এক শান্ত ও মিতব্যয়ী জীবনযাপন করে।", ["Thrifty", "Economical", "Sparing"], ["Extravagant", "Wasteful"], "Spoken"),
    ("Futile", "/ˈfjuː.taɪl/", "Adj", "পণ্ড, নিরর্থক বা নিষ্ফল", "Their attempts to escape were futile.", "পালানোর জন্য তাদের চেষ্টা ছিল নিরর্থক।", ["Useless", "Vain", "Fruitless"], ["Effective", "Successful"], "IELTS"),
    ("Garrulous", "/ˈɡær.əl.əs/", "Adj", "বাচাল, অতিরিক্ত বাচাল স্বভাবে কথাবলা", "A garrulous driver talked throughout the trip.", "এক বাচাল ড্রাইভার পুরো ভ্রমণ জুড়ে কথা বলেই গেল।", ["Talkative", "Loquacious", "Voluble"], ["Taciturn", "Reticent"], "GRE"),
    ("Garish", "/ˈɡeə.rɪʃ/", "Adj", "কর্কশ উজ্জ্বল, চটকদার ও দৃষ্টিকটু", "She avoided wearing garish colors.", "সে চটকদার উজ্জ্বল রঙের পোশাক পরা এড়িয়ে চলত।", ["Gaudy", "Flashy", "Tasteless"], ["Subdued", "Tasteful"], "Fashion"),
    ("Gargantuan", "/ɡɑːˈɡæn.tʃu.ən/", "Adj", "বিশাল, অতিকায় বা প্রকাণ্ড", "Building the dam was a gargantuan task.", "বাঁধটি নির্মাণ করা এক প্রকাণ্ড কাজ ছিল।", ["Gigantic", "Huge", "Colossal"], ["Tiny", "Miniature"], "Literature"),
    ("Genial", "/ˈdʒiː.ni.əl/", "Adj", "সদয়, অমায়িক ও উষ্ণপ্রকৃতির", "Our host was warm and genial.", "আমাদের মেজবান ছিলেন আন্তরিক ও অমায়িক।", ["Friendly", "Cordial", "Amiable"], ["Cold", "Unfriendly"], "Spoken"),
    ("Germane", "/dʒɜːˈmeɪn/", "Adj", "প্রাসঙ্গিক, বিষয়োপযোগী", "Please keep your remarks germane to topic.", "আপনার বক্তব্য বিষয়ের সাথে প্রাসঙ্গিক রাখুন।", ["Relevant", "Pertinent", "Applicable"], ["Irrelevant", "Extraneous"], "Academic"),
    ("Gluttony", "/ˈɡlʌt.ən.i/", "Noun", "পেটুকতা, অতিরিক্ত আহার", "Gluttony is harmful to digestive health.", "অতিরিক্ত আহার পরিপাক স্বাস্থ্যের জন্য ক্ষতিকর।", ["Greed", "Overeating"], ["Abstinence", "Moderation"], "Health"),
    ("Grandiloquent", "/ɡrænˈdɪl.ə.kwənt/", "Adj", "আড়ম্বরপূর্ণ, ফাঁপা বুলিভরা", "He used grandiloquent language in his speech.", "সে তার ভাষণে আড়ম্বরপূর্ণ বড় বড় বুলি ব্যবহার করল।", ["Pompous", "Bombastic", "Pretentious"], ["Simple", "Unpretentious"], "GRE"),
    ("Gratuitous", "/ɡrəˈtʃuː.ɪ.təs/", "Adj", "অহেতুক, অপ্রয়োজনীয় বা অনাহূত", "The film contained gratuitous violence.", "চলচ্চিত্রটিতে অহেতুক সহিংসতা অন্তর্ভুক্ত ছিল।", ["Uncalled-for", "Unwarranted", "Needless"], ["Necessary", "Justified"], "Legal"),
    ("Gregarious", "/ɡrɪˈɡeə.ri.əs/", "Adj", "মিশুক, দলপ্রিয় বা সঙ্গপ্রিয়", "Dolphins are gregarious creatures.", "ডলফিন দলপ্রিয় সামাজিক প্রাণী।", ["Sociable", "Outgoing", "Friendly"], ["Solitary", "Reserved"], "BCS"),
    ("Guile", "/ɡaɪl/", "Noun", "ধূর্ততা, ছলনা বা চাতুরি", "He won the match through sheer guile.", "সে স্রেফ চাতুরির দ্বারা ম্যাচটি জিতেছিল।", ["Cunning", "Deceit", "Slyness"], ["Honesty", "Candor"], "Literature"),
    ("HACKNEYED", "/ˈhæk.niːd/", "Adj", "ঘিসাপিটা, গতানুগতিক ও একঘেয়ে", "The plot relied on hackneyed clichés.", "গল্পটি গতানুগতিক ঘিসাপিটা ধারণার ওপর নির্ভরশীল ছিল।", ["Trite", "Overused", "Banale"], ["Fresh", "Original"], "IELTS"),
    ("Halcyon", "/ˈhæl.si.ən/", "Adj", "শান্তিপূর্ণ, সোনালী বা সুখকর অতীত", "He recalled the halcyon days of youth.", "সে যৌবনের সোনালী শান্তিময় দিনগুলোর কথা স্মরণ করল।", ["Peaceful", "Tranquil", "Golden"], ["Stormy", "Turbulent"], "Literature"),
    ("Hapless", "/ˈhæp.ləs/", "Adj", "অভাগা, কপালপোড়া বা দুর্ভাগা", "The hapless victim lost all his savings.", "অভাগা ভুক্তভোগী তার সব সঞ্চয় হারিয়েছিল।", ["Unfortunate", "Unlucky", "Ill-fated"], ["Lucky", "Fortunate"], "Literature"),
    ("Harangue", "/həˈræŋ/", "Noun", "উত্তেজক দীর্ঘ বক্তৃতা, গালাগালপূর্ণ বক্তব্য", "He delivered a long harangue to crowd.", "সে ভিড়ের সামনে এক দীর্ঘ তর্কমূলক ভাষণ দিল।", ["Tirade", "Diatribe", "Rant"], [], "Politics"),
    ("Hedonism", "/ˈhiː.dən.ɪ.zəm/", "Noun", "ভোগবাদ, সুখই পরম লক্ষ্য এমন মতবাদ", "His life was dedicated to pure hedonism.", "তার জীবন খাঁটি ভোগবাদের প্রতি নিবেদিত ছিল।", ["Pleasure-seeking", "Sensualism"], ["Asceticism"], "Philosophy"),
    ("Hegemony", "/hɪˈɡem.ən.i/", "Noun", "আధిপত্য, নেতৃত্ব বা কর্তত্ব", "The empire maintained hegemony in region.", "সাম্রাজ্যটি অঞ্চলে তাদের আধিপত্য বজায় রেখেছিল।", ["Dominance", "Supremacy", "Control"], [], "History"),
    ("Heinous", "/ˈheɪ.nəs/", "Adj", "জঘন্য, নৃশংস বা ক্ষমাঘ্ন", "It was a heinous crime that shocked all.", "এটি একটি জঘন্য অপরাধ ছিল যা সবাইকে স্তব্ধ করেছিল।", ["Atrocious", "Monstrous", "Abominable"], ["Admirable", "Noble"], "Legal"),
    ("Hierarchy", "/ˈhaɪə.rɑː.ki/", "Noun", "ক্রমোচ্চ স্তরবিন্যাস, পদমর্যাদাক্রম", "There is a strict hierarchy in army.", "সেনাবাহিনীতে এক কঠোর পদমর্যাদাক্রম বিদ্যমান।", ["Ranking", "Pecking order", "Gradation"], [], "Management"),
    ("Homogeneous", "/ˌhɒm.əˈdʒiː.ni.əs/", "Adj", "সমজাতীয়, একই উপাদানবিশিষ্ট", "The class is culturally homogeneous.", "শ্রেণিটি সামাজিকভাবে সমজাতীয়।", ["Uniform", "Consistent", "Similar"], ["Heterogeneous", "Diverse"], "Academic"),
    ("Hyperbole", "/haɪˈpɜː.bəl.i/", "Noun", "অতিরঞ্জন, বাড়িয়ে বলা উক্তি", "To say he is a genius is hyperbole.", "তাকে প্রতিভা বলা একপ্রকার অতিরঞ্জন।", ["Exaggeration", "Overstatement"], ["Understatement"], "Literature"),
    ("Hypocrisy", "/hɪˈpɒk.rə.si/", "Noun", "ভণ্ডামি, মুনাফেকী বা দ্বিমুখী নীতি", "I cannot stand his sheer hypocrisy.", "আমি তার ভণ্ডামি সহ্য করতে পারি না।", ["In sincerity", "Insincerity", "Deceit"], ["Sincerity", "Honesty"], "Spoken"),
    ("Iconoclast", "/aɪˈkɒn.ə.klæst/", "Noun", "প্রথাভাঙ্গা ব্যক্তিত্ব, ঐতিহ্যবিরোধী", "An iconoclast challenged traditional views.", "এক প্রথাভাঙ্গা ব্যক্তিত্ব প্রচলিত ধারণাকে চ্যালেঞ্জ করল।", ["Rebel", "Dissenter", "Nonconformist"], ["Conformist"], "GRE"),
    ("Idiosyncrasy", "/ˌɪd.i.əˈsɪŋ.krə.si/", "Noun", "ব্যক্তিগত অদ্ভুত স্বভাব বা বৈশিষ্ট্য", "Wearing mismatched socks was his idiosyncrasy.", "বেমানান মোজা পরা ছিল তার এক অদ্ভুত বৈশিষ্ট্য।", ["Quirk", "Peculiarity", "Eccentricity"], [], "Psychology"),
    ("Ignominious", "/ˌɪɡ.nəˈmɪn.i.əs/", "Adj", "লজ্জাজনক, অপমানজনক", "They suffered an ignominious defeat.", "তারা এক লজ্জাজনক পরাজয়ের সম্মুখীন হলো।", ["Humiliating", "Disgraceful", "Shameful"], ["Glorious", "Honorable"], "History"),
    ("Illicit", "/ɪˈlɪs.ɪt/", "Adj", "অবৈধ, বেআইনি বা নিষিদ্ধ", "They were caught selling illicit drugs.", "অবৈধ মাদক বিক্রির সময় তারা ধরা পড়েছিল।", ["Illegal", "Unlawful", "Forbidden"], ["Legal", "Licicit"], "Legal"),
    ("Immutable", "/ɪˈmjuː.tə.bəl/", "Adj", "অপরিবর্তনীয়, অপরিবর্ত্য", "Laws of physics are considered immutable.", "পদার্থবিজ্ঞানের সূত্রগুলো অপরিবর্তনীয় হিসেবে গণ্য হয়।", ["Unchangeable", "Permanent", "Fixed"], ["Mutable", "Flexible"], "Science"),

    # 151 - 180
    ("Impartial", "/ɪmˈpɑː.ʃəl/", "Adj", "নিরপেক্ষ, পক্ষপাতহীন", "A judge must remain strictly impartial.", "একজন বিচারককে অবশ্যই সম্পূর্ণ নিরপেক্ষ থাকতে হবে।", ["Unbiased", "Neutral", "Fair"], ["Biased", "Partial"], "Legal"),
    ("Impeccable", "/ɪmˈpek.ə.bəl/", "Adj", "ত্রুটিহীন, নিখুঁত বা নিষ্পাপ", "She has impeccable manners.", "তার আচার-ব্যবহার অত্যন্ত নিখুঁত।", ["Flawless", "Faultless", "Perfect"], ["Flawed", "Imperfect"], "Spoken"),
    ("Impecunious", "/ˌɪm.pɪˈkjuː.ni.əs/", "Adj", "অর্থহীন, দরিদ্র বা নিঃস্ব", "An impecunious student lived on noodles.", "এক অর্থহীন ছাত্র নুডুলস খেয়ে দিন কাটাত।", ["Penniless", "Poor", "Indigent"], ["Wealthy", "Rich"], "GRE"),
    ("Impediment", "/ɪmˈped.ɪ.mənt/", "Noun", "বাধা, প্রতিবন্ধকতা", "Lack of funds is a major impediment.", "তহবিলের অভাব এক প্রধান প্রতিবন্ধকতা।", ["Obstacle", "Barrier", "Hindrance"], ["Aid", "Help"], "IELTS"),
    ("Imperious", "/ɪmˈpɪə.ri.əs/", "Adj", "অহংকারী, হুকুমদারি মেজাজের", "She spoke in an imperious tone.", "সে এক হুকুমদারি মেজাজে কথা বলল।", ["Domineering", "Arrogant", "Overbearing"], ["Humble", "Submissive"], "Literature"),
    ("Impetuous", "/ɪmˈpetʃ.u.əs/", "Adj", "অবিবেচক, আবেগপ্রবণ ও বেপরোয়া", "He made an impetuous decision.", "সে এক অবিবেচক তাড়াহুড়ো সিদ্ধান্ত নিল।", ["Rash", "Impulsive", "Hasty"], ["Cautious", "Considered"], "GRE"),
    ("Implacable", "/ɪmˈplæk.ə.bəl/", "Adj", "কঠোর, অনমনীয় ও অপরিবর্তনীয়", "He remained an implacable enemy.", "সে এক কঠোর অনমনীয় শত্রু হয়েই রইল।", ["Unforgiving", "Relentless", "Unappeasable"], ["Forgiving", "Placable"], "GRE"),
    ("Implicit", "/ɪmˈplɪs.ɪt/", "Adj", "অন্তর্নিহিত, পরোক্ষ বা সুনিশ্চিত", "There was an implicit warning in his words.", "তার কথার মধ্যে এক পরোক্ষ সতর্কবার্তা ছিল।", ["Implied", "Inherent", "Tacit"], ["Explicit", "Direct"], "Academic"),
    ("Impugn", "/ɪmˈpjuːn/", "Verb", "সত্যতা চ্যালেঞ্জ করা, সন্দেহ প্রকাশ করা", "Do not impugn my integrity.", "আমার সততা নিয়ে প্রশ্ন তুলবেন না।", ["Challenge", "Question", "Call into question"], ["Defend", "Support"], "GRE"),
    ("Impunity", "/ɪmˈpjuː.nə.ti/", "Noun", "শাস্তিহীনতা, অব্যাহতি", "Criminals cannot act with impunity.", "অপরাধীরা পার পেয়ে যেতে পারে না।", ["Immunity", "Exemption from punishment"], ["Liability"], "Legal"),
    ("Inadvertent", "/ˌɪn.ədˈvɜː.tənt/", "Adj", "অনিচ্ছাকৃত, অস সতর্কতাহেতু", "The mistake was purely inadvertent.", "ভুলটি ছিল সম্পূর্ণ অনিচ্ছাকৃত।", ["Unintentional", "Accidental"], ["Deliberate", "Intentional"], "Spoken"),
    ("Incandescent", "/ˌɪn.kænˈdes.ənt/", "Adj", "উজ্জ্বল দীপ্তিমান, অমলিন তেজস্বী", "The bulbs gave off an incandescent glow.", "বাল্বগুলো এক উজ্জ্বল দীপ্তি ছড়িয়ে দিচ্ছিল।", ["Luminous", "Radiant", "Glowing"], ["Dull", "Dark"], "Science"),
    ("Inchoate", "/ɪnˈkəʊ.eɪt/", "Adj", "প্রাথমিক, অপূর্ণ বা অপরিপক্ক", "His ideas are still inchoate.", "তার ধারণাগুলো এখনও প্রাথমিক পর্যায়ে রয়েছে।", ["Rudimentary", "Nascent", "Undeveloped"], ["Mature", "Developed"], "GRE"),
    ("Incisive", "/ɪnˈsaɪ.sɪv/", "Adj", "তীক্ষ্ণ, ধারালো ও প্রাঞ্জল", "She offered an incisive analysis of situation.", "সে পরিস্থিতির এক প্রাঞ্জল বিশ্লেষণ উপস্থাপন করল।", ["Sharp", "Perceptive", "Acute"], ["Vague", "Dull"], "Academic"),
    ("Incongruous", "/ɪnˈkɒŋ.ɡru.əs/", "Adj", "বেমানান, অসঙ্গতিপূর্ণ", "A modern sofa looked incongruous in room.", "ঘরে একটি আধুনিক সোফা বেশ বেমানান দেখাচ্ছিল।", ["Out of place", "Incompatible"], ["Harmonious", "Fitting"], "Architecture"),
    ("Indefatigable", "/ˌɪn.dɪˈfæt.ɪ.ɡə.bəl/", "Adj", "অক্লান্ত, পরিশ্রমে নাছোড়", "An indefatigable worker completed the job.", "এক অক্লান্ত কর্মী কাজটি শেষ করলেন।", ["Tireless", "Untiring", "Unwearied"], ["Lazy", "Tired"], "Spoken"),
    ("Indigent", "/ˈɪn.dɪ.dʒənt/", "Adj", "দরিদ্র, নিঃস্ব বা অভাবগ্রস্ত", "Charity provided food for indigent families.", "দাতব্য সংস্থা অভাবগ্রস্ত পরিবারকে খাবার দিল।", ["Poor", "Destitute", "Needy"], ["Wealthy", "Rich"], "BCS"),
    ("Indolent", "/ˈɪn.də.lənt/", "Adj", "কুঁড়ে, অলস বা নিষ্ক্রিয়", "An indolent youth lay on the grass.", "এক অলস যুবক ঘাসের ওপর শুয়ে রইল।", ["Lazy", "Slothful", "Idle"], ["Energetic", "Industrious"], "BCS"),
    ("Ineffable", "/ɪnˈef.ə.bəl/", "Adj", "অবাচ্য, ভাষায় প্রকাশের অতীত", "She felt an ineffable joy.", "সে ভাষায় প্রকাশের অতীত এক আনন্দ অনুভব করল।", ["Indescribable", "Inexpressible"], ["Definable"], "Literature"),
    ("Inexorable", "/ɪnˈek.sər.ə.bəl/", "Adj", "অপ্রতিরোধ্য, অনমনীয়", "Aging is an inexorable process.", "বার্ধক্য এক অপ্রতিরোধ্য প্রক্রিয়া।", ["Relentless", "Unstoppable", "Unforgiving"], ["Preventable", "Flexible"], "Science"),
    ("Ingenuous", "/ɪnˈdʒen.ju.əs/", "Adj", "সরল, অকপট বা নিষ্কলঙ্ক", "Her ingenuous nature won everyone over.", "তার সরল স্বভাব সবাইকে জয় করে নিল।", ["Naive", "Innocent", "Trusting"], ["Sophisticated", "Sly"], "GRE"),
    ("Inimical", "/ɪˈnɪm.ɪ.ক্যাল/", "Adj", "বিরোধী, ক্ষতিকর বা শত্রুবৎ", "Policies inimical to public interest.", "জনস্বার্থ বিরোধী নীতিসমূহ।", ["Harmful", "Hostile", "Detrimental"], ["Friendly", "Favorable"], "Academic"),
    ("Inscrutable", "/ɪnˈskruː.tə.bəl/", "Adj", "দুর্ভেদ্য, রহস্যময় বা অতল", "His expression was completely inscrutable.", "তার মুখের এক্সপ্রেশন ছিল সম্পূর্ণ দুর্ভেদ্য।", ["Mysterious", "Unfathomable", "Enigmatic"], ["Transparent", "Clear"], "GRE"),
    ("Insidious", "/ɪnˈsɪd.i.əs/", "Adj", "চতুর, ক্ষতিকরভাবে ছড়ানো", "High blood pressure is an insidious disease.", "উচ্চ রক্তচাপ এক ক্ষতিকরভাবে ছড়ানো রোগ।", ["Stealthy", "Subtle", "Treacherous"], ["Overt", "Harmless"], "Medical"),
    ("Insipid", "/ɪnˈsɪp.ɪd/", "Adj", "নীরস, পানসে বা স্বাদহীন", "The soup was bland and insipid.", "সুপটি ছিল নিরামিষ ও পানসে।", ["Tasteless", "Bland", "Dull"], ["Tasty", "Exciting"], "Spoken"),
    ("Insolent", "/ˈɪn.səl.ənt/", "Adj", "উদ্ধত, অশিষ্ট বা বেপরোয়া", "An insolent child talked back to parents.", "এক উদ্ধত সন্তান বাবা-মায়ের সাথে তর্ক করল।", ["Impertinent", "Rude", "Disrespectful"], ["Polite", "Respectful"], "Spoken"),
    ("Intransigent", "/ɪnˈtræn.sɪ.dʒənt/", "Adj", "অনমনীয়, আপসহীন বা কঠোর", "Management remained intransigent on pay.", "ব্যবস্থাপনা বেতন বিষয়ে অনমনীয় রইল।", ["Stubborn", "Uncompromising"], ["Flexible", "Compliant"], "Business"),
    ("Intrepid", "/ɪnˈtrep.ɪd/", "Adj", "নির্ভীক, অকুতোভয়", "An intrepid explorer ventured into cave.", "এক নির্ভীক অভিযাত্রী গুহার গভীরে গেল।", ["Fearless", "Brave", "Dauntless"], ["Cowardly", "Timid"], "IELTS"),
    ("Inundate", "/ˈɪn.ʌn.deɪt/", "Verb", "প্লাবিত করা, বন্যায় ভাসানো", "Letters inundated the director's office.", "চিঠিপত্র পরিচালকের অফিস প্লাবিত করে দিল।", ["Flood", "Overwhelm", "Swamp"], [], "General"),
    ("Invective", "/ɪnˈvek.tɪv/", "Noun", "গালিগালাজ, কটু আক্রমণাত্মক ভাষা", "A torrent of invective poured forth.", "আক্রমণাত্মক কথার বন্যা বয়ে গেল।", ["Abuse", "Vituperation", "Censure"], ["Praise", "Flattery"], "GRE"),

    # 181 - 210
    ("Inveterate", "/ɪnˈvet.ər.ət/", "Adj", "বদ্ধমূল, দীর্ঘদিনের অভ্যাসে পরিণত", "He is an inveterate liar.", "সে এক চরম বদ্ধমূল মিথ্যুক।", ["Habitual", "Ingrained", "Chronic"], [], "Psychology"),
    ("Irascible", "/ɪˈræs.ə.bəl/", "Adj", "একগুঁয়ে, বদমেজাজী বা সহজে ক্রুদ্ধ", "An irascible man shouted at the waiter.", "এক বদমেজাজী লোক ওয়েটারের ওপর চিৎকার করল।", ["Irritable", "Short-tempered", "Quick-tempered"], ["Placid", "Good-natured"], "GRE"),
    ("Jettison", "/ˈdʒet.ɪ.sən/", "Verb", "বর্জন করা, জাহাজ থেকে ফেলে দেওয়া", "We must jettison outdated ideas.", "আমাদের অবশ্যই সেকেলে চিন্তাভাবনা বর্জন করতে হবে।", ["Discard", "Dump", "Abandon"], ["Retain", "Keep"], "General"),
    ("Jocular", "/ˈdʒɒk.jə.lər/", "Adj", "রসিক, তামাশাপূর্ণ বা কৌতুকাশ্রয়ী", "He spoke in a jocular vein.", "সে এক রসিক মেজাজে কথা বলল।", ["Joking", "Humorous", "Playful"], ["Solemn", "Serious"], "Spoken"),
    ("Juxtapose", "/ˌdʒʌk.stəˈpəʊz/", "Verb", "পাশাপাশি স্থাপন করা", "Juxtaposing two pictures showed contrast.", "ছবি দুটো পাশাপাশি রাখা বৈপরীত্য ফুটিয়ে তুলল।", ["Compare", "Place side-by-side"], [], "Art"),
    ("Laconic", "/ləˈkɒn.ɪk/", "Adj", "স্বল্পভাষী, কম কথায় সংক্ষিপ্ত", "His laconic reply left no doubt.", "তার স্বল্পভাষী সংক্ষিপ্ত উত্তর কোনো সন্দেহ রাখেনি।", ["Concise", "Terse", "Brief"], ["Verbose", "Wordy"], "GRE"),
    ("Lament", "/ləˈment/", "Verb", "বিলাপ করা, শোক প্রকাশ করা", "She lamented the loss of her best friend.", "সে তার প্রিয় বন্ধুর হারানোর শোকে বিলাপ করল।", ["Mourn", "Grieve", "Bemoan"], ["Celebrate", "Rejoice"], "Literature"),
    ("Lassitude", "/ˈlæs.ɪ.tʃuːd/", "Noun", "অবসাদ, ক্লান্তি বা অলসতা", "A heavy lunch induced lassitude.", "ভারী দুপুরের খাবার অবসাদ ডেকে আনল।", ["Fatigue", "Lethargy", "Weariness"], ["Vigor", "Energy"], "Medical"),
    ("Laudable", "/ˈlɔː.də.bəl/", "Adj", "প্রশংসনীয়, সাধুবাদযোগ্য", "Her efforts to help were laudable.", "সাহায্য করার জন্য তার প্রচেষ্টা প্রশংসনীয় ছিল।", ["Praiseworthy", "Commendable"], ["Blameworthy"], "Academic"),
    ("Lethargic", "/ləˈθɑː.dʒɪk/", "Adj", "নিস্তেজ, অলস বা শক্তিহীন", "Hot weather made everyone lethargic.", "গরম আবহাওয়া সবাইকে নিস্তেজ করে দিল।", ["Sluggish", "Apathetic", "Listless"], ["Energetic", "Active"], "Spoken"),
    ("Levity", "/ˈlev.ə.ti/", "Noun", "হালকাভাব, অহেতুক চপলতা", "Avoid levity during serious ceremonies.", "গম্ভীর অনুষ্ঠানে চপলতা পরিহার করুন।", ["Frivolity", "Lightness"], ["Gravity", "Seriousness"], "Spoken"),
    ("Loquacious", "/ləˈkweɪ.ʃəs/", "Adj", "বাচাল, বাচাল স্বভাবের", "A loquacious passenger shared entire life story.", "এক বাচাল যাত্রী তার পুরো জীবনের গল্প শোনালো।", ["Talkative", "Voluble", "Garrulous"], ["Taciturn", "Silent"], "BCS"),
    ("Lucid", "/ˈluː.sɪd/", "Adj", "স্পষ্ট, সহজবোধ্য বা প্রাঞ্জল", "The professor gave a lucid explanation.", "অধ্যাপক অত্যন্ত প্রাঞ্জল ব্যাখ্যা দিলেন।", ["Clear", "Coherent", "Intelligible"], ["Confusing", "Obscure"], "Academic"),
    ("Lugubrious", "/ləˈɡuː.bri.əs/", "Adj", "শোকাতুর, করুণ বা চরম বিষণ্ণ", "He wore a lugubrious expression.", "তার মুখে এক করুণ বিষণ্ণ এক্সপ্রেশন ছিল।", ["Mournful", "Gloomy", "Sorrowful"], ["Cheerful", "Joyful"], "Literature"),
    ("Magnanimous", "/mæɡˈnæn.ɪ.məs/", "Adj", "মহানুভব, উদারচেতা", "He was magnanimous toward his defeated opponent.", "পরাজিত বিরোধীর প্রতি সে মহানুভব ছিল।", ["Generous", "Forgiving", "Noble"], ["Petty", "Mean"], "BCS"),
    ("Malevolent", "/məˈlev.əl.ənt/", "Adj", "বিদ্বেষপরায়ণ, ক্ষতিকর মনোভাবাপন্ন", "A malevolent villain plotted revenge.", "এক বিদ্বেষপরায়ণ ভিলেন প্রতিশোধের চক্রান্ত করল।", ["Spiteful", "Malicious", "Hostile"], ["Benevolent", "Kind"], "Literature"),
    ("Malleable", "/ˈmæl.i.ə.bəl/", "Adj", "নমনীয়, সহজে রূপান্তরযোগ্য", "Gold is a highly malleable metal.", "সোনা একটি অত্যন্ত নমনীয় ধাতু।", ["Pliable", "Flexible", "Adaptable"], ["Rigid", "Stiff"], "Science"),
    ("Maverick", "/ˈmæv.ər.ɪk/", "Noun", "স্বতন্ত্র চিন্তার লোক, প্রথাভাঙা ব্যক্তি", "He is a political maverick.", "সে এক প্রথাভাঙা স্বতন্ত্র রাজনৈতিক ব্যক্তিত্ব।", ["Individualist", "Nonconformist", "Rebel"], ["Conformist"], "Politics"),
    ("Mendacious", "/menˈdeɪ.ʃəs/", "Adj", "মিথ্যাচারী, অসত্যবাদিনী", "Mendacious propaganda spread rapidly.", "মিথ্যাচারী অপপ্রচার দ্রুত ছড়িয়ে পড়ল।", ["Untruthful", "Lying", "Deceitful"], ["Truthful", "Honest"], "GRE"),
    ("Mercenary", "/ˈmɜː.sən.ər.i/", "Adj", "অর্থলোভী, অর্থের বিনিময়ে নিয়োজিত", "He was motivated by purely mercenary reasons.", "সে খাঁটি অর্থলোভী উদ্দেশ্যে চালিত হয়েছিল।", ["Money-oriented", "Greedy"], ["Altruistic"], "Business"),
    ("Mercurial", "/mɜːˈkjʊə.ri.əl/", "Adj", "পরিবর্তনশীল, ক্ষণে ক্ষণে মেজাজ বদলানো", "Her mercurial temper made her unpredictable.", "তার ক্ষণে ক্ষণে বদলানো মেজাজ তাকে অনিশ্চিত করত।", ["Volatile", "Capricious", "Fickle"], ["Stable", "Constant"], "GRE"),
    ("Meticulous", "/məˈtɪk.jə.ləs/", "Adj", "খুঁতখুঁতে, অত্যন্ত নিখুঁত ও সতর্ক", "He paid meticulous attention to details.", "সে খুঁটিনাটি বিষয়ে অত্যন্ত নিখুঁত মনোযোগ দিল।", ["Precise", "Painstaking", "Thorough"], ["Careless", "Sloppy"], "IELTS"),
    ("Mitigate", "/ˈmɪt.ɪ.ɡeɪt/", "Verb", "উপশম করা, তীব্রতা কমানো", "Tree planting helps mitigate climate change.", "গাছ লাগানো জলবায়ু পরিবর্তন উপশম করে।", ["Lessen", "Ease", "Alleviate"], ["Aggravate", "Intensify"], "IELTS"),
    ("Mollify", "/ˈmɒl.ɪ.faɪ/", "Verb", "শান্ত করা, নরম করা", "She tried to mollify her angry parent.", "সে তার ক্রুদ্ধ অভিভাবককে শান্ত করার চেষ্টা করল।", ["Pacify", "Appease", "Soothe"], ["Enrage", "Provoke"], "GRE"),
    ("Mundane", "/mʌnˈdeɪn/", "Adj", "সাধারণ, জাগতিক বা একঘেয়ে", "He handled mundane household chores.", "সে সাধারণ জাগতিক ঘরের কাজ সামলালো।", ["Ordinary", "Everyday", "Boring"], ["Extraordinary", "Exciting"], "Spoken"),
    ("Munificent", "/mjuːˈnɪf.ɪ.sənt/", "Adj", "উদার, অতি দানশীল", "A munificent donor gave millions.", "এক অতি দানশীল দাতা লক্ষ লক্ষ টাকা দান করলেন।", ["Generous", "Bountiful", "Lavish"], ["Miserly", "Stingy"], "GRE"),
    ("Myopic", "/maɪˈɒp.ɪk/", "Adj", "ক্ষীণদৃষ্টি, দূরদর্শিতাহীন", "Short-term planning is a myopic strategy.", "স্বল্পমেয়াদী পরিকল্পনা এক দূরদর্শিতাহীন কৌশল।", ["Short-sighted", "Unforeseeing"], ["Far-sighted", "Visionary"], "Management"),
    ("Nadir", "/ˈneɪ.dɪər/", "Noun", "সর্বনিম্ন বিন্দু, চরম পতন", "His career reached its nadir last year.", "গত বছর তার ক্যারিয়ার চরম পতনে পৌঁছেছিল।", ["Lowest point", "Bottom"], ["Zenith", "Peak"], "BCS"),
    ("Nefarious", "/nəˈfeə.ri.əs/", "Adj", "জঘন্য, অপকর্মপরায়ণ বা কুখ্যাত", "The gang engaged in nefarious activities.", "গ্যাংটি জঘন্য অপকর্মে লিপ্ত ছিল।", ["Wicked", "Evil", "Villainous"], ["Noble", "Virtuous"], "Legal"),
    ("Neophyte", "/ˈniː.ə.faɪt/", "Noun", "নবীন, শিক্ষানবিশ বা আনাড়ি", "He is a neophyte in computer coding.", "কম্পিউটার কোডিংয়ে সে একজন নবীন শিক্ষানবিশ।", ["Novice", "Beginner", "Tyro"], ["Veteran", "Expert"], "GRE"),

    # 211 - 240
    ("Nostalgia", "/nɒsˈtæl.dʒə/", "Noun", "অতীতের প্রতি আকুলতা, গৃহকাতরতা", "Old photos evoked a sense of nostalgia.", "পুরনো ছবিগুলো অতীতের ব্যাকুলতা জাগিয়ে দিল।", ["Reminiscence", "Longing"], [], "Spoken"),
    ("Noxious", "/ˈnɒk.ʃəs/", "Adj", "ক্ষতিকর, বিষাক্ত বা বিষময়", "Noxious fumes filled the basement.", "বিষাক্ত ধোঁয়া সেলারটি ভরিয়ে দিল।", ["Harmful", "Toxic", "Poisonous"], ["Harmless", "Wholesome"], "Medical"),
    ("Nuance", "/ˈnjuː.ɑːns/", "Noun", "সূক্ষ্ম পার্থক্য, তারতম্য", "He understood every nuance of meaning.", "সে অর্থের প্রতিটি সূক্ষ্ম পার্থক্য অনুধাবন করল।", ["Subtlety", "Shade of meaning"], [], "IELTS"),
    ("Obdurate", "/ˈɒb.dʒər.ət/", "Adj", "একগুঁয়ে, পাষাণ হৃদয় বা অবাধ্য", "He remained obdurate despite tears.", "কান্নাকাটি সত্ত্বেও সে একগুঁয়ে পাষাণই রইল।", ["Stubborn", "Unyielding", "Callous"], ["Compliant", "Flexible"], "GRE"),
    ("Obfuscate", "/ˈɒb.fʌs.keɪt/", "Verb", "অস্পষ্ট করা, বিভ্রান্ত করা", "Don't obfuscate the facts with jargon.", "পারিভাষিক শব্দ দিয়ে তথ্য অস্পষ্ট করবেন না।", ["Confuse", "Obscure", "Muddle"], ["Clarify", "Simplify"], "Academic"),
    ("Oblivious", "/əˈblɪv.i.əs/", "Adj", "অসচেতন, বেখবর বা ভোলাভালা", "He was oblivious to danger around him.", "সে চারপাশের বিপদ সম্পর্কে অসচেতন ছিল।", ["Unaware", "Unmindful", "Heedless"], ["Aware", "Mindful"], "Spoken"),
    ("Obsequious", "/əbˈsiː.kwi.əs/", "Adj", "চাটুকার, দাসবৎ অনুগত", "He bowed in an obsequious manner.", "সে তোষামোদি ভঙ্গিতে মাথা নোয়াল।", ["Servile", "Fawning", "Subservient"], ["Domineering", "Assertive"], "GRE"),
    ("Obsolete", "/ˈɒb.sə.liːt/", "Adj", "সেকেলে, অপ্রচলিত", "Floppy disks are completely obsolete now.", "ফ্লপি ডিস্ক এখন সম্পূর্ণ অপ্রচলিত।", ["Outdated", "Archaic", "Defunct"], ["Modern", "Current"], "Technology"),
    ("Obstinate", "/ˈɒb.stɪ.nət/", "Adj", "একগুঁয়ে, অবাধ্য বা নাছোড়বান্দা", "An obstinate child refused to move.", "এক একগুঁয়ে শিশু নড়তে অস্বীকার করল।", ["Stubborn", "Headstrong", "Mulish"], ["Flexible", "Yielding"], "BCS"),
    ("Obviate", "/ˈɒb.vi.eɪt/", "Verb", "দূর করা, নিবারণ করা", "Vaccines obviate the need for hospitalization.", "ভ্যাকসিন হাসপাতালে ভর্তির প্রয়োজন দূর করে।", ["Prevent", "Preclude", "Eliminate"], [], "Medical"),
    ("Onerous", "/ˈɒn.ər.əs/", "Adj", "গুরুভার, কষ্টসাধ্য বা দায়িত্বপূর্ণ", "He carried out an onerous duty.", "সে এক গুরুভার দায়িত্ব পালন করল।", ["Burdensome", "Heavy", "Demanding"], ["Light", "Easy"], "IELTS"),
    ("Opacity", "/əʊˈpæs.ə.ti/", "Noun", "অস্বচ্ছতা, অস্পষ্টতা", "Opacity of the glass hid inside view.", "কাঁচের অস্বচ্ছতা ভিতরের দৃশ্য ঢেকে দিল।", ["Murkiness", "Unclearness"], ["Clarity", "Transparency"], "Science"),
    ("Opulent", "/ˈɒp.jə.lənt/", "Adj", "ঐশ্বর্যশালী, জাঁকজমকপূর্ণ", "They lived in an opulent mansion.", "তারা এক জাঁকজমকপূর্ণ প্রাসাদে থাকত।", ["Luxurious", "Grand", "Wealthy"], ["Poor", "Modest"], "Literature"),
    ("Ostentatious", "/ˌɒs.tenˈteɪ.ʃəs/", "Adj", "আড়ম্বরপূর্ণ, লোকদেখানো", "He wore ostentatious gold rings.", "সে লোকদেখানো সোনার আংটি পরেছিল।", ["Showy", "Pretentious", "Flamboyant"], ["Modest", "Unobtrusive"], "GRE"),
    ("Pacify", "/ˈpæs.ɪ.faɪ/", "Verb", "শান্ত করা, শমন করা", "She pacified the crying infant.", "সে কাঁদতে থাকা শিশুটিকে শান্ত করল।", ["Soothe", "Calm", "Appease"], ["Enrage", "Provoke"], "Spoken"),
    ("Palpable", "/ˈpæl.pə.bəl/", "Adj", "স্পষ্ট অনুভবযোগ্য, প্রত্যক্ষ", "The tension in the room was palpable.", "ঘরের মধ্যকার উত্তেজনা স্পষ্ট অনুভবযোগ্য ছিল।", ["Tangible", "Noticeable", "Obvious"], ["Imperceptible", "Subtle"], "Literature"),
    ("Panacea", "/ˌpæn.əˈsiː.ə/", "Noun", "সর্বরোগহর ওষুধ, সর্বব্যাধির প্রতিষেধক", "There is no easy panacea for poverty.", "দারিদ্র্যের কোনো সহজ সর্বরোগহর প্রতিকার নেই।", ["Cure-all", "Universal remedy"], [], "Medical"),
    ("Paradigm", "/ˈpær.ə.daɪm/", "Noun", "আদর্শ উদাহরণ, নজির বা মডেল", "AI creates a new paradigm in education.", "এআই শিক্ষায় এক নতুন মডেল সৃষ্টি করছে।", ["Model", "Pattern", "Archetype"], [], "Academic"),
    ("Pariah", "/pəˈraɪ.ə/", "Noun", "একঘরে লোক, সমাজচ্যুত ব্যক্তি", "His treason made him a social pariah.", "তার বিশ্বাসঘাতকতা তাকে একঘরে করে দিল।", ["Outcast", "Rejection"], [], "Sociology"),
    ("Paucity", "/ˈpɔː.sə.ti/", "Noun", "স্বল্পতা, অভাব বা অপ্রতুলতা", "There is a paucity of reliable evidence.", "নির্ভরযোগ্য সাক্ষ্যের চরম অপ্রতুলতা রয়েছে।", ["Scarcity", "Shortage", "Lack"], ["Abundance", "Surplus"], "IELTS"),
    ("Pedantic", "/pɪˈdæn.tɪk/", "Adj", "পণ্ডিতাভিমানী, অহেতুক খুঁটিনাটি অনুরাগী", "Avoid being too pedantic with rules.", "নিয়মের ব্যাপারে অতিরিক্ত পণ্ডিতাভিমানী হওয়া এড়ান।", ["Over-scrupulous", "Fussy", "Picky"], [], "Academic"),
    ("Pedestrian", "/pəˈdes.tri.ən/", "Adj", "সাধারণ, নিরুত্তাপ বা গতানুগতিক", "His presentation was somewhat pedestrian.", "তার প্রেজেন্টেশনটি কিছুটা সাধারণ ছিল।", ["Ordinary", "Dull", "Boring"], ["Exciting", "Extraordinary"], "GRE"),
    ("Penchant", "/ˈpɒ̃.ʃɒ̃/", "Noun", "বিশেষ প্রবৃত্তি, গভীর আসক্তি", "She has a penchant for antique art.", "প্রাচীন শিল্পের প্রতি তার এক বিশেষ আসক্তি রয়েছে।", ["Liking", "Inclination", "Fondness"], ["Aversion", "Dislike"], "IELTS"),
    ("Perfidious", "/pəˈfɪd.i.əs/", "Adj", "বিশ্বাসঘাতক, অবিশ্বস্ত", "A perfidious friend betrayed his secrets.", "এক বিশ্বাসঘাতক বন্ধু তার গোপন কথা ফাঁস করল।", ["Treacherous", "Disloyal", "Faithless"], ["Loyal", "Faithful"], "Literature"),
    ("Perfunctory", "/pəˈfʌŋk.tər.i/", "Adj", "দায়সারা, যন্ত্রের মতো বা বেখেয়ালী", "He gave a perfunctory nod.", "সে এক দায়সারা মাথা নাড়ল।", ["Cursory", "Casual", "Careless"], ["Thorough", "Careful"], "BCS"),
    ("Pervasive", "/pəˈveɪ.sɪv/", "Adj", "সর্বব্যাপী, ব্যাপকভাবে বিস্তৃত", "Corruption was pervasive in system.", "ব্যবস্থায় দুর্নীতি ছিল সর্বব্যাপী বিস্তৃত।", ["Widespread", "Omnipresent", "Prevalent"], ["Rare", "Limited"], "IELTS"),
    ("Philanthropy", "/fɪˈlæn.θrə.pi/", "Noun", "জনকল্যাণ, দানশীলতা", "He dedicated his fortune to philanthropy.", "সে তার সম্পদ জনকল্যাণে উৎসর্গ করল।", ["Charity", "Altruism", "Benevolence"], [], "Social"),
    ("Phlegmatic", "/fleɡˈmæt.ɪk/", "Adj", "ধীরস্থির, সহজে উত্তেজিত হয় না এমন", "A phlegmatic disposition kept him calm.", "তার এক ধীরস্থির মেজাজ তাকে শান্ত রাখল।", ["Calm", "Unemotional", "Cool"], ["Excitable", "Emotional"], "Psychology"),
    ("Plausible", "/ˈplɔː.zə.bəl/", "Adj", "বিশ্বাসযোগ্য, সম্ভাব্য", "Her explanation sounded highly plausible.", "তার ব্যাখ্যাটি অত্যন্ত বিশ্বাসযোগ্য মনে হলো।", ["Credible", "Believable", "Reasonable"], ["Implausible", "Unbelievable"], "IELTS"),
    ("Plethora", "/ˈpleθ.ər.ə/", "Noun", "আধিক্য, প্রাচুর্য বা আতিশয্য", "A plethora of options confused the buyer.", "বিকল্পের প্রাচুর্য ক্রেতাকে বিভ্রান্ত করল।", ["Abundance", "Excess", "Surplus"], ["Paucity", "Scarcity"], "Academic"),

    # 241 - 270
    ("Pragmatic", "/præɡˈmæt.ɪk/", "Adj", "বাস্তবধর্মী, বাস্তবমুখী", "We need a pragmatic approach to fix it.", "এটি ঠিক করতে আমাদের বাস্তবমুখী পন্থা দরকার।", ["Practical", "Realistic", "Sensible"], ["Idealistic", "Impractical"], "Spoken"),
    ("Precarious", "/prɪˈkeə.ri.əs/", "Adj", "ঝুঁকিপূর্ণ, অনিশ্চিত বা বিপদসঙ্কুল", "He earned a precarious living.", "সে এক ঝুঁকিপূর্ণ জীবিকা নির্বাহ করত।", ["Uncertain", "Risky", "Hazardous"], ["Safe", "Secure"], "IELTS"),
    ("Precipitous", "/prɪˈsɪp.ɪ.təs/", "Adj", "খাড়া, অতি দ্রুত পতনশীল", "A precipitous drop in sales surprised all.", "বিক্রির অতি দ্রুত পতন সবাইকে অবাক করল।", ["Steep", "Abrupt", "Sudden"], ["Gradual"], "Business"),
    ("Precocious", "/prɪˈkəʊ.ʃəs/", "Adj", "অকালপক্ব, বয়সের তুলনায় অগ্রগামী", "A precocious child played chess at four.", "চার বছর বয়সে এক অকালপক্ব শিশু দাবা খেলত।", ["Advanced", "Gifted", "Mature"], ["Backward"], "Psychology"),
    ("Predilection", "/ˌpriː.dɪˈlek.ʃən/", "Noun", "পক্ষপাত, বিশেষ অনুরাগ", "She has a predilection for spicy food.", "ঝাল খাবারের প্রতি তার এক বিশেষ অনুরাগ আছে।", ["Preference", "Partiality", "Liking"], ["Dislike", "Aversion"], "GRE"),
    ("Presumptuous", "/prɪˈzʌmp.tʃu.əs/", "Adj", "আস্পর্ধাপূর্ণ, সীমালঙ্ঘনকারী", "It would be presumptuous to judge him.", "তাকে বিচার করা এক আস্পর্ধাপূর্ণ কাজ হবে।", ["Overconfident", "Arrogant", "Audacious"], ["Modest", "Humble"], "GRE"),
    ("Prodigal", "/ˈprɒd.ɪ.ɡəl/", "Adj", "অমিতব্যয়ী, অপচয়ী", "The prodigal son squandered his inheritance.", "অপচয়ী ছেলেটি তার উত্তরাধিকার উড়িয়ে দিল।", ["Wasteful", "Extravagant", "Spendthrift"], ["Thrifty", "Frugal"], "Literature"),
    ("Prodigious", "/prəˈdɪdʒ.əs/", "Adj", "বিপুল, প্রকাণ্ড বা বিস্ময়কর", "He has a prodigious memory for facts.", "তথ্যের ক্ষেত্রে তার এক বিস্ময়কর স্মৃতিশক্তি রয়েছে।", ["Enormous", "Huge", "Immense"], ["Small", "Tiny"], "Academic"),
    ("Profound", "/prəˈfaʊnd/", "Adj", "গভীর, সুদূরপ্রসারী বা অসামান্য", "His words had a profound effect.", "তার কথাগুলো এক গভীর প্রভাব ফেলেছিল।", ["Deep", "Insightful", "Intense"], ["Superficial", "Shallow"], "IELTS"),
    ("Profligate", "/ˈprɒf.lɪ.ɡət/", "Adj", "উচ্ছৃঙ্খল, অপচয়ী ও লম্পট", "Profligate spending led to bankruptcy.", "অপচয়ী খরচ দেউলিয়া হওয়ার কারণ হলো।", ["Wasteful", "Extravagant", "Dissolute"], ["Thrifty", "Economical"], "GRE"),
    ("Profuse", "/prəˈfjuːs/", "Adj", "বিপুল, প্রচুর বা অঢেল", "He offered profuse apologies.", "সে অঢেল ক্ষমা প্রার্থনা পেশ করল।", ["Abundant", "Copious", "Extravagant"], ["Sparse", "Meager"], "Spoken"),
    ("Prolific", "/prəˈlɪf.ɪk/", "Adj", "প্রচুর উৎপাদনশীল, উর্বর", "A prolific writer published twenty books.", "এক প্রচুর উৎপাদনশীল লেখক ২০টি বই প্রকাশ করলেন।", ["Productive", "Fertile", "Fruitful"], ["Unproductive", "Barren"], "Academic"),
    ("Propensity", "/prəˈpen.sə.ti/", "Noun", "স্বাভাবিক প্রবণতা, ঝোঁক", "He has a propensity for exaggeration.", "বাড়িয়ে বলার দিকে তার এক স্বাভাবিক প্রবণতা রয়েছে।", ["Tendency", "Inclination", "Leaning"], [], "Psychology"),
    ("Prosaic", "/prəˈzeɪ.ɪk/", "Adj", "নীরস, গদ্যময় বা গতানুগতিক", "A prosaic description bored readers.", "এক গতানুগতিক বিবরণ পাঠকদের বিরক্ত করল।", ["Dull", "Unimaginative", "Ordinary"], ["Poetic", "Imaginative"], "GRE"),
    ("Pugnacious", "/pʌɡˈneɪ.ʃəs/", "Adj", "ঝগড়াটে, যুদ্ধংদেহী", "His pugnacious nature started fights.", "তার ঝগড়াটে স্বভাব মারামারি বাঁধাত।", ["Combative", "Aggressive", "Belligerent"], ["Peaceful", "Friendly"], "GRE"),
    ("Punctilious", "/pʌŋkˈtɪl.i.əs/", "Adj", "সুনির্দিষ্ট, খুঁটিনাটিতে যত্নশীল", "He was punctilious about punctuality.", "সময়নিষ্ঠার বিষয়ে সে অত্যন্ত খুঁটিনাটি সচেতন ছিল।", ["Meticulous", "Scrupulous", "Conscientious"], ["Careless", "Sloppy"], "GRE"),
    ("Quagmire", "/ˈkwæɡ.maɪər/", "Noun", "জটিল সংকট, দলদল", "The country was caught in a political quagmire.", "দেশটি এক রাজনৈতিক জটিল সংকটে আটকে ছিল।", ["Predicament", "Morass", "Bog"], [], "Politics"),
    ("Quell", "/kwel/", "Verb", "দমন করা, শান্ত করা", "Police acted quickly to quell the riot.", "পুলিশ দাঙ্গা দমন করতে দ্রুত কাজ করল।", ["Suppress", "Subdue", "Calm"], ["Provoke", "Incite"], "Legal"),
    ("Ququerulous", "/ˈkwer.ə.ləs/", "Adj", "ঘ্যানঘ্যানে, সর্বদাই অভিযোগকারী", "A querulous customer complained about food.", "এক ঘ্যানঘ্যানে খদ্দের খাবার নিয়ে অভিযোগ করল।", ["Complaining", "Peevish", "Petulant"], ["Content", "Cheerfully"], "GRE"),
    ("Quixotic", "/kwɪkˈsɒt.ɪk/", "Adj", "কল্পনাবিহারী, অবাস্তব আদর্শবাদী", "His scheme was noble but quixotic.", "তার পরিকল্পনাটি মহৎ কিন্তু অবাস্তব ছিল।", ["Idealistic", "Impractical", "Unrealistic"], ["Pragmatic", "Practical"], "BCS"),

    # 271 - 300
    ("Rancor", "/ˈræŋ.kər/", "Noun", "তীব্র বিদ্বেষ, দীর্ঘদিনের রোষ", "They parted without any rancor.", "কোনো বিষোদগার ছাড়াই তারা আলাদা হলো।", ["Bitter hostility", "Enmity", "Hatred"], ["Goodwill", "Friendship"], "GRE"),
    ("Rapacious", "/rəˈpeɪ.ʃəs/", "Adj", "লোভী, লুণ্ঠনকারী বা শিকারী", "Rapacious landlords raised rents sharply.", "লোভী বাড়িওয়ালারা ভাড়া দ্রুত বাড়িয়ে দিল।", ["Greedy", "Grasping", "Voracious"], ["Generous", "Content"], "Literature"),
    ("Recant", "/rɪˈkænt/", "Verb", "প্রকাশ্যে মতামত প্রত্যাহার করা", "The witness recanted his testimony.", "সাক্ষী তার সাক্ষ্য প্রকাশ্যে প্রত্যাহার করল।", ["Retract", "Withdraw", "Renounce"], ["Affirm", "Reassert"], "Legal"),
    ("Recluse", "/rɪˈkluːs/", "Noun", "নির্জনবাসী, সমাজবিচ্ছিন্ন ব্যক্তি", "He lived as a recluse in cabin.", "সে কুঁড়েঘরে এক নির্জনবাসী হিসেবে বাস করত।", ["Hermit", "Loner", "Solitary"], [], "Literature"),
    ("Recondite", "/ˈrek.ən.daɪt/", "Adj", "গূঢ়, দুর্বোধ্য বা জটিল", "He studied recondite ancient texts.", "সে গূঢ় প্রাচীন মূলপাঠসমূহ অধ্যায়ন করল।", ["Abstruse", "Obscure", "Deep"], ["Clear", "Simple"], "GRE"),
    ("Redundant", "/rɪˈdʌn.dənt/", "Adj", "অতিরিক্ত, অনাবশ্যক ছাঁটাইযোগ্য", "Remove all redundant words from draft.", "ড্রাফট থেকে অনাবশ্যক শব্দগুলো কেটে দিন।", ["Unnecessary", "Superfluous", "Excess"], ["Essential", "Necessary"], "Spoken"),
    ("Refute", "/rɪˈfjuːt/", "Verb", "খণ্ডন করা, ভুল প্রমাণ করা", "The attorney refuted allegations.", "আইনজীবী অভিযোগসমূহ খণ্ডন করলেন।", ["Disprove", "Rebut", "Confute"], ["Prove", "Confirm"], "Academic"),
    ("Relinquish", "/rɪˈlɪŋ.kwɪʃ/", "Verb", "বর্জন করা, ছেড়ে দেওয়া বা ত্যাগ করা", "He relinquished command of ship.", "সে জাহাজের দায়িত্ব ছেড়ে দিল।", ["Surrender", "Yield", "Abandon"], ["Retain", "Keep"], "Legal"),
    ("Remorse", "/rɪˈmɔːs/", "Noun", "পাপবোধ, গভীর অনুশোচনা", "He felt deep remorse for his crime.", "সে তার অপরাধের জন্য গভীর অনুশোচনা অনুভব করল।", ["Regret", "Contrition", "Guilt"], [], "Spoken"),
    ("Renounce", "/rɪˈnaʊns/", "Verb", "আনুষ্ঠানিকভাবে ত্যাগ করা", "He renounced his claim to throne.", "সে সিংহাসনের দাবি আনুষ্ঠানিকভাবে ত্যাগ করল।", ["Relinquish", "Abandon", "Reject"], ["Claim", "Assert"], "History"),
    ("Replete", "/rɪˈpliːt/", "Adj", "পরিপূর্ণ, কানায় কানায় ভরা", "The book is replete with pictures.", "বইটি ছবিতে কানায় কানায় পরিপূর্ণ।", ["Full", "Abounding", "Sated"], ["Empty", "Lacking"], "Literature"),
    ("Reprehensible", "/ˌrep.rɪˈhen.sə.bəl/", "Adj", "গর্হিত, চরম নিন্দনীয়", "His behavior was utterly reprehensible.", "তার আচরণ ছিল চরম গর্হিত ও নিন্দনীয়।", ["Blameworthy", "Deplorable", "Censurable"], ["Praiseworthy", "Noble"], "BCS"),
    ("Resilient", "/rɪˈzɪl.jənt/", "Adj", "ঘুরে দাঁড়াতে সক্ষম, স্থিতিস্থাপক", "The business proved resilient during crisis.", "সংকটের সময়ে ব্যবসাটি ঘুরে দাঁড়াতে সক্ষম হলো।", ["Tough", "Adaptable", "Flexible"], ["Fragile", "Vulnerable"], "Spoken"),
    ("Reticent", "/ˈret.ɪ.sənt/", "Adj", "স্বল্পভাষী, চুপচাপ বা সংকোচবোধক", "She was reticent about her personal life.", "তার ব্যক্তিগত জীবন নিয়ে সে নীরব থাকত।", ["Reserved", "Quiet", "Secretive"], ["Talkative", "Open"], "Spoken"),
    ("Revere", "/rɪˈvɪər/", "Verb", "গভীর শ্রদ্ধা করা, মান্য করা", "Citizens revere freedom fighters.", "নাগরিকরা মুক্তিযোদ্ধাদের পরম শ্রদ্ধায় স্মরণ করে।", ["Venerate", "Respect", "Honor"], ["Despise", "Scorn"], "BCS"),
    ("Sacrosanct", "/ˈsæk.rəʊ.sæŋkt/", "Adj", "পবিত্র, অলঙ্ঘনীয়", "Freedom of speech is sacrosanct.", "বাকস্বাধীনতা অলঙ্ঘনীয়।", ["Sacred", "Inviolable", "Hallowed"], [], "Politics"),
    ("Sagacious", "/səˈɡeɪ.ʃəs/", "Adj", "বিচক্ষণ, প্রজ্ঞাবান বা দূরদর্শী", "A sagacious advisor guided the leader.", "এক প্রজ্ঞাবান উপদেষ্টা নেতাকে দিকনির্দেশনা দিলেন।", ["Wise", "Shrewd", "Perceptive"], ["Foolish", "Foolhardy"], "BCS"),
    ("Salient", "/ˈseɪ.li.ənt/", "Adj", "প্রধান, লক্ষণীয় বা মূল", "He highlighted the salient points.", "সে মূল পয়েন্টগুলো ফুটিয়ে তুলল।", ["Prominent", "Key", "Main"], ["Minor", "Inconspicuous"], "Academic"),
    ("Salubrious", "/səˈluː.bri.əs/", "Adj", "স্বাস্থ্যকর, পুষ্টিকর", "Mountain air is salubrious.", "পাহাড়ের হাওয়া স্বাস্থ্যের জন্য অনুকূল।", ["Healthy", "Wholesome", "Beneficial"], ["Unhealthy", "Noxious"], "Medical"),
    ("Sanguine", "/ˈsæŋ.ɡwɪn/", "Adj", "আশাবাদী, প্রফুল্ল বা সানন্দ", "He remains sanguine about future.", "সে ভবিষ্যৎ নিয়ে আশাবাদী রয়েছে।", ["Optimistic", "Hopeful", "Confident"], ["Pessimistic", "Gloomy"], "GRE"),
    ("Scrupulous", "/ˈskruː.pjə.ləs/", "Adj", "সৎ, বিবেকবান ও অত্যন্ত নিখুঁত", "She was scrupulous in financial matters.", "অর্থনৈতিক বিষয়ে সে অত্যন্ত বিবেকবান ছিল।", ["Meticulous", "Honest", "Conscientious"], ["Careless", "Dishonest"], "Academic"),
    ("Serendipity", "/ˌser.ənˈdɪp.ə.ti/", "Noun", "আকস্মিক সৌভাগ্যপ্রাপ্তি, আনন্দের কাকতালীয় ঘটনা", "Meeting her was pure serendipity.", "তার সাথে সাক্ষাৎ হওয়া এক আনন্দের কাকতালীয় ঘটনা ছিল।", ["Chance luck", "Fluke"], [], "Literature"),
    ("Solitude", "/ˈsɒl.ɪ.tʃuːd/", "Noun", "নির্জনতা, একাকী নিঃসঙ্গতা", "He enjoyed the solitude of woods.", "সে বনের নির্জনতা উপভোগ করল।", ["Seclusion", "Loneliness", "Isolation"], ["Crowd", "Company"], "Literature"),
    ("Spurious", "/ˈspjʊə.ri.əs/", "Adj", "নকল, কৃত্রিম বা ভুয়া", "Spurious claims were easily debunked.", "ভুয়া দাবিগুলো সহজেই খণ্ডন করা গেল।", ["Fake", "False", "Counterfeit"], ["Genuine", "Authentic"], "GRE"),
    ("Stoic", "/ˈstəʊ.ɪk/", "Adj", "সুখ-দুঃখে অবিচল, সহনশীল", "He remained stoic during tragedy.", "ট্র্যাজেডির সময় সে অবিচল রইল।", ["Unemotional", "Patient", "Resigned"], ["Emotional", "Excitable"], "Philosophy"),
    ("Substantiate", "/səbˈstæn.ʃi.eɪt/", "Verb", "প্রমাণ দিয়ে সাব্যস্ত করা", "You must substantiate your claims.", "আপনাকে অবশ্যই দাবিসমূহ প্রমাণ করতে হবে।", ["Verify", "Validate", "Confirm"], ["Disprove", "Refute"], "IELTS"),
    ("Superfluous", "/suːˈpɜː.flu.əs/", "Adj", "প্রয়োজনাতিরিক্ত, বাড়তি", "Cut out superfluous text.", "প্রয়োজনাতিরিক্ত পাঠ্য কেটে দিন।", ["Redundant", "Excessive", "Extra"], ["Essential", "Necessary"], "BCS"),
    ("Sycophant", "/ˈsɪk.ə.fænt/", "Noun", "চাটুকার, তোষামোদকারী", "The king was surrounded by sycophants.", "রাজা চাটুকারদের দিয়ে পরিবেষ্টিত ছিলেন।", ["Flatterer", "Toady", "Fawner"], [], "BCS"),
    ("Taciturn", "/ˈtæs.ɪ.tɜːn/", "Adj", "স্বল্পভাষী, চুপচাপ স্বভাবের", "His father was a taciturn man.", "তার বাবা ছিলেন এক স্বল্পভাষী ব্যক্তি।", ["Reserved", "Quiet", "Untalkative"], ["Garrulous", "Loquacious"], "GRE"),
    ("Tenacious", "/təˈneɪ.ʃəs/", "Adj", "অদম্য, নাছোড়বান্দা বা সংকল্পবদ্ধ", "A tenacious advocate fought for justice.", "এক অদম্য আইনজীবী ন্যায়ের জন্য লড়ে গেলেন।", ["Persistent", "Determined", "Dogged"], ["Yielding", "Weak"], "Spoken")
]

# Filter batch2_candidates against existing_words
selected_300 = []
seen = set()

for item in batch2_candidates:
    w = item[0].strip()
    k = w.lower()
    if k not in existing_words and k not in seen:
        seen.add(k)
        selected_300.append(item)

print(f"Candidates gathered: {len(batch2_candidates)}")
print(f"Filtered unique words ready: {len(selected_300)}")

