# coding=utf-8
import json

data = json.load(open("app/src/main/assets/dictionary_1000.json"))
existing = {x["word"].strip().lower() for x in data}

# 70 distinct advanced GRE / IELTS academic words
raw_entries = [
    ("Acclimatization", "Noun", "/əˌklaɪ.mə.taɪˈzeɪ.ʃən/ (অ্যাক্লাইমেটাইজেশন)", "জলবায়ু সহনশীলতা, নতুন পরিবেশ বা তাপমাত্রায় নিজেকে মানিয়ে নেওয়ার প্রক্রিয়া", ["Adaptation", "Adjustment", "Habituation"], ["Incompatibility"], "High altitude acclimatization is essential before climbing Mount Everest.", "মাউন্ট এভারেস্টে ওঠার আগে উচ্চতর উচ্চতার জলবায়ু সহনশীলতা অত্যন্ত প্রয়োজনীয়।"),
    ("Adjudication", "Noun", "/əˌdʒuː.dɪˈkeɪ.ʃən/ (অ্যাডজুডিকেশন)", "আইনি নিষ্পত্তি বা রায় প্রদান, বিবাদের আইনি সিদ্ধান্ত", ["Judgment", "Arbitration", "Settlement", "Ruling"], ["Dispute", "Litigation"], "The judge's formal adjudication settled the longstanding land dispute.", "বিচারকের আনুষ্ঠানিক আইনি নিষ্পত্তি বা রায় প্রদান দীর্ঘদিনের জমি বিবাদের অবসান ঘটিয়েছিল।"),
    ("Adumbrate", "Verb", "/ˈæd.əm.breɪt/ (অ্যাডামব্রেট)", "আভাস দেওয়া, অস্পষ্ট ধারণা বা পূর্বসূচনা প্রকাশ করা", ["Foreshadow", "Outline", "Prefigure", "Intimate"], ["Clarify", "Detail", "Explicate"], "The outline adumbrates the main themes of the upcoming research report.", "রূপরেখাটি আসন্ন গবেষণা প্রতিবেদনের মূল বিষয়গুলোর আভাস দেওয়া পূরণ করে।"),
    ("Amalgamation", "Noun", "/əˌmæl.ɡəˈmeɪ.ʃən/ (অ্যামালগামেশন)", "একত্রীকরণ বা সংমিশ্রণ, বিভিন্ন প্রতিষ্ঠানের এক সংস্থায় রূপান্তর", ["Merger", "Union", "Combination", "Consolidation"], ["Separation", "Division", "Splintering"], "The amalgamation of the two banks created the largest financial group in the country.", "দুটি ব্যাংকের একত্রীকরণ বা সংমিশ্রণ দেশের বৃহত্তম আর্থিক গোষ্ঠী তৈরি করেছিল।"),
    ("Anachronism", "Noun", "/əˈnæk.rə.nɪz.əm/ (অ্যানাক্রোনিজম)", "কালবৈষম্য, ঐতিহাসিক যুগের সাথে অনানুপাতিক বা বেমানান উপাদান", ["Misplacement", "Chronological error", "Incongruity"], ["Timeliness", "Historical accuracy"], "A smartphone in a movie set in the 1800s is a funny anachronism.", "১৮০০ সালের প্রেক্ষাপটে তৈরি চলচ্চিত্রে একটি স্মার্টফোন একটি মজার কালবৈষম্য।"),
    ("Anaphora", "Noun", "/əˈnæf.ər.ə/ (অ্যানাফোরা)", "অনুপাস অলঙ্কার, বাক্যের শুরুতে একই শব্দের শৈল্পিক পুনঃপ্রয়োগ", ["Repetition", "Rhetorical figure"], ["Variation"], "The speech used anaphora to emphasize the urgency of climate action.", "বক্তৃতাটিতে জলবায়ু পদক্ষেপের জরুরি প্রয়োগের ওপর জোর দিতে অনুপাস অলঙ্কার ব্যবহার করা হয়েছিল।"),
    ("Apothegm", "Noun", "/ˈæp.ə.θem/ (অ্যাপোথেম)", "সারসংক্ষেপ প্রবচন, সংক্ষিপ্ত বিজ্ঞ উপদেশপূর্ণ বাক্য", ["Aphorism", "Maxim", "Adage", "Motto"], ["Nonsense", "Absurdity"], "The old coach shared a wise apothegm about perseverance with the team.", "প্রবীণ কোচ দলের সাথে অধ্যবসায় নিয়ে একটি প্রজ্ঞাপূর্ণ প্রবচন শেয়ার করেছেন।"),
    ("Appellation", "Noun", "/ˌæp.əˈleɪ.ʃən/ (অ্যাপেলেশন)", "উপাধি বা উপনাম, কোনো পদ বা স্থানকে দেওয়া আনুষ্ঠানিক নাম", ["Title", "Name", "Designation", "Epithet"], ["Anonymity"], "He earned the noble appellation of 'The Peacemaker' for his diplomacy.", "তিনি তার কূটনীতির জন্য 'শান্তিদূত' নামের নোবেল উপাধি বা উপনাম অর্জন করেছিলেন।"),
    ("Archipelagic", "Adjective", "/ˌɑː.kɪ.pɪˈlædʒ.ɪk/ (আরকিপেলাজিক)", "দ্বীপপুঞ্জীয়, ভৌগোলিকভাবে বিচ্ছিন্ন দ্বীপাঞ্চলের সমন্বয়ে তৈরি", ["Island-clustered", "Insular"], ["Continental", "Mainland"], "The archipelagic nation relies heavily on ferry transport between its islands.", "দ্বীপপুঞ্জীয় দেশটি এর দ্বীপগুলোর মধ্যে ফেরি পরিবহনের ওপর ব্যাপকভাবে নির্ভর করে।"),
    ("Argumentation", "Noun", "/ˌɑː.ɡjʊ.menˈteɪ.ʃən/ (আর্গুমেন্টেশন)", "যুক্তি উপস্থাপন, সুসংবদ্ধ যুক্তির মাধ্যমে নিজের অবস্থান সমর্থনের ধারা", ["Reasoning", "Debate", "Discourse", "Logic"], ["Irrationality", "Dogma"], "His brilliant argumentation convinced the jury to acquit the defendant.", "তার চমৎকার যুক্তি উপস্থাপন জুরিকে আসামিকে খালাস দিতে রাজি করিয়েছিল।"),
    ("Arrogate", "Verb", "/ˈær.ə.ɡeɪt/ (অ্যারোগেট)", "অন্যায়ভাবে দাবি করা বা আত্মসাৎ করা, অধিকার না থাকা সত্ত্বেও ক্ষমতা নেওয়া", ["Usurp", "Claim", "Appropriate", "Seize"], ["Relinquish", "Surrender", "Yield"], "The military junta attempted to arrogate supreme executive powers.", "সামরিক জান্তা পরম নির্বাহী ক্ষমতা অন্যায়ভাবে দাবি করা এর চেষ্টা করেছিল।"),
    ("Assuetude", "Noun", "/ˈæs.wɪ.tjuːd/ (অ্যাসুইটিউড)", "অভ্যস্ততা বা আচার, দীর্ঘদিনের অভ্যাসে পরিণত হওয়া কাজ", ["Habit", "Custom", "Practice"], ["Unfamiliarity", "Novelty"], "Years of living in the arctic created a natural assuetude to freezing weather.", "সুমেরুতে বহু বছর বসবাসের ফলে বরফশীতল আবহাওয়ার প্রতি এক প্রাকৃতিক অভ্যস্ততা তৈরি হয়েছিল।"),
    ("Beatification", "Noun", "/biːˌæt.ɪ.fɪˈkeɪ.ʃən/ (বিয়াটিফিকেশন)", "পূণ্যবান ঘোষণা, চার্চ কর্তৃক প্রদত্ত বিশেষ সম্মানজনক স্বীকৃতি", ["Canonization", "Blessing", "Sanctification"], ["Excommunication"], "The cathedral celebrated the beatification of the revered missionary nun.", "ক্যাথেড্রাল শ্রদ্ধেয় মিশনারি নানকে পূণ্যবান ঘোষণা উদযাপন করেছে।"),
    ("Benediction", "Noun", "/ˌben.ɪˈdɪk.ʃən/ (বেনিডিকশন)", "মাঙ্গলিক আশীর্বাদ, ঈশ্বর বা প্রধানের পক্ষ থেকে শুভকামনা নিবেদন", ["Blessing", "Grace", "Invocation", "Prayer"], ["Curse", "Malediction"], "The patriarch gave a soothing benediction to the departing pilgrims.", "কুলপতি বিদায়ী তীর্থযাত্রীদের এক আনন্দদায়ক মাঙ্গলিক আশীর্বাদ প্রদান করেন।"),
    ("Bifurcation", "Noun", "/ˌbaɪ.fəˈkeɪ.ʃən/ (বাইফারকেশন)", "দ্বিধাবিভক্তকরণ, প্রধান ধারা বা পথকে দুই ভাগে ভাগ করা", ["Forking", "Division", "Dichotomy", "Splitting"], ["Merging", "Unification"], "The bifurcation of the stream allowed water to reach both farmland plots.", "স্রোতের দ্বিধাবিভক্তকরণ পানিকে উভয় কৃষিজমিতে পৌঁছাতে সাহায্য করেছিল।"),
    ("Bowdlerize", "Verb", "/ˈbaʊd.lə.raɪz/ (বাউডলারাইজ)", "লেখা পরিমার্জন ও সেন্সর করা, অনুচিত অংশ কেটে সাহিত্য প্রকাশ করা", ["Censor", "Expurgate", "Sanitize"], ["Include", "Restore"], "The editors bowdlerize the historical letters to make them suitable for youth.", "সম্পাদকরা যুবকদের উপযোগী করতে ঐতিহাসিক চিঠিগুলো পরিমার্জন ও সেন্সর করেছিল।"),
    ("Braggadocio", "Noun", "/ˌbræɡ.əˈdəʊ.tʃi.əʊ/ (ব্র্যাগ্যাডোসিও)", "ফাঁপা অহংকার, নিজের শক্তি বা অর্থ নিয়ে দম্ভ প্রকাশ", ["Boastfulness", "Bravado", "Swagger"], ["Modesty", "Humility"], "His empty braggadocio convinced no one in the courtroom.", "তার ফাঁপা অহংকার এজলাসের কাউকেই আশ্বস্ত করতে পারেনি।"),
    ("Cacography", "Noun", "/kæˈkɒɡ.rə.fi/ (ক্যাকোগ্রাফি)", "বাজে বা অপরিষ্কার হস্তাক্ষর, পড়তে কষ্ট হওয়া লিখন", ["Bad handwriting", "Scrawl", "Scribble"], ["Calligraphy"], "The doctor's prescription was notorious for its illegible cacography.", "ডাক্তারের প্রেসক্রিপশনটি এর অস্পষ্ট বাজে বা অপরিষ্কার হস্তাক্ষর এর জন্য পরিচিত ছিল।"),
    ("Cajolery", "Noun", "/kəˈdʒəʊ.lər.i/ (ক্যাজোলারি)", "মিষ্টি কথায় ভুলানো, চাটুকারিতার মাধ্যমে রাজি করানোর কৌশল", ["Wheedling", "Flattery", "Coaxing", "Blandishment"], ["Coercion", "Threats"], "She used sweet cajolery to persuade her uncle to finance her trip.", "তিনি তার ট্রিপে অর্থায়নে চাচাকে রাজি করাতে মিষ্টি কথায় ভুলানো এর আশ্রয় নিয়েছিলেন।"),
    ("Camouflage", "Noun", "/ˈkæm.ə.flɑːʒ/ (ক্যামোফ্লেজ)", "ছদ্মবেশ বা রূপলুকানো, পরিবেশের সাথে মিশে গোপন থাকার কৌশল", ["Disguise", "Concealment", "Cover", "Mask"], ["Exposure", "Uncovering"], "Chameleons use skin color camouflage to hide from dangerous predators.", "ক্যামেলিয়ন বিপজ্জনক শিকারীদের কাছ থেকে লুকাতে ত্বকের রঙের ছদ্মবেশ ব্যবহার করে।"),
    ("Cannibalism", "Noun", "/ˈkæn.ɪ.bəl.ɪz.əm/ (ক্যানিব্যালিজম)", "স্বজাতিভক্ষণ, নিজস্ব প্রজাতির মাংস খাওয়ার নৃশংস অভ্যাস", ["Anthropophagy", "Self-consumption"], ["Vegetarianism"], "Famine forced the isolated survivors into horrifying acts of cannibalism.", "দুর্ভিক্ষ বিচ্ছিন্ন বেঁচে থাকা মানুষদের স্বজাতিভক্ষণ এর মতো ভয়াবহ কাজে বাধ্য করেছিল।"),
    ("Captiousness", "Noun", "/ˈkæp.ʃəs.নəs/ (ক্যাপশাসনেস)", "খুঁতখুঁতে বিচারপ্রবণতা, সবসময় ভুল ধরার মানসিকতা", ["Faultfinding", "Carping", "Hypercriticism"], ["Approval", "Praise"], "Her constant captiousness demoralized the young junior research team.", "তার অনবরত খুঁতখুঁতে বিচারপ্রবণতা তরুণ জুনিয়র গবেষণা দলকে হতাশ করেছিল।"),
    ("Catechism", "Noun", "/ˈkæt.ə.kɪz.əm/ (ক্যাটেকিজম)", "ধর্মীয় নীতিমালার সওয়াল-জবাব, মুখস্থ বিদ্যার প্রশ্নোত্তরী", ["Instruction", "Doctrine", "Dogma"], ["Dissent"], "Students recited the traditional catechism during Sunday school.", "শিক্ষার্থীরা রবিবার স্কুলের সময় ঐতিহ্যবাহী নীতিমালার সওয়াল-জবাব আবৃত্তি করেছিল।"),
    ("Causticity", "Noun", "/kɔːˈstɪs.ə.ti/ (কস্টাসিটি)", "কটু বা তীব্রতা, ক্ষয়কারী রাসায়নিক বা ব্যঙ্গাত্মক কথা", ["Corrosiveness", "Bitterness", "Acrimony"], ["Gentleness", "Mildness"], "The causticity of his remarks left his opponents deeply offended.", "তার মন্তব্যের কটু বা তীব্রতা তার বিরোধীদের গভীরভাবে ক্ষুব্ধ করেছিল।"),
    ("Climacteric", "Noun", "/klaɪˈmæk.tər.ɪk/ (ক্লাইম্যাকটেরিক)", "জীবনের চরম সংকটময় সন্ধিক্ষণ, গুরুত্বপূর্ণ পরিবর্তনের মুহূর্ত", ["Critical point", "Crisis", "Turning point", "Menopause"], ["Continuity", "Stability"], "Middle age often brings a psychological climacteric regarding career goals.", "মধ্যবয়স প্রায়শই কর্মজীবনের লক্ষ্য সম্পর্কিত একটি মনস্তাত্ত্বিক চরম সংকটময় সন্ধিক্ষণ নিয়ে আসে।"),
    ("Cognomen", "Noun", "/kɒɡˈnəʊ.men/ (কগনোটেন)", "বংশগত পরিচিতি বা উপাধিসূচক নাম", ["Surname", "Nickname", "Epithet"], ["Anonymity"], "His bravery in battle earned him the glorious cognomen 'The Lionheart'.", "যুদ্ধে তার বীরত্ব তাকে 'সিংহহৃদয়' এর মতো গৌরবময় উপাধিসূচক নাম এনে দিয়েছিল।"),
    ("Compunction", "Noun", "/kəmˈpʌŋk.ʃən/ (কমপাঙ্কশন)", "অনুতাপ ও অপরাধবোধ, অন্যায় করার পর বিবেকের দংশন", ["Remorse", "Qualm", "Guilt", "Scruple"], ["Indifference", "Callousness"], "He stole the money with no apparent compunction or hesitation.", "সে কোনো দৃশ্যমান অনুতাপ ও অপরাধবোধ বা দ্বিধা ছাড়াই টাকা চুরি করেছিল।"),
    ("Condign", "Adjective", "/kənˈdaɪn/ (কনডাইন)", "উপযুক্ত ও সুসংগত, অপরাধের মানানসই ন্যায়সঙ্গত শাস্তি", ["Fitting", "Deserved", "Appropriate"], ["Unjust", "Undeserved"], "The criminal received condign punishment for his serious offenses.", "অপরাধী তার গুরুতর অপরাধের জন্য উপযুক্ত ও সুসংগত শাস্তি পেয়েছিল।"),
    ("Coruscate", "Verb", "/ˈkɒr.ə.skeɪt/ (করোস্কেট)", "ঝিলমিল করে জ্বলা, আলোকরশ্মি ছড়ানো", ["Sparkle", "Glisten", "Shine", "Flash"], ["Dull", "Darken"], "The crystal chandelier coruscate brilliantly above the ballroom dance floor.", "বলরুমের নাচের মেঝের ওপরে ক্রিস্টাল ঝাড়বাতিটি চমৎকারভাবে ঝিলমিল করে জ্বলা শুরু করে।"),
    ("Cosmogony", "Noun", "/kɒzˈmɒɡ.ə.ni/ (কসমোগনি)", "মহাবিশ্ব সৃষ্টি তত্ত্ব, মহাজাগতিক বস্তুর উৎপত্তির ইতিহাস", ["Cosmology", "Creation theory"], ["End times"], "Mythology offers fascinating accounts of ancient solar cosmogony.", "পৌরাণিক কাহিনী প্রাচীন সৌর মহাবিশ্ব সৃষ্টি তত্ত্ব এর চিত্তাকর্ষক বিবরণ দেয়।"),
    ("Desideratum", "Noun", "/dɪˌzɪd.əˈrɑː.təm/ (ডিজিডারেটাম)", "পরম কাঙ্ক্ষিত বিষয়, যা অভাব মেটাতে অত্যন্ত প্রয়োজনীয়", ["Requirement", "Need", "Essential"], ["Surplus"], "Clean drinking water is an urgent desideratum for rural drought communities.", "বিশুদ্ধ খাবার পানি গ্রামীণ খরা পীড়িত সম্প্রদায়ের জন্য এক পরম কাঙ্ক্ষিত বিষয়।"),
    ("Diuturnity", "Noun", "/ˌdaɪ.juːˈtɜː.nə.ti/ (ডায়াটারনিটি)", "দীর্ঘকালস্থায়িত্ব, যুগ যুগ ধরে টিকে থাকার সামর্থ্য", ["Durability", "Permanence", "Longevity"], ["Brevity", "Transience"], "The monument stands as testament to the diuturnity of Egyptian civilization.", "স্মৃতিস্তম্ভটি মিশরীয় সভ্যতার দীর্ঘকালস্থায়িত্ব এর প্রমাণ হিসেবে দাঁড়িয়ে আছে।"),
    ("Divagation", "Noun", "/ˌdaɪ.vəˈɡeɪ.ʃən/ (ডাইভাগ্রেশন)", "মূল বিষয় থেকে বিচ্যুতি, আলোচনার খেই হারিয়ে ফেলা", ["Digression", "Wandering", "Deviation"], ["Directness", "Focus"], "The professor's lecture suffered from constant divagation into side stories.", "অধ্যাপকের বক্তৃতাটি পার্শ্ববর্তী গল্পে অনবরত মূল বিষয় থেকে বিচ্যুতি এর শিকার হয়েছিল।"),
    ("Efflorescence", "Noun", "/ˌef.lɔːˈres.əns/ (এফলোরেসেন্স)", "পূর্ণ প্রস্ফুটিত রূপ, শিল্প বা সংস্কৃতি চরম বিকাশ পাওয়া", ["Flourishing", "Blooming", "Culmination"], ["Decline", "Decay"], "The renaissance period was a glorious efflorescence of human culture.", "রেনেসাঁ পর্বটি মানব সংস্কৃতির এক গৌরবময় পূর্ণ প্রস্ফুটিত রূপ ছিল।"),
    ("Effulgence", "Noun", "/ɪˈfʌl.dʒəns/ (ইফালজেন্স)", "উজ্জ্বল প্রভা, চারদিক উদ্ভাসিত করা জ্যোতি", ["Radiance", "Brilliance", "Splendor"], ["Darkness", "Dullness"], "The morning sun rose with magnificent effulgence over the mountains.", "সকালের সূর্য পাহাড়ের ওপর চমৎকার উজ্জ্বল প্রভা নিয়ে উদিত হয়েছিল।"),
    ("Ersatz", "Adjective", "/ˈeə.zæts/ (এরস্যাটস)", "কৃত্রিম বিকল্প, আসল জিনিষের বদলে ব্যবহৃত অনুকরণীয় জিনিস", ["Artificial", "Substitute", "Synthetic"], ["Genuine", "Real"], "They served ersatz chocolate made from carob during the supply shortage.", "সরবরাহের ঘাটতির সময় তারা ক্যারব থেকে তৈরি কৃত্রিম বিকল্প চকোলেট পরিবেশন করেছিল।"),
    ("Filibuster", "Noun", "/ˈfɪl.ɪ.bʌs.tər/ (ফিলিবাস্টার)", "দীর্ঘ বক্তৃতায় বিলে বাধা সৃষ্টি, আইন পাসে বিলম্ব ঘটানোর চেষ্টা", ["Delaying tactic", "Obstruction"], ["Expedition", "Voting"], "The senator planned a marathon filibuster to halt the voting process.", "সিনেটর ভোটিং প্রক্রিয়া স্থগিত করতে এক ম্যারাথন দীর্ঘ বক্তৃতায় বিলে বাধা সৃষ্টি এর পরিকল্পনা করেছিলেন।"),
    ("Glabrous", "Adjective", "/ˈɡleɪ.brəs/ (গ্ল্যাব্রাস)", "লোমহীন মসৃণ ত্বক বা পাতা", ["Hairless", "Smooth", "Sleek"], ["Hairy", "Hirsute"], "Botany students examined the glabrous stem of the desert plant.", "উদ্ভিদবিদ্যার ছাত্ররা মরুভূমির গাছের লোমহীন মসৃণ কান্ড পরীক্ষা করেছিল।"),
    ("Halitosis", "Noun", "/ˌhæl.ɪˈtəʊ.sɪs/ (হ্যালিটোসিস)", "মুখের দুর্গন্ধ, স্বাস্থ্যবিধি না মানায় মুখে দুর্গন্ধ তৈরি হওয়া", ["Bad breath", "Foul odor"], ["Fresh breath"], "Proper flossing significantly reduces the risk of chronic halitosis.", "সঠিক ফ্লসিং দীর্ঘস্থায়ী মুখের দুর্গন্ধ এর ঝুঁকি উল্লেখযোগ্যভাবে কমায়।"),
    ("Heuristic", "Adjective", "/hjʊəˈrɪs.tɪk/ (হিওরিস্টিক)", "ব্যবহারিক ও অভিজ্ঞতালব্ধ শিক্ষা পদ্ধতি", ["Self-learning", "Problem-solving"], ["Rote-learned"], "Heuristic problem solving helps software quickly find approximate answers.", "ব্যবহারিক ও অভিজ্ঞতালব্ধ শিক্ষা পদ্ধতি সফটওয়্যারকে দ্রুত আনুমানিক উত্তর খুঁজে পেতে সাহায্য করে।"),
    ("Historiography", "Noun", "/hɪˌstɒr.iˈɒɡ.rə.fi/ (হিস্টোরিওগ্রাফি)", "ইতিহাস লিখন ধারা ও ঐতিহাসিক গবেষণা পদ্ধতি", ["Historical study", "Methodology"], ["Fiction"], "Modern historiography re-evaluates the causes of the First World War.", "আধুনিক ইতিহাস লিখন ধারা প্রথম বিশ্বযুদ্ধের কারণগুলো পুনর্বিবেচনা করে।"),
    ("Iconography", "Noun", "/ˌaɪ.kəˈnɒɡ.rə.fi/ (আইকনোগ্রাফি)", "প্রতীক ও চিত্রবিজ্ঞান, প্রাচীন শিল্পের চিহ্নের অর্থ ব্যাখ্যা", ["Symbolism", "Art study"], ["Abstraction"], "The museum tour explained Christian iconography in medieval altar paintings.", "জাদুঘর ভ্রমণটি মধ্যযুগীয় বেদীর চিত্রগুলোতে খ্রিস্টান প্রতীক ও চিত্রবিজ্ঞান ব্যাখ্যা করেছিল।"),
    ("Inchoate", "Adjective", "/ɪnˈkəʊ.eɪt/ (ইনকোয়েট)", "শুরু হওয়া অসম্পূর্ণ রূপ, যা এখনও পূর্ণতা পায়নি", ["Rudimentary", "Incipient", "Unformed"], ["Complete", "Finished"], "The artist sketched an inchoate design for the public mural.", "শিল্পী গণ ম্যুরালের জন্য একটি শুরু হওয়া অসম্পূর্ণ রূপ স্কেচ করেছিলেন।"),
    ("Ineluctable", "Adjective", "/ˌɪn.ɪˈlʌk.tə.bəl/ (ইনইলাক্টেবল)", "অনিবার্য বা অলঙ্ঘনীয়, যাকে কোনভাবেই এড়ানো যায় না", ["Inevitable", "Unavoidable", "Inescapable"], ["Avoidable", "Preventable"], "Change is an ineluctable law of nature and life.", "পরিবর্তন প্রকৃতি ও জীবনের এক অনিবার্য বা অলঙ্ঘনীয় আইন।"),
    ("Irascible", "Adjective", "/ɪˈræs.ə.bəl/ (ইরাসিবল)", "খিটখিটে ও বদমেজাজী, অল্পতেই রাগে ফেটে পড়ে এমন", ["Quick-tempered", "Irritable", "Cholerick"], ["Calm", "Patient"], "The irascible professor demanded absolute silence in his lecture hall.", "খিটখিটে ও বদমেজাজী অধ্যাপক তার লেকচার হলে সম্পূর্ণ নীরবতার দাবি করেছিলেন।"),
    ("Juxtaposition", "Noun", "/ˌdʒʌk.stə.pəˈzɪʃ.ən/ (জাক্সটাপজিশন)", "পাশাপাশি রেখে বৈপরিত্য দেখানো, তুলনামূলক স্থাপন", ["Contrast", "Comparison", "Proximity"], ["Separation"], "The juxtaposition of wealth and poverty in the city was striking.", "শহরে সম্পদ এবং দারিদ্র্যের পাশাপাশি রেখে বৈপরিত্য দেখানো ছিল দৃশ্যমান তীব্র।"),
    ("Lachrymose", "Adjective", "/ˈlæk.rɪ.məʊs/ (ল্যাকরিমোস)", "কাঁদুনে বা অশ্রুসজল, খুব দ্রুত কেঁদে ফেলে এমন", ["Tearful", "Sorrowful", "Mournful"], ["Joyful", "Cheerful"], "She delivered a lachrymose eulogy at her best friend's funeral.", "তিনি তার সেরা বন্ধুর শেষকৃত্যে একটি কাঁদুনে বা অশ্রুসজল শোকগাথা পাঠ করেছিলেন।"),
    ("Macabre", "Adjective", "/məˈkɑː.brə/ (মাকাব্রা)", "মৃত্যুভিত্তিক বীভৎস, গা ছমছম করা দৃশ্য", ["Gruesome", "Grisly", "Morbid"], ["Pleasant", "Delightful"], "The macabre stories of Edgar Allan Poe continue to chill readers.", "এডগার অ্যালান পোর মৃত্যুভিত্তিক বীভৎস গল্পগুলো পাঠকদের শিহরিত করে চলেছে।"),
    ("Magnanimity", "Noun", "/ˌmæg.nəˈnɪm.ə.ti/ (ম্যাগনানিম্যাক্সিটি)", "উদার মহানুভবতা, ক্ষমার মানসিকতা দেখানো", ["Generosity", "Nobility", "Forgiveness"], ["Meanness", "Pettyness"], "The ruler showed magnanimity by granting amnesty to political prisoners.", "শাসক রাজনৈতিক বন্দীদের রাজক্ষমা দিয়ে উদার মহানুভবতা দেখিয়েছিলেন।"),
    ("Mellifluous", "Adjective", "/məˈlɪf.lu.əs/ (মেলिफ্লুয়াস)", "সুমিষ্ট সুরের, মধুঝরা কণ্ঠস্বর", ["Dulcet", "Euphonious", "Smooth"], ["Harsh", "Grate"], "The choir sang in a rich, mellifluous harmony that captivated all.", "গায়কদল এক সমৃদ্ধ, সুমিষ্ট সুরের ঐকতানে গেয়েছিল যা সবাইকে মুগ্ধ করেছিল।"),
    ("Metamorphosis", "Noun", "/ˌmet.əˈmɔː.fə.sɪs/ (মেটামরফোসিস)", "দৈহিক বা রূপগত রূপান্তর, আকৃতির আমূল পরিবর্তন", ["Transformation", "Transmutation"], ["Stagnation"], "The tadpole undergoes metamorphosis to become a fully grown frog.", "ব্যাঙাচিটি পূর্ণাঙ্গ ব্যাঙে পরিণত হতে রূপগত রূপান্তর এর মধ্য দিয়ে যায়।"),
    ("Misnomer", "Noun", "/ˌmɪsˈnəʊ.mər/ (মিসনোমার)", "ভুল আখ্যা বা অসঙ্গতিপূর্ণ নাম", ["Wrong name", "Misnaming"], ["Accurate term"], "To call that fierce guard dog 'Tiny' is a funny misnomer.", "সেই হিংস্র প্রহরী কুকুরকে 'টাইনি' বলা একটি মজার ভুল আখ্যা।"),
    ("Nihilism", "Noun", "/ˈnaɪ.hɪ.lɪz.əm/ (নাইহিলিজম)", "শূন্যবাদ, সকল নৈতিক মূল্যবোধের অনুপস্থিতিতে বিশ্বাস", ["Skepticism", "Anarchism"], ["Belief", "Faith"], "Despair over the war led many young intellectuals into nihilism.", "যুদ্ধের ওপর হতাশা অনেক তরুণ বুদ্ধিজীবীকে শূন্যবাদ এর দিকে পরিচালিত করেছিল।"),
    ("Obfuscation", "Noun", "/ˌɒb.fʌsˈkeɪ.ʃən/ (অবফাসকেশন)", "ঘোলাটে করার চেষ্টা, ইচ্ছাকৃতভাবে অস্পষ্ট রাখা", ["Confusion", "Obscurity"], ["Clarity", "Clarification"], "The politician used obfuscation to avoid answering questions directly.", "রাজনীতিবিদ সরাসরি প্রশ্নের উত্তর দেওয়া এড়াতে ঘোলাটে করার চেষ্টা ব্যবহার করেছিলেন।"),
    ("Oligarchy", "Noun", "/ˈɒl.ɪ.ɡɑː.ki/ (অলগার্কি)", "গোষ্ঠীতন্ত্র বা কতিপয়তন্ত্র, গুটিকয়েক ধনী লোকের দ্বারা পরিচালিত রাষ্ট্র", ["Small group rule", "Plutocracy"], ["Democracy"], "The country was controlled by a wealthy economic oligarchy.", "দেশটি একটি ধনী অর্থনৈতিক গোষ্ঠীতন্ত্র বা কতিপয়তন্ত্র দ্বারা নিয়ন্ত্রিত ছিল।"),
    ("Omnipresence", "Noun", "/ˌɒm.nɪˈprez.əns/ (ওমনিপ্রেজেন্স)", "সর্বত্র বিদ্যমান থাকা, সর্বব্যাপী রূপ", ["Ubiquity", "Pervasiveness"], ["Absence"], "The omnipresence of surveillance cameras raised privacy concerns.", "নজরদারি ক্যামেরার সর্বত্র বিদ্যমান থাকা গোপনীয়তার উদ্বেগ বাড়িয়েছিল।"),
    ("Opprobrium", "Noun", "/əˈprəʊ.bri.əm/ (অপ্রোব্রিয়াম)", "জনসমক্ষে চরম ধিক্কার বা নিন্দা", ["Disgrace", "Infamy", "Shame"], ["Praise", "Honor"], "The corrupt official resigned under intense public opprobrium.", "দুর্নীতিগ্রস্ত কর্মকর্তা তীব্র জনসমক্ষে চরম ধিক্কার এর মুখে পদত্যাগ করেছেন।"),
    ("Ostracism", "Noun", "/ˈɒs.trə.sɪz.əm/ (অস্ট্রাসিজম)", "সমাজচ্যুতকরণ বা সমাজ থেকে বহিষ্কার", ["Exclusion", "Banishment"], ["Inclusion", "Acceptance"], "Her betrayal led to complete social ostracism by her peers.", "তার বিশ্বাসঘাতকতা তার সহপাঠীদের দ্বারা সম্পূর্ণ সমাজচ্যুতকরণ এর দিকে পরিচালিত করেছিল।"),
    ("Paternalism", "Noun", "/pəˈtɜː.nəl.ɪz.əm/ (প্যাটার্নালিজম)", "অভিভাবকসুলভ কর্তৃত্ব, স্বাধীনতা খর্ব করে সুরক্ষা প্রদান", ["Patronage", "Authoritarian care"], ["Autonomy"], "Some citizens resented the state's welfare paternalism.", "কিছু নাগরিক রাষ্ট্রের কল্যাণমুখী অভিভাবকসুলভ কর্তৃত্ব এ অসন্তুষ্ট ছিলেন।"),
    ("Patrimony", "Noun", "/ˈpæt.rɪ.mə.ni/ (প্যাট্রিমনি)", "পৈতৃক সম্পদ বা জাতীয় সাংস্কৃতিক ঐতিহ্য", ["Inheritance", "Legacy", "Heritage"], ["Divestment"], "The ancient temple complex is part of the country's national patrimony.", "প্রাচীন মন্দির প্রাঙ্গণটি দেশের জাতীয় পৈতৃক সম্পদ বা জাতীয় সাংস্কৃতিক ঐতিহ্য এর অংশ।"),
    ("Pedagogy", "Noun", "/ˈped.ə.ɡɒdʒ.i/ (পেডাগোজি)", "শিক্ষাদান তত্ত্ব ও কৌশল, পঠন-পাঠন পদ্ধতি", ["Teaching science", "Education theory"], ["Ignorance"], "Innovative digital pedagogy engages students more effectively.", "উদ্ভাবনী ডিজিটাল শিক্ষাদান তত্ত্ব ও কৌশল শিক্ষার্থীদের আরও কার্যকরভাবে সংযুক্ত করে।"),
    ("Psephology", "Noun", "/siːˈfɒl.ə.dʒi/ (সেফোলজি)", "নির্বাচন পরিসংখ্যান ও ভোটদান সম্পর্কিত বিদ্যা", ["Voting statistics", "Election study"], ["Astrology"], "Psephology predicted a tight race between the rival political parties.", "নির্বাচন পরিসংখ্যান ও ভোটদান সম্পর্কিত বিদ্যা প্রতিদ্বন্দ্বী রাজনৈতিক দলগুলোর মধ্যে তুমুল লড়াইয়ের পূর্বাভাস দিয়েছিল।"),
    ("Recalcitrant", "Adjective", "/rɪˈkæl.sɪ.trənt/ (রিক্যালসিট্রান্ট)", "একগুঁয়ে অবাধ্য, কোনো নিয়ম না মানা", ["Insubordinate", "Unruly", "Defiant"], ["Obedient", "Submissive"], "The recalcitrant prisoner refused to cooperate with the guards.", "একগুঁয়ে অবাধ্য বন্দি প্রহরীদের সাথে সহযোগিতা করতে অস্বীকার করেছিল।"),
    ("Recrimination", "Noun", "/rɪˌkrɪm.ɪˈneɪ.ʃən/ (রিক্রিমিনেশন)", "পাল্টা দোষারোপ, এক পক্ষের জবাবে অন্য পক্ষের অভিযোগ", ["Countercharge", "Retort"], ["Praise", "Forgiveness"], "The meeting dissolved into angry recrimination and shouting.", "বৈঠকটি ক্ষুব্ধ পাল্টা দোষারোপ এবং চেঁচামেচিতে ভেস্তে গিয়েছিল।"),
    ("Repercussion", "Noun", "/ˌriː.pəˈkʌʃ.ən/ (রিপারকাশন)", "পরোক্ষ সুদূরপ্রসারী প্রতিক্রিয়া বা মন্দ ফলাফল", ["Consequence", "Backlash"], ["Cause"], "The economic policy decision had unexpected global repercussion.", "অর্থনৈতিক নীতি সিদ্ধান্তের অপ্রত্যাশিত বৈশ্বিক পরোক্ষ সুদূরপ্রসারী প্রতিক্রিয়া ছিল।"),
    ("Sycophancy", "Noun", "/ˈsɪk.ə.fən.si/ (সিকোফ্যান্সি)", "তোষামোদ বা চাটুকারিতা, স্বার্থ উদ্ধারে মিথ্যা প্রশংসা", ["Flattery", "Servility"], ["Honesty", "Disdain"], "The manager was surrounded by sycophancy and fake praise.", "ম্যানেজার তোষামোদ বা চাটুকারিতা এবং ভুয়া প্রশংসায় পরিবেষ্টিত ছিলেন।"),
    ("Ubiquity", "Noun", "/juːˈbɪk.wə.ti/ (ইউবিকুইটি)", "সর্ববিদ্যমানতা, সর্বত্র উপস্থিতি", ["Omnipresence", "Pervasiveness"], ["Scarcity"], "The ubiquity of social media has redefined modern human connection.", "সোশ্যাল মিডিয়ার সর্ববিদ্যমানতা আধুনিক মানব সংযোগকে নতুন করে সংজ্ঞায়িত করেছে।"),
    ("Vicissitude", "Noun", "/vɪˈsɪs.ɪ.tʃuːd/ (ভিসিসিটিউড)", "জীবনের অনিশ্চিত পরিবর্তন ও উত্থান-পতন", ["Fluctuating", "Ups and downs"], ["Stability"], "He faced the vicissitude of life with courage and grace.", "তিনি সাহস এবং মর্যাদার সাথে জীবনের অনিশ্চিত পরিবর্তন ও উত্থান-পতন এর মুখোমুখি হয়েছিলেন।"),
    ("Volubility", "Noun", "/ˌvɒl.jʊˈbɪl.ə.ti/ (ভলিউবিলিটি)", "বাকপটুতা বা দ্রুত কথা বলার ক্ষমতা", ["Fluency", "Loquacity"], ["Taciturnity"], "His endless volubility entertained everyone at the dinner party.", "তার অশেষ বাকপটুতা ডিনার পার্টিতে সবাইকে বিনোদিত করেছিল।")
]

added = []
for item in raw_entries:
    word, pos, pron, mean, syns, ants, ex_en, ex_bn = item
    if word.strip().lower() not in existing:
        added.append(item)

print(f"Generated {len(added)} fresh entries for batch9_extra2.py")

with open("batch9_extra2.py", "w", encoding="utf-8") as f:
    f.write("# coding=utf-8\n\nBATCH9_EXTRA2 = [\n")
    for item in added:
        f.write(f"    {repr(item)},\n")
    f.write("]\n")

print("Successfully written batch9_extra2.py!")
