import json

# Load existing dataset
with open('app/src/main/assets/dictionary_1000.json', 'r', encoding='utf-8') as f:
    dict_data = json.load(f)

existing_words_set = set(x['word'].strip().lower() for x in dict_data)
print(f"Existing count: {len(dict_data)}")

# 350 curated, authentic high-frequency competitive exam words (BCS, Bank, Varsity Admission, GRE, IELTS)
new_words_raw = [
    # A
    ("Candid", "Adjective", "/ˈkæn.dɪd/ (ক্যান্ডিড)", "কপটতাহীন বা আমায়িক ও স্পষ্টভাষী", ["Frank", "Outspoken", "Direct", "Honest"], ["Deceitful", "Evasive", "Guarded"], "She gave a candid assessment of the company's financial status.", "তিনি কোম্পানির আর্থিক পরিস্থিতির একটি স্পষ্টভাষী মূল্যায়ন দিয়েছিলেন।", "BCS & Bank"),
    ("Capricious", "Adjective", "/kəˈprɪʃ.əs/ (ক্যাপ্রিশাস)", "খামখেয়ালী বা পরিবর্তনশীল", ["Fickle", "Whimsical", "Erratic", "Impulsive"], ["Stable", "Predictable", "Consistent"], "The coastal weather is notoriously capricious during spring.", "বসন্তকালে উপকূলীয় আবহাওয়া অত্যন্ত খামখেয়ালী প্রকৃতির হয়।", "GRE & Admission"),
    ("Castigate", "Adjective/Verb", "/ˈkæs.tɪ.ɡeɪt/ (ক্যাস্টিগেট)", "তীব্রভাবে সমালোচনা করা বা শাস্তি দেওয়া", ["Chastise", "Censure", "Reprove", "Reprimand"], ["Praise", "Compliment", "Extol"], "The director castigated the team for failing to meet the safety deadline.", "নিরাপত্তার সময়সীমা পূরণে ব্যর্থ হওয়ার জন্য পরিচালক দলটিকে কঠোর সমালোচনা করেছিলেন।", "GRE & BCS"),
    ("Caustic", "Adjective", "/ˈkɔː.stɪk/ (কস্টিক)", "অত্যন্ত কটু, দগ্ধকারী বা কষাঘাতপূর্ণ", ["Sarcastic", "Acerbic", "Cutting", "Biting"], ["Gentle", "Kind", "Mild"], "Her caustic remarks left everyone feeling hurt.", "তাঁর কটু মন্তব্য সবাইকে আঘাতপ্রাপ্ত করে রেখেছিল।", "BCS & Bank"),
    ("Chicanery", "Noun", "/ʃɪˈkeɪ.nər.i/ (শিকেনারী)", "প্রতারণা, ছলাকলা বা রাজনৈতিক শঠতা", ["Trickery", "Deception", "Duplicity", "Subterfuge"], ["Honesty", "Truthfulness", "Frankness"], "The audit revealed financial chicanery within the executive committee.", "নিরীক্ষায় নির্বাহী কমিটির মধ্যে আর্থিক শঠতা প্রকাশ পেয়েছিল।", "GRE & Bank"),
    ("Clandestine", "Adjective", "/klænˈdes.tɪn/ (ক্ল্যান্ডেস্টিন)", "গোপন বা অলক্ষ্যে সম্পাদিত", ["Secret", "Covert", "Surreptitious", "Furtive"], ["Overt", "Open", "Public"], "They held a clandestine meeting to discuss the merger.", "তারা একীভূতকরণ নিয়ে আলোচনা করতে একটি গোপন বৈঠক করেছিল।", "BCS & IELTS"),
    ("Cogent", "Adjective", "/ˈkəʊ.dʒənt/ (কোজেন্ট)", "সুনির্দিষ্ট ও জোরালোভাবে যুক্তিযুক্ত", ["Compelling", "Persuasive", "Convincing", "Sound"], ["Unconvincing", "Weak", "Ineffective"], "The lawyer presented a cogent argument that swayed the jury.", "আইনজীবী একটি জোরালো যুক্তি উপস্থাপন করেছিলেন যা জুরিকে প্রভাবিত করেছিল।", "GRE & BCS"),
    ("Commensurate", "Adjective", "/kəˈmen.sjər.ət/ (কমেনশুরেট)", "সমানুপাতিক বা উপযুক্ত সামঞ্জস্যপূর্ণ", ["Proportional", "Equivalent", "Corresponding"], ["Incommensurate", "Disproportionate"], "Salary will be commensurate with your experience and skills.", "আপনার অভিজ্ঞতা ও দক্ষতার সাথে সামঞ্জস্যপূর্ণ বেতন প্রদান করা হবে।", "Bank & Corporate"),
    ("Compendium", "Noun", "/kəmˈpen.di.əm/ (কমপেন্ডিয়াম)", "সারসংক্ষেপ বা সংক্ষিপ্ত সারণী", ["Summary", "Abstract", "Digest", "Compilation"], ["Expansion", "Unabridged version"], "The book is a comprehensive compendium of regional history.", "বইটি আঞ্চলিক ইতিহাসের একটি পূর্ণাঙ্গ সারসংক্ষেপ।", "GRE & Admission"),
    ("Complaisant", "Adjective", "/kəmˈpleɪ.zənt/ (কমপ্লেজেন্ট)", "পরের সন্তুষ্টিবিধানে ইচ্ছুক বা বিনয়ী", ["Obliging", "Polite", "Cooperative", "Submissive"], ["Disagreeable", "Refractory", "Uncooperative"], "She was so complaisant that she rarely refused any request.", "তিনি এতটাই বাধ্য ছিলেন যে কোনো অনুরোধ কখনো ফেলতেন না।", "GRE & BCS"),
    ("Conciliatory", "Adjective", "/kənˈsɪl.i.ə.tər.i/ (কনসিলিয়েটরি)", "শান্তিদায়ক বা বিরোধ মীমাংসাকারী", ["Pacifying", "Appeasing", "Placatory", "Mollifying"], ["Antagonistic", "Aggressive", "Provocative"], "The nation took a conciliatory approach to resolve border issues.", "সীমান্ত বিরোধ মেটাতে দেশটি একটি শান্তিদায়ক পদক্ষেপ গ্রহণ করেছিল।", "BCS & Bank"),
    ("Condone", "Verb", "/kənˈdəʊn/ (কনডোন)", "উপেক্ষা করা বা ক্ষমা দৃষ্টিতে দেখা", ["Overlook", "Pardon", "Forgive", "Disregard"], ["Condemn", "Censure", "Punish"], "The university does not condone academic dishonesty in any form.", "বিশ্ববিদ্যালয় কোনো অবস্থাতেই একাডেমিক অসদুপায়কে ক্ষমা সুন্দর দৃষ্টিতে দেখে না।", "BCS & IELTS"),
    ("Confound", "Verb", "/kənˈfaʊnd/ (কনফাউন্ড)", "কিংকর্তব্যবিমূঢ় করা বা গুলিয়ে ফেলা", ["Confuse", "Baffle", "Perplex", "Bewilder"], ["Clarify", "Enlighten", "Explain"], "The complex riddle confounded even the cleverest students.", "জটিল ধাঁধাটি এমনকি সবচেয়ে মেধাবী শিক্ষার্থীদেরও কিংকর্তব্যবিমূঢ় করে দিয়েছিল।", "GRE & Admission"),
    ("Connoisseur", "Noun", "/ˌkɒn.əˈsɜːr/ (কনয়সার)", "শিল্প বা রসবোধের সমঝদার জহুরী", ["Expert", "Authority", "Afficionado", "Judge"], ["Novice", "Ignoramus", "Amateur"], "As an art connoisseur, he could instantly spot an authentic masterwork.", "শিল্পের সমঝদার হিসেবে তিনি মুহূর্তেই খাঁটি মাস্টারওয়ার্ক চিনতে পারতেন।", "BCS & Bank"),
    ("Conundrum", "Noun", "/kəˈnʌn.drəm/ (কনানড্রাম)", "জটিল সমস্যা বা কঠিন ধাঁধা", ["Puzzle", "Enigma", "Riddle", "Dilemma"], ["Solution", "Resolution", "Explanation"], "Finding a balance between economic growth and pollution is a major conundrum.", "অর্থনৈতিক প্রবৃদ্ধি ও দূষণের মধ্যে ভারসাম্য রক্ষা করা একটি বড় জটিল সমস্যা।", "GRE & IELTS"),
    ("Copious", "Adjective", "/ˈkəʊ.pi.əs/ (কোপিয়াস)", "প্রচুর বা অঢেল পরিমাণে বিদ্যমান", ["Abundant", "Plentiful", "Ample", "Profuse"], ["Meager", "Scarce", "Scanty"], "The researchers took copious notes during the long trial.", "দীর্ঘ পরীক্ষা চলাকালীন গবেষকরা প্রচুর পরিমাণে নোট নিয়েছিলেন।", "BCS & Bank"),
    ("Corroborate", "Verb", "/kəˈrɒb.ə.reɪt/ (করোবোরেট)", "প্রমাণের মাধ্যমে সত্যতা সমর্থন করা", ["Confirm", "Verify", "Substantiate", "Validate"], ["Refute", "Contradict", "Disprove"], "Recent lab tests corroborate the doctor's initial diagnosis.", "সাম্প্রতিক ল্যাব পরীক্ষাগুলো ডাক্তারের প্রাথমিক নির্ণয়ের সত্যতা সমর্থন করে।", "GRE & Bank"),
    ("Credulous", "Adjective", "/ˈkred.jə.ləs/ (ক্রেডিউলাস)", "সহজ বিশ্বাসী বা অতিপ্রবণ", ["Gullible", "Naïve", "Trusting", "Uncritical"], ["Skeptical", "Incredulous", "Suspicious"], "The credulous customer believed every claim made in the advertisement.", "সহজ বিশ্বাসী গ্রাহকটি বিজ্ঞাপনে করা প্রতিটি দাবি বিশ্বাস করেছিল।", "BCS & Admission"),
    ("Culpable", "Adjective", "/ˈkʌl.pə.bəl/ (কালপেবল)", "দণ্ডনীয় বা অপরাধের জন্য দায়ী", ["Blameworthy", "Guilty", "Liable", "At fault"], ["Innocent", "Blameless", "Exonerated"], "Both parties were found equally culpable for the financial loss.", "আর্থিক ক্ষতির জন্য উভয় পক্ষকেই সমানভাবে দায়ী পাওয়া গেছে।", "BCS & Law"),
    ("Cursory", "Adjective", "/ˈkɜː.sər.i/ (কার্সরি)", "দ্রুত ও উপরভাসা নজরে দেখা", ["Hasty", "Superficial", "Perfunctory", "Casual"], ["Thorough", "Detailed", "Meticulous"], "He gave the report a cursory glance before stepping into the meeting.", "সভায় ঢোকার আগে তিনি প্রতিবেদনটি কেবল দ্রুত উপরভাসা নজরে দেখে নিয়েছিলেন।", "BCS & Bank"),

    # D
    ("Dearth", "Noun", "/dɜːθ/ (ডার্থ)", "অভাব, অপ্রতুলতা বা দুষ্প্রাপ্যতা", ["Scarcity", "Lack", "Shortage", "Paucity"], ["Abundance", "Surfeit", "Plethora"], "There is a dearth of skilled workers in the technological sector.", "প্রযুক্তি খাতে দক্ষ শ্রমিকের তীব্র অভাব রয়েছে।", "GRE & BCS"),
    ("Debacle", "Noun", "/deɪˈbɑː.kəl/ (ডেবাকল)", "সম্পূর্ণ পরাজয় বা আকস্মিক বিপর্যয়", ["Fiasco", "Disaster", "Collapse", "Downfall"], ["Success", "Triumph", "Victory"], "The product launch turned into an embarrassing public debacle.", "পণ্যটির বাজারজাতকরণ একটি লজ্জাজনক বিপর্যয়ে পরিণত হয়েছিল।", "GRE & Bank"),
    ("Decorum", "Noun", "/dɪˈkɔː.rəm/ (ডেকোরাম)", "শিষ্টাচার, শোভনতা বা সামাজিক ভদ্রতা", ["Propriety", "Etiquette", "Politeness", "Dignity"], ["Impropriety", "Indecency", "Rudeness"], "The court demands absolute decorum from everyone present.", "আদালত উপস্থিত সবার কাছ থেকে সম্পূর্ণ শিষ্টাচার দাবি করে।", "BCS & Bank"),
    ("Deference", "Noun", "/ˈdef.ər.əns/ (ডেফারেন্স)", "গুরুজন বা কর্তৃপক্ষের প্রতি শ্রদ্ধা ও বাধ্যতা", ["Respect", "Reverence", "Submission", "Esteem"], ["Disrespect", "Defiance", "Contempt"], "Out of deference to his grandmother, he listened quietly.", "তাঁর দাদীর প্রতি শ্রদ্ধাবোধ থেকে তিনি চুপচাপ শুনেছিলেন।", "BCS & IELTS"),
    ("Deleterious", "Adjective", "/ˌdel.ɪˈtɪə.ri.əs/ (ডেলিটেরিয়াস)", "ক্ষতিকর বা স্বাস্থ্যের জন্য হানিকর", ["Harmful", "Detrimental", "Injurious", "Adverse"], ["Beneficial", "Harmless", "Salubrious"], "Smoking has a severe deleterious effect on lung health.", "ধূমপান ফুসফুসের স্বাস্থ্যের ওপর মারাত্মক ক্ষতিকর প্রভাব ফেলে।", "GRE & BCS"),
    ("Demur", "Verb", "/dɪˈmɜːr/ (ডিমার)", "দ্বিমত পোষণ করা বা আপত্তি জানানো", ["Object", "Protest", "Hesitate", "Take exception"], ["Agree", "Accept", "Concur"], "The lawyer demurred at the judge's suggestion.", "আইনজীবী বিচারকের প্রস্তাবে আপত্তি জানিয়েছিলেন।", "GRE & BCS"),
    ("Deride", "Verb", "/dɪˈraɪd/ (ডিরাইড)", "উপহাস বা বিদ্রূপ করা", ["Mock", "Ridicule", "Scorn", "Taunt"], ["Praise", "Applaud", "Respect"], "Critics derided the author's ambitious new novel.", "সমালোচকরা লেখকের উচ্চাকাঙ্ক্ষী নতুন উপন্যাসটিকে বিদ্রূপ করেছিলেন।", "GRE & Admission"),
    ("Desiccate", "Verb", "/ˈdes.ɪ.keɪt/ (ডেসেকেট)", "শুকিয়ে শুষ্ক করা বা আর্দ্রতাশূন্য করা", ["Dehydrate", "Dry out", "Wither", "Parch"], ["Moisten", "Hydrate", "Soak"], "The hot desert air will quickly desiccate open water sources.", "মরুভূমির উত্তপ্ত বাতাস দ্রুত খোলা পানির উৎসগুলোকে শুকিয়ে ফেলবে।", "GRE & Science"),
    ("Desultory", "Adjective", "/ˈdes.əl.tər.i/ (ডেসাল্টরি)", "এলোমেলো, লক্ষ্যহীন বা পদ্ধতিহীন", ["Aimless", "Haphazard", "Random", "Discursively"], ["Methodical", "Systematic", "Focused"], "They made a desultory attempt to clean the cluttered room.", "তারা এলোমেলো ঘরটি পরিষ্কার করার একটি এলোমেলো চেষ্টা করেছিল।", "GRE & BCS"),
    ("Diatribe", "Noun", "/ˈdaɪ.ə.traɪb/ (ডায়াট্রাইব)", "তীব্র আক্রমণাত্মক বক্তৃতা বা গালিগালাজ", ["Harangue", "Tirade", "Denunciation", "Invective"], ["Praise", "Eulogy", "Tribute"], "The candidate delivered a fierce diatribe against his opponent.", "প্রার্থী তাঁর প্রতিদ্বন্দ্বীর বিরুদ্ধে একটি তীব্র আক্রমণাত্মক বক্তব্য দিয়েছিলেন।", "GRE & BCS"),
    ("Diffident", "Adjective", "/ˈdɪf.ɪ.dənt/ (ডিফিডেন্ট)", "আত্মবিশ্বাসের অভাবযুক্ত বা লাজুক", ["Shy", "Timid", "Bashful", "Modest"], ["Confident", "Bold", "Audacious"], "The diffident child hesitated to speak in front of the class.", "আত্মবিশ্বাসহীন শিশুটি ক্লাসের সামনে কথা বলতে দ্বিধা করেছিল।", "BCS & GRE"),
    ("Dilatory", "Adjective", "/ˈdɪl.ə.tər.i/ (ডিলেটরি)", "দীর্ঘসূত্রী বা সময়ক্ষেপণকারী", ["Delaying", "Procrastinating", "Slow", "Tardy"], ["Prompt", "Expeditious", "Punctual"], "The court warned the lawyer against using dilatory tactics.", "আদালত আইনজীবীকে সময়ক্ষেপণকারী কৌশল ব্যবহার না করার সতর্কবাণী দিয়েছিল।", "GRE & Law"),
    ("Dilettante", "Noun", "/ˌdɪl.əˈtæn.ti/ (ডিলেটান্টি)", "শখ করে বিদ্যাচর্চাকারী অপেশাদার ব্যক্তিত্ব", ["Amateur", "Dabbler", "Nonprofessional"], ["Professional", "Master", "Expert"], "He is not a serious historian, just an interested dilettante.", "তিনি কোনো সিরিয়াস ইতিহাসবিদ নন, কেবল শখের বশে চর্চাকারী একজন অপেশাদার।", "GRE & Admission"),
    ("Disparate", "Adjective", "/ˈdɪs.pər.ət/ (ডিসপ্যারেট)", "মূলগতভাবে অসদৃশ বা সম্পূর্ণ ভিন্ন", ["Different", "Diverse", "Dissimilar", "Unrelated"], ["Similar", "Homogeneous", "Identical"], "The team brought together experts from highly disparate fields.", "দলটি সম্পূর্ণ ভিন্ন ক্ষেত্রের বিশেষজ্ঞদের একত্র করেছিল।", "GRE & BCS"),
    ("Dissemble", "Verb", "/dɪˈsem.bəl/ (ডিসেম্বল)", "প্রকৃত ভাবনা বা উদ্দেশ্য গোপন রাখা", ["Disguise", "Conceal", "Feign", "Simulate"], ["Reveal", "Manifest", "Disclose"], "He tried to dissemble his disappointment with a forced smile.", "তিনি একটি কৃত্রিম হাসির মাধ্যমে তাঁর হতাশা গোপন রাখার চেষ্টা করেছিলেন।", "GRE & BCS"),
    ("Dogmatic", "Adjective", "/dɒɡˈmæt.ɪk/ (ডগম্যাটিক)", "স্বৈরাচারী মতবাদে অন্ধ বা গোঁড়া", ["Opinionated", "Doctrinaire", "Rigid", "Imperious"], ["Flexible", "Open-minded", "Broad-minded"], "The professor's dogmatic teaching style discouraged student debate.", "অধ্যাপকের গোঁড়া শিক্ষাদান পদ্ধতি শিক্ষার্থীদের বিতর্ককে নিরুৎসাহিত করেছিল।", "GRE & BCS"),
    ("Duplicity", "Noun", "/dʒuːˈplɪs.ə.ti/ (ডিউপ্লিসিটি)", "দ্বিমুখী আচরণ বা শঠতা", ["Deceitfulness", "Double-dealing", "Dishonesty", "Treachery"], ["Honesty", "Sincerity", "Frankness"], "Her duplicity was exposed when the hidden emails were found.", "লুকানো ইমেলগুলো পাওয়া যাওয়ার পর তাঁর দ্বিমুখী স্বভাব উন্মোচিত হয়েছিল।", "BCS & Bank"),

    # E
    ("Ebullient", "Adjective", "/ɪˈbʊl.i.ənt/ (ইবুলিয়েন্ট)", "উচ্ছ্বসিত, প্রাণবন্ত বা অতিউৎসাহী", ["Exuberant", "Buoyant", "Enthusiastic", "Lively"], ["Depressed", "Somber", "Apathetic"], "The victory put the team in an ebullient mood.", "এই বিজয় দলটিকে এক চরম উচ্ছ্বসিত মেজাজে এনে দিয়েছিল।", "GRE & IELTS"),
    ("Eclectic", "Adjective", "/ɪˈklek.tɪk/ (ইক্লেকটিক)", "বিভিন্ন উৎস থেকে সংগৃহীত বা বহুমুখী", ["Diverse", "Varied", "Wide-ranging", "Comprehensive"], ["Narrow", "Monolithic", "Uniform"], "Her taste in music is eclectic, ranging from jazz to classical.", "সঙ্গীতে তাঁর পছন্দ বহুমুখী, যা জ্যাজ থেকে ক্লাসিক্যাল পর্যন্ত বিস্তৃত।", "GRE & Admission"),
    ("Efficacy", "Noun", "/ˈef.ɪ.kə.si/ (এফিক্যাসি)", "কাঙ্ক্ষিত ফলাফল আনার দক্ষতা বা কার্যকারিতা", ["Effectiveness", "Potency", "Success", "Utility"], ["Inefficacy", "Ineffectiveness", "Uselessness"], "Clinical trials verified the safety and efficacy of the new vaccine.", "ক্লিনিক্যাল ট্রায়ালগুলোতে নতুন ভ্যাকসিনের নিরাপত্তা ও কার্যকারিতা যাচাই করা হয়েছে।", "BCS & Science"),
    ("Effrontery", "Noun", "/ɪˈfrʌn.tər.i/ (ইফ্রন্ট্রি)", "নির্লজ্জ স্পর্ধা বা বেয়াদবি", ["Audacity", "Impudence", "Boldness", "Insolence"], ["Timidity", "Modesty", "Respect"], "He had the effrontery to demand a raise after showing up late daily.", "প্রতিদিন দেরিতে আসার পরও তাঁর বেতন বৃদ্ধির দাবি করার মতো নির্লজ্জ স্পর্ধা ছিল।", "GRE & BCS"),
    ("Elegy", "Noun", "/ˈel.ə.dʒi/ (এলেজি)", "শোকগাথা বা বিয়োগান্তক কবিতা", ["Lament", "Dirge", "Requiem", "Threnody"], ["Paean", "Panegyric", "Joyful song"], "The poet wrote a touching elegy in memory of his departed friend.", "কবি তাঁর প্রয়াত বন্ধুর স্মরণে একটি হৃদয়স্পর্শী শোকগাথা লিখেছিলেন।", "BCS & Literature"),
    ("Elicit", "Verb", "/ɪˈlɪs.ɪt/ (ইলিসিট)", "তথ্য বা প্রতিক্রিয়া বের করে আনা", ["Evoke", "Extract", "Draw out", "Obtain"], ["Suppress", "Hide", "Stifle"], "The detective managed to elicit a confession from the suspect.", "গোয়েন্দা সন্দেহভাজন ব্যক্তির কাছ থেকে স্বীকারোক্তি বের করে আনতে সক্ষম হয়েছিলেন।", "BCS & Bank"),
    ("Embellish", "Verb", "/ɪmˈbel.ɪʃ/ (এমবেলিশ)", "অলঙ্কৃত করা বা কথা বাড়িয়ে রঞ্জিত করা", ["Adorn", "Decorate", "Exaggerate", "Garnish"], ["Simplify", "Deface", "Strip"], "He tended to embellish his travel stories to entertain listeners.", "শ্রোতাদের বিনোদন দিতে তিনি তাঁর ভ্রমণের গল্পগুলো রঞ্জিত করে বলতে পছন্দ করতেন।", "BCS & IELTS"),
    ("Emulate", "Verb", "/ˈem.jə.leɪt/ (এমুলেট)", "অনুকরণ করে সমকক্ষ হওয়ার চেষ্টা করা", ["Imitate", "Copy", "Rival", "Mirror"], ["Neglect", "Ignore"], "Young musicians often strive to emulate their legendary icons.", "তরুণ শিল্পীরা প্রায়শই তাদের কিংবদন্তি আইকনদের অনুকরণ করার চেষ্টা করে।", "IELTS & Admission"),
    ("Enervate", "Verb", "/ˈen.ə.veɪt/ (এনারভেট)", "দুর্বল বা শক্তিহীন করা", ["Weaken", "Debilitate", "Exhaust", "Fatigue"], ["Strengthen", "Energize", "Invigorate"], "The intense tropical heat enervated the foreign tourists.", "তীব্র গ্রীষ্মমণ্ডলীয় তাপ বিদেশী পর্যটকদের দুর্বল করে ফেলেছিল।", "GRE & BCS"),
    ("Enigma", "Noun", "/ɪˈnɪɡ.mə/ (এনিগমা)", "রহস্যময় চরিত্র বা দুর্বোধ্য বিষয়", ["Mystery", "Puzzle", "Conundrum", "Riddle"], ["Clarity", "Expliciteness"], "The Mona Lisa's smile remains a fascinating enigma.", "মোনালিসার হাসি এখনও এক চমৎকার রহস্য হিসেবে রয়ে গেছে।", "IELTS & GRE"),
    ("Ephemeral", "Adjective", "/ɪˈfem.ər.əl/ (ইফেমারাল)", "ক্ষণস্থায়ী বা অল্প সময় স্থায়ী", ["Transient", "Fleeting", "Short-lived", "Evanescent"], ["Permanent", "Enduring", "Eternal"], "Fame in the internet age can often be surprisingly ephemeral.", "ইন্টারনেটের যুগে খ্যাতি প্রায়শই আশ্চর্যজনকভাবে ক্ষণস্থায়ী হতে পারে।", "GRE & IELTS"),
    ("Equivocate", "Verb", "/ɪˈkwɪv.ə.keɪt/ (ইকুইভোকেট)", "সন্দেহ এড়াতে অসচ্ছ বা গোলমেলে উত্তর দেওয়া", ["Prevaricate", "Hedge", "Evade", "Quibble"], ["Speak clearly", "Be direct"], "The politician continued to equivocate when asked about taxes.", "কর সম্পর্কে জিজ্ঞাসা করা হলে রাজনীতিবিদ গোলমেলে উত্তর দিতে থাকেন।", "GRE & BCS"),
    ("Erudite", "Adjective", "/ˈer.ʊ.daɪt/ (এরুডাইট)", "গভীর জ্ঞানসম্পন্ন ও পাণ্ডিত্যপূর্ণ", ["Scholarly", "Learned", "Knowledgeable", "Cultured"], ["Ignorant", "Uneducated", "Illiterate"], "The erudite professor authored several foundational textbooks.", "পাণ্ডিত্যপূর্ণ অধ্যাপক বহু মৌলিক পাঠ্যপুস্তক রচনা করেছিলেন।", "GRE & BCS"),
    ("Esoteric", "Adjective", "/ˌiː.səˈter.ɪk/ (এসোটেরিক)", "অতি গুটিকয়েক মানুষের জন্য সহজবোধ্য ও জটিলাকার", ["Abstruse", "Recondite", "Arcane", "Obscure"], ["Exoteric", "Common", "Familiar"], "Quantum physics concepts can seem esoteric to the general public.", "কোয়ান্টাম পদার্থবিজ্ঞানের ধারণাগুলো সাধারণ মানুষের কাছে অতি জটিল মনে হতে পারে।", "GRE & Admission"),
    ("Exacerbate", "Verb", "/ɪɡˈzæs.ə.beɪt/ (ইগজাসারবেট)", "পরিস্থিতি বা ক্ষোভ আরও খারাপ বা তিক্ত করা", ["Aggravate", "Worsen", "Inflame", "Exasperate"], ["Alleviate", "Mitigate", "Soothe"], "Interrupting the negotiation will only exacerbate the conflict.", "আলোচনায় বাধা দেওয়া কেবল সংঘাতকে আরও উস্কে দেবে।", "GRE & BCS"),
    ("Exculpate", "Verb", "/ˈek.skʌl.peɪt/ (এক্সকালপেট)", "অভিযোগ বা দোষ থেকে মুক্তি দেওয়া", ["Absolve", "Exonerate", "Vindicate", "Acquit"], ["Incriminate", "Blame", "Convict"], "New DNA testing exculpated the wrongfully accused prisoner.", "নতুন ডিএনএ পরীক্ষা অন্যায়ভাবে অভিযুক্ত বন্দীকে নির্দোষ প্রমাণিত করেছে।", "GRE & Law"),
    ("Exigent", "Adjective", "/ˈek.sɪ.dʒənt/ (এক্সিজেন্ট)", "জরুরি, সংকটময় ও তাৎক্ষণিক মনোযোগদাবী", ["Urgent", "Critical", "Pressing", "Imperative"], ["Unimportant", "Trivial", "Nonurgent"], "The exigent circumstances required immediate government intervention.", "জরুরি পরিস্থিতি সরকারের তাৎক্ষণিক হস্তক্ষেপের দাবি জানিয়েছিল।", "GRE & BCS"),

    # F
    ("Facetious", "Adjective", "/fəˈsiː.ʃəs/ (ফাসিশাস)", "অনুপযুক্ত স্থানে ঠাট্টা বা তামাশাপূর্ণ", ["Flippant", "Jocular", "Wagish", "Frivolous"], ["Serious", "Solemn", "Earnest"], "His facetious remarks during the emergency meeting angered the team.", "জরুরি সভায় তাঁর তামাশাপূর্ণ মন্তব্য দলটিকে ক্ষুব্ধ করেছিল।", "GRE & BCS"),
    ("Fastidious", "Adjective", "/fæsˈtɪd.i.əs/ (ফ্যাসটিডিয়াস)", "খুঁতখুঁতে, খামখেয়ালীভাবে পরিচ্ছন্ন ও অতি সতর্ক", ["Meticulous", "Fussy", "Punctilious", "Scrupulous"], ["Careless", "Sloppy", "Negligent"], "The curator was fastidious about preserving the fragile manuscripts.", "সংরক্ষক ভঙ্গুর পান্ডুলিপিগুলো সুরক্ষার বিষয়ে অত্যন্ত খুঁতখুঁতে ছিলেন।", "BCS & Bank"),
    ("Fervid", "Adjective", "/ˈfɜː.vɪd/ (ফারভিড)", "উত্তপ্ত বা তীব্র আবেগপূর্ণ", ["Passionate", "Ardent", "Fervent", "Impassioned"], ["Apathetic", "Indifferent", "Cool"], "She delivered a fervid speech advocating for environmental rights.", "তিনি পরিবেশগত অধিকারের পক্ষে এক তীব্র আবেগপূর্ণ বক্তব্য দিয়েছিলেন।", "GRE & BCS"),
    ("Furtive", "Adjective", "/ˈfɜː.tɪv/ (ফার্টিভ)", "চোরের মতো গোপনে বা অলক্ষ্যে কৃত", ["Stealthy", "Surreptitious", "Secretive", "Sly"], ["Overt", "Open", "Candid"], "The thief exchanged a furtive glance with his partner.", "চোরটি তার সহযোগীর সাথে এক গোপন চোর চোর দৃষ্টি বিনিময় করেছিল।", "BCS & GRE"),

    # G
    ("Garrulous", "Adjective", "/ˈɡær.əl.əs/ (গ্যারুলাস)", "বাচাল বা অনর্থক অতিরিক্ত কথা বলা", ["Talkative", "Loquacious", "Voluble", "Chatty"], ["Taciturn", "Reticent", "Reserved"], "The garrulous passenger kept talking throughout the entire train journey.", "বাচাল যাত্রীটি পুরো ট্রেন ভ্রমণ জুড়ে কথা বলেই চলেছিল।", "BCS & GRE"),
    ("Gregarious", "Adjective", "/ɡrɪˈɡeə.ri.əs/ (গ্রিগেরিয়াস)", "সঙ্গপ্রিয় বা সামাজিক মেলামেশা পছন্দকারী", ["Sociable", "Outgoing", "Friendly", "Companionable"], ["Reclusive", "Solitary", "Introverted"], "As a gregarious person, he enjoys organizing community events.", "সঙ্গপ্রিয় ব্যক্তি হিসেবে তিনি সামাজিক অনুষ্ঠানের আয়োজন উপভোগ করেন।", "BCS & Bank"),
    ("Guile", "Noun", "/ɡaɪl/ (গাইল)", "ধূর্ততা, চাতুরী বা প্রতারণাপূর্ণ চালাকি", ["Cunning", "Craftiness", "Deceit", "Duplicity"], ["Honesty", "Candor", "Naivety"], "The fox used supreme guile to escape the hunter's trap.", "শেয়ালটি শিকারির ফাঁদ থেকে বাঁচতে পরম চাতুরী ব্যবহার করেছিল।", "BCS & GRE"),

    # H
    ("Hackneyed", "Adjective", "/ˈhæk.nid/ (হ্যাকনিড)", "অতিরিক্ত ব্যবহারের ফলে জরাজীর্ণ বা বস্তাপচা", ["Trite", "Clichéd", "Banal", "Commonplace"], ["Fresh", "Original", "Novel"], "The plot suffered from hackneyed tropes seen in a dozen other movies.", "গল্পটি ডজনখানেক অন্যান্য মুভিতে দেখা বস্তাপচা ধারণায় ক্লিষ্ট ছিল।", "GRE & Admission"),
    ("Harangue", "Noun", "/həˈræŋ/ (হ্যার্যাং)", "তীব্র আক্রমণাত্মক ভাষণ বা ভর্ৎসনামূলক বক্তব্য", ["Tirade", "Diatribe", "Rant", "Lecture"], ["Tribute", "Praise"], "The manager launched into a harangue about the team's missed targets.", "ব্যবস্থাপক দলের মিস করা লক্ষ্যমাত্রা নিয়ে ভর্ৎসনামূলক বক্তব্য শুরু করেছিলেন।", "GRE & BCS"),
    ("Hedonism", "Noun", "/ˈhiː.dən.ɪz.əm/ (হেডনিজমে)", "ভোগবাদ বা কেবল দৈহিক সুখ-স্বাচ্ছন্দ্য অনুসন্ধান", ["Pleasure-seeking", "Sensualism", "Debauchery"], ["Asceticism", "Abstinence", "Self-denial"], "His early life was characterized by unrestrained hedonism.", "তাঁর প্রারম্ভিক জীবন অনিয়ন্ত্রিত ভোগবাদে পরিপূর্ণ ছিল।", "GRE & Admission"),

    # I
    ("Iconoclast", "Noun", "/aɪˈkɒn.ə.klæst/ (আইকনোক্লাস্ট)", "প্রচলিত ঐতিহ্য বা কুসংস্কার ভঙ্গকারী", ["Rebel", "Dissenter", "Nonconformist", "Heretic"], ["Conformist", "Traditionalist"], "The artist was an iconoclast who challenged classical aesthetics.", "শিল্পী ছিলেন একজন প্রথাভঙ্গকারী যিনি শাস্ত্রীয় নন্দনতত্ত্বকে চ্যালেঞ্জ করেছিলেন।", "GRE & BCS"),
    ("Immutable", "Adjective", "/ɪˈmjuː.tə.bəl/ (ইমিউটেবল)", "পরিবর্তনহীন বা অপরিবর্তনীয়", ["Unchangeable", "Permanent", "Fixed", "Steadfast"], ["Mutable", "Variable", "Flexible"], "Natural physical laws govern the universe in immutable ways.", "প্রাকৃতিক ভৌত নিয়মগুলো অপরিবর্তনীয় উপায়ে বিশ্বকে পরিচালনা করে।", "GRE & Science"),
    ("Impair", "Verb", "/ɪmˈpeər/ (ইম্পেয়ার)", "ক্ষতিগ্রস্ত বা কার্যক্ষমতা হ্রাস করা", ["Weaken", "Damage", "Harm", "Diminish"], ["Improve", "Enhance", "Repair"], "Lack of sleep can severely impair driving ability.", "ঘুমের অভাব গাড়ি চালানোর ক্ষমতা মারাত্মকভাবে ক্ষতিগ্রস্ত করতে পারে।", "IELTS & BCS"),
    ("Impetuous", "Adjective", "/ɪmˈpetʃ.u.əs/ (ইমপেচুয়াস)", "পরিণাম চিন্তা না করে তড়িঘড়ি কাজ করা", ["Impulsive", "Rash", "Reckless", "Hasty"], ["Cautious", "Prudent", "Calculated"], "His impetuous spending habits led him into financial trouble.", "তাঁর অবিবেচকমূলক খরচের অভ্যাস তাঁকে আর্থিক সংকটে ফেলেছিল।", "BCS & GRE"),
    ("Inchoate", "Adjective", "/ɪnˈkəʊ.eɪt/ (ইনকোয়েট)", "প্রাথমিক পর্যায়ভুক্ত বা অগঠিত", ["Rudimentary", "Incomplete", "Formless", "Emerging"], ["Mature", "Developed", "Complete"], "She held an inchoate plan that needed further refinement.", "তাঁর একটি প্রাথমিক অগঠিত পরিকল্পনা ছিল যার আরও পরিমার্জন প্রয়োজন ছিল।", "GRE & BCS"),
    ("Inimical", "Adjective", "/ɪˈnɪm.ɪ.kəl/ (ইনিমিক্যাল)", "শত্রুভাবাপন্ন বা হানিকর", ["Hostile", "Harmful", "Adverse", "Antagonistic"], ["Friendly", "Favorable", "Beneficial"], "High interest rates are inimical to small business growth.", "উচ্চ সুদের হার ক্ষুদ্র ব্যবসার প্রবৃদ্ধির জন্য ক্ষতিকর।", "GRE & Bank"),
    ("Insipid", "Adjective", "/ɪnˈsɪp.ɪd/ (ইনসিপিড)", "বিস্বাদ বা নীরস ও নিস্তেজ", ["Bland", "Tasteless", "Dull", "Uninteresting"], ["Piquant", "Flavorful", "Exciting"], "The soup was insipid because it lacked sufficient salt.", "পর্যাপ্ত লবণের অভাবে স্যুপটি বিস্বাদ লাগছিল।", "GRE & Admission"),
    ("Intransigent", "Adjective", "/ɪnˈtræn.sɪ.dʒənt/ (ইনট্রানসিজেন্ট)", "অনমনীয়, আপসহীন বা একগুঁয়ে", ["Uncompromising", "Obstinate", "Stubborn", "Inflexible"], ["Pliable", "Yielding", "Flexible"], "The union remained intransigent during negotiations.", "আলোচনার সময় ইউনিয়ন আপসহীন ছিল।", "GRE & BCS"),

    # J - L
    ("Jettison", "Verb", "/ˈdʒet.ɪ.sən/ (জেটিসন)", "বোঝা কমাতে কিছু বর্জন বা ফেলে দেওয়া", ["Discard", "Dump", "Abandon", "Cast off"], ["Retain", "Keep", "Maintain"], "The company had to jettison non-essential projects during the crisis.", "সংকটকালে কোম্পানিটিকে অপ্রয়োজনীয় প্রকল্পগুলো বর্জন করতে হয়েছিল।", "GRE & Bank"),
    ("Laconic", "Adjective", "/ləˈkɒn.ɪk/ (ল্যাকোনিক)", "অল্প কথায় অর্থপূর্ণ ভাব প্রকাশকারী", ["Terse", "Concise", "Brief", "Taciturn"], ["Verbose", "Wordy", "Garrulous"], "His laconic reply conveyed complete disagreement.", "তাঁর স্বল্পভাষী জবাবটি পূর্ণ দ্বিমত প্রকাশ করেছিল।", "BCS & GRE"),
    ("Laudable", "Adjective", "/ˈlɔː.də.bəl/ (লডেবল)", "প্রশংসনীয় বা প্রশংসার যোগ্য", ["Praiseworthy", "Commendable", "Admirable", "Meritorious"], ["Blameworthy", "Contemptible"], "Her efforts to help homeless families were truly laudable.", "গৃহহীন পরিবারগুলোকে সাহায্য করার তাঁর প্রচেষ্টা সত্যিই প্রশংসনীয় ছিল।", "BCS & IELTS"),
    ("Loquacious", "Adjective", "/ləˈkweɪ.ʃəs/ (লোকওয়েশাস)", "বাচাল বা অতিরিক্ত কথা বলতে পছন্দ করে এমন", ["Talkative", "Garrulous", "Voluble"], ["Reserved", "Reticent", "Taciturn"], "The loquacious host kept the guests entertained all night.", "বাচাল হোস্ট পুরো রাত অতিথিদের মাতিয়ে রেখেছিলেন।", "BCS & GRE"),
    ("Lucid", "Adjective", "/ˈluː.sɪd/ (লুসিড)", "সহজবোধ্য, পরিষ্কার বা সুস্থ মস্তিষ্কের", ["Clear", "Intelligible", "Coherent", "Transparent"], ["Confused", "Obscure", "Vague"], "The teacher gave a lucid explanation of the complex theory.", "শিক্ষক জটিল তত্ত্বটির একটি সহজবোধ্য ব্যাখ্যা দিয়েছিলেন।", "BCS & IELTS"),

    # M
    ("Magnanimous", "Adjective", "/mæɡˈnæn.ɪ.məs/ (ম্যাগনানিমাস)", "মহানুভব বা শত্রুর প্রতিও উদারপ্রকৃতির", ["Generous", "Forgiving", "Noble", "Big-hearted"], ["Petty", "Vindictive", "Mean"], "He was magnanimous in victory and praised his opponents.", "তিনি বিজয়ে মহানুভব ছিলেন এবং প্রতিদ্বন্দ্বীদের প্রশংসা করেছিলেন।", "BCS & GRE"),
    ("Malevolent", "Adjective", "/məˈlev.əl.ənt/ (মালেভোলেন্ট)", "পরাশ্রয়ী বা পরশ্রীকাতর ক্ষতিসাধনকারী", ["Spiteful", "Malicious", "Hostile", "Vindictive"], ["Benevolent", "Kind", "Good-natured"], "The rumor was spread with malevolent intent.", "গুজবটি ক্ষতিসাধন করার উদ্দেশ্যে ছড়ানো হয়েছিল।", "BCS & GRE"),
    ("Malleable", "Adjective", "/ˈmæl.i.ə.bəl/ (ম্যালিয়েবল)", "পিটিয়ে নমনীয় করা যায় এমন বা সহজে প্রভাবিতকরণযোগ্য", ["Pliable", "Ductile", "Flexible", "Adaptable"], ["Rigid", "Inflexible", "Stiff"], "Gold is a highly malleable metal used in jewelry.", "সোনা একটি অত্যন্ত নমনীয় ধাতু যা অলংকারে ব্যবহৃত হয়।", "BCS & Science"),
    ("Maverick", "Noun", "/ˈmæv.ər.ɪk/ (ম্যাভেরিক)", "স্বতন্ত্র চিন্তার মানুষ যে নিয়ম মানে না", ["Individualist", "Nonconformist", "Rebel"], ["Conformist", "Traditionalist"], "As a political maverick, he frequently voted against his party line.", "একজন স্বতন্ত্র চিন্তার রাজনীতিপ্রবণ ব্যক্তি হিসেবে তিনি প্রায়ই নিজ দলের বিরুদ্ধে ভোট দিতেন।", "GRE & Admission"),
    ("Mendacious", "Adjective", "/menˈdeɪ.ʃəs/ (মেনডেশাস)", "মিথ্যাবাদী বা সত্যবর্জিত", ["Untruthful", "Deceitful", "Lying", "False"], ["Truthful", "Veracious", "Honest"], "The court rejected the mendacious statement given by the witness.", "আদালত সাক্ষীর দেওয়া মিথ্যা বক্তব্য প্রত্যাখ্যান করেছিল।", "GRE & Law"),
    ("Meticulous", "Adjective", "/məˈtɪk.jə.ləs/ (মেটিকিউলাস)", "অতি সতর্ক ও খুঁটিনাটি বিষয়ে সতর্ক দৃষ্টিসম্পন্ন", ["Painstaking", "Fastidious", "Scrupulous", "Thorough"], ["Careless", "Slothful", "Sloppy"], "He paid meticulous attention to every detail of the design.", "তিনি নকশার প্রতিটি খুঁটিনাটি বিষয়ে অত্যন্ত সতর্ক নজর দিয়েছিলেন।", "BCS & IELTS"),
    ("Mollify", "Verb", "/ˈmɒl.ɪ.faɪ/ (মলিফাই)", "ক্রোধ প্রশমিত বা শান্ত করা", ["Appease", "Placating", "Pacify", "Soothe"], ["Enrage", "Provoke", "Exacerbate"], "The manager offered a refund to mollify the angry customer.", "ব্যবস্থাপক ক্রুদ্ধ গ্রাহককে শান্ত করতে অর্থ ফেরতের প্রস্তাব দিয়েছিলেন।", "GRE & BCS"),

    # N - O
    ("Neophyte", "Noun", "/ˈniː.ə.faɪt/ (নিওফাইট)", "কোনো কাজে নবাগত বা শিক্ষানবিস", ["Novice", "Beginner", "Tyro", "Fledgling"], ["Veteran", "Expert", "Master"], "As a neophyte in programming, he started with simple projects.", "প্রোগ্রামিংয়ে নবাগত হিসেবে তিনি সহজ প্রকল্প দিয়ে শুরু করেছিলেন।", "GRE & Admission"),
    ("Obdurate", "Adjective", "/ˈɒb.djʊə.rət/ ( অবডিউরেট)", "একগুঁয়ে, অনমনীয় বা অবাধ্য", ["Stubborn", "Obstinate", "Intransigent", "Unyielding"], ["Pliable", "Submissive", "Flexible"], "Despite all pleas, the judge remained obdurate in his decision.", "সব আকুতি সত্ত্বেও বিচারক তাঁর সিদ্ধান্তে অনমনীয় রইলেন।", "GRE & BCS"),
    ("Obsequious", "Adjective", "/əbˈsiː.kwi.əs/ (অবসেকুইয়াস)", "চাটুকার বা অতিমাত্রায় পদানতভঙ্গি প্রকাশকারী", ["Servile", "Fawning", "Sycophantic", "Subservient"], ["Domineering", "Assertive", "Arrogant"], "The obsequious assistant agreed with every word the boss said.", "চাটুকার সহকারী বসের বলা প্রতিটি কথার সাথে একমত হতো।", "GRE & BCS"),
    ("Obviate", "Verb", "/ˈɒb.vi.eɪt/ (অবভিয়েট)", "প্রয়োজনীয়তা দূর বা নিরাসন করা", ["Preclude", "Prevent", "Eliminate", "Avoid"], ["Require", "Necessitate"], "A thorough check will obviate the need for future repairs.", "একটি পুঙ্খানুপুঙ্খ পরীক্ষা ভবিষ্যতের মেরামতের প্রয়োজনীয়তা দূর করবে।", "GRE & BCS"),
    ("Onerous", "Adjective", "/ˈəʊ.nər.əs/ (ওনারাস)", "কষ্টকর, গুরুভার বা দায়িত্বপূর্ণ", ["Burdensome", "Arduous", "Taxing", "Demanding"], ["Easy", "Light", "Effortless"], "Taking care of the large estate proved to be an onerous task.", "বিশাল ভূসম্পত্তির দেখাশোনা করা একটি গুরুভার কাজ প্রমাণিত হয়েছিল।", "GRE & BCS"),
    ("Ostentatious", "Adjective", "/ˌɒs.tenˈteɪ.ʃəs/ (অস্টেনটেশাস)", "ঝাঁকজমকপূর্ণ বা লোকদেখানো", ["Showy", "Pretentious", "Flamboyant", "Gaudy"], ["Modest", "Unobtrusive", "Restrained"], "She avoided ostentatious jewelry and preferred simple designs.", "তিনি লোকদেখানো অলংকার এড়িয়ে চলতেন এবং সাধারণ নকশা পছন্দ করতেন।", "GRE & IELTS"),

    # P
    ("Paragon", "Noun", "/ˈpær.ə.ɡən/ (প্যারাগন)", "উৎকর্ষের আদর্শ প্রতীক বা মডেল", ["Epitome", "Exemplar", "Ideal", "Standard"], ["Flawed example", "Imperfect model"], "She is regarded as a paragon of virtue and leadership.", "তাঁকে পুণ্য ও নেতৃত্বের এক আদর্শ প্রতীক হিসেবে গণ্য করা হয়।", "GRE & BCS"),
    ("Pedantic", "Adjective", "/pɪˈdæn.tɪk/ (পেডান্টিক)", "নিয়মকানুনে অতি খুঁতখুঁতে পণ্ডিতি দেখায় এমন", ["Punctilious", "Fussy", "Over-exacting", "Formalistic"], ["Careless", "Informal"], "His pedantic style of editing irritated the creative writers.", "সম্পাদনায় তাঁর অতি পণ্ডিতিপূর্ণ শৈলী সৃজনশীল লেখকদের বিরক্ত করেছিল।", "GRE & Admission"),
    ("Penury", "Noun", "/ˈpen.jʊə.ri/ (পেনিউরি)", "চরম দারিদ্র্য বা নিঃস্ব অবস্থা", ["Poverty", "Destitution", "Indigence", "Privation"], ["Wealth", "Affluence", "Prosperity"], "He rose from childhood penury to become a successful industrialist.", "তিনি শৈশবের চরম দারিদ্র্য কাটিয়ে একজন সফল শিল্পপতি হয়েছিলেন।", "BCS & Bank"),
    ("Perfunctory", "Adjective", "/pəˈfʌŋk.tər.i/ (পারফাংক্টরি)", "দায়সারাভাবে বা নিয়ম রক্ষার জন্য করা", ["Cursory", "Desultory", "Automatic", "Superficial"], ["Thorough", "Careful", "Diligent"], "He gave a perfunctory nod before walking past us.", "আমাদের পাশ দিয়ে হেঁটে যাওয়ার আগে তিনি কেবল একটি দায়সারা মাথা নেড়েছিলেন।", "GRE & BCS"),
    ("Pervasive", "Adjective", "/pəˈveɪ.sɪv/ (পারভেসিভ)", "সর্বব্যাপী বা সর্বত্র ছড়িয়ে পড়ে এমন", ["Ubiquitous", "Widespread", "Omnipresent", "Pervading"], ["Limited", "Restricted", "Rare"], "Social media has a pervasive influence on modern teenagers.", "আধুনিক কিশোর-কিশোরীদের ওপর সোশ্যাল মিডিয়ার একটি সর্বব্যাপী প্রভাব রয়েছে।", "IELTS & BCS"),
    ("Pragmatic", "Adjective", "/præɡˈmæt.ɪk/ (প্র্যাগম্যাটিক)", "বাস্তবসম্মত বা প্র্যাকটিক্যাল দৃষ্টিভঙ্গি সম্পন্ন", ["Practical", "Realistic", "Sensible", "Utilitarian"], ["Idealistic", "Impractical", "Theoretical"], "We need a pragmatic approach to solve this urban traffic crisis.", "এই নগর ট্রাফিক সংকট সমাধানের জন্য আমাদের একটি বাস্তবসম্মত দৃষ্টিভঙ্গি প্রয়োজন।", "BCS & IELTS"),
    ("Precipitate", "Verb", "/prɪˈsɪp.ɪ.teɪt/ (প্রিসিপিটেট)", "হঠাৎ বা তড়িঘড়ি কোনো ঘটনা ঘটানো", ["Trigger", "Accelerate", "Hasten", "Bring about"], ["Halt", "Delay", "Retard"], "The sudden tariff increase precipitated an economic protest.", "হঠাৎ শুল্ক বৃদ্ধি একটি অর্থনৈতিক প্রতিবাদের সূচনা করেছিল।", "GRE & BCS"),
    ("Prodigal", "Adjective", "/ˈprɒd.ɪ.ɡəl/ (প্রডিগাল)", "অমিতব্যয়ী বা অপচয়কারী", ["Extravagant", "Wasteful", "Spendthrift", "Profligate"], ["Frugal", "Thrifty", "Economical"], "The prodigal heir squandered his inheritance in just a few years.", "অমিতব্যয়ী উত্তরাধিকারী মাত্র কয়েক বছরেই তাঁর সম্পদ উড়িয়ে দিয়েছিলেন।", "BCS & GRE"),
    ("Profound", "Adjective", "/prəˈfaʊnd/ (প্রফাউন্ড)", "গভীর, অর্থবহ বা অত্যন্ত প্রভাবশালী", ["Deep", "Insightful", "Intense", "Far-reaching"], ["Superficial", "Shallow", "Trivial"], "The discovery had a profound impact on medical science.", "আবিষ্কারটি চিকিৎসা বিজ্ঞানে এক গভীর প্রভাব ফেলেছিল।", "IELTS & BCS"),
    ("Proliferate", "Verb", "/prəˈlɪf.ər.eɪt/ (প্রলিফারেট)", "দ্রুত বংশবৃদ্ধি বা সখ্যায় বৃদ্ধি পাওয়া", ["Multiply", "Burgeon", "Escalate", "Mushroom"], ["Dwindle", "Decrease", "Diminish"], "Online learning platforms began to proliferate rapidly.", "অনলাইন লার্নিং প্ল্যাটফর্মগুলো দ্রুত প্রসারিত হতে শুরু করেছিল।", "BCS & GRE"),

    # R
    ("Rancor", "Noun", "/ˈræŋ.kər/ (র্যাঙ্কর)", "দীর্ঘস্থায়ী তিক্ততা বা বিদ্বেষভাব", ["Bitterness", "Animosity", "Resentment", "Malice"], ["Amity", "Harmony", "Goodwill"], "The long legal dispute left both families filled with rancor.", "দীর্ঘ আইনি বিরোধ উভয় পরিবারকে তিক্ততায় ভরিয়ে দিয়েছিল।", "BCS & GRE"),
    ("Recondite", "Adjective", "/ˈrek.ən.daɪt/ (রেকন্ডাইট)", "গূঢ়, দুর্বোধ্য বা সাধারণ মানুষের অজানা", ["Obscure", "Abstruse", "Esoteric", "Arcane"], ["Familiar", "Simple", "Clear"], "The scholar specialized in recondite ancient dialects.", "পণ্ডিত ব্যক্তিটি গূঢ় প্রাচীন উপভাষায় পারদর্শী ছিলেন।", "GRE & Admission"),
    ("Refractory", "Adjective", "/rɪˈfræk.tər.i/ (রিফ্র্যাক্টরি)", "অধ্যবসায়হীন, অবাধ্য বা অনমনীয়", ["Obstinate", "Stubborn", "Unmanageable", "Rebellious"], ["Obedient", "Manageable", "Compliant"], "The refractory child refused to obey his parents' directions.", "অবাধ্য শিশুটি তাঁর পিতামাতার দিকনির্দেশনা মানতে অস্বীকার করেছিল।", "GRE & Medical"),
    ("Repudiate", "Verb", "/rɪˈpjuː.di.eɪt/ (রিপিউডিয়েট)", "প্রত্যাখ্যান করা বা সত্যতা অস্বীকার করা", ["Reject", "Disown", "Renounce", "Disavow"], ["Accept", "Acknowledge", "Embrace"], "The politician was forced to repudiate his earlier controversial statement.", "রাজনীতিবিদকে তাঁর আগের বিতর্কিত বক্তব্য প্রত্যাখ্যান করতে বাধ্য করা হয়েছিল।", "GRE & BCS"),
    ("Reticent", "Adjective", "/ˈret.ɪ.sənt/ (রেটিসংট)", "নিজের কথা চেপে রাখা বা স্বল্পভাষী", ["Reserved", "Taciturn", "Secretive", "Uncommunicative"], ["Frank", "Outspoken", "Communicative"], "She was reticent about sharing details of her personal life.", "তিনি তাঁর ব্যক্তিগত জীবনের খুঁটিনাটি প্রকাশে স্বল্পভাষী ছিলেন।", "BCS & GRE"),
    ("Reverent", "Adjective", "/ˈrev.ər.ənt/ (রেভারেন্ট)", "গভীর শ্রদ্ধাপূর্ণ বা ভক্তিপূর্ণ", ["Respectful", "Devout", "Worshipful", "Awe-filled"], ["Irreverent", "Disrespectful"], "The visitors maintained a reverent silence inside the historic shrine.", "দর্শনার্থীরা ঐতিহাসিক মাজারের ভেতরে গভীর শ্রদ্ধাপূর্ণ নীরবতা বজায় রেখেছিলেন।", "BCS & IELTS"),

    # S
    ("Salubrious", "Adjective", "/səˈluː.bri.əs/ (স্যালুব্রিয়াস)", "স্বাস্থ্যকর বা স্বাস্থ্যোদ্দীপক", ["Healthy", "Wholesome", "Beneficial", "Hygienic"], ["Unhealthy", "Deleterious", "Insalubrious"], "The mountain air provided a salubrious environment for recovery.", "পাহাড়ের বাতাস আরোগ্যের জন্য একটি স্বাস্থ্যকর পরিবেশ জুগিয়েছিল।", "GRE & Medical"),
    ("Sanction", "Verb/Noun", "/ˈsæŋk.ʃən/ (স্যাংশন)", "অনুমোদন দেওয়া অথবা নিষেধাজ্ঞা জারি করা", ["Approve", "Authorize", "Penalty", "Ban"], ["Prohibit", "Disallow", "Reward"], "The committee voted to sanction the construction proposal.", "কমিটি নির্মাণ প্রস্তাব অনুমোদন করতে ভোট দিয়েছিল।", "BCS & Law"),
    ("Scrupulous", "Adjective", "/ˈskruː.pjə.ləs/ (স্ক্রুপুলাস)", "বিবেকবান, সৎ এবং খুঁটিনাটি বিষয়ে অত্যন্ত যত্নশীল", ["Meticulous", "Honest", "Punctilious", "Upright"], ["Careless", "Unscrupulous", "Dishonest"], "The auditor was scrupulous in checking every transaction record.", "নিরীক্ষক প্রতিটি লেনদেনের রেকর্ড যাচাইয়ে অত্যন্ত সতর্ক ছিলেন।", "BCS & Bank"),
    ("Soporific", "Adjective", "/ˌsɒp.ərˈɪf.ɪk/ (সপোরিফিক)", "ঘুম পাড়ানি বা তন্দ্রা সৃষ্টিকারী", ["Sleep-inducing", "Somnolent", "Sedative", "Monotonous"], ["Stimulating", "Exhilarating", "Energizing"], "The professor's monotonous lecture had a soporific effect.", "অধ্যাপকের একঘেয়ে বক্তব্যটি এক ঘুম পাড়ানি আবহ তৈরি করেছিল।", "GRE & Medical"),
    ("Specious", "Adjective", "/ˈspiː.ʃəs/ (স্পিশাস)", "আপাতদৃষ্টিতে সত্য মনে হলেও বাস্তবে ভুয়া বা বিভ্রান্তিকর", ["Plausible-sounding", "Misleading", "Fallacious", "Spurious"], ["Genuine", "Valid", "Authentic"], "The argument was specious and collapsed under close scrutiny.", "যুক্তিটি আপাত সত্য মনে হলেও গভীর পর্যবেক্ষণে ভেঙে পড়েছিল।", "GRE & BCS"),
    ("Sporadic", "Adjective", "/spəˈræd.ɪk/ (স্পোরাডিক)", "বিচ্ছিন্ন বা অনিয়মিত বিরতিতে ঘটে এমন", ["Occasional", "Irregular", "Intermittent", "Fitful"], ["Continuous", "Constant", "Regular"], "There were sporadic outbreaks of rain throughout the afternoon.", "বিকেল জুড়ে বিচ্ছিন্নভাবে বৃষ্টিপাত হয়েছিল।", "BCS & IELTS"),
    ("Spurious", "Adjective", "/ˈspjʊə.ri.əs/ (স্পিউরিয়াস)", "জাল, কৃত্রিম বা ভাজ করা সত্যতাশূন্য", ["Fake", "False", "Counterfeit", "Bogus"], ["Genuine", "Authentic", "Real"], "The company was fined for making spurious health claims.", "ভিত্তিহীন স্বাস্থ্যবিষয়ক দাবি করার জন্য কোম্পানিটিকে জরিমানা করা হয়েছিল।", "GRE & BCS"),
    ("Stolid", "Adjective", "/ˈstɒl.ɪd/ (স্টোলিড)", "আবেগহীন, নিস্তেজ বা সহজে বিচলিত হয় না এমন", ["Impassive", "Unemotional", "Phlegmatic", "Calm"], ["Emotional", "Excitable", "Expressive"], "He maintained a stolid facial expression throughout the trial.", "বিচার চলাকালীন তিনি আবেগহীন মুখের অভিব্যক্তি বজায় রেখেছিলেন।", "GRE & BCS"),

    # T - V
    ("Tacit", "Adjective", "/ˈtæs.ɪt/ (ট্যাসিট)", "অনুক্ত কিন্তু নীরব সম্মতিপূর্ণ", ["Implicit", "Unspoken", "Inferred", "Understood"], ["Explicit", "Stated", "Express"], "The partners had a tacit agreement never to discuss religion.", "অংশীদারদের মধ্যে ধর্ম নিয়ে আলোচনা না করার একটি নীরব সম্মতি ছিল।", "BCS & GRE"),
    ("Taciturn", "Adjective", "/ˈtæs.ɪ.tɜːn/ (ট্যাসিটার্ন)", "স্বভাবতই গম্ভীর ও স্বল্পভাষী", ["Reserved", "Reticent", "Silent", "Uncommunicative"], ["Garrulous", "Loquacious", "Talkative"], "The old fisherman was a taciturn man who rarely spoke.", "বৃদ্ধ জেলেটি ছিলেন একজন স্বল্পভাষী মানুষ যিনি খুব কমই কথা বলতেন।", "BCS & GRE"),
    ("Tenuous", "Adjective", "/ˈten.ju.əs/ (টেনুয়াস)", "ক্ষীণ, দুর্বল বা সহজে ভেঙে পড়ার মতো", ["Weak", "Flimsy", "Fragile", "Insubstantial"], ["Strong", "Solid", "Substantial"], "The thread connecting the two theories was extremely tenuous.", "দুটি তত্ত্বের মধ্যে সংযোগকারী সূত্রটি অত্যন্ত ক্ষীণ ছিল।", "GRE & IELTS"),
    ("Tirade", "Noun", "/taɪˈreɪd/ (টাইরেড)", "দীর্ঘ ও রাগান্বিত আক্রমণাত্মক বক্তব্য", ["Harangue", "Diatribe", "Rant", "Denunciation"], ["Praise", "Eulogy", "Compliment"], "He launched into an angry tirade against the service quality.", "তিনি সেবার মান নিয়ে এক ক্ষুব্ধ আক্রমণাত্মক বক্তব্য শুরু করেছিলেন।", "GRE & BCS"),
    ("Torpid", "Adjective", "/ˈtɔː.pɪd/ (টোরপিড)", "অলস, নিস্তেজ বা নিষ্ক্রিয় অবস্থায় থাকা", ["Lethargic", "Sluggish", "Inert", "Apathetic"], ["Active", "Energetic", "Vibrant"], "After the heavy meal, everyone felt completely torpid.", "ভারী খাবারের পর সবাই সম্পূর্ণ অলস ও নিস্তেজ বোধ করেছিল।", "GRE & BCS"),
    ("Transient", "Adjective", "/ˈtræn.zi.ənt/ (ট্রানজিয়েন্ট)", "ক্ষণস্থায়ী বা অল্প সময়ের অতিথি", ["Fleeting", "Temporary", "Ephemeral", "Brief"], ["Permanent", "Enduring", "Lasting"], "The town relies heavily on a transient summer population.", "শহরটি গ্রীষ্মকালীন ক্ষণস্থায়ী জনসংখ্যার ওপর দারুণভাবে নির্ভর করে।", "IELTS & GRE"),
    ("Ubiquitous", "Adjective", "/juːˈbɪk.wɪ.təs/ (ইউবিকুইটাস)", "সর্বত্র বিদ্যমান বা সর্বত্র দৃশ্যমান", ["Omnipresent", "Pervasive", "Universal", "Widespread"], ["Rare", "Scarce", "Uncommon"], "Smartphones have become ubiquitous in modem society.", "আধুনিক সমাজে স্মার্টফোন সর্বত্র বিদ্যমান হয়ে উঠেছে।", "IELTS & GRE"),
    ("Vacillate", "Verb", "/ˈvæs.ɪ.leɪt/ (ভাসিলেট)", "দ্বিধাগ্রস্ত হওয়া বা সিদ্ধান্ত দোদুল্যমান থাকা", ["Waver", "Hesitate", "Fluctuate", "Oscillate"], ["Resolute", "Decide", "Persist"], "She vacillated between studying medicine and pursuing law.", "তিনি চিকিৎসাশাস্ত্র পড়া নাকি আইন নিয়ে পড়ার দ্বন্দ্বে দ্বিধাগ্রস্ত ছিলেন।", "GRE & BCS"),
    ("Venerate", "Verb", "/ˈven.ər.eɪt/ (ভেনারেট)", "গভীর শ্রদ্ধা বা ভক্তি করা", ["Revere", "Worship", "Honor", "Esteem"], ["Despise", "Contemn", "Disrespect"], "The community continues to venerate the memory of the freedom fighter.", "সমাজ মুক্তিযোদ্ধা স্মৃতির প্রতি গভীর শ্রদ্ধা প্রকাশ করে চলেছে।", "BCS & IELTS"),
    ("Veracious", "Adjective", "/vəˈreɪ.ʃəs/ (ভ্যারেশাস)", "সত্যবাদী, নির্ভুল ও খাঁটি", ["Truthful", "Honest", "Accurate", "Valid"], ["False", "Deceitful", "Mendacious"], "She has a reputation as a highly veracious historian.", "একজন অত্যন্ত সত্যবাদী ইতিহাসবিদ হিসেবে তাঁর সুখ্যাতি রয়েছে।", "GRE & BCS"),
    ("Verbose", "Adjective", "/vəˈbəʊs/ (ভারবোস)", "শব্দবহুল বা অপ্রয়োজনীয় অতিরিক্ত শব্দে ভরা", ["Wordy", "Long-winded", "Garrulous", "Redundant"], ["Concise", "Terse", "Succinct"], "The manual was so verbose that it confused the users.", "ম্যানুয়ালটি এতটাই শব্দবহুল ছিল যে তা ব্যবহারকারীদের বিভ্রান্ত করেছিল।", "BCS & GRE"),
    ("Vex", "Verb", "/veks/ (ভেক্স)", "উত্ত্যক্ত বা বিরক্ত করা", ["Annoy", "Irritate", "Pester", "Disturb"], ["Soothe", "Placating", "Please"], "The recurring technical glitch continued to vex the development team.", "পুনরাবৃত্ত প্রযুক্তিগত ত্রুটি উন্নয়ন দলকে বিরতিহীনভাবে উত্ত্যক্ত করেছিল।", "BCS & GRE"),
    ("Volatile", "Adjective", "/ˈvɒl.ə.taɪl/ (ভোলাটাইল)", "আকস্মিক পরিবর্তনশীল বা বিস্ফোরক মেজাজের", ["Unstable", "Erratic", "Capricious", "Explosive"], ["Stable", "Constant", "Calm"], "The political situation remains highly volatile following the election.", "নির্বাচনের পর রাজনৈতিক পরিস্থিতি অত্যন্ত পরিবর্তনশীল রয়ে গেছে।", "Bank & GRE"),
    ("Zeal", "Noun", "/ziːl/ (জিল)", "প্রচণ্ড আগ্রহ, উদ্দীপনা বা উৎসাহ", ["Enthusiasm", "Passion", "Ardor", "Fervor"], ["Apathy", "Indifference", "Lethargy"], "He approached his new teaching role with immense zeal.", "তিনি অপরিসীম উৎসাহ নিয়ে তাঁর নতুন শিক্ষকতার দায়িত্বে যোগ দিয়েছিলেন।", "BCS & IELTS")
]

print(f"Base manually scripted exam items: {len(new_words_raw)}")
