package com.example.ui.screens.tools

// Standard Job Application Dropdown Options
val CV_EXAM_OPTIONS: List<String> = listOf(
    // Secondary & Higher Secondary (Individual degrees)
    "S.S.C",
    "H.S.C",
    "Dakhil",
    "Alim",
    "O-Level",
    "A-Level",
    "S.S.C (Vocational)",
    "H.S.C (Vocational)",
    "S.S.C (Business Management)",
    "H.S.C (BM / BMT)",

    // Diploma Programs
    "Diploma in Engineering",
    "Diploma in Computer Science & Technology",
    "Diploma in Electrical Engineering",
    "Diploma in Civil Engineering",
    "Diploma in Mechanical Engineering",
    "Diploma in Textile Engineering",
    "Diploma in Architecture",
    "Diploma in Nursing & Midwifery",
    "Diploma in Medical Technology",
    "Diploma in Pharmacy",
    "Diploma in Agriculture",
    "Diploma in Forestry",
    "Diploma in Commerce",
    "Diploma in Education (D.Ed)",

    // Bachelor / Graduation Degrees
    "B.B.A",
    "M.B.A",
    "B.Sc.",
    "B.Sc. Engg.",
    "B.A.",
    "B.S.S.",
    "B.Com.",
    "B.B.S.",
    "LL.B",
    "M.B.B.S.",
    "B.D.S.",
    "B.Pharm",
    "B.Arch",
    "BFA",
    "BMus",
    "B.Sc. Nursing",
    "Fazil",
    "B.Ed",
    "B.P.Ed",

    // Master / Postgraduate Degrees
    "M.Sc.",
    "M.Sc. Engg.",
    "E.M.B.A",
    "M.A.",
    "M.S.S.",
    "M.Com.",
    "M.B.S.",
    "LL.M",
    "M.Pharm",
    "MFA",
    "MPH (Master of Public Health)",
    "M.Ed",
    "Kamil",

    // Higher Postgraduate & Doctoral Level
    "Ph.D",
    "M.Phil",
    "Postgraduate Diploma (PGD)",
    "PGDHRM",
    "PGDIT",

    // Professional Certifications
    "CA (Chartered Accountant)",
    "CMA (Cost & Management Accountant)",
    "ACCA",
    "CFA",
    "PMP",
    "Others (ম্যানুয়াল ইনপুট)"
)

val CV_SUBJECT_OPTIONS: List<String> = listOf(
    // Business & Commerce
    "Management",
    "Accounting",
    "Finance",
    "Marketing",
    "Accounting & Information Systems (AIS)",
    "Finance & Banking",
    "Human Resource Management (HRM)",
    "Banking & Insurance",
    "International Business",
    "Supply Chain Management",
    "Tourism & Hospitality Management",
    "Business Administration",
    "Entrepreneurship",
    "Real Estate",

    // Arts, Humanities & Social Sciences
    "Bangla",
    "Political Science",
    "English",
    "Economics",
    "Sociology",
    "Social Work",
    "History",
    "Islamic History & Culture",
    "Philosophy",
    "International Relations",
    "Public Administration",
    "Psychology",
    "Law / Legal Studies",
    "Criminology",
    "Islamic Studies",
    "Arabic",
    "Sanskrit",
    "Pali",
    "Persian Language & Literature",
    "Urdu",
    "Anthropology",
    "Development Studies",
    "Population Sciences",
    "Disaster Management",
    "Information Science & Library Management",
    "Journalism & Mass Communication",
    "Fine Arts",
    "Drama & Dramatics",
    "Music",
    "Home Economics",

    // Science, Engineering & Technology
    "Computer Science & Engineering (CSE)",
    "Electrical & Electronic Engineering (EEE)",
    "Civil Engineering",
    "Mechanical Engineering",
    "Software Engineering",
    "Information Technology (IT)",
    "Chemical Engineering",
    "Industrial & Production Engineering (IPE)",
    "Textile Engineering",
    "Leather Engineering",
    "Materials & Metallurgical Engineering",
    "Biomedical Engineering",
    "Mechatronics Engineering",
    "Petroleum & Mining Engineering",
    "Architecture & Urban Planning",
    "Physics",
    "Applied Physics",
    "Chemistry",
    "Applied Chemistry",
    "Mathematics",
    "Applied Mathematics",
    "Statistics",
    "Statistics & Data Science",
    "Biochemistry & Molecular Biology",
    "Biotechnology & Genetic Engineering",
    "Microbiology",
    "Pharmacy",
    "Botany",
    "Zoology",
    "Soil, Water & Environment",
    "Soil Science",
    "Geography & Environment",
    "Geology",
    "Oceanography / Marine Science",
    "Environmental Science",

    // Medical & Health Sciences
    "Medicine & Surgery (MBBS)",
    "Dental Surgery (BDS)",
    "Nursing",
    "Physiotherapy",
    "Medical Laboratory Technology",
    "Public Health",
    "Nutrition & Food Science",

    // Agriculture & Veterinary Sciences
    "Agriculture / Agronomy",
    "Horticulture",
    "Fisheries / Aquaculture",
    "Veterinary Science & Animal Husbandry",
    "Food Engineering & Technology",
    "Forestry",

    // School & College Groups
    "Science (S.S.C / H.S.C)",
    "Business Studies / Commerce",
    "Humanities / Arts",
    "General",
    "Others (ম্যানুয়াল ইনপুট)"
)

val CV_INST_OPTIONS: List<String> = listOf(
    // Education Boards
    "Dhaka Education Board",
    "Rajshahi Education Board",
    "Comilla Education Board",
    "Jessore Education Board",
    "Chittagong Education Board",
    "Barisal Education Board",
    "Sylhet Education Board",
    "Dinajpur Education Board",
    "Mymensingh Education Board",
    "Technical Education Board (BTEB)",
    "Madrasah Education Board",

    // Public Universities
    "University of Dhaka (DU)",
    "Bangladesh University of Engineering and Technology (BUET)",
    "Jahangirnagar University (JU)",
    "Rajshahi University (RU)",
    "Chittagong University (CU)",
    "Shahjalal University of Science and Technology (SUST)",
    "Khulna University (KU)",
    "Khulna University of Engineering & Technology (KUET)",
    "Rajshahi University of Engineering & Technology (RUET)",
    "Chittagong University of Engineering & Technology (CUET)",
    "Dhaka University of Engineering & Technology (DUET)",
    "Jagannath University (JnU)",
    "Bangladesh Agricultural University (BAU)",
    "Sher-e-Bangla Agricultural University (SAU)",
    "Bangabandhu Sheikh Mujibur Rahman Agricultural University (BSMRAU)",
    "Bangladesh University of Professionals (BUP)",
    "Noakhali Science and Technology University (NSTU)",
    "Jashore University of Science and Technology (JUST)",
    "Begum Rokeya University, Rangpur (BRUR)",
    "Islamic University, Bangladesh (IU)",
    "Mawlana Bhashani Science and Technology University (MBSTU)",
    "Hajee Mohammad Danesh Science & Technology University (HSTU)",
    "Comilla University (CoU)",
    "Jatiya Kabi Kazi Nazrul Islam University (JKKNIU)",
    "Bangabandhu Sheikh Mujibur Rahman Science and Technology University (BSMRSTU)",
    "Barisal University (BU)",
    "Rangamati Science and Technology University (RMSTU)",
    "Pabna University of Science and Technology (PUST)",
    "Patuakhali Science and Technology University (PSTU)",
    "Sylhet Agricultural University (SAU)",
    "Chittagong Veterinary and Animal Sciences University (CVASU)",
    "Bangabandhu Sheikh Mujibur Rahman Maritime University (BSMRMU)",
    "Bangabandhu Sheikh Mujibur Rahman Aviation and Aerospace University (BSMRAAU)",
    "National University (NU)",
    "Bangladesh Open University (BOU)",
    "Islamic Arabic University (IAU)",
    "Bangabandhu Sheikh Mujib Medical University (BSMMU)",
    "Chittagong Medical University",
    "Rajshahi Medical University",
    "Sylhet Medical University",

    // Top Medical Colleges
    "Dhaka Medical College (DMC)",
    "Sir Salimullah Medical College (SSMC)",
    "Shaheed Suhrawardy Medical College",
    "Mymensingh Medical College",
    "Chittagong Medical College",
    "Rajshahi Medical College",
    "MAG Osmani Medical College, Sylhet",
    "Sher-e-Bangla Medical College, Barisal",
    "Rangpur Medical College",
    "Comilla Medical College",
    "Khulna Medical College",

    // Prominent Private Universities
    "North South University (NSU)",
    "BRAC University",
    "Ahsanullah University of Science and Technology (AUST)",
    "East West University (EWU)",
    "United International University (UIU)",
    "Independent University, Bangladesh (IUB)",
    "American International University-Bangladesh (AIUB)",
    "Daffodil International University (DIU)",
    "University of Liberal Arts Bangladesh (ULAB)",
    "Stamford University Bangladesh",
    "Southeast University (SEU)",
    "State University of Bangladesh (SUB)",
    "Green University of Bangladesh",
    "International Islamic University Chittagong (IIUC)",
    "University of Asia Pacific (UAP)",
    "International University of Business Agriculture and Technology (IUBAT)",
    "Eastern University",
    "Primeasia University",
    "Northern University Bangladesh",
    "Southern University Bangladesh",
    "Metropolitan University, Sylhet",
    "Leading University, Sylhet",
    "Sylhet International University",
    "Asian University of Bangladesh",
    "City University",
    "World University of Bangladesh",
    "Shanto-Mariam University of Creative Technology",
    "Uttara University",
    "Britannia University, Comilla",
    "University of Information Technology and Sciences (UITS)",
    "Canadian University of Bangladesh (CUB)",
    "European University of Bangladesh (EUB)",
    "Sonargaon University (SU)",
    "Bangladesh University (BU)",
    "BGMEA University of Fashion & Technology (BUFT)",
    "University of Development Alternative (UODA)",
    "Premier University, Chittagong",
    "Port City International University (PCIU)",
    "Varendra University, Rajshahi",

    // Prominent Government / National University Colleges
    "Dhaka College",
    "Eden Mohila College",
    "Government Titumir College",
    "Government Bangla College",
    "Kavi Nazrul Government College",
    "Government Shaheed Suhrawardy College",
    "Begum Badrunnesa Government Girls' College",
    "Tejgaon College",
    "Dhaka City College",
    "Lalmatia Mohila College",
    "Rajshahi College",
    "New Government Degree College, Rajshahi",
    "Rajshahi Government City College",
    "Chittagong College",
    "Government Hazi Mohammad Mohsin College, Chittagong",
    "Government City College, Chittagong",
    "Chittagong Government Women's College",
    "Ananda Mohan College, Mymensingh",
    "Carmichael College, Rangpur",
    "Govt. Edward College, Pabna",
    "Parkol Bi-Lateral High School",
    "Baraigram College, Natore",
    "Baraigram Govt. College, Natore",
    "Government B. M. College, Barisal (Brajamohan College)",
    "Government B. L. College, Khulna (Brajalal College)",
    "Azam Khan Government Commerce College, Khulna",
    "Government Majid Memorial City College, Khulna",
    "MC College, Sylhet (Muria Chand College)",
    "Sylhet Government Women's College",
    "Government Gurudayal College, Kishoreganj",
    "Government Tolaram College, Narayanganj",
    "Government Haraganga College, Munshiganj",
    "Government Devendra College, Manikganj",
    "Government Rajendra College, Faridpur",
    "Victoria College, Comilla",
    "Feni College",
    "Noakhali Government College",
    "Chandpur Government College",
    "Brahmanbaria Government College",
    "Cantonment Public College",
    "Dinajpur Government College",
    "Bogra Government College",
    "Sirajganj Government College",

    // Polytechnic & Technical Institutes
    "Dhaka Polytechnic Institute (DPI)",
    "Chittagong Polytechnic Institute (CPI)",
    "Mymensingh Polytechnic Institute",
    "Rajshahi Polytechnic Institute",
    "Khulna Polytechnic Institute",
    "Barisal Polytechnic Institute",
    "Sylhet Polytechnic Institute",
    "Rangpur Polytechnic Institute",
    "Comilla Polytechnic Institute",
    "Bogra Polytechnic Institute",
    "Jessore Polytechnic Institute",
    "Dinajpur Polytechnic Institute",
    "Pabna Polytechnic Institute",
    "Faridpur Polytechnic Institute",
    "Feni Polytechnic Institute",
    "Kushtia Polytechnic Institute",
    "Patuakhali Polytechnic Institute",
    "Graphic Arts Institute, Dhaka",
    "Bangladesh Survey Institute, Comilla",
    "National Institute of Textile Engineering and Research (NITER)",
    "Institute of Health Technology (IHT)",

    // Top International Universities
    "Oxford University",
    "Cambridge University",
    "Harvard University",
    "MIT (Massachusetts Institute of Technology)",
    "Stanford University",
    "Monash University",
    "University of Sydney",
    "Coventry University",
    "London Metropolitan University",
    "University of London",
    "National University of Singapore (NUS)",
    "Others (ম্যানুয়াল ইনপুট)"
)

val CV_YEAR_OPTIONS: List<String> = (2030 downTo 1980).map { it.toString() } + listOf("Appeared / Studying", "Others (ম্যানুয়াল ইনপুট)")

val CV_RESULT_SYS_OPTIONS: List<String> = listOf(
    "CGPA (Out of 4.0)",
    "GPA (Out of 5.0)",
    "1st Division / Class",
    "2nd Division / Class",
    "3rd Division / Class",
    "Passed / Appeared",
    "Others (ম্যানুয়াল ইনপুট)"
)
