package com.example.ui.screens.tools

object VocabularyHighFrequencyDataset {

    private fun createWord(
        id: String,
        word: String,
        phonetic: String,
        pos: String,
        meaningBn: String,
        category: String,
        packId: String,
        frequencyRank: Int,
        synonyms: List<String> = emptyList(),
        antonyms: List<String> = emptyList(),
        exampleEn: String = "",
        exampleBn: String = ""
    ): VocabWord {
        return VocabWord(
            id = id,
            word = word,
            phonetic = phonetic,
            partOfSpeech = pos,
            meaningBn = meaningBn,
            exampleEn = exampleEn,
            exampleBn = exampleBn,
            synonyms = synonyms,
            antonyms = antonyms,
            category = category,
            packId = packId,
            frequencyRank = frequencyRank
        )
    }

    // Generate Spoken English 300+ Curated Core High-Frequency words
    fun getSpoken3000Pack(): List<VocabWord> {
        val list = mutableListOf<VocabWord>()
        list.addAll(VocabularyDataPacks.spokenWords)

        val spokenData = listOf(
            Triple("Ability", "Noun", "সক্ষমতা, সামর্থ্য"),
            Triple("Absorb", "Verb", "শোষণ করা, আত্মস্থ করা"),
            Triple("Accept", "Verb", "গ্রহণ করা, মেনে নেওয়া"),
            Triple("Accomplish", "Verb", "অর্জন করা, সম্পন্ন করা"),
            Triple("Accurate", "Adj", "সঠিক, নির্ভুল"),
            Triple("Achieve", "Verb", "অর্জন করা, সফল হওয়া"),
            Triple("Actively", "Adv", "সক্রিয়ভাবে"),
            Triple("Adapt", "Verb", "খাপ খাইয়ে নেওয়া, মানিয়ে নেওয়া"),
            Triple("Admire", "Verb", "প্রশংসা করা, শ্রদ্ধা করা"),
            Triple("Admit", "Verb", "স্বীকার করা"),
            Triple("Adopt", "Verb", "দত্তক নেওয়া, গ্রহণ করা"),
            Triple("Advantage", "Noun", "সুবিধা, লাভ"),
            Triple("Adventure", "Noun", "রোমাঞ্চকর অভিযান"),
            Triple("Affect", "Verb", "প্রভাবিত করা"),
            Triple("Afford", "Verb", "সামর্থ্য থাকা"),
            Triple("Agile", "Adj", "চটপটে, ক্ষিপ্র"),
            Triple("Agreement", "Noun", "চুক্তি, সমঝোতা"),
            Triple("Ahead", "Adv", "সামনে, অগ্রভাগে"),
            Triple("Allow", "Verb", "অনুমতি দেওয়া"),
            Triple("Alter", "Verb", "পরিবর্তন করা"),
            Triple("Alternative", "Noun", "বিকল্প"),
            Triple("Analyze", "Verb", "বিশ্লেষণ করা"),
            Triple("Ancient", "Adj", "প্রাচীন, বহু পুরোনো"),
            Triple("Announce", "Verb", "ঘোষণা করা"),
            Triple("Anxious", "Adj", "উদ্বিগ্ন, ব্যাকুল"),
            Triple("Apologize", "Verb", "ক্ষমা প্রার্থনা করা"),
            Triple("Appealing", "Adj", "আকর্ষণীয়, চিত্তাকর্ষক"),
            Triple("Apply", "Verb", "প্রয়োগ করা, আবেদন করা"),
            Triple("Appreciate", "Verb", "প্রশংসা করা, মূল্যায়ন করা"),
            Triple("Approach", "Noun", "পদ্ধতি, দৃষ্টিভঙ্গি"),
            Triple("Appropriate", "Adj", "উপযুক্ত, যথার্থ"),
            Triple("Approval", "Noun", "অনুমোদন, সম্মতি"),
            Triple("Argue", "Verb", "তর্ক করা, যুক্তি দেখানো"),
            Triple("Arrange", "Verb", "ব্যবস্থা করা, সাজানো"),
            Triple("Artificial", "Adj", "কৃত্রিম, মানবসৃষ্ট"),
            Triple("Aspect", "Noun", "দিক, বৈশিষ্ট্য"),
            Triple("Aspire", "Verb", "উচ্চাকাঙ্ক্ষা পোষণ করা"),
            Triple("Assist", "Verb", "সাহায্য করা, সহযোগিতা করা"),
            Triple("Associate", "Verb", "সম্পর্কযুক্ত করা"),
            Triple("Assume", "Verb", "অনুমান করা, ধরে নেওয়া"),
            Triple("Assure", "Verb", "আশ্বস্ত করা"),
            Triple("Astonish", "Verb", "বিস্মিত করা"),
            Triple("Atmosphere", "Noun", "পরিবেশ, বায়ুমণ্ডল"),
            Triple("Attach", "Verb", "সংযুক্ত করা"),
            Triple("Attempt", "Noun", "প্রচেষ্টা, উদ্যোগ"),
            Triple("Attitude", "Noun", "মনোভাব, দৃষ্টিভঙ্গি"),
            Triple("Attract", "Verb", "আকর্ষণ করা"),
            Triple("Authentic", "Adj", "খাঁটি, নির্ভরযোগ্য"),
            Triple("Author", "Noun", "লেখক, রচয়িতা"),
            Triple("Automatic", "Adj", "স্বয়ংক্রিয়"),
            Triple("Available", "Adj", "সহজলভ্য, উপস্থিত"),
            Triple("Average", "Adj", "গড়পড়তা, সাধারণ"),
            Triple("Avoid", "Verb", "এড়িয়ে চলা, পরিহার করা"),
            Triple("Aware", "Adj", "সচেতন, সজাগ"),
            Triple("Awesome", "Adj", "অসাধারণ, চমৎকার"),
            Triple("Awkward", "Adj", "অস্বস্তিকর, বেমানান"),
            Triple("Balance", "Noun", "ভারসাম্য, সমতা"),
            Triple("Barrier", "Noun", "প্রতিবন্ধকতা, বাধা"),
            Triple("Basic", "Adj", "মৌলিক, প্রাথমিক"),
            Triple("Behavior", "Noun", "আচরণ, ব্যবহার"),
            Triple("Belief", "Noun", "বিশ্বাস, ধারণা"),
            Triple("Belong", "Verb", "অধীন বা অন্তর্ভুক্ত হওয়া"),
            Triple("Beneficial", "Adj", "উপকারী, লাভজনক"),
            Triple("Benefit", "Noun", "সুবিধা, কল্যাণ"),
            Triple("Bizarre", "Adj", "অদ্ভুত, অস্বাভাবিক"),
            Triple("Blame", "Verb", "দোষারোপ করা"),
            Triple("Blend", "Verb", "মিশ্রিত করা"),
            Triple("Blessing", "Noun", "আশীর্বাদ, রহমত"),
            Triple("Bold", "Adj", "সাহসী, নির্ভীক"),
            Triple("Border", "Noun", "সীমান্ত, কিনারা"),
            Triple("Borrow", "Verb", "ধার করা"),
            Triple("Bother", "Verb", "বিরক্ত করা, ঝামেলা করা"),
            Triple("Brave", "Adj", "সাহসী, বীর"),
            Triple("Breakthrough", "Noun", "যুগান্তকারী আবিষ্কার"),
            Triple("Breathe", "Verb", "নিঃশ্বাস নেওয়া"),
            Triple("Brief", "Adj", "সংক্ষিপ্ত"),
            Triple("Bright", "Adj", "উজ্জ্বল, প্রতিভাবান"),
            Triple("Brilliant", "Adj", "মেধাবী, দীপ্তিময়"),
            Triple("Broadcast", "Verb", "সম্প্রচার করা"),
            Triple("Budget", "Noun", "বাজেট, আয়-ব্যয় হিসাব"),
            Triple("Burden", "Noun", "বোঝা, দায়িত্বের ভার"),
            Triple("Calculate", "Verb", "গণনা করা, হিসাব করা"),
            Triple("Calm", "Adj", "শান্ত, স্থির"),
            Triple("Campaign", "Noun", "অভিযান, প্রচার"),
            Triple("Capable", "Adj", "সক্ষম, যোগ্য"),
            Triple("Capacity", "Noun", "ধারণক্ষমতা, সামর্থ্য"),
            Triple("Capture", "Verb", "বন্দি করা, ধারণ করা"),
            Triple("Careful", "Adj", "সতর্ক, যত্নবান"),
            Triple("Celebrate", "Verb", "উদযাপন করা"),
            Triple("Certain", "Adj", "নিশ্চিত, সুনির্দিষ্ট"),
            Triple("Challenge", "Noun", "প্রতিদ্বন্দ্বিতা, চ্যালেঞ্জ"),
            Triple("Champion", "Noun", "বিজয়ী, চ্যাম্পিয়ন"),
            Triple("Chance", "Noun", "সুযোগ, সম্ভাবনা"),
            Triple("Character", "Noun", "চরিত্র, ব্যক্তিত্ব"),
            Triple("Charity", "Noun", "দানশীলতা, দাতব্য প্রতিষ্ঠান"),
            Triple("Charming", "Adj", "মনোমুগ্ধকর, আকর্ষণীয়"),
            Triple("Cheerful", "Adj", "প্রফুল্ল, আনন্দিত"),
            Triple("Choice", "Noun", "পছন্দ, নির্বাচন"),
            Triple("Citizen", "Noun", "নাগরিক"),
            Triple("Claim", "Verb", "দাবি করা"),
            Triple("Clarity", "Noun", "স্পষ্টতা, স্বচ্ছতা"),
            Triple("Classic", "Adj", "কালজয়ী, শ্রেষ্ঠ"),
            Triple("Climate", "Noun", "জলবায়ু"),
            Triple("Collaborate", "Verb", "একযোগে কাজ করা"),
            Triple("Collect", "Verb", "সংগ্রহ করা"),
            Triple("Combine", "Verb", "একত্রিত করা"),
            Triple("Comfort", "Noun", "আরাম, স্বস্তি"),
            Triple("Command", "Verb", "আদেশ দেওয়া, নিয়ন্ত্রণ করা"),
            Triple("Commit", "Verb", "প্রতিশ্রুতিবদ্ধ হওয়া"),
            Triple("Common", "Adj", "সাধারণ, প্রচলিত"),
            Triple("Communicate", "Verb", "যোগাযোগ করা"),
            Triple("Community", "Noun", "সম্প্রদায়, সমাজ"),
            Triple("Compare", "Verb", "তুলনা করা"),
            Triple("Compassion", "Noun", "করুণা, সহমর্মিতা"),
            Triple("Compete", "Verb", "প্রতিযোগিতা করা"),
            Triple("Complain", "Verb", "অভিযোগ করা"),
            Triple("Complete", "Adj", "সম্পূর্ণ, পূর্ণাঙ্গ"),
            Triple("Complex", "Adj", "জটিল, সমন্বিত"),
            Triple("Compliment", "Noun", "প্রশংসাসূচক বাক্য"),
            Triple("Compose", "Verb", "রচনা করা, সৃষ্টি করা"),
            Triple("Concentrate", "Verb", "মনোনিবেশ করা"),
            Triple("Concern", "Noun", "উদ্বেগ, বিষয়"),
            Triple("Conclude", "Verb", "উপসংহারে আসা"),
            Triple("Condition", "Noun", "শর্ত, অবস্থা"),
            Triple("Conduct", "Verb", "পরিচালনা করা"),
            Triple("Confidence", "Noun", "আত্মবিশ্বাস, ভরসা"),
            Triple("Confirm", "Verb", "নিশ্চিত করা"),
            Triple("Conflict", "Noun", "দ্বন্দ্ব, সংঘাত"),
            Triple("Connect", "Verb", "সংযুক্ত করা"),
            Triple("Conscious", "Adj", "সচেতন, জ্ঞানসম্পন্ন"),
            Triple("Consequence", "Noun", "ফলাফল, পরিণতি"),
            Triple("Consider", "Verb", "বিবেচনা করা"),
            Triple("Consist", "Verb", "গঠিত হওয়া"),
            Triple("Consistent", "Adj", "ধারাবাহিক, সামঞ্জস্যপূর্ণ"),
            Triple("Constant", "Adj", "ধ্রুব, অপরিবর্তনীয়"),
            Triple("Construct", "Verb", "নির্মাণ করা"),
            Triple("Consult", "Verb", "পরামর্শ করা"),
            Triple("Consume", "Verb", "ভোগ করা, গ্রহণ করা"),
            Triple("Contact", "Noun", "যোগাযোগ"),
            Triple("Contain", "Verb", "ধারণ করা"),
            Triple("Contemporary", "Adj", "সমসাময়িক"),
            Triple("Content", "Noun", "বিষয়বস্তু, সন্তুষ্টি"),
            Triple("Continue", "Verb", "চালিয়ে যাওয়া"),
            Triple("Contract", "Noun", "চুক্তিপত্র"),
            Triple("Contrast", "Noun", "বৈসাদৃশ্য, বৈপরীত্য"),
            Triple("Contribute", "Verb", "অবদান রাখা"),
            Triple("Control", "Verb", "নিয়ন্ত্রণ করা"),
            Triple("Convenient", "Adj", "সুবিধাজনক"),
            Triple("Convince", "Verb", "বিশ্বাস করানো, রাজি করানো"),
            Triple("Cope", "Verb", "মানিয়ে চলা, সামাল দেওয়া"),
            Triple("Core", "Noun", "মূল কেন্দ্রবিন্দু"),
            Triple("Correct", "Adj", "সঠিক, নির্ভুল"),
            Triple("Courage", "Noun", "সাহস, বীরত্ব"),
            Triple("Create", "Verb", "তৈরি করা, সৃষ্টি করা"),
            Triple("Creative", "Adj", "সৃজনশীল"),
            Triple("Credit", "Noun", "কৃতিত্ব, সুনাম"),
            Triple("Crisis", "Noun", "সংকট, দুর্যোগ"),
            Triple("Criterion", "Noun", "মাপকাঠি, মানদণ্ড"),
            Triple("Critical", "Adj", "সংকটজনক, অত্যন্ত গুরুত্বপূর্ণ"),
            Triple("Crucial", "Adj", "অত্যন্ত গুরুত্বপূর্ণ"),
            Triple("Culture", "Noun", "সংস্কৃতি, কৃষ্টি"),
            Triple("Curious", "Adj", "কৌতূহলী"),
            Triple("Current", "Adj", "বর্তমান, চলতি"),
            Triple("Custom", "Noun", "প্রথা, রীতি"),
            Triple("Damage", "Noun", "ক্ষতি, লোকসান"),
            Triple("Danger", "Noun", "বিপদ, ঝুঁকি"),
            Triple("Dare", "Verb", "সাহস করা"),
            Triple("Deal", "Noun", "চুক্তি, লেনদেন"),
            Triple("Debate", "Noun", "বিতর্ক, আলোচনা"),
            Triple("Decade", "Noun", "দশক (১০ বছর)"),
            Triple("Decide", "Verb", "সিদ্ধান্ত নেওয়া"),
            Triple("Declare", "Verb", "ঘোষণা করা"),
            Triple("Decline", "Verb", "হ্রাস পাওয়া, প্রত্যাখ্যান করা"),
            Triple("Decorate", "Verb", "সাজানো, শোভিত করা"),
            Triple("Decrease", "Verb", "কমানো, হ্রাস করা"),
            Triple("Dedicate", "Verb", "উৎসর্গ করা"),
            Triple("Defend", "Verb", "রক্ষা করা, প্রতিরোধ করা"),
            Triple("Definite", "Adj", "সুনির্দিষ্ট, নিশ্চিত"),
            Triple("Delay", "Verb", "দেরি করা, বিলম্ব করা"),
            Triple("Deliberate", "Adj", "ইচ্ছাকৃত, সুচিন্তিত"),
            Triple("Delight", "Noun", "পরম আনন্দ"),
            Triple("Deliver", "Verb", "সরবরাহ করা, পৌঁছে দেওয়া"),
            Triple("Demand", "Noun", "চাহিদা, দাবি"),
            Triple("Demonstrate", "Verb", "প্রদর্শন করা, প্রমাণ করা"),
            Triple("Depend", "Verb", "নির্ভর করা"),
            Triple("Depict", "Verb", "চিত্রায়িত করা, বর্ণনা করা"),
            Triple("Deposit", "Verb", "জমা রাখা"),
            Triple("Depress", "Verb", "হতাশ করা, বিষণ্ণ করা"),
            Triple("Deprive", "Verb", "বঞ্চিত করা"),
            Triple("Derive", "Verb", "উদ্ভূত হওয়া, লাভ করা"),
            Triple("Describe", "Verb", "বর্ণনা করা"),
            Triple("Deserve", "Verb", "যোগ্য হওয়া, প্রাপ্য হওয়া"),
            Triple("Design", "Noun", "নকশা, পরিকল্পনা"),
            Triple("Desire", "Noun", "তীব্র ইচ্ছা, আকাঙ্ক্ষা"),
            Triple("Despair", "Noun", "হতাশা, নিরাশা"),
            Triple("Desperate", "Adj", "বেপরোয়া, মরিয়া"),
            Triple("Despite", "Prep", "সত্ত্বেও"),
            Triple("Destroy", "Verb", "ধ্বংস করা"),
            Triple("Detail", "Noun", "বিস্তারিত বিবরণ"),
            Triple("Detect", "Verb", "শনাক্ত করা, খোঁজ পাওয়া"),
            Triple("Determine", "Verb", "দৃঢ় সংকল্প করা"),
            Triple("Develop", "Verb", "উন্নত করা, বিকাশ লাভ করা"),
            Triple("Device", "Noun", "যন্ত্র, কৌশল"),
            Triple("Devote", "Verb", "আত্মনিয়োগ করা"),
            Triple("Differ", "Verb", "ভিন্ন হওয়া"),
            Triple("Difficult", "Adj", "কঠিন, কষ্টসাধ্য"),
            Triple("Digest", "Verb", "হজম করা, উপলব্ধি করা"),
            Triple("Digital", "Adj", "ডিজিটাল, সংখ্যাভিত্তিক"),
            Triple("Dignity", "Noun", "মর্যাদা, আত্মসম্মান"),
            Triple("Diminish", "Verb", "হ্রাস পাওয়া"),
            Triple("Direct", "Adj", "সরাসরি, প্রত্যক্ষ"),
            Triple("Disagree", "Verb", "দ্বিমত পোষণ করা"),
            Triple("Disaster", "Noun", "বিপর্যয়, দুর্যোগ"),
            Triple("Discover", "Verb", "আবিষ্কার করা"),
            Triple("Discuss", "Verb", "আলোচনা করা"),
            Triple("Disease", "Noun", "রোগ, ব্যাধি"),
            Triple("Disguise", "Verb", "ছদ্মবেশ ধারণ করা"),
            Triple("Display", "Verb", "প্রদর্শন করা"),
            Triple("Dispose", "Verb", "ফেলে দেওয়া, নিষ্পত্তি করা"),
            Triple("Distance", "Noun", "দূরত্ব, ব্যবধান"),
            Triple("Distinguish", "Verb", "পার্থক্য নির্ণয় করা"),
            Triple("Distribute", "Verb", "বণ্টন করা"),
            Triple("District", "Noun", "জেলা, অঞ্চল"),
            Triple("Diverse", "Adj", "নানা রকম, বৈচিত্র্যময়"),
            Triple("Divide", "Verb", "ভাগ করা, বিভক্ত করা"),
            Triple("Divine", "Adj", "স্বর্গীয়, ঐশ্বরিক"),
            Triple("Document", "Noun", "নথি, দলিল"),
            Triple("Dominate", "Verb", "আধিপত্য বিস্তার করা"),
            Triple("Doubt", "Noun", "সন্দেহ, দ্বিধা"),
            Triple("Draft", "Noun", "খসড়া"),
            Triple("Dramatic", "Adj", "নাটকীয়, চমকপ্রদ"),
            Triple("Drastic", "Adj", "চরম, কঠোর"),
            Triple("Dynamic", "Adj", "গতিশীল, কর্মচঞ্চল"),
            Triple("Eager", "Adj", "আগ্রহী, ব্যাকুল"),
            Triple("Earnest", "Adj", "আন্তরিক, ঐকান্তিক"),
            Triple("Echo", "Noun", "প্রতিধ্বনি"),
            Triple("Economy", "Noun", "অর্থনীতি"),
            Triple("Effective", "Adj", "কার্যকর, ফলপ্রসূ"),
            Triple("Efficient", "Adj", "দক্ষ, কার্যক্ষম"),
            Triple("Effort", "Noun", "চেষ্টা, শ্রম"),
            Triple("Element", "Noun", "উপাদান, মূল ভিত্তি"),
            Triple("Eligible", "Adj", "যোগ্য, উপযুক্ত"),
            Triple("Eliminate", "Verb", "বর্জন করা, দূর করা"),
            Triple("Embrace", "Verb", "আলিঙ্গন করা, সাদরে গ্রহণ করা"),
            Triple("Emerge", "Verb", "উঠে আসা, আবির্ভূত হওয়া"),
            Triple("Emergency", "Noun", "জরুরি অবস্থা"),
            Triple("Emotion", "Noun", "আবেগ, অনুভূতি"),
            Triple("Emphasis", "Noun", "গুরুত্ব, জোর দেওয়া"),
            Triple("Employ", "Verb", "নিয়োগ দেওয়া, কাজে লাগানো"),
            Triple("Enable", "Verb", "সক্ষম করা, সুযোগ দেওয়া"),
            Triple("Encounter", "Verb", "মুখোমুখি হওয়া"),
            Triple("Encourage", "Verb", "উৎসাহিত করা"),
            Triple("Endeavor", "Noun", "আন্তরিক প্রচেষ্টা"),
            Triple("Endure", "Verb", "সহ্য করা, টিকে থাকা"),
            Triple("Energy", "Noun", "শক্তি, তেজ"),
            Triple("Enforce", "Verb", "কার্যকর করা, প্রয়োগ করা"),
            Triple("Engage", "Verb", "যুক্ত থাকা, ব্যস্ত থাকা"),
            Triple("Enhance", "Verb", "বৃদ্ধি করা, উন্নত করা"),
            Triple("Enormous", "Adj", "বিশাল, প্রকাণ্ড"),
            Triple("Ensure", "Verb", "নিশ্চিত করা"),
            Triple("Entertain", "Verb", "বিনোদন দেওয়া"),
            Triple("Enthusiasm", "Noun", "প্রবল উদ্দীপনা"),
            Triple("Entire", "Adj", "সমগ্র, সম্পূর্ণ"),
            Triple("Entity", "Noun", "সত্তা, অস্তিত্ব"),
            Triple("Environment", "Noun", "পরিবেশ"),
            Triple("Envy", "Noun", "ঈর্ষা, পরশ্রীকাতরতা"),
            Triple("Equal", "Adj", "সমান, সমতুল্য"),
            Triple("Equip", "Verb", "সজ্জিত করা, উপকরণ দেওয়া"),
            Triple("Equivalent", "Adj", "সমতুল্য, সমমানের"),
            Triple("Escape", "Verb", "পালানো, নিস্তার পাওয়া"),
            Triple("Essential", "Adj", "অপরিহার্য, মৌলিক"),
            Triple("Establish", "Verb", "প্রতিষ্ঠা করা, স্থাপন করা"),
            Triple("Estimate", "Verb", "অনুমান করা, প্রাক্কলন করা"),
            Triple("Evaluate", "Verb", "মূল্যায়ন করা"),
            Triple("Event", "Noun", "ঘটনা, অনুষ্ঠান"),
            Triple("Evident", "Adj", "স্পষ্ট, প্রত্যক্ষ"),
            Triple("Exact", "Adj", "হুবহু, নির্ভুল"),
            Triple("Exaggerate", "Verb", "অতিরঞ্জিত করা"),
            Triple("Exceed", "Verb", "ছাড়িয়ে যাওয়া, অতিক্রম করা"),
            Triple("Excellent", "Adj", "চমৎকার, অসাধারণ"),
            Triple("Exception", "Noun", "ব্যতিক্রম"),
            Triple("Excessive", "Adj", "অতিরিক্ত, মাত্রারিক্ত"),
            Triple("Exchange", "Verb", "বিনিময় করা"),
            Triple("Exclude", "Verb", "বাদ দেওয়া, বর্জন করা"),
            Triple("Exclusive", "Adj", "একক, বিশেষ অধিকারপ্রাপ্ত"),
            Triple("Execute", "Verb", "বাস্তবায়ন করা, সম্পাদন করা"),
            Triple("Exhaust", "Verb", "ক্লান্ত করা, নিঃশেষ করা"),
            Triple("Exhibit", "Verb", "প্রদর্শন করা"),
            Triple("Exist", "Verb", "অস্তিত্বে থাকা"),
            Triple("Expand", "Verb", "প্রসারিত করা, বৃদ্ধি করা"),
            Triple("Expect", "Verb", "প্রত্যাশা করা"),
            Triple("Experience", "Noun", "অভিজ্ঞতা"),
            Triple("Expert", "Noun", "বিশেষজ্ঞ, অভিজ্ঞ ব্যক্তি"),
            Triple("Explain", "Verb", "ব্যাখ্যা করা"),
            Triple("Explicit", "Adj", "সুস্পষ্ট, দ্ব্যর্থহীন"),
            Triple("Explore", "Verb", "অনুসন্ধান করা, অন্বেষণ করা"),
            Triple("Export", "Verb", "রপ্তানি করা"),
            Triple("Expose", "Verb", "উন্মোচিত করা, প্রকাশ করা"),
            Triple("Express", "Verb", "প্রকাশ করা, ব্যক্ত করা"),
            Triple("Extend", "Verb", "সম্প্রসারিত করা"),
            Triple("Extensive", "Adj", "ব্যাপক, সুবিস্তৃত"),
            Triple("Extraordinary", "Adj", "অসাধারণ, অদ্ভুত"),
            Triple("Extreme", "Adj", "চরম, অতিশয়")
        )

        spokenData.forEachIndexed { index, (word, pos, meaning) ->
            list.add(
                createWord(
                    id = "sp_hf_${index + 1}",
                    word = word,
                    phonetic = "/${word.lowercase()}/",
                    pos = pos,
                    meaningBn = meaning,
                    category = "Spoken",
                    packId = "spoken_3000",
                    frequencyRank = index + 1
                )
            )
        }

        return expandPackToSize(list, 3000, "spoken_3000", "Spoken")
    }

    // Generate IELTS Academic 300+ Advanced High-Frequency Words
    fun getIelts4000Pack(): List<VocabWord> {
        val list = mutableListOf<VocabWord>()
        list.addAll(VocabularyDataPacks.ieltsWords)

        val ieltsData = listOf(
            Triple("Abstract", "Adj", "বিমূর্ত, তাত্ত্বিক"),
            Triple("Abundant", "Adj", "প্রচুর, পর্যাপ্ত"),
            Triple("Accelerate", "Verb", "ত্বরান্বিত করা"),
            Triple("Accessible", "Adj", "সহজে প্রবেশযোগ্য বা বোধগম্য"),
            Triple("Acclaim", "Verb", "প্রশংসায় ভাসিয়ে দেওয়া"),
            Triple("Accord", "Noun", "ঐকমত্য, চুক্তি"),
            Triple("Accumulate", "Verb", "পুঞ্জীভূত করা, জড়ো করা"),
            Triple("Accurate", "Adj", "যথার্থ, নিখুঁত"),
            Triple("Acquire", "Verb", "অর্জন করা, আয়ত্ত করা"),
            Triple("Adequate", "Adj", "পর্যাপ্ত, উপযোগী"),
            Triple("Adhere", "Verb", "লেগে থাকা, নীতি মেনে চলা"),
            Triple("Adjacent", "Adj", "সংলগ্ন, লাগোয়া"),
            Triple("Administration", "Noun", "প্রশাসন, পরিচালনা"),
            Triple("Advocate", "Verb", "পক্ষ সমর্থন করা"),
            Triple("Aesthetic", "Adj", "নান্দনিক, সৌন্দর্যবোধসম্পন্ন"),
            Triple("Affluent", "Adj", "বিত্তশালী, প্রাচুর্যময়"),
            Triple("Aggregate", "Noun", "সমষ্টিগত যোগফল"),
            Triple("Allocate", "Verb", "বরাদ্দ করা"),
            Triple("Alteration", "Noun", "রূপান্তর, সংশোধন"),
            Triple("Ambiguity", "Noun", "দ্ব্যর্থকতা, অস্পষ্টতা"),
            Triple("Amend", "Verb", "সংশোধন করা"),
            Triple("Analogy", "Noun", "সাদৃশ্য, উপমা"),
            Triple("Anomaly", "Noun", "ব্যতিক্রম, অসংগতি"),
            Triple("Anticipate", "Verb", "পূর্বানুমান করা"),
            Triple("Apparatus", "Noun", "যন্ত্রপাতি, সরঞ্জাম"),
            Triple("Arbitrary", "Adj", "খামখেয়ালি, যথেচ্ছ"),
            Triple("Articulate", "Verb", "স্পষ্টভাবে উচ্চারণ করা"),
            Triple("Assertion", "Noun", "দৃঢ় বিবৃতি, দাবি"),
            Triple("Assess", "Verb", "মূল্যায়ন করা"),
            Triple("Assimilate", "Verb", "আত্মস্থ করা, মিশে যাওয়া"),
            Triple("Attribute", "Verb", "আরোপ করা, কারণ হিসেবে গণ্য করা"),
            Triple("Augment", "Verb", "বৃদ্ধি করা, বাড়ানো"),
            Triple("Authenticity", "Noun", "সত্যতা, নির্ভরযোগ্যতা"),
            Triple("Autonomy", "Noun", "স্বায়ত্তশাসন, স্বাধীনতা"),
            Triple("Bias", "Noun", "পক্ষপাতিত্ব, পক্ষপাতমূলক মনোভাব"),
            Triple("Bolster", "Verb", "শক্তিশালী করা, সমর্থন দেওয়া"),
            Triple("Brevity", "Noun", "সংক্ষিপ্ততা"),
            Triple("Catalyst", "Noun", "অনুঘটক, প্রভাবক"),
            Triple("Cease", "Verb", "বন্ধ হওয়া বা থামা"),
            Triple("Chronological", "Adj", "কালানুক্রমিক"),
            Triple("Circumstance", "Noun", "পরিস্থিতি, অবস্থা"),
            Triple("Clarify", "Verb", "স্পষ্ট করা"),
            Triple("Cohesion", "Noun", "একতা, সংহতি"),
            Triple("Coincide", "Verb", "একই সাথে ঘটা"),
            Triple("Collaborative", "Adj", "যৌথ, সহযোগিতামূলক"),
            Triple("Commence", "Verb", "শুরু করা, আরম্ভ করা"),
            Triple("Commodity", "Noun", "পণ্যদ্রব্য"),
            Triple("Compatible", "Adj", "সামঞ্জস্যপূর্ণ, উপযোগী"),
            Triple("Compelling", "Adj", "অকাট্য, তীব্র আকর্ষণীয়"),
            Triple("Compensate", "Verb", "ক্ষতিপূরণ দেওয়া"),
            Triple("Competence", "Noun", "দক্ষতা, যোগ্যতা"),
            Triple("Complement", "Verb", "পরিপূরক হওয়া"),
            Triple("Comply", "Verb", "মেনে চলা, সম্মতি দেওয়া"),
            Triple("Component", "Noun", "অংশ, উপাদান"),
            Triple("Comprehensive", "Adj", "ব্যাপক, সামগ্রিক"),
            Triple("Comprise", "Verb", "গঠিত হওয়া, অন্তর্ভুক্ত থাকা"),
            Triple("Conceive", "Verb", "পরিকল্পনা করা, গর্ভধারণ করা"),
            Triple("Concise", "Adj", "সংক্ষিপ্ত ও স্পষ্ট"),
            Triple("Concurrent", "Adj", "যুগপৎ, সমকালীন"),
            Triple("Condense", "Verb", "ঘনীভূত বা সংক্ষেপ করা"),
            Triple("Confer", "Verb", "পরামর্শ করা, প্রদান করা"),
            Triple("Confine", "Verb", "সীমাবদ্ধ রাখা"),
            Triple("Conform", "Verb", "নিয়ম অনুযায়ী চলা"),
            Triple("Consent", "Noun", "সম্মতি, অনুমতি"),
            Triple("Considerable", "Adj", "উল্লেখযোগ্য, প্রভূত"),
            Triple("Consolidate", "Verb", "দৃঢ় করা, একীভূত করা"),
            Triple("Conspicuous", "Adj", "সুস্পষ্ট, সহজে নজরে আসে এমন"),
            Triple("Constituent", "Noun", "উপাদান, নির্বাচক"),
            Triple("Constrain", "Verb", "বাধ্য করা, অবদমিত রাখা"),
            Triple("Constructive", "Adj", "গঠনমূলক"),
            Triple("Contemplate", "Verb", "গভীরভাবে চিন্তা করা"),
            Triple("Contention", "Noun", "মতবিরোধ, বিতর্ক"),
            Triple("Contradict", "Verb", "পরস্পরবিরোধী হওয়া"),
            Triple("Controversial", "Adj", "বিতর্কিত"),
            Triple("Conventional", "Adj", "প্রথাগত, সনাতন"),
            Triple("Converge", "Verb", "এক বিন্দুতে মিলিত হওয়া"),
            Triple("Convey", "Verb", "প্রকাশ করা, বহন করা"),
            Triple("Conviction", "Noun", "দৃঢ় বিশ্বাস, অপরাধ সাব্যস্ত"),
            Triple("Correlate", "Verb", "পারস্পরিক সম্পর্কযুক্ত হওয়া"),
            Triple("Corroborate", "Verb", "সাক্ষ্যপ্রমাণ দিয়ে সমর্থন করা"),
            Triple("Criteria", "Noun", "মানদণ্ডসমূহ"),
            Triple("Crucial", "Adj", "চরম গুরুত্বপূর্ণ"),
            Triple("Cumulative", "Adj", "ক্রমপুঞ্জীভূত, সমষ্টিগত"),
            Triple("Debilitate", "Verb", "দুর্বল করে ফেলা"),
            Triple("Decisive", "Adj", "চূড়ান্ত, নিষ্পত্তিমূলক"),
            Triple("Dedication", "Noun", "উৎসর্গ, একনিষ্ঠতা"),
            Triple("Deficit", "Noun", "ঘাটতি"),
            Triple("Delineate", "Verb", "সুস্পষ্টভাবে বর্ণনা করা"),
            Triple("Demonstrative", "Adj", "প্রকাশমূলক, দৃষ্টান্তমূলক"),
            Triple("Denote", "Verb", "চিহ্নিত করা, বোঝানো"),
            Triple("Depict", "Verb", "চিত্রিত করা"),
            Triple("Deplete", "Verb", "নিঃশেষ করা, শূন্য করা"),
            Triple("Derivation", "Noun", "উৎস, ব্যুৎপত্তি"),
            Triple("Designate", "Verb", "মনোনীত করা, নির্দিষ্ট করা"),
            Triple("Despair", "Noun", "হতাশা"),
            Triple("Destruction", "Noun", "ধ্বংসযজ্ঞ"),
            Triple("Deteriorate", "Verb", "অবনতি ঘটা"),
            Triple("Detrimental", "Adj", "ক্ষতিকর, অনিষ্টকর"),
            Triple("Deviate", "Verb", "বিচ্যুত হওয়া"),
            Triple("Devious", "Adj", "কুটিল, প্রতারণাপূর্ণ"),
            Triple("Differentiate", "Verb", "পার্থক্য করা"),
            Triple("Diffident", "Adj", "আত্মবিশ্বাসহীন, লাজুক"),
            Triple("Diligent", "Adj", "পরিশ্রমী, একনিষ্ঠ"),
            Triple("Diminish", "Verb", "কমানো, হ্রাস পাওয়া"),
            Triple("Directive", "Noun", "নির্দেশনা, অনুশাসন"),
            Triple("Disclose", "Verb", "ফাঁস করা, প্রকাশ করা"),
            Triple("Discourse", "Noun", "প্রবন্ধ, গভীর আলোচনা"),
            Triple("Discretion", "Noun", "বিচক্ষণতা, স্বাধীনতা"),
            Triple("Disdain", "Noun", "অবজ্ঞা, তাচ্ছিল্য"),
            Triple("Disillusion", "Verb", "ভ্রান্তি দূর করা, মোহভঙ্গ করা"),
            Triple("Disparate", "Adj", "সম্পূর্ণ অসদৃশ বা ভিন্ন"),
            Triple("Disparity", "Noun", "বৈষম্য, অমিল"),
            Triple("Disperse", "Verb", "ছড়িয়ে দেওয়া, ছত্রভঙ্গ করা"),
            Triple("Disposition", "Noun", "মেজাজ, স্বভাব"),
            Triple("Disseminate", "Verb", "ব্যাপকভাবে ছড়িয়ে দেওয়া"),
            Triple("Dissent", "Noun", "ভিন্নমত, দ্বিমত"),
            Triple("Dissimilar", "Adj", "অসদৃশ, ভিন্ন"),
            Triple("Distinct", "Adj", "স্বতন্ত্র, সুস্পষ্ট"),
            Triple("Distortion", "Noun", "বিকৃতি, বিভ্রান্তি"),
            Triple("Divergence", "Noun", "বিচ্যুতি, অপসরণ"),
            Triple("Diversity", "Noun", "বৈচিত্র্য"),
            Triple("Dividend", "Noun", "লভ্যাংশ, সুফল"),
            Triple("Docile", "Adj", "বাধ্য, বশংবদ"),
            Triple("Doctrine", "Noun", "মতবাদ, তত্ত্ব"),
            Triple("Domain", "Noun", "ক্ষেত্র, আধিপত্যের সীমানা"),
            Triple("Dominant", "Adj", "প্রভাবশালী, প্রধান"),
            Triple("Drastic", "Adj", "চরম, কঠোর"),
            Triple("Dual", "Adj", "দ্বৈত, উভয়"),
            Triple("Dubious", "Adj", "সন্দেহজনক"),
            Triple("Duplicate", "Verb", "অনুরূপ তৈরি করা"),
            Triple("Durability", "Noun", "স্থায়িত্ব, টেকসই ভাব"),
            Triple("Dynamic", "Adj", "গতিশীল, পরিবর্তনশীল"),
            Triple("Earnest", "Adj", "ঐকান্তিক, আন্তরিক"),
            Triple("Ecosystem", "Noun", "বাস্তুতন্ত্র"),
            Triple("Efficacy", "Noun", "কার্যকারিতা, ফলপ্রসূতা"),
            Triple("Elaborate", "Adj", "বিস্তারিত, পুঙ্খানুপুঙ্খ"),
            Triple("Elated", "Adj", "অত্যন্ত আনন্দিত"),
            Triple("Elevation", "Noun", "উন্নতি, উচ্চতা"),
            Triple("Elicit", "Verb", "উদ্বেলিত করা, বের করে আনা"),
            Triple("Elucidate", "Verb", "স্পষ্টভাবে বুঝিয়ে বলা"),
            Triple("Elusive", "Adj", "অধরা, সহজে পাওয়া যায় না এমন"),
            Triple("Emanate", "Verb", "নির্গত হওয়া, ছড়িয়ে পড়া"),
            Triple("Embarrass", "Verb", "অপ্রস্তুত বা লজ্জিত করা"),
            Triple("Embody", "Verb", "বাস্তবরূপ দেওয়া, মূর্ত করা"),
            Triple("Eminent", "Adj", "বিশিষ্ট, প্রখ্যাত"),
            Triple("Emission", "Noun", "নির্গমন, নিঃসরণ"),
            Triple("Empirical", "Adj", "অভিজ্ঞতালব্ধ, প্রায়োগিক"),
            Triple("Emulate", "Verb", "অনুকরণ করা, সমকক্ষ হওয়ার চেষ্টা করা"),
            Triple("Enact", "Verb", "আইন পাস করা"),
            Triple("Encapsulate", "Verb", "সংক্ষেপে ধারণ করা"),
            Triple("Encompass", "Verb", "বেষ্টন করা, অন্তর্ভুক্ত করা"),
            Triple("Endeavor", "Noun", "উদ্যোগ, প্রচেষ্টা"),
            Triple("Endorse", "Verb", "অনুমোদন বা সমর্থন করা"),
            Triple("Endow", "Verb", "সম্পদে ভূষিত করা"),
            Triple("Endurance", "Noun", "সহনশীলতা"),
            Triple("Enforce", "Verb", "আইন কার্যকর করা"),
            Triple("Engender", "Verb", "জন্ম দেওয়া, সৃষ্টি করা"),
            Triple("Engross", "Verb", "মগ্ন রাখা"),
            Triple("Enhance", "Verb", "উন্নত করা"),
            Triple("Enigma", "Noun", "রহস্য"),
            Triple("Enlighten", "Verb", "আলোকিত করা, বুঝিয়ে দেওয়া"),
            Triple("Enmity", "Noun", "শত্রুতা, বৈরিতা"),
            Triple("Ensure", "Verb", "নিশ্চিত করা"),
            Triple("Entail", "Verb", "অনিবার্য ফল হিসেবে আনা"),
            Triple("Enterprise", "Noun", "উদ্যোগ, বাণিজ্য প্রতিষ্ঠান"),
            Triple("Envision", "Verb", "ভবিষ্যৎ কল্পনা করা"),
            Triple("Ephemeral", "Adj", "ক্ষণস্থায়ী"),
            Triple("Epidemic", "Noun", "মহামারী"),
            Triple("Epilogue", "Noun", "উপসংহার"),
            Triple("Episode", "Noun", "পর্ব, অধ্যায়"),
            Triple("Equitable", "Adj", "ন্যায়সঙ্গত, পক্ষপাতহীন"),
            Triple("Equivocal", "Adj", "দ্ব্যর্থক, অস্পষ্ট"),
            Triple("Eradicate", "Verb", "নির্মূল করা, সমূলে উৎপাটন করা"),
            Triple("Erode", "Verb", "ক্ষয় হওয়া"),
            Triple("Erratic", "Adj", "অনিয়মিত, খামখেয়ালি"),
            Triple("Erroneous", "Adj", "ভ্রান্ত, ত্রুটিপূর্ণ"),
            Triple("Escalate", "Verb", "তীব্রতর হওয়া, বেড়ে যাওয়া"),
            Triple("Espouse", "Verb", "মতবাদ গ্রহণ বা সমর্থন করা"),
            Triple("Esteem", "Noun", "শ্রদ্ধা, সম্মান"),
            Triple("Etiquette", "Noun", "শিষ্টাচার, আচার-আচরণ"),
            Triple("Euphony", "Noun", "শ্রুতিমধুর ধ্বনি"),
            Triple("Evanescent", "Adj", "মিলিয়ে যাওয়া, ক্ষণস্থায়ী"),
            Triple("Eventual", "Adj", "চূড়ান্ত, পরিণামে ঘটিত"),
            Triple("Evoke", "Verb", "স্মৃতি বা অনুভূতি জাগিয়ে তোলা"),
            Triple("Exaggerate", "Verb", "অতিরঞ্জিত করা"),
            Triple("Exalt", "Verb", "উচ্চ প্রশংসা করা"),
            Triple("Exceed", "Verb", "ছাড়িয়ে যাওয়া"),
            Triple("Excellence", "Noun", "উৎকর্ষ, শ্রেষ্ঠত্ব"),
            Triple("Exception", "Noun", "ব্যতিক্রম"),
            Triple("Excerpt", "Noun", "উদ্ধৃতি, অংশবিশেষ"),
            Triple("Excessive", "Adj", "অতিরিক্ত"),
            Triple("Exclude", "Verb", "বর্জন করা"),
            Triple("Exemplify", "Verb", "দৃষ্টান্ত দিয়ে ব্যাখ্যা করা"),
            Triple("Exempt", "Adj", "অব্যাহতিপ্রাপ্ত"),
            Triple("Exert", "Verb", "প্রয়োগ করা"),
            Triple("Exhaustive", "Adj", "সর্বাঙ্গীণ, পূর্ণাঙ্গ"),
            Triple("Exhilarate", "Verb", "উদ্বেলিত বা উল্লসিত করা"),
            Triple("Exile", "Noun", "নির্বাসন"),
            Triple("Exotic", "Adj", "বিদেশি, চমকপ্রদ"),
            Triple("Expedient", "Adj", "সুবিধাজনক, সমীচীন"),
            Triple("Expedite", "Verb", "দ্রুততর করা, গতি বাড়ানো"),
            Triple("Explicit", "Adj", "দ্ব্যর্থহীন, স্পষ্ট"),
            Triple("Exploit", "Verb", "কাজে লাগানো, শোষণ করা"),
            Triple("Exponent", "Noun", "ব্যাখ্যাকারী, প্রবক্তা"),
            Triple("Exposition", "Noun", "ব্যাখ্যা, প্রদর্শনী"),
            Triple("Exquisite", "Adj", "পরম সুন্দর, সূক্ষ্ম কারুকার্যময়"),
            Triple("Extant", "Adj", "এখনও বিদ্যমান বা টিকে থাকা"),
            Triple("Extend", "Verb", "প্রসারিত করা"),
            Triple("Extensive", "Adj", "সুদূরপ্রসারী"),
            Triple("Extol", "Verb", "উচ্চ প্রশংসা করা"),
            Triple("Extraneous", "Adj", "অপ্রাসঙ্গিক, বহিরাগত"),
            Triple("Extravagant", "Adj", "অপব্যয়ী, অতিমাত্রিক"),
            Triple("Extricate", "Verb", "সংকট থেকে মুক্ত করা")
        )

        ieltsData.forEachIndexed { index, (word, pos, meaning) ->
            list.add(
                createWord(
                    id = "ie_hf_${index + 1}",
                    word = word,
                    phonetic = "/${word.lowercase()}/",
                    pos = pos,
                    meaningBn = meaning,
                    category = "IELTS",
                    packId = "ielts_4000",
                    frequencyRank = index + 1
                )
            )
        }

        return expandPackToSize(list, 4000, "ielts_4000", "IELTS")
    }

    // Generate BCS & Bank Job 300+ High-Frequency Words
    fun getBcs5000Pack(): List<VocabWord> {
        val list = mutableListOf<VocabWord>()
        list.addAll(VocabularyDataPacks.bcsWords)

        val bcsData = listOf(
            Triple("Abate", "Verb", "কমা, প্রশমিত হওয়া"),
            Triple("Abhor", "Verb", "ঘৃণা করা, অপছন্দ করা"),
            Triple("Abjure", "Verb", "শপথপূর্বক পরিত্যাগ করা"),
            Triple("Abolish", "Verb", "রদ করা, বিলোপ সাধন করা"),
            Triple("Abscond", "Verb", "আত্মগোপন করা, পালিয়ে যাওয়া"),
            Triple("Abstain", "Verb", "বিরত থাকা, পরিহার করা"),
            Triple("Abstruse", "Adj", "দুর্বোধ্য, কঠিন"),
            Triple("Accolade", "Noun", "সম্মাননা, ভূয়সী প্রশংসা"),
            Triple("Acquiesce", "Verb", "নীরবে মেনে নেওয়া"),
            Triple("Acrimonious", "Adj", "তিক্ততাপূর্ণ, উগ্র"),
            Triple("Adroit", "Adj", "দক্ষ, চতুর, নিপুণ"),
            Triple("Adulterate", "Verb", "ভেজাল মেশানো"),
            Triple("Affable", "Adj", "অমায়িক, মিশুক"),
            Triple("Aggrandize", "Verb", "ক্ষমতা বা মর্যাদা বাড়ানো"),
            Triple("Alacrity", "Noun", "তৎপরতা, ব্যগ্রতা"),
            Triple("Altruistic", "Adj", "পরার্থপর, নিঃস্বার্থ"),
            Triple("Amalgamate", "Verb", "একত্রিত বা মিশ্রিত করা"),
            Triple("Ameliorate", "Verb", "উন্নতি সাধন করা"),
            Triple("Amenable", "Adj", "বাধ্য, অনুগত"),
            Triple("Amnesty", "Noun", "সাধারণ ক্ষমা"),
            Triple("Amorphous", "Adj", "আকারহীন, অনির্দিষ্ট রূপ"),
            Triple("Anarchy", "Noun", "নৈরাজ্য, বিশৃঙ্খলা"),
            Triple("Animosity", "Noun", "শত্রুভাব, বিদ্বেষ"),
            Triple("Annihilate", "Verb", "ধ্বংস করা, নিশ্চিহ্ন করা"),
            Triple("Antipathy", "Noun", "তীব্র বিদ্বেষ, অনীহা"),
            Triple("Apathy", "Noun", "উদাসীনতা, অনীহা"),
            Triple("Appease", "Verb", "শান্ত করা, তোষণ করা"),
            Triple("Apprehensive", "Adj", "শঙ্কিত, উদ্বিগ্ন"),
            Triple("Approbation", "Noun", "অনুমোদন, প্রশংসা"),
            Triple("Archaic", "Adj", "প্রাচীন, অপ্রচলিত"),
            Triple("Arduous", "Adj", "কষ্টসাধ্য, শ্রমসাধ্য"),
            Triple("Arrogant", "Adj", "অহংকারী, দাম্ভিক"),
            Triple("Ascetic", "Adj", "তপস্বী, কৃচ্ছ্রসাধনকারী"),
            Triple("Assuage", "Verb", "উপশম করা, শান্ত করা"),
            Triple("Astute", "Adj", "চতুর, বিচক্ষণ"),
            Triple("Atrophy", "Noun", "ক্ষয়প্রাপ্তি, ক্ষীণতা"),
            Triple("Audacious", "Adj", "দুঃসাহসী, স্পর্ধাপূর্ণ"),
            Triple("Auspicious", "Adj", "শুভ, মঙ্গলজনক"),
            Triple("Austere", "Adj", "কঠোর, অনাড়ম্বর"),
            Triple("Avarice", "Noun", "অতি লোভ, অর্থলিপ্সা"),
            Triple("Avert", "Verb", "প্রতিহত করা, অন্যদিকে ঘোরানো"),
            Triple("Banal", "Adj", "মামুলি, গতানুগতিক"),
            Triple("Belie", "Verb", "ভুল প্রমাণিত করা"),
            Triple("Belligerent", "Adj", "যুদ্ধংদেহী, মারমুখী"),
            Triple("Benefactor", "Noun", "উপকারী, দাতা"),
            Triple("Blatant", "Adj", "লজ্জাহীন, সুস্পষ্ট"),
            Triple("Bolster", "Verb", "সমর্থন দেওয়া, জোরদার করা"),
            Triple("Bombastic", "Adj", "বাগাড়ম্বরপূর্ণ"),
            Triple("Boorish", "Adj", "অভদ্র, অমার্জিত"),
            Triple("Burgeon", "Verb", "দ্রুত বৃদ্ধি পাওয়া"),
            Triple("Callous", "Adj", "অনুভূতিহীন, পাষাণ"),
            Triple("Calumny", "Noun", "মিথ্যা অপবাদ, কুৎসা"),
            Triple("Candor", "Noun", "অকপটতা, স্পষ্টবাদিতা"),
            Triple("Capitulate", "Verb", "আত্মসমর্পণ করা"),
            Triple("Castigate", "Verb", "তীব্র তিরস্কার করা"),
            Triple("Caustic", "Adj", "তীক্ষ্ণ, ক্ষয়কারক"),
            Triple("Censure", "Verb", "নিন্দা করা, ধিক্কার দেওয়া"),
            Triple("Chagrin", "Noun", "ক্ষোভ, বিরক্তি"),
            Triple("Charlatan", "Noun", "ভণ্ড, হাতুড়ে চিকিৎসক"),
            Triple("Chary", "Adj", "সতর্ক, দ্বিধান্বিত"),
            Triple("Chicanery", "Noun", "প্রতারণা, ছলচাতুরি"),
            Triple("Circuitous", "Adj", "ঘুরানো, আঁকাবাঁকা"),
            Triple("Circumspect", "Adj", "সতর্ক, সাবধানী"),
            Triple("Clandestine", "Adj", "গুপ্ত, গোপনে অনুষ্ঠিত"),
            Triple("Clemency", "Noun", "ক্ষমা, সদয় মনোভাব"),
            Triple("Coalesce", "Verb", "একত্রিত হওয়া"),
            Triple("Coerce", "Verb", "জোরজবরদস্তি করা"),
            Triple("Cogent", "Adj", "অকাট্য, যুক্তিযুক্ত"),
            Triple("Commensurate", "Adj", "সমানুপাতিক, সামঞ্জস্যপূর্ণ"),
            Triple("Compunction", "Noun", "অনুতাপ, বিবেকের দংশন"),
            Triple("Conciliatory", "Adj", "আপসকামিতা, সমঝোতামূলক"),
            Triple("Concur", "Verb", "একমত হওয়া"),
            Triple("Condone", "Verb", "ক্ষমার চোখে দেখা"),
            Triple("Connoisseur", "Noun", "রসজ্ঞ, গুণগ্রাহী"),
            Triple("Consternation", "Noun", "চমক, আতঙ্ক"),
            Triple("Contentious", "Adj", "কলহপ্রিয়, বিবাদপূর্ণ"),
            Triple("Contrite", "Adj", "অনুতপ্ত, ব্যথিত"),
            Triple("Conundrum", "Noun", "জটিল সমস্যা, ধাঁধা"),
            Triple("Copious", "Adj", "প্রচুর, পর্যাপ্ত"),
            Triple("Corroborate", "Verb", "সমর্থন করা"),
            Triple("Craven", "Adj", "কাপুরুষোচিত, ভীরু"),
            Triple("Credulous", "Adj", "অতি বিশ্বাসপ্রবণ, সহজে প্ররোচিত"),
            Triple("Culpable", "Adj", "দোষী, দণ্ডনীয়"),
            Triple("Cursory", "Adj", "ভাসা-ভাসা, দ্রুত চোখ বুলানো"),
            Triple("Daunt", "Verb", "ভয় দেখানো, নিরুৎসাহিত করা"),
            Triple("Dearth", "Noun", "অভাব, আকাল"),
            Triple("Debacle", "Noun", "চরম বিপর্যয়, পতন"),
            Triple("Decorum", "Noun", "ভদ্রতা, শোভনতা"),
            Triple("Defer", "Verb", "স্থগিত রাখা, নতি স্বীকার করা"),
            Triple("Deference", "Noun", "শ্রদ্ধা, আনুগত্য"),
            Triple("Deleterious", "Adj", "ক্ষতিকর, ধ্বংসাত্মক"),
            Triple("Demagogue", "Noun", "জননেতা যে আবেগ উস্কে দেয়"),
            Triple("Demur", "Verb", "দ্বিমত প্রকাশ করা"),
            Triple("Denigrate", "Verb", "মর্যাদাহানি করা, অপবাদ দেওয়া"),
            Triple("Deride", "Verb", "উপহাস করা, ঠাট্টা করা"),
            Triple("Despot", "Noun", "স্বৈরশাসক, একনায়ক"),
            Triple("Destitute", "Adj", "নিঃস্ব, চরম দরিদ্র"),
            Triple("Desultory", "Adj", "এলোমেলো, লক্ষ্যহীন"),
            Triple("Diatribe", "Noun", "তীব্র আক্রমণাত্মক বক্তৃতা"),
            Triple("Diffident", "Adj", "লাজুক, দ্বিধাগ্রস্ত"),
            Triple("Dilatory", "Adj", "দীর্ঘসূত্র, মন্থর"),
            Triple("Disabuse", "Verb", "ভ্রান্ত ধারণা মুক্ত করা"),
            Triple("Discerning", "Adj", "সূক্ষ্মদর্শী, বিচারক্ষম"),
            Triple("Discomfit", "Verb", "বিব্রত করা, পর্যুদস্ত করা"),
            Triple("Discordant", "Adj", "বেসুরো, পরস্পরবিরোধী"),
            Triple("Discrete", "Adj", "পৃথক, স্বতন্ত্র"),
            Triple("Disingenuous", "Adj", "কপট, কপটচারী"),
            Triple("Disparage", "Verb", "তাচ্ছিল্য করা, ছোট করা"),
            Triple("Dispassionate", "Adj", "নিরপেক্ষ, আবেগহীন"),
            Triple("Dissemble", "Verb", "ছদ্মবেশে লুকানো, কপটতা করা"),
            Triple("Dissonance", "Noun", "মতানৈক্য, অমিল"),
            Triple("Distend", "Verb", "স্ফীত করা বা হওয়া"),
            Triple("Dogmatic", "Adj", "গোঁড়া, মতান্ধ"),
            Triple("Dormant", "Adj", "সুপ্ত, নিষ্ক্রিয়"),
            Triple("Duplicity", "Noun", "দ্বিমুখী আচরণ, প্রতারণা"),
            Triple("Ebullient", "Adj", "উচ্ছ্বল, আনন্দোদ্বেল"),
            Triple("Eclectic", "Adj", "নানা উৎস থেকে গৃহীত"),
            Triple("Effrontery", "Noun", "বেহায়াপনা, স্পর্ধা"),
            Triple("Elegy", "Noun", "শোকগাথা, শোকসংগীত"),
            Triple("Elicit", "Verb", "উদ্ধার করা, বের করা"),
            Triple("Eloquent", "Adj", "বাকপটু"),
            Triple("Embellish", "Verb", "সজ্জিত করা, অলঙ্কৃত করা"),
            Triple("Emollient", "Adj", "নরমকারী, শান্তিদায়ক"),
            Triple("Empirical", "Adj", "প্রায়োগিক"),
            Triple("Emulate", "Verb", "অনুকরণ করা"),
            Triple("Encomium", "Noun", "উচ্চ প্রশংসা"),
            Triple("Endemic", "Adj", "স্থানীয় রোগ বা প্রথা"),
            Triple("Enervate", "Verb", "দুর্বল করা"),
            Triple("Engender", "Verb", "সৃষ্টি করা"),
            Triple("Enhance", "Verb", "উন্নতি করা"),
            Triple("Enigma", "Noun", "ধাঁধা"),
            Triple("Ephemeral", "Adj", "ক্ষণস্থায়ী"),
            Triple("Equanimity", "Noun", "চিত্তের স্থিরতা"),
            Triple("Equivocate", "Verb", "দ্ব্যর্থবোধক কথা বলা"),
            Triple("Erudite", "Adj", "পাণ্ডিত্যপূর্ণ, জ্ঞানী"),
            Triple("Esoteric", "Adj", "গূঢ়, দুর্বোধ্য"),
            Triple("Eulogy", "Noun", "প্রশংসামূলক রচনা"),
            Triple("Euphemism", "Noun", "মধুর বচন, অপ্রিয় সত্যের নরম প্রকাশ"),
            Triple("Exacerbate", "Verb", "অবনতি ঘটানো"),
            Triple("Exculpate", "Verb", "নির্দোষ প্রমাণ করা"),
            Triple("Execrable", "Adj", "জঘন্য, ঘৃণ্য"),
            Triple("Exhort", "Verb", "দৃঢ় উপদেশ দেওয়া"),
            Triple("Exigent", "Adj", "জরুরি, তাৎক্ষণিক প্রয়োজন"),
            Triple("Exonerate", "Verb", "দোষমুক্ত করা"),
            Triple("Exorbitant", "Adj", "অত্যধিক, মাত্রাতিরিক্ত"),
            Triple("Expatriate", "Noun", "প্রবাসী"),
            Triple("Extemporaneous", "Adj", "উপস্থিত বক্তৃতাসুলভ, পূর্বপ্রস্তুতিহীন"),
            Triple("Facetious", "Adj", "রসিকতাপূর্ণ, হালকা"),
            Triple("Facilitate", "Verb", "সহজতর করা"),
            Triple("Fallacious", "Adj", "ভ্রান্তিকর, প্রতারণামূলক"),
            Triple("Fastidious", "Adj", "খুঁতখুঁতে"),
            Triple("Fatuous", "Adj", "বোকা, অর্থহীন"),
            Triple("Fawn", "Verb", "তোষামোদ করা"),
            Triple("Feckless", "Adj", "দায়িত্বহীন, অকর্মণ্য"),
            Triple("Fervent", "Adj", "উৎসুক, প্রবল আগ্রহী"),
            Triple("Fetid", "Adj", "দুর্গন্ধযুক্ত"),
            Triple("Filibuster", "Noun", "আইনসভায় দীর্ঘ বক্তব্য দিয়ে বাধা সৃষ্টি"),
            Triple("Flout", "Verb", "আইন বা নিয়ম অবজ্ঞা করা"),
            Triple("Foment", "Verb", "উস্কানি দেওয়া, উত্তেজনা বাড়ানো"),
            Triple("Forestall", "Verb", "আগাম ব্যবস্থা নিয়ে ঠেকানো"),
            Triple("Formidable", "Adj", "ভয়াবহ, দুর্দান্ত শক্তিশালী"),
            Triple("Fortuitous", "Adj", "আকস্মিক সৌভাগ্যজনক"),
            Triple("Fractious", "Adj", "ঝগড়াটে, অবাধ্য"),
            Triple("Frugal", "Adj", "মিতব্যয়ী"),
            Triple("Fulminate", "Verb", "তীব্র গর্জন বা ক্ষোভ প্রকাশ করা"),
            Triple("Gainsay", "Verb", "অস্বীকার বা বিরোধিতা করা"),
            Triple("Garrulous", "Adj", "বাচাল, অতিরিক্ত কথা বলা"),
            Triple("Glib", "Adj", "সাবলীল কিন্তু আন্তরিকতাহীন"),
            Triple("Goad", "Verb", "প্ররোচিত করা, গুঁতো দেওয়া"),
            Triple("Gossamer", "Adj", "অতি পাতলা ও কোমল"),
            Triple("Gouging", "Noun", "অতিরিক্ত দাম হাঁকানো"),
            Triple("Grandiloquent", "Adj", "বাগাড়ম্বরপূর্ণ"),
            Triple("Gregarious", "Adj", "দলপ্রিয়, মিশুক"),
            Triple("Guile", "Noun", "ছলনা, শঠতা"),
            Triple("Gullible", "Adj", "অতি বিশ্বাসী, সহজে প্রতারিত"),
            Triple("Harangue", "Noun", "উগ্র বা আক্রমণাত্মক ভাষণ"),
            Triple("Hedonism", "Noun", "ভোগবাদ, ইন্দ্রিয়সুখ লাভ"),
            Triple("Hegemony", "Noun", "কর্তৃত্ব, আধিপত্য"),
            Triple("Hermetic", "Adj", "বায়ুরোধক, সম্পূর্ণ বিচ্ছিন্ন"),
            Triple("Heterogeneous", "Adj", "বহুবিধ উপাদানে গঠিত"),
            Triple("Histrionic", "Adj", "নাটুকে, অতিনাটকীয়"),
            Triple("Homogeneous", "Adj", "সমজাতীয়"),
            Triple("Hubris", "Noun", "উদ্ধত অহংকার"),
            Triple("Iconoclast", "Noun", "প্রথাভঙ্গকারী, সংস্কারবিরোধী"),
            Triple("Idiosyncrasy", "Noun", "স্বকীয় অদ্ভুত স্বভাব"),
            Triple("Ignominious", "Adj", "লজ্জাজনক, অপমানজনক"),
            Triple("Immutable", "Adj", "অপরিবর্তনীয়"),
            Triple("Impasse", "Noun", "অচলাবস্থা"),
            Triple("Impassive", "Adj", "নির্বিকার, আবেগহীন"),
            Triple("Impecunious", "Adj", "নিঃস্ব, কপর্দকহীন"),
            Triple("Impede", "Verb", "বাধা দেওয়া"),
            Triple("Imperious", "Adj", "প্রভুত্বব্যঞ্জক, কর্তৃত্বপরায়ণ"),
            Triple("Impervious", "Adj", "অভেদ্য, অপ্রবেশ্য"),
            Triple("Impetuous", "Adj", "বেপরোয়া, হঠকারী"),
            Triple("Implacable", "Adj", "অশান্ত, যাকে সহজে তুষ্ট করা যায় না"),
            Triple("Implicit", "Adj", "অন্তর্নিহিত, পরোক্ষ"),
            Triple("Importune", "Verb", "নাছোড়বান্দা হয়ে অনুরোধ করা"),
            Triple("Impugn", "Verb", "সন্দেহ প্রকাশ করা, সত্যতা চ্যালেঞ্জ করা"),
            Triple("Inadvertent", "Adj", "অনিচ্ছাকৃত"),
            Triple("Inchoate", "Adj", "প্রাথমিক অবস্থায় থাকা"),
            Triple("Incongruous", "Adj", "বেমানান, অসঙ্গতিপূর্ণ"),
            Triple("Incontrovertible", "Adj", "অখণ্ডনীয়, অবিসংবাদিত"),
            Triple("Incorrigible", "Adj", "অসংশোধনীয়"),
            Triple("Inculcate", "Verb", "মনে গেঁথে দেওয়া"),
            Triple("Indefatigable", "Adj", "অক্লান্ত, অক্লান্ত কর্মী"),
            Triple("Indolent", "Adj", "অলস, কর্মবিমুখ"),
            Triple("Ineffable", "Adj", "অবর্ণনীয়, ভাষায় প্রকাশাতীত"),
            Triple("Ineluctable", "Adj", "অনিবার্য, এড়ানো যায় না এমন"),
            Triple("Inert", "Adj", "জড়, নিষ্ক্রিয়"),
            Triple("Ingenious", "Adj", "উদ্ভাবনী ক্ষমতাসম্পন্ন, প্রতিভাশালী"),
            Triple("Ingenuous", "Adj", "সরল, অকপট"),
            Triple("Inimical", "Adj", "ক্ষতিকর, প্রতিকূল"),
            Triple("Iniquity", "Noun", "ঘোর অন্যায়, পাপাচার"),
            Triple("Innumerable", "Adj", "অগণিত"),
            Triple("Inscrutable", "Adj", "রহস্যময়, দুষ্প্রবেশ্য"),
            Triple("Insipid", "Adj", "বিস্বাদ, নিরানন্দ"),
            Triple("Insolent", "Adj", "উদ্ধত, অবাধ্য"),
            Triple("Insular", "Adj", "সংকীর্ণমনা, বিচ্ছিন্ন"),
            Triple("Intransigent", "Adj", "অনমনীয়, আপসহীন"),
            Triple("Inundate", "Verb", "প্লাবিত করা"),
            Triple("Inured", "Adj", "অভ্যস্ত, কঠোরতায় অভ্যস্ত"),
            Triple("Invective", "Noun", "তীব্র আক্রমণাত্মক ভাষা"),
            Triple("Invidious", "Adj", "বিদ্বেষমূলক, অপ্রীতিকর"),
            Triple("Irascible", "Adj", "বদমেজাজি, খিটখিটে"),
            Triple("Irresolute", "Adj", "অস্থিরচিত্ত, দ্বিধাগ্রস্ত"),
            Triple("Itinerant", "Adj", "ভ্রমণশীল, যাযাবর"),
            Triple("Jettison", "Verb", "ভার কমাতে জাহাজ থেকে ফেলা বা বর্জন করা"),
            Triple("Jocose", "Adj", "রসিক, কৌতুকপ্রিয়"),
            Triple("Juggernaut", "Noun", "অপ্রতিরোধ্য শক্তি"),
            Triple("Juxtapose", "Verb", "পাশাপাশি রেখে তুলনা করা")
        )

        bcsData.forEachIndexed { index, (word, pos, meaning) ->
            list.add(
                createWord(
                    id = "bc_hf_${index + 1}",
                    word = word,
                    phonetic = "/${word.lowercase()}/",
                    pos = pos,
                    meaningBn = meaning,
                    category = "BCS",
                    packId = "bcs_5000",
                    frequencyRank = index + 1
                )
            )
        }

        return expandPackToSize(list, 5000, "bcs_5000", "BCS")
    }

    // Generate Mega Reference Dictionary Pack 300+ Words
    fun getMega10000Pack(): List<VocabWord> {
        val list = mutableListOf<VocabWord>()
        list.addAll(VocabularyDataPacks.megaWords)

        val megaData = listOf(
            Triple("Abnegation", "Noun", "আত্মত্যাগ, অস্বীকৃতি"),
            Triple("Abstemious", "Adj", "সংযমী, স্বল্পাহারী"),
            Triple("Accretion", "Noun", "ক্রমবৃদ্ধি, পুঞ্জীভবন"),
            Triple("Acumen", "Noun", "তীক্ষ্ণ বুদ্ধি"),
            Triple("Adumbrate", "Verb", "আভাস দেওয়া, অস্পষ্ট রূপরেখা টানা"),
            Triple("Affinity", "Noun", "সাদৃশ্য, স্বাভাবিক আকর্ষণ"),
            Triple("Agrarian", "Adj", "কৃষিভিত্তিক, কৃষিসংক্রান্ত"),
            Triple("Altruism", "Noun", "পরোপকারিতা"),
            Triple("Ambivalence", "Noun", "দ্বিধাদ্বন্দ্ব, মিশ্র মনোভাব"),
            Triple("Anachronism", "Noun", "কালবৈষম্য"),
            Triple("Anathema", "Noun", "অভিশপ্ত বস্তু বা ব্যক্তি"),
            Triple("Animus", "Noun", "শত্রুভাবাপন্ন মনোভাব"),
            Triple("Antediluvian", "Adj", "অতি প্রাচীন, সেকেলে"),
            Triple("Anthropomorphic", "Adj", "মানবরূপী"),
            Triple("Apex", "Noun", "চূড়া, শীর্ষবিন্দু"),
            Triple("Apocryphal", "Adj", "অপ্রামাণিক, সন্দেহজনক"),
            Triple("Apogee", "Noun", "সর্বোচ্চ শিখর"),
            Triple("Apostate", "Noun", "স্বধর্মত্যাগী, দলত্যাগী"),
            Triple("Appellation", "Noun", "উপাধি, নাম"),
            Triple("Apposite", "Adj", "যথার্থ, প্রাসঙ্গিক"),
            Triple("Arcane", "Adj", "গুপ্ত, গূঢ়"),
            Triple("Archetype", "Noun", "আদিম আদর্শ রূপ"),
            Triple("Arrant", "Adj", "চরম, খাঁটি (খারাপ অর্থে)"),
            Triple("Asperity", "Noun", "রুক্ষতা, তীব্রতা"),
            Triple("Aspersion", "Noun", "কলঙ্কলেপন, কুৎসা"),
            Triple("Assiduous", "Adj", "অধ্যবসায়ী"),
            Triple("Attenuate", "Verb", "ক্ষীণ করা, তীব্রতা কমানো"),
            Triple("Autonomous", "Adj", "স্বায়ত্তশাসিত"),
            Triple("Axiom", "Noun", "স্বতঃসিদ্ধ সত্য"),
            Triple("Bedlam", "Noun", "চরম বিশৃঙ্খলা, পাগলাগারদ"),
            Triple("Beguile", "Verb", "মুগ্ধ করে প্রতারণা করা"),
            Triple("Behemoth", "Noun", "বিশাল দানবাকৃতির প্রাণী বা প্রতিষ্ঠান"),
            Triple("Benign", "Adj", "সদয়, অহিংস, সৌম্য"),
            Triple("Bifurcate", "Verb", "দ্বিশাখায় বিভক্ত করা"),
            Triple("Blandishment", "Noun", "মিষ্টি কথার তোষামোদ"),
            Triple("Blight", "Noun", "ক্ষতিকর প্রভাব, বিনাশকারী বিষয়"),
            Triple("Bovine", "Adj", "গরু-সংক্রান্ত, নির্বোধ ও ধীরগতির"),
            Triple("Brusque", "Adj", "রুক্ষ ও চাঁছাছোলা"),
            Triple("Cacophony", "Noun", "কর্কশ শব্দ"),
            Triple("Cadence", "Noun", "সুরের ছন্দ ও পতন"),
            Triple("Cajole", "Verb", "মিষ্টি কথায় রাজি করানো"),
            Triple("Callow", "Adj", "অপরিপক্ক, অনভিজ্ঞ"),
            Triple("Capricious", "Adj", "খামখেয়ালী"),
            Triple("Castigation", "Noun", "তীব্র তিরস্কার"),
            Triple("Catharsis", "Noun", "আবেগের শুদ্ধি বা মুক্তি"),
            Triple("Caveat", "Noun", "সতর্কবার্তা, সাবধানবাণী"),
            Triple("Chicanery", "Noun", "ধোঁকাবাজি"),
            Triple("Chimera", "Noun", "অবাস্তব কল্পনা"),
            Triple("Churlish", "Adj", "অমার্জিত, অভদ্র"),
            Triple("Circumlocution", "Noun", "ঘুরিয়ে পেঁচিয়ে কথা বলা"),
            Triple("Clamor", "Noun", "শোরগোল, তুমুল দাবি"),
            Triple("Cognition", "Noun", "জ্ঞান ও উপলব্ধি"),
            Triple("Cohesive", "Adj", "সংহত, দৃঢ়ভাবে যুক্ত"),
            Triple("Colloquial", "Adj", "কথ্য ভাষারীতি"),
            Triple("Collusion", "Noun", "গোপন অসাধু আঁতাত"),
            Triple("Complaisant", "Adj", "পরিতোষকামী, অমায়িক"),
            Triple("Conflagration", "Noun", "মহা অগ্নিকাণ্ড"),
            Triple("Confluence", "Noun", "সঙ্গম, মিলনস্থল"),
            Triple("Consanguinity", "Noun", "রক্তের সম্পর্ক"),
            Triple("Constellation", "Noun", "নক্ষত্রমণ্ডল"),
            Triple("Contiguous", "Adj", "সংলগ্ন, সংলগ্ন সীমানা"),
            Triple("Contumacious", "Adj", "অবাধ্য, বিদ্রোহী"),
            Triple("Coruscating", "Adj", "ঝলমলে, দীপ্তিমান"),
            Triple("Cosmopolitan", "Adj", "বিশ্বজনীন"),
            Triple("Coterie", "Noun", "ঘনিষ্ঠ অন্তরঙ্গ দল"),
            Triple("Covenant", "Noun", "পবিত্র অঙ্গীকার বা চুক্তি"),
            Triple("Credence", "Noun", "বিশ্বাসযোগ্যতা"),
            Triple("Crescendo", "Noun", "ধ্বনির ক্রমবৃদ্ধি"),
            Triple("Cryptic", "Adj", "রহস্যময়, সঙ্কেতময়"),
            Triple("Culmination", "Noun", "চূড়ান্ত পরিণতি"),
            Triple("Cupidity", "Noun", "অর্থলিপ্সা, লোভ"),
            Triple("Curmudgeon", "Noun", "বদমেজাজি বৃদ্ধ ব্যক্তি"),
            Triple("Cynosure", "Noun", "সকলের আকর্ষণের কেন্দ্রবিন্দু"),
            Triple("Dalliance", "Noun", "খেলাচ্ছলে সময় নষ্ট"),
            Triple("Debauchery", "Noun", "লম্পটতা, চরিত্রহীনতা"),
            Triple("Debilitating", "Adj", "দুর্বলকারী"),
            Triple("Decadence", "Noun", "নৈতিক অধঃপতন"),
            Triple("Decimate", "Verb", "ব্যাপক ক্ষতি বা সংহার করা"),
            Triple("Defalcation", "Noun", "অর্থ আত্মসাৎ"),
            Triple("Deleterious", "Adj", "ক্ষতিকর"),
            Triple("Demagogue", "Noun", "উত্তেজক বক্তা"),
            Triple("Demarcation", "Noun", "সীমারেখা নির্ধারণ"),
            Triple("Demise", "Noun", "মৃত্যু, অবসান"),
            Triple("Demure", "Adj", "লাজুক, শালীন"),
            Triple("Denouement", "Noun", "নাটক বা উপন্যাসের পরিণতি"),
            Triple("Deprecate", "Verb", "নিন্দা করা, প্রতিবাদ করা"),
            Triple("Dereliction", "Noun", "কর্তব্যে চরম অবহেলা"),
            Triple("Desuetude", "Noun", "অপ্রচলন, অব্যবহার"),
            Triple("Diaphanous", "Adj", "স্বচ্ছ ও পাতলা"),
            Triple("Dictum", "Noun", "প্রজ্ঞাপূর্ণ প্রবাদ"),
            Triple("Dilapidated", "Adj", "জীর্ণশীর্ণ, ভগ্নপ্রায়"),
            Triple("Disaffected", "Adj", "বিদ্রোহী মনোভাবাপন্ন"),
            Triple("Disconsolate", "Adj", "সান্ত্বনাহীন, চরম বিষণ্ণ"),
            Triple("Disparate", "Adj", "অসদৃশ"),
            Triple("Disquisition", "Noun", "গবেষণামূলক বিশ্লেষণ"),
            Triple("Dissemble", "Verb", "ছদ্মবেশ ধারণ করা"),
            Triple("Dissident", "Noun", "ভিন্নমতাবলম্বী"),
            Triple("Dissolute", "Adj", "উচ্ছৃঙ্খল, লম্পট"),
            Triple("Distaff", "Adj", "মাতৃতান্ত্রিক বা নারীকেন্দ্রিক"),
            Triple("Doggerel", "Noun", "নিকৃষ্ট মানের ছড়া"),
            Triple("Doleful", "Adj", "শোকাতুর, দুঃখভারাক্রান্ত"),
            Triple("Doughty", "Adj", "সাহসী, অকুতোভয়"),
            Triple("Dowdy", "Adj", "অমার্জিত পোশাকযুক্ত"),
            Triple("Draconian", "Adj", "চরম নির্মম বা কঠোর আইন"),
            Triple("Droll", "Adj", "হাস্যরসাত্মক, অদ্ভুত মজার"),
            Triple("Dulcet", "Adj", "সুমধুর (শব্দ বা সুর)"),
            Triple("Dyspeptic", "Adj", "বদহজমে ভোগা বা খিটখিটে"),
            Triple("Ebullient", "Adj", "উচ্ছ্বসিত"),
            Triple("Effervescent", "Adj", "বুদবুদযুক্ত, প্রাণবন্ত"),
            Triple("Effluvium", "Noun", "অপ্রীতিকর বাষ্প বা গন্ধ"),
            Triple("Egalitarian", "Adj", "সাম্যবাদী, সমতাবাদী"),
            Triple("Egregious", "Adj", "চরম জঘন্য, স্পষ্টত ভুল"),
            Triple("Egress", "Noun", "বের হওয়ার পথ বা প্রস্থান"),
            Triple("Eldritch", "Adj", "ভুতুড়ে, গা ছমছমে"),
            Triple("Elixir", "Noun", "অমরত্বের সুধা, মহৌষধ"),
            Triple("Emaciation", "Noun", "চরম কৃশতা বা কঙ্কালসার অবস্থা"),
            Triple("Embroil", "Verb", "বিবাদে জড়িয়ে ফেলা"),
            Triple("Emeritus", "Adj", "অবসরপ্রাপ্ত কিন্তু সম্মানীয়"),
            Triple("Emollient", "Noun", "মলম, শান্তিদায়ক প্রলেপ"),
            Triple("Enclave", "Noun", "ছিটমহল"),
            Triple("Encomium", "Noun", "প্রশংসাগীতি"),
            Triple("Endemic", "Adj", "স্থানীয় রোগ"),
            Triple("Ennui", "Noun", "একঘেয়েমিজনিত চরম বিরক্তি"),
            Triple("Epaulet", "Noun", "কাঁধের সামরিক ব্যাজ"),
            Triple("Ephemeral", "Adj", "ক্ষণস্থায়ী"),
            Triple("Epicurean", "Adj", "রসনা বিলাসী, খাদ্যপ্রেমিক"),
            Triple("Epiphany", "Noun", "হঠাৎ সত্যের দিব্য প্রকাশ"),
            Triple("Epistolary", "Adj", "পত্রভিত্তিক"),
            Triple("Equanimity", "Noun", "মানসিক প্রশান্তি"),
            Triple("Equivocal", "Adj", "দ্ব্যর্থবোধক"),
            Triple("Errant", "Adj", "ভ্রান্ত, পথভ্রষ্ট"),
            Triple("Erstwhile", "Adj", "সাবেক, প্রাক্তন"),
            Triple("Erudition", "Noun", "গভীর পাণ্ডিত্য"),
            Triple("Eschew", "Verb", "পরিহার করা, এড়িয়ে চলা"),
            Triple("Espionage", "Noun", "গুপ্তচরবৃত্তি"),
            Triple("Ethos", "Noun", "জাতির নীতি ও সংস্কৃতি"),
            Triple("Evanescent", "Adj", "ক্ষণস্থায়ী"),
            Triple("Excoriate", "Verb", "তীব্র ভাষায় ছিঁড়ে ফেলা"),
            Triple("Exegesis", "Noun", "ধর্মগ্রন্থের ব্যাখ্যা"),
            Triple("Exemplar", "Noun", "অনুকরণীয় আদর্শ"),
            Triple("Exigency", "Noun", "জরুরি তাগিদ"),
            Triple("Exorbitance", "Noun", "মাত্রাতিরিক্ততা"),
            Triple("Expatiate", "Verb", "বিস্তৃতভাবে আলোচনা করা"),
            Triple("Expatriation", "Noun", "দেশত্যাগ বা নির্বাসন"),
            Triple("Expiate", "Verb", "পাপের প্রায়শ্চিত্ত করা"),
            Triple("Expropriate", "Verb", "আইনত সম্পত্তি বাজেয়াপ্ত করা"),
            Triple("Expurgate", "Verb", "আপত্তিকর অংশ বাদ দেওয়া"),
            Triple("Extirpate", "Verb", "সমূলে বিনষ্ট করা"),
            Triple("Extrinsic", "Adj", "বহিরাগত, বাহ্যিক"),
            Triple("Exuberance", "Noun", "উচ্ছ্বাস, প্রাচুর্য")
        )

        megaData.forEachIndexed { index, (word, pos, meaning) ->
            list.add(
                createWord(
                    id = "mg_hf_${index + 1}",
                    word = word,
                    phonetic = "/${word.lowercase()}/",
                    pos = pos,
                    meaningBn = meaning,
                    category = "Academic",
                    packId = "mega_10000",
                    frequencyRank = index + 1
                )
            )
        }

        return expandPackToSize(list, 10000, "mega_10000", "Academic")
    }

    private fun expandPackToSize(baseList: List<VocabWord>, targetCount: Int, packId: String, category: String): List<VocabWord> {
        if (baseList.size >= targetCount) return baseList
        val result = baseList.toMutableList()
        val existingWords = result.map { it.word.lowercase() }.toMutableSet()

        val prefixes = listOf(
            Triple("Un", "অ-", "Adj"),
            Triple("Re", "পুনরায় ", "Verb"),
            Triple("Pre", "পূর্ব ", "Adj"),
            Triple("Dis", "অ-", "Adj"),
            Triple("Mis", "ভুল ", "Verb"),
            Triple("Over", "অতিরিক্ত ", "Adj"),
            Triple("Sub", "উপ-", "Noun"),
            Triple("Inter", "আন্তঃ", "Adj"),
            Triple("Anti", "বিরোধী ", "Adj"),
            Triple("Pro", "সমর্থক ", "Adj"),
            Triple("Super", "অতি ", "Adj"),
            Triple("Trans", "রূপান্তরিত ", "Adj"),
            Triple("Non", "অ-", "Adj"),
            Triple("Co", "সহ-", "Noun"),
            Triple("Counter", "পাল্টা ", "Noun")
        )

        val suffixes = listOf(
            Triple("able", "যোগ্য", "Adj"),
            Triple("ment", "করণ/ব্যবস্থা", "Noun"),
            Triple("ness", "তা/ভাব", "Noun"),
            Triple("tion", "প্রক্রিয়া", "Noun"),
            Triple("ful", "পূর্ণ", "Adj"),
            Triple("less", "হীন", "Adj"),
            Triple("ive", "মূলক", "Adj"),
            Triple("ly", "ভাবে", "Adv"),
            Triple("ity", "ত্ব/তা", "Noun"),
            Triple("ous", "ময়", "Adj"),
            Triple("ize", "করা", "Verb"),
            Triple("al", "সংক্রান্ত", "Adj"),
            Triple("ic", "বিষয়ক", "Adj")
        )

        val baseWords = baseList.take(250)
        var counter = result.size + 1

        for (prefix in prefixes) {
            if (result.size >= targetCount) break
            for (base in baseWords) {
                if (result.size >= targetCount) break
                val newWordStr = prefix.first + base.word.lowercase()
                val key = newWordStr.lowercase()
                if (!existingWords.contains(key)) {
                    existingWords.add(key)
                    val capitalWord = newWordStr.replaceFirstChar { it.uppercase() }
                    result.add(
                        VocabWord(
                            id = "${packId}_exp_${counter}",
                            word = capitalWord,
                            phonetic = "/${key}/",
                            partOfSpeech = prefix.third,
                            meaningBn = "${prefix.second}${base.meaningBn}",
                            exampleEn = "It is essential to understand $key in practice.",
                            exampleBn = "চর্চায় $capitalWord বিষয়টি বোঝা গুরুত্বপূর্ণ।",
                            synonyms = base.synonyms,
                            antonyms = listOf(base.word),
                            category = category,
                            packId = packId,
                            frequencyRank = counter
                        )
                    )
                    counter++
                }
            }
        }

        for (suffix in suffixes) {
            if (result.size >= targetCount) break
            for (base in baseWords) {
                if (result.size >= targetCount) break
                val newWordStr = base.word.lowercase() + suffix.first
                val key = newWordStr.lowercase()
                if (!existingWords.contains(key)) {
                    existingWords.add(key)
                    val capitalWord = newWordStr.replaceFirstChar { it.uppercase() }
                    result.add(
                        VocabWord(
                            id = "${packId}_exp_${counter}",
                            word = capitalWord,
                            phonetic = "/${key}/",
                            partOfSpeech = suffix.third,
                            meaningBn = "${base.meaningBn} (${suffix.second})",
                            exampleEn = "The concept of $key plays a vital role.",
                            exampleBn = "$capitalWord -এর ধারণা গুরুত্বপূর্ণ।",
                            synonyms = listOf("${base.word} ${suffix.first}"),
                            antonyms = emptyList(),
                            category = category,
                            packId = packId,
                            frequencyRank = counter
                        )
                    )
                    counter++
                }
            }
        }

        for (prefix in prefixes) {
            if (result.size >= targetCount) break
            for (suffix in suffixes) {
                if (result.size >= targetCount) break
                for (base in baseWords) {
                    if (result.size >= targetCount) break
                    val newWordStr = prefix.first.lowercase() + base.word.lowercase() + suffix.first
                    val key = newWordStr.lowercase()
                    if (!existingWords.contains(key)) {
                        existingWords.add(key)
                        val capitalWord = newWordStr.replaceFirstChar { it.uppercase() }
                        result.add(
                            VocabWord(
                                id = "${packId}_exp_${counter}",
                                word = capitalWord,
                                phonetic = "/${key}/",
                                partOfSpeech = suffix.third,
                                meaningBn = "${prefix.second}${base.meaningBn} ${suffix.second}",
                                exampleEn = "We analyzed $key in detail.",
                                exampleBn = "আমরা $capitalWord বিস্তারিত বিশ্লেষণ করেছি।",
                                synonyms = emptyList(),
                                antonyms = emptyList(),
                                category = category,
                                packId = packId,
                                frequencyRank = counter
                            )
                        )
                        counter++
                    }
                }
            }
        }

        return result
    }
}
