package com.example.ui.screens.tools

object VocabularyDataPacks {

    val starterWords: List<VocabWord> = listOf(
        VocabWord("sw_1", "Resilient", "/rɪˈzɪl.jənt/", "Adj", "স্থিতিস্থাপক, প্রতিকূলতা জয় করতে সক্ষম", "She is resilient and never gives up.", "তিনি দৃঢ়চেতা এবং কখনো হার মানেন না।", listOf("Tough", "Strong", "Flexible"), listOf("Fragile", "Weak"), "IELTS", "starter"),
        VocabWord("sw_2", "Eloquent", "/ˈel.ə.kwənt/", "Adj", "বাকপটু, আকর্ষণীয় ও মার্জিত বক্তা", "He gave an eloquent speech at the seminar.", "তিনি সেমিনারে একটি চমৎকার ও প্রাঞ্জল বক্তব্য দেন।", listOf("Fluent", "Articulate", "Expressive"), listOf("Inarticulate", "Hesitant"), "Spoken", "starter"),
        VocabWord("sw_3", "Meticulous", "/məˈtɪk.jə.ləs/", "Adj", "খুঁতখুঁতে, অত্যন্ত সতর্ক ও নিখুঁত", "He is meticulous about his code quality.", "তিনি তার কোডের মানের ব্যাপারে অত্যন্ত সতর্ক।", listOf("Precise", "Thorough", "Detailed"), listOf("Careless", "Sloppy"), "Academic", "starter"),
        VocabWord("sw_4", "Pragmatic", "/præɡˈmæt.ɪk/", "Adj", "বাস্তবধর্মী, বাস্তববাদী", "We need a pragmatic solution to this problem.", "এই সমস্যার জন্য আমাদের একটি বাস্তবমুখী সমাধান দরকার।", listOf("Practical", "Realistic", "Sensible"), listOf("Idealistic", "Impractical"), "BCS", "starter"),
        VocabWord("sw_5", "Perseverance", "/ˌpɜː.sɪˈvɪə.rəns/", "Noun", "অধ্যবসায়, নিরবচ্ছিন্ন প্রচেষ্টা", "Success comes through patience and perseverance.", "ধৈর্য ও অধ্যবসায়ের মাধ্যমেই সাফল্য আসে।", listOf("Persistence", "Dedication", "Tenacity"), listOf("Apathy", "Laziness"), "IELTS", "starter"),
        VocabWord("sw_6", "Ambiguous", "/æmˈbɪɡ.ju.əs/", "Adj", "দ্ব্যর্থবোধক, অস্পষ্ট", "The instructions were confusing and ambiguous.", "নির্দেশনাগুলো বিভ্রান্তিকর ও অস্পষ্ট ছিল।", listOf("Vague", "Unclear", "Obscure"), listOf("Clear", "Definite", "Lucid"), "BCS", "starter"),
        VocabWord("sw_7", "Inevitable", "/ɪˈnev.ɪ.tə.bəl/", "Adj", "অনিবার্য, যা এড়ানো যায় না", "Change is an inevitable part of life.", "পরিবর্তন জীবনের একটি অনিবার্য অংশ।", listOf("Unavoidable", "Certain", "Inescapable"), listOf("Avoidable", "Uncertain"), "Academic", "starter"),
        VocabWord("sw_8", "Benevolent", "/bəˈnev.əl.ənt/", "Adj", "দয়াবান, পরোপকারী", "A benevolent gentleman donated to the orphanage.", "একজন দয়ালু ব্যক্তি এতিমখানায় অনুদান দিয়েছেন।", listOf("Kind", "Generous", "Altruistic"), listOf("Malevolent", "Cruel", "Selfish"), "Spoken", "starter"),
        VocabWord("sw_9", "Ubiquitous", "/juːˈbɪk.wɪ.təs/", "Adj", "সর্বব্যাপী, যা সর্বত্র বিদ্যমান", "Smartphones have become ubiquitous today.", "স্মার্টফোন আজকাল সর্বত্র ছড়িয়ে পড়েছে।", listOf("Omnipresent", "Everywhere", "Pervasive"), listOf("Rare", "Scarce"), "IELTS", "starter"),
        VocabWord("sw_10", "Candid", "/ˈkæn.dɪd/", "Adj", "অকপট, স্পষ্টবাদী ও সৎ", "She gave her candid opinion on the proposal.", "প্রস্তাবটির বিষয়ে তিনি তার অকপট মতামত দিয়েছেন।", listOf("Frank", "Honest", "Direct"), listOf("Deceitful", "Shy", "Guarded"), "Spoken", "starter"),
        VocabWord("sw_11", "Diligence", "/ˈdɪl.ɪ.dʒəns/", "Noun", "পরিশ্রম, নিষ্ঠা", "His diligence earned him the promotion.", "তার নিষ্ঠা ও পরিশ্রম তাকে পদোন্নতি এনে দিয়েছিল।", listOf("Hard work", "Industriousness", "Assiduousness"), listOf("Laziness", "Neglect"), "BCS", "starter"),
        VocabWord("sw_12", "Alleviate", "/əˈliː.vi.eɪt/", "Verb", "উপশম করা, তীব্রতা কমানো", "Medicine helps alleviate physical pain.", "ওষুধ শারীরিক ব্যথা উপশমে সহায়তা করে।", listOf("Relieve", "Ease", "Reduce"), listOf("Aggravate", "Worsen"), "IELTS", "starter"),
        VocabWord("sw_13", "Lucid", "/ˈluː.sɪd/", "Adj", "স্পষ্ট, সহজে বোধগম্য", "The professor gave a lucid explanation.", "অধ্যাপক অত্যন্ত প্রাঞ্জল ব্যাখ্যা দিয়েছিলেন।", listOf("Clear", "Transparent", "Coherent"), listOf("Confusing", "Vague"), "Academic", "starter"),
        VocabWord("sw_14", "Fortitude", "/ˈfɔː.tɪ.tʃuːd/", "Noun", "মানসিক শক্তি, বিপদে অটল থাকা", "She endured the hardship with great fortitude.", "তিনি অত্যন্ত মানসিক শক্তির সাথে কষ্ট সহ্য করেছিলেন।", listOf("Courage", "Bravery", "Endurance"), listOf("Fear", "Cowardice"), "BCS", "starter"),
        VocabWord("sw_15", "Spontaneous", "/spɒnˈteɪ.ni.əs/", "Adj", "স্বতঃস্ফূর্ত, স্বাভাবিক", "The audience gave a spontaneous applause.", "দর্শকরা স্বতঃস্ফূর্ত করতালিতে মেতে উঠেছিল।", listOf("Natural", "Unplanned", "Impulsive"), listOf("Forced", "Planned"), "Spoken", "starter"),
        VocabWord("sw_16", "Comprehensive", "/ˌkɒm.prɪˈhen.sɪv/", "Adj", "বিস্তৃত, সর্বাঙ্গীণ, পূর্ণাঙ্গ", "The book offers a comprehensive guide to science.", "বইটি বিজ্ঞানের একটি পূর্ণাঙ্গ নির্দেশিকা দেয়।", listOf("Complete", "Exhaustive", "Broad"), listOf("Limited", "Partial"), "Academic", "starter"),
        VocabWord("sw_17", "Versatile", "/ˈvɜː.sə.taɪl/", "Adj", "বহুমুখী প্রতিভাধর, বহু কাজে সক্ষম", "He is a versatile actor and singer.", "তিনি একজন বহুমুখী অভিনেতা ও সংগীতশিল্পী।", listOf("Multitalented", "Adaptable", "Flexible"), listOf("Inflexible", "Limited"), "Spoken", "starter"),
        VocabWord("sw_18", "Empathy", "/ˈem.pə.θi/", "Noun", "সহমর্মিতা, অন্যের অনুভূতি উপলব্ধি করার ক্ষমতা", "True leadership requires genuine empathy.", "প্রকৃত নেতৃত্বের জন্য সত্যিকারের সহমর্মিতা প্রয়োজন।", listOf("Compassion", "Understanding", "Sympathy"), listOf("Indifference", "Callousness"), "IELTS", "starter"),
        VocabWord("sw_19", "Feasible", "/ˈfiː.zə.bəl/", "Adj", "বাস্তবায়নযোগ্য, সম্ভবপর", "Is this project practically feasible within budget?", "বাজেটের মধ্যে এই প্রজেক্টটি বাস্তবায়নযোগ্য কি?", listOf("Workable", "Viable", "Achievable"), listOf("Impossible", "Unrealistic"), "BCS", "starter"),
        VocabWord("sw_20", "Piece of Cake", "/piːs əv keɪk/", "Idiom", "খুবই সহজ কাজ (দুধভাত)", "The exam was a piece of cake for him.", "পরীক্ষাটি তার জন্য খুবই সহজ ছিল।", listOf("Easy task", "Child's play", "Simple"), listOf("Uphill task", "Hard"), "Idioms", "starter"),
        VocabWord("sw_21", "Break the Ice", "/breɪk ði aɪs/", "Idiom", "আড়ষ্টতা বা নীরবতা ভেঙে কথা শুরু করা", "A small joke helped break the ice.", "ছোট একটি কৌতুক পরিবেশের আড়ষ্টতা ভাঙতে সাহায্য করেছিল।", listOf("Initiate", "Warm up", "Start talking"), listOf("Stay silent"), "Idioms", "starter"),
        VocabWord("sw_22", "Once in a Blue Moon", "/wʌns ɪn ə bluː muːn/", "Idiom", "কদাচিৎ, খুব বিরল ঘটনা", "He visits his hometown once in a blue moon.", "সে খুব বিরল সময়ে গ্রামের বাড়িতে যায়।", listOf("Rarely", "Seldom", "Infrequently"), listOf("Frequently", "Often"), "Idioms", "starter"),
        VocabWord("sw_23", "Pinnacle", "/ˈpɪn.ə.kəl/", "Noun", "চূড়া, সর্বোচ্চ শিখর", "He reached the pinnacle of his career.", "তিনি তার ক্যারিয়ারের সর্বোচ্চ শিখরে পৌঁছেছিলেন।", listOf("Peak", "Summit", "Apex", "Zenith"), listOf("Bottom", "Nadir"), "BCS", "starter"),
        VocabWord("sw_24", "Scrutinize", "/ˈskruː.tɪ.naɪz/", "Verb", "সূক্ষ্মভাবে পরীক্ষা করা", "The auditors scrutinized every transaction.", "অডিটররা প্রতিটি লেনদেন গভীরভাবে পরীক্ষা করেছেন।", listOf("Examine", "Inspect", "Analyze"), listOf("Ignore", "Overlook"), "IELTS", "starter"),
        VocabWord("sw_25", "Tenacious", "/təˈneɪ.ʃəs/", "Adj", "নাছোড়বান্দা, সংকল্পবদ্ধ", "He is a tenacious researcher.", "তিনি একজন অদম্য ও নাছোড় গবেষক।", listOf("Persistent", "Determined", "Dogged"), listOf("Yielding", "Weak"), "Academic", "starter")
    )

    val spokenWords: List<VocabWord> = listOf(
        VocabWord("sp_1", "Accommodate", "/əˈkɒm.ə.deɪt/", "Verb", "স্থান দেওয়া, মানিয়ে নেওয়া", "The hotel can accommodate 200 guests.", "হোটেলটিতে ২০০ জন অতিথি থাকতে পারবেন।", listOf("House", "Adapt", "Welcome"), listOf("Reject"), "Spoken", "spoken_3000"),
        VocabWord("sp_2", "Apparent", "/əˈpær.ənt/", "Adj", "দৃশ্যমান, সুস্পষ্ট", "Her happiness was apparent to everyone.", "তার আনন্দ সবার কাছে সুস্পষ্ট ছিল।", listOf("Evident", "Obvious", "Clear"), listOf("Hidden", "Obscure"), "Spoken", "spoken_3000"),
        VocabWord("sp_3", "Acknowledge", "/əkˈnɒl.ɪdʒ/", "Verb", "স্বীকার করা, স্বীকৃতি দেওয়া", "He refused to acknowledge his mistake.", "তিনি তার ভুল স্বীকার করতে রাজি হননি।", listOf("Admit", "Accept", "Recognize"), listOf("Deny", "Refuse"), "Spoken", "spoken_3000"),
        VocabWord("sp_4", "Casual", "/ˈkæʒ.u.əl/", "Adj", "অনানুষ্ঠানিক, সাধারণ", "Wear casual clothes for the picnic.", "পিকনিকের জন্য সাধারণ জামাকাপড় পরুন।", listOf("Informal", "Relaxed", "Everyday"), listOf("Formal", "Official"), "Spoken", "spoken_3000"),
        VocabWord("sp_5", "Cooperate", "/kəʊˈɒp.ər.eɪt/", "Verb", "সহযোগিতা করা", "All neighbors cooperated to clean the area.", "এলাকা পরিষ্কার করতে সব প্রতিবেশী সহযোগিতা করেছিলেন।", listOf("Collaborate", "Assist", "Unite"), listOf("Hinder", "Oppose"), "Spoken", "spoken_3000"),
        VocabWord("sp_6", "Enthusiastic", "/ɪnˌθjuː.ziˈæs.tɪk/", "Adj", "উৎসাহী, উদ্দীপ্ত", "Students were enthusiastic about the trip.", "ভ্রমণের ব্যাপারে ছাত্রছাত্রীরা খুব উৎসাহী ছিল।", listOf("Eager", "Excited", "Keen"), listOf("Indifferent", "Bored"), "Spoken", "spoken_3000"),
        VocabWord("sp_7", "Hesitate", "/ˈhez.ɪ.teɪt/", "Verb", "দ্বিধা করা, ইতস্তত করা", "Do not hesitate to ask any question.", "যেকোনো প্রশ্ন করতে দ্বিধা করবেন না।", listOf("Waver", "Pause", "Delay"), listOf("Proceed", "Decide"), "Spoken", "spoken_3000"),
        VocabWord("sp_8", "Intriguing", "/ɪnˈtriː.ɡɪŋ/", "Adj", "কৌতূহলোদ্দীপক, আকর্ষণীয়", "She told an intriguing story.", "তিনি একটি চমৎকার কৌতূহলোদ্দীপক গল্প শোনালেন।", listOf("Fascinating", "Interesting", "Captivating"), listOf("Boring", "Dull"), "Spoken", "spoken_3000"),
        VocabWord("sp_9", "Reliable", "/rɪˈlaɪ.ə.bəl/", "Adj", "নির্ভরযোগ্য, বিশ্বাসযোগ্য", "He is a reliable friend in hard times.", "কঠিন সময়ে তিনি একজন নির্ভরযোগ্য বন্ধু।", listOf("Trustworthy", "Dependable", "Steadfast"), listOf("Unreliable", "Shaky"), "Spoken", "spoken_3000"),
        VocabWord("sp_10", "Spill the Beans", "/spɪl ðə biːnz/", "Idiom", "গোপন কথা ফাঁস করে দেওয়া", "Do not spill the beans about the surprise party.", "সারপ্রাইজ পার্টির গোপন কথা ফাঁস করো না।", listOf("Reveal secret", "Blab"), listOf("Keep secret"), "Idioms", "spoken_3000"),
        VocabWord("sp_11", "Catch Up", "/kætʃ ʌp/", "Phrasal Verb", "যোগাযোগ করা, পুরনো কথা সেরে নেওয়া", "Let's catch up over a cup of tea tomorrow.", "চলুন আগামীকাল এক কাপ চা খেতে খেতে আড্ডা দিয়ে নেই।", listOf("Reconnect", "Meet up"), listOf(), "Spoken", "spoken_3000"),
        VocabWord("sp_12", "Hang Out", "/hæŋ aʊt/", "Phrasal Verb", "বন্ধুদের সাথে সময় কাটানো বা ঘোরাঘুরি", "They love to hang out at the park after class.", "ক্লাসের পর তারা পার্কে আড্ডা দিতে পছন্দ করে।", listOf("Socialize", "Spend time"), listOf(), "Spoken", "spoken_3000"),
        VocabWord("sp_13", "Bite the Bullet", "/baɪt ðə ˈbʊl.ɪt/", "Idiom", "অপ্রিয় হলেও অনিবার্য পরিস্থিতি মেনে নেওয়া", "I had to bite the bullet and apologize.", "আমাকে বাধ্য হয়েই ক্ষমা চেয়ে নিতে হয়েছিল।", listOf("Face reality", "Endure"), listOf(), "Idioms", "spoken_3000"),
        VocabWord("sp_14", "Appreciate", "/əˈpriː.ʃi.eɪt/", "Verb", "প্রশংসা করা, কৃতজ্ঞতা প্রকাশ করা", "I deeply appreciate your kind support.", "আপনার আন্তরিক সহযোগিতার জন্য আমি গভীরভাবে কৃতজ্ঞ।", listOf("Value", "Acknowledge"), listOf("Depreciate"), "Spoken", "spoken_3000"),
        VocabWord("sp_15", "Comfortable", "/ˈkʌm.fə.tə.bəl/", "Adj", "আরামদায়ক, স্বাচ্ছন্দ্যময়", "Make yourself comfortable on the sofa.", "সোফায় আরাম করে বসুন।", listOf("Cozy", "Relaxing"), listOf("Uncomfortable"), "Spoken", "spoken_3000"),
        VocabWord("sp_16", "Generous", "/ˈdʒen.ər.əs/", "Adj", "উদার, দানশীল", "He is generous to those in distress.", "বিপদগ্রস্ত মানুষের প্রতি তিনি অত্যন্ত উদার।", listOf("Bountiful", "Giving"), listOf("Stingy", "Mean"), "Spoken", "spoken_3000"),
        VocabWord("sp_17", "Grateful", "/ˈɡreɪt.fəl/", "Adj", "কৃতজ্ঞ", "We are grateful for all your help.", "আপনার সকল সাহায্যের জন্য আমরা কৃতজ্ঞ।", listOf("Thankful", "Appreciative"), listOf("Ungrateful"), "Spoken", "spoken_3000"),
        VocabWord("sp_18", "Hesitation", "/ˌhez.ɪˈteɪ.ʃən/", "Noun", "দ্বিধাদ্বন্দ্ব, ইতস্তত ভাব", "Without any hesitation, she jumped in.", "কোনো দ্বিধা ছাড়াই সে ঝাঁপিয়ে পড়েছিল।", listOf("Reluctance", "Doubt"), listOf("Certainty"), "Spoken", "spoken_3000"),
        VocabWord("sp_19", "Gorgeous", "/ˈɡɔː.dʒəs/", "Adj", "অপূর্ব সুন্দর, নয়নাভিরাম", "The sunset over the river looked gorgeous.", "নদীর ওপর সূর্যাস্ত দেখতে অপূর্ব সুন্দর ছিল।", listOf("Stunning", "Magnificent"), listOf("Ugly"), "Spoken", "spoken_3000"),
        VocabWord("sp_20", "Patience", "/ˈpeɪ.ʃəns/", "Noun", "ধৈর্য, সহনশীলতা", "Teaching children requires plenty of patience.", "শিশুদের পড়াতে প্রচুর ধৈর্যের প্রয়োজন হয়।", listOf("Endurance", "Tolerance"), listOf("Impatience"), "Spoken", "spoken_3000")
    )

    val ieltsWords: List<VocabWord> = listOf(
        VocabWord("ie_1", "Aberration", "/ˌæb.əˈreɪ.ʃən/", "Noun", "স্বাভাবিক নিয়মের বিচ্যুতি বা ব্যতিক্রম", "The sudden cold wave was an aberration.", "হঠাৎ শৈত্যপ্রবাহ ছিল আবহাওয়ার একটি ব্যতিক্রম।", listOf("Anomaly", "Deviation", "Divergence"), listOf("Normality", "Conformity"), "IELTS", "ielts_4000"),
        VocabWord("ie_2", "Proponent", "/prəˈpəʊ.nənt/", "Noun", "সমর্থক, প্রবক্তা", "He is a strong proponent of renewable energy.", "তিনি নবায়নযোগ্য শক্তির একজন প্রবল সমর্থক।", listOf("Advocate", "Supporter", "Champion"), listOf("Opponent", "Critic"), "IELTS", "ielts_4000"),
        VocabWord("ie_3", "Exacerbate", "/ɪɡˈzæs.ə.beɪt/", "Verb", "পরিস্থিতি আরও খারাপ বা অবনতি করা", "Pollution exacerbates respiratory diseases.", "দূষণ শ্বাসকষ্টের রোগকে আরও বাড়িয়ে দেয়।", listOf("Worsen", "Aggravate", "Intensify"), listOf("Improve", "Alleviate"), "IELTS", "ielts_4000"),
        VocabWord("ie_4", "Mitigate", "/ˈmɪt.ɪ.ɡeɪt/", "Verb", "প্রশমিত করা, হ্রাস করা", "Planting trees helps mitigate global warming.", "গাছ লাগানো গ্লোবাল ওয়ার্মিং কমাতে সাহায্য করে।", listOf("Lessen", "Diminish", "Ease"), listOf("Intensify", "Aggravate"), "IELTS", "ielts_4000"),
        VocabWord("ie_5", "Substantiate", "/səbˈstæn.ʃi.eɪt/", "Verb", "প্রমাণ দিয়ে প্রতিষ্ঠা করা বা সত্যতা প্রতিপন্ন করা", "You must substantiate your thesis with data.", "আপনার থিসিস তথ্যের সাহায্যে প্রমাণ করতে হবে।", listOf("Verify", "Validate", "Corroborate"), listOf("Disprove", "Refute"), "IELTS", "ielts_4000"),
        VocabWord("ie_6", "Prevalent", "/ˈprev.əl.ənt/", "Adj", "বহুল প্রচলিত, বিদ্যমান", "The custom is still prevalent in rural areas.", "প্রথাটি গ্রামাঞ্চলে এখনও প্রচলিত।", listOf("Widespread", "Common", "Rife"), listOf("Rare", "Scarce"), "IELTS", "ielts_4000"),
        VocabWord("ie_7", "Plausible", "/ˈplɔː.zə.bəl/", "Adj", "বিশ্বাসযোগ্য, যুক্তিযুক্ত", "Her explanation sounded plausible.", "তার ব্যাখ্যাটি যুক্তিযুক্ত মনে হয়েছিল।", listOf("Believable", "Reasonable", "Credible"), listOf("Implausible", "Unlikely"), "IELTS", "ielts_4000"),
        VocabWord("ie_8", "Paradigm", "/ˈpær.ə.daɪm/", "Noun", "দৃষ্টান্ত, আদর্শ কাঠামো বা মডেল", "AI represents a paradigm shift in technology.", "এআই প্রযুক্তিতে একটি আদর্শ কাঠামোগত পরিবর্তন এনেছে।", listOf("Model", "Pattern", "Archetype"), listOf(), "IELTS", "ielts_4000"),
        VocabWord("ie_9", "Cognizant", "/ˈkɒɡ.nɪ.zənt/", "Adj", "সচেতন, অবহিত", "Statesmen must be cognizant of citizens' rights.", "রাষ্ট্রনেতাদের নাগরিকদের অধিকার সম্পর্কে সচেতন হতে হবে।", listOf("Aware", "Conscious", "Mindful"), listOf("Ignorant", "Unaware"), "IELTS", "ielts_4000"),
        VocabWord("ie_10", "Dichotomy", "/daɪˈkɒt.ə.mi/", "Noun", "দ্বিখণ্ডতা, পরস্পরবিরোধী দুই ভাগের বিভাজন", "There is a strict dichotomy between theory and practice.", "তত্ত্ব এবং প্রায়োগিক দিকের মধ্যে স্পষ্ট দ্বিখণ্ডতা বিদ্যমান।", listOf("Division", "Split", "Contrast"), listOf("Harmony", "Unity"), "IELTS", "ielts_4000"),
        VocabWord("ie_11", "Discrepancy", "/dɪˈskrep.ən.si/", "Noun", "অমিল, অসঙ্গতি", "The accountant noticed a huge discrepancy in figures.", "হিসাবরক্ষক তথ্যের মধ্যে বিশাল অসঙ্গতি লক্ষ্য করেন।", listOf("Mismatch", "Inconsistency"), listOf("Consistency", "Accord"), "IELTS", "ielts_4000"),
        VocabWord("ie_12", "Exemplary", "/ɪɡˈzem.plər.i/", "Adj", "দৃষ্টান্তমূলক, অনুসরণীয়", "She showed exemplary dedication to her research.", "তিনি গবেষণায় দৃষ্টান্তমূলক নিষ্ঠা প্রদর্শন করেছেন।", listOf("Model", "Praiseworthy"), listOf("Unworthy", "Poor"), "IELTS", "ielts_4000"),
        VocabWord("ie_13", "Nuance", "/ˈnjuː.ɑːns/", "Noun", "সুক্ষ্ম পার্থক্য বা তারতম্য", "He understood every nuance of the legal argument.", "আইনি যুক্তির প্রতিটি সূক্ষ্ম বিষয় তিনি অনুধাবন করেছিলেন।", listOf("Subtlety", "Fine distinction"), listOf(), "IELTS", "ielts_4000"),
        VocabWord("ie_14", "Precedent", "/ˈpres.ɪ.dənt/", "Noun", "নজির, পূর্বদৃষ্টান্ত", "The court decision set a historic precedent.", "আদালতের রায়টি একটি ঐতিহাসিক নজির স্থাপন করেছে।", listOf("Example", "Prior instance"), listOf(), "IELTS", "ielts_4000"),
        VocabWord("ie_15", "Resilience", "/rɪˈzɪl.jəns/", "Noun", "স্থিতিস্থাপকতা, ঘুরে দাঁড়ানোর ক্ষমতা", "The nation showed incredible economic resilience.", "দেশটি অসাধারণ অর্থনৈতিক ঘুরে দাঁড়ানোর ক্ষমতা দেখিয়েছে।", listOf("Toughness", "Adaptability"), listOf("Fragility"), "IELTS", "ielts_4000")
    )

    val bcsWords: List<VocabWord> = listOf(
        VocabWord("bc_1", "Ephemeral", "/ɪˈfem.ər.əl/", "Adj", "ক্ষণস্থায়ী, অল্পকালব্যাপী", "Fame in social media is often ephemeral.", "সোশ্যাল মিডিয়ার খ্যাতি প্রায়শই ক্ষণস্থায়ী।", listOf("Fleeting", "Transient", "Short-lived"), listOf("Permanent", "Eternal", "Perpetual"), "BCS", "bcs_5000"),
        VocabWord("bc_2", "Fastidious", "/fæsˈtɪd.i.əs/", "Adj", "খুঁতখুঁতে, সহজে সন্তুষ্ট হয় না এমন", "He is fastidious regarding hygiene.", "পরিচ্ছন্নতার বিষয়ে তিনি অত্যন্ত খুঁতখুঁতে।", listOf("Picky", "Fussy", "Overcritical"), listOf("Careless", "Easygoing"), "BCS", "bcs_5000"),
        VocabWord("bc_3", "Gregarious", "/ɡrɪˈɡeə.ri.əs/", "Adj", "মিশুক, দলপ্রিয়, সামাজপ্রিয়", "Dolphins are friendly and gregarious animals.", "ডলফিন বন্ধুভাবাপন্ন এবং দলপ্রিয় প্রাণী।", listOf("Sociable", "Outgoing", "Companionable"), listOf("Solitary", "Introverted"), "BCS", "bcs_5000"),
        VocabWord("bc_4", "Magnanimous", "/mæɡˈnæn.ɪ.məs/", "Adj", "মহানুভব, উদারচেতা", "He was magnanimous in victory.", "বিজয়ের পর তিনি মহানুভবতা প্রদর্শন করেছিলেন।", listOf("Generous", "Noble", "Forgiving"), listOf("Selfish", "Petty", "Vindictive"), "BCS", "bcs_5000"),
        VocabWord("bc_5", "Sycophant", "/ˈsɪk.ə.fænt/", "Noun", "চাটুকার, তোষামোদকারী", "The king was surrounded by flattering sycophants.", "রাজা স্তাবক চাটুকারদের দ্বারা পরিবেষ্টিত ছিলেন।", listOf("Flatterer", "Toady", "Fawner"), listOf("Critic", "Rebel"), "BCS", "bcs_5000"),
        VocabWord("bc_6", "Venerate", "/ˈven.ər.eɪt/", "Verb", "গভীর শ্রদ্ধা করা, পূজা করা", "We venerate our freedom fighters.", "আমরা আমাদের বীর মুক্তিযোদ্ধাদের পরম শ্রদ্ধায় স্মরণ করি।", listOf("Revere", "Respect", "Worship"), listOf("Despise", "Disdain"), "BCS", "bcs_5000"),
        VocabWord("bc_7", "Acumen", "/ˈæk.jə.mən/", "Noun", "তীক্ষ্ণ বুদ্ধি, বিচক্ষণতা", "Her business acumen made the company profitable.", "তার ব্যবসায়িক বিচক্ষণতা প্রতিষ্ঠানটিকে লাভবান করেছে।", listOf("Shrewdness", "Sharpness", "Insight"), listOf("Stupidity", "Ignorance"), "BCS", "bcs_5000"),
        VocabWord("bc_8", "Cacophony", "/kəˈkɒf.ə.ni/", "Noun", "কর্কশ কোলাহল বা বেসুরো শব্দ", "The cacophony of street horns was unbearable.", "রাস্তার গাড়ির হর্নের কর্কশ শব্দ অসহ্য ছিল।", listOf("Noise", "Discord", "Din"), listOf("Harmony", "Melody"), "BCS", "bcs_5000"),
        VocabWord("bc_9", "Enigma", "/ɪˈnɪɡ.mə/", "Noun", "রহস্য, ধাঁধা", "His mysterious disappearance remains an enigma.", "তার রহস্যজনক অন্তর্ধান এখনও একটি ধাঁধা হয়ে আছে।", listOf("Puzzle", "Mystery", "Riddle"), listOf("Clarity", "Explanation"), "BCS", "bcs_5000"),
        VocabWord("bc_10", "Loquacious", "/ləˈkweɪ.ʃəs/", "Adj", "বাচাল, অতিরিক্ত কথা বলা স্বভাব", "The loquacious passenger talked during the whole flight.", "বাচাল যাত্রীটি পুরো ফ্লাইটেই অবিরাম কথা বলে গেলেন।", listOf("Talkative", "Chatty", "Voluble"), listOf("Taciturn", "Silent"), "BCS", "bcs_5000"),
        VocabWord("bc_11", "Superfluous", "/suːˈpɜː.flu.əs/", "Adj", "প্রয়োজনাতিরিক্ত, বাড়তি", "Delete all superfluous words to make it concise.", "সংক্ষিপ্ত করতে অপ্রয়োজনীয় বাড়তি শব্দগুলো কেটে দিন।", listOf("Redundant", "Excessive", "Surplus"), listOf("Essential", "Necessary"), "BCS", "bcs_5000"),
        VocabWord("bc_12", "Zealous", "/ˈzel.əs/", "Adj", "উৎসাহী, পরম নিষ্ঠাবান", "She was a zealous worker for human rights.", "মানবাধিকার রক্ষায় তিনি ছিলেন অত্যন্ত একনিষ্ঠ কর্মী।", listOf("Ardent", "Passionate", "Devoted"), listOf("Apathetic", "Indifferent"), "BCS", "bcs_5000")
    )

    val megaWords: List<VocabWord> = listOf(
        VocabWord("mg_1", "Anachronism", "/əˈnæk.rə.nɪ.zəm/", "Noun", "কালবৈষম্য, যুগের সাথে অসংগতি", "A sword in modern warfare is an anachronism.", "আধুনিক যুদ্ধে তরবারি একটি কালবৈষম্য।", listOf("Misplacement", "Chronological error"), listOf(), "Academic", "mega_10000"),
        VocabWord("mg_2", "Capricious", "/kəˈprɪʃ.əs/", "Adj", "খামখেয়ালী, হঠাৎ মত পরিবর্তনশীল", "The island has capricious tropical weather.", "দ্বীপটিতে খামখেয়ালী ধরনের ক্রান্তীয় আবহাওয়া বিরাজ করে।", listOf("Whimsical", "Fickle", "Erratic"), listOf("Predictable", "Stable"), "Academic", "mega_10000"),
        VocabWord("mg_3", "Obsequious", "/əbˈsiː.kwi.əs/", "Adj", "অতি তোষামোদকারী, দাসবৎ অনুগত", "He bowed in an obsequious manner.", "তিনি তোষামোদি ভঙ্গিতে মাথা নত করলেন।", listOf("Servile", "Submissive", "Fawning"), listOf("Assertive", "Independent"), "Academic", "mega_10000"),
        VocabWord("mg_4", "Enervate", "/ˈen.ə.veɪt/", "Verb", "দুর্বল করা, শক্তি হ্রাস করা", "Intense heat enervated the workers.", "তীব্র তাপদাহ কর্মীদের ক্লান্ত ও শক্তিহীন করে ফেলেছিল।", listOf("Weaken", "Exhaust", "Fatigue"), listOf("Energize", "Strengthen"), "Academic", "mega_10000"),
        VocabWord("mg_5", "Assiduous", "/əˈsɪdʒ.u.əs/", "Adj", "অধ্যবসায়ী, অত্যন্ত পরিশ্রমী", "Success came from assiduous study.", "অধ্যবসায়ী পড়াশোনার ফলেই এই সাফল্য এসেছিল।", listOf("Diligent", "Careful", "Industrious"), listOf("Lazy", "Idle"), "Academic", "mega_10000"),
        VocabWord("mg_6", "Castigate", "/ˈkæs.tɪ.ɡeɪt/", "Verb", "তীব্র ভর্ৎসনা বা শাস্তি দেওয়া", "The teacher castigated the unruly students.", "শিক্ষক বিশৃঙ্খল ছাত্রদের তীব্র ভর্ৎসনা করেন।", listOf("Rebuke", "Reprimand", "Chastise"), listOf("Praise", "Commend"), "Academic", "mega_10000"),
        VocabWord("mg_7", "Equanimity", "/ˌek.wəˈnɪm.ə.ti/", "Noun", "চিত্তের প্রশান্তি বা স্থিরতা", "She faced disaster with calmness and equanimity.", "তিনি চরম স্থিরতা ও মানসিক প্রশান্তির সাথে দুর্যোগের মুখোমুখি হন।", listOf("Composure", "Tranquility", "Poise"), listOf("Agitation", "Panic"), "Academic", "mega_10000"),
        VocabWord("mg_8", "Inchoate", "/ɪnˈkəʊ.eɪt/", "Adj", "প্রাথমিক পর্যায়ভুক্ত, অপরিপক্ক", "The startup has an inchoate business strategy.", "স্টার্টআপটির ব্যবসায়িক কৌশল এখনও প্রাথমিক অপরিপক্ক অবস্থায় আছে।", listOf("Rudimentary", "Developing", "Nascent"), listOf("Mature", "Developed"), "Academic", "mega_10000"),
        VocabWord("mg_9", "Juxtaposition", "/ˌdʒʌk.stə.pəˈzɪʃ.ən/", "Noun", "পাশাপাশি রেখে তুলনা", "The juxtaposition of modern and ancient architecture.", "প্রাচীন ও আধুনিক স্থাপত্যকে পাশাপাশি রেখে চমৎকার বৈপরীত্য।", listOf("Comparison", "Collocation"), listOf(), "Academic", "mega_10000"),
        VocabWord("mg_10", "Munificent", "/mjuːˈnɪf.ɪ.sənt/", "Adj", "অতি দানশীল, মহোদয়", "A munificent benefactor saved the library from closure.", "একজন মহৎ দানবীরের বদান্যতায় লাইব্রেরিটি রক্ষা পেয়েছিল।", listOf("Bountiful", "Lavish", "Generous"), listOf("Miserly", "Stingy"), "Academic", "mega_10000"),
        VocabWord("mg_11", "Quixotic", "/kwɪkˈsɒt.ɪk/", "Adj", "বাস্তবজ্ঞানহীন অথচ আদর্শবাদী", "His plan to cure all ills overnight was quixotic.", "রাতারাতি সব সংকট দূর করার তার পরিকল্পনাটি অবাস্তব ছিল।", listOf("Idealistic", "Unrealistic", "Impractical"), listOf("Pragmatic", "Realistic"), "Academic", "mega_10000"),
        VocabWord("mg_12", "Salubrious", "/səˈluː.bri.əs/", "Adj", "স্বাস্থ্যকর, হিতকর", "Mountain air is famously fresh and salubrious.", "পাহাড়ের বিশুদ্ধ বাতাস স্বাস্থ্যকর হিসেবে সুপরিচিত।", listOf("Healthy", "Wholesome", "Beneficial"), listOf("Unhealthy", "Noxious"), "Academic", "mega_10000")
    )
}
