name: Android Release Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '9.3.1'

    - name: Decode Keystore
      id: decode_keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore
        echo "KEYSTORE_PATH=$(pwd)/release.keystore" >> $GITHUB_ENV

    - name: Build with Gradle
      run: gradle assembleRelease --build-cache --parallel
      env:
        KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk
